  # Objective

__Microsoft sees all the big companies creating original video content, and they want to get in on the fun. They have decided to create a new movie studio, but the problem is they don't know anything about creating movies. They have hired you to help them better understand the movie industry. Your team is in charged with doing data analysis that explores what type of films are currently doing the best at the box office. You must then translate
those findings into actionable insights that the CEO can use when deciding what type of films they should be creating.__

# Datasets

There are 10 datasests in this project 

_Name.basics.csv_
  - _Colunms in the dataset_
     - _nconst_
     - _primary_name_
     - _birth_year_
     - _death_year_
     - _primary_profession_
     - _known_for_titles_

_Bom.movie_gross.csv_
   - _Colunms in the dataset_
      - _title_
      - _studio_
      - _domestic_gross_
      - _foreign_gross_
      - _year_
     
_Rt.movie_info.tsv_
   - _Columns in the dataset_
     - _id_
     - _synopsis_
     - _rating_
     - _genre_
     - _director_
     - _writer_
     - _theater_date_
     - _currency_
     - _box_office_
     - _runtime_
     - _studio_
     
_Title.akas.csv_
   - _Columns in the dataset_
     - _title_id_
     - _ordering_
     - _title_
     - _region_
     - _language_
     - _types_
     - _attributes_
     - _is_original_title_
     
_Title.basics.csv_
  - _Columns in the dataset_
    - _tconst_
    - _primary_title_
    - _original_title_
    - _start_year_
    - _runtime_mintues_
    - _genres_
    
_Title.crew.csv_
  - _Columns in the dataset_
    - _tconst_
    - _directors_
    - _writers_
    
_Title.principals.csv_
  - _Columns in the dataset_
    - _tconst_
    - _ordering_
    - _nconst_
    - _category_
    - _job_
    - _charactors_

_Title.ratings.csv_
  - _Columns in the dataset_
    - _tconst_
    - _averagerating_
    - _numvoters_
    
_Tmdb.movies.csv_
  - _Columns in the dataset_
    - _genre_ids_
    - _id_
    - _original_language_
    - _original_title_
    - _popularity_
    - _release_date_
    - _title_
    - _vote_average_
    - _vote_count_
    
_Tn.movie_budgets_
   - _Columns in the dataset_
     - _id_
     - _release_date_
     - _movie_
     - _production_budget_
     - _domestic_gross_
     - _worldwide_gross_

# Approaches

Based on the datasets there are nine main genres; Action and Adventures, Drama, Comedy, Documentry, Classics, Art House and International, Musical and Performing Arts, Horror, Mystrey and Suspense, Animation, Special Interest, Kids and Family and there are also five main System Ratings; System R Rating, System PG-13 Rating, System PG Rating, System G Rating and System NR Rating. In this Project the genres are being split into nine different sections with indivisual data analysis based on the same data visualization concepts and the system ratings are being compared among one another and also analyised to view which one best fit the genres. There will be eleven differnt graphs for each genres describing and protarying insights on the activity of the data.

## Graphs
These are the elven main graphs.
  - __Profit Percentage baised on cost__:
     - This data visualization shows the name, cost, profit, the type of system rating and profit percenatge by cost. The purpose of this notion is to view past the profit and better understand how successful the movie really is by analysing the cost and calculating how much more was made compared to it. This allows the idea of higher profit dosn't mean more profitable to be considered as a justification based on the results proving so. The system rating were added to be compared among eachother, to observe which one was better and to also know which one was the best fit for any particular genere by calculating the average of the reults of each system rating
   
  
  
  - __Gross Profit Margin Percentage__:
     - This data visualization has two pionts about the movie on one panel. The fisrt piont shows the name, amount of profit made in dollars, type of system rating and Gross Profit Margin Percentage. The other piont shows the name, revenue made in dollars and the type of system rating. The graph was designed this way to compare the profit amount against the revenue amount, allowing the Gross Profit Margin Percntage to be more visible and inderectly see the expenses made from a graph perpsective.
     
 
 - __Budget and Revenue of Movies__:
    - This graph is a scatter plot with an x-axis and a y-axis, the x-axis is the revenue of the movies in dollars and the y-axis is the budget of the movies in dollars. This graph is a blueprint to better understand  wether the amount of money spent on the movie effected the amount of revenue generted and to also spot movies that spent less money than the average with a higher revenue.
 
 
 - __Revenue of Movies/Budget of Movies__:
    - The revenue graph has an x-axis that shows the revnue of the movies, name and the type of system ratings with no y-axis. The budget graph has an x-axis that shows the budget of the movies and also the name and system ratings with no y-axis. Both graphs have a table split into catagories of the system ratings showing were they are postions in the axis. These graphs were constructed to predict how much will be made depending on how much is spent based on the pattern of budget of movies to revenue of movies and to indirectly spot anomalies.
    
 
 - __Movies that mdae Profit__:
    - This graph simply shows all the movies that made profit, from the highest to the lowest.


 - __Movies that had losses__:
   - This graph is a colunm graph that shows the movies that did not make any profit. It shows the cost of the movie, revenue and by how much was not made to prevent a loss by the movie. It also shows the name and system ratings it belongs to. This dilema was created to percieve what agenda was not making any money, to try and understand the other half of film industry that is overlooked.
   
   
 
 - __Top 20 Highest Profitable Movies/ Top 20 Lowest Profitable Mobies__:
    - The top 20 highest profitable graph is a 3D chart that shows the top 20 most profitable movies with an x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. The top 20 lowest profitable graph is also a 3D chart that shows the top 20 movies that had the lowest profit, with the x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. These graphs were creted to really spot what movis were the kings and queens of the movie industry and what movie was barely making sales. This brings a lot of questioning to what each of the movies did do britiantally or failed to do.
    

- __Most Successful Moive__:
   - This graph is built up of two sections, the first section is an x-axis whcih shows the names and a y-axis which shows the budget, revenu and profit of the movies in dollars, the second section compares the gross profit margin percentage to the profit percnatge by cost of the movies whcih is all compared to all other movies in the data frame. The sections data is based on the top 20 most profitable movies. The concept of the visualization is to  dive deep into detail to anlayze what movie were actually more succesfull than the other, other than just focusing on the highets profits made. Factors like budget and revenue expressed in gross profit margin percentage and proft percentage by cost allows the differences among the most profitable movies to become more disguishable, whcih can open a new perspcetive on anyalzing numbers.
   
 
 - __Tickets Sold__:
    - This graph simply shows what system ratings have the highest tickets sold to better understand what audience best fist this genre through the sales of the system ratings.

Before starting any data extracting, liabreis such as Altair, Pandas, Pandas_highcharts, Collections need to be installed to help create great insightful interactive graphs.

In [145]:
import altair as alt # used to create interactive graphs
import pandas as pd # used to make for dataframes
import collections# used to put data into sections
import matplotlib.pyplot as plt# used to make graphs

In [146]:
# helps create highcharts graphs
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import json

Before the graphs are made the data is extracted from the rt.movie_info.tsv file and made into a dataframe.

In [147]:
# The data frame is called movie_info
movie_info = pd.read_csv("rt.movie_info.tsv.gz",error_bad_lines=False,sep='\t')

In [19]:
movie_info.head()

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN

In [363]:
# Getting first 500 movies 
first_500 = []
for i in movie_info.genre[:500].dropna():
    first_500.append(i)
len(first_500)

496

The movies form the data frame have been selected and put into genres groups for the first 500 movies

In [364]:
# putting movies into groups
grouped_500 = []
for i in first_500:
    grouped_500.append(i.split('|',1)[0])
grouped_500=collections.Counter(grouped_500)
grouped_500

Counter({'Action and Adventure': 117,
         'Drama': 103,
         'Comedy': 115,
         'Documentary': 11,
         'Classics': 53,
         'Art House and International': 55,
         'Musical and Performing Arts': 3,
         'Horror': 23,
         'Mystery and Suspense': 7,
         'Animation': 6,
         'Special Interest': 2,
         'Kids and Family': 1})

# Blueprint: Profit Percentage Based on Cost

The amount of movies in the genre groups are all uneven, the goal through out the project is to make sure they all have the same amount of movies that are being analyzed to give it a fair comparison which will be done later on in the project.

The next step is to choose a genre to select and start analyzing. For this section Action and Adventure is being analyzed.

This is the blueprint for creating the first visualization Profit Percentage by cost, bokeh will be used to create these graphs.
Blueprint:
 1. Create a new dataframe for the graph, the dataframe columns will consist of these key infomation of the moives in the Action and Adventure Genre;
    - The Names 
    - Product Budget 
    - System Ratings 
    - Ratings 
    - Domestic Gross 
    - World Wide Gross
    - Profit
    - No. of Tickets
    - Product Budget in integers
    - Profit in integers
    - Total Gross in integers
    - Domestic total in integers
 
 
 2. Install bokeh and create the componets needed for the format of the code script for the graph.There will be five graphs and in each graph are key information of the movies based on the same system rating which are R, PG-13, PG, G and NR. These are the key componets needed in each graph based on the same system rating;
    - X-axis Range
    - Y-axis Range
    - Name
    - Profit in integers
    - System Rating
    - Percentage Profit by Cost
    - Cost


3. The graphs has to have visual componets that convey the information smoothly and also differentiate from one another due to that fact that they are all in groups, these are the formats to help do so; 
    - Color
    - Tooltips (make the graph interactive)
    - Type and shape of pionts in the graph

Below is the code script used to create a new dataframe needed for the graphs

In [365]:
# Getting the names of the first 200 movies in the Action and Adventure genre
movie_buddget = pd.read_csv('tn.movie_budgets.csv.gz')
name_movies = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac': # 'Ac' is the first two words for Action and Adventure
        name_movies.append(movie_buddget.movie[x])
len(name_movies)

117

In [366]:
# Getting product budget of the first 200 movies in Action and Adventure genre
product_budget = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac':product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

117

In [367]:
# Getting ratings of the first 200 movies in Action and Adventure genre
ratings = pd.read_csv('imdb.title.ratings.csv.gz')
rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac': rating.append(ratings.averagerating[x])
len(rating)

117

In [368]:
# Getting system ratings of the first 200 movies in Action and Adventure genre
system_rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac': system_rating.append(movie_info.rating[x])
len(system_rating)

117

In [369]:
# Getting domestic gross of the first 200 movies in Action and Adventure genre
domestic_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac': domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

117

In [370]:
# Getting worldwide gross of the first 200 movies in Action and Adventure genre
worldwide_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ac': worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

117

The amount of movies per system rating all have to be the same. The code bellow caluclates how much movies are currently in each system rating.

In [371]:
# putting system ratings into groups
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating
# need all groups to be even, all groups need 42 records

Counter({'R': 42, 'PG-13': 18, 'PG': 19, 'G': 6, 'NR': 32})

'R' has the highest count of movies, so all system rating will have to have 42 movies.

Due to the fact that the amount of movies per system rating is not tha same, the following codes caluclate how much is needed for each misiing amount in each group and also getting the indexes of what is needed.

In [372]:
# making sure all system_rating have the same amout of records
# getting the index of  system PG-13: need 24
index_PG13 = movie_info[movie_info['rating']=='PG-13'].index
index_PG13[100:150]

Int64Index([ 732,  736,  757,  764,  769,  775,  777,  781,  787,  791,  802,
             804,  806,  832,  835,  838,  844,  845,  877,  879,  883,  884,
             889,  893,  905,  907,  926,  929,  933,  944,  948,  956,  961,
             964,  965,  966,  972,  974,  985,  988,  998, 1004, 1008, 1013,
            1016, 1020, 1025, 1030, 1033, 1036],
           dtype='int64')

Based on the indexed that are found, the code below double checks to make sure each index fits all the critra  needed to fit.

In [373]:
# using data frame to see ifno
movie_info.iloc[[359,360,384,408,417,423,423,424,
                428,430,434,436,437,440,442,450,462,466,492,495,499,
                507,512,524,570,574,584,597,604,607,615,619,631,641,649,
                657,660,663,665,674,676,690,707,716,721,729,
                732,736,757,764,769,775,777,781,787,791,802,804,806,832]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
359,469,"Jacqueline Kennedy Onassis sued him, Marlon Br...",PG-13,Documentary|Musical and Performing Arts|Specia...,Leon Gast,NaN,"Jul 30, 2010","Oct 19, 2010",$,"2,367",88 minutes,Magnolia Pictures
360,470,Louis Gossett Jr. stars in Sidney J. Furie's p...,PG-13,Action and Adventure,NaN,NaN,"Jan 17, 1986","May 22, 2001",NaN,NaN,117 minutes,NaN
384,497,Newly divorced Emma Moriarty (Sally Field) mov...,PG-13,Comedy|Drama|Romance,Martin Ritt,NaN,"Dec 25, 1985","May 16, 2000",NaN,NaN,108 minutes,NaN
408,533,"Jack Lemmon is Sam Bissel, a happily married a...",PG-13,Classics|Comedy,David Swift,Jim Fritzell|Everett Greenbaum|David Swift,"Jul 22, 1964","Jun 9, 2009",NaN,NaN,130 minutes,NaN
417,547,This delightfully vulgar sex farce about infid...,PG-13,Classics|Comedy|Romance,Billy Wilder,NaN,"Dec 22, 1964","Jul 15, 2003",NaN,NaN,126 minutes,NaN
423,554,1970s-era DC antihero Jonah Hex makes his way ...,PG-13,Action and Adventure|Drama|Horror|Western,Jimmy Hayward,Mark Neveldine|Brian Taylor,"Jun 18, 2010","Oct 12, 2010",$,"10,500,000",84 minutes,Warner Bros. Pictures
423,554,1970s-era DC antihero Jonah Hex makes his way ...,PG-13,Action and Adventure|Drama|Horror|Western,Jimmy Hayward,Mark Neveldine|Brian Taylor,"Jun 18, 2010","Oct 12, 2010",$,"10,500,000",84 minutes,Warner Bros. Pictures
424,555,This wistful drama is set in the summer of 197...,PG-13,Comedy|Drama,Lesli Linka Glatter,NaN,"Oct 20, 1995","Dec 21, 1999",NaN,NaN,96 minutes,NaN
428,561,A child discovers a whole new world when he ru...,PG-13,Action and Adventure|Art House and Internation...,John Leekley,John Leekley,"Aug 1, 2000","Nov 21, 2000",NaN,NaN,109 minutes,NaN
430,563,Kat Ellis is looking for the right man -- now,PG-13,Comedy|Drama|Romance,Clare Kilner,Dana Fox,"Feb 4, 2005","Aug 16, 2005",$,"32,000,000",89 minutes,Universal Pictures
434,567,Now graduated from college and out in the real...,PG-13,Comedy,Trish Sie,Mike White|Kay Cannon,"Dec 22, 2017","Mar 20, 2018",$,"104,880,310",NaN,NaN
436,572,Earl and Hank have only one thing in common: t...,PG-13,Action and Adventure|Comedy|Drama,Dennis Dugan,David Ronn|Jay Scherick,"Jan 17, 2003","May 27, 2003",$,"35,764,982",91 minutes,Sony Pictures
437,573,A young man and his pals rule supreme at their...,PG-13,Comedy|Drama,NaN,NaN,"Sep 23, 2005","Dec 13, 2005",$,"17,364,602",118 minutes,Fox Searchlight Pictures
440,579,"In the riveting suspense drama, CHAPPAQUIDDICK...",PG-13,Mystery and Suspense,John Curran,Taylor Allen|Andrew Logan,"Apr 6, 2018","Jul 10, 2018",NaN,NaN,101 minutes,NaN
442,581,David Wagner is a Nineties kid with a Fifties ...,PG-13,Comedy|Drama|Science Fiction and Fantasy,Gary Ross,Gary Ross,"Oct 23, 1998","Mar 23, 1999",NaN,NaN,125 minutes,New Line Cinema
450,590,"Two ferociously ambitious sisters, Mary and An...",PG-13,Drama|Romance,Justin Chadwick,Peter Morgan,"Feb 29, 2008","Jun 10, 2008",$,"26,800,000",115 minutes,Sony Pictures/Columbia
462,605,Saturday Night Live star Chris Farley had his ...,PG-13,Comedy|Special Interest,Peter Segal,Bonnie Turner,"Mar 31, 1995","Nov 9, 1999",NaN,NaN,95 minutes,NaN
466,610,American tourist Frank (Johnny Depp) meets a m...,PG-13,Action and Adventure|Mystery and Suspense|Romance,Florian Henckel von Donnersmarck,Florian Henckel von Donnersmarck|Christopher M...,"Dec 10, 2010","Mar 22, 2011",$,"67,631,157",103 minutes,Columbia Pictures
492,643,Brigsby Bear Adventures is a children's TV sho...,PG-13,Comedy,Dave McCary,Kevin Costello,"Jul 28, 2017","Nov 14, 2017",$,"529,426",97 minutes,Sony Pictures Classics
495,646,"On the eve of graduating law school, Veronica ...",PG-13,Comedy|Drama|Mystery and Suspense,NaN,NaN,"Mar 14, 2014","May 6, 2014",$,"2,664,765",108 minutes,Warner Bros.
499,654,John Hughes crafts an exemplary '80s Brat Pack...,PG-13,Comedy|Drama,Howard Deutch,John Hughes,"Feb 28, 1986","Aug 20, 2002",NaN,NaN,96 minutes,NaN
507,665,"Malcolm McDowell, with shock-white hair and a ...",PG-13,Art House and International|Drama,Karen Shakhnazarov,Aleksandr Borodyanskiy|Karen Shakhnazarov,"Jan 1, 2001","Jun 7, 2005",NaN,NaN,104 minutes,NaN
512,672,A couple's strength and faith are tested after...,PG-13,Drama|Horror,Bill Duke,Brian Bird,"Jan 9, 2009","Apr 7, 2009",$,"10,572,742",100 minutes,Screen Gems/SONY PICTURES
524,686,Set in a dystopic present where vigilant gargo...,PG-13,Horror|Mystery and Suspense|Science Fiction an...,Stuart Beattie,Stuart Beattie,"Jan 24, 2014","May 13, 2014",$,"15,687,400",92 minutes,Lionsgate Films
570,740,Director Joe Johnston takes over the creative ...,PG-13,Action and Adventure|Mystery and Suspense|Scie...,Joe Johnston,Jim Taylor|Alexander Payne|Peter Buchman,"Jul 18, 2001","Dec 11, 2001",NaN,NaN,92 minutes,Universal Pictures
574,744,On a flight home to Chicago for a family weddi...,PG-13,Comedy|Romance,John Burgess,Dode Levenson,"Feb 6, 2015","Feb 9, 2015",NaN,NaN,100 minutes,Freestyle Releasing
584,755,Directing his first film since 1998's Lethal W...,PG-13,Action and Adventure|Science Fiction and Fantasy,Richard Donner,Jeff Maguire|George Nolfi,"Nov 26, 2003","Apr 13, 2004",$,"19,375,474",116 minutes,Paramount Pictures
597,771,From the creators of Scary Movie and Date Movi...,PG-13,Comedy,Jason Friedberg|Aaron Seltzer,Aaron Seltzer|Jason Friedberg,"Jan 25, 2008","Jun 3, 2008",$,"38,200,000",84 minutes,20th Century Fox
604,781,Yoji Yamada's torchy Japanese drama Love and H...,PG-13,Art House and International|Classics|Drama|Rom...,Yoji Yamada,Yoji Yamada|Ichiro Yamamoto|Emiko Hiramatsu,"Nov 2, 2007","Nov 11, 2008",NaN,NaN,121 minutes,The Bigger Picture
607,784,"During a Los Angeles Christmas, a group of 82n...",PG-13,Classics|Comedy|Drama,Lewis Milestone,Charles Lederer|Harry Brown,"Aug 10, 1960","May 13, 2008",NaN,NaN,128 minutes,NaN
615,793,This small-town romance may be trying to ride ...,PG-13,Drama|Romance,Jack Fisk,Naomi Foner,NaN,NaN,NaN,NaN,85 minutes,NaN
619,800,A bank robber tries to go straight but finds h...,PG-13,Action and Adventure|Drama,Oley Sassone,Mark Sevi,NaN,NaN,NaN,NaN,90 minutes,NaN
631,814,An egotistical TV reporter learns to appreciat...,PG-13,Comedy|Romance,Stephen Herek,John Scott Shepherd|Dana Stevens,"Apr 26, 2002","Oct 15, 2002",$,"14,400,987",103 minutes,20th Century Fox
641,825,"With the help of her former warden, ex-con Per...",PG-13,Drama,Lee David Zlotoff,Lee David Zlotoff,"Aug 23, 1996","Nov 6, 2001",NaN,NaN,106 minutes,NaN
649,833,"A group of friends who are avid ""Star Wars"" fa...",PG-13,Action and Adventure|Comedy|Drama,Kyle Newman,NaN,"Jul 31, 2008","May 19, 2009",$,"700,000",90 minutes,NaN
657,841,This is a contemporary retelling of H.G. Wells...,PG-13,Action and Adventure|Science Fiction and Fantasy,Steven Spielberg,Josh Friedman|David Koepp,"Jun 29, 2005","Nov 22, 2005",$,"234,141,872",117 minutes,Paramount Pictures
660,846,"Dee Roberts is a 24-year-old, African-American...",PG-13,Drama,Tim Disney,Bill Haney,"Apr 17, 2009","Oct 13, 2009",$,"465,786",113 minutes,Samuel Goldwyn Films
663,849,A sterling cast headed by Oscar-nominated Susa...,PG-13,Action and Adventure|Drama|Mystery and Suspense,Joel Schumacher,Akiva Goldsman|Robert Getchell,"Jul 20, 1994","Dec 16, 1997",NaN,NaN,120 minutes,NaN
665,852,"This 1987 concert film, shot by Purple Rain di...",PG-13,Documentary|Musical and Performing Arts,Prince,NaN,"Jun 1, 1987","Jan 28, 2003",NaN,NaN,85 minutes,NaN
674,862,A man is being driven crazy by his shiftless b...,PG-13,Comedy,Anthony Russo|Joe Russo,NaN,"Jul 13, 2006","Nov 21, 2006",$,"75,604,320",109 minutes,Universal Pictures
676,864,Vacancy director Nimr,PG-13,Drama|Mystery and Suspense,NaN,NaN,"Dec 4, 2009","Mar 16, 2010",$,"15,988,876",88 minutes,NaN
690,883,"Now that Greg Focker is ""in"" with his soon-to-...",PG-13,Comedy,Jay Roach,Jim Herzfeld|John Hamburg,"Dec 22, 2004","Apr 26, 2005",$,"279,167,575",118 minutes,Universal Pictures
707,908,A man and a woman battle with deceit and infid...,PG-13,Art House and International|Comedy|Drama,Jan Hrebejk,NaN,"Jun 8, 2001","Nov 27, 2001",NaN,NaN,120 minutes,Sony Pictures Classics
716,921,A group of maverick computer and espionage exp...,PG-13,Action and Adventure|Comedy|Drama|Mystery and ...,Phil Alden Robinson,NaN,"Sep 9, 1992","Mar 31, 1998",NaN,NaN,126 minutes,NaN
721,926,"In this suspense drama, a college student find...",PG-13,Horror|Mystery and Suspense,Rob Cohen,John Pogue,"Apr 1, 2000","Oct 24, 2000",NaN,NaN,106 minutes,Universal Studios Home Video
729,936,A teen-aged girl nearly comes unglued after he...,PG-13,Drama|Romance,Craig Bolotin,Craig Bolotin,"Jun 1, 1993","Feb 9, 1994",NaN,NaN,89 minutes,NaN
732,940,A woman is forced to prove her own sanity to s...,PG-13,Action and Adventure|Drama|Mystery and Suspense,Robert Schwentke,NaN,"Sep 23, 2005","Jan 24, 2006",$,"89,602,378",98 minutes,Touchstone Pictures
736,946,Tom is a twentysomething loser with no life. M...,PG-13,Comedy,Matt Reeves|Natt Reeves,Matt Reeves|Jason Katims,"May 3, 1996","Apr 3, 2001",NaN,NaN,97 minutes,NaN
757,975,"On her deathbed, a mother makes her son promis...",PG-13,Comedy|Romance,Andrew Bergman,Andrew Bergman,"Aug 28, 1992","May 15, 2001",NaN,NaN,95 minutes,NaN
764,984,A teenager and his kid brother spar with their...,PG-13,Drama|Mystery and Suspense,Michael Apted,Ron Koslow,"Jun 1, 1984","Jul 31, 2012",NaN,NaN,103 minutes,NaN
769,994,"Fresh Horses features Molly Ringwald as Jewel,...",PG-13,Drama|Romance,David Anspaugh,Larry Ketron,"Nov 18, 1988","Mar 23, 2004",NaN,NaN,102 minutes,NaN
775,1001,Based on the 2009 investigative book by BBC co...,PG-13,Drama,Stephen Frears,Jeff Pope|Steve Coogan,"Nov 22, 2013","Apr 15, 2014",NaN,NaN,98 minutes,The Weinstein Company
777,1004,Based on the Pulitzer Prize-winning novel by A...,PG-13,Drama,Steven Spielberg,Menno Meyjes,"Dec 16, 1985","Feb 18, 2003",NaN,NaN,154 minutes,NaN
781,1009,Director James L. Brooks returns to the helm f...,PG-13,Comedy|Drama|Romance,NaN,NaN,"Dec 17, 2010","Mar 22, 2011",$,"30,212,620",121 minutes,Columbia Pictures
787,1017,David Fincher's The Curious Case of Benjamin B...,PG-13,Drama|Science Fiction and Fantasy|Romance,David Fincher,Eric Roth|Robin Swicord,"Dec 25, 2008","May 5, 2009",$,"127,490,802",166 minutes,Paramount
791,1023,"Lorraine Gary stars as Ellen Brody, the widow ...",PG-13,Action and Adventure|Horror|Mystery and Suspense,Joseph Sargent,Michael De Guzman,"Jan 1, 1987","Jan 15, 1999",NaN,NaN,89 minutes,NaN
802,1036,"With THE FITZGERALD FAMILY CHRISTMAS, Burns re...",PG-13,Drama,Edward Burns,Edward Burns,"Dec 7, 2012","Nov 5, 2013",NaN,NaN,99 minutes,Tribeca Film
804,1038,Two New Yorkers fight the battle of the sexes ...,PG-13,Comedy|Drama|Romance,Donald Petrie,Burr Steers|Brian Regan|Kristen Buckley,"Feb 7, 2003","Jul 1, 2003",$,"105,765,605",115 minutes,Paramount Pictures
806,1043,"In the Holy Bible, the Book of Revelations spe...",PG-13,Action and Adventure|Drama|Mystery and Suspens...,Vic Sarin|Victor Sarin,NaN,"Jan 26, 2001","Oct 31, 2000",NaN,NaN,100 minutes,Cloud Ten Pictures
832,1077,Steven Spielberg's phenomenally successful sci...,PG-13,Action and Adventure|Mystery and Suspense|Scie...,Steven Spielberg,Michael Crichton|David Koepp|Malia Scotch Marmo,"Jun 11, 1993","Oct 10, 2000",$,"45,299,680",126 minutes,NaN

In [374]:
#checking if the names are already used
for i in name_movies:
    if i == 'Death Race':
        print('yes!')
else:print('no')

no

In [375]:
#checking info in the dataframe
movie_buddget.iloc[[9,24,97,113,125,150,156,177,185,219,229,295,303,318,
                   327]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
9,10,"Nov 6, 2015",Spectre,"$300,000,000","$200,074,175","$879,620,923"
24,25,"May 26, 2017",Pirates of the Caribbean: Dead Men Tell No Tales,"$230,000,000","$172,558,876","$788,241,137"
97,98,"Jun 19, 2015",Inside Out,"$175,000,000","$356,461,711","$854,235,992"
113,14,"Aug 1, 2014",Guardians of the Galaxy,"$170,000,000","$333,172,112","$770,867,516"
125,26,"May 27, 2016",Alice Through the Looking Glass,"$170,000,000","$77,042,381","$276,928,112"
150,51,"Nov 24, 2004",Alexander,"$155,000,000","$34,297,191","$167,297,191"
156,57,"Mar 4, 2016",Zootopia,"$150,000,000","$341,268,248","$1,019,429,616"
177,78,"Mar 29, 2018",Ready Player One,"$150,000,000","$137,690,172","$579,290,136"
185,86,"Nov 21, 2008",Bolt,"$150,000,000","$114,053,579","$328,015,029"
219,20,"Mar 6, 2009",Watchmen,"$138,000,000","$107,509,799","$186,976,250"
229,30,"Nov 14, 2003",Master and Commander: The Far Side of the World,"$135,000,000","$93,926,386","$212,912,137"
295,96,"Feb 12, 2014",RoboCop,"$120,000,000","$58,607,007","$242,981,799"
303,4,"May 19, 1999",Star Wars Ep. I: The Phantom Menace,"$115,000,000","$474,544,677","$1,027,044,677"
318,19,"May 29, 2015",San Andreas,"$110,000,000","$155,190,832","$456,258,539"
327,28,"Dec 21, 2016",Passengers,"$110,000,000","$100,014,699","$302,239,672"

After making sure the index fits properly, it is stored in a avairable used later on to add it back to the dataframe. This is being repeted through out the next few coding script.

In [376]:
# new names index for pg-13
no2 = [156,177,185,219,295,303,318,327,338,360,423,428,436,
      466,570,584,619,649,657,663,716,633,635,667,732,791,806]

In [377]:
# making sure all system_rating have the same amout of records
# getting system PG: need 23
index_PG = movie_info[movie_info['rating']=='PG'].index
index_PG[100:150]

Int64Index([667, 671, 680, 682, 686, 694, 695, 698, 701, 705, 710, 725, 741,
            753, 756, 760, 761, 779, 784, 790, 800, 811, 813, 818, 822, 837,
            841, 847, 853, 854, 855, 856, 860, 867, 869, 882, 887, 888, 913,
            914, 919, 928, 931, 934, 940, 949, 954, 957, 962, 981],
           dtype='int64')

In [378]:
movie_info.iloc[[426,431,439,452,455,458,463,470,471,473,474,481,504,505,589,601,
                617,623,627,633,635,640,651,653,655,667,753,756,760,761,779,784,790,800,811,822,837,841,847,853,854,855,856,860]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
426,559,A pair of hot young southern California surfer...,PG,Comedy|Kids and Family,Neal Israel,Dan Gordon,"Aug 20, 1993","Sep 3, 2002",NaN,NaN,87 minutes,NaN
431,564,"For super-dog ""Bolt"", every day is filled with...",PG,Action and Adventure|Animation|Comedy,NaN,NaN,"Nov 21, 2008","Mar 24, 2009",$,"114,053,579",96 minutes,Walt Disney Pictures
439,578,Woody Allen's gentle and nostalgic tribute to ...,PG,Comedy|Drama,Woody Allen,Woody Allen,"Jan 30, 1987","Nov 6, 2001",NaN,NaN,96 minutes,NaN
452,594,"Bill Murray, Dan Aykroyd, Harold Ramis and Ern...",PG,Action and Adventure|Comedy|Science Fiction an...,Ivan Reitman,Harold Ramis|Dan Aykroyd|Peter Torokvei,"Jun 8, 1984","Jun 29, 1999",NaN,NaN,105 minutes,Columbia Pictures
455,597,Director Lawrence Kasdan and Frank Galati adap...,PG,Comedy|Drama|Romance,Lawrence Kasdan,Anne Tyler|Frank Galati|Lawrence Kasdan,"Dec 23, 1988","Jun 1, 2004",NaN,NaN,121 minutes,NaN
458,601,Superman (Christopher Reeve) tries to save the...,PG,Action and Adventure|Science Fiction and Fantasy,NaN,Lawrence Konner|Mark Rosenthal,"Jul 24, 1987","May 1, 2001",NaN,NaN,91 minutes,NaN
463,607,Director and former stunt coordinator Chuck Ba...,PG,Drama|Mystery and Suspense|Science Fiction and...,Chuck Bail,NaN,"Jul 1, 1986","Apr 15, 1987",NaN,NaN,95 minutes,NaN
470,614,In one of John Wayne's more interesting late W...,PG,Classics|Drama|Western,Mark Rydell,NaN,"Jan 13, 1972","Oct 6, 1998",NaN,NaN,128 minutes,NaN
471,615,Master filmmaker Hou Hsiao Hsien directs this ...,PG,Art House and International|Drama,Hsiao-hsien Hou,NaN,"Jan 1, 1986","Sep 11, 2001",NaN,NaN,109 minutes,NaN
473,618,A would-be Nashville star finds himself in hot...,PG,Drama,NaN,Bob Bonney,NaN,NaN,NaN,NaN,110 minutes,NaN
474,619,Convinced that a recently burned-down structur...,PG,Comedy|Kids and Family|Science Fiction and Fan...,Michael Rubbo,Michael Rubbo,NaN,NaN,NaN,NaN,96 minutes,NaN
481,628,"""Queen of Katwe"" is the colorful true story of...",PG,Drama|Kids and Family,Mira Nair,William Wheeler,NaN,NaN,$,"8,874,389",124 minutes,NaN
504,661,One woman's rocky road to the altar gets playe...,PG,Comedy|Romance,Joel Zwick,Nia Vardalos,"Apr 19, 2002","Feb 11, 2003",$,"241,250,669",95 minutes,IFC Films
505,663,A pair of high-school dweebs get a chance to b...,PG,Comedy|Science Fiction and Fantasy,Les Mayfield,Shawn Schepps|Dana Olsen|George Zaloom,"May 22, 1992","May 15, 2001",NaN,NaN,88 minutes,NaN
589,761,Arthur Penn directed this quirky look at the l...,PG,Classics|Western,Arthur Penn,Leslie Stevens,"May 7, 1958","Nov 14, 2006",NaN,NaN,102 minutes,NaN
601,776,"Loosely based on Fellini's 8 1/2, this Woody A...",PG,Comedy|Drama,Woody Allen,Woody Allen,"Sep 26, 1980","Jul 5, 2000",NaN,NaN,88 minutes,NaN
617,797,The life of a middle-class black family in Los...,PG,Drama,Charles Burnett,Charles Burnett,"Jan 1, 1990","Jun 13, 1991",NaN,NaN,102 minutes,NaN
623,805,A sequel to HBO's award-winning film The Gathe...,PG,Action and Adventure|Drama,NaN,Hugh Whitemore,NaN,NaN,NaN,NaN,98 minutes,NaN
627,809,"Dismissed when first released, later heralded ...",PG,Classics|Drama|Mystery and Suspense|Romance,Alfred Hitchcock,NaN,"Jan 1, 1958","Mar 31, 1998",NaN,NaN,128 minutes,NaN
633,816,Two mismatched wolves embark on a cross-countr...,PG,Action and Adventure|Animation|Comedy|Kids and...,Anthony Bell|Ben Gluck|Benjamin Gluck,Steve Moore|Chris Denk,"Sep 17, 2010","Jan 11, 2011",$,"25,077,977",88 minutes,Lionsgate Films
635,818,This third film in the Teenage Mutant Ninja Tu...,PG,Action and Adventure|Comedy|Kids and Family|Sc...,Stuart Gillard|Corey Feldman|Tim Kelleher,Stuart Gillard|Joe Batteer,"Mar 19, 1993","Sep 3, 2002",NaN,NaN,96 minutes,NaN
640,824,"Making great fun of the '70s, this lively sci-...",PG,Comedy|Musical and Performing Arts|Science Fic...,Lucas Reiner,Lucas Reiner|Roman Coppola,"Jan 1, 1990","Jun 3, 2003",NaN,NaN,82 minutes,NaN
651,835,"In this off-beat sci-fi outing, alien invaders...",PG,Science Fiction and Fantasy,John Hayes,Frank Ray Perilli,"Jun 26, 1978","Mar 8, 2005",NaN,NaN,88 minutes,NaN
653,837,The Green Room (La Chambre Verte) is perhaps t...,PG,Art House and International|Drama,NaN,NaN,NaN,NaN,NaN,NaN,95 minutes,NaN
655,839,This distaff romantic tear jerker concerns a y...,PG,Drama|Romance,Arthur Hiller,Erich Segal,"Dec 16, 1970","Apr 24, 2001",NaN,NaN,100 minutes,Paramount Pictures
667,855,"Between giving up his super powers, confrontin...",PG,Action and Adventure|Science Fiction and Fantasy,Richard Lester|Richard Donner,Mario Puzo|David Newman|Leslie Newman,"Jun 19, 1981","May 1, 2001",NaN,NaN,127 minutes,NaN
753,971,Born Free is the heartwarming true story of a ...,PG,Action and Adventure|Drama|Kids and Family,James Hill,NaN,"Jun 22, 1966","Mar 4, 2003",NaN,NaN,96 minutes,NaN
756,974,Based on the autobiographical novel by Farley ...,PG,Action and Adventure|Drama,Carroll Ballard,Richard Kletter|Curtis Hanson|Sam Hamm,"Jan 1, 1983","Feb 22, 2000",NaN,NaN,105 minutes,NaN
760,978,'THX 1138' is a chilling look at a 25th-centur...,PG,Drama|Science Fiction and Fantasy,George Lucas,George Lucas|Walter Murch,"Mar 11, 1971","Sep 14, 2004",NaN,NaN,88 minutes,Warner Bros. Pictures
761,980,Connery's decision to quit as Bond left Brocco...,PG,Action and Adventure|Mystery and Suspense|Romance,Peter Hunt,Richard Maibaum|Simon Raven,"Dec 18, 1969","May 16, 2000",NaN,NaN,144 minutes,NaN
779,1007,Ernest (Jim Varney) gets a job as a fix-it man...,PG,Comedy|Kids and Family,NaN,Coke Sams|John Cherry,"May 22, 1987","Sep 3, 2002",NaN,NaN,92 minutes,NaN
784,1014,When a young American travels to the city of V...,PG,Comedy|Drama|Romance,Gary Winick,Jose Rivera|Tim Sullivan,"May 14, 2010","Sep 14, 2010",$,"53,021,560",105 minutes,Summit Entertainment
790,1022,"In this animated futuristic tale, a pair of tw...",PG,Action and Adventure|Animation|Kids and Family...,Ralph Bakshi,Ralph Bakshi,"Feb 9, 1977","May 25, 2004",NaN,NaN,80 minutes,Eureka Entertainment Ltd
800,1034,Henry VIII and His Six Wives is a feature film...,PG,Drama,Waris Hussein,Ian Thorne,NaN,NaN,NaN,NaN,125 minutes,NaN
811,1048,"In this film, Jerry Mathers stumbles upon Harr...",PG,Classics|Comedy|Mystery and Suspense,Alfred Hitchcock,John Michael Hayes|John Hayes,"Oct 3, 1955","Mar 6, 2001",NaN,NaN,100 minutes,NaN
822,1065,Two unlikely friends -- a boy and a killer wha...,PG,Action and Adventure|Kids and Family,NaN,Karen Janszen|Corey Blechman|John Mattson,"Jul 21, 1995","Jan 28, 2003",NaN,NaN,98 minutes,NaN
837,1082,There's a few million dollars' worth of star p...,PG,Classics|Drama,John Frankenheimer,Robert Alan Aurthur|William Hanley,"Dec 21, 1966","Jul 11, 2006",NaN,NaN,167 minutes,NaN
841,1086,With a plot based on The Magnificent Seven and...,PG,Science Fiction and Fantasy,NaN,Anne Dyer|John Sayles,"Dec 25, 1980","Feb 6, 2001",NaN,NaN,105 minutes,NaN
847,1094,When a soap-opera scriptwriter (John Candy) is...,PG,Comedy|Science Fiction and Fantasy,Tom Mankiewicz,NaN,"Aug 9, 1991","Apr 16, 2002",NaN,NaN,96 minutes,NaN
853,1101,"This Academy Award-nominated classic, voted on...",PG,Comedy|Drama,George Lucas,George Lucas|Gloria Katz|Willard Huyck,"Aug 1, 1973","Sep 15, 1998",NaN,NaN,113 minutes,NaN
854,1102,"Teenaged Anne Frank, a Dutch Jew, perished alo...",PG,Classics|Drama,George Stevens,Albert Hackett|Frances Goodrich,"Mar 18, 1959","Feb 3, 2004",NaN,NaN,156 minutes,NaN
855,1103,In this stop-motion animated comedy set in pre...,PG,Animation|Comedy|Kids and Family,Nick Park,Mark Burton|James Higginson,"Feb 16, 2018","May 22, 2018",NaN,NaN,89 minutes,Lionsgate
856,1104,"In this compact, fast-paced action thriller, a...",PG,Action and Adventure|Drama|Mystery and Suspense,Don Siegel,NaN,"Sep 19, 1973","Dec 28, 2004",NaN,NaN,111 minutes,NaN
860,1112,"Three sisters Sachi, Yoshino and Chika live to...",PG,Drama,Hirokazu Koreeda,Hirokazu Koreeda,"Jul 8, 2016","Nov 22, 2016",$,"466,986",128 minutes,Sony Pictures Classics

In [379]:
#checking if the names are already used
for i in name_movies:
    if i == 'Sound of Music':
        print('yes!')
else:print('no')

no

In [380]:
movie_buddget.iloc[[22,56,139,142,166,175,227,239,271,272,292,
                    333,346,347,354,370,431,452,458,
                   623,633,635,667]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
22,23,"Apr 14, 2017",The Fate of the Furious,"$250,000,000","$225,764,765","$1,234,846,267"
56,57,"Jun 24, 2011",Cars 2,"$200,000,000","$191,450,875","$560,155,383"
139,40,"May 24, 2013",Fast and Furious 6,"$160,000,000","$238,679,850","$789,300,444"
142,43,"Dec 25, 2008",The Curious Case of Benjamin Button,"$160,000,000","$127,509,326","$329,631,958"
166,67,"Jun 15, 2005",Batman Begins,"$150,000,000","$205,343,774","$359,142,722"
175,76,"May 10, 2019",PokÃ©mon: Detective Pikachu,"$150,000,000","$139,507,806","$411,258,433"
227,28,"Nov 19, 1999",The World is Not Enough,"$135,000,000","$126,930,660","$361,730,660"
239,40,"Aug 3, 2007",The Bourne Ultimatum,"$130,000,000","$227,471,070","$444,043,396"
271,72,"Apr 1, 2010",Clash of the Titans,"$125,000,000","$163,214,888","$493,214,888"
272,73,"Nov 4, 2016",Trolls,"$125,000,000","$153,707,064","$344,150,134"
292,93,"Apr 19, 2013",Oblivion,"$120,000,000","$89,107,235","$287,916,633"
333,34,"Mar 18, 2016",The Divergent Series: Allegiant,"$110,000,000","$66,184,051","$172,022,517"
346,47,"Nov 23, 2016",Allied,"$106,000,000","$40,098,064","$119,266,661"
347,48,"Jul 16, 2004","I, Robot","$105,000,000","$144,801,023","$348,629,585"
354,55,"Jun 9, 2000",Gone in 60 Seconds,"$103,300,000","$101,643,008","$232,643,008"
370,71,"Jul 15, 1994",True Lies,"$100,000,000","$146,282,411","$365,300,000"
431,32,"Feb 14, 2008",The Spiderwick Chronicles,"$92,500,000","$71,195,053","$162,839,667"
452,53,"Jun 6, 2008",You Don't Mess With the Zohan,"$90,000,000","$100,018,837","$202,910,991"
458,59,"Jul 24, 2015",Pixels,"$90,000,000","$78,765,986","$244,041,804"
623,24,"Dec 25, 2006",Children of Men,"$76,000,000","$35,552,383","$69,845,011"
633,34,"Jun 25, 2010",Grown Ups,"$75,000,000","$162,001,186","$272,223,430"
635,36,"Jul 14, 2000",X-Men,"$75,000,000","$157,299,717","$296,872,367"
667,68,"Oct 23, 1998",Soldier,"$75,000,000","$14,623,082","$14,623,082"

In [381]:
#new name index for pg
no1=[56,142,227,239,271,272,292,
    346,347,354,370,452,458,
    623,753,756,761,790,822,856]

In [382]:
# making sure all system_rating have the same amout of records
# getting system NR: need 10
index_PG = movie_info[movie_info['rating']=='NR'].index
index_PG[50:100]

Int64Index([164, 169, 171, 174, 179, 180, 183, 186, 195, 196, 197, 200, 208,
            210, 213, 215, 216, 220, 221, 222, 225, 228, 233, 236, 237, 238,
            244, 250, 251, 257, 258, 263, 265, 267, 268, 273, 274, 282, 284,
            289, 290, 291, 293, 305, 306, 312, 314, 320, 321, 323],
           dtype='int64')

In [383]:
movie_info.iloc[[164,169,171,174,179,180,183,186,195,196,
                197,200,208,237,238,244,250,251,257,258,263,265,267,268,273,274,282,284,289,290,291,293]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
164,216,"""I'm the finest woman who walked the streets,""...",NR,Classics|Comedy,Lowell Sherman,Mae West|Harvey Thew|John Bright,"Feb 9, 1933","Apr 22, 2008",NaN,NaN,65 minutes,NaN
169,223,"The Leningrad Cowboys, the self-proclaimed Wor...",NR,Documentary|Musical and Performing Arts,NaN,NaN,"Jul 2, 1994","Apr 26, 2005",NaN,NaN,54 minutes,NaN
171,225,Forbidden love between a beautiful orphan and ...,NR,Drama|Television,Bobby Roth,Maria Nation,"Apr 6, 1997","Dec 7, 2004",NaN,NaN,93 minutes,NaN
174,229,The grass is always greener.... In this Britis...,NR,Comedy,Val Guest,NaN,"Oct 11, 1957","Mar 28, 2000",NaN,NaN,85 minutes,NaN
179,236,John Wayne once again goes undercover to catch...,NR,Classics|Western,NaN,NaN,"May 10, 1934","Jun 18, 2006",NaN,NaN,59 minutes,NaN
180,237,Coproduced by the BBC and America's Fox Networ...,NR,Action and Adventure|Drama|Science Fiction and...,Geoffrey Sax,Matthew Jacobs,"May 12, 1996","Feb 8, 2011",NaN,NaN,85 minutes,NaN
183,240,"In this film, Maurice Chevalier plays a Parisi...",NR,Classics|Comedy|Musical and Performing Arts|Ro...,George Cukor|Ernst Lubitsch,Samson Raphaelson,"Mar 22, 1932","Feb 12, 2008",NaN,NaN,80 minutes,NaN
186,247,"Based on a popular British television drama, t...",NR,Art House and International|Drama|Romance,NaN,Ted Willis,NaN,NaN,NaN,NaN,93 minutes,NaN
195,258,NaN,NR,Art House and International|Drama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,259,One of history's most shocking horrors returns...,NR,Drama|Horror|Mystery and Suspense,NaN,Leif Holt,NaN,NaN,NaN,NaN,93 minutes,NaN
197,261,Tea for Two is a Technicolor adaptation of the...,NR,Classics|Comedy|Drama|Musical and Performing Arts,David Butler,Harry Clork|William Jacobs|Harry Clark,"Sep 2, 1950","Apr 7, 2009",NaN,NaN,98 minutes,NaN
200,265,Wakeboarding is a sport of ever-increasing pop...,NR,Special Interest|Sports and Fitness,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208,275,Stephen Chow's prodigious skills with guns and...,NR,Action and Adventure|Art House and Internation...,Gordon Chan,NaN,"Dec 31, 1991","Mar 28, 2006",NaN,NaN,101 minutes,NaN
237,308,"In this occult obscurity, an old hillbilly nam...",NR,Horror,NaN,NaN,NaN,NaN,NaN,NaN,75 minutes,NaN
238,309,The first person the audience sees in Ship of ...,NR,Classics|Documentary|Drama|Romance,Stanley Kramer,Abby Mann,"Jul 29, 1965","Dec 2, 2003",NaN,NaN,52 minutes,NaN
244,317,"Directed by Christopher Roth, this biopic chro...",NR,Art House and International|Comedy|Drama|Myste...,Christopher Roth,NaN,NaN,NaN,NaN,NaN,129 minutes,NaN
250,327,"When a new robot, Raymond, defeats the three h...",NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13 minutes,NaN
251,328,"In this exploitation film, a sadistic juvenile...",NR,Action and Adventure|Classics|Drama|Mystery an...,Douglas Heyes,Douglas Heyes,"Nov 4, 1964","Oct 31, 2000",NaN,NaN,83 minutes,NaN
257,335,"Retired attorney Spencer Tracy, now a self-des...",NR,Drama|Mystery and Suspense,John Sturges,NaN,NaN,NaN,NaN,NaN,101 minutes,NaN
258,336,"A depressed, alcoholic man is driven further a...",NR,Drama,NaN,NaN,NaN,NaN,NaN,NaN,89 minutes,NaN
263,348,Dean Martin and Jerry Lewis made their last jo...,NR,Classics|Comedy,Frank Tashlin,Erna Lazarus,"Jan 1, 1956","Jun 5, 2007",NaN,NaN,95 minutes,NaN
265,350,An atomic bomb test in the Arctic Circle awake...,NR,Classics|Horror|Science Fiction and Fantasy,NaN,NaN,"Jun 13, 1953","Oct 21, 2003",NaN,NaN,80 minutes,NaN
267,353,Robert (character actor David Thornton) is a g...,NR,Art House and International|Comedy|Drama,Darko Lungulov,Darko Lungulov,"May 14, 2010","Jul 13, 2010",NaN,NaN,90 minutes,Independant Pictures
268,354,Bob Hope's first starring vehicle for producer...,NR,Classics|Comedy|Musical and Performing Arts,David Butler,Frank Fenton|Harry Kurnitz|Lynn Root,"Mar 4, 1943","Aug 21, 2003",NaN,NaN,95 minutes,NaN
273,361,NaN,NR,Drama|Special Interest,Roberto Sanchez Santos,NaN,NaN,NaN,NaN,NaN,7 minutes,NaN
274,363,Hammer's second outing for the notorious vampi...,NR,Horror,Terence Fisher,Anthony Hinds|Jimmy Sangster,"Jan 12, 1966","May 26, 1998",NaN,NaN,90 minutes,NaN
282,372,"A once-acclaimed New York playwright, Nate (Je...",NR,Comedy,Sam Hoffman,Sam Hoffman,NaN,NaN,NaN,NaN,93 minutes,NaN
284,374,The plot of the overinflated MGM musical Broad...,NR,Comedy|Musical and Performing Arts,Roy Del Ruth,Harry Clork|Dorothy Kingsley|Jerome Kern|Jack ...,NaN,NaN,NaN,NaN,117 minutes,NaN
289,380,Director Danny Verete's Yellow Asphalt is an a...,NR,Art House and International|Drama,Dan Verete,Danny Verete,"Mar 15, 2002","Jun 21, 2005",NaN,NaN,83 minutes,NaN
290,384,"In this romantic comedy, New York sportswriter...",NR,Classics|Comedy|Romance,George Stevens,NaN,"Jan 19, 1942","Aug 27, 1997",NaN,NaN,114 minutes,NaN
291,385,How to Kill a Lady is an Bond-style thriller w...,NR,Action and Adventure|Drama|Mystery and Suspense,Manfred Kohler,NaN,NaN,NaN,NaN,NaN,93 minutes,NaN
293,387,"In this western, Will Penny is an aging and im...",NR,Action and Adventure|Classics|Western|Romance,Tom Gries,Tom Gries,"Apr 10, 1968","Jun 4, 2002",NaN,NaN,109 minutes,NaN

In [384]:
# new names index for NR
no3=[169,171,174,179,180,195,196,233,251,293]

In [385]:
# making sure all system_rating have the same amout of records
# getting system G: need 36
index_G = movie_info[movie_info['rating']=='G'].index
index_G[100:110]

Int64Index([], dtype='int64')

In [386]:
movie_info.iloc[[1450,1522,1528,1540,1544,1557,1558]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1450,1867,"Filmed in panoramic Cinerama, this star-studde...",G,Action and Adventure|Classics|Drama|Western,John Ford|Henry Hathaway|George Marshall|Richa...,NaN,"Feb 20, 1963","Sep 30, 2006",NaN,NaN,180 minutes,NaN
1522,1958,Twenty-nine-year-old Iranian-American writer C...,G,Drama,Amir Motlagh,Amir Motlagh,NaN,NaN,NaN,NaN,74 minutes,NaN
1528,1965,"Because of a misunderstanding on his part, Cli...",G,Animation|Kids and Family,Robert Ramirez,Robert Ramirez|Rhett Reese,"Apr 23, 2004","Aug 24, 2004",$,"2,782,548",73 minutes,Warner Bros. Pictures
1540,1979,"In this taut crime drama, a radio broadcaster ...",G,Classics|Drama|Mystery and Suspense,Michael Curtiz,Ranald MacDougall|Bess Meredyth,NaN,NaN,NaN,NaN,103 minutes,NaN
1544,1983,This animated children's film spoofs the Sherl...,G,Action and Adventure|Animation|Kids and Family,Burny Mattinson|Ron Clements|John Musker|Dave ...,NaN,"Jul 2, 1986","Jul 23, 2002",NaN,NaN,74 minutes,NaN
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,NaN,"Jan 1, 1962","May 11, 2004",NaN,NaN,111 minutes,NaN
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,"Apr 1, 1993","Jan 29, 2002",NaN,NaN,101 minutes,NaN

In [387]:
# new name index for G
no = [30,143,168,248,254,593,892,894,1102,1105,1439,1450,
     1544]

In [388]:
# getting system G name:need 36,couldnt get all missed 10
names=[]
for i in no:
    names.append(movie_buddget.movie[i])
names

['The Amazing Spider-Man',
 "The Sorcerer's Apprentice",
 'Dunkirk',
 'Rio 2',
 'R.I.P.D.',
 'Thirteen Days',
 'The Tale of Despereaux',
 'The Dark Tower',
 'Stepmom',
 'Inside Man',
 'Legal Eagles',
 'Fever Pitch',
 "The Time Traveler's Wife"]

In [389]:
# getting system PG name:need 23
names1=[]
for i in no1:
    names1.append(movie_buddget.movie[i])
names1[:8]

['Cars 2',
 'The Curious Case of Benjamin Button',
 'The World is Not Enough',
 'The Bourne Ultimatum',
 'Clash of the Titans',
 'Trolls',
 'Oblivion',
 'Allied']

In [390]:
# getting system PG-13 name:need 24
names2=[]
for i in no2:
    names2.append(movie_buddget.movie[i])
names2[:8]

['Zootopia',
 'Ready Player One',
 'Bolt',
 'Watchmen',
 'RoboCop',
 'Star Wars Ep. I: The Phantom Menace',
 'San Andreas',
 'Passengers']

In [391]:
# getting system NR name:need 10
names3=[]
for i in no3:
    names3.append(movie_buddget.movie[i])
names3[:9]

['Thor',
 'X-Men Origins: Wolverine',
 'Mad Max: Fury Road',
 'Mission: Impossible III',
 'Angels & Demons',
 'Flushed Away',
 "Madagascar 3: Europe's Most Wanted",
 'Miami Vice',
 'The Adventures of Tintin']

Now that all the new indexs has been idnetified they will be added to the new dataframe needed to create the five interactive graphs.

In [392]:
# add new 'R' names to the original
for i in names:
    name_movies.append(i)
len(name_movies)

130

In [393]:
# add new 'PG' names to the original
for i in names1:
    name_movies.append(i)
len(name_movies)

150

In [394]:
# add new 'PG-13' names to the original
for i in names2:
    name_movies.append(i)
len(name_movies)

177

In [395]:
# add new 'G' names to the original
for i in names3:
    name_movies.append(i)
len(name_movies)

187

Now that the names have been updated with the new indexes, we use it to get the rest of the key components from the original dataframe to add to the new dataframe.

In [396]:
#getting the index of the names to get other info from dataframe
index = []
for i in name_movies:
    index.append(list(movie_buddget[movie_buddget['movie']==i].index))
len(index)

187

In [397]:
#Turning nested list to regular list
from funcy import flatten,isa
flat_list = flatten(index)

In [398]:
#converting list of list into int 
newflat_list = []
for i in flat_list:
    i=int(i)
    newflat_list.append(i)

In [399]:
# removing integers that are not needed
newflat_list1 = []
for i in newflat_list:
    if i == 2095:continue
    if i == 273:continue
    if i == 3232:continue
    if i == 2434:continue
    if i == 4198:continue
    if i == 4476:continue
    if i == 3409:continue
    if i == 3050:continue
    if i == 3566:continue
    if i == 3254:continue
    else: newflat_list1.append(i)

In [400]:
len(newflat_list1)

187

In [401]:
#using the updated indexes to get the new and old product budgets
product_budget = []
for x in newflat_list1:
    product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

187

In [402]:
# using the updated indexes to get the new and old ratings
rating = []
for x in newflat_list1:
    rating.append(ratings.averagerating[x])
len(rating)

187

In [403]:
#using the updated indexes to get thenew and old system ratings
system_rating = []
for x in newflat_list1:
    system_rating.append(movie_info.rating[x])
len(system_rating)

187

In [404]:
# all system ratings have the same amout of records 42 except for 'G' system rating
# 'G' rating needs 23 movies 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'R': 42, 'PG-13': 42, 'PG': 42, 'G': 19, 'NR': 42})

The data set did not have enough movies in the Action and Adventure genre that was G-rated. The 23 movies needed were from Box Office Mojo, they will be added to the data frame.

In [405]:
# the name of the movies
name_mojo = ['Captain America: Civil War','Cinderella','The Sound of Music','The Tale of Despereaux','Monsters University','Herbie: Fully Loaded',
            'Wallace & Gomit: The Curse of the Were-Rabbit','A Boy\'s Life','Ozzy','Ponyo','Gnomeo & Juliet','Yellow Submarine',
            'Curious George 1','Fantastica: A Boonie Bears','Ice Age 2: The Meltdown','The Fox and the Child','Space Chimps','The Oegieloves',
            'Brother Bears 1','Cliffords','The Wizard of Oz','Chicken Little','Wall-E']
# ratings of the movies
rating_mojo = [7.8,7.6,8.1,6.1,7.3,4.8,7.4,7.3,5.2,7.7,6.9,7.4,6.5,6.4,6.8,8,4.5,2.1,6.8,5.4,8,5.7,8.4]
# worldwide gross
worldwide_gross_mojo = ['$1,078,000,000','$542,400,000','$2,366,000,000','$86,957,280','$743,539,607','$144,146,816','$194,111,171','$424,600,00',
                       '$12,852,439','$202,551,810','$193,900,000','$1,278,261','$69,800,000','$77,151,096','$660,998,756','$29,610,210',
                       '$65,097,693','$1,065,907','$250,397,798','$3,252,426','$34,949,482','$314,432,837','$521,311,860']
# domestic gross
domestic_gross_mojo = ['$434,000,000','$201,200,000','$163,214,076','$50,877,145','$268,492,764','$66,023,816','$56,110,897','$204,400,000',
                      '$0','$15,090,399','$94,000,000','$992,303','$58,400,000','$76,630,780','$195,336,621','$29,610,210','$30,105,968',
                       '$1,065,907','$85,336,277','$2,922,354','$34,685,891','$135,386,665','$223,808,164']
# product budget
product_budget_mojo = ['$200,000,000','$100,000,000','$62,890,769','$60,000,000','$200,000,000','$50,000,000','$30,000,000',
                      '$90,000,000','$10,000,000','$34,000,000','$36,000,000','$250,000','$50,000,000','$90,000,000','$80,000,00',
                       '$13,000,000','$37,000,000','$20,000,000','$46,000,000','$70,000','$2,777,000','$150,000,000','$180,000,000']

In [406]:
# adding names from mojo to the original
for i in name_mojo:
    name_movies.append(i)
len(name_movies)

210

In [407]:
g = 'G'*23
g= list(g)
for i in g:
    system_rating.append(i)
len(system_rating)

210

In [408]:
# adding rating from mojo to the original
for i in rating_mojo:
    rating.append(i)
len(rating)

210

In [409]:
# adding product budget from mojo to the original
for i in product_budget_mojo:
    product_budget.append(i)
len(product_budget)

210

In [410]:
#using the updated indexes to get the new and old domestic gross
domestic_gross = []
for x in newflat_list1:
    domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

187

In [411]:
# adding product budget from mojo to the original
for i in domestic_gross_mojo:
    domestic_gross.append(i)
len(domestic_gross)

210

In [412]:
### using the updated indexes to get the new and old worldwide gross
worldwide_gross = []
for x in newflat_list1:
    worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

187

In [413]:
# adding product budget from mojo to the original
for i in worldwide_gross_mojo:
    worldwide_gross.append(i)
len(worldwide_gross)

210

In [414]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'R': 42, 'PG-13': 42, 'PG': 42, 'G': 42, 'NR': 42})

All the information have been gathered, the script below uses it to create a new and updated dataframe.

In [415]:
all_actionadventure_info = pd.DataFrame({'Name':name_movies,'System_ratings':system_rating,'Rating':rating,'Worlwide_gross':worldwide_gross,
                               'Domestic_gross':domestic_gross,'Product_budget':product_budget})
all_actionadventure_info1=all_actionadventure_info.dropna()
all_actionadventure_info1 = all_actionadventure_info[all_actionadventure_info.Name !='Moonfall']

Now that the dataframe has been updated, Worldwide Gross, Product Budget and Domestic Gross has to be converted from string to int.

In [416]:
# turning Worldwide gross into int
storage1 = []
storage2 = []
total_gross=[]
for i in  all_actionadventure_info1.dropna().Worlwide_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    total_gross.append(i)
len(total_gross)

210

In [417]:
# turning Produt budget  into int
storage1 = []
storage2 = []
budget=[]
for i in  all_actionadventure_info1.dropna().Product_budget:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    budget.append(i)
len(budget)

210

In [418]:
# turning Domestic gross into int
storage1 = []
storage2 = []
Doomestic_gross=[]
for i in  all_actionadventure_info1.dropna().Domestic_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    Doomestic_gross.append(i)
len(Doomestic_gross)

210

In [419]:
#drop all the NA from the dataframe
all_actionadventure_info1 = all_actionadventure_info1.dropna()


#adding all the string componnets that have been converted to dataframe
all_actionadventure_info1['Buget']=budget
all_actionadventure_info1['Total_gross']=total_gross
all_actionadventure_info1['Domestic_total']=Doomestic_gross
all_actionadventure_info1[190:]

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total
190,The Tale of Despereaux,G,6.1,"$86,957,280","$50,877,145","$60,000,000",60000000,86957280,50877145
191,Monsters University,G,7.3,"$743,539,607","$268,492,764","$200,000,000",200000000,743539607,268492764
192,Herbie: Fully Loaded,G,4.8,"$144,146,816","$66,023,816","$50,000,000",50000000,144146816,66023816
193,Wallace & Gomit: The Curse of the Were-Rabbit,G,7.4,"$194,111,171","$56,110,897","$30,000,000",30000000,194111171,56110897
194,A Boy's Life,G,7.3,"$424,600,00","$204,400,000","$90,000,000",90000000,42460000,204400000
195,Ozzy,G,5.2,"$12,852,439",$0,"$10,000,000",10000000,12852439,0
196,Ponyo,G,7.7,"$202,551,810","$15,090,399","$34,000,000",34000000,202551810,15090399
197,Gnomeo & Juliet,G,6.9,"$193,900,000","$94,000,000","$36,000,000",36000000,193900000,94000000
198,Yellow Submarine,G,7.4,"$1,278,261","$992,303","$250,000",250000,1278261,992303
199,Curious George 1,G,6.5,"$69,800,000","$58,400,000","$50,000,000",50000000,69800000,58400000
200,Fantastica: A Boonie Bears,G,6.4,"$77,151,096","$76,630,780","$90,000,000",90000000,77151096,76630780
201,Ice Age 2: The Meltdown,G,6.8,"$660,998,756","$195,336,621","$80,000,00",8000000,660998756,195336621
202,The Fox and the Child,G,8.0,"$29,610,210","$29,610,210","$13,000,000",13000000,29610210,29610210
203,Space Chimps,G,4.5,"$65,097,693","$30,105,968","$37,000,000",37000000,65097693,30105968
204,The Oegieloves,G,2.1,"$1,065,907","$1,065,907","$20,000,000",20000000,1065907,1065907
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164

In [420]:
# getting profit
profit = []
for x,y in enumerate(total_gross):
    profit.append(y-budget[x])
len(profit)

210

In [421]:
all_actionadventure_info1['Profit']=profit

In [422]:
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit
0,Avatar,R,8.3,"$2,776,345,279","$760,507,625","$425,000,000",425000000,2776345279,760507625,2351345279
1,Spectre,PG-13,4.2,"$879,620,923","$200,074,175","$300,000,000",300000000,879620923,200074175,579620923
2,Captain America: Civil War,R,7.6,"$1,140,069,413","$408,084,349","$250,000,000",250000000,1140069413,408084349,890069413
3,Batman v Superman: Dawn of Justice,PG,6.5,"$867,500,281","$330,360,194","$250,000,000",250000000,867500281,330360194,617500281
4,The Hobbit: The Battle of the Five Armies,G,6.6,"$945,577,621","$255,119,788","$250,000,000",250000000,945577621,255119788,695577621
...,...,...,...,...,...,...,...,...,...,...
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277,204397798
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354,3182426
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891,32172482
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665,164432837
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164,341311860

In [423]:
# Creating Box office column
# dividing total gross by the avg price of tickets, to get an estimsted number of tickes sold
no_tickets = []
for i in all_actionadventure_info1.Total_gross:
    no_tickets.append(round(i/13)) 
no_tickets[:10]

[213565021,
 67663148,
 87697647,
 66730791,
 72736740,
 94988174,
 28775774,
 32103176,
 50324114,
 64347669]

In [424]:
# converting integer of no. of tickets into string
tickets_string = []
for i in no_tickets:
    tickets_string.append("{:,.0f}".format(i))
len(tickets_string)

210

In [425]:
# converting integer of profit to currency
currency = []
for i in all_actionadventure_info1.Profit:
    currency.append("${:,.0f}".format(i))
len(currency)

210

In [426]:
all_actionadventure_info1['No.Tickets']=tickets_string
all_actionadventure_info1['Profit$']= currency
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit,No.Tickets,Profit$
0,Avatar,R,8.3,"$2,776,345,279","$760,507,625","$425,000,000",425000000,2776345279,760507625,2351345279,"213,565,021","$2,351,345,279"
1,Spectre,PG-13,4.2,"$879,620,923","$200,074,175","$300,000,000",300000000,879620923,200074175,579620923,"67,663,148","$579,620,923"
2,Captain America: Civil War,R,7.6,"$1,140,069,413","$408,084,349","$250,000,000",250000000,1140069413,408084349,890069413,"87,697,647","$890,069,413"
3,Batman v Superman: Dawn of Justice,PG,6.5,"$867,500,281","$330,360,194","$250,000,000",250000000,867500281,330360194,617500281,"66,730,791","$617,500,281"
4,The Hobbit: The Battle of the Five Armies,G,6.6,"$945,577,621","$255,119,788","$250,000,000",250000000,945577621,255119788,695577621,"72,736,740","$695,577,621"
...,...,...,...,...,...,...,...,...,...,...,...,...
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277,204397798,"19,261,369","$204,397,798"
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354,3182426,"250,187","$3,182,426"
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891,32172482,"2,688,422","$32,172,482"
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665,164432837,"24,187,141","$164,432,837"
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164,341311860,"40,100,912","$341,311,860"

After the dataframe has been updated, bokeh is being installed.

In [357]:
from bokeh.layouts import gridplot,row
from bokeh.plotting import figure,output_file,ColumnDataSource
from bokeh.io import push_notebook,show,output_notebook
from bokeh.models import NumeralTickFormatter
output_notebook()

Bokeh is successfully installed, now the key componets need to be creted for each system rating group to make the graphs.

A reminder of the componets;
 - Cost
 - Proft
 - Name
 - Profit Percntage by Cost
 - Type of System Rating

In [118]:
# index of all 'R' system ratings
index_r = []
for i,x in enumerate(system_rating):
    if x == 'R':index_r.append(i)

In [119]:
# getiing the profit for all 'R' system rating
r_profit = []
for i in index_r:
    r_profit.append(all_actionadventure_info1.Profit[i])
r_profit

[2351345279,
 890069413,
 142085065,
 192341288,
 439213485,
 894039076,
 1015392272,
 662316233,
 508996336,
 452220086,
 136359676,
 349283695,
 208541369,
 1135772799,
 675524642,
 277150894,
 160043823,
 289942139,
 693524737,
 424987477,
 143271982,
 113317814,
 500912003,
 109545589,
 733998877,
 -37371735,
 42364370,
 40468000,
 778210985,
 547271443,
 164065678,
 363195589,
 262211740,
 -30451359,
 -4744515,
 168898761,
 522726752,
 198693989,
 213500000,
 67092943,
 16000000,
 214477886]

In [120]:
# getting the cost for 'R' system rating
cost1 = []
for i in index_r:
    cost1.append(all_actionadventure_info1.Product_budget[i])
cost1

['$425,000,000',
 '$250,000,000',
 '$232,000,000',
 '$225,000,000',
 '$215,000,000',
 '$210,000,000',
 '$200,000,000',
 '$200,000,000',
 '$200,000,000',
 '$200,000,000',
 '$200,000,000',
 '$175,000,000',
 '$175,000,000',
 '$170,000,000',
 '$160,000,000',
 '$155,000,000',
 '$150,000,000',
 '$142,000,000',
 '$136,200,000',
 '$130,000,000',
 '$130,000,000',
 '$125,000,000',
 '$120,000,000',
 '$120,000,000',
 '$115,000,000',
 '$115,000,000',
 '$110,000,000',
 '$110,000,000',
 '$109,000,000',
 '$108,000,000',
 '$105,000,000',
 '$102,000,000',
 '$100,000,000',
 '$100,000,000',
 '$100,000,000',
 '$95,000,000',
 '$92,000,000',
 '$90,000,000',
 '$90,000,000',
 '$90,000,000',
 '$90,000,000',
 '$85,000,000']

In [121]:
# getiing the name for all 'R' system rating
r_name = []
for i in index_r:
    r_name.append(all_actionadventure_info1.Name[i])
r_name

['Avatar',
 'Captain America: Civil War',
 'Superman Returns',
 'The Chronicles of Narnia: Prince Caspian',
 'Men in Black 3',
 'Transformers: Age of Extinction',
 'Iron Man 3',
 'Guardians of the Galaxy Vol 2',
 'The Amazing Spider-Man 2',
 'Fantastic Beasts: The Crimes of Grindelwald',
 'Prince of Persia: Sands of Time',
 'Ralph Breaks The Internet',
 'Cars 3',
 'Jurassic World: Fallen Kingdom',
 'Inception',
 'Terminator: Genisys',
 'Chicken Little',
 'Die Another Day',
 'The Twilight Saga: Breaking Dawn, Part 2',
 'Puss in Boots',
 'Bad Boys II',
 'Batman & Robin',
 'Life of Pi',
 'Ghost Rider',
 'Star Wars Ep. III: Revenge of the Sith',
 'Windtalkers',
 'The Taking of Pelham 123',
 'Speed 2: Cruise Control',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Martian',
 '10,000 B.C.',
 'Bumblebee',
 'Planet of the Apes',
 'Land of the Lost',
 'Peter Pan',
 'The Fifth Element',
 'The Incredibles',
 'What Lies Beneath',
 'Mulan',
 'Lara Croft: Tomb Raider: The Cradle of Life',
 'Mission to Mars',
 'Horton Hears a Who']

In [122]:
# getiing the $profit for all 'R' system rating
r_dollar = []
for i in index_r:
    r_dollar.append(all_actionadventure_info1['Profit$'][i])
len(r_dollar)

42

In [123]:
# getiing the system rating for all 'R' system rating
r_sratings = []
for i in index_r:
    r_sratings.append(all_actionadventure_info1.System_ratings[i])
len(r_sratings)

42

In [124]:
# getting percentage profit for all 'R' system rating
percent_profit = []
for i in index_r:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit.append(round(i,0))
percent_profit

[553.0,
 356.0,
 61.0,
 85.0,
 204.0,
 426.0,
 508.0,
 331.0,
 254.0,
 226.0,
 68.0,
 200.0,
 119.0,
 668.0,
 422.0,
 179.0,
 107.0,
 204.0,
 509.0,
 327.0,
 110.0,
 91.0,
 417.0,
 91.0,
 638.0,
 -32.0,
 39.0,
 37.0,
 714.0,
 507.0,
 156.0,
 356.0,
 262.0,
 -30.0,
 -5.0,
 178.0,
 568.0,
 221.0,
 237.0,
 75.0,
 18.0,
 252.0]

In [125]:
# turning float of percentage of profit into int for 'R' system rating
pp = []
for i in percent_profit:
    i = int(i)
    pp.append(i)
pp

[553,
 356,
 61,
 85,
 204,
 426,
 508,
 331,
 254,
 226,
 68,
 200,
 119,
 668,
 422,
 179,
 107,
 204,
 509,
 327,
 110,
 91,
 417,
 91,
 638,
 -32,
 39,
 37,
 714,
 507,
 156,
 356,
 262,
 -30,
 -5,
 178,
 568,
 221,
 237,
 75,
 18,
 252]

In [126]:
# converting integer to percentage for 'R' system rating
percentage_profit = []
for i in pp:
    percentage_profit.append("{:}%".format(i))
percentage_profit

['553%',
 '356%',
 '61%',
 '85%',
 '204%',
 '426%',
 '508%',
 '331%',
 '254%',
 '226%',
 '68%',
 '200%',
 '119%',
 '668%',
 '422%',
 '179%',
 '107%',
 '204%',
 '509%',
 '327%',
 '110%',
 '91%',
 '417%',
 '91%',
 '638%',
 '-32%',
 '39%',
 '37%',
 '714%',
 '507%',
 '156%',
 '356%',
 '262%',
 '-30%',
 '-5%',
 '178%',
 '568%',
 '221%',
 '237%',
 '75%',
 '18%',
 '252%']

In [127]:
# index of all 'G' system ratings
index_g = []
for i,x in enumerate(system_rating):
    if x == 'G':index_g.append(i)

In [128]:
# getiing the profit for all 'G' system rating
g_profit = []
for i in index_g:
    g_profit.append(all_actionadventure_info1.Profit[i])
g_profit

[695577621,
 671133378,
 449680774,
 115759682,
 3039258,
 72525156,
 537890267,
 57986320,
 349837368,
 362846291,
 -50923322,
 -13445453,
 30482317,
 53461527,
 109745279,
 135798265,
 9851591,
 10071069,
 63332135,
 878000000,
 362100000,
 777000000,
 26957280,
 543539607,
 94146816,
 164111171,
 -47540000,
 2852439,
 168551810,
 1396943394,
 1028261,
 19800000,
 -12848904,
 652998756,
 16610210,
 28097693,
 -18934093,
 204397798,
 3182426,
 32172482,
 164432837,
 341311860]

In [129]:
# getting the cost for 'G' system rating
cost2 = []
for i in index_g:
    cost2.append(all_actionadventure_info1.Product_budget[i])
cost2

['$250,000,000',
 '$150,000,000',
 '$150,000,000',
 '$125,000,000',
 '$100,000,000',
 '$90,000,000',
 '$220,000,000',
 '$160,000,000',
 '$150,000,000',
 '$130,000,000',
 '$130,000,000',
 '$80,000,000',
 '$60,000,000',
 '$60,000,000',
 '$50,000,000',
 '$50,000,000',
 '$40,000,000',
 '$40,000,000',
 '$39,000,000',
 '$200,000,000',
 '$200,000,000',
 '$94,000,000',
 '$60,000,000',
 '$200,000,000',
 '$50,000,000',
 '$30,000,000',
 '$90,000,000',
 '$10,000,000',
 '$34,000,000',
 '$260,000,000',
 '$250,000',
 '$50,000,000',
 '$90,000,000',
 '$80,000,00',
 '$13,000,000',
 '$37,000,000',
 '$20,000,000',
 '$46,000,000',
 '$70,000',
 '$2,777,000',
 '$150,000,000',
 '$180,000,000']

In [130]:
# getiing the name for all 'G' system rating
g_name = []
for i in index_g:
    g_name.append(all_actionadventure_info1.Name[i])
len(g_name)

42

In [131]:
# getiing the $profit for all 'G' system rating
g_dollar = []
for i in index_g:
    g_dollar.append(all_actionadventure_info1['Profit$'][i])
len(g_dollar)

42

In [132]:
# getiing the system rating for all 'G' system rating
g_sratings = []
for i in index_g:
    g_sratings.append(all_actionadventure_info1.System_ratings[i])
len(g_sratings)

42

In [133]:
# getting percentage profit for all 'G' system rating
percent_profit1 = []
for i in index_g:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit1.append(round(i,0))
percent_profit1

[278.0,
 447.0,
 300.0,
 93.0,
 3.0,
 81.0,
 244.0,
 36.0,
 233.0,
 279.0,
 -39.0,
 -17.0,
 51.0,
 89.0,
 219.0,
 272.0,
 25.0,
 25.0,
 162.0,
 439.0,
 181.0,
 827.0,
 45.0,
 272.0,
 188.0,
 547.0,
 -53.0,
 29.0,
 496.0,
 537.0,
 411.0,
 40.0,
 -14.0,
 8162.0,
 128.0,
 76.0,
 -95.0,
 444.0,
 4546.0,
 1159.0,
 110.0,
 190.0]

In [134]:
# turning float of percentage of profit into int for 'G' system rating
pp1= []
for i in percent_profit1:
    i = int(i)
    pp1.append(i)
pp1

[278,
 447,
 300,
 93,
 3,
 81,
 244,
 36,
 233,
 279,
 -39,
 -17,
 51,
 89,
 219,
 272,
 25,
 25,
 162,
 439,
 181,
 827,
 45,
 272,
 188,
 547,
 -53,
 29,
 496,
 537,
 411,
 40,
 -14,
 8162,
 128,
 76,
 -95,
 444,
 4546,
 1159,
 110,
 190]

In [135]:
# converting integer to percentage for 'G' system rating
percentage_profit1 = []
for i in pp1:
    percentage_profit1.append("{:}%".format(i))
percentage_profit1

['278%',
 '447%',
 '300%',
 '93%',
 '3%',
 '81%',
 '244%',
 '36%',
 '233%',
 '279%',
 '-39%',
 '-17%',
 '51%',
 '89%',
 '219%',
 '272%',
 '25%',
 '25%',
 '162%',
 '439%',
 '181%',
 '827%',
 '45%',
 '272%',
 '188%',
 '547%',
 '-53%',
 '29%',
 '496%',
 '537%',
 '411%',
 '40%',
 '-14%',
 '8162%',
 '128%',
 '76%',
 '-95%',
 '444%',
 '4546%',
 '1159%',
 '110%',
 '190%']

In [136]:
# index of all 'PG' system ratings
index_pg = []
for i,x in enumerate(system_rating):
    if x == 'PG':index_pg.append(i)

In [137]:
# getiing the profit for all 'PG' system rating
pg_profit = []
for i in index_pg:
    pg_profit.append(all_actionadventure_info1.Profit[i])
pg_profit

[617500281,
 984846267,
 200062763,
 364537546,
 451156389,
 629300444,
 209142722,
 514837547,
 261258433,
 494954103,
 246839614,
 -1163244,
 98370892,
 62022517,
 259000072,
 289870414,
 91325698,
 70339667,
 113877963,
 984846267,
 360155383,
 629300444,
 169631958,
 209142722,
 261258433,
 226730660,
 314043396,
 368214888,
 219150134,
 167916633,
 62022517,
 13266661,
 243629585,
 129343008,
 265300000,
 70339667,
 112910991,
 154041804,
 -6154989,
 197223430,
 221872367,
 -60376918]

In [138]:
# getting the cost for 'PG' system rating
cost3 = []
for i in index_pg:
    cost3.append(all_actionadventure_info1.Product_budget[i])
cost3

['$250,000,000',
 '$250,000,000',
 '$200,000,000',
 '$178,000,000',
 '$170,000,000',
 '$160,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$140,000,000',
 '$140,000,000',
 '$140,000,000',
 '$110,000,000',
 '$110,000,000',
 '$103,000,000',
 '$100,000,000',
 '$99,000,000',
 '$92,500,000',
 '$90,000,000',
 '$250,000,000',
 '$200,000,000',
 '$160,000,000',
 '$160,000,000',
 '$150,000,000',
 '$150,000,000',
 '$135,000,000',
 '$130,000,000',
 '$125,000,000',
 '$125,000,000',
 '$120,000,000',
 '$110,000,000',
 '$106,000,000',
 '$105,000,000',
 '$103,300,000',
 '$100,000,000',
 '$92,500,000',
 '$90,000,000',
 '$90,000,000',
 '$76,000,000',
 '$75,000,000',
 '$75,000,000',
 '$75,000,000']

In [139]:
# getiing the name for all 'PG' system rating
pg_name = []
for i in index_pg:
    pg_name.append(all_actionadventure_info1.Name[i])
len(pg_name)

42

In [140]:
# getiing the $profit for all 'PG' system rating
pg_dollar = []
for i in index_pg:
    pg_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg_dollar)

42

In [141]:
# getiing the system rating for all 'PG' system rating
pg_sratings = []
for i in index_pg:
    pg_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg_sratings)

42

In [142]:
# getting percentage profit for all 'PG' system rating
percent_profit2 = []
for i in index_pg:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit2.append(round(i,0))
percent_profit2

[247.0,
 394.0,
 100.0,
 205.0,
 265.0,
 393.0,
 139.0,
 343.0,
 174.0,
 354.0,
 176.0,
 -1.0,
 89.0,
 56.0,
 251.0,
 290.0,
 92.0,
 76.0,
 127.0,
 394.0,
 180.0,
 393.0,
 106.0,
 139.0,
 174.0,
 168.0,
 242.0,
 295.0,
 175.0,
 140.0,
 56.0,
 13.0,
 232.0,
 125.0,
 265.0,
 76.0,
 125.0,
 171.0,
 -8.0,
 263.0,
 296.0,
 -81.0]

In [143]:
# turning float of percentage of profit into int for 'PG' system rating
pp2= []
for i in percent_profit2:
    i = int(i)
    pp2.append(i)
pp2

[247,
 394,
 100,
 205,
 265,
 393,
 139,
 343,
 174,
 354,
 176,
 -1,
 89,
 56,
 251,
 290,
 92,
 76,
 127,
 394,
 180,
 393,
 106,
 139,
 174,
 168,
 242,
 295,
 175,
 140,
 56,
 13,
 232,
 125,
 265,
 76,
 125,
 171,
 -8,
 263,
 296,
 -81]

In [144]:
# converting integer to percentage for 'PG' system rating
percentage_profit2= []
for i in pp2:
    percentage_profit2.append("{:}%".format(i))
percentage_profit2

['247%',
 '394%',
 '100%',
 '205%',
 '265%',
 '393%',
 '139%',
 '343%',
 '174%',
 '354%',
 '176%',
 '-1%',
 '89%',
 '56%',
 '251%',
 '290%',
 '92%',
 '76%',
 '127%',
 '394%',
 '180%',
 '393%',
 '106%',
 '139%',
 '174%',
 '168%',
 '242%',
 '295%',
 '175%',
 '140%',
 '56%',
 '13%',
 '232%',
 '125%',
 '265%',
 '76%',
 '125%',
 '171%',
 '-8%',
 '263%',
 '296%',
 '-81%']

In [145]:
# index of all 'PG-13' system ratings
index_pg13 = []
for i,x in enumerate(system_rating):
    if x == 'PG-13':index_pg13.append(i)

In [146]:
# getiing the profit for all 'PG-13' system rating
pg13_profit = []
for i in index_pg13:
    pg13_profit.append(all_actionadventure_info1.Profit[i])
pg13_profit

[579620923,
 19535492,
 540539572,
 679235992,
 129276941,
 12297191,
 277300260,
 397938302,
 77912137,
 151896578,
 43018913,
 185986876,
 153880341,
 57910690,
 842429370,
 -68088638,
 769701857,
 72753837,
 869429616,
 429290136,
 178015029,
 48976250,
 77912137,
 122981799,
 912044677,
 346258539,
 192239672,
 153880341,
 108853353,
 256824714,
 13874967,
 310561724,
 96861183,
 53049560,
 90805525,
 -29367963,
 -75978328,
 44512771,
 -20655679,
 144519367,
 53954323,
 -9720178]

In [147]:
# getiing the name for all 'PG-13' system rating
pg13_name = []
for i in index_pg13:
    pg13_name.append(all_actionadventure_info1.Name[i])
len(pg13_name)

42

In [148]:
# getting the cost for 'PG-13' system rating
cost4 = []
for i in index_pg13:
    cost4.append(all_actionadventure_info1.Product_budget[i])
cost4

['$300,000,000',
 '$200,000,000',
 '$180,000,000',
 '$175,000,000',
 '$170,000,000',
 '$155,000,000',
 '$150,000,000',
 '$135,000,000',
 '$135,000,000',
 '$135,000,000',
 '$120,000,000',
 '$110,000,000',
 '$110,000,000',
 '$110,000,000',
 '$94,000,000',
 '$92,000,000',
 '$90,000,000',
 '$90,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$138,000,000',
 '$135,000,000',
 '$120,000,000',
 '$115,000,000',
 '$110,000,000',
 '$110,000,000',
 '$110,000,000',
 '$110,000,000',
 '$102,000,000',
 '$95,000,000',
 '$94,000,000',
 '$91,000,000',
 '$90,000,000',
 '$80,000,000',
 '$80,000,000',
 '$77,500,000',
 '$75,000,000',
 '$75,000,000',
 '$75,000,000',
 '$70,000,000',
 '$70,000,000']

In [149]:
# getiing the $profit for all 'PG-13' system rating
pg13_dollar = []
for i in index_pg13:
    pg13_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg13_dollar)

42

In [150]:
# getiing the system rating for all 'PG-13' system rating
pg13_sratings = []
for i in index_pg13:
    pg13_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg13_sratings)

42

In [151]:
# getting percentage profit for all 'PG-13' system rating
percent_profit3 = []
for i in index_pg13:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit3.append(round(i,0))
percent_profit3

[193.0,
 10.0,
 300.0,
 388.0,
 76.0,
 8.0,
 185.0,
 295.0,
 58.0,
 113.0,
 36.0,
 169.0,
 140.0,
 53.0,
 896.0,
 -74.0,
 855.0,
 81.0,
 580.0,
 286.0,
 119.0,
 35.0,
 58.0,
 102.0,
 793.0,
 315.0,
 175.0,
 140.0,
 99.0,
 252.0,
 15.0,
 330.0,
 106.0,
 59.0,
 114.0,
 -37.0,
 -98.0,
 59.0,
 -28.0,
 193.0,
 77.0,
 -14.0]

In [152]:
# turning float of percentage of profit into int
pp3= []
for i in percent_profit3:
    i = int(i)
    pp3.append(i)
pp3

[193,
 10,
 300,
 388,
 76,
 8,
 185,
 295,
 58,
 113,
 36,
 169,
 140,
 53,
 896,
 -74,
 855,
 81,
 580,
 286,
 119,
 35,
 58,
 102,
 793,
 315,
 175,
 140,
 99,
 252,
 15,
 330,
 106,
 59,
 114,
 -37,
 -98,
 59,
 -28,
 193,
 77,
 -14]

In [153]:
# converting integer to percentage
percentage_profit3= []
for i in pp3:
    percentage_profit3.append("{:}%".format(i))
percentage_profit3

['193%',
 '10%',
 '300%',
 '388%',
 '76%',
 '8%',
 '185%',
 '295%',
 '58%',
 '113%',
 '36%',
 '169%',
 '140%',
 '53%',
 '896%',
 '-74%',
 '855%',
 '81%',
 '580%',
 '286%',
 '119%',
 '35%',
 '58%',
 '102%',
 '793%',
 '315%',
 '175%',
 '140%',
 '99%',
 '252%',
 '15%',
 '330%',
 '106%',
 '59%',
 '114%',
 '-37%',
 '-98%',
 '59%',
 '-28%',
 '193%',
 '77%',
 '-14%']

In [154]:
# index of all 'NR' system ratings
index_NR = []
for i,x in enumerate(system_rating):
    if x == 'NR':index_NR.append(i)

In [155]:
# getiing the profit for all 'NR' system rating
NR_profit = []
for i in index_NR:
    NR_profit.append(all_actionadventure_info1.Profit[i])
NR_profit

[626519699,
 1148258224,
 787854547,
 623008101,
 544401889,
 141365187,
 369076069,
 195408305,
 476549695,
 137594577,
 155270083,
 128314513,
 -61583254,
 128073859,
 234942531,
 222831065,
 360004754,
 410663443,
 208711434,
 308056280,
 166192091,
 541695615,
 676680557,
 185075882,
 229504276,
 24818283,
 70936470,
 69296573,
 -14712583,
 86124621,
 199680778,
 179330185,
 476549695,
 299326618,
 224825760,
 220098020,
 247501348,
 340875846,
 137594577,
 155270083,
 30357126,
 601921271]

In [156]:
# getiing the name for all 'NR' system rating
nr_name = []
for i in index_NR:
    nr_name.append(all_actionadventure_info1.Name[i])
len(nr_name)

42

In [157]:
# getting the cost for 'NR' system rating
cost5 = []
for i in index_NR:
    cost5.append(all_actionadventure_info1.Product_budget[i])
cost5

['$210,000,000',
 '$200,000,000',
 '$175,000,000',
 '$175,000,000',
 '$170,000,000',
 '$170,000,000',
 '$160,000,000',
 '$160,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$140,000,000',
 '$138,000,000',
 '$137,500,000',
 '$132,000,000',
 '$130,000,000',
 '$125,000,000',
 '$125,000,000',
 '$120,000,000',
 '$120,000,000',
 '$120,000,000',
 '$115,000,000',
 '$110,000,000',
 '$110,000,000',
 '$110,000,000',
 '$109,000,000',
 '$100,000,000',
 '$100,000,000',
 '$100,000,000',
 '$97,000,000',
 '$95,000,000',
 '$94,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$150,000,000',
 '$149,000,000',
 '$145,000,000']

In [158]:
# getiing the $profit for all 'NR' system rating
nr_dollar = []
for i in index_NR:
    nr_dollar.append(all_actionadventure_info1['Profit$'][i])
len(nr_dollar)

42

In [159]:
# getiing the system rating for all 'NR' system rating
nr_sratings = []
for i in index_NR:
    nr_sratings.append(all_actionadventure_info1.System_ratings[i])
len(nr_sratings)

42

In [160]:
# getting percentage profit for all 'NR' system rating
percent_profit4 = []
for i in index_NR:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit4.append(round(i,0))
percent_profit4

[298.0,
 574.0,
 450.0,
 356.0,
 320.0,
 83.0,
 231.0,
 122.0,
 318.0,
 92.0,
 104.0,
 92.0,
 -45.0,
 93.0,
 178.0,
 171.0,
 288.0,
 329.0,
 174.0,
 257.0,
 138.0,
 471.0,
 615.0,
 168.0,
 209.0,
 23.0,
 71.0,
 69.0,
 -15.0,
 89.0,
 210.0,
 191.0,
 318.0,
 200.0,
 150.0,
 147.0,
 165.0,
 227.0,
 92.0,
 104.0,
 20.0,
 415.0]

In [161]:
# turning float of percentage of profit into int for 'NR' system rating
pp4= []
for i in percent_profit4:
    i = int(i)
    pp4.append(i)
pp4

[298,
 574,
 450,
 356,
 320,
 83,
 231,
 122,
 318,
 92,
 104,
 92,
 -45,
 93,
 178,
 171,
 288,
 329,
 174,
 257,
 138,
 471,
 615,
 168,
 209,
 23,
 71,
 69,
 -15,
 89,
 210,
 191,
 318,
 200,
 150,
 147,
 165,
 227,
 92,
 104,
 20,
 415]

In [162]:
# converting integer to percentage for 'NR' system rating
percentage_profit4= []
for i in pp4:
    percentage_profit4.append("{:}%".format(i))
percentage_profit4

['298%',
 '574%',
 '450%',
 '356%',
 '320%',
 '83%',
 '231%',
 '122%',
 '318%',
 '92%',
 '104%',
 '92%',
 '-45%',
 '93%',
 '178%',
 '171%',
 '288%',
 '329%',
 '174%',
 '257%',
 '138%',
 '471%',
 '615%',
 '168%',
 '209%',
 '23%',
 '71%',
 '69%',
 '-15%',
 '89%',
 '210%',
 '191%',
 '318%',
 '200%',
 '150%',
 '147%',
 '165%',
 '227%',
 '92%',
 '104%',
 '20%',
 '415%']

In [1]:
rangee = list(range(42)) # x-axis range
# allows the garph to hover over the piont to show all information about the pionts  
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,box_select,hover"

# Graph 1
source = ColumnDataSource(data=dict(
    x = rangee, # x-axis
    y = r_profit,# y-axis
    name=r_name, # name of movie
    profit=r_dollar,# profit in currency($)
    system_rating=r_sratings ,# system rating of movie
    percent_profit=percentage_profit,# profit percentage based on cost
    cost1=cost1))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name"),# the name
    ("Cost","@cost1"),# the cost
    ("Profit","@profit"),# the profit
    ("(System-Rating)","@system_rating"),# the system rating
    ("(Profit-Percentage)","@percent_profit")]# the profit percentage
p3 = figure(title='Profit.Drama.System Rating R',tools=TOOLS,plot_height=300,
           plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p3.left[0].formatter.use_scientific=False 
# makes the digits more visible by turning it into millions on the y-axis
p3.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
p3.circle('x','y',color="#054D6B",width=3,source=source)
p3.line('x','y',color="#054D6B",# the style and color of the graph
        line_dash='dashed',line_width=2,source=source)

# Graph 2
source4 = ColumnDataSource(data=dict(
     o=rangee,# x-axis
     e=g_profit,# y-axis
     name1=g_name,# name of movies
     profit1=g_dollar,# profit of movies in curreny($)
     system_rating1=g_sratings,# system rating of movie
     percent_profit1=percentage_profit1,# profit percentage based on cost
     cost2=cost2))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name1"),# the name
    ("Cost","@cost2"),# the cost
    ("Profit","@profit1"),# the profit in dollars
    ("(System-Rating)","@system_rating1"),# the system rating
    ("(Profit-Percentage)","@percent_profit1")]# the profit percentage
p4 = figure(title='Profit.Drama.System Rating G',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p4.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p4.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
# the style and color of the graph
p4.circle(x='o',y='e',color='#05C4FB',width=3,source=source4)
p4.line(x='o',y='e',color='#05C4FB',source=source4)
 
# Graph 3
source1 = ColumnDataSource(data=dict(
       p=rangee,# x-axis
       q=pg_profit,# y-axis
       name2=pg_name,# name of movies
       profit2=pg_dollar,# profit of movies in currency ($)
       system_rating2=pg_sratings,# system rating of moives
       percent_profit2=percentage_profit2,# profit percnetage based on cost
       cost3=cost3))# cost of movies
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name2"),# the name 
    ("Cost","@cost3"),# the cost
    ("Profit","@profit2"),# the profit the dollars
    ("(System-Rating)","@system_rating2"),# the system rating
    ("(Profit-Percentage)","@percent_profit2")]# the profit percentage 
p5 = figure(title='Profit.Drama.System Rating PG',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p5.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p5.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of graph
p5.square(x='p',y='q',line_color='#1215D7',fill_color=None,source=source1)
p5.line(x='p',y='q',line_color='#1215D7',source=source1)

# Graph 4
source2 = ColumnDataSource(data=dict(
       r=rangee,# x-axis
       t=pg13_profit,# y-axis
       name3=pg13_name,# name of movies
       profit3=pg13_dollar,# profit of movies to currency ($)
       system_rating3=pg13_sratings,# system rating of movies
       percent_profit3=percentage_profit3,# profit percentage based on cost
       cost4=cost4))# cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name3"),# the name
    ("Cost","@cost4"),# the cost
    ("Profit","@profit3"),# the profit in dollars
    ("(System-Rating)","@system_rating3"),# the system rating
    ("(Profit-Percentage)","@percent_profit3")]# the profit percentage
p6 = figure(title='Profit.Drama.System Rating PG-13',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
#takes away the scientific notation off the y-axis
p6.left[0].formatter.use_scientific=False
# makes the digits more visible ny turning it into millions on the y-axis
p6.yaxis[0].formatter=NumeralTickFormatter(format='$0.a')
# the style and color of the graph
p6.triangle(x='r',y='t',color='#04B2FB',width=2,source=source2)
p6.line(x='r',y='t',color='#04B2FB',width=2,source=source2)

# Graph 5
source3 = ColumnDataSource(data=dict(
        l=rangee,# x-axis
        i=NR_profit,# y-axis
        name4=nr_name,# name of movies
        profit4=nr_dollar,# profit of movies to currency ($)
        system_rating4=nr_sratings,# system rating of movies
        percent_profit4=percentage_profit4,# profit percentage based on cost
        cost5=cost5))#cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name4"),# the name
    ("Cost","@cost5"),# the cost
    ("Profit","@profit4"),# the profit in dollars
    ("(System-Rating)","@system_rating4"),# the system rating
    ("(Profit-Percentage)","@percent_profit4")]# the profit percentage
p7 = figure(title='Profit.Drama.System Rating NR',tools=TOOLS,
            plot_height=300,plot_width=300,tooltips=TOOLTIPS)
#takes away the scientiifc notation off the y-axis
p7.left[0].formatter.use_scientific=False
#makes the digits more visible by turning it into millions  on the y-axis
p7.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of the graph
p7.circle(x='l',y='i',color='#2889B2',fill_color=None,width=2,source=source3)
p7.line(x='l',y='i',color='#2889B2',width=2,source=source3)

output_file("toolbar.thml")
show(row(p3,p4,p5,p6,p7))# this puts the graphs side by side

NameError: name 'ColumnDataSource' is not defined

# Blueprint: Gross Profit Margin Percentage

This is the blueprint for creating the second visualiztion Gross Profit Margin Percentage, altair will be used to create this graph.

__Blueprint__:
 - 1. Understanding the dataframe format used to create this data visualiztion helps make the process easier, these are the key componets that make up the dataframe used for this graph.
   
    - The data frame that altair used to create this graph consist of four colunms;
     
       - Yield: This colunm is the only colunm that shows any type of informations that is in numbers 
       - Variety: This colunm is the only column that contains category or groupings among the other pionts in the dataframe
       - Year: This colunm is based on datasets that contains timeframes
       - Site: This is a colunm that pinpionts differiantion among the rest of the data pionts
       
 
 - 2. Create five dataframes for five different graphs based on the documented format that is supplied by Altair. 
   
    - The dataframes will consist of these six columns;
      
       - Name: This colunm shows the names of each movie
       - Type: The concept of this graph portrays the profit made compared to the Revenue, the two main elements that reflects that is the Revenue and the Profit ergo the 'Type' column are made up of those two elements.
       - Yield: This colunm shows how much the 'Type' column is in int, this is used to plot the pionts in the graph.
       - Type Yield: This colunm shows the 'Yield' colunm in currency which is a string, this is mostly used for the tooltip to make it easier to understand how much the elements in the 'Type' column is in dollars.
       - System Rating: This shows the System Rating of each movie.
       - Gross Profit Margin: This colunm shows the gross profit margin in percentage.
       
 
 - 3. The style of this graph is a Becker's Barkey Trellis Plot which is found in Altair's Gallery. There are two pionts shaped as a ring in each panel, the first ring projects the Renvue and the other ring projects the Profit, this set up allows the perseption of how much of a fraction do each movie actually walk away with when compared to the Revenue allowing the Profit to be seen from a differnt angle. This could make the movie look more profitable or seem over-rated. Each ring when hovered shows the Name of the movie, the Type choosing beteween Profit or Revenue, the Type Yield which is the amount of the Type in dollars, the Gross Profit Margin Percentage and the System Rating. The closer the Profit is to the Revenue the more buoyant it is!

In [101]:
# understanding how the data frame is formatted
# this was the eact dataframe used in Altairs example
from vega_datasets import data
source = data.barley()
source

        yield           variety  year             site
0    27.00000         Manchuria  1931  University Farm
1    48.86667         Manchuria  1931           Waseca
2    27.43334         Manchuria  1931           Morris
3    39.93333         Manchuria  1931        Crookston
4    32.96667         Manchuria  1931     Grand Rapids
..        ...               ...   ...              ...
115  58.16667  Wisconsin No. 38  1932           Waseca
116  47.16667  Wisconsin No. 38  1932           Morris
117  35.90000  Wisconsin No. 38  1932        Crookston
118  20.66667  Wisconsin No. 38  1932     Grand Rapids
119  29.33333  Wisconsin No. 38  1932           Duluth

[120 rows x 4 columns]

These are the variables needed to create the columns for the first dataframe; new_name,new_systems, new_total_gross, new_worldwide_gross, new_profit, new_currency_profit, gross_profit_margin_percentage.

This is all the names of the movie for the rated-R movies.

In [170]:
new_name=[]
name = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x=='R':
            name.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name):
    new_name.append( x)
new_name

['Avatar',
 'Captain America: Civil War',
 'Superman Returns',
 'The Chronicles of Narnia: Prince Caspian',
 'Men in Black 3',
 'Transformers: Age of Extinction',
 'Iron Man 3',
 'Guardians of the Galaxy Vol 2',
 'The Amazing Spider-Man 2',
 'Fantastic Beasts: The Crimes of Grindelwald',
 'Prince of Persia: Sands of Time',
 'Ralph Breaks The Internet',
 'Cars 3',
 'Jurassic World: Fallen Kingdom',
 'Inception',
 'Terminator: Genisys',
 'Chicken Little',
 'Die Another Day',
 'The Twilight Saga: Breaking Dawn, Part 2',
 'Puss in Boots',
 'Bad Boys II',
 'Batman & Robin',
 'Life of Pi',
 'Ghost Rider',
 'Star Wars Ep. III: Revenge of the Sith',
 'Windtalkers',
 'The Taking of Pelham 123',
 'Speed 2: Cruise Control',
 'The Lord of the Rings: The Fellowship of the Ring',
 'The Martian',
 '10,000 B.C.',
 'Bumblebee',
 'Planet of the Apes',
 'Land of the Lost',
 'Peter Pan',
 'The Fifth Element',
 'The Incredibles',
 'What Lies Beneath',
 'Mulan',
 'Lara Croft: Tomb Raider: The Cradle of Life',
 'Mission to Mars',
 'Horton Hears a Who']

This is all the domestic revenue of each movie in the rated-R catagory of movies.

In [171]:
new_total_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_total_gross.append(all_actionadventure_info1.Total_gross[i])
new_total_gross

[2776345279,
 1140069413,
 374085065,
 417341288,
 654213485,
 1104039076,
 1215392272,
 862316233,
 708996336,
 652220086,
 336359676,
 524283695,
 383541369,
 1305772799,
 835524642,
 432150894,
 310043823,
 431942139,
 829724737,
 554987477,
 273271982,
 238317814,
 620912003,
 229545589,
 848998877,
 77628265,
 152364370,
 150468000,
 887210985,
 655271443,
 269065678,
 465195589,
 362211740,
 69548641,
 95255485,
 263898761,
 614726752,
 288693989,
 303500000,
 157092943,
 106000000,
 299477886]

This is all the world wide revenue of each movie in the rated-R catagory of movies.

In [172]:
new_worldwide_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_worldwide_gross.append(all_actionadventure_info1.Worlwide_gross[i])
new_worldwide_gross

['$2,776,345,279',
 '$1,140,069,413',
 '$374,085,065',
 '$417,341,288',
 '$654,213,485',
 '$1,104,039,076',
 '$1,215,392,272',
 '$862,316,233',
 '$708,996,336',
 '$652,220,086',
 '$336,359,676',
 '$524,283,695',
 '$383,541,369',
 '$1,305,772,799',
 '$835,524,642',
 '$432,150,894',
 '$310,043,823',
 '$431,942,139',
 '$829,724,737',
 '$554,987,477',
 '$273,271,982',
 '$238,317,814',
 '$620,912,003',
 '$229,545,589',
 '$848,998,877',
 '$77,628,265',
 '$152,364,370',
 '$150,468,000',
 '$887,210,985',
 '$655,271,443',
 '$269,065,678',
 '$465,195,589',
 '$362,211,740',
 '$69,548,641',
 '$95,255,485',
 '$263,898,761',
 '$614,726,752',
 '$288,693,989',
 '$303,500,000',
 '$157,092,943',
 '$106,000,000',
 '$299,477,886']

This is all the profit in dollars of each movie in the rated-R catagory, this is particularly used for tooltip.

In [173]:
new_currency_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_currency_profit.append(all_actionadventure_info1['Profit$'][i])
new_currency_profit

['$2,351,345,279',
 '$890,069,413',
 '$142,085,065',
 '$192,341,288',
 '$439,213,485',
 '$894,039,076',
 '$1,015,392,272',
 '$662,316,233',
 '$508,996,336',
 '$452,220,086',
 '$136,359,676',
 '$349,283,695',
 '$208,541,369',
 '$1,135,772,799',
 '$675,524,642',
 '$277,150,894',
 '$160,043,823',
 '$289,942,139',
 '$693,524,737',
 '$424,987,477',
 '$143,271,982',
 '$113,317,814',
 '$500,912,003',
 '$109,545,589',
 '$733,998,877',
 '$-37,371,735',
 '$42,364,370',
 '$40,468,000',
 '$778,210,985',
 '$547,271,443',
 '$164,065,678',
 '$363,195,589',
 '$262,211,740',
 '$-30,451,359',
 '$-4,744,515',
 '$168,898,761',
 '$522,726,752',
 '$198,693,989',
 '$213,500,000',
 '$67,092,943',
 '$16,000,000',
 '$214,477,886']

This is all the profit in int of each mvoie in the rated-R catagory, this is particularly used for the Y and X axis.

In [174]:
new_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_profit.append(all_actionadventure_info1.Profit[i])
new_profit

[2351345279,
 890069413,
 142085065,
 192341288,
 439213485,
 894039076,
 1015392272,
 662316233,
 508996336,
 452220086,
 136359676,
 349283695,
 208541369,
 1135772799,
 675524642,
 277150894,
 160043823,
 289942139,
 693524737,
 424987477,
 143271982,
 113317814,
 500912003,
 109545589,
 733998877,
 -37371735,
 42364370,
 40468000,
 778210985,
 547271443,
 164065678,
 363195589,
 262211740,
 -30451359,
 -4744515,
 168898761,
 522726752,
 198693989,
 213500000,
 67092943,
 16000000,
 214477886]

In [175]:
# a list of rated-'r'
new_systems = list('R'*42)
len(new_systems)

42

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [176]:
# Creating the gross profit margin percentage column
p_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        p_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
p_rev

[84.6921057256582,
 78.07151063353719,
 37.98202021243483,
 46.08728959498491,
 67.13611001155074,
 80.97893411881374,
 83.54440746353536,
 76.80665255434198,
 71.79110951004971,
 69.33550433465184,
 40.539840453407976,
 66.62112484730237,
 54.372588162712645,
 86.9808897742248,
 80.85035533877168,
 64.13289845004925,
 51.61974247750132,
 67.12522646464923,
 83.58491751222792,
 76.57604803936864,
 52.42834664257677,
 47.54903215082361,
 80.67358990964779,
 47.722802898207725,
 86.45463461549431,
 -48.14191712258415,
 27.804643565946552,
 26.894755030970042,
 87.71430901523385,
 83.5182806829566,
 60.97607068263831,
 78.07373878603136,
 72.39183909389574,
 -43.78426172266975,
 -4.9808312875631255,
 64.00134671340878,
 85.03400092794399,
 68.82512160653266,
 70.34596375617792,
 42.70907509830025,
 15.09433962264151,
 71.61726993090902]

In [177]:
# turning float of percentage of profit into int
pp_rev= []
for i in p_rev:
    i = int(i)
    pp_rev.append(round(i,0))
len(pp_rev)

42

In [178]:
# converting integer to percentage
gross_profit_margin_percentage= []
for i in pp_rev:
    gross_profit_margin_percentage.append("{:}%".format(i))
len(gross_profit_margin_percentage)

42

These are the variables needed to create the columns for the second dataframe; new_name1, new_systems1, new_total_gross1, new_worldwide_gross1, new_profit1, new_currency_profit1, gross_profit_margin_percentage1

This is all the names of the movie for the rated-PG movies.

In [179]:
new_name1=[]
name1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            name1.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name1):
    new_name1.append( x)
new_name1

['Batman v Superman: Dawn of Justice',
 'The Fate of the Furious',
 'Tron: Legacy',
 'X-Men: Apocalypse',
 'Iron Man 2',
 'Fast and Furious 6',
 'Batman Begins',
 'Kung Fu Panda 2',
 'PokÃ©mon: Detective Pikachu',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Star Trek',
 'Gods of Egypt',
 'The Aviator',
 'The Divergent Series: Allegiant',
 'The Hangover 3',
 'The Wolf of Wall Street',
 'The LEGO Movie 2: The Second Part',
 'The Spiderwick Chronicles',
 'King Arthur',
 'The Fate of the Furious',
 'Cars 2',
 'Fast and Furious 6',
 'The Curious Case of Benjamin Button',
 'Batman Begins',
 'PokÃ©mon: Detective Pikachu',
 'The World is Not Enough',
 'The Bourne Ultimatum',
 'Clash of the Titans',
 'Trolls',
 'Oblivion',
 'The Divergent Series: Allegiant',
 'Allied',
 'I, Robot',
 'Gone in 60 Seconds',
 'True Lies',
 'The Spiderwick Chronicles',
 "You Don't Mess With the Zohan",
 'Pixels',
 'Children of Men',
 'Grown Ups',
 'X-Men',
 'Soldier']

This is all the domestic revenue of each movie in the rated-PG catagory of movies.

In [180]:
new_total_gross1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_total_gross1.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross1)

42

This is all the world wide revenue of each movie in the rated-PG catagory of movies.

In [181]:
new_worldwide_gross1= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_worldwide_gross1.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross1)

42

This is all the profit in dollars of each movie in the rated-PG catagory, this is particularly used for tooltip.

In [182]:
new_currency_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_currency_profit1.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit1)

42

This is all the profit in int of each mvoie in the rated-PG catagory, this is particularly used for the Y and X axis.

In [183]:
new_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_profit1.append(all_actionadventure_info1.Profit[i])
len(new_profit1)

42

In [184]:
# list of rated-'PG'
new_systems1 = []
for i in list(range(0,42)):
    new_systems1.append('PG')

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [185]:
# Creating the profit rev percentage column
p1_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        p1_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
p1_rev

[71.18156553081278,
 79.75456486519872,
 50.00784414419495,
 67.19121076276627,
 72.63169098627753,
 79.72888508852783,
 58.23387449850648,
 77.43809737027382,
 63.526583781930626,
 77.95116224329682,
 63.809290741356186,
 -0.8378501727597265,
 47.20951715271248,
 36.05488286164305,
 71.54696698513364,
 74.35045173753554,
 47.98390283586402,
 43.195658831702225,
 55.85594505866237,
 79.75456486519872,
 64.29562116695753,
 79.72888508852783,
 51.46101701704542,
 58.23387449850648,
 63.526583781930626,
 62.67941456773391,
 70.72358216087511,
 74.6560772918112,
 63.67864264728138,
 58.321268643065864,
 36.05488286164305,
 11.123528477082125,
 69.88207412173583,
 55.59720410767729,
 72.62523952915411,
 43.195658831702225,
 55.64557663611234,
 63.12107248641712,
 -8.812353111376845,
 72.4491018278625,
 74.73661804299893,
 -412.88777564127724]

In [186]:
# turning float of percentage of profit into int
pp1_rev= []
for i in p1_rev:
    i = int(i)
    pp1_rev.append(round(i,0))
len(pp1_rev)

42

In [187]:
# converting integer to percentage
gross_profit_margin_percent1= []
for i in pp1_rev:
    gross_profit_margin_percent1.append("{:}%".format(i))
gross_profit_margin_percent1
len(gross_profit_margin_percent1)

42

These are the variables needed to create the columns for the third dataframe; new_name2, new_systems2, new_total_gross2, new_worldwide_gross2, new_profit2, new_currency_profit2, gross_profit_margin_percentage2

In [188]:
new_name2=[]
name2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            name2.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name2):
    new_name2.append(x)
new_name2

['The Hobbit: The Battle of the Five Armies',
 'Wonder Woman',
 'Madagascar: Escape 2 Africa',
 'Assassinâ\x80\x99s Creed',
 'Transcendence',
 'The Magnificent Seven',
 'The Amazing Spider-Man',
 "The Sorcerer's Apprentice",
 'Dunkirk',
 'Rio 2',
 'R.I.P.D.',
 'Thirteen Days',
 'The Tale of Despereaux',
 'The Dark Tower',
 'Stepmom',
 'Inside Man',
 'Legal Eagles',
 'Fever Pitch',
 "The Time Traveler's Wife",
 'Toy Story 4',
 'Cars 2',
 'Finding Nemo',
 'The Tale of Despereaux',
 'Monsters University',
 'Herbie: Fully Loaded',
 'Wallace & Gomit: The Curse of the Were-Rabbit',
 "A Boy's Life",
 'Ozzy',
 'Ponyo',
 'The Lion King',
 'Yellow Submarine',
 'Curious George 1',
 'Fantastica: A Boonie Bears',
 'Ice Age 2: The Meltdown',
 'The Fox and the Child',
 'Space Chimps',
 'The Oegieloves',
 'Brother Bears 1',
 'Cliffords',
 'The Wizard of Oz',
 'Chicken Little',
 'Wall-E']

In [189]:
new_systems2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_systems2.append(all_actionadventure_info1.Total_gross[i])
new_systems2

[945577621,
 821133378,
 599680774,
 240759682,
 103039258,
 162525156,
 757890267,
 217986320,
 499837368,
 492846291,
 79076678,
 66554547,
 90482317,
 113461527,
 159745279,
 185798265,
 49851591,
 50071069,
 102332135,
 1078000000,
 562100000,
 871000000,
 86957280,
 743539607,
 144146816,
 194111171,
 42460000,
 12852439,
 202551810,
 1656943394,
 1278261,
 69800000,
 77151096,
 660998756,
 29610210,
 65097693,
 1065907,
 250397798,
 3252426,
 34949482,
 314432837,
 521311860]

In [190]:
new_worldwide_gross2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_worldwide_gross2.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross2)

42

In [191]:
new_currency_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_currency_profit2.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit2)

42

In [192]:
new_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_profit2.append(all_actionadventure_info1.Profit[i])
len(new_profit2)

42

In [193]:
new_systems2 = list('G'*42)
new_systems2

['G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G',
 'G']

In [194]:
# Creating the profit rev percentage column
p2_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        p2_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
p2_rev

[73.56113401503609,
 81.73256574159137,
 74.98669183614682,
 48.08100801528721,
 2.9496116907208316,
 44.623957167590724,
 70.97205102384565,
 26.600898625198134,
 69.99023890506722,
 73.62260762149066,
 -64.39739666352702,
 -20.20215538391389,
 33.68870074359391,
 47.118638725882825,
 68.70017047577349,
 73.08909208597831,
 19.76183869437587,
 20.113549003717097,
 61.888804528509056,
 81.44712430426716,
 64.41914250133428,
 89.20780711825488,
 31.000601674753398,
 73.1016346517234,
 65.31314295558217,
 84.54493894120087,
 -111.96420160150731,
 22.193756375735376,
 83.21417122858591,
 84.30845610408342,
 80.44217886644434,
 28.36676217765043,
 -16.65420799725256,
 98.78971027897063,
 56.09622491701343,
 43.162348318549476,
 -1776.3363032609784,
 81.62923141999835,
 97.84776041022917,
 92.05424561085054,
 52.29505880138085,
 65.47172358595486]

In [195]:
# turning float of percentage of profit into int
pp2_rev= []
for i in p2_rev:
    i = int(i)
    pp2_rev.append(round(i,0))
pp2_rev

[73,
 81,
 74,
 48,
 2,
 44,
 70,
 26,
 69,
 73,
 -64,
 -20,
 33,
 47,
 68,
 73,
 19,
 20,
 61,
 81,
 64,
 89,
 31,
 73,
 65,
 84,
 -111,
 22,
 83,
 84,
 80,
 28,
 -16,
 98,
 56,
 43,
 -1776,
 81,
 97,
 92,
 52,
 65]

In [196]:
# converting integer to percentage
gross_profit_margin_percentage2= []
for i in pp2_rev:
    gross_profit_margin_percentage2.append("{:}%".format(i))
gross_profit_margin_percentage2

['73%',
 '81%',
 '74%',
 '48%',
 '2%',
 '44%',
 '70%',
 '26%',
 '69%',
 '73%',
 '-64%',
 '-20%',
 '33%',
 '47%',
 '68%',
 '73%',
 '19%',
 '20%',
 '61%',
 '81%',
 '64%',
 '89%',
 '31%',
 '73%',
 '65%',
 '84%',
 '-111%',
 '22%',
 '83%',
 '84%',
 '80%',
 '28%',
 '-16%',
 '98%',
 '56%',
 '43%',
 '-1776%',
 '81%',
 '97%',
 '92%',
 '52%',
 '65%']

These are the variables needed to create the columns for the fourth dataframe; new_name3, new_systems3, new_total_gross3, new_worldwide_gross3, new_profit3, new_currency_profit3, gross_profit_margin_percentage3

In [197]:
new_name3=[]
name3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            name3.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name3):
    new_name3.append( x)
len(new_name3)

42

In [198]:
new_total_gross3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_total_gross3.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross3)

42

In [199]:
new_worldwide_gross3= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_worldwide_gross3.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross3)

42

In [200]:
new_currency_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_currency_profit3.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit3)

42

In [201]:
new_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_profit3.append(all_actionadventure_info1.Profit[i])
len(new_profit3)

42

In [202]:
new_systems3 = []
for i in list(range(0,42)):
    new_systems3.append('PG-13')

In [203]:
p3_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            p3_rev.append(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100)

len(p3_rev)

42

In [204]:
# turning float of percentage of profit into int
pp3_rev= []
for i in p3_rev:
    i = int(i)
    pp3_rev.append(round(i,0))
len(pp3_rev)

42

In [205]:
# converting integer to percentage
gross_profit_margin_percentage3= []
for i in pp3_rev:
    gross_profit_margin_percentage3.append("{:}%".format(i))
len(gross_profit_margin_percentage3)

42

These are the variables needed to create the columns for the fivth dataframe; new_name4, new_systems4, new_total_gross4, new_worldwide_gross4, new_profit4, new_currency_profit4, gross_profit_margin_percentage4

In [206]:
new_name4=[]
name4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            name4.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name4):
    new_name4.append(x)
new_name4
len(new_name4)

42

In [207]:
new_total_gross4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_total_gross4.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross4)

42

In [208]:
new_worldwide_gross4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_worldwide_gross4.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross4)

42

In [209]:
new_currency_profit4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_currency_profit4.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit4)

42

In [210]:
new_profit4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_profit4.append(all_actionadventure_info1.Profit[i])
len(new_profit4)

42

In [211]:
new_systems4 = []
for i in list(range(0,42)):
    new_systems4.append('NR')

In [212]:
p4_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            p4_rev.append(round(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100,
                                0))
p4_rev

[75.0,
 85.0,
 82.0,
 78.0,
 76.0,
 45.0,
 70.0,
 55.0,
 76.0,
 48.0,
 51.0,
 48.0,
 -81.0,
 48.0,
 64.0,
 63.0,
 74.0,
 77.0,
 63.0,
 72.0,
 58.0,
 82.0,
 86.0,
 63.0,
 68.0,
 19.0,
 41.0,
 41.0,
 -17.0,
 47.0,
 68.0,
 66.0,
 76.0,
 67.0,
 60.0,
 59.0,
 62.0,
 69.0,
 48.0,
 51.0,
 17.0,
 81.0]

In [213]:
# turning float of percentage of profit into int
pp4_rev= []
for i in p4_rev:
    i = int(i)
    pp4_rev.append(round(i,2))
pp4_rev

[75,
 85,
 82,
 78,
 76,
 45,
 70,
 55,
 76,
 48,
 51,
 48,
 -81,
 48,
 64,
 63,
 74,
 77,
 63,
 72,
 58,
 82,
 86,
 63,
 68,
 19,
 41,
 41,
 -17,
 47,
 68,
 66,
 76,
 67,
 60,
 59,
 62,
 69,
 48,
 51,
 17,
 81]

In [214]:
# converting integer to percentage
gross_profit_margin_percent4= []
for i in pp4_rev:
    gross_profit_margin_percent4.append("{:}%".format(i))
len(gross_profit_margin_percent4)

42

In [215]:
# list for type colunm
l = []
for i in list(range(0,42)):
    l.append('Revenue')
for i in list(range(0,42)):
    l.append('Profit')
len(l)

84

In [216]:
df5 = pd.DataFrame({'Name':new_name4*2,'Yield':new_total_gross4+new_profit4,'Type Yield':new_worldwide_gross4+new_currency_profit4,
                    'System Ratings':new_systems4*2,'Gross Profit Margin %':gross_profit_margin_percent4*2,'Type':l})

df4 = pd.DataFrame({'Name':new_name3*2,'Yield':new_total_gross3+new_profit3,'Type Yield':new_worldwide_gross3+new_currency_profit3,
                  'System Ratings':new_systems3*2,'Gross Profit Margin %':gross_profit_margin_percentage3*2,'Type':l})

df3 = pd.DataFrame({'Name':new_name2*2,'Yield':new_total_gross4+new_profit2,'Type Yield':new_worldwide_gross2+new_currency_profit2,
                    'System Ratings':new_systems2*2,'Gross Profit Margin %':gross_profit_margin_percentage2*2,'Type':l})

df2 = pd.DataFrame({'Name':new_name1*2,'Yield':new_total_gross1+new_profit1,'Type Yield':new_worldwide_gross1+new_currency_profit1,
                  'System Ratings':new_systems1*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

df1 = pd.DataFrame({'Name':new_name*2,'Yield':new_total_gross+new_profit,'Type Yield':new_worldwide_gross+new_currency_profit,
                    'System Ratings':new_systems*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

In [332]:
df1

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Avatar,2776345279,"$2,776,345,279",R,71%,Revenue
1,Captain America: Civil War,1140069413,"$1,140,069,413",R,79%,Revenue
2,Superman Returns,374085065,"$374,085,065",R,50%,Revenue
3,The Chronicles of Narnia: Prince Caspian,417341288,"$417,341,288",R,67%,Revenue
4,Men in Black 3,654213485,"$654,213,485",R,72%,Revenue
...,...,...,...,...,...,...
79,What Lies Beneath,198693989,"$198,693,989",R,63%,Profit
80,Mulan,213500000,"$213,500,000",R,-8%,Profit
81,Lara Croft: Tomb Raider: The Cradle of Life,67092943,"$67,092,943",R,72%,Profit
82,Mission to Mars,16000000,"$16,000,000",R,74%,Profit
83,Horton Hears a Who,214477886,"$214,477,886",R,-412%,Profit

In [333]:
df2

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Batman v Superman: Dawn of Justice,867500281,"$867,500,281",PG,71%,Revenue
1,The Fate of the Furious,1234846267,"$1,234,846,267",PG,79%,Revenue
2,Tron: Legacy,400062763,"$400,062,763",PG,50%,Revenue
3,X-Men: Apocalypse,542537546,"$542,537,546",PG,67%,Revenue
4,Iron Man 2,621156389,"$621,156,389",PG,72%,Revenue
...,...,...,...,...,...,...
79,Pixels,154041804,"$154,041,804",PG,63%,Profit
80,Children of Men,-6154989,"$-6,154,989",PG,-8%,Profit
81,Grown Ups,197223430,"$197,223,430",PG,72%,Profit
82,X-Men,221872367,"$221,872,367",PG,74%,Profit
83,Soldier,-60376918,"$-60,376,918",PG,-412%,Profit

In [334]:
df3

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,The Hobbit: The Battle of the Five Armies,836519699,"$945,577,621",G,73%,Revenue
1,Wonder Woman,1348258224,"$821,133,378",G,81%,Revenue
2,Madagascar: Escape 2 Africa,962854547,"$599,680,774",G,74%,Revenue
3,Assassinâs Creed,798008101,"$240,759,682",G,48%,Revenue
4,Transcendence,714401889,"$103,039,258",G,2%,Revenue
...,...,...,...,...,...,...
79,Brother Bears 1,204397798,"$204,397,798",G,81%,Profit
80,Cliffords,3182426,"$3,182,426",G,97%,Profit
81,The Wizard of Oz,32172482,"$32,172,482",G,92%,Profit
82,Chicken Little,164432837,"$164,432,837",G,52%,Profit
83,Wall-E,341311860,"$341,311,860",G,65%,Profit

In [335]:
df4

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Spectre,879620923,"$879,620,923",PG-13,65%,Revenue
1,Green Lantern,219535492,"$219,535,492",PG-13,8%,Revenue
2,"The Chronicles of Narnia: The Lion, the Witch ...",720539572,"$720,539,572",PG-13,75%,Revenue
3,Inside Out,854235992,"$854,235,992",PG-13,79%,Revenue
4,Godzilla: King of the Monsters,299276941,"$299,276,941",PG-13,43%,Revenue
...,...,...,...,...,...,...
79,Charlie Wilson's War,44512771,"$44,512,771",PG-13,37%,Profit
80,Spanglish,-20655679,"$-20,655,679",PG-13,-38%,Profit
81,Inferno,144519367,"$144,519,367",PG-13,65%,Profit
82,Big Fish,53954323,"$53,954,323",PG-13,43%,Profit
83,I Spy,-9720178,"$-9,720,178",PG-13,-16%,Profit

In [336]:
df5

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Transformers: Revenge of the Fallen,836519699,"$836,519,699",NR,75%,Revenue
1,Black Panther,1348258224,"$1,348,258,224",NR,85%,Revenue
2,The Jungle Book,962854547,"$962,854,547",NR,82%,Revenue
3,Coco,798008101,"$798,008,101",NR,78%,Revenue
4,Captain America: The Winter Soldier,714401889,"$714,401,889",NR,76%,Revenue
...,...,...,...,...,...,...
79,Angels & Demons,340875846,"$340,875,846",NR,69%,Profit
80,Bee Movie,137594577,"$137,594,577",NR,48%,Profit
81,Wrath of the Titans,155270083,"$155,270,083",NR,51%,Profit
82,Flushed Away,30357126,"$30,357,126",NR,17%,Profit
83,Madagascar 3: Europe's Most Wanted,601921271,"$601,921,271",NR,81%,Profit

In [235]:
# this is the first graph: this is the System R rating category
a=alt.Chart(df1).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis = alt.Axis(grid=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem PG rating category
b=alt.Chart(df2).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
        axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem G rating category
c=alt.Chart(df3).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the third graph: this is the Sytem PG-13 rating category
d=alt.Chart(df4).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,#take away the grid
       scale=alt.Scale(zero=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the fourth graph: this is the Sytem NR rating category
e=alt.Chart(df5).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,
       scale=alt.Scale(zero=False),# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

f= alt.vconcat(b,c,d,e).configure_view(strokeOpacity=0).configure_axisLeft(labelColor='#080CFE')
f&a # combines the graphs together

alt.VConcatChart(...)

# Blueprint: Budget and Revenue of Movies

This js the blueprint for creating the third visualization Budget and Revenue of Movies, altair will be used to create this graph. 

__Blueprint:__
   - The format of the dataframe needed for this graph is straight forward, based on the ideology of the persception of the chart, these are the colunms needed for thr dataframe;
        - Name,
        - System Ratings,
        - Budget,
        - Revenue,
        - Budget of Movie,
        - Renenue of Movies
   
  
  - The style of this chart is a Selection Histogram which is found in the Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis is the Revenue and the y-axis is the Budget, this set up projects wether a linear regression, meaning if the hypothesis which is, the higher the budget the higher the revenue is proven right projecting a linear regression.
  
  - The graph has an attachted histogram showing the amount of items in each category within the selection. In order to make a selection create a box by dragging the mouse. When the mouse hovers the pionts it projects the name, system rating, budget of the movies and the reevenue of the movies.

In [247]:
listt = range(0,210)

In [248]:
dataframe2 = pd.DataFrame({"Name":all_actionadventure_info1.Name,"System Rating":all_actionadventure_info1.System_ratings,"Budget":all_actionadventure_info1.Buget,'Range':listt,
                           "Revenue":all_actionadventure_info1.Total_gross,'Budget of Movie':all_actionadventure_info1.Product_budget,'Revenue of Movie':all_actionadventure_info1.Worlwide_gross})

In [238]:
#scatter graph
brush = alt.selection(type='interval')# to reate the selction box
points=alt.Chart(dataframe2).mark_circle(size=60).encode(
    x="Revenue:Q",# x-axis
    y='Budget',# y-axis
    color='System Rating', # color based on system rating put into category
    # interactive when the pionts are hovered the name, budget, revenue and system rating shows up
    tooltip=['Name','System Rating','Budget of Movie','Revenue of Movie']
).properties(height=400,width=500).add_selection(brush)# the size of graph

# histogram chart
bars=alt.Chart(dataframe2).mark_bar().encode(
        y='System Rating:N',# y-axis
        color='System Rating:N',# color put into groups based on system ratings
        x='count(Revenue):Q').transform_filter(brush)# x-axis
points&bars# graphs combined together

alt.VConcatChart(...)

# Blueprint: Revenue of Movies

This is the blueprint for creating the fourth visualization Revenue of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis shows the revenue of each movie and the y-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the revenue of the movie.

In [250]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
points1=base.mark_point(size=60).encode(
       y=alt.Y('Range',title='',axis=None),# y-axis
       x = alt.X('Revenue:Q',title='Revenue'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
x_ticks=base.mark_tick().encode(
    alt.X('Revenue',axis=tick_axis),# x-axis
    alt.Y('System Rating',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
points1&x_ticks# the two graphs combined

alt.VConcatChart(...)

# Blueprint: Budget of Movies

This is the blueprint for creating the fivth visualization Budget of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The y-axis shows the Budget of each movie and the x-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the budget of the movie.

In [251]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
pionts1=base.mark_point(size=60).encode(
       x=alt.X('Range',title='',axis=None),# y-axis
       y = alt.Y('Budget:Q',title='Budget'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
y_ticks=base.mark_tick().encode(
    alt.X('System Rating',axis=tick_axis),# x-axis
    alt.Y('Budget',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
y_ticks|pionts1# the two graphs combined

alt.HConcatChart(...)

# Blueprint: Movies that made Profit

In [427]:
dataframe = pd.DataFrame({"Name":all_actionadventure_info1.Name,"Profit":all_actionadventure_info1.Profit})

In [428]:
# get the largest movies in profit to the smallest for lollipop graph
new1 = []
for i,x in enumerate(dataframe.Profit):
    new1.append((i,x))
new1.sort(reverse=True,key=lambda x:x[1])
new1

[(0, 2351345279),
 (189, 2303109231),
 (11, 1148258224),
 (26, 1135772799),
 (12, 1015392272),
 (5, 984846267),
 (155, 912044677),
 (10, 894039076),
 (2, 890069413),
 (187, 878000000),
 (150, 869429616),
 (103, 842429370),
 (21, 787854547),
 (85, 778210985),
 (108, 769701857),
 (72, 733998877),
 (4, 695577621),
 (54, 693524737),
 (22, 679235992),
 (75, 676680557),
 (31, 675524642),
 (37, 671133378),
 (13, 662316233),
 (201, 652998756),
 (32, 629300444),
 (9, 626519699),
 (23, 623008101),
 (3, 617500281),
 (183, 601921271),
 (1, 579620923),
 (87, 547271443),
 (28, 544401889),
 (191, 543539607),
 (73, 541695615),
 (19, 540539572),
 (117, 537890267),
 (106, 522726752),
 (41, 514837547),
 (14, 508996336),
 (67, 500912003),
 (48, 494954103),
 (38, 476549695),
 (16, 452220086),
 (27, 451156389),
 (40, 449680774),
 (188, 442400000),
 (8, 439213485),
 (151, 429290136),
 (59, 424987477),
 (63, 410663443),
 (55, 397938302),
 (33, 369076069),
 (134, 368214888),
 (20, 364537546),
 (90, 363195589),
 (120, 362846291),
 (130, 360155383),
 (62, 360004754),
 (119, 349837368),
 (24, 349283695),
 (156, 346258539),
 (209, 341311860),
 (181, 340875846),
 (133, 314043396),
 (161, 310561724),
 (69, 308056280),
 (177, 299326618),
 (47, 289942139),
 (93, 289870414),
 (43, 277300260),
 (35, 277150894),
 (140, 265300000),
 (91, 262211740),
 (42, 261258433),
 (89, 259000072),
 (159, 256824714),
 (180, 247501348),
 (49, 246839614),
 (185, 243993951),
 (138, 243629585),
 (58, 234942531),
 (77, 229504276),
 (132, 226730660),
 (178, 224825760),
 (61, 222831065),
 (172, 221872367),
 (179, 220098020),
 (135, 219150134),
 (116, 214477886),
 (110, 213500000),
 (39, 209142722),
 (66, 208711434),
 (25, 208541369),
 (205, 204397798),
 (15, 200062763),
 (101, 199680778),
 (109, 198693989),
 (171, 197223430),
 (34, 195408305),
 (7, 192341288),
 (157, 192239672),
 (79, 185986876),
 (76, 185075882),
 (104, 179330185),
 (152, 178015029),
 (131, 169631958),
 (102, 168898761),
 (196, 168551810),
 (136, 167916633),
 (70, 166192091),
 (208, 164432837),
 (193, 164111171),
 (88, 164065678),
 (44, 160043823),
 (149, 158613188),
 (197, 157900000),
 (46, 155270083),
 (142, 154041804),
 (80, 153880341),
 (57, 151896578),
 (169, 144519367),
 (60, 143271982),
 (6, 142085065),
 (29, 141365187),
 (45, 137594577),
 (18, 136359676),
 (126, 135798265),
 (139, 129343008),
 (30, 129276941),
 (50, 128314513),
 (53, 128073859),
 (144, 125500000),
 (154, 122981799),
 (65, 115759682),
 (115, 113877963),
 (64, 113317814),
 (141, 112910991),
 (125, 109745279),
 (68, 109545589),
 (158, 108853353),
 (78, 98370892),
 (162, 96861183),
 (192, 94146816),
 (99, 91325698),
 (164, 90805525),
 (100, 86124621),
 (175, 83345997),
 (56, 77912137),
 (147, 72768975),
 (112, 72753837),
 (111, 72525156),
 (92, 70936470),
 (105, 70339667),
 (94, 69296573),
 (113, 67092943),
 (129, 63332135),
 (81, 62022517),
 (118, 57986320),
 (84, 57910690),
 (170, 53954323),
 (124, 53461527),
 (163, 53049560),
 (153, 48976250),
 (167, 44512771),
 (71, 43018913),
 (82, 42364370),
 (83, 40468000),
 (207, 32172482),
 (123, 30482317),
 (182, 30357126),
 (184, 28818556),
 (203, 28097693),
 (190, 26957280),
 (86, 24818283),
 (186, 22531552),
 (199, 19800000),
 (17, 19535492),
 (145, 19173475),
 (202, 16610210),
 (114, 16000000),
 (160, 13874967),
 (137, 13266661),
 (36, 12297191),
 (128, 10071069),
 (127, 9851591),
 (176, 7516819),
 (206, 3182426),
 (97, 3039258),
 (195, 2852439),
 (198, 1028261),
 (148, -800000),
 (51, -1163244),
 (96, -4744515),
 (143, -6154989),
 (174, -9720178),
 (200, -12848904),
 (122, -13445453),
 (146, -13537029),
 (98, -14712583),
 (204, -18934093),
 (168, -20655679),
 (165, -29367963),
 (95, -30451359),
 (74, -37371735),
 (194, -47540000),
 (121, -50923322),
 (173, -60376918),
 (52, -61583254),
 (107, -68088638),
 (166, -75978328)]

In [429]:
# getting the name of movies for the lollipop graph
new2 = []
for i in new1:
    new2.append(dataframe.Name[i[0]])
for i,x in enumerate(new2):
    print(i,x)

0 Avatar
1 The Sound of Music
2 Black Panther
3 Jurassic World: Fallen Kingdom
4 Iron Man 3
5 The Fate of the Furious
6 Star Wars Ep. I: The Phantom Menace
7 Transformers: Age of Extinction
8 Captain America: Civil War
9 Captain America: Civil War
10 Zootopia
11 Finding Nemo
12 The Jungle Book
13 The Lord of the Rings: The Fellowship of the Ring
14 Ice Age: Dawn of the Dinosaurs
15 Star Wars Ep. III: Revenge of the Sith
16 The Hobbit: The Battle of the Five Armies
17 The Twilight Saga: Breaking Dawn, Part 2
18 Inside Out
19 Deadpool 2
20 Inception
21 Wonder Woman
22 Guardians of the Galaxy Vol 2
23 Ice Age 2: The Meltdown
24 Fast and Furious 6
25 Transformers: Revenge of the Fallen
26 Coco
27 Batman v Superman: Dawn of Justice
28 Madagascar 3: Europe's Most Wanted
29 Spectre
30 The Martian
31 Captain America: The Winter Soldier
32 Monsters University
33 Star Wars Ep. II: Attack of the Clones
34 The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
35 The Amazing Spider-Man
36 The Incredibles
37 Kung Fu Panda 2
38 The Amazing Spider-Man 2
39 Life of Pi
40 Pirates of the Caribbean: The Curse of the Black Pearl
41 Ratatouille
42 Fantastic Beasts: The Crimes of Grindelwald
43 Iron Man 2
44 Madagascar: Escape 2 Africa
45 Cinderella
46 Men in Black 3
47 Ready Player One
48 Puss in Boots
49 Sherlock Holmes: A Game of Shadows
50 The Revenant
51 Godzilla
52 Clash of the Titans
53 X-Men: Apocalypse
54 Bumblebee
55 Rio 2
56 Cars 2
57 Teenage Mutant Ninja Turtles
58 Dunkirk
59 Ralph Breaks The Internet
60 San Andreas
61 Wall-E
62 Angels & Demons
63 The Bourne Ultimatum
64 Kingsman: The Secret Service
65 Rampage
66 Thor
67 Die Another Day
68 The Wolf of Wall Street
69 The Matrix Revolutions
70 Terminator: Genisys
71 True Lies
72 Planet of the Apes
73 PokÃ©mon: Detective Pikachu
74 The Hangover 3
75 Minority Report
76 Mission: Impossible III
77 Star Trek
78 The Adventures of Tintin
79 I, Robot
80 Penguins of Madagascar
81 Tomorrow Never Dies
82 The World is Not Enough
83 X-Men Origins: Wolverine
84 Noah
85 X-Men
86 Mad Max: Fury Road
87 Trolls
88 Horton Hears a Who
89 Mulan
90 Batman Begins
91 The Perfect Storm
92 Cars 3
93 Brother Bears 1
94 Tron: Legacy
95 Sex and the City 2
96 What Lies Beneath
97 Grown Ups
98 X-Men: First Class
99 The Chronicles of Narnia: Prince Caspian
100 Passengers
101 Miss Peregrineâs Home for Peculiar Children
102 The Divergent Series: Insurgent
103 Lara Croft: Tomb Raider
104 Bolt
105 The Curious Case of Benjamin Button
106 The Fifth Element
107 Ponyo
108 Oblivion
109 Elysium
110 Chicken Little
111 Wallace & Gomit: The Curse of the Were-Rabbit
112 10,000 B.C.
113 Chicken Little
114 The Prince of Egypt
115 Gnomeo & Juliet
116 Wrath of the Titans
117 Pixels
118 Real Steel
119 Turbo
120 Inferno
121 Bad Boys II
122 Superman Returns
123 The Polar Express
124 Bee Movie
125 Prince of Persia: Sands of Time
126 Inside Man
127 Gone in 60 Seconds
128 Godzilla: King of the Monsters
129 Exodus: Gods and Kings
130 The Incredible Hulk
131 The Sum of All Fears
132 RoboCop
133 Assassinâs Creed
134 King Arthur
135 Batman & Robin
136 You Don't Mess With the Zohan
137 Stepmom
138 Ghost Rider
139 Kingdom of Heaven
140 The Aviator
141 The Secret Life of Walter Mitty
142 Herbie: Fully Loaded
143 The LEGO Movie 2: The Second Part
144 Zookeeper
145 Gangs of New York
146 Broken Arrow
147 Master and Commander: The Far Side of the World
148 Peteâs Dragon
149 The Interpreter
150 The Magnificent Seven
151 The Other Guys
152 The Spiderwick Chronicles
153 The Emperor's New Groove
154 Lara Croft: Tomb Raider: The Cradle of Life
155 The Time Traveler's Wife
156 The Divergent Series: Allegiant
157 The Sorcerer's Apprentice
158 Ghost in the Shell
159 Big Fish
160 The Dark Tower
161 Spy Game
162 Watchmen
163 Charlie Wilson's War
164 The Island
165 The Taking of Pelham 123
166 Speed 2: Cruise Control
167 The Wizard of Oz
168 The Tale of Despereaux
169 Flushed Away
170 Miami Vice
171 Space Chimps
172 The Tale of Despereaux
173 The Cat in the Hat
174 Power Rangers
175 Curious George 1
176 Green Lantern
177 Hall Pass
178 The Fox and the Child
179 Mission to Mars
180 Seventh Son
181 Allied
182 Alexander
183 Fever Pitch
184 Legal Eagles
185 Death Race
186 Cliffords
187 Transcendence
188 Ozzy
189 Yellow Submarine
190 Random Hearts
191 Gods of Egypt
192 Peter Pan
193 Children of Men
194 I Spy
195 Fantastica: A Boonie Bears
196 Thirteen Days
197 Downsizing
198 Mortal Engines
199 The Oegieloves
200 Spanglish
201 Mighty Joe Young
202 Land of the Lost
203 Windtalkers
204 A Boy's Life
205 R.I.P.D.
206 Soldier
207 Stealth
208 The Alamo
209 Renegades

Using a for loop to put the name and profit in html code which will be pasted in the cell below.

In [436]:
for x in range(len(new2)):
    print('        }, { \n           name:',"'",new2[x],"'",','+'\n           low:',new1[x][1])

        }, {
           name: ' Avatar ' ,
           low: 2351345279
        }, {
           name: ' The Sound of Music ' ,
           low: 2303109231
        }, {
           name: ' Black Panther ' ,
           low: 1148258224
        }, {
           name: ' Jurassic World: Fallen Kingdom ' ,
           low: 1135772799
        }, {
           name: ' Iron Man 3 ' ,
           low: 1015392272
        }, {
           name: ' The Fate of the Furious ' ,
           low: 984846267
        }, {
           name: ' Star Wars Ep. I: The Phantom Menace ' ,
           low: 912044677
        }, {
           name: ' Transformers: Age of Extinction ' ,
           low: 894039076
        }, {
           name: ' Captain America: Civil War ' ,
           low: 890069413
        }, {
           name: ' Captain America: Civil War ' ,
           low: 878000000
        }, {
           name: ' Zootopia ' ,
           low: 869429616
        }, {
           name: ' Finding Nemo ' ,
           low: 842429370
        }, {
           name: ' The Jungle Book ' ,
           low: 787854547
        }, {
           name: ' The Lord of the Rings: The Fellowship of the Ring ' ,
           low: 778210985
        }, {
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, {
           name: ' Star Wars Ep. III: Revenge of the Sith ' ,
           low: 733998877
        }, {
           name: ' The Hobbit: The Battle of the Five Armies ' ,
           low: 695577621
        }, {
           name: ' The Twilight Saga: Breaking Dawn, Part 2 ' ,
           low: 693524737
        }, {
           name: ' Inside Out ' ,
           low: 679235992
        }, {
           name: ' Deadpool 2 ' ,
           low: 676680557
        }, {
           name: ' Inception ' ,
           low: 675524642
        }, {
           name: ' Wonder Woman ' ,
           low: 671133378
        }, {
           name: ' Guardians of the Galaxy Vol 2 ' ,
           low: 662316233
        }, {
           name: ' Ice Age 2: The Meltdown ' ,
           low: 652998756
        }, {
           name: ' Fast and Furious 6 ' ,
           low: 629300444
        }, {
           name: ' Transformers: Revenge of the Fallen ' ,
           low: 626519699
        }, {
           name: ' Coco ' ,
           low: 623008101
        }, {
           name: ' Batman v Superman: Dawn of Justice ' ,
           low: 617500281
        }, {
           name: ' Madagascar 3: Europe's Most Wanted ' ,
           low: 601921271
        }, {
           name: ' Spectre ' ,
           low: 579620923
        }, {
           name: ' The Martian ' ,
           low: 547271443
        }, {
           name: ' Captain America: The Winter Soldier ' ,
           low: 544401889
        }, {
           name: ' Monsters University ' ,
           low: 543539607
        }, {
           name: ' Star Wars Ep. II: Attack of the Clones ' ,
           low: 541695615
        }, {
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 540539572
        }, {
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, {
           name: ' The Incredibles ' ,
           low: 522726752
        }, {
           name: ' Kung Fu Panda 2 ' ,
           low: 514837547
        }, {
           name: ' The Amazing Spider-Man 2 ' ,
           low: 508996336
        }, {
           name: ' Life of Pi ' ,
           low: 500912003
        }, {
           name: ' Pirates of the Caribbean: The Curse of the Black Pearl ' ,
           low: 494954103
        }, {
           name: ' Ratatouille ' ,
           low: 476549695
        }, {
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 452220086
        }, {
           name: ' Iron Man 2 ' ,
           low: 451156389
        }, {
           name: ' Madagascar: Escape 2 Africa ' ,
           low: 449680774
        }, {
           name: ' Cinderella ' ,
           low: 442400000
        }, {
           name: ' Men in Black 3 ' ,
           low: 439213485
        }, {
           name: ' Ready Player One ' ,
           low: 429290136
        }, {
           name: ' Puss in Boots ' ,
           low: 424987477
        }, {
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, {
           name: ' The Revenant ' ,
           low: 397938302
        }, {
           name: ' Godzilla ' ,
           low: 369076069
        }, {
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, {
           name: ' X-Men: Apocalypse ' ,
           low: 364537546
        }, {
           name: ' Bumblebee ' ,
           low: 363195589
        }, {
           name: ' Rio 2 ' ,
           low: 362846291
        }, {
           name: ' Cars 2 ' ,
           low: 360155383
        }, {
           name: ' Teenage Mutant Ninja Turtles ' ,
           low: 360004754
        }, {
           name: ' Dunkirk ' ,
           low: 349837368
        }, {
           name: ' Ralph Breaks The Internet ' ,
           low: 349283695
        }, {
           name: ' San Andreas ' ,
           low: 346258539
        }, {
           name: ' Wall-E ' ,
           low: 341311860
        }, {
           name: ' Angels & Demons ' ,
           low: 340875846
        }, {
           name: ' The Bourne Ultimatum ' ,
           low: 314043396
        }, {
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, {
           name: ' Rampage ' ,
           low: 308056280
        }, {
           name: ' Thor ' ,
           low: 299326618
        }, {
           name: ' Die Another Day ' ,
           low: 289942139
        }, {
           name: ' The Wolf of Wall Street ' ,
           low: 289870414
        }, {
           name: ' The Matrix Revolutions ' ,
           low: 277300260
        }, {
           name: ' Terminator: Genisys ' ,
           low: 277150894
        }, {
           name: ' True Lies ' ,
           low: 265300000
        }, {
           name: ' Planet of the Apes ' ,
           low: 262211740
        }, {
           name: ' PokÃ©mon: Detective Pikachu ' ,
           low: 261258433
        }, {
           name: ' The Hangover 3 ' ,
           low: 259000072
        }, {
           name: ' Minority Report ' ,
           low: 256824714
        }, {
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, {
           name: ' Star Trek ' ,
           low: 246839614
        }, {
           name: ' The Adventures of Tintin ' ,
           low: 243993951
        }, {
           name: ' I, Robot ' ,
           low: 243629585
        }, {
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, {
           name: ' Tomorrow Never Dies ' ,
           low: 229504276
        }, {
           name: ' The World is Not Enough ' ,
           low: 226730660
        }, {
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, {
           name: ' Noah ' ,
           low: 222831065
        }, {
           name: ' X-Men ' ,
           low: 221872367
        }, {
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, {
           name: ' Trolls ' ,
           low: 219150134
        }, {
           name: ' Horton Hears a Who ' ,
           low: 214477886
        }, {
           name: ' Mulan ' ,
           low: 213500000
        }, {
           name: ' Batman Begins ' ,
           low: 209142722
        }, {
           name: ' The Perfect Storm ' ,
           low: 208711434
        }, {
           name: ' Cars 3 ' ,
           low: 208541369
        }, {
           name: ' Brother Bears 1 ' ,
           low: 204397798
        }, {
           name: ' Tron: Legacy ' ,
           low: 200062763
        }, {
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, {
           name: ' What Lies Beneath ' ,
           low: 198693989
        }, {
           name: ' Grown Ups ' ,
           low: 197223430
        }, {
           name: ' X-Men: First Class ' ,
           low: 195408305
        }, {
           name: ' The Chronicles of Narnia: Prince Caspian ' ,
           low: 192341288
        }, {
           name: ' Passengers ' ,
           low: 192239672
        }, {
           name: ' Miss Peregrineâs Home for Peculiar Children ' ,
           low: 185986876
        }, {
           name: ' The Divergent Series: Insurgent ' ,
           low: 185075882
        }, {
           name: ' Lara Croft: Tomb Raider ' ,
           low: 179330185
        }, {
           name: ' Bolt ' ,
           low: 178015029
        }, {
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, {
           name: ' The Fifth Element ' ,
           low: 168898761
        }, {
           name: ' Ponyo ' ,
           low: 168551810
        }, {
           name: ' Oblivion ' ,
           low: 167916633
        }, {
           name: ' Elysium ' ,
           low: 166192091
        }, {
           name: ' Chicken Little ' ,
           low: 164432837
        }, {
           name: ' Wallace & Gomit: The Curse of the Were-Rabbit ' ,
           low: 164111171
        }, {
           name: ' 10,000 B.C. ' ,
           low: 164065678
        }, {
           name: ' Chicken Little ' ,
           low: 160043823
        }, {
           name: ' The Prince of Egypt ' ,
           low: 158613188
        }, {
           name: ' Gnomeo & Juliet ' ,
           low: 157900000
        }, {
           name: ' Wrath of the Titans ' ,
           low: 155270083
        }, {
           name: ' Pixels ' ,
           low: 154041804
        }, {
           name: ' Real Steel ' ,
           low: 153880341
        }, {
           name: ' Turbo ' ,
           low: 151896578
        }, {
           name: ' Inferno ' ,
           low: 144519367
        }, {
           name: ' Bad Boys II ' ,
           low: 143271982
        }, {
           name: ' Superman Returns ' ,
           low: 142085065
        }, {
           name: ' The Polar Express ' ,
           low: 141365187
        }, {
           name: ' Bee Movie ' ,
           low: 137594577
        }, {
           name: ' Prince of Persia: Sands of Time ' ,
           low: 136359676
        }, {
           name: ' Inside Man ' ,
           low: 135798265
        }, {
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, {
           name: ' Godzilla: King of the Monsters ' ,
           low: 129276941
        }, {
           name: ' Exodus: Gods and Kings ' ,
           low: 128314513
        }, {
           name: ' The Incredible Hulk ' ,
           low: 128073859
        }, {
           name: ' The Sum of All Fears ' ,
           low: 125500000
        }, {
           name: ' RoboCop ' ,
           low: 122981799
        }, {
           name: ' Assassinâs Creed ' ,
           low: 115759682
        }, {
           name: ' King Arthur ' ,
           low: 113877963
        }, {
           name: ' Batman & Robin ' ,
           low: 113317814
        }, {
           name: ' You Don't Mess With the Zohan ' ,
           low: 112910991
        }, {
           name: ' Stepmom ' ,
           low: 109745279
        }, {
           name: ' Ghost Rider ' ,
           low: 109545589
        }, {
           name: ' Kingdom of Heaven ' ,
           low: 108853353
        }, {
           name: ' The Aviator ' ,
           low: 98370892
        }, {
           name: ' The Secret Life of Walter Mitty ' ,
           low: 96861183
        }, {
           name: ' Herbie: Fully Loaded ' ,
           low: 94146816
        }, {
           name: ' The LEGO Movie 2: The Second Part ' ,
           low: 91325698
        }, {
           name: ' Zookeeper ' ,
           low: 90805525
        }, {
           name: ' Gangs of New York ' ,
           low: 86124621
        }, {
           name: ' Broken Arrow ' ,
           low: 83345997
        }, {
           name: ' Master and Commander: The Far Side of the World ' ,
           low: 77912137
        }, {
           name: ' Peteâs Dragon ' ,
           low: 72768975
        }, {
           name: ' The Interpreter ' ,
           low: 72753837
        }, {
           name: ' The Magnificent Seven ' ,
           low: 72525156
        }, {
           name: ' The Other Guys ' ,
           low: 70936470
        }, {
           name: ' The Spiderwick Chronicles ' ,
           low: 70339667
        }, {
           name: ' The Emperor's New Groove ' ,
           low: 69296573
        }, {
           name: ' Lara Croft: Tomb Raider: The Cradle of Life ' ,
           low: 67092943
        }, {
           name: ' The Time Traveler's Wife ' ,
           low: 63332135
        }, {
           name: ' The Divergent Series: Allegiant ' ,
           low: 62022517
        }, {
           name: ' The Sorcerer's Apprentice ' ,
           low: 57986320
        }, {
           name: ' Ghost in the Shell ' ,
           low: 57910690
        }, {
           name: ' Big Fish ' ,
           low: 53954323
        }, {
           name: ' The Dark Tower ' ,
           low: 53461527
        }, {
           name: ' Spy Game ' ,
           low: 53049560
        }, {
           name: ' Watchmen ' ,
           low: 48976250
        }, {
           name: ' Charlie Wilson's War ' ,
           low: 44512771
        }, {
           name: ' The Island ' ,
           low: 43018913
        }, {
           name: ' The Taking of Pelham 123 ' ,
           low: 42364370
        }, {
           name: ' Speed 2: Cruise Control ' ,
           low: 40468000
        }, {
           name: ' The Wizard of Oz ' ,
           low: 32172482
        }, {
           name: ' The Tale of Despereaux ' ,
           low: 30482317
        }, {
           name: ' Flushed Away ' ,
           low: 30357126
        }, {
           name: ' Miami Vice ' ,
           low: 28818556
        }, {
           name: ' Space Chimps ' ,
           low: 28097693
        }, {
           name: ' The Tale of Despereaux ' ,
           low: 26957280
        }, {
           name: ' The Cat in the Hat ' ,
           low: 24818283
        }, {
           name: ' Power Rangers ' ,
           low: 22531552
        }, {
           name: ' Curious George 1 ' ,
           low: 19800000
        }, {
           name: ' Green Lantern ' ,
           low: 19535492
        }, {
           name: ' Hall Pass ' ,
           low: 19173475
        }, {
           name: ' The Fox and the Child ' ,
           low: 16610210
        }, {
           name: ' Mission to Mars ' ,
           low: 16000000
        }, {
           name: ' Seventh Son ' ,
           low: 13874967
        }, {
           name: ' Allied ' ,
           low: 13266661
        }, {
           name: ' Alexander ' ,
           low: 12297191
        }, {
           name: ' Fever Pitch ' ,
           low: 10071069
        }, {
           name: ' Legal Eagles ' ,
           low: 9851591
        }, {
           name: ' Death Race ' ,
           low: 7516819
        }, {
           name: ' Cliffords ' ,
           low: 3182426
        }, {
           name: ' Transcendence ' ,
           low: 3039258
        }, {
           name: ' Ozzy ' ,
           low: 2852439
        }, {
           name: ' Yellow Submarine ' ,
           low: 1028261
        }, {
           name: ' Random Hearts ' ,
           low: -800000
        }, {
           name: ' Gods of Egypt ' ,
           low: -1163244
        }, {
           name: ' Peter Pan ' ,
           low: -4744515
        }, {
           name: ' Children of Men ' ,
           low: -6154989
        }, {
           name: ' I Spy ' ,
           low: -9720178
        }, {
           name: ' Fantastica: A Boonie Bears ' ,
           low: -12848904
        }, {
           name: ' Thirteen Days ' ,
           low: -13445453
        }, {
           name: ' Downsizing ' ,
           low: -13537029
        }, {
           name: ' Mortal Engines ' ,
           low: -14712583
        }, {
           name: ' The Oegieloves ' ,
           low: -18934093
        }, {
           name: ' Spanglish ' ,
           low: -20655679
        }, {
           name: ' Mighty Joe Young ' ,
           low: -29367963
        }, {
           name: ' Land of the Lost ' ,
           low: -30451359
        }, {
           name: ' Windtalkers ' ,
           low: -37371735
        }, {
           name: ' A Boy's Life ' ,
           low: -47540000
        }, {
           name: ' R.I.P.D. ' ,
           low: -50923322
        }, {
           name: ' Soldier ' ,
           low: -60376918
        }, {
           name: ' Stealth ' ,
           low: -61583254
        }, {
           name: ' The Alamo ' ,
           low: -68088638
        }, {
           name: ' Renegades ' ,
           low: -75978328

In [439]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/dumbbell.js"></script>
<script src="https://code.highcharts.com/modules/lollipop.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="r1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [444]:
%%js
Highcharts.chart('r1', {

    chart: {
        type: 'lollipop',
        inverted:true,
        height:1600
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. {xDescription}, {point.y}.'
        }
    },

    legend: {
        enabled: true,
        layout:'vertical',
        reversed:true
    },

    subtitle: {
        text: '209 Movies'
    },

    title: {
        text: 'Action & Adventure Genre'
    },

    tooltip: {
        shared: true
    },

    xAxis: {
        type:'category',
        title:{
            text:'Movies'
        }
    },
    yAxis:{
        title:{
            text:'Profit'
        }
    },
    series: [{
        name: 'Profit',
        color:'blue',
        dataSorting:{
            enabled: false
        },
        data: [{
           name: ' Avatar ' ,
           low: 2351345279
        }, { 
           name: ' The Sound of Music ' ,
           low: 2303109231
        }, { 
           name: ' Black Panther ' ,
           low: 1148258224
        }, { 
           name: ' Jurassic World: Fallen Kingdom ' ,
           low: 1135772799
        }, { 
           name: ' Iron Man 3 ' ,
           low: 1015392272
        }, { 
           name: ' The Fate of the Furious ' ,
           low: 984846267
        }, { 
           name: ' Star Wars Ep. I: The Phantom Menace ' ,
           low: 912044677
        }, { 
           name: ' Transformers: Age of Extinction ' ,
           low: 894039076
        }, { 
           name: ' Captain America: Civil War ' ,
           low: 890069413
        }, { 
           name: ' Captain America: Civil War ' ,
           low: 878000000
        }, { 
           name: ' Zootopia ' ,
           low: 869429616
        }, { 
           name: ' Finding Nemo ' ,
           low: 842429370
        }, { 
           name: ' The Jungle Book ' ,
           low: 787854547
        }, { 
           name: ' The Lord of the Rings: The Fellowship of the Ring ' ,
           low: 778210985
        }, { 
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, { 
           name: ' Star Wars Ep. III: Revenge of the Sith ' ,
           low: 733998877
        }, { 
           name: ' The Hobbit: The Battle of the Five Armies ' ,
           low: 695577621
        }, { 
           name: ' The Twilight Saga: Breaking Dawn, Part 2 ' ,
           low: 693524737
        }, { 
           name: ' Inside Out ' ,
           low: 679235992
        }, { 
           name: ' Deadpool 2 ' ,
           low: 676680557
        }, { 
           name: ' Inception ' ,
           low: 675524642
        }, { 
           name: ' Wonder Woman ' ,
           low: 671133378
        }, { 
           name: ' Guardians of the Galaxy Vol 2 ' ,
           low: 662316233
        }, { 
           name: ' Ice Age 2: The Meltdown ' ,
           low: 652998756
        }, { 
           name: ' Fast and Furious 6 ' ,
           low: 629300444
        }, { 
           name: ' Transformers: Revenge of the Fallen ' ,
           low: 626519699
        }, { 
           name: ' Coco ' ,
           low: 623008101
        }, { 
           name: ' Batman v Superman: Dawn of Justice ' ,
           low: 617500281
        }, { 
           name: ' Madagascar 3: Europe\'s Most Wanted ' ,
           low: 601921271
        }, { 
           name: ' Spectre ' ,
           low: 579620923
        }, { 
           name: ' The Martian ' ,
           low: 547271443
        }, { 
           name: ' Captain America: The Winter Soldier ' ,
           low: 544401889
        }, { 
           name: ' Monsters University ' ,
           low: 543539607
        }, { 
           name: ' Star Wars Ep. II: Attack of the Clones ' ,
           low: 541695615
        }, { 
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 540539572
        }, { 
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, { 
           name: ' The Incredibles ' ,
           low: 522726752
        }, { 
           name: ' Kung Fu Panda 2 ' ,
           low: 514837547
        }, { 
           name: ' The Amazing Spider-Man 2 ' ,
           low: 508996336
        }, { 
           name: ' Life of Pi ' ,
           low: 500912003
        }, { 
           name: ' Pirates of the Caribbean: The Curse of the Black Pearl ' ,
           low: 494954103
        }, { 
           name: ' Ratatouille ' ,
           low: 476549695
        }, { 
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 452220086
        }, { 
           name: ' Iron Man 2 ' ,
           low: 451156389
        }, { 
           name: ' Madagascar: Escape 2 Africa ' ,
           low: 449680774
        }, { 
           name: ' Cinderella ' ,
           low: 442400000
        }, { 
           name: ' Men in Black 3 ' ,
           low: 439213485
        }, { 
           name: ' Ready Player One ' ,
           low: 429290136
        }, { 
           name: ' Puss in Boots ' ,
           low: 424987477
        }, { 
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, { 
           name: ' The Revenant ' ,
           low: 397938302
        }, { 
           name: ' Godzilla ' ,
           low: 369076069
        }, { 
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, { 
           name: ' X-Men: Apocalypse ' ,
           low: 364537546
        }, { 
           name: ' Bumblebee ' ,
           low: 363195589
        }, { 
           name: ' Rio 2 ' ,
           low: 362846291
        }, { 
           name: ' Cars 2 ' ,
           low: 360155383
        }, { 
           name: ' Teenage Mutant Ninja Turtles ' ,
           low: 360004754
        }, { 
           name: ' Dunkirk ' ,
           low: 349837368
        }, { 
           name: ' Ralph Breaks The Internet ' ,
           low: 349283695
        }, { 
           name: ' San Andreas ' ,
           low: 346258539
        }, { 
           name: ' Wall-E ' ,
           low: 341311860
        }, { 
           name: ' Angels & Demons ' ,
           low: 340875846
        }, { 
           name: ' The Bourne Ultimatum ' ,
           low: 314043396
        }, { 
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, { 
           name: ' Rampage ' ,
           low: 308056280
        }, { 
           name: ' Thor ' ,
           low: 299326618
        }, { 
           name: ' Die Another Day ' ,
           low: 289942139
        }, { 
           name: ' The Wolf of Wall Street ' ,
           low: 289870414
        }, { 
           name: ' The Matrix Revolutions ' ,
           low: 277300260
        }, { 
           name: ' Terminator: Genisys ' ,
           low: 277150894
        }, { 
           name: ' True Lies ' ,
           low: 265300000
        }, { 
           name: ' Planet of the Apes ' ,
           low: 262211740
        }, { 
           name: ' PokÃ©mon: Detective Pikachu ' ,
           low: 261258433
        }, { 
           name: ' The Hangover 3 ' ,
           low: 259000072
        }, { 
           name: ' Minority Report ' ,
           low: 256824714
        }, { 
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, { 
           name: ' Star Trek ' ,
           low: 246839614
        }, { 
           name: ' The Adventures of Tintin ' ,
           low: 243993951
        }, { 
           name: ' I, Robot ' ,
           low: 243629585
        }, { 
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, { 
           name: ' Tomorrow Never Dies ' ,
           low: 229504276
        }, { 
           name: ' The World is Not Enough ' ,
           low: 226730660
        }, { 
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, { 
           name: ' Noah ' ,
           low: 222831065
        }, { 
           name: ' X-Men ' ,
           low: 221872367
        }, { 
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, { 
           name: ' Trolls ' ,
           low: 219150134
        }, { 
           name: ' Horton Hears a Who ' ,
           low: 214477886
        }, { 
           name: ' Mulan ' ,
           low: 213500000
        }, { 
           name: ' Batman Begins ' ,
           low: 209142722
        }, { 
           name: ' The Perfect Storm ' ,
           low: 208711434
        }, { 
           name: ' Cars 3 ' ,
           low: 208541369
        }, { 
           name: ' Brother Bears 1 ' ,
           low: 204397798
        }, { 
           name: ' Tron: Legacy ' ,
           low: 200062763
        }, { 
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, { 
           name: ' What Lies Beneath ' ,
           low: 198693989
        }, { 
           name: ' Grown Ups ' ,
           low: 197223430
        }, { 
           name: ' X-Men: First Class ' ,
           low: 195408305
        }, { 
           name: ' The Chronicles of Narnia: Prince Caspian ' ,
           low: 192341288
        }, { 
           name: ' Passengers ' ,
           low: 192239672
        }, { 
           name: ' Miss Peregrineâs Home for Peculiar Children ' ,
           low: 185986876
        }, { 
           name: ' The Divergent Series: Insurgent ' ,
           low: 185075882
        }, { 
           name: ' Lara Croft: Tomb Raider ' ,
           low: 179330185
        }, { 
           name: ' Bolt ' ,
           low: 178015029
        }, { 
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, { 
           name: ' The Fifth Element ' ,
           low: 168898761
        }, { 
           name: ' Ponyo ' ,
           low: 168551810
        }, { 
           name: ' Oblivion ' ,
           low: 167916633
        }, { 
           name: ' Elysium ' ,
           low: 166192091
        }, { 
           name: ' Chicken Little ' ,
           low: 164432837
        }, { 
           name: ' Wallace & Gomit: The Curse of the Were-Rabbit ' ,
           low: 164111171
        }, { 
           name: ' 10,000 B.C. ' ,
           low: 164065678
        }, { 
           name: ' Chicken Little ' ,
           low: 160043823
        }, { 
           name: ' The Prince of Egypt ' ,
           low: 158613188
        }, { 
           name: ' Gnomeo & Juliet ' ,
           low: 157900000
        }, { 
           name: ' Wrath of the Titans ' ,
           low: 155270083
        }, { 
           name: ' Pixels ' ,
           low: 154041804
        }, { 
           name: ' Real Steel ' ,
           low: 153880341
        }, { 
           name: ' Turbo ' ,
           low: 151896578
        }, { 
           name: ' Inferno ' ,
           low: 144519367
        }, { 
           name: ' Bad Boys II ' ,
           low: 143271982
        }, { 
           name: ' Superman Returns ' ,
           low: 142085065
        }, { 
           name: ' The Polar Express ' ,
           low: 141365187
        }, { 
           name: ' Bee Movie ' ,
           low: 137594577
        }, { 
           name: ' Prince of Persia: Sands of Time ' ,
           low: 136359676
        }, { 
           name: ' Inside Man ' ,
           low: 135798265
        }, { 
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, { 
           name: ' Godzilla: King of the Monsters ' ,
           low: 129276941
        }, { 
           name: ' Exodus: Gods and Kings ' ,
           low: 128314513
        }, { 
           name: ' The Incredible Hulk ' ,
           low: 128073859
        }, { 
           name: ' The Sum of All Fears ' ,
           low: 125500000
        }, { 
           name: ' RoboCop ' ,
           low: 122981799
        }, { 
           name: ' Assassinâs Creed ' ,
           low: 115759682
        }, { 
           name: ' King Arthur ' ,
           low: 113877963
        }, { 
           name: ' Batman & Robin ' ,
           low: 113317814
        }, { 
           name: ' You Don\'t Mess With the Zohan ' ,
           low: 112910991
        }, { 
           name: ' Stepmom ' ,
           low: 109745279
        }, { 
           name: ' Ghost Rider ' ,
           low: 109545589
        }, { 
           name: ' Kingdom of Heaven ' ,
           low: 108853353
        }, { 
           name: ' The Aviator ' ,
           low: 98370892
        }, { 
           name: ' The Secret Life of Walter Mitty ' ,
           low: 96861183
        }, { 
           name: ' Herbie: Fully Loaded ' ,
           low: 94146816
        }, { 
           name: ' The LEGO Movie 2: The Second Part ' ,
           low: 91325698
        }, { 
           name: ' Zookeeper ' ,
           low: 90805525
        }, { 
           name: ' Gangs of New York ' ,
           low: 86124621
        }, { 
           name: ' Broken Arrow ' ,
           low: 83345997
        }, { 
           name: ' Master and Commander: The Far Side of the World ' ,
           low: 77912137
        }, { 
           name: ' Peteâs Dragon ' ,
           low: 72768975
        }, { 
           name: ' The Interpreter ' ,
           low: 72753837
        }, { 
           name: ' The Magnificent Seven ' ,
           low: 72525156
        }, { 
           name: ' The Other Guys ' ,
           low: 70936470
        }, { 
           name: ' The Spiderwick Chronicles ' ,
           low: 70339667
        }, { 
           name: ' The Emperor\'s New Groove ' ,
           low: 69296573
        }, { 
           name: ' Lara Croft: Tomb Raider: The Cradle of Life ' ,
           low: 67092943
        }, { 
           name: ' The Time Traveler\'s Wife ' ,
           low: 63332135
        }, { 
           name: ' The Divergent Series: Allegiant ' ,
           low: 62022517
        }, { 
           name: ' The Sorcerer\'s Apprentice ' ,
           low: 57986320
        }, { 
           name: ' Ghost in the Shell ' ,
           low: 57910690
        }, { 
           name: ' Big Fish ' ,
           low: 53954323
        }, { 
           name: ' The Dark Tower ' ,
           low: 53461527
        }, { 
           name: ' Spy Game ' ,
           low: 53049560
        }, { 
           name: ' Watchmen ' ,
           low: 48976250
        }, { 
           name: ' Charlie Wilson\'s War ' ,
           low: 44512771
        }, { 
           name: ' The Island ' ,
           low: 43018913
        }, { 
           name: ' The Taking of Pelham 123 ' ,
           low: 42364370
        }, { 
           name: ' Speed 2: Cruise Control ' ,
           low: 40468000
        }, { 
           name: ' The Wizard of Oz ' ,
           low: 32172482
        }, { 
           name: ' The Tale of Despereaux ' ,
           low: 30482317
        }, { 
           name: ' Flushed Away ' ,
           low: 30357126
        }, { 
           name: ' Miami Vice ' ,
           low: 28818556
        }, { 
           name: ' Space Chimps ' ,
           low: 28097693
        }, { 
           name: ' The Tale of Despereaux ' ,
           low: 26957280
        }, { 
           name: ' The Cat in the Hat ' ,
           low: 24818283
        }, { 
           name: ' Power Rangers ' ,
           low: 22531552
        }, { 
           name: ' Curious George 1 ' ,
           low: 19800000
        }, { 
           name: ' Green Lantern ' ,
           low: 19535492
        }, { 
           name: ' Hall Pass ' ,
           low: 19173475
        }, { 
           name: ' The Fox and the Child ' ,
           low: 16610210
        }, { 
           name: ' Mission to Mars ' ,
           low: 16000000
        }, { 
           name: ' Seventh Son ' ,
           low: 13874967
        }, { 
           name: ' Allied ' ,
           low: 13266661
        }, { 
           name: ' Alexander ' ,
           low: 12297191
        }, { 
           name: ' Fever Pitch ' ,
           low: 10071069
        }, { 
           name: ' Legal Eagles ' ,
           low: 9851591
        }, { 
           name: ' Death Race ' ,
           low: 7516819
        }, { 
           name: ' Cliffords ' ,
           low: 3182426
        }, { 
           name: ' Transcendence ' ,
           low: 3039258
        }, { 
           name: ' Ozzy ' ,
           low: 2852439
        }, { 
           name: ' Yellow Submarine ' ,
           low: 1028261
        }]
    }]
});

In [76]:
# getting the Cost
new3 = []
for i in new1:
    new3.append(all_actionadventure_info1.Buget[i[0]])
new3

[200000000,
 306000000,
 190000000,
 330600000,
 317000000,
 160000000,
 125000000,
 225000000,
 150000000,
 150000000,
 175000000,
 180000000,
 300000000,
 160000000,
 258000000,
 410600000,
 185000000,
 127500000,
 230000000,
 151000000,
 145000000,
 150000000,
 165000000,
 125000000,
 127000000,
 150000000,
 165000000,
 110000000,
 225000000,
 135000000,
 125000000,
 90000000,
 90000000,
 65000000,
 60000000,
 140000000,
 65000000,
 70000000,
 85000000,
 300000000,
 103000000,
 207000000,
 152000000,
 98000000,
 150000000,
 130000000,
 61000000,
 115000000,
 150000000,
 75000000,
 55000000,
 90000000,
 70000000,
 85000000,
 125000000,
 190000000,
 90000000,
 80000000,
 100000000,
 90000000,
 125000000,
 87500000,
 130000000,
 70000000,
 175000000,
 70000000,
 135000000,
 85000000,
 190000000,
 175000000,
 90000000,
 65000000,
 60000000,
 85000000,
 90000000,
 125000000,
 150000000,
 70000000,
 150000000,
 100000000,
 130000000,
 90000000,
 40000000,
 65000000,
 90000000,
 90000000,
 85000000,
 70000000,
 50000000,
 60000000,
 58000000,
 66000000,
 68000000,
 120000000,
 275000000,
 65000000,
 90000000,
 54000000,
 90000000,
 135000000,
 102500000,
 50000000,
 110000000,
 50000000,
 70000000,
 110000000,
 70000000,
 60000000,
 60000000,
 65000000,
 65000000,
 90000000,
 150000000,
 62000000,
 130000000,
 144000000,
 65000000,
 38000000,
 50200000,
 65000000,
 61000000,
 100000000,
 67500000,
 65000000,
 65000000,
 39000000,
 86000000,
 160000000,
 60000000,
 40000000,
 60000000,
 60000000,
 48000000,
 60000000,
 72500000,
 170000000,
 70000000,
 60000000,
 60000000,
 90000000,
 42000000,
 100000000,
 49000000,
 135000000,
 60000000,
 120000000,
 160000000,
 68000000,
 70000000,
 110000000,
 100000000,
 72500000,
 106000000,
 50000000,
 40000000,
 40000000,
 65000000,
 68000000,
 65000000,
 195000000,
 180000000,
 95000000,
 64000000,
 175000000,
 100000000,
 100000000,
 45000000,
 50000000,
 68000000,
 65000000,
 100000000,
 40000000,
 70000000,
 70000000,
 40000000,
 45000000,
 80000000,
 68000000,
 65000000,
 72000000,
 40000000,
 40000000,
 109000000,
 46500000,
 145000000,
 40000000,
 40000000,
 40000000,
 65000000,
 65000000,
 40000000,
 52000000,
 40000000,
 40000000,
 55000000,
 65000000,
 40000000,
 45000000,
 49800000,
 130000000,
 137000000,
 75000000,
 120000000,
 75000000,
 90000000,
 90000000,
 105000000,
 110000000,
 350000000]

In [77]:
# getting the Rev
new4 = []
for i in new1:
    new4.append(all_actionadventure_info1.Total_gross[i[0]])
new4

[2208208395,
 2053311220,
 1518722794,
 1403013963,
 1316721747,
 1146894640,
 975047606,
 1066215812,
 943076457,
 897099794,
 880166350,
 846980024,
 963420425,
 807330936,
 894860230,
 1045663875,
 786635413,
 689420051,
 788241137,
 708272592,
 694713230,
 688858992,
 676404566,
 630163454,
 615461394,
 637517365,
 652127828,
 563749323,
 667999518,
 573068425,
 556319450,
 511358276,
 498438212,
 463517383,
 454161935,
 517599142,
 442169052,
 443483213,
 450728529,
 655945209,
 457683805,
 550517357,
 489592267,
 435040395,
 475825484,
 444043396,
 368567189,
 416456852,
 449326618,
 371917043,
 345922730,
 375381768,
 351500000,
 363064265,
 402448265,
 467381584,
 366101666,
 349088523,
 365300000,
 347425832,
 376000000,
 333132750,
 373993951,
 300854823,
 405760225,
 297115976,
 361730660,
 311001124,
 411002906,
 381687380,
 289660619,
 261400000,
 253555383,
 276014965,
 273477501,
 304115534,
 328015029,
 239814025,
 319713881,
 262794441,
 290650494,
 249517956,
 197115710,
 221297061,
 239373970,
 235900000,
 224614744,
 207068340,
 185798265,
 195194085,
 188715611,
 194169619,
 193500000,
 242981799,
 393151347,
 180148897,
 203932174,
 166617328,
 200859554,
 245724600,
 212282709,
 159745279,
 218853353,
 156399644,
 175807183,
 215300000,
 172543519,
 159946489,
 159356941,
 163527824,
 163295654,
 186049020,
 238202668,
 147864886,
 215080810,
 229008658,
 148345997,
 120000000,
 126931325,
 137768975,
 132493015,
 171377916,
 137489730,
 128874043,
 128468793,
 102332135,
 148715342,
 217986320,
 113461527,
 92256918,
 111946251,
 105203825,
 90376224,
 99823958,
 109362966,
 206627518,
 103735965,
 90723216,
 90482317,
 120100000,
 71000000,
 126704591,
 72689126,
 157956466,
 82812456,
 142531552,
 181674817,
 87173475,
 88933562,
 127983283,
 115149422,
 86509602,
 119266661,
 62967368,
 50071069,
 49851591,
 74575290,
 77224232,
 72516819,
 197687603,
 180047784,
 94894448,
 63200000,
 174131329,
 98227017,
 97523020,
 41467606,
 46112640,
 60265197,
 56824633,
 91800000,
 31124367,
 60279822,
 58953319,
 26736665,
 31681811,
 66554547,
 54462971,
 48164150,
 54616869,
 21215882,
 19756077,
 87683966,
 23726626,
 121671925,
 16340767,
 14938149,
 14358033,
 39017984,
 38253433,
 13208023,
 23010607,
 10717421,
 7974607,
 22597969,
 26670920,
 734423,
 73706,
 0,
 79076678,
 85131830,
 14623082,
 49628177,
 0,
 10551417,
 0,
 10364769,
 3100000,
 149762350]

In [442]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="w1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [443]:
%%js
Highcharts.chart('w1',{
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        categories:['The Lovely Bones','Random hearts','Evan Almighty','Jin LAadng shAxad san',
'Green Zone','Dredd','For Love of the Game','The Insider','Elektra',
'Treasure Planet','Victor Frankenstein','I Spy','The Legend of Hercules',
'Baahubali: The Beginning','Pinocchio','Thirteen Days','Downsizing',
'Red Dawn','Driven','New York Mintue','Amelia','Ali','Silence',
'Sahara'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    colors:['#5179D6','#2F5E8C','#33CCFF'],
    yAxis:{
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        name:'Cost',
        data:[95000000,64000000,175000000,100000000,100000000,45000000,
             50000000,60000000,65000000,100000000,40000000,70000000,
             70000000,40000000,45000000,80000000,68000000,65000000,
             72000000,40000000,109000000,46500000,145000000]
    },{
        name:'Loss',
        data:[-105552,-800000,-868671,-1772983,-2476980,-3532394,
             -3887360,-7734803,-8175367,-8200000,-8875633,-9720178,
             -11046681,-13263335,-13318189,-13445453,-13537029,-16835850,
             -17383131,-18784118,-20243923,-21316034,-22773374,-23328075]
    },{
        name:'Revenue',
        data:[94894448,63200000,174131329,98227017,97523020,41467606,46112640,60265197,56824633,
             91800000,31124367,60279822,58953319,26736665,31681811,66554547,54462971,48164150,
             54616869,21215882,19756077,87683966,23726626,121671925]
    }]
});

In [5]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="f1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [6]:
%%js
Highcharts.chart('f1',{
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        categories:['Paranoia','The Hudsucker Proxy','Memoirs of an Invisible Man',
'Primary Colors','The Missing','FearDotCom','Bulletproof Monk','Universal Soldier II: The Return',
'Impostor','Bullet to the Head','Oliver Twist','Dragon Nest Warriors Dawn','FoodFight!',
'Ad Astra','R.I.P.D','Final Fantasy: The Spirits Within','Soldier','How Do You Know? ',
'355','The Promise','Army of the Dead','Town & Country', 'Men in Black: International','Dark Pheonix'],
        labels:{
           enabled:false
        }},
    yAxis:{
        labels:{
            enabled:true
        }
    },
    credits:{
        enabled:false
    },
    colors:['#5179D6','#2F5E8C','#33CCFF'],
    series:[{
        name:'Cost',
        data:[40000000,40000000,40000000,65000000,65000000,40000000,52000000,
             40000000,40000000,55000000,65000000,40000000,45000000,49800000,
             130000000,137000000,75000000,120000000,75000000,90000000,
             90000000,105000000,110000000,350000000]
    },{
        name:'Loss',
        data:[-23659233,-25061851,-25641967,-25982016,-26746567,-26791977,
             -28989393,-29282579,-32025393,-32402031,-38329080,-39265577,
             -44926294,-49800000,-50923322,-51868170,-60376918,-70371823,
             -75000000,-79448583,-90000000,-94635231,-106900000,-200237650]
    },{
        name:'Revenue',
        data:[16340767,14938149,14358033,39017984,38253433,13208023,23010607,
             10717421,7974607,22597969,26670920,734423,73706,0,79076678,85131830,
             14623082,49628177,0,10551417,0,10364769,3100000,149762350]
    }]
});

In [9]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="httos://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="b1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [10]:
%%js
new Highcharts.chart('b1',{
    chart:{
        type:'cylinder',
        options3d:{
            enabled:true,
            alpha:15,
            beta:16,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Highest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Highest Profit',
        color:'#0080FF',
           data:[
            ['Avatar|1st Highest',2008208295],
            ['The Sound of Music|2nd Highest',1747311220],
            ['The Lion King|3rd Highest',1328722794],
            ['Black Panther|4th Highest',1072413963],
            ['Jurassic World: Fallen Kingdom|5th Highest',999721747],
            ['Iron Man 3|6th Highest',986894640],
            ['The Fate of the Furious|7th Highest',850047606],
            ['Star Wars Ep. I: The Phantom Menace |8th Highest ',841215812],
            ['Inside Out: Age of Extinction|9th Highest',793076457],
            ['Captain America: Civil War|10th Highest',747099794],
            ['Toy Story 4|11th Highest',705166350],
            ['Zootopia|12th Highest',666980024],
            ['Finding Nemo|13th Highest',663420425],
            ['The Jungle Book|14th Highest',647330936],
            ['The Lord of the Rings: The Fellowship of the Ring|15th Highest',636860230],
            ['Ice Age: Dawn of the Dinosaurs|16th Highest',635063875],
            ['Star Wars Ep. III: Revenge of the Sith|17th Highest',601635413],
            ['The Hobbit: The Battle of the Five Armies|18th Highest',561920051],
            ['The Twilight Saga: Breaking Dawn, Part 2|19th Highest',558241137],
            ['Inside Out|20th Highest',557272592]
         ]
    }]
        
});

In [11]:
%%HTML
<script src="https://code.jpuery.com/jpuery-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="c1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [12]:
%%js
Highcharts.chart('c1',{
    chart:{
        type:'column',
        options3d:{
            enabled:true,
            alpha:15,
            beta:25,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Lowest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Lowest Profits',
        color :'#0F52BA',
           data:[
            ['Hugo|1st Lowest',47784],
            ['Jack the Giant Slayer|2nd Lowset',2587603],
            ['Death Race|3rd Lowest',7516819],
            ['Money Train|4th Lowest',9224232],
            ['I Frankenstein|5th Lowest',9575290], 
            ['Legal Eagles|6th Lowest',9851591],
            ['Fever Pitch|7th Lowest',10071069],
            ['The Peacemaker|8th Lowest',12967368],
            ['Allied|9th Lowest',13266661],
            ['The Kingdom|10th Lowest',14009602],
            ['Wonder Park|11th Lowest',15149422],
            ['Enders Game|12th Lowest',17983283],
            ['Rumor Has It|13th Lowest',18933562],
            ['Hall Pass|14th Lowest',19173475],
            ['Poseidon|15th Lowest',21674817],
            ['Power Rangers|16th Lowest',22531552],
            ['Edge of Darkness|17th Lowest',22812456],
            ['Happy Feet Two|18th Lowest',22956466],
            ['The One|19th Lowest',23689126],
            ['Piont Break|20th Lowest',26704591]
         ]
    }]
        
});

In [79]:
#getting profit percent by cost
new5 = []
for i in new1:
    new5.append(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Buget[i[0]]
         *100)
new5

[1004.1041975,
 571.0167385620915,
 699.3277863157895,
 324.38413883847545,
 315.3696362776025,
 616.80915,
 680.0380848,
 373.87369422222224,
 528.717638,
 498.0665293333334,
 402.9522,
 370.5444577777778,
 221.14014166666664,
 404.581835,
 246.84505038759693,
 154.6672856794934,
 325.2083313513514,
 440.721608627451,
 242.71353782608696,
 369.0546966887417,
 379.1125724137931,
 359.239328,
 309.94216121212116,
 404.1307632,
 384.6152708661417,
 325.01157666666666,
 295.2289866666667,
 412.4993845454545,
 196.88867466666667,
 324.4951296296296,
 345.05556,
 468.17586222222224,
 453.8202355555556,
 613.1036661538461,
 656.9365583333333,
 269.71367285714285,
 580.2600799999999,
 533.5474471428571,
 430.26885764705884,
 118.64840299999999,
 344.35320873786407,
 165.95041400966184,
 222.10017565789474,
 343.91877040816325,
 217.21698933333334,
 241.5718430769231,
 504.20850655737706,
 262.1363930434783,
 199.55107866666665,
 395.8893906666667,
 528.9504181818182,
 317.0908533333333,
 402.1428571428571,
 327.1344294117647,
 221.95861200000002,
 145.99030736842104,
 306.77962888888885,
 336.36065375,
 265.3,
 286.02870222222225,
 200.8,
 280.7231428571428,
 187.68765461538462,
 329.7926042857143,
 131.8629857142857,
 324.4513942857143,
 167.94863703703703,
 265.88367529411767,
 116.31731894736843,
 118.10707428571428,
 221.84513222222222,
 302.1538461538462,
 322.592305,
 224.7234882352941,
 203.86389,
 143.2924272,
 118.676686,
 242.59146428571427,
 113.14258733333334,
 162.794441,
 123.57730307692307,
 177.24217333333334,
 392.789275,
 240.4570169230769,
 165.97107777777777,
 162.11111111111111,
 164.25263999999999,
 195.8119142857143,
 271.59653000000003,
 225.32347499999997,
 225.37174310344827,
 194.19639242424242,
 184.55882352941177,
 102.4848325,
 42.96412618181818,
 177.15214923076923,
 126.59130444444445,
 208.5506074074074,
 123.17728222222222,
 82.01822222222222,
 107.1050819512195,
 219.490558,
 98.95759363636364,
 212.799288,
 151.15311857142856,
 95.72727272727273,
 146.49074142857143,
 166.57748166666667,
 165.59490166666666,
 151.58126769230768,
 151.22408307692308,
 106.72113333333333,
 58.80177866666667,
 138.49175161290324,
 65.44677692307692,
 59.033790277777776,
 128.22461076923076,
 215.78947368421052,
 152.8512450199203,
 111.95226923076925,
 117.20166393442624,
 71.377916,
 103.68848888888888,
 98.26775846153846,
 97.64429692307692,
 162.39008974358975,
 72.92481627906977,
 36.24145,
 89.102545,
 130.642295,
 86.577085,
 75.33970833333333,
 88.2838,
 66.37326333333333,
 50.84547034482758,
 21.54559882352941,
 48.19423571428572,
 51.20536,
 50.80386166666667,
 33.44444444444444,
 69.04761904761905,
 26.704591,
 48.34515510204081,
 17.00478962962963,
 38.020759999999996,
 18.77629333333333,
 13.546760625000001,
 28.19628676470588,
 27.047945714285714,
 16.348439090909093,
 15.149422000000001,
 19.323588965517242,
 12.515717924528303,
 25.934736,
 25.177672499999996,
 24.628977499999998,
 14.731215384615384,
 13.565047058823529,
 11.564336923076922,
 1.3782579487179487,
 0.026546666666666666,
 -0.11110736842105264,
 -1.25,
 -0.4963834285714286,
 -1.7729829999999998,
 -2.47698,
 -7.849764444444444,
 -7.77472,
 -11.374710294117648,
 -12.577487692307693,
 -8.200000000000001,
 -22.1890825,
 -13.885968571428572,
 -15.780972857142858,
 -33.1583375,
 -29.595975555555555,
 -16.80681625,
 -19.907395588235293,
 -25.90130769230769,
 -24.1432375,
 -46.960295,
 -50.6098075,
 -19.555994495412843,
 -48.97499784946236,
 -16.088327586206898,
 -59.1480825,
 -62.654627500000004,
 -64.1049175,
 -39.97233230769231,
 -41.148564615384615,
 -66.9799425,
 -55.748832692307694,
 -73.20644750000001,
 -80.0634825,
 -58.91278363636364,
 -58.967815384615385,
 -98.1639425,
 -99.83620888888889,
 -100.0,
 -39.171786153846156,
 -37.85997810218978,
 -80.50255733333333,
 -58.643185833333334,
 -100.0,
 -88.27620333333334,
 -100.0,
 -90.12879142857143,
 -97.18181818181819,
 -57.21075714285714]

In [80]:
#getting gross profit margin percent
new6 = []
for i in new1:
    new6.append(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Total_gross[i[0]]
         *100)
new6

<ipython-input-80-d7cf4be7d842>:4: RuntimeWarning: divide by zero encountered in longlong_scalars
  new6.append(all_drama_info1.Profit[i[0]]/all_drama_info1.Total_gross[i[0]]

[90.94288381237678,
 85.09724210244173,
 87.48948782815201,
 76.43644263574588,
 75.92505776393166,
 86.04928522466545,
 87.18011313183,
 78.89733040274965,
 84.09460877889352,
 83.27945218544995,
 80.11739485382508,
 78.7480229876118,
 68.86094666303136,
 80.18160919328378,
 71.16868183984441,
 60.73307973845802,
 76.48211649988353,
 81.5061949801051,
 70.82111181416303,
 78.68052474350158,
 79.128078502262,
 78.2248614386963,
 75.6063148751719,
 80.16387665667453,
 79.36507452163603,
 76.47122914055839,
 74.69821208120565,
 80.48778144608077,
 66.31734096550652,
 76.44260369082453,
 77.53089524373091,
 82.3998155062616,
 81.94359946062883,
 85.97679345285741,
 86.78885318735485,
 72.95204171725617,
 85.29974006412371,
 84.2158625291641,
 81.14164191279758,
 54.26447272061713,
 77.4953802440093,
 62.399005704737476,
 68.95375800533222,
 77.47335623856263,
 68.47583724624552,
 70.72358216087511,
 83.44942202654941,
 72.38609487448174,
 66.61671176578281,
 79.83421265263179,
 84.10049550661213,
 76.02440830317578,
 80.08534850640113,
 76.58816683597324,
 68.94010712159488,
 59.34799176854174,
 75.41666472503843,
 77.08317669326527,
 72.62523952915411,
 74.09519048082758,
 66.75531914893617,
 73.7341945515714,
 65.24007951133947,
 76.73296399173897,
 56.87108069796639,
 76.44017634379917,
 62.67941456773391,
 72.66890906799424,
 53.771616398254864,
 54.1509598771644,
 68.92915567511095,
 75.13389441469013,
 76.33653078467674,
 69.20456831027259,
 67.09052859160066,
 58.89719990429689,
 54.270388019324564,
 70.81071467775915,
 53.08305052916986,
 61.94744469499642,
 55.2727407371962,
 63.93045156237173,
 79.70735057089057,
 70.62771656059182,
 62.401926993148,
 61.84824077999153,
 62.15742631748164,
 66.19473551582053,
 73.08909208597831,
 69.26136363199736,
 69.26592363363092,
 66.00910052771954,
 64.85788113695091,
 50.61358484715145,
 30.05238260063751,
 63.91873551132539,
 55.86767981005293,
 67.59040572298699,
 55.19257201975067,
 45.060445718499494,
 51.71533259451668,
 68.70017047577349,
 49.73803302890224,
 68.03061776790233,
 60.18365188184603,
 48.9084997677659,
 59.43052488688375,
 62.48745416349839,
 62.348674853139904,
 60.2514126281042,
 60.19489900202733,
 51.625652207144114,
 37.02841313263544,
 58.069828694826164,
 39.55760162889474,
 37.12028127774977,
 56.18351602706206,
 68.33333333333333,
 60.45105493068791,
 52.81956623397974,
 53.95983705254198,
 41.649424655158015,
 50.90542399057733,
 49.56315601893549,
 49.40405488202882,
 61.888804528509056,
 42.171400177393934,
 26.600898625198134,
 47.118638725882825,
 56.64281783182915,
 46.40285006060631,
 42.96785311750785,
 46.88868612169502,
 39.89418852736735,
 33.706991816589905,
 17.726350466059415,
 32.5209921168613,
 33.86477833854567,
 33.68870074359391,
 25.062447960033307,
 40.845070422535215,
 21.07626155393217,
 32.58964208759368,
 14.533413276035184,
 27.54713131560788,
 15.808115244545995,
 11.930556671484084,
 21.994620496659103,
 21.289557703760927,
 14.051274962215182,
 13.156316147205672,
 16.19427401827603,
 11.123528477082125,
 20.59379073935566,
 20.113549003717097,
 19.76183869437587,
 12.839762339509509,
 11.944737760551636,
 10.365621525676685,
 1.3595202527697197,
 0.026539621281870374,
 -0.11123095420714181,
 -1.2658227848101267,
 -0.4988596853814859,
 -1.8049850785960446,
 -2.5398926325292224,
 -8.518442082236433,
 -8.430139762112947,
 -12.834609998868832,
 -14.387012407101688,
 -8.932461873638346,
 -28.516669913319042,
 -16.12509406547352,
 -18.738013715563664,
 -49.60729021364482,
 -42.037334923814804,
 -20.20215538391389,
 -24.8554729047007,
 -34.955148175562115,
 -31.82740299521747,
 -88.53800186105862,
 -102.4693465205668,
 -24.31007055497467,
 -95.98235332743897,
 -19.172931635625883,
 -144.78655132895537,
 -167.77079275350647,
 -178.58969261318734,
 -66.58984738934744,
 -69.91938997997906,
 -202.84623217267264,
 -125.9827391776323,
 -273.22411800376227,
 -401.5921160754379,
 -143.38470417407865,
 -143.71112807507203,
 -5346.452521230953,
 -60953.3742164817,
 -inf,
 -64.39739666352702,
 -60.926882459827304,
 -412.88777564127724,
 -141.7981220627951,
 -inf,
 -752.9660044712477,
 -inf,
 -913.0471793437943,
 -3448.3870967741937,
 -133.7035977333422]

In [83]:
%%HTML
<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="x1" display; inline-block></div>
    <div id="n1" display; inline-block></div>
    <div id="no1" display; inline-block></div>
    <div id="xo1" display; inline-block></div>
    <p class="highcharts-description">
    </p>
</figure>

In [84]:
%%js
Highcharts.chart('x1',{
    title:{
        text:"What Movie Is The Most Successful?"
    },
    xAxis:{
        categories:['The Sound of Music|2nd Highest',
                   'The Lion King|3rd Highest',
                   'Black Panther|4th Highest',
                   'Star Wars Ep.VIII:The Last Jedi|5th Highest',
                   'Iron Man 3|6th Highest',
                   'The Fate of the Furious|7th Highest',
                   'Star Wars Ep. I: The Phantom Menace |8th Highest',
                   'Harry Potter and the Oder of the Phoenix|9th Highest',
                   'Captain America: Civil War|10th Highest'],
        crosshair:{
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',
        color:'#111E6C',
        name:'Profit',
        data:[1747311220,1328722794,1072413963,999721747,986894640,850047606,
             841215812,793076457,747099794]
    },{
        type:'column',
        color:Highcharts.getOptions().colors[1],
        name:'Revenue',
        data:[2053311220,1518722794,1403013963,1316721747,1146894640,975047606,
             1066215812,943076457,897099794]
    },{
        type:'spline',
        color:'gold',
        name:'Cost',
        data:[306000000,190000000,330600000,317000000,160000000,125000000,
             225000000,150000000,150000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [85]:
%%js
Highcharts.chart('n1',{
        title:{
            text:""
        },
        xAxis:{
           categories:['The Sound of Music|2nd Highest',
                   'The Lion King|3rd Highest',
                   'Black Panther|4th Highest',
                   'Star Wars Ep.VIII:The Last Jedi|5th Highest',
                   'Iron Man 3|6th Highest',
                   'The Fate of the Furious|7th Highest',
                   'Star Wars Ep. I: The Phantom Menace |8th Highest',
                   'Harry Potter and the Oder of the Phoenix|9th Highest',
                   'Captain America: Civil War|10th Highest'],
           crosshair:{
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[85,87,76,76,86,87,79,84,83]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[571,699,324,315,617,680,374,529,498]
       }]  
    
   });

In [86]:
%%js
Highcharts.chart('no1',{
    title:{
        text:""
    },
    xAxis:{
        categories:['Spider-Man:Homecoming|11th Highest',
                   'Thor:Regnarok|12th Highest',
                   'Pirates of the Caribbean: At Worlds End|13th Highest',
                   'The Jungle Book|14th Highest',
                   'The Lord of the Rings: The Fellowship of the Ring|15th Highest',
                   'Ice Age: Dawn of the Dinosaurs|16th Highest',
                   'Star Wars Ep. III: Revenge of the Sith|17th Highest',
                   'The Hobbit: The Battle of the Five Armies|18th Highest',
                   'The Twilight Saga: Breaking Dawn, Part 2|19th Highest',
                   'Inside Out|20th Highest'],
        crosshair:{
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',
        color:'#111E6C',
        name:'Profit',
        data:[705166350,666980024,663420425,647330936,636860230,635063875,601635413,561920051,558241137,557272592]
    },{
        type:'column',
        color:Highcharts.getOptions().colors[1],
        name:'Revenue',
        data:[880166350,846980024,963420425,807330936,894860230,1045663875,786635413,689420051,788241137,708272592]
    },{
        type:'spline',
        color:'gold',
        name:'Cost',
        data:[175000000,180000000,300000000,160000000,258000000,410600000,
             185000000,127500000,230000000,151000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [23]:
%%js
Highcharts.chart('xo1',{
        title:{
            text:""
        },
        xAxis:{
           categories:['Spider-Man|11th Highest',
                   'Zootopia|12th Highest',
                   'Pirates of the Caribbean: At Worlds End|13th Highest',
                   'The Jungle Book|14th Highest',
                   'The Lord of the Rings: The Fellowship of the Ring|15th Highest',
                   'Ice Age: Dawn of the Dinosaurs|16th Highest',
                   'Star Wars Ep. III: Revenge of the Sith|17th Highest',
                   'The Twilight Saga: Breaking Dawn, Park 1|18th Highest',
                   'The Twilight Saga: Breaking Dawn, Part 2|19th Highest',
                   'Inside Out|20th Highest'],
           crosshair:{
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[80,79,67,80,71,61,76,82,71,79]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[402,371,221,405,247,155,325,441,243,369,]
       }]  
    
   });

In [30]:
var = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var.append(no_tickets[i])
var

In [1]:
var1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var1.append(all_actionadventure_info1['Name'][i])
var1

In [52]:
var2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var2.append(all_actionadventure_info1['Profit'][i])
var2

[635063875,
 -200237650,
 1072413963,
 663420425,
 355945209,
 636860230,
 841215812,
 442999518,
 601635413,
 666980024,
 206687380,
 21674817,
 747099794,
 88202668,
 -23328075,
 85008658,
 -51868170,
 22956466,
 561920051,
 431319450,
 -70371823,
 354683805,
 162794441,
 71377916,
 26704591,
 337040395,
 285381768,
 199660619,
 276101666,
 113932174,
 145900000,
 -79448583,
 -90000000,
 -25641967,
 -20243923,
 -18784118,
 -26791977,
 -29282579,
 -23659233,
 -13263335,
 -8875633]

In [68]:
var3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var3.append(no_tickets[i])
var3

[101286288,
 30242411,
 169862184,
 116824830,
 35952430,
 31615608,
 67705104,
 31212325,
 15894424,
 50163679,
 88222665,
 62102380,
 54482507,
 72544343,
 36601960,
 34563586,
 53439479,
 39815319,
 44082187,
 18901892,
 28768765,
 47343184,
 28923077,
 30957559,
 10963966,
 9844868,
 238462,
 797290,
 8857648,
 7061538,
 7501771,
 7555924,
 7299573,
 38341401,
 14311463,
 21036731,
 9238462,
 25625596,
 11439642,
 34671425,
 23923163,
 21231920]

In [54]:
var4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var4.append(all_actionadventure_info1['Name'][i])
var4

['Star Wars Ep. VIII: The Last Jedi',
 'Solo: A Star Wars Story',
 'Titanic',
 'Furious 7',
 'Star Trek Into Darkness',
 'Pacific Rim',
 'Spider-Man: Homecoming',
 'The Mummy: Tomb of the Dragon Emperor',
 'Tomorrowland',
 'Big Hero 6',
 'Aquaman',
 'Shrek the Third',
 'Transformers',
 'Harry Potter and the Order of the Phoenix',
 'Charlie and the Chocolate Factory',
 'Thor',
 'Mission: Impossibleâ\x80\x94Ghost Protocol',
 'Kung Fu Panda 3',
 'The Croods',
 'Rango',
 'The Adventures of Tintin',
 'Logan',
 'Godzilla',
 'Prometheus',
 'Power Rangers',
 "Ender's Game",
 'Men in Black: International',
 'Town & Country',
 'Wonder Park',
 'Treasure Planet',
 'Green Zone',
 'Jin lÃ\xadng shÃ\xad san chai',
 'The Lovely Bones',
 'Sherlock Holmes',
 'Atlantis: The Lost Empire',
 'Tomb Raider',
 'Volcano',
 'Fantastic Four',
 'Seabiscuit',
 "Ocean's Eleven",
 'The Bourne Supremacy',
 'Divergent']

In [55]:
var5 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var5.append(all_actionadventure_info1['Profit'][i])
var5

[999721747,
 118151347,
 2008208395,
 1328722794,
 277381584,
 221002906,
 705166350,
 230760225,
 36627518,
 487127828,
 986894640,
 647330936,
 557272592,
 793076457,
 325825484,
 299326618,
 549713230,
 377599142,
 438068425,
 110724600,
 243993951,
 488461394,
 251000000,
 277448265,
 22531552,
 17983283,
 -106900000,
 -94635231,
 15149422,
 -8200000,
 -2476980,
 -1772983,
 -105552,
 408438212,
 96049020,
 183477501,
 30100000,
 245632750,
 62715342,
 365728529,
 226001124,
 191014965]

In [69]:
var6 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var6.append(no_tickets[i])
var6

[157947017,
 42347489,
 13849830,
 52031120,
 52989153,
 24593375,
 27825435,
 34157184,
 48474112,
 23393503,
 32035142,
 6744920,
 9174359,
 28100000,
 39335252,
 19193689,
 15450735,
 1124852,
 0,
 8412536,
 6654585,
 4201298,
 34114093,
 27038462,
 22855075,
 23142679,
 15928334,
 13272578,
 6841043,
 4534871,
 14884615,
 6705652,
 4635784,
 4189459,
 20107692,
 9882215,
 10597613,
 3704935,
 4371126,
 5736561,
 2051609,
 4861538]

In [57]:
var7 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var7.append(all_actionadventure_info1['Name'][i])
var7

['Star Wars Ep. VII: The Force Awakens',
 'King Kong',
 'Hugo',
 'Doctor Strange',
 'Mission: Impossibleâ\x80\x94Rogue Nation',
 'The Last Airbender',
 'The World is Not Enough',
 'The Bourne Ultimatum',
 'Fast Five',
 'Skyscraper',
 'The Wolverine',
 'Ali',
 'Allied',
 'True Lies',
 'Toy Story 2',
 'Alvin and the Chipmunks: The Road Chip',
 'Percy Jackson: Sea of Monsters',
 'Soldier',
 '355',
 "Fool's Gold",
 'The Kingdom',
 'Driven',
 'Alvin and the Chipmunks: The Squeakquel',
 'Who Framed Roger Rabbit?',
 'Oceanâ\x80\x99s 8',
 'Hook',
 'Sleepy Hollow',
 'AVP: Alien Vs. Predator',
 'Rumor Has It',
 'The Legend of Hercules',
 'The Sum of All Fears',
 'Hall Pass',
 'The Insider',
 'Downsizing',
 'Total Recall',
 'Step Brothers',
 'Peteâ\x80\x99s Dragon',
 'Red Dawn',
 'Elektra',
 'I, Frankenstein',
 'Oliver Twist',
 'Random Hearts']

In [58]:
var8 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var8.append(all_actionadventure_info1['Profit'][i])
var8

[1747311220,
 343517357,
 47784,
 511404566,
 538858992,
 169713881,
 226730660,
 314043396,
 505163454,
 179115534,
 301456852,
 -21316034,
 13266661,
 265300000,
 421358276,
 159517956,
 110859554,
 -60376918,
 -75000000,
 36862966,
 14009602,
 -17383131,
 373483213,
 281500000,
 227115976,
 230854823,
 137068340,
 102543519,
 18933562,
 -11046681,
 125500000,
 19173475,
 -7734803,
 -13537029,
 196400000,
 63468793,
 72768975,
 -16835850,
 -8175367,
 9575290,
 -38329080,
 -800000]

In [70]:
var9 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var9.append(no_tickets[i])
var9

[15206739,
 16768178,
 6082821,
 17278057,
 26852963,
 5119581,
 28609003,
 18447233,
 13523629,
 12561204,
 13857607,
 2942572,
 6960178,
 8727810,
 14516585,
 26609441,
 1738305,
 12816718,
 1770047,
 9763948,
 12288098,
 14292174,
 12030742,
 4843644,
 3547126,
 0,
 5591471,
 6952017,
 1825125,
 3189816,
 2437062,
 5670,
 5461538,
 15162747,
 3834738,
 7096686,
 3851621,
 613431,
 1149088,
 56494,
 7871703,
 9230769]

In [60]:
var10 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var10.append(all_actionadventure_info1['Name'][i])
var10

['Jack the Giant Slayer',
 "The Sorcerer's Apprentice",
 'R.I.P.D.',
 'Itâ\x80\x99s Complicated',
 'Alvin and the Chipmunks: Chipwrecked',
 'Thirteen Days',
 'Shark Tale',
 'Die Hard 2',
 'Daddyâ\x80\x99s Home 2',
 'World Trade Center',
 'The Dictator',
 'The Missing',
 'The Tale of Despereaux',
 'The Dark Tower',
 'Rambo III',
 'Murder on the Orient Express',
 'Bullet to the Head',
 'Seven Pounds',
 'Bulletproof Monk',
 'The Adjustment Bureau',
 'Stepmom',
 'Inside Man',
 'Planes: Fire and Rescue',
 'The Peacemaker',
 'For Love of the Game',
 'Ad Astra',
 'The One',
 'Bedazzled',
 'Silence',
 'Dredd',
 'Pinocchio',
 'Foodfight!',
 'Cleopatra',
 'The Intern',
 'Legal Eagles',
 'The Skeleton Key',
 'Fever Pitch',
 'Impostor',
 'The Hudsucker Proxy',
 "Dragon Nest Warriors' Dawn",
 "The Time Traveler's Wife",
 'Star Trek: Generations']

In [71]:
var11 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var11.append(all_actionadventure_info1['Profit'][i])
var11

[2687603,
 57986320,
 -50923322,
 139614744,
 269088523,
 -13445453,
 296917043,
 169814025,
 105807183,
 98295654,
 115148897,
 -26746567,
 30482317,
 53461527,
 130715611,
 290922730,
 -32402031,
 112617328,
 -28989393,
 76731325,
 109745279,
 135798265,
 106399644,
 12967368,
 -3887360,
 -49800000,
 23689126,
 42376224,
 -22773374,
 -3532394,
 -13318189,
 -44926294,
 29000000,
 157115710,
 9851591,
 52256918,
 10071069,
 -32025393,
 -25061851,
 -39265577,
 63332135,
 82000000]

In [72]:
var12 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var12.append(no_tickets[i])
var12

[60633934,
 13394718,
 37660944,
 49039797,
 25231925,
 22357730,
 16544678,
 75003662,
 18690908,
 43365333,
 16561538,
 16834873,
 16329439,
 26725064,
 18413382,
 27928020,
 4636909,
 7979690,
 5940326,
 10576133,
 14936125,
 35655183,
 34013004,
 12579063,
 9913388,
 11411231,
 17022851,
 3001383,
 5578217,
 11374222,
 28351322,
 10191770,
 34935533,
 19504260,
 6978709,
 15014930,
 7678766,
 12303576,
 12258226,
 8611250,
 8092602,
 6370189]

In [63]:
var13 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var13.append(all_actionadventure_info1['Name'][i])
var13

['Pirates of the Caribbean: Dead Men Tell No Tales',
 'Evan Almighty',
 'War for the Planet of the Apes',
 'Moana',
 'Bolt',
 'Salt',
 'Australia',
 'Harry Potter and the Sorcererâ\x80\x99s Stone',
 'RoboCop',
 'The Smurfs',
 'The Patriot',
 'Kingdom of Heaven',
 'Public Enemies',
 'Rush Hour 2',
 'The Girl with the Dragon Tattoo',
 'Fast & Furious',
 'I Spy',
 'Escape Plan',
 'Money Train',
 'Abraham Lincoln: Vampire Hunter',
 'Need for Speed',
 'The Matrix',
 'Les Miserables',
 'Unbroken',
 'Space Cowboys',
 'Broken Arrow',
 'Everest',
 'Primary Colors',
 'Death Race',
 'The Hateful Eight',
 'Gone Girl',
 '2 Guns',
 '300',
 'Wild Hogs',
 'Kangaroo Jack',
 'London Has Fallen',
 'Hellboy',
 'Jack Reacher: Never Go Back',
 'The Jackal',
 'The Boxtrolls',
 'First Man',
 'Edge of Darkness']

In [64]:
var14 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var14.append(all_actionadventure_info1['Profit'][i])
var14

[558241137,
 -868671,
 337592267,
 487517365,
 178015029,
 160650494,
 85080810,
 850047606,
 122981799,
 453749323,
 105300000,
 108853353,
 109782709,
 257425832,
 149373970,
 278064265,
 -9720178,
 33735965,
 9224232,
 69989730,
 128169619,
 398517383,
 377169052,
 98527824,
 63874043,
 83345997,
 156297061,
 -25982016,
 7516819,
 85864886,
 307567189,
 71493015,
 394161935,
 193555383,
 30723216,
 135194085,
 39823958,
 99946489,
 99356941,
 51946251,
 45203825,
 22812456]

In [122]:
ttl = v+v1+v2+v3+v4
ttl

4825963891

In [123]:
# average of no tickets of R system rating
v = 0
for i in var:
    v+=i
(v/ttl*100)

24.159197754759994

In [124]:
# average of no tickets of NR system rating
v1 = 0
for i in var3:
    v1+=i
v1/ttl*100

32.14796181739604

In [125]:
# average of no tickets of PG system rating
v2 = 0
for i in var6:
    v2+=i
v2/ttl*100

18.3899328723759

In [126]:
# average of no tickets of G system rating
v3 = 0
for i in var9:
    v3+=i
v3/ttl*100

7.904832850312762

In [127]:
# average of no tickets of PG13 system rating
v4= 0
for i in var12:
    v4+=i
v4/ttl*100

17.398074705155313

In [24]:
%%html
<script src="http://code.highcharts.com/highchart.js"></script>
<div id='hraph2' style="height:600px"></div>

In [37]:
%%js
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'hraph2'
    },
    title:{
        text:'Number of Tickets Sold'
    },
    subtitle:{
        text:'Action & Adventure Genre'
    },
    series:[{
        type:'pie',
        name: 'Percentage of Tickets Sold',
        tooltip:{
            valueSuffix:'%'
        },
        shadow: true,
        data:[{
            name:'System Rating: R',
            y:24.15,
            sliced:true,
            color: '#4682B4',
        },{
            name:'System Rating: PG-13',
            y:17.39,
            sliced:true,
            color:'#1D2951',
        },{
            name:'System Rating: PG',
            y:18.38,
            sliced:true,
            color:'#588BAE',
        },{
            name:'System Rating: NR',
            y:32.14,
            sliced:true,
            color:'#73C2FB',
        },{
            name:'System Rating: G',
            y:7.90,
            sliced:true,
            color:'#000080',
        }],
        innerSize:'80%',
        size:'83%'
       },{
        type:'pie',
        shadow: true,
        dataLabels: false,
        name: 'No. of Tickets Sold',
        data:[{
            name:'Ice Age: Dawn of the Dinosaurs',
                   y:80435683,
                   sliced:true,
                   selected:true,
                   color:'#4682B4',
                 },{
                   name:'Dark Phoenix',
                   y:11520181,
                   sliced:false,
                   color:'#4682B4',
                 },{
                   name:'Black Panther',
                   y:107924151,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Pirates of the Caribbean: At World End',
                   y:74109263,
                   sliced:false,
                   color:'#4682B4',
                 },{
                   name:'Justice League',
                   y:50457324,
                   selected:true,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'The Lord of the Rings: The Fellowship of the Ring',
                   y:68835402,
                   sliced:false,
                   color:'#4682B4',
                 },{
                   name:'Star Wars Ep. I: The Phantom Menace ',
                   y:82016601,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Man of Steel',
                   y:51384578,
                   color:'#4682B4',
                 },{
                   name:'Star Wars Ep. III: Revenge of the Sith',
                   y:60510416,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Thor: Rangnarok',
                   y:65152310,
                   color:'#4682B4',
                 },{
                   name:'Monsters vs. Aliens',
                   y:29360568,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Poseidon',
                   y:13974986,
                   color:'#4682B4',
                 },{
                   name:'Captain America: Civil War',
                   y:69007676,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Dark Shadows',
                   y:18323282,
                   color:'#4682B4',
                 },{
                   name:'Sahara',
                   y:9359379,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Ghostbusters',
                   y:17616051,
                   color:'#4682B4',
                 },{
                   name:'Final Fantasy: The Spirits Within',
                   y:6548602,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Happy Feet Two',
                   y:12150497,
                   color:'#4682B4',
                 },{
                   name:'The Twilight Saga: Breaking Down Part 1',
                   y:53032312,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'The Day After Tomorrow',
                   y:42793804,
                   color:'#4682B4',
                 },{
                   name:'How Do You Know?',
                   y:3817552,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Gladiator',
                   y:35206447,
                   color:'#4682B4',
                 },{
                   name:'Epic',
                   y:20214957,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Blood Diamond',
                   y:13182917,
                   color:'#4682B4',
                 },{
                   name:'Point Break',
                   y:9746507,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'The Mummy Returns',
                   y:33464646,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Spider-Man: Into The Spider-Verse 3D',
                   y:28875521,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'The Departed',
                   y:2281586,
                   color:'#4682B4',
                 },{
                   name:'Die Hard with a Vengeance',
                   y:28161667,
                   sliced:true,
                   color:'#4682B4'
                 },{
                   name:'Valkyrie',
                   y:15687090,
                   color:'#4682B4',
                 },{
                   name:'Artificial Intelligence: AI',
                   y:18146154,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'The Promise',
                   y:811647,
                   color:'#4682B4',
                 },{
                   name:'Army of the Dead',
                   y:0,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'Memoirs of an Invisible Man',
                   y:1104464,
                   color:'#4682B4',
                 },{
                   name:'Amelia',
                   y:1519698,
                   sliced:true,
                   color:'#4682B4',
                 },{
                   name:'New York Minute',
                   y:1631991,
                   color:'#4682B4',
                 },{
                   name:'FearDotCom',
                   y:1016002,
                   color:'#4682B4',
                 },{
                   name:'Universal Soldier II: The Return',
                   y:824417,
                   color:'#4682B4',
                 },{
                   name:'Paranoia',
                   y:1256982,
                   color:'#4682B4',
                 },{
                   name:'Baahubali: The Beginning',
                   y:2056667,
                   color:'#4682B4',
                 },{
                   name:'Victor Frankenstein',
                   y:2394182,
                   color:'#4682B4',
            },{
             name:'The Twilight Saga: Breaking Dawn, Part 2',
             y:60633934,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Evan Almighty',
             y:13394718,
             color:'#1D2951',
            },{
             name:'War for the Planet of the Apes',
             y:37660944,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Moana',
             y:49039797,
             color:'#1D2951',
            },{
             name:'Bolt',
             sliced:true,
             y:25231925,
             color:'#1D2951',
            },{
             name:'Salt',
             y:22357730,
             color:'#1D2951',
            },{
             name:'Australia',
             sliced:true,
             y:16544678,
             color:'#1D2951',
            },{
             name:'Harry Potter and the Sorcerers Stone',
             y:75003662,
             color:'#1D2951',
            },{
             name:'RoboCop',
             sliced:true,
             y:18690908,
             color:'#1D2951',
            },{
             name:'The Smurfs',
             y:43365333,
             color:'#1D2951',
            },{
             name:'The Patriot',
             sliced:true,
             y:16561538,
             color:'#1D2951',
            },{
             name:'Kingdom of Heaven',
             y:16834873,
             color:'#1D2951',
            },{
             name:'Public Enemies',
             sliced:true,
             y:16329439,
             color:'#1D2951',
            },{
             name:'Rush Hour 2',
             y:26725064,
             color:'#1D2951',
            },{
             name:'The Girl with the Dragon Tattoo',
             y:18413382,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Fast & Furious',
             y:27928020,
             color:'#1D2951',
            },{
             name:'I Spy',
             sliced:true,
             y:4636909,
             color:'#1D2951',
            },{
             name:'Escape Plan',
             y:7979690,
             color:'#1D2951',
            },{
             name:'Money Train',
             sliced:true,
             y:5940326,
             color:'#1D2951',
            },{
             name:'Abraham Lincoln: Vampire Hunter',
             y:10576133,
             color:'#1D2951',
            },{
             name:'Need for Speed',
             y:14936125,
             color:'#1D2951',
            },{
             name:'The Matrix',
             y:35655183,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Les Miserables',
             y:34013004,
             color:'#1D2951',
            },{
             name:'Unbroken',
             y:12579063,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Space Cowboys',
             y:9913388,
             color:'#1D2951',
            },{
             name:'Broken Arrow',
             y:11411231,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Everest',
             y:17022851,
             color:'#1D2951',
            },{
             name:'Primary Colours',
             y:3001383,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Death Race',
             y:5578217,
             color:'#1D2951',
            },{
             name:'The Hateful Eight',
             y:11374222,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Gone Girl',
             y:28351322,
             color:'#1D2951',
            },{
             name:'2 Guns',
             y:10191770,
             sliced:true,
             color:'#1D2951',
            },{
             name:'300',
             y:34935533,
             color:'#1D2951',
            },{
             name:'Wild Hogs',
             y:19504260,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Kangaroo Jack',
             y:6978709,
             color:'#1D2951',
            },{
             name:'London Has Fallen',
             y:15014930,
             sliced:true,
             color:'#1D2951',
            },{
             name:'Hellboy',
             y:7678766,
             color:'#1D2951',
            },{
             name:'Jack Reacher: Never Go Back',
             y:12303576,
             sliced:true,
             color:'#1D2951',
            },{
             name:'The Jackal',
             y:12258226,
             color:'#1D2951',
            },{
             name:'The Boxtrolls',
             y:8611250,
             sliced:true,
             color:'#1D2951',
            },{
             name:'First Man',
             y:8092602,
             color:'#1D2951',
            },{
             name:'Edge of Darkness',
             sliced:true,
             y:6370189,
             color:'#1D2951',
            }

              ,{
              name:'Star Wars Ep. VII: The Force Awakens',
              y:157947017,
              sliced:true,
              color:'#588BAE' ,   
            },{
              name:'King Kong',
              y:42347489,
              color:'#588BAE',
            },{
              name:'Hugo',
              sliced:true,
              y:13849830,
              color:'#588BAE',
            },{
              name:'Doctor Strange',
              y:52031120,
              color:'#588BAE',
            },{
              name:'Mission: Impossible Rogue Nation',
              y:52989153,
              sliced:true,
              color:'#588BAE',
            },{
              name:'The Last Airbender',
              y:24593375,
              color:'#588BAE',
            },{
              name:'The World is Not Enough',
              y:27825435,
              sliced:true,
              color:'#588BAE',
            },{
              name:'The Bourne Ultimatum',
              y:34157184,
              color:'#588BAE',
            },{
              name:'Fast Five',
              y:48474112,
              sliced:true,
              color:'#588BAE',
            },{
              name:'Skyscrapper',
              y:23393503,
              color:'#588BAE',
            },{
              name:'The Wolverine',
              y:32035142,
              sliced:true,
              color:'#588BAE',
            },{
              name:'Ali',
              y:6744920,
              color:'#588BAE',
            },{
              name:'Allied',
              sliced:true,
              y:9174359,
              color:'#588BAE',
            },{
              name:'True Lies',
              y:28100000,
              color:'#588BAE',
            },{
              name:'Toy Story 2',
              y:39335252,
              sliced:true,
              color:'#588BAE',
            },{
              name:'Alvin and the Chipmunks: The Road Chip',
              y:19193689,
              color:'#588BAE',
            },{
              name:'Percy Jackson: Sea of Monsters',
              y:15450735,
              sliced:true,
              color:'#588BAE',
            },{
              name:'Soldier',
              y:1124852,
              color:'#588BAE',
            },{
              name:'355',
              sliced:true,
              y:0,
              color:'#588BAE',
            },{
              name:'Fools Gold',
              y:8412536,
              color:'#588BAE',
            },{
              name:'The Kingdom',
              sliced:true,
              y:6654585,
              color:'#588BAE',
            },{
              name:'Driven',
              y:4201298,
              color:'#588BAE',
            },{
              name:'Alvin and the Chipmunks: The Squeakquel',
              sliced:true,
              y:34114093,
              color:'#588BAE',
            },{
              name:'Who Framed Roger Rabbit?',
              y:27038462,
              color:'#588BAE'
            },{
              name:'Oceans 8',
              sliced:true,
              y:22855075,
              color:'#588BAE',
            },{
              name:'Hook',
              y:23142679,
              color:'#588BAE',
            },{
              name:'Sleepy Hallow',
              sliced:true,
              y:15928334,
              color:'#588BAE',
            },{
              name:'AVP: Alien Vs. Predator',
              y:13272578,
              color:'#588BAE',
            },{
              name:'Rumor Has It',
              sliced:true,
              y:6841043,
              color:'#588BAE',
            },{
              name:'The Legend of Hercules',
              y:4534871,
              color:'#588BAE',
            },{
              name:'The Sum of All Fears',
              y:14884615,
              sliced:true,
              color:'#588BAE',
            },{
              name:'Hall Pass',
              y:6705652,
              color:'#588BAE',
            },{
              name:'The Insider',
              sliced:true,
              y:4635784,
              color:'#588BAE',
            },{
              name:'Downsizing',
              y:4189459,
              color:'#588BAE'
            },{
              name:'Total Recall',
              sliced:true,
              y:20107692,
              color:'#588BAE',
            },{  
              name:'Step Brothers',
              y:9882215,
              color:'#588BAE',
            },{
              name:'Petes Dragon',
              sliced:true,
              y:10597613,
              color:'#588BAE',
            },{
              name:'Red Dawn',
              y:3704935,
              color:'#588BAE',
            },{
              name:'Elektra',
              sliced:true,
              y:4371126,
              color:'#588BAE',
            },{
              name:'I, Frankenstein',
              y:5736561,
              color:'#588BAE',
            },{
              name:'Oliver Twist',
              sliced:true,
              y:2051609,
              color:'#588BAE',
            },{
              name:'Random Hearts',
              y:4861538,
              color:'#588BAE',
            }

               ,{
                name:'Jurassic World: Fallen Kingdom',
                y:101286288,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Solo: A Star Wars Story',
                y:30242411,
                color:'#73C2FB',
               },{
                name:'Avatar',
                y:169862184,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'The Lion King',
                y:116824830,
                color:'#73C2FB',
               },{
                name:'Star Trek Into Darkness',
                y:35952430,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Pacific Rim',
                y:31615608,
                color:'#73C2FB',
               },{
                name:'Toy Story 4',
                y:67705104,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'The Mummy: Tomb of the Dragon Emperor',
                y:31212325,
                color:'#73C2FB',
               },{
                name:'Tomorrowland',
                y:15894424,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Big Hero 6',
                y:50163679,
                color:'#73C2FB',
               },{
                name:'Iron Man 3',
                y:88222665,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Shrek the Thrid',
                y:62102380,
                color:'#73C2FB',
               },{
                name:'Inside Out
                y:54482507,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Inside Out: Age of Extinction',
                y:72544343,
                color:'#73C2FB',
               },{
                name:'Charlie and the Chocolate Factory',
                y:36601960,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Thor',
                y:34563586,
                color:'#73C2FB',
               },{
                name:'Mission: Impossible Ghost Protocol',
                y:53439479,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Kung Fu Panda 3',
                y:39815319,
                color:'#73C2FB',
               },{
                name:'The Croods',
                y:44082187,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Rango',
                y:18901892,
                color:'#73C2FB',
               },{
                name:'The Adventures of Tintin',
                y:28768765,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Logan',
                y:47343184,
                color:'#73C2FB',
               },{
                name:'Godzilla',
                y:28923077,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Prometheus',
                y:30957559,
                color:'#73C2FB',
               },{
                name:'Power Rangers',
                y:10963966,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Enders Game',
                y:9844868,
                color:'#73C2FB',
               },{
                name:'Men in Black: International',
                y:238462,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Town & Country',
                y:797290,
                color:'#73C2FB',
               },{
                name:'Wonder Park',
                y:8857648,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Treasure Planet',
                y:7061538,
                color:'#73C2FB',
               },{
                name:'Green Zone',
                y:7501771,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Jin IAad san chai',
                y:7555924,
                color:'#73C2FB',
               },{
                name:'The Lovely Bones',
                y:7299573,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Sherlock Holmes',
                y:38341401,
                color:'#73C2FB',
               },{
                name:'Atlantic The Lost Empire',
                y:14311463,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Tomb Raider',
                y:21036731,
                color:'#73C2FB',
               },{
                name:'Volcano',
                y:9238462,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Fantastic Four',
                y:25625596,
                color:'#73C2FB',
               },{
                name:'Seabiscuit',
                y:11439642,
                sliced:true,
                color:'#73C2FB',
               },{
                name:'Oceans Eleven',
                y:34671425,
                color:'#73C2FB',
               },{
                name:'The Bourne Supremacy',
                y:23923163,
                slidced:true,
                color:'#73C2FB',
               },{
                name:'Divergent',
                y:21231920,
                color:'#73C2FB',
               }

               ,{
                name:'Jack the Giant Slayer',
                color:'#000080',
                sliced:true,
                y:15206739,
              },{
                name:'The Sorcerers Apprentice',
                color:'#000080',
                y:16768178,
               },{
                name:'R.I.P.D.',
                color:'#000080',
                sliced:true,
                y:6082821,
               },{
                name:'Its Complicated',
                color:'#000080',
                y:17278057,
               },{
                name:'Alvin and the Chipmunks Chipwrecked',
                color:'#000080',
                sliced:true,
                y:26852963,
               },{
                name:'Thirteen Days',
                color:'#000080',
                y:5119581,
               },{
                name:'Shark Tale',
                color:'#000080',
                sliced:true,
                y:28609003,
               },{
                name:'Die Hard 2',
                color:'#000080',
                y:18447233,
               },{
                name:'Daddys Home 2',
                color:'#000080',
                sliced:true,
                y:13523629,
               },{
                name:'World Trade Center',
                color:'#000080',
                y:12561204,
               },{
                name:'The Dictator',
                color:'#000080',
                sliced:true,
                y:13857607,
               },{
                name:'The Missing',
                color:'#000080',
                y:2942572,
               },{
                name:'The Tale of Despereaux',
                color:'#000080',
                sliced:true,
                y:6960178,
               },{
                name:'The Dark Tower',
                color:'#000080',
                y:8727810,
               },{
                name:'Rambo III',
                color:'#000080',
                sliced:true,
                y:14516585,
               },{
                name:'Murder on the Orient Express',
                color:'#000080',
                y:26609441,
               },{
                name:'Bullet to the Head',
                color:'#000080',
                y:1738305,
                sliced:true,
               },{
                name:'Seven Pounds',
                color:'#000080',
                y:12816718,
               },{
                name:'Bulletproof Monk',
                y:1770047,
                color:'#000080',
               },{
                name:'The Adjustment Bureau',
                y:9763948,
                color:'#000080',
               },{
                name:'Stepmom',
                y:12288098,
                color:'#000080',
               },{
                name:'Inside Man',
                y:14292124,
                color:'#000080',
               },{
                name:'Planes: Fire and Rescue',
                y:12030742,
                color:'#000080',
               },{
                name:'The Peacemaker',
                y:4843644,
                color:'#000080',
               },{
                name:'For Love of the Game',
                y:3547126,
                color:'#000080',
               },{
                name:'Ad Astra',
                y:0,
                color:'#000080',
               },{
                name:'The One',
                y:5591471,
                color:'#000080',
               },{
                name:'Bedazzled',
                y:6952017,
                color:'#000080',
               },{
                name:'Silence',
                y:1825125,
                color:'#000080',
               },{
                name:'Dredd',
                y:3189816,
                color:'#000080',
               },{
                name:'Pinocchio',
                y:2437062,
                color:'#000080',
               },{
                name:'Foodfight',
                y:5670,
                color:'#000080',
               },{
                name:'Cleopatra',
                y:5461538,
                color:'#000080',
               },{
                name:'The Intern',
                y:15162747,
                color:'#000080',
               },{
                name:'Legal Eagles',
                y:3834738,
                sliced:true,
                color:'#000080',
               },{
                name:'The Skeleton Key',
                y:7096686,
                sliced:true,
                color:'#000080',
               },{
                name:'Fever Pitch',
                y:3851621,
                sliced:true,
                color:'#000080',
               },{
                name:'Impostor',
                y:613431,
                sliced:true,
                color:'#000080',
               },{
                name:'The Hudsucker Proxy',
                y:1149088,
                sliced:true,
                color:'#000080',
               },{
                name:'Dragon Nest Warriors Dawn',
                y:56494,
                sliced:true,
                color:'#000080',
               },{
                name:'The Time Travelers Wife',
                y:7871703,
                sliced:true,
                color:'#000080',
               },{
                name:'Star Trek: Generations',
                y:9230769,
                sliced:true,
                color:'#000080'
               }],
        innerSize:'93%',
        size:'100%'
    }]
});