  # Objective

__Microsoft sees all the big companies creating original video content, and they want to get in on the fun. They have decided to create a new movie studio, but the problem is they don't know anything about creating movies. They have hired you to help them better understand the movie industry. Your team is in charge with doing data analysis that explores what type of films are currently doing the best at the box office. You must then translate
those findings into actionable insights that the CEO can use when deciding what type of films they should be creating.__

# Datasets

There are 10 datasests in this project 

_Name.basics.csv_
  - _Colunms in the dataset_
     - _nconst_
     - _primary_name_
     - _birth_year_
     - _death_year_
     - _primary_profession_
     - _known_for_titles_

_Bom.movie_gross.csv_
   - _Colunms in the dataset_
      - _title_
      - _studio_
      - _domestic_gross_
      - _foreign_gross_
      - _year_
     
_Rt.movie_info.tsv_
   - _Columns in the dataset_
     - _id_
     - _synopsis_
     - _rating_
     - _genre_
     - _director_
     - _writer_
     - _theater_date_
     - _currency_
     - _box_office_
     - _runtime_
     - _studio_
     
_Title.akas.csv_
   - _Columns in the dataset_
     - _title_id_
     - _ordering_
     - _title_
     - _region_
     - _language_
     - _types_
     - _attributes_
     - _is_original_title_
     
_Title.basics.csv_
  - _Columns in the dataset_
    - _tconst_
    - _primary_title_
    - _original_title_
    - _start_year_
    - _runtime_mintues_
    - _genres_
    
_Title.crew.csv_
  - _Columns in the dataset_
    - _tconst_
    - _directors_
    - _writers_
    
_Title.principals.csv_
  - _Columns in the dataset_
    - _tconst_
    - _ordering_
    - _nconst_
    - _category_
    - _job_
    - _charactors_

_Title.ratings.csv_
  - _Columns in the dataset_
    - _tconst_
    - _averagerating_
    - _numvoters_
    
_Tmdb.movies.csv_
  - _Columns in the dataset_
    - _genre_ids_
    - _id_
    - _original_language_
    - _original_title_
    - _popularity_
    - _release_date_
    - _title_
    - _vote_average_
    - _vote_count_
    
_Tn.movie_budgets_
   - _Columns in the dataset_
     - _id_
     - _release_date_
     - _movie_
     - _production_budget_
     - _domestic_gross_
     - _worldwide_gross_

# Approaches

Based on the datasets there are nine main genres; Action and Adventures, Drama, Comedy, Documentry, Classics, Art House and International, Musical and Performing Arts, Horror, Mystrey and Suspense, Animation, Special Interest, Kids and Family and there are also five main System Ratings; System R Rating, System PG-13 Rating, System PG Rating, System G Rating and System NR Rating. In this Project the genres that are being chosen are Classic, Drama, Comedy, Classics and Art House and International which will all have indivisual data analysis based on the same data visualization concepts and the system ratings are being compared among one another and also analyised to view which one best fit the genres. There will be eleven differnt graphs for each genres describing and protarying insights on the activity of the data.

## Graphs
These are the elven main graphs.
  - __Profit Percentage baised on cost__:
     - This data visualization shows the name, cost, profit, the type of system rating and profit percenatge by cost. The purpose of this notion is to view past the profit and better understand how successful the movie really is by analysing the cost and calculating how much more was made compared to it. This allows the idea of higher profit dosn't mean more profitable to be considered as a justification based on the results proving so. The system rating were added to be compared among eachother, to observe which one was better and to also know which one was the best fit for any particular genere by calculating the average of the reults of each system rating
   
  
  
  - __Gross Profit Margin Percentage__:
     - This data visualization has two pionts about the movie on one panel. The fisrt piont shows the name, amount of profit made in dollars, type of system rating and Gross Profit Margin Percentage. The other piont shows the name, revenue made in dollars and the type of system rating. The graph was designed this way to compare the profit amount against the revenue amount, allowing the Gross Profit Margin Percntage to be more visible and inderectly see the expenses made from a graph perpsective.
     
 
 - __Budget and Revenue of Movies__:
    - This graph is a scatter plot with an x-axis and a y-axis, the x-axis is the revenue of the movies in dollars and the y-axis is the budget of the movies in dollars. This graph is a blueprint to better understand  wether the amount of money spent on the movie effected the amount of revenue generted and to also spot movies that spent less money than the average with a higher revenue.
 
 
 - __Revenue of Movies/Budget of Movies__:
    - The revenue graph has an x-axis that shows the revnue of the movies, name and the type of system ratings with no y-axis. The budget graph has an x-axis that shows the budget of the movies and also the name and system ratings with no y-axis. Both graphs have a table split into catagories of the system ratings showing were they are postions in the axis. These graphs were constructed to predict how much will be made depending on how much is spent based on the pattern of budget of movies to revenue of movies and to indirectly spot anomalies.
    
 
 - __Movies that mdae Profit__:
    - This graph simply shows all the movies that made profit, from the highest to the lowest.


 - __Movies that had losses__:
   - This graph is a colunm graph that shows the movies that did not make any profit. It shows the cost of the movie, revenue and by how much was not made to prevent a loss by the movie. It also shows the name and system ratings it belongs to. This dilema was created to percieve what agenda was not making any money, to try and understand the other half of film industry that is overlooked.
   
   
 
 - __Top 20 Highest Profitable Movies/ Top 20 Lowest Profitable Mobies__:
    - The top 20 highest profitable graph is a 3D chart that shows the top 20 most profitable movies with an x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. The top 20 lowest profitable graph is also a 3D chart that shows the top 20 movies that had the lowest profit, with the x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. These graphs were creted to really spot what movis were the kings and queens of the movie industry and what movie was barely making sales. This brings a lot of questioning to what each of the movies did do britiantally or failed to do.
    

- __Most Successful Moive__:
   - This graph is built up of two sections, the first section is an x-axis whcih shows the names and a y-axis which shows the budget, revenu and profit of the movies in dollars, the second section compares the gross profit margin percentage to the profit percnatge by cost of the movies whcih is all compared to all other movies in the data frame. The sections data is based on the top 20 most profitable movies. The concept of the visualization is to  dive deep into detail to anlayze what movie were actually more succesfull than the other, other than just focusing on the highets profits made. Factors like budget and revenue expressed in gross profit margin percentage and proft percentage by cost allows the differences among the most profitable movies to become more disguishable, whcih can open a new perspcetive on anyalzing numbers.
   
 
 - __Tickets Sold__:
    - This graph simply shows what system ratings have the highest tickets sold to better understand what audience best fist this genre through the sales of the system ratings.

Before starting any data extracting, liabreis such as Altair, Pandas, Pandas_highcharts, Collections need to be installed to help create great insightful interactive graphs.

In [3]:
import altair as alt # used to create interactive graphs
import pandas as pd # used to make for dataframes
import collections# used to put data into sections
import matplotlib.pyplot as plt# used to make graphs

In [4]:
# helps create highcharts graphs
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import json

Before the graphs are made the data is extracted from the rt.movie_info.tsv file and made into a dataframe.

In [5]:
# The data frame is called movie_info
movie_info = pd.read_csv("rt.movie_info.tsv.gz",error_bad_lines=False,sep='\t')

In [6]:
movie_info.head()

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN

In [7]:
# Getting first 500 movies 
first_500 = []
for i in movie_info.genre[:500].dropna():
    first_500.append(i)
len(first_500)

496

The movies form the data frame have been selected and put into genres groups for the first 500 movies

In [8]:
# putting movies into groups
grouped_500 = []
for i in first_500:
    grouped_500.append(i.split('|',1)[0])
grouped_500=collections.Counter(grouped_500)
grouped_500

Counter({'Action and Adventure': 117,
         'Drama': 103,
         'Comedy': 115,
         'Documentary': 11,
         'Classics': 53,
         'Art House and International': 55,
         'Musical and Performing Arts': 3,
         'Horror': 23,
         'Mystery and Suspense': 7,
         'Animation': 6,
         'Special Interest': 2,
         'Kids and Family': 1})

# Blueprint: Profit Percentage Based on Cost

The amount of movies in the genre groups are all uneven, the goal through out the project is to make sure they all have the same amount of movies that are being analyzed to give it a fair comparison which will be done later on in the project.

The next step is to choose a genre to select and start analyzing. For this section Action and Adventure is being analyzed.

This is the blueprint for creating the first visualization Profit Percentage by cost, bokeh will be used to create these graphs.
Blueprint:
 1. Create a new dataframe for the graph, the dataframe columns will consist of these key infomation of the moives in the Action and Adventure Genre;
    - The Names 
    - Product Budget 
    - System Ratings 
    - Ratings 
    - Domestic Gross 
    - World Wide Gross
    - Profit
    - No. of Tickets
    - Product Budget in integers
    - Profit in integers
    - Total Gross in integers
    - Domestic total in integers
 
 
 2. Install bokeh and create the componets needed for the format of the code script for the graph.There will be five graphs and in each graph are key information of the movies based on the same system rating which are R, PG-13, PG, G and NR. These are the key componets needed in each graph based on the same system rating;
    - X-axis Range
    - Y-axis Range
    - Name
    - Profit in integers
    - System Rating
    - Percentage Profit by Cost
    - Cost


3. The graphs has to have visual componets that convey the information smoothly and also differentiate from one another due to that fact that they are all in groups, these are the formats to help do so; 
    - Color
    - Tooltips (make the graph interactive)
    - Type and shape of pionts in the graph

Below is the code script used to create a new dataframe needed for the graphs

In [9]:
# Getting the names of the first 200 movies in the Action and Adventure genre
movie_buddget = pd.read_csv('tn.movie_budgets.csv.gz')
name_movies = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': # 'Cl' is the first two words for Action and Adventure
        name_movies.append(movie_buddget.movie[x])
len(name_movies)

55

In [10]:
# Getting product budget of the first 200 movies in Action and Adventure genre
product_budget = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar':product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

55

In [11]:
# Getting ratings of the first 200 movies in Action and Adventure genre
ratings = pd.read_csv('imdb.title.ratings.csv.gz')
rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': rating.append(ratings.averagerating[x])
len(rating)

55

In [12]:
# Getting system ratings of the first 200 movies in Action and Adventure genre
system_rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': system_rating.append(movie_info.rating[x])
len(system_rating)

55

In [13]:
# Getting domestic gross of the first 200 movies in Action and Adventure genre
domestic_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

55

In [14]:
# Getting worldwide gross of the first 200 movies in Action and Adventure genre
worldwide_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

55

The amount of movies per system rating all have to be the same. The code bellow caluclates how much movies are currently in each system rating.

In [14]:
# putting system ratings into groups
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating
# need all groups to be even, all groups need 42 records

Counter({'PG-13': 10, 'R': 21, 'PG': 4, 'NR': 19, 'G': 1})

'R' has the highest count of movies, so all system rating will have to have 42 movies based on all the previous genre analysis to make it a fair analysis

Due to the fact that the amount of movies per system rating is not tha same, the following codes caluclate how much is needed for each misiing amount in each group and also getting the indexes of what is needed.

In [23]:
# making sure all system_rating have the same amout of records
# getting the index of  system PG-13: need 32
index_PG13 = movie_info[movie_info['rating']=='PG-13'].index
index_PG13[250:300]

Int64Index([], dtype='int64')

Based on the indexes on the 'PG-13' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-13-rated. The 35 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [25]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Hidden Figures ':
        print('yes')

In [1]:
#informations on the movies needed for pg-13
# the name of the movies
name_mojo1 = ['The Fountain','Primer','The Tree of Life','Another Earth',' The New World','Restless ',
             'The Box','Departures','The Chorus','The Kite Runner','Radio Flyer ',
             'The Cider House Rules','A Better Life','A Separation','Crouching Tiger, Hidden Dragon ',' Dear Frankie',
             'Invictus','Life Is Beautiful','The Diving Bell and the Butterfly',
             'The Perks of Being a Wallflower','The Impossible','The Sea Inside','The Perks of Being a Wallflower'
              ,'Back to the Future','Apollo 13','Finding Neverland','Groundhog Day', 'Hidden Figures',
             'Boy Erased','The Imposter','happy as lazzaro','My Life as a Zucchini']
# ratings of the movies
rating_mojo1 = [7.2,6.9,6.8, 7,6.7,6.8,
              5.6,8.1,7.9,7.6,8,7,
              7.4,7.2,8.3,7.8,7.7,5.8,
              7.3,8.6,7,8,8,7.6,
              8,8,6.1,7,8,6,
             7,6,8]
# worldwide gross
worldwide_gross_mojo1 = ['$21,796,621','$1,189,906','$58,409,247','$2,304,064','$71,036,076','$4,066,191',
             '$33,333,531','$70,636,951','$115,937,265','$96,820,727','$8,786,940','$140,718,085',
             '$1,863,506','$22,926,076','$330,451,697','$2,341,621','$122,233,971','$228,847,384',
             '$29,370,408','$33,384,127','$279,959,676','$61,741,311','$33,384,127','$549,313,764',
             '$389,471,114','$164,864,089','$130,158,018','$235,956,898','$11,862,650','$3,232,717',
             '$1,802,696','$5,872,598']
# domestic gross
domestic_gross_mojo1 = ['$13,426,071','$600,319','$13,303,319','$1,570,117','$18,303,867','$263,647',
             '$15,051,977','$1,498,210','$2,949,769','$20,394,001','$8,786,940','$91,452,106',
             '$1,759,252','$7,099,055','$198,207,571','$25,475','$37,491,364','$57,247,384',
             '$7,731,708','$17,742,948','$26,881,089','$2,974,919','$17,742,948','$520,972,147',
             '$299,399,485','$73,040,998','$130,158,018','$169,607,287','$6,788,692','$901,954',
             '$502,508','$309,766']
# product budget
product_budget_mojo1 = ['$46,324,136','$9,893','$32,000,000','$118,840','$43,196,351','$12,918,735',
             '$30,000,000','$2,757,562','$7,490,570','$25,815,064','$66,110,152','$38,141,403',
             '$10,000,000','$500,000','$26,310,505','$4,893,180','$60,000,000','$20,000,000',
             '$18,070,545','$13,000,000','$63,599,186','$17,129,013','$13,000,0000','$46,999,107',
             '$107,878,343','$35,332,881','$26,800,002','$25,000,000','$11,000,000','$1,000,000',
             '$7,271,623','$8,000,000']

In [25]:

# making sure all system_rating have the same amout of records
# getting system PG: need 38
index_PG = movie_info[movie_info['rating']=='PG'].index
index_PG[250:300]

Int64Index([], dtype='int64')

In [24]:
movie_info.iloc[[1307, 1309, 1313, 1318, 1336, 1348, 1351, 1363, 1370, 1380, 1386,
            1391, 1393, 1404, 1409, 1417, 1424, 1425, 1438, 1459, 1461, 1462,
            1463, 1466, 1468, 1471, 1473, 1476, 1485, 1486, 1493, 1498, 1511,
            1514, 1530, 1531, 1546, 1553, 1556, 1558]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1307,1690,Fifteen-year-old Jim Hawkins stumbles upon a m...,PG,Action and Adventure|Animation|Kids and Family...,Ron Clements|John Musker,Sam Levine|Alex Mann|Ron Clements|John Musker|...,"Nov 27, 2002","Apr 29, 2003",$,"38,120,554",95 minutes,Buena Vista Distribution Compa
1309,1692,"Long before Grease was even thought of, the Br...",PG,Classics|Drama|Musical and Performing Arts,Claude Whatham,Ray Connolly,"Jan 1, 1973","Nov 28, 2000",NaN,NaN,90 minutes,NaN
1313,1698,John Hughes continues the trend he began with ...,PG,Comedy|Kids and Family,NaN,John Hughes,"Jun 25, 1993","Jan 28, 2003",NaN,NaN,94 minutes,NaN
1318,1703,"In this film, filmmaker Akira Kurosawa spins t...",PG,Art House and International|Classics|Drama,Akira Kurosawa,Akira Kurosawa|Masato Ide,"Oct 10, 1980","Mar 29, 2005",NaN,NaN,179 minutes,NaN
1336,1730,Television sitcom star Tim Allen made his big ...,PG,Action and Adventure|Comedy|Kids and Family|Sc...,John Pasquin,Leo Benvenuti|Steve Rudnick,"Nov 11, 1994","Oct 13, 1998",NaN,NaN,97 minutes,NaN
1348,1742,Robin Wright and Cary Elwes star in this fairy...,PG,Action and Adventure|Comedy|Kids and Family|Sc...,Rob Reiner,William Goldman,"Sep 25, 1987","Jan 26, 1999",NaN,NaN,98 minutes,20th Century Fox
1351,1745,"When a retired stock car driver, Brewster Bake...",PG,Comedy|Drama,NaN,Mike Marvin|Alex Matter,"Jul 16, 1982","Apr 4, 2006",NaN,NaN,110 minutes,NaN
1363,1760,Basketball superstar Michael Jordan and cartoo...,PG,Comedy|Kids and Family,Joe Pytka,Leo Benvenuti|Steve Rudnick|Timothy Harris|Her...,"Nov 15, 1996","Aug 27, 1997",NaN,NaN,88 minutes,NaN
1370,1769,"After sitting on the shelf for some time, Teen...",PG,Comedy|Science Fiction and Fantasy,Rod Daniel,Matthew Weisman|Jeph Loeb,"Aug 23, 1985","Sep 9, 2014",NaN,NaN,92 minutes,NaN
1380,1779,"In this film, Kit is a war-scarred veteran of ...",PG,Action and Adventure|Drama|Mystery and Suspens...,Richard Wallace,NaN,NaN,NaN,NaN,NaN,91 minutes,NaN
1386,1788,London 1818: a secret love affair begins betwe...,PG,Drama|Romance,Jane Campion,Jane Campion,"May 15, 2009","Jan 26, 2010",$,"4,341,275",119 minutes,Apparition Films
1391,1795,"One of the first recognizable ""vigilante"" film...",PG,Action and Adventure|Art House and Internation...,NaN,Tom Laughlin,"Jul 12, 1967","Oct 31, 2000",NaN,NaN,112 minutes,NaN
1393,1798,For the Tibetan Mastiffs living on Snow Mounta...,PG,Animation|Comedy|Kids and Family,Ash Brannon,Ash Brannon|Kurt Voelker,"Feb 24, 2017","May 23, 2017",$,"9,404,922",80 minutes,Summit Premiere
1404,1812,An Army officer comes into conflict with a sma...,PG,Action and Adventure|Comedy,NaN,Dan Gordon|Bob Gale,"Mar 16, 1984","Jun 15, 1998",NaN,NaN,114 minutes,NaN
1409,1818,From Dr. No director Terence Young comes this ...,PG,Action and Adventure|Mystery and Suspense,Terence Young|Gail Harvey,Shimon Wincelberg|Dorothea Bennett|Albert Simo...,NaN,NaN,NaN,NaN,90 minutes,NaN
1417,1826,"This (13th) time around, 007 (once again playe...",PG,Action and Adventure|Drama|Mystery and Suspense,John Glen,NaN,"Jun 10, 1983","Oct 17, 2000",NaN,NaN,131 minutes,NaN
1424,1837,"""Becoming Jane,"" is the story of the great, un...",PG,Drama|Romance,Julian Jarrold,Sarah Williams|Kevin Hood,"Aug 3, 2007","Feb 12, 2008",$,"18,602,895",120 minutes,Miramax Films
1425,1839,The musicians of the Buena Vista Social Club e...,PG,Documentary,Lucy Walker,NaN,"May 26, 2017","Sep 12, 2017",$,"118,253",111 minutes,NaN
1438,1854,"The ""mermaids"" are really tribal pearl divers ...",PG,Action and Adventure|Drama|Romance,Robert Florey,Carroll Young,NaN,NaN,NaN,NaN,68 minutes,NaN
1459,1879,Thornton Wilder's award-winning novel is given...,PG,Art House and International|Drama|Faith and Sp...,Mary McGuckian,Mary McGuckian,"Jun 10, 2005","Oct 11, 2005",NaN,NaN,120 minutes,NaN
1461,1881,"""Bicentennial Man,"" follows the life and times...",PG,Comedy|Drama|Science Fiction and Fantasy,Chris Columbus,Nicholas Kazan,"Dec 17, 1999","Jan 15, 2002",NaN,NaN,131 minutes,Buena Vista Pictures
1462,1882,"In ""Ralph Breaks the Internet,"" video-game bad...",PG,Animation|Comedy|Kids and Family|Science Ficti...,Phil Johnston|Rich Moore,Phil Johnston|Pamela Ribon,NaN,NaN,NaN,NaN,114 minutes,Walt Disney Animation Studios
1463,1883,Burt Lancaster and Alain Delon play cat-and-mo...,PG,Action and Adventure|Drama|Mystery and Suspense,Michael Winner,NaN,"Apr 19, 1973","Jan 18, 2000",NaN,NaN,114 minutes,NaN
1466,1886,"""Houston, we have a problem."" Those words were...",PG,Action and Adventure|Drama,Ron Howard,Al Reinert|William Broyles,"Jun 30, 1995","Sep 7, 2004",NaN,NaN,140 minutes,Universal Pictures
1468,1889,Milos Foreman's cinematic adaptation of E.L. D...,PG,Drama,Milos Forman,NaN,"Nov 20, 1981","Nov 16, 2004",NaN,NaN,155 minutes,NaN
1471,1892,"Based on Peter Benchley's best-selling novel, ...",PG,Action and Adventure|Drama|Mystery and Suspense,Steven Spielberg,Howard Sackler|Carl Gottlieb|Peter Benchley,"Jun 1, 1975","Jul 11, 2000",NaN,NaN,124 minutes,Universal Pictures
1473,1896,"In the epic conclusion of the saga, the Empire...",PG,Action and Adventure|Drama|Science Fiction and...,Richard Marquand,George Lucas|Lawrence Kasdan,"May 25, 1983","Sep 12, 2006",NaN,NaN,133 minutes,Twentieth Century Fox
1476,1899,Thanks to the carelessness of a cute little do...,PG,Comedy|Horror|Science Fiction and Fantasy,Tim Burton,Warren Skaaren|Michael McDowell|Larry Wilson|M...,"Mar 30, 1988","Jun 26, 1997",NaN,NaN,93 minutes,NaN
1485,1911,This breathlessly paced high-tech thriller sta...,PG,Classics|Drama|Mystery and Suspense,Sidney Lumet,Lawrence Sanders|Frank Pierson,"Jun 17, 1971","Jan 6, 2003",NaN,NaN,95 minutes,NaN
1486,1912,"In the sequel to the hit comedy Sister Act, Wh...",PG,Comedy,Bill Duke,James Orr|Jim Cruickshank|Judi Ann Mason|James...,"Dec 10, 1993","Feb 20, 2001",NaN,NaN,106 minutes,NaN
1493,1923,"Cocoon 2: The Return, like most sequels, relie...",PG,Comedy|Drama|Science Fiction and Fantasy,NaN,NaN,"Nov 23, 1988","Jun 1, 2004",NaN,NaN,116 minutes,NaN
1498,1930,Sharp-tongued East End spy Harry Palmer once a...,PG,Action and Adventure|Art House and Internation...,Guy Hamilton,Evan Jones,"Jan 1, 1966","Aug 14, 2001",NaN,NaN,102 minutes,NaN
1511,1945,"Left on a nun's doorstep, Larry, Curly and Moe...",PG,Comedy,Bobby Farrelly|Peter Farrelly,Bobby Farrelly|Peter Farrelly|Mike Cerrone,"Apr 13, 2012","Jul 17, 2012",$,"41,800,000",92 minutes,20th Century Fox
1514,1949,"A sweet, innocent and none-too-educated Southe...",PG,Comedy|Romance,Barnet Kellman,Craig Bolotin|Patricia Resnick|Susan Berman,"Apr 3, 1992","May 6, 2003",NaN,NaN,91 minutes,NaN
1530,1968,"This holiday season, acclaimed filmmaker Camer...",PG,Comedy|Drama,Cameron Crowe,Aline Brosh McKenna|Cameron Crowe,"Dec 23, 2011","Apr 3, 2012",$,"72,700,000",126 minutes,20th Century Fox
1531,1969,Melvin Frank's burlesque amalgam of McCabe and...,PG,Action and Adventure|Comedy|Western,Melvin Frank,NaN,"Apr 1, 1976","Jun 7, 2005",NaN,NaN,104 minutes,NaN
1546,1986,Aki Kaurismaki's The Man Without a Past opens ...,PG,Art House and International|Comedy|Drama,NaN,NaN,"Aug 30, 2002","Oct 7, 2003",$,"794,306",97 minutes,NaN
1553,1993,A former child actor turned talent agent is hi...,PG,Comedy,James Lapine,NaN,"Jun 4, 1993","Apr 8, 2003",NaN,NaN,95 minutes,NaN
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,"Jul 23, 1993","Apr 17, 2001",NaN,NaN,88 minutes,Paramount Vantage
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,"Apr 1, 1993","Jan 29, 2002",NaN,NaN,101 minutes,NaN

In [19]:
#checking if the names are already used
for i in name_movies:
    if i == 'Sound of Music':
        print('yes!')
else:print('no')

no

In [26]:
movie_buddget.iloc[[543,653,928,934,954,1028,1252,1459,1546]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
543,44,"May 7, 1999",The Mummy,"$80,000,000","$155,385,488","$416,385,488"
653,54,"Jun 4, 2010",Killers,"$75,000,000","$47,059,963","$95,572,749"
928,29,"May 13, 2011",Priest,"$60,000,000","$29,136,626","$84,154,026"
934,35,"Aug 14, 1998",The Avengers,"$60,000,000","$23,385,416","$48,585,416"
954,55,"Jan 25, 2019",The Kid Who Would Be King,"$59,000,000","$16,790,790","$28,348,446"
1028,29,"Jun 4, 1999",Instinct,"$55,000,000","$34,105,207","$34,105,207"
1252,53,"Nov 20, 1998",A Bug's Life,"$45,000,000","$162,798,565","$363,095,319"
1459,60,"Aug 26, 2011",Colombiana,"$40,000,000","$36,665,854","$72,295,262"
1546,47,"Feb 2, 2007",Because I Said So,"$39,000,000","$42,674,040","$69,538,833"

In [27]:
#new name index for pg
no1=[543,653,928,934,954,1028,1252,1459,1546]

Based on the indexes on the 'PG' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-rated. The 25 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [22]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Cars':
        print('yes')

In [28]:
#informtions on the movies needed for pg
# the name of the movies
name_mojo2 = ['Lagaan','April and the Extraordinary World',' Badlands','Where the Wild Things Are','Andrei Rublev',
              'Tokyo Story',
             'Bicycle Thieves','Days of Heaven','Suspiria','Under the Skin','Midnight in Paris','Frida',
             'Girl with a Pearl Earring','Mr. Turner','The Tree of Life','Waste Land','Rivers and Tides','Moonlight',
             '3 Ninjas','Karate Kid','Walt Before Mickey','Loving Vincent','The Best Offer ','Basquiat (film)',
             'La Belle Noiseuse','Mona Lisa Smile drawing','Days of Heaven','Solaris','The Conformist']
# ratings of the movies
rating_mojo2 = [9.5,9.1,7.8,6.7,8.2,7.8,
             8,5,7,6.4,8.9,7.4
             ,6.9,6.8,7.4,5.3,8,7
             ,7.3,6,8,5.4,7.8,7,5
             ,7.8,6.2,8]
# worldwide gross
worldwide_gross_mojo2 = ['$40,717,774','$495,879','$67,458','$100,140,096','$145,491','$59,654',
             '$428,978','$15,355,298','$7,942,093','$5,735,963','$153,959,590',' $56,300,000',
             '$31,466,789','$22,200,000','$58,409,247','$291,307','$5,042,641','$65,300,000',
             '$54,777,551','$335,299,206','$476,046','$42,187,665','$20,596,350','$5,109,693',
             '$777,754','$187,067,435','$22,436,801','$190,144,486','$2,768,810']
# domestic gross
domestic_gross_mojo2 = ['$835,767','$295,488','$67,458','$77,233,467','$124,189','$59,654',
             '$371,111','$14,457,141','$2,483,472','$2,614,251','$56,817,045','$25,900,000 ',
             '$11,670,971','$3,958,500','$13,303,319','$187,716','$3,293,762','$27,854,932',
             '$54,776,983','$233,515,218','$476,046','$6,735,118','$100,035','$5,109,693',
             '$777,754','$84,522,942','$21,124,435','$94,894,810','$405,268']
          
# product budget
product_budget_mojo2 = ['$5,138,425','$10,400,000','$558,062','$100,000,000','$1,300,000','$35,000',
             '$133,000','$12,583,285','$20,000,000','$13,300,000','$17,000,000','$12,000,000',
             '$12,000,000','$11,641,518','$32,000,000','$1,500,000','$$898,186','$4,000,000',
             '$4,722,153','$20,570,503','$568,000','$5,500,000','$18,000,000','$5,599,766',
             '$1,168,044','$63,860,942','$18,386,400','$5,253,842','$5,181,843']

In [37]:
# making sure all system_rating have the same amout of records
# getting system NR: need 23
index_PG = movie_info[movie_info['rating']=='NR'].index
index_PG[200:250]

Int64Index([618, 628, 629, 630, 638, 642, 644, 645, 647, 648, 654, 656, 658,
            661, 669, 677, 678, 679, 688, 693, 697, 699, 700, 711, 713, 714,
            715, 718, 720, 722, 724, 727, 731, 734, 735, 739, 742, 743, 745,
            747, 750, 767, 768, 770, 771, 772, 773, 776, 788, 789],
           dtype='int64')

In [50]:
movie_info.iloc[[ 618, 628, 629, 630, 638, 642, 644, 645, 647, 648, 654, 656, 658,
            661, 669, 677, 678, 679, 688, 693, 697, 699, 700, 711, 713, 714,
            715, 718, 720, 722, 724, 727, 731, 734, 735, 739, 742, 743, 745,
            747, 750, 767, 768, 770, 771, 772, 773, 776, 788, 789]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
618,798,"Celia, who calls herself Ginevra, is a movie a...",NR,Drama,Ingemo Engstrom,NaN,NaN,NaN,NaN,NaN,157 minutes,NaN
628,810,This frothy romantic comedy from Korea begins ...,NR,Comedy|Drama|Romance,Jae-young Kwak,Jae-young Kwak|Ho-sik Kim,"Jul 27, 2001","Feb 19, 2013",NaN,NaN,123 minutes,NaN
629,811,The trials and tribulations of four teenagers-...,NR,Art House and International|Drama,Eli Cohen,NaN,"Jan 1, 1994","Jan 24, 2006",NaN,NaN,141 minutes,NaN
630,812,Hands of a Stranger was adapted by playwright ...,NR,Drama|Mystery and Suspense,Larry Elikann,NaN,NaN,NaN,NaN,NaN,179 minutes,NaN
638,821,"In this drama, set in a Scandinavian hospital ...",NR,Art House and International|Comedy|Drama,Mai Zetterling,David Hughes|Mai Zetterling,NaN,NaN,NaN,NaN,113 minutes,NaN
642,826,"Stanley Kubrick's second film, Killer's Kiss w...",NR,Classics|Drama|Mystery and Suspense,Stanley Kubrick,NaN,"Sep 28, 1955","May 15, 2001",NaN,NaN,67 minutes,NaN
644,828,Robert Stack and Dorothy Malone are Cliff and ...,NR,Action and Adventure|Classics|Drama,NaN,NaN,"Feb 19, 1960","Oct 24, 2006",NaN,NaN,91 minutes,NaN
645,829,International sex symbol Jane Birkin (of BLOW-...,NR,Art House and International|Horror|Mystery and...,Antonio Margheriti,Giovanni Simonelli|Antonio Margheriti,"Jan 1, 1973","Oct 25, 2005",NaN,NaN,95 minutes,Blue Underground
647,831,"Filming weddings is a thankless job, so when A...",NR,Comedy,Pavan Moondi,Pavan Moondi,NaN,NaN,NaN,NaN,98 minutes,Factory 25
648,832,"Based on Russian folklore, this slapstick sati...",NR,Art House and International,Alexander Medvedkin,NaN,NaN,NaN,NaN,NaN,69 minutes,NaN
654,838,The Weight of Water is the story of a blind ad...,NR,Action and Adventure|Documentary,Michael Brown,NaN,NaN,NaN,NaN,NaN,79 minutes,NaN
656,840,"Wrongfully convicted for a hold-up, a war vet ...",NR,Classics|Drama|Mystery and Suspense,Mervyn Le Roy,Sheridan Gibney|Brown Holmes,"Nov 19, 1932","May 10, 2005",NaN,NaN,90 minutes,NaN
658,843,Miners want to drill for billions of dollars w...,NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60 minutes,NaN
661,847,"In this Alfred Hitchcock film, Derrick De Marn...",NR,Classics|Drama|Mystery and Suspense,Alfred Hitchcock,Alma Reville|Charles Bennett|Gerald Savory|Edw...,"Feb 17, 1938","Jul 30, 2002",NaN,NaN,80 minutes,NaN
669,857,Gary Cooper stars as an island drifter who fal...,NR,Drama|Romance,Mark Robson,NaN,NaN,NaN,NaN,NaN,100 minutes,NaN
677,866,Judith Allen stars as Telephone Operator Helen...,NR,Drama,Scott Pembroke,NaN,NaN,NaN,NaN,NaN,61 minutes,NaN
678,867,An original comedy that casts Marcello Mastroi...,NR,Comedy|Romance,Vittorio De Sica,Eduardo De Filippo|Isabella Quarantotti|Cesare...,"Dec 19, 1963","Jun 29, 2004",NaN,NaN,119 minutes,NaN
679,868,Filmmaker Irene Lusztig unearths a dark family...,NR,Art House and International|Documentary|Specia...,Irene Lusztig,Irene Lusztig,NaN,NaN,NaN,NaN,90 minutes,NaN
688,880,"In this musical western, ranch owner ""Lucky"" L...",NR,Western,Joseph Kane,Betty Burbridge,NaN,NaN,NaN,NaN,60 minutes,NaN
693,888,The Knute Rockne legend is largely founded on ...,NR,Classics|Drama,Lloyd Bacon,Robert Buckner,"Jan 1, 1940","Aug 15, 2006",NaN,NaN,98 minutes,NaN
697,895,"After a sexual assault by a random stranger, S...",NR,Drama|Horror|Mystery and Suspense,Eric England,Eric England,"Nov 22, 2013","Mar 18, 2014",$,"3,328",84 minutes,IFC Films
699,897,Just before his demotion to the ranks of minor...,NR,Action and Adventure|Drama,NaN,Frederick Hugh Herbert,NaN,NaN,NaN,NaN,70 minutes,NaN
700,898,To quell the rumors that musical stars Alice F...,NR,Classics|Drama|Musical and Performing Arts|Rom...,Walter Lang,Robert Ellis|Helen Logan,"Nov 22, 1940","Jul 19, 1994",NaN,NaN,94 minutes,NaN
711,913,"For recent retiree Caroline (Fanny Ardant, 8 W...",NR,Comedy|Drama,Marion Vernoux,Marion Vernoux|Fanny Chesnel,NaN,NaN,NaN,NaN,94 minutes,Tribeca Film
713,915,An experiment gone wrong gives new meaning to ...,NR,Horror|Science Fiction and Fantasy,Ian Curteis,NaN,NaN,NaN,NaN,NaN,77 minutes,NaN
714,918,Max Shulman and Robert Paul Smith's Broadway h...,NR,Classics|Comedy|Musical and Performing Arts|Ro...,Charles Walters,NaN,"Jan 1, 1955","May 13, 2008",NaN,NaN,111 minutes,NaN
715,919,The PBS series Great Performances first presen...,NR,Drama,Fielder Cook,Ronald Ribman,"Sep 9, 1986","Feb 18, 2003",NaN,NaN,93 minutes,NaN
718,923,Director Howard Hawks' second western was also...,NR,Action and Adventure|Western,Howard Hawks,Borden Chase|Charles Schnee,NaN,NaN,NaN,NaN,133 minutes,NaN
720,925,"Adapted from the book by David Foster Wallace,...",NR,Comedy|Drama,John Krasinski,John Krasinski,"Sep 25, 2009","Mar 16, 2010",NaN,NaN,80 minutes,IFC
722,928,Cecil B. DeMille's The Greatest Show on Earth ...,NR,Classics|Drama|Kids and Family|Romance,NaN,NaN,"Feb 21, 1952","Apr 6, 2004",NaN,NaN,92 minutes,NaN
724,931,Dilwale Dulhania Le Jayenge (Brave Heart Will ...,NR,Art House and International|Comedy|Kids and Fa...,Aditya Chopra,Aditya Chopra,"Oct 19, 1995","May 18, 2004",NaN,NaN,192 minutes,NaN
727,934,A young man is in danger of losing his inherit...,NR,Classics|Mystery and Suspense,NaN,John Krafft,"Oct 28, 1936","Mar 15, 2005",NaN,NaN,70 minutes,NaN
731,939,When North Korean soldiers attempt to assassin...,NR,Action and Adventure|Art House and Internation...,Woo-Suk Kang|Kang Woo-seok,Kim Heui-jae,"Apr 24, 2003","Dec 1, 2014",NaN,NaN,134 minutes,Cinema Service
734,943,"Classic, heartbreaking neo-realist drama of tw...",NR,Art House and International|Classics|Drama,Vittorio De Sica,Sergio Amidei|Adolfo Franci|Cesare Giulio Viol...,"Aug 26, 1947","May 17, 2011",NaN,NaN,90 minutes,NaN
735,944,The producers of Quartet and Trio concluded th...,NR,Classics|Comedy|Drama,Harold French|Pat Jackson|Anthony Pelissier,NaN,NaN,NaN,NaN,NaN,85 minutes,NaN
739,950,A young man trying to break out of his blue co...,NR,Drama,Chris Kentis,Laura Lau|Chris Kentis,"Apr 11, 1997","Feb 13, 2001",NaN,NaN,96 minutes,NaN
742,957,"J.J. Hunsecker, a powerful New York newspaper ...",NR,Classics|Drama,Alexander Mackendrick,Clifford Odets|Ernest Lehman,"Jun 27, 1957","Jun 19, 2001",NaN,NaN,96 minutes,NaN
743,959,Two young women try to climb the corporate lad...,NR,Art House and International|Drama|Romance,Jean-Claude Brisseau,Jean-Claude Brisseau,"Apr 9, 2003","Nov 23, 2004",NaN,NaN,115 minutes,NaN
745,962,"Punk rocker, performance artist, and persona n...",NR,Documentary|Musical and Performing Arts,Todd Phillips,NaN,"Jan 1, 1994","Jan 25, 2000",NaN,NaN,120 minutes,NaN
747,964,"In 1995, during the making of his TV series Tr...",NR,Documentary|Special Interest,Jonathan Challis|Susan Crook|John Coffey|Ian L...,NaN,"May 11, 2012","Oct 22, 2012",$,"104,286",70 minutes,Magnolia Pictures
750,968,Arnab a typical Bengali man is making his way ...,NR,Art House and International|Horror|Mystery and...,Prosit Roy,Abhishek Bannerjee|Prosit Roy|Rajat Kapoor,NaN,NaN,NaN,NaN,NaN,NaN
767,988,NaN,NR,Horror,NaN,NaN,NaN,NaN,NaN,NaN,83 minutes,NaN
768,992,"In 1988, Taileen slips into a coma after a car...",NR,Horror|Mystery and Suspense,Luis Almeida,Luis Almeida,"Nov 21, 2006","Nov 21, 2006",NaN,NaN,106 minutes,NaN
770,996,A depressed ex-boxer finds his future looking ...,NR,Comedy|Drama|Mystery and Suspense,Nicanor Loreti,NaN,"Nov 5, 2011","Jun 18, 2013",NaN,NaN,85 minutes,NaN
771,997,John Denver stars in this thrilling drama--ori...,NR,Action and Adventure,NaN,NaN,NaN,NaN,NaN,NaN,96 minutes,NaN
772,998,Set amidst the political and economic havoc ca...,NR,Comedy|Mystery and Suspense,Ilkka Jarvilaturi,Paul Kolsby,NaN,NaN,NaN,NaN,99 minutes,NaN
773,999,Yet another teenager discovers how difficult g...,NR,Comedy,Holly Goldberg Sloan,Holly Goldberg Sloan,NaN,NaN,NaN,NaN,90 minutes,NaN
776,1002,No film critic of 1989 could write an assessme...,NR,Action and Adventure|Art House and Internation...,Jacques Rivette,Pascal Bonitzer|Christine Laurent,"Dec 22, 1989","Jan 2, 2002",NaN,NaN,150 minutes,NaN
788,1020,The title character of the Russian Little Vera...,NR,Art House and International|Drama|Romance,Vasili Pichul,Mariya Khmelik,"Apr 14, 1989","Aug 28, 2000",NaN,NaN,130 minutes,NaN
789,1021,NaN,NR,Documentary,Henri Cartier-Bresson,Alfred Lewis Levitt,NaN,NaN,NaN,NaN,33 minutes,NaN

In [40]:
movie_buddget.iloc[[331,335,352,363,364,371,386,394,429,451,483,506,529,547,555,
                   558,560,564,578,592,598,629,638]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
331,32,"Jun 11, 2010",The A-Team,"$110,000,000","$77,222,099","$177,241,171"
335,36,"Nov 1, 2013",Ender's Game,"$110,000,000","$61,737,191","$127,983,283"
352,53,"Apr 27, 2001",Town & Country,"$105,000,000","$6,712,451","$10,364,769"
363,64,"Nov 15, 2002",Harry Potter and the Chamber of Secrets,"$100,000,000","$262,233,381","$879,225,135"
364,65,"Jul 2, 1991",Terminator 2: Judgment Day,"$100,000,000","$203,464,105","$515,419,827"
371,72,"Nov 2, 2007",American Gangster,"$100,000,000","$130,164,645","$267,985,456"
386,87,"Jun 11, 2004",The Stepford Wives,"$100,000,000","$59,475,623","$96,221,971"
394,95,"Jul 23, 2004",Catwoman,"$100,000,000","$40,202,379","$82,145,379"
429,30,"Jul 18, 2001",Jurassic Park III,"$93,000,000","$181,166,115","$365,900,000"
451,52,"Jul 11, 1997",Contact,"$90,000,000","$100,920,329","$165,900,000"
483,84,"Sep 14, 2018",The Predator,"$88,000,000","$51,024,708","$159,487,563"
506,7,"Mar 30, 2012",Mirror Mirror,"$85,000,000","$64,935,167","$173,613,482"
529,30,"Dec 15, 2006",Charlotte's Web,"$82,500,000","$82,985,708","$143,985,708"
547,48,"Jul 12, 2013",Grown Ups 2,"$80,000,000","$133,668,525","$247,023,808"
555,56,"Dec 25, 2008",Bedtime Stories,"$80,000,000","$110,101,975","$221,468,935"
558,59,"Feb 14, 2003",Daredevil,"$80,000,000","$102,543,518","$182,782,518"
560,61,"Jun 6, 1997",Con Air,"$80,000,000","$101,117,573","$224,117,573"
564,65,"Nov 26, 1997",Flubber,"$80,000,000","$92,993,801","$177,993,801"
578,79,"Jul 30, 2004",The Manchurian Candidate,"$80,000,000","$65,948,711","$96,148,711"
592,93,"Dec 20, 2013",Walking with Dinosaurs,"$80,000,000","$36,076,121","$123,368,842"
598,99,"Nov 14, 2003",Looney Tunes: Back in Action,"$80,000,000","$20,950,820","$54,540,662"
629,30,"Jun 30, 2017",Despicable Me 3,"$75,000,000","$264,624,300","$1,034,727,750"
638,39,"Feb 13, 2004",50 First Dates,"$75,000,000","$120,776,832","$196,320,329"

In [44]:
# new names index for NR
no3=[331,335,352,363,364,371,386,394,429,451,483,506,529,547,555,
                   558,560,564,578,592,598,629,638]

In [51]:
# making sure all system_rating have the same amout of records
# getting system G: need 37
index_G = movie_info[movie_info['rating']=='G'].index
index_G[:50]

Int64Index([  21,   30,   65,   90,  143,  154,  168,  170,  248,  254,  264,
             279,  294,  381,  401,  404,  433,  454,  501,  548,  593,  634,
             702,  704,  792,  795,  810,  892,  894,  958,  994, 1041, 1051,
            1075, 1080, 1102, 1105, 1123, 1147, 1156, 1208, 1209, 1227, 1241,
            1314, 1323, 1325, 1349, 1405, 1439],
           dtype='int64')

In [52]:
movie_info.iloc[[ 21,   30,   65,   90,  143,  154,  168,  170,  248,  254,  264,
             279,  294,  381,  401,  404,  433,  454,  501,  548,  593,  634,
             702,  704,  792,  795,  810,  892,  894,  958,  994, 1041, 1051,
            1075, 1080, 1102, 1105, 1123, 1147, 1156, 1208, 1209, 1227, 1241,
            1314, 1323, 1325, 1349, 1405, 1439]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
21,28,Elvis goes Hawaiian for the second time in thi...,G,Classics|Comedy|Musical and Performing Arts|Ro...,NaN,Allan Weiss|Anthony Lawrence,"Jun 15, 1966","Jan 7, 2003",NaN,NaN,90 minutes,NaN
30,42,"Warner Bros.' ""Perry Mason"" series quietly sli...",G,Action and Adventure|Classics|Drama|Mystery an...,NaN,Frederick Hugh Herbert,NaN,NaN,NaN,NaN,65 minutes,NaN
65,83,"Told in flashback, Affair with a Stranger reco...",G,Comedy|Drama|Kids and Family|Romance,Roy Rowland,Richard Flournoy,NaN,NaN,NaN,NaN,89 minutes,NaN
90,115,"""Toy Story 2"" is the exciting, all-new sequel ...",G,Animation|Comedy|Kids and Family|Science Ficti...,John Lasseter,Doug Chamberlain|Rita Hsiao|Doug Chamberlin|Ch...,"Nov 24, 1999","Oct 17, 2000",NaN,NaN,92 minutes,Buena Vista Pictures
143,187,Tommy (Anthony Rogers) is a young stamp collec...,G,Action and Adventure|Kids and Family|Science F...,Michael Rubbo,Michael Rubbo,"Dec 8, 1988","Oct 24, 2006",NaN,NaN,101 minutes,NaN
154,200,It took some doing to persuade the staunchly C...,G,Classics|Comedy|Drama|Musical and Performing Arts,Leo McCarey,Frank Corvett|Frank Butler|Frank Cavett|Leo Mc...,"May 3, 1944","Feb 6, 2007",NaN,NaN,126 minutes,NaN
168,222,Inasmuch as the spectacular Richard Rodgers an...,G,Action and Adventure|Classics|Comedy|Musical a...,Charles Walters,Sidney Sheldon,"Jan 1, 1962","Apr 26, 2005",NaN,NaN,124 minutes,NaN
170,224,"Steve McQueen stars as the Cincinnati Kid, a c...",G,Classics|Drama,Norman Jewison,NaN,"Oct 15, 1965","May 31, 2005",NaN,NaN,113 minutes,NaN
248,323,"Yes, Paul Newman is a blue-eyed Indian in Homb...",G,Action and Adventure|Western,Martin Ritt,NaN,"Jan 1, 1967","Jun 4, 2002",NaN,NaN,111 minutes,NaN
254,332,ACP Ajay Rathore is transferred to Mumbai to e...,G,Action and Adventure|Art House and International,John Mathew Matthan,NaN,"Apr 30, 1999","Jul 27, 1999",NaN,NaN,155 minutes,NaN
264,349,Lewis Carroll's classic fantasy about a young ...,G,Kids and Family|Science Fiction and Fantasy,John Henderson,NaN,"Jun 1, 1998","Jan 11, 2005",NaN,NaN,83 minutes,NaN
279,368,"Originally Tokyo Monogatari, Yasujiro Ozu's To...",G,Art House and International|Drama,Yasujiro Ozu,NaN,"Nov 3, 1953","Oct 30, 2003",NaN,NaN,134 minutes,NaN
294,388,"Hard-hitting and gritty, this prison film chro...",G,Classics|Drama,Jules Dassin,Richard Brooks,"Jan 1, 1947","Apr 17, 2007",NaN,NaN,94 minutes,Criterion Collection
381,494,This superbly animated children's tale is dire...,G,Animation|Drama|Kids and Family|Science Fictio...,Hayao Miyazaki,Hayao Miyazaki,"Jan 1, 1988","Mar 7, 2006",NaN,NaN,87 minutes,NaN
401,522,A large-format Imax film about the career of M...,G,Documentary|Special Interest|Sports and Fitness,NaN,Jonathan Hock,"May 5, 2000","Feb 13, 2001",NaN,NaN,45 minutes,NaN
404,526,Norman Jewison's adaptation of the long-runnin...,G,Classics|Comedy|Drama|Kids and Family|Musical ...,Norman Jewison,Joseph Stein,"Nov 3, 1971","Jun 30, 1998",NaN,NaN,179 minutes,NaN
433,566,Both actress Judy Davis and director Gillian A...,G,Art House and International|Drama|Romance,Gillian Armstrong,Eleanor Witcombe,"Aug 17, 1979","May 31, 2005",NaN,NaN,101 minutes,Westchester Films
454,596,"""Arctic Tale"" is an epic adventure that explor...",G,Documentary|Special Interest,Adam Ravetch|Sarah Robertson,Linda Woolverton|Mose Richards|Kristin Gore,"Aug 17, 2007","Aug 1, 2017",$,"598,103",86 minutes,Paramount Vantage
501,656,This is the large-screen debut of famous (or i...,G,Kids and Family,Steve Gomer,Stephen White,"Apr 3, 1998","Sep 1, 1998",NaN,NaN,75 minutes,NaN
548,717,One of the first important distinctions to be ...,G,Drama|Special Interest,NaN,NaN,NaN,NaN,NaN,NaN,73 minutes,NaN
593,766,In a film designed to bring smiles to the post...,G,Action and Adventure|Animation|Comedy|Kids and...,Arna Selznick,Peter Sauder,"Dec 31, 1985","Aug 6, 2002",NaN,NaN,76 minutes,NaN
634,817,Based on the Broadway play by Robert Fryer and...,G,Classics|Comedy|Romance,Walter Lang,Phoebe Ephron|Henry Ephron,"May 15, 1957","May 4, 2004",NaN,NaN,104 minutes,NaN
702,901,Winged Migration co-directors Jacques Cluzaud ...,G,Documentary|Drama,Jacques Cluzaud|Jacques Perrin,NaN,"Apr 22, 2010","Oct 19, 2010",$,"19,000,000",103 minutes,Disneynature
704,903,Director James Cameron journeys back to the si...,G,Comedy|Documentary|Science Fiction and Fantasy...,James Cameron,NaN,"Apr 11, 2003","Apr 27, 2004",$,"16,302,332",59 minutes,Buena Vista Distribution
792,1024,"In this musical, Fred Astaire and Burgess Mere...",G,Classics|Comedy|Musical and Performing Arts|Ro...,NaN,Johnny Mercer|Ian McLellan Hunter|Frank Cavett...,"Jan 1, 1940","Jul 25, 2006",NaN,NaN,83 minutes,NaN
795,1028,"Brian Henson, the son of Muppet founder Jim He...",G,Kids and Family|Science Fiction and Fantasy,Brian Henson,Jerry Juhl,"Jan 1, 1992","Oct 8, 2002",NaN,NaN,120 minutes,NaN
810,1047,NaN,G,Drama|Musical and Performing Arts,Nils Tavernier,NaN,NaN,NaN,NaN,NaN,95 minutes,Les Films du Losange
892,1154,Darrell Rooney directed this direct-to-video s...,G,Action and Adventure|Animation|Comedy|Drama|Ki...,Rob LaDuca|Darrell Rooney,Flip Kobler|Cindy Marcus,"Oct 27, 1998","Oct 27, 1998",NaN,NaN,75 minutes,NaN
894,1156,"A blend of live-action and animation, Fun and ...",G,Action and Adventure|Animation|Classics|Comedy...,Jack Kinney|Hamilton Luske|Bill Roberts|Willia...,Ted Sears|Eldon Dedini|Homer Brightman|Harry R...,"Sep 27, 1947","Jun 20, 2000",NaN,NaN,96 minutes,NaN
958,1239,Something mysterious is happening in the Hundr...,G,Animation|Kids and Family,Frank Nissen,Brian Hohlfeld|Evan Spiliotopoulos,"Feb 11, 2005","May 24, 2005",$,"18,013,938",67 minutes,Buena Vista
994,1287,Powaqqatsi was the second of the feature-lengt...,G,Art House and International|Documentary|Drama|...,Godfrey Reggio,Godfrey Reggio|Ken Richards,"Apr 29, 1988","Sep 17, 2002",NaN,NaN,95 minutes,NaN
1041,1346,This moving prison drama tells the fascinating...,G,Classics|Drama|Mystery and Suspense,John Frankenheimer,Elizabeth Stroud|Guy Trosper|Guy Troper,"Jul 3, 1962","Mar 6, 2001",NaN,NaN,143 minutes,NaN
1051,1358,"Returning to the Ireland of his birth, directo...",G,Classics|Comedy|Drama|Romance,John Ford,NaN,"Aug 14, 1952","Feb 20, 2001",NaN,NaN,129 minutes,NaN
1075,1386,A pair of bumbling vampire-hunters attempts to...,G,Art House and International|Comedy|Horror,Roman Polanski,NaN,"Nov 13, 1967","Oct 5, 2004",NaN,NaN,107 minutes,NaN
1080,1391,Murder by Contract was more professionally ben...,G,Drama|Mystery and Suspense,Irving Lerner,Benjamin Simcoe,"Dec 1, 1958","Nov 3, 2009",NaN,NaN,81 minutes,NaN
1102,1418,A comedy drama set on a Yorkshire chicken farm...,G,Action and Adventure|Animation|Comedy|Drama|Ki...,Peter Lord|Nick Park,Jack Rosenthal|Karey Kirkpatrick,"Jun 21, 2000","Nov 21, 2000",$,"106,604,314",85 minutes,NaN
1105,1423,"In this comical Disney espionage adventure, a ...",G,Action and Adventure|Comedy|Kids and Family|My...,Robert Stevenson,Bill Walsh,"Aug 6, 1975","Nov 18, 1988",NaN,NaN,93 minutes,NaN
1123,1448,"Frank D. Gilroy's Pulitzer-winning ""kitchen si...",G,Classics|Drama,Ulu Grosbard,NaN,"Oct 13, 1968","May 30, 1996",NaN,NaN,108 minutes,NaN
1147,1477,In this sequel to the Academy Award -winning h...,G,Comedy|Kids and Family|Science Fiction and Fan...,George Miller,Dick-King Smith|Judy Morris|Mark Lamprell,"Nov 25, 1998","May 4, 1999",NaN,NaN,90 minutes,Universal Studios
1156,1488,"Christopher Lloyd, Kelly Ripa, Nicollette Sher...",G,Animation|Kids and Family|Science Fiction and ...,Ben Stassen,Domonic Paris|Dominic Paris,"Aug 15, 2008","Dec 2, 2008",$,"13,592,311",84 minutes,Summit Entertainment
1208,1554,The movie chronicles the adventures of a young...,G,Kids and Family|Musical and Performing Arts,Britt Allcroft,Britt Allcroft,"Jul 26, 2000","Oct 31, 2000",$,"2,027,042",95 minutes,Destination Films
1209,1555,This western spoof tells the story of a tough ...,G,Classics|Comedy|Musical and Performing Arts|We...,Elliot Silverstein|Elliott Silverstein,Walter Newman|Roy Chanslor|Frank Pierson,"Jun 24, 1965","Aug 8, 2000",NaN,NaN,97 minutes,NaN
1227,1583,This stark British/Norwegian film closely adhe...,G,Art House and International|Drama,Casper Wrede|Caspar Wrede,Ronald Harwood,NaN,NaN,NaN,NaN,100 minutes,NaN
1241,1604,Children's book authors Jean and Laurent de Br...,G,Animation|Art House and International|Kids and...,Alan Bunce,NaN,"Jul 28, 1989","Jan 20, 2004",NaN,NaN,75 minutes,NaN
1314,1699,The popular animated duo of cat and mouse team...,G,Animation|Comedy|Kids and Family,Phil Roman,Dennis Marks,"Jan 1, 1992","Mar 12, 2002",NaN,NaN,80 minutes,NaN
1323,1711,"Directed by Garry Marshall, The Princess Diari...",G,Comedy|Kids and Family,Garry Marshall,Shonda Rhimes,"Aug 11, 2004","Dec 14, 2004",$,"95,111,012",113 minutes,NaN
1325,1713,"In this second of his saga of four seasons, wr...",G,Drama|Romance,Eric Rohmer,NaN,"Jan 29, 1992","Feb 9, 2015",NaN,NaN,114 minutes,Big World Pictures
1349,1743,This animated feature chronicles the trials an...,G,Animation|Kids and Family|Science Fiction and ...,Art Vitello,NaN,NaN,NaN,NaN,NaN,100 minutes,NaN
1405,1813,Astronauts unwittingly bring some alien goo ab...,G,Drama|Horror|Science Fiction and Fantasy,Kinji Fukasaku,Charles Sinclair|Tom Rowe|William Finger,"Jan 1, 1969","Sep 25, 1991",NaN,NaN,90 minutes,NaN
1439,1855,Following the surprisingly successful children...,G,Action and Adventure|Kids and Family|Science F...,NaN,Michael Ende|Karin Howard,"Jun 1, 1991","Sep 4, 2001",NaN,NaN,90 minutes,NaN

In [53]:
movie_buddget.iloc[[433,994,1075,1227]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
433,34,"Feb 14, 2013",A Good Day to Die Hard,"$92,000,000","$67,349,198","$304,249,198"
994,95,"Nov 10, 2017",Murder on the Orient Express,"$55,000,000","$102,826,543","$345,922,730"
1075,76,"Apr 16, 2003",Bulletproof Monk,"$52,000,000","$23,010,607","$23,010,607"
1227,28,"Oct 20, 2000",Bedazzled,"$48,000,000","$37,879,996","$90,376,224"

In [54]:
# new names index for G
no4 = [433,994,1075,1227]

Based on the indexes on the 'G' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was G-rated. The 37 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [29]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'The Prince and the Pauper':
        print('yes')

In [30]:
#informtions on the movies needed for g
# the name of the movies
name_mojo3 = ['','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','',]
# ratings of the movies
rating_mojo3 = [,,,,,,
             ,,,,,,
             ,,,,,,
             ,,,,,,
             ,,,,,,
             ,,]
# worldwide gross
worldwide_gross_mojo3 = ['','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','',]
# domestic gross
domestic_gross_mojo3 = ['','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','',]
# product budget
product_budget_mojo3 = ['','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','','','','','',
             '','',]

In [69]:
# making sure all system_rating have the same amout of records
# getting the index of  system R: need 21
index_R = movie_info[movie_info['rating']=='R'].index
index_R[300:350]

Int64Index([839, 842, 843, 846, 848, 849, 858, 861, 862, 864, 868, 872, 874,
            875, 876, 880, 881, 898, 899, 900, 901, 903, 906, 909, 910, 912,
            915, 917, 925, 927, 930, 935, 938, 939, 942, 943, 947, 951, 953,
            955, 967, 968, 971, 973, 975, 977, 979, 982, 996, 997],
           dtype='int64')

In [70]:
movie_info.iloc[[839, 842, 843, 846, 848, 849, 858, 861, 862, 864, 868, 872, 874,
            875, 876, 880, 881, 898, 899, 900, 901, 903, 906, 909, 910, 912,
            915, 917, 925, 927, 930, 935, 938, 939, 942, 943, 947, 951, 953,
            955, 967, 968, 971, 973, 975, 977, 979, 982, 996, 997]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
839,1084,"Shy, sensitive April (Emma Roberts) is the cla...",R,Drama,Gia Coppola,Gia Coppola,"May 9, 2014","Sep 9, 2014",$,"406,235",100 minutes,Tribeca Film
842,1089,Writer/director Gus Van Sant's early bid for b...,R,Comedy|Drama|Science Fiction and Fantasy,Gus Van Sant,Gus Van Sant,"May 20, 1994","Nov 2, 2004",NaN,NaN,100 minutes,NaN
843,1090,Voter apathy in the United States is at an all...,R,Classics|Comedy,NaN,Jack Margolis,"Apr 1, 1975","Sep 2, 2008",NaN,NaN,95 minutes,NaN
846,1093,Tennessee Williams' 27 Wagons Full of Cotton w...,R,Classics|Comedy,Elia Kazan,Tennessee Williams,"Dec 18, 1956","Jul 9, 2003",NaN,NaN,114 minutes,NaN
848,1095,Kevin Smith's follow-up to his unexpected hit ...,R,Comedy,Kevin Smith,Kevin Smith,"Oct 20, 1995","Jul 18, 2000",NaN,NaN,95 minutes,NaN
849,1096,Harry Hook directed this second screen adaptat...,R,Action and Adventure|Drama,Harry Hook,Jay Presson Allen|Sara Schiff,"Jan 1, 1989","Nov 20, 2001",NaN,NaN,90 minutes,NaN
858,1108,Chris has a job interview in Raleigh in three ...,R,Horror|Mystery and Suspense,Rob Schmidt,NaN,"May 30, 2003","Oct 14, 2003",$,"15,176,515",95 minutes,20th Century Fox Distribution
861,1113,"Luke Wilson, Giovanni Ribisi, and Gabriel Mach...",R,Comedy|Drama,George Gallo,George Gallo|Andy Weiss,"Aug 6, 2010","Feb 8, 2011",$,"723,714",112 minutes,Paramount Pictures
862,1114,"When four lifelong friends-Regina Hall, Queen ...",R,Comedy|Drama,NaN,Kenya Barris|Tracy Oliver,"Jul 21, 2017","Oct 17, 2017",$,"115,088,305",122 minutes,Universal Pictures
864,1116,In director Dennis Hopper's comedy reminiscent...,R,Comedy,Dennis Hopper,John Rice|Joe Batteer|Dan Gilroy|Joe Gayton,"Apr 22, 1994","Dec 5, 2000",NaN,NaN,105 minutes,NaN
868,1122,TOUCHY FEELY is a closely observed examination...,R,Drama,Lynn Shelton,Lynn Shelton,"Sep 6, 2013","Dec 10, 2013",$,"35,966",90 minutes,Magnolia Pictures
872,1128,When an aging executive takes a vacation to Ri...,R,Comedy|Romance,Stanley Donen,Charlie Peters|Larry Gelbart,"Feb 17, 1984","May 22, 2001",NaN,NaN,90 minutes,NaN
874,1132,Driven over the edge by drugs and crime at the...,R,Action and Adventure|Drama,Albert Pyun,John Stockwell|Marty Ross|Scott Fields,"Jun 1, 1986","Feb 24, 2015",NaN,NaN,96 minutes,NaN
875,1133,This contemporary western stars Dermot Mulrone...,R,Drama|Mystery and Suspense,Michael Fields,Richard Ford Grayling,"Jun 1, 1991","Feb 5, 1992",NaN,NaN,94 minutes,NaN
876,1134,"A homage to Von Sternberg's 'The Blue Angel,' ...",R,Documentary|Drama|Special Interest,Rainer Werner Fassbinder,NaN,NaN,NaN,NaN,NaN,57 minutes,NaN
880,1140,Johnny Knoxville and his crew of fun-loving ma...,R,Comedy|Documentary,Jeff Tremaine,Jeff Tremaine|Johnny Knoxville,"Oct 25, 2002","Mar 25, 2003",$,"64,209,101",84 minutes,Paramount Pictures
881,1141,"While traveling in the Midwest, two aging fur-...",R,Action and Adventure|Western,Richard Lang,NaN,NaN,NaN,NaN,NaN,102 minutes,NaN
898,1161,Screenwriter Nimrod Antal makes an impressive ...,R,Action and Adventure|Art House and Internation...,NaN,NaN,"Apr 1, 2005","Aug 30, 2005",$,"116,783",105 minutes,ThinkFilm Inc.
899,1162,SNL alumni Tina Fey steps into the well worn s...,R,Comedy|Drama,Glenn Ficarra|John Requa,Robert Carlock,"Mar 4, 2016","Jun 28, 2016",$,"18,356,529",111 minutes,Paramount Pictures
900,1163,"Based on Peter Turner's memoir, the film follo...",R,Art House and International|Drama|Romance,Paul McGuigan,Matt Greenhalgh,"Dec 29, 2017","Apr 24, 2018",NaN,NaN,105 minutes,Sony Pictures Classics
901,1164,"""Mary Queen of Scots"" explores the turbulent l...",R,Drama,Josie Rourke,Beau Willimon,NaN,NaN,NaN,NaN,112 minutes,Focus Features
903,1167,"In this wickedly funny screwball satire, Mel C...",R,Comedy,NaN,NaN,"Mar 22, 1996","Jun 15, 1999",NaN,NaN,93 minutes,Miramax Films
906,1170,A violent and psychotic rapist is released fro...,R,Art House and International|Comedy|Drama,Tony Bill,John Patrick Shanley,"Jan 1, 1987","Sep 18, 2007",NaN,NaN,92 minutes,NaN
909,1173,"In this film, set in the 15th century, Anatoly...",R,Art House and International|Drama,Andrei Tarkovsky,Andrey Konchalovskiy|Andrei Tarkovsky,"Jan 1, 1973","Feb 2, 1999",NaN,NaN,205 minutes,NaN
910,1175,This Chinese saga chronicles 30 years in the l...,R,Art House and International|Drama,Yimou Zhang,Lu Wei|Yu Hua,"Dec 16, 1994","Jul 1, 2003",NaN,NaN,125 minutes,NaN
912,1179,Loosely based on former policeman Joseph Wamba...,R,Comedy|Drama,Robert Aldrich,Christopher Knopf|Joseph Wambaugh,NaN,NaN,NaN,NaN,119 minutes,NaN
915,1183,After making a striking directorial debut with...,R,Comedy|Drama|Romance,Sofia Coppola,Sofia Coppola,"Sep 26, 2003","Feb 3, 2004",$,"44,566,004",102 minutes,Focus Features
917,1186,In the time just preceding Castro's takeover o...,R,Drama|Romance,Sydney Pollack,David Rayfiel|Judith Rascoe|Paul Schrader,"Jan 1, 1990","Nov 17, 1998",NaN,NaN,144 minutes,NaN
925,1197,1967-1976 As one of history's greatest fashion...,R,Art House and International|Drama|Special Inte...,Bertrand Bonello,Bertrand Bonello|Thomas Bidegain,"May 8, 2015","Sep 22, 2015",NaN,NaN,135 minutes,Sony Pictures Classics
927,1200,In 1881 a younger member of the notorious Jame...,R,Action and Adventure|Drama|Western,Andrew Dominik,Andrew Dominik,"Oct 5, 2007","Feb 5, 2008",$,"3,900,000",159 minutes,Warner Bros. Pictures
930,1207,"Directed by Nicholas Racz, The Burial Society ...",R,Drama|Mystery and Suspense,Nicholas Racz,NaN,"Jan 11, 2003","Aug 29, 2006",NaN,NaN,95 minutes,Regent Releasing
935,1214,"Sissy Spacek, Troy Garity, and music icon Dave...",R,Drama|Mystery and Suspense,Perry Moore|Hunter Hill,Hunter Hill|Perry Moore,"Nov 7, 2008","Mar 3, 2009",NaN,NaN,93 minutes,Screen Media Films
938,1217,"For decades, the South American metropolis of ...",R,Action and Adventure|Drama,NaN,NaN,"Aug 17, 2007","Oct 28, 2008",NaN,NaN,114 minutes,IFC Films
939,1218,A young woman searches for love in New York Ci...,R,Comedy|Romance,Christian Ditter,Abby Kohn|Marc Silverstein|Dana Fox,"Feb 12, 2016","May 24, 2016",NaN,NaN,110 minutes,Warner Bros. Pictures
942,1221,"Jim Jarmusch takes his quirky, uniquely modern...",R,Drama|Science Fiction and Fantasy|Western,Jim Jarmusch,Jim Jarmusch,"May 26, 1995","Jul 3, 2001",NaN,NaN,121 minutes,NaN
943,1222,American independent filmmaker Paul F. Ryan ma...,R,Drama,NaN,NaN,"Sep 5, 2003","Oct 14, 2003",NaN,NaN,132 minutes,DEJ Productions
947,1226,Kiefer Sutherland won a Genie Award for his pe...,R,Drama,NaN,NaN,NaN,NaN,NaN,NaN,107 minutes,NaN
951,1231,"THE ROVER, David Michod's highly anticipated f...",R,Mystery and Suspense|Science Fiction and Fanta...,NaN,NaN,"Jun 13, 2014","Sep 23, 2014",$,"709,133",103 minutes,A24 Films
953,1234,Guy Maddin and George Toles wrote this bizarre...,R,Comedy|Drama|Special Interest,Guy Maddin,Guy Maddin,"Aug 27, 1993","Mar 24, 2009",NaN,NaN,100 minutes,NaN
955,1236,"AMERICAN PASTORAL follows Seymour ""Swede"" Levo...",R,Drama,Ewan McGregor,John Romano,"Oct 21, 2016","Feb 7, 2017",$,"541,457",126 minutes,Lakeshore Entertainment
967,1256,Marc Forster's psychological thriller Stay sta...,R,Drama|Mystery and Suspense|Science Fiction and...,Marc Forster,David Benioff,"Oct 21, 2005","Mar 28, 2006",$,"3,349,167",99 minutes,20th Century Fox
968,1257,"Ribald, violent, surreal and satirical, Marqui...",R,Animation|Art House and International|Comedy|S...,Henri Xhonneux,Henri Xhonneux|Roland Topor,NaN,NaN,NaN,NaN,88 minutes,NaN
971,1261,"In the tradition of Fried Green Tomatoes, this...",R,Comedy|Drama,Herbert Ross,Don Roos,"Feb 3, 1995","Nov 6, 2001",NaN,NaN,115 minutes,NaN
973,1264,The Super centers on the mysterious disappeara...,R,Mystery and Suspense,Stephan Rick,NaN,"Oct 19, 2018","Dec 18, 2018",NaN,NaN,90 minutes,NaN
975,1266,"Slow-moving and dark, this Klute clone stars T...",R,Drama|Mystery and Suspense,Gordon Willis,NaN,NaN,NaN,NaN,NaN,96 minutes,NaN
977,1268,"After ten years of marriage, Jeff and Nealy La...",R,Comedy,Jacob Aaron Estes,Jacob Aaron Estes,"Nov 2, 2012","Apr 30, 2013",$,"63,595",91 minutes,The Weinstein Company
979,1271,"In 2003, respected filmmaker and screenwriter ...",R,Horror,Paul Schrader,NaN,"May 20, 2005","Oct 25, 2005",NaN,NaN,111 minutes,NaN
982,1274,Set during the 1950s in a small coastal Englis...,R,Comedy|Drama,Philip Goodhew,Philip Goodhew,"Sep 10, 1996","Feb 10, 1998",NaN,NaN,105 minutes,NaN
996,1289,"In this film, Susan Anspach, an American house...",R,Art House and International|Comedy|Drama,Dusan Makavejev,NaN,"Nov 8, 1981","Sep 11, 2001",NaN,NaN,98 minutes,NaN
997,1290,It has been two decades since master filmmaker...,R,Action and Adventure|Drama|Horror|Mystery and ...,NaN,NaN,"Jun 24, 2005","Oct 18, 2005",$,"20,433,940",92 minutes,Universal Pictures

In [71]:
movie_buddget.iloc[[568,572,590,599,603,613,636,639,646,650,668,706,738,752,763,816,900,
                   906,909,910,925]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
568,69,"Sep 28, 2018",Smallfoot,"$80,000,000","$83,240,103","$213,691,277"
572,73,"Aug 8, 1997",Conspiracy Theory,"$80,000,000","$76,118,990","$142,783,718"
590,91,"Dec 13, 1996",Mars Attacks!,"$80,000,000","$37,771,017","$101,371,017"
599,100,"Dec 18, 2009",Nine,"$80,000,000","$19,676,965","$53,508,858"
603,4,"Dec 25, 1997",The Postman,"$80,000,000","$17,650,704","$20,841,123"
613,14,"Oct 4, 2002",Red Dragon,"$78,000,000","$92,955,420","$206,455,420"
636,37,"Jun 27, 2008",Wanted,"$75,000,000","$134,508,551","$342,416,460"
639,40,"Jul 20, 2007",Hairspray,"$75,000,000","$118,871,849","$203,035,572"
646,47,"Feb 18, 2005",Constantine,"$75,000,000","$75,976,178","$221,594,911"
650,51,"Apr 16, 1999",Life,"$75,000,000","$64,062,587","$73,521,587"
668,69,"Jan 15, 1999",Virus,"$75,000,000","$14,010,690","$30,626,690"
706,7,"Dec 14, 2001",Vanilla Sky,"$70,000,000","$100,614,858","$202,726,605"
738,39,"Jan 16, 1998",Hard Rain,"$70,000,000","$19,870,567","$19,870,567"
752,53,"Jun 30, 2010",The Twilight Saga: Eclipse,"$68,000,000","$300,531,751","$706,102,828"
763,64,"Oct 10, 2008",Body of Lies,"$67,500,000","$39,394,666","$118,556,530"
816,17,"Dec 25, 2016",Live by Night,"$65,000,000","$10,378,555","$21,774,432"
900,1,"Nov 26, 1997",Alien: Resurrection,"$60,000,000","$47,795,018","$160,700,000"
906,7,"Jun 19, 2009",Year One,"$60,000,000","$43,337,279","$57,604,723"
909,10,"Feb 19, 2002",Reign of Fire,"$60,000,000","$43,061,982","$82,150,183"
910,11,"Nov 20, 2009",Planet 51,"$60,000,000","$42,194,060","$108,996,113"
925,26,"Aug 21, 2013",The Mortal Instruments: City of Bones,"$60,000,000","$31,165,421","$75,965,567"

In [73]:
# new names index for R
no5 = [568,572,590,599,603,613,636,639,646,650,668,706,738,752,763,816,900,
                   906,909,910,925]

Based on the indexes on the 'R' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was R-rated. The 24 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [33]:
# getting system PG name:need 35
names1=[]
for i in no1:
    names1.append(movie_buddget.movie[i])
names1[:8]

['AVP: Alien Vs. Predator',
 'The Legend of Hercules',
 'Elektra',
 'Daddy Day Care',
 'Beyond Borders',
 'Zero Dark Thirty',
 'Taken 2',
 'Journey to the Center of the Earth']

In [34]:
# aading names1, the names of the PG movies to the orignal 
for i in names1:
    name_movies.append(i)
len(name_movies)

63

In [35]:
# getting system NR name:need 26
names4=[]
for i in no3:
    names4.append(movie_buddget.movie[i])
names4[:9]

['Penguins of Madagascar',
 'Harry Potter and the Prisoner of Azkaban',
 'Harry Potter and the Deathly Hallows: Part I',
 'X-Men 2',
 'Sherlock Holmes: A Game of Shadows',
 "Charlie's Angels: Full Throttle",
 "Gulliver's Travels",
 'Live Free or Die Hard',
 'Wonder Park']

In [36]:
# aading names4, the names of the NR movies to the orignal 
for i in names4:
    name_movies.append(i)
len(name_movies)

90

In [37]:
#getting the index of the names to get other info from dataframe
index = []
for i in name_movies:
    index.append(list(movie_buddget[movie_buddget['movie']==i].index))
len(index)

90

In [38]:
#checking index to see integers that are not needed
index

[[12],
 [20],
 [30],
 [53],
 [73],
 [87],
 [95],
 [110],
 [116],
 [121],
 [130],
 [132],
 [138],
 [147],
 [152],
 [160],
 [162],
 [165],
 [168],
 [177],
 [181],
 [190],
 [195],
 [208],
 [218],
 [222],
 [233],
 [235],
 [259],
 [261],
 [264],
 [272],
 [286],
 [290],
 [294],
 [297, 484],
 [308],
 [316],
 [332],
 [389],
 [400],
 [404],
 [411],
 [412, 4775],
 [413],
 [437],
 [452],
 [461],
 [465],
 [466],
 [474],
 [485],
 [487],
 [710],
 [741],
 [811],
 [854],
 [949],
 [1065],
 [1253],
 [1258],
 [1309],
 [1485],
 [236],
 [238],
 [263],
 [265],
 [268],
 [290],
 [312],
 [320],
 [393],
 [415],
 [441],
 [456],
 [465],
 [469],
 [489],
 [491],
 [528],
 [551],
 [577],
 [591],
 [596],
 [608],
 [642],
 [656],
 [661],
 [673],
 [700]]

In [43]:
# Turning nested list to regular list
from funcy import flatten,isa
flat_list = flatten(index)

In [44]:
# converting list of list into int 
newflat_list = []
for i in flat_list:
    i=int(i)
    newflat_list.append(i)
len(newflat_list)

92

In [45]:
# removing integers that are not needed
newflat_list1 = []
for i in newflat_list:
    if i == 4775:continue
    if i == 484:continue
    
    else: newflat_list1.append(i)

In [46]:
len(newflat_list1)

90

Now that the names have been updated with the new indexes, we use it to get the rest of the key components from the original dataframe to add to the new dataframe.

In [47]:
# using the updated indexes to get the new and old ratings
rating = []
for x in newflat_list1:
    rating.append(ratings.averagerating[x])
len(rating)

90

In [48]:
#using the updated indexes to get thenew and old system ratings
system_rating = []
for x in newflat_list1:
    system_rating.append(movie_info.rating[x])
len(system_rating)

90

In [49]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'NR': 42, 'G': 5, 'R': 19, 'PG-13': 7, 'PG': 17})

In [50]:
#using the updated indexes to get the new and old product budgets
product_budget = []
for x in newflat_list1:
    product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

90

In [51]:
#using the updated indexes to get the new and old domestic gross
domestic_gross = []
for x in newflat_list1:
    domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

90

In [52]:
# using the updated indexes to get the new and old worldwide gross
worldwide_gross = []
for x in newflat_list1:
    worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

90

In [56]:
# getting system PG-13 name:need 24
names2=[]
for i in name_mojo1[:-3]:
    names2.append(i)
len(names2)

35

In [57]:
# getting system G name:need 37
names3=[]
for i in name_mojo3:
    names3.append(i)
len(names3)

37

In [58]:
# getting system R name 
names=[]
for i in name_mojo4[:-1]:
    names.append(i)
len(names)

23

In [59]:
# getting system PG name:need 25
names1=[]
for i in name_mojo2[:-10]:
    names1.append(i)
len(names1)

25

In [60]:
# add new 'PG-13' names to the original
for i in names2:
    name_movies.append(i)
len(name_movies)

125

In [61]:
# add new 'PG-13' worldwide gross to the original
for i in worldwide_gross_mojo1[:-3]:
    worldwide_gross.append(i)
len(worldwide_gross)

125

In [62]:
# add new 'PG-13' domestic gross to the original
for i in domestic_gross_mojo1[:-3]:
    domestic_gross.append(i)
len(domestic_gross)

125

In [63]:
# add new 'PG-13' product budget to the original
for i in product_budget_mojo1[:-3]:
    product_budget.append(i)
len(product_budget)

125

In [64]:
pg13 = ['PG-13']*35
for i in pg13:
    system_rating.append(i)
len(system_rating)

125

In [65]:
# add new 'G' names to the original
for i in names3:
    name_movies.append(i)
len(name_movies)

162

In [66]:
# add new 'G' worldwide gross to the original
for i in worldwide_gross_mojo3:
    worldwide_gross.append(i)
len(worldwide_gross)

162

In [67]:
# add new 'G' domestic gross to the original
for i in domestic_gross_mojo3:
    domestic_gross.append(i)
len(domestic_gross)

162

In [68]:
# add new 'G' product budget to the original
for i in product_budget_mojo3:
    product_budget.append(i)
len(product_budget)

162

In [69]:
pg13 = ['G']*37
for i in pg13:
    system_rating.append(i)
len(system_rating)

162

In [70]:
# add new 'R' names to the original
for i in names:
    name_movies.append(i)
len(name_movies)

185

In [71]:
# add new 'R' worldwide gross to the original
for i in worldwide_gross_mojo4[:-1]:
    worldwide_gross.append(i)
len(worldwide_gross)

185

In [72]:
# add new 'R' domestic gross to the original
for i in domestic_gross_mojo4[:-1]:
    domestic_gross.append(i)
len(domestic_gross)

185

In [73]:
# add new 'R' product budget to the original
for i in product_budget_mojo4[:-1]:
    product_budget.append(i)
len(product_budget)

185

In [74]:
r1 = 'R'*23
r1= list(r1)
for i in r1:
    system_rating.append(i)
len(system_rating)

185

In [75]:
# add new 'PG' names to the original
for i in names1:
    name_movies.append(i)
len(name_movies)

210

In [76]:
# add new 'PG' worldwide gross to the original
for i in worldwide_gross_mojo2[:-10]:
    worldwide_gross.append(i)
len(worldwide_gross)

210

In [77]:
# add new 'PG' domestic gross to the original
for i in domestic_gross_mojo2[:-10]:
    domestic_gross.append(i)
len(domestic_gross)

210

In [78]:
# add new 'PG' product budget to the original
for i in product_budget_mojo2[:-10]:
    product_budget.append(i)
len(product_budget)

210

In [79]:
pg1 = ['PG']*25
for i in pg1:
    system_rating.append(i)
len(system_rating)

210

In [80]:
# adding rating from mojo to the original
for i in rating_mojo1[:-3]:
    rating.append(i)
len(rating)

125

In [81]:
# adding rating from mojo to the original
for i in rating_mojo3:
    rating.append(i)
len(rating)

162

In [82]:
# adding rating from mojo to the original
for i in rating_mojo4[:-1]:
    rating.append(i)
len(rating)

185

In [83]:
# adding rating from mojo to the original
for i in rating_mojo2[:-10]:
    rating.append(i)
len(rating)

210

In [84]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'NR': 42, 'G': 42, 'R': 42, 'PG-13': 42, 'PG': 42})

Now that all the new indexs has been idnetified they will be added to the new dataframe needed to create the five interactive graphs.

All the information have been gathered, the script below uses it to create a new and updated dataframe.

In [85]:
all_actionadventure_info = pd.DataFrame({'Name':name_movies,'System_ratings':system_rating,'Rating':rating,'Worlwide_gross':worldwide_gross,
                               'Domestic_gross':domestic_gross,'Product_budget':product_budget})
all_actionadventure_info1=all_actionadventure_info.dropna()
all_actionadventure_info1 = all_actionadventure_info[all_actionadventure_info.Name !='Moonfall']

Now that the dataframe has been updated, Worldwide Gross, Product Budget and Domestic Gross has to be converted from string to int.

In [86]:
# turning Worldwide gross into int
storage1 = []
storage2 = []
total_gross=[]
for i in  all_actionadventure_info1.dropna().Worlwide_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    total_gross.append(i)
len(total_gross)

210

In [87]:
# turning Produt budget  into int
storage1 = []
storage2 = []
budget=[]
for i in  all_actionadventure_info1.dropna().Product_budget:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    budget.append(i)
len(budget)

210

In [88]:
# turning Domestic gross into int
storage1 = []
storage2 = []
Doomestic_gross=[]
for i in  all_actionadventure_info1.dropna().Domestic_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    Doomestic_gross.append(i)
len(Doomestic_gross)

210

In [89]:
#drop all the NA from the dataframe
all_actionadventure_info1 = all_actionadventure_info1.dropna()


#adding all the string componnets that have been converted to dataframe
all_actionadventure_info1['Buget']=budget
all_actionadventure_info1['Total_gross']=total_gross
all_actionadventure_info1['Domestic_total']=Doomestic_gross
all_actionadventure_info1[190:]

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total
190,Hugo (film),PG,7.5,"$185,770,160","$73,864,507","$156,000,000",156000000,185770160,73864507
191,My Girl,PG,6.9,"$236,509,222","$115,811,254","$29,201,121",29201121,236509222,115811254
192,Inkheart,PG,6.1,"$62,803,180","$17,303,424","$60,000,000",60000000,62803180,17303424
193,Enchanted,PG,7.0,"$439,485,533","$164,967,635","$109,714,023",109714023,439485533,164967635
194,Hook (film),PG,6.8,"$585,774,488","$585,774,488","$136,271,898",136271898,585774488,585774488
195,Bridge to Terabithia,PG,7.1,"$177,590,944","$106,193,419","$25,815,064",25815064,177590944,106193419
196,The Goonies,PG,7.8,"$306,731,016","$156,828,600","$46,999,107",46999107,306731016,156828600
197,"The Chronicles of Narnia: The Lion, the Witch ...",PG,6.9,"$1,019,722,175","$399,280,713","$246,375,827",246375827,1019722175,399280713
198,Night at the Museum,PG,6.4,"$574,480,841","$250,863,268","$110,000,000",110000000,574480841,250863268
199,The Parent Trap,PG,6.5,"$741,603,630","$107,077,773","$25,030,049",25030049,741603630,107077773
200,National Treasure,PG,6.9,"$148,740,695","$355,207,271","$161,484,190",161484190,148740695,355207271
201,The Princess Bride,PG,8.0,"$72,738,988","$37,715,692","$37,715,692",37715692,72738988,37715692
202,National Treasure: Book of Secrets,PG,6.5,"$592,768,412","$167,797,918","$167,797,918",167797918,592768412,167797918
203,Up,PG,8.9,"$735,099,082","$72,738,988","$175,000,000",175000000,735099082,72738988
204,The Witches 1990,PG,6.9,"$31,728,982","$283,919,389","$22,721,760",22721760,31728982,283919389
205,E.T. the Extra-Terrestrial,PG,7.8,"$2,197,125,900","$293,004,000","$29,095,500",29095500,2197125900,293004000
206,Nanny McPhee,PG,6.5,"$168,735,696","$21,400,909","$34,218,86",3421886,168735696,21400909
207,Big (film),PG,7.3,"$342,337,714","$995,334,989","$40,628,526",40628526,342337714,995334989
208,Matilda,PG,6.9,"$56,164,340","$64,528,717","$61,088,364",61088364,56164340,64528717
209,Finding Neverland,PG,7.6,"$164,864,089","$260,084,100","$35,332,881",35332881,164864089,260084100

In [90]:
# getting profit
profit = []
for x,y in enumerate(total_gross):
    profit.append(y-budget[x])
len(profit)

210

In [91]:
all_actionadventure_info1['Profit']=profit

In [92]:
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit
0,The Lone Ranger,NR,7.0,"$260,002,115","$89,302,115","$275,000,000",275000000,260002115,89302115,-14997885
1,The Hobbit: The Desolation of Smaug,NR,7.2,"$960,366,855","$258,366,855","$250,000,000",250000000,960366855,258366855,710366855
2,The Amazing Spider-Man,G,5.4,"$757,890,267","$262,030,663","$220,000,000",220000000,757890267,262030663,537890267
3,Oz the Great and Powerful,R,6.1,"$490,359,051","$234,770,996","$200,000,000",200000000,490359051,234770996,290359051
4,Iron Man,NR,8.6,"$585,171,547","$318,604,126","$186,000,000",186000000,585171547,318604126,399171547
...,...,...,...,...,...,...,...,...,...,...
205,E.T. the Extra-Terrestrial,PG,7.8,"$2,197,125,900","$293,004,000","$29,095,500",29095500,2197125900,293004000,2168030400
206,Nanny McPhee,PG,6.5,"$168,735,696","$21,400,909","$34,218,86",3421886,168735696,21400909,165313810
207,Big (film),PG,7.3,"$342,337,714","$995,334,989","$40,628,526",40628526,342337714,995334989,301709188
208,Matilda,PG,6.9,"$56,164,340","$64,528,717","$61,088,364",61088364,56164340,64528717,-4924024
209,Finding Neverland,PG,7.6,"$164,864,089","$260,084,100","$35,332,881",35332881,164864089,260084100,129531208

In [93]:
# Creating Box office column
# dividing total gross by the avg price of tickets, to get an estimsted number of tickes sold
no_tickets = []
for i in all_actionadventure_info1.Total_gross:
    no_tickets.append(round(i/13)) 
no_tickets[:10]

[20000163,
 73874373,
 58299251,
 37719927,
 45013196,
 26838617,
 86389350,
 10740795,
 54664967,
 26538802]

In [94]:
# converting integer of no. of tickets into string
tickets_string = []
for i in no_tickets:
    tickets_string.append("{:,.0f}".format(i))
len(tickets_string)

210

In [95]:
# converting integer of profit to currency
currency = []
for i in all_actionadventure_info1.Profit:
    currency.append("${:,.0f}".format(i))
len(currency)

210

In [96]:
all_actionadventure_info1['No.Tickets']=tickets_string
all_actionadventure_info1['Profit$']= currency
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit,No.Tickets,Profit$
0,The Lone Ranger,NR,7.0,"$260,002,115","$89,302,115","$275,000,000",275000000,260002115,89302115,-14997885,"20,000,163","$-14,997,885"
1,The Hobbit: The Desolation of Smaug,NR,7.2,"$960,366,855","$258,366,855","$250,000,000",250000000,960366855,258366855,710366855,"73,874,373","$710,366,855"
2,The Amazing Spider-Man,G,5.4,"$757,890,267","$262,030,663","$220,000,000",220000000,757890267,262030663,537890267,"58,299,251","$537,890,267"
3,Oz the Great and Powerful,R,6.1,"$490,359,051","$234,770,996","$200,000,000",200000000,490359051,234770996,290359051,"37,719,927","$290,359,051"
4,Iron Man,NR,8.6,"$585,171,547","$318,604,126","$186,000,000",186000000,585171547,318604126,399171547,"45,013,196","$399,171,547"
...,...,...,...,...,...,...,...,...,...,...,...,...
205,E.T. the Extra-Terrestrial,PG,7.8,"$2,197,125,900","$293,004,000","$29,095,500",29095500,2197125900,293004000,2168030400,"169,009,685","$2,168,030,400"
206,Nanny McPhee,PG,6.5,"$168,735,696","$21,400,909","$34,218,86",3421886,168735696,21400909,165313810,"12,979,669","$165,313,810"
207,Big (film),PG,7.3,"$342,337,714","$995,334,989","$40,628,526",40628526,342337714,995334989,301709188,"26,333,670","$301,709,188"
208,Matilda,PG,6.9,"$56,164,340","$64,528,717","$61,088,364",61088364,56164340,64528717,-4924024,"4,320,334","$-4,924,024"
209,Finding Neverland,PG,7.6,"$164,864,089","$260,084,100","$35,332,881",35332881,164864089,260084100,129531208,"12,681,853","$129,531,208"

After the dataframe has been updated, bokeh is being installed.

In [97]:
from bokeh.layouts import gridplot,row
from bokeh.plotting import figure,output_file,ColumnDataSource
from bokeh.io import push_notebook,show,output_notebook
from bokeh.models import NumeralTickFormatter
output_notebook()

Bokeh is successfully installed, now the key componets need to be creted for each system rating group to make the graphs.

A reminder of the componets;
 - Cost
 - Proft
 - Name
 - Profit Percntage by Cost
 - Type of System Rating

In [98]:
# index of all 'R' system ratings
index_r = []
for i,x in enumerate(system_rating):
    if x == 'R':index_r.append(i)

In [99]:
# getiing the profit for all 'R' system rating
r_profit = []
for i in index_r:
    r_profit.append(all_actionadventure_info1.Profit[i])
len(r_profit)

42

In [100]:
# getting the cost for 'R' system rating
cost1 = []
for i in index_r:
    cost1.append(all_actionadventure_info1.Product_budget[i])
len(cost1)

42

In [101]:
# getiing the name for all 'R' system rating
r_name = []
for i in index_r:
    r_name.append(all_actionadventure_info1.Name[i])
len(r_name)

42

In [102]:
# getiing the $profit for all 'R' system rating
r_dollar = []
for i in index_r:
    r_dollar.append(all_actionadventure_info1['Profit$'][i])
len(r_dollar)

42

In [103]:
# getiing the system rating for all 'R' system rating
r_sratings = []
for i in index_r:
    r_sratings.append(all_actionadventure_info1.System_ratings[i])
len(r_sratings)

42

In [104]:
# getting percentage profit for all 'R' system rating
percent_profit = []
for i in index_r:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit.append(round(i,0))
len(percent_profit)

42

In [105]:
# turning float of percentage of profit into int for 'R' system rating
pp = []
for i in percent_profit:
    i = int(i)
    pp.append(i)
len(pp)

42

In [106]:
# converting integer to percentage for 'R' system rating
percentage_profit = []
for i in pp:
    percentage_profit.append("{:}%".format(i))
len(percentage_profit)

42

In [107]:
# index of all 'G' system ratings
index_g = []
for i,x in enumerate(system_rating):
    if x == 'G':index_g.append(i)

In [108]:
# getiing the profit for all 'G' system rating
g_profit = []
for i in index_g:
    g_profit.append(all_actionadventure_info1.Profit[i])
len(g_profit)

42

In [109]:
# getting the cost for 'G' system rating
cost2 = []
for i in index_g:
    cost2.append(all_actionadventure_info1.Product_budget[i])
len(cost2)

42

In [110]:
# getiing the name for all 'G' system rating
g_name = []
for i in index_g:
    g_name.append(all_actionadventure_info1.Name[i])
len(g_name)

42

In [111]:
# getiing the $profit for all 'G' system rating
g_dollar = []
for i in index_g:
    g_dollar.append(all_actionadventure_info1['Profit$'][i])
len(g_dollar)

42

In [112]:
# getiing the system rating for all 'G' system rating
g_sratings = []
for i in index_g:
    g_sratings.append(all_actionadventure_info1.System_ratings[i])
len(g_sratings)

42

In [113]:
# getting percentage profit for all 'G' system rating
percent_profit1 = []
for i in index_g:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit1.append(round(i,0))
len(percent_profit1)

42

In [114]:
# turning float of percentage of profit into int for 'G' system rating
pp1= []
for i in percent_profit1:
    i = int(i)
    pp1.append(i)
len(pp1)

42

In [115]:
# converting integer to percentage for 'G' system rating
percentage_profit1 = []
for i in pp1:
    percentage_profit1.append("{:}%".format(i))
len(percentage_profit1)

42

In [116]:
# index of all 'PG' system ratings
index_pg = []
for i,x in enumerate(system_rating):
    if x == 'PG':index_pg.append(i)

In [117]:
# getiing the profit for all 'PG' system rating
pg_profit = []
for i in index_pg:
    pg_profit.append(all_actionadventure_info1.Profit[i])
len(pg_profit)

42

In [118]:
# getting the cost for 'PG' system rating
cost3 = []
for i in index_pg:
    cost3.append(all_actionadventure_info1.Product_budget[i])
len(cost3)

42

In [119]:
# getiing the name for all 'PG' system rating
pg_name = []
for i in index_pg:
    pg_name.append(all_actionadventure_info1.Name[i])
len(pg_name)

42

In [120]:
# getiing the $profit for all 'PG' system rating
pg_dollar = []
for i in index_pg:
    pg_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg_dollar)

42

In [121]:
# getiing the system rating for all 'PG' system rating
pg_sratings = []
for i in index_pg:
    pg_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg_sratings)

42

In [122]:
# getting percentage profit for all 'PG' system rating
percent_profit2 = []
for i in index_pg:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit2.append(round(i,0))
len(percent_profit2)

42

In [123]:
# turning float of percentage of profit into int for 'PG' system rating
pp2= []
for i in percent_profit2:
    i = int(i)
    pp2.append(i)
len(pp2)

42

In [124]:
# converting integer to percentage for 'PG' system rating
percentage_profit2= []
for i in pp2:
    percentage_profit2.append("{:}%".format(i))
len(percentage_profit2)

42

In [125]:
# index of all 'PG-13' system ratings
index_pg13 = []
for i,x in enumerate(system_rating):
    if x == 'PG-13':index_pg13.append(i)

In [126]:
# getiing the profit for all 'PG-13' system rating
pg13_profit = []
for i in index_pg13:
    pg13_profit.append(all_actionadventure_info1.Profit[i])
len(pg13_profit)

42

In [127]:
# getiing the name for all 'PG-13' system rating
pg13_name = []
for i in index_pg13:
    pg13_name.append(all_actionadventure_info1.Name[i])
len(pg13_name)

42

In [128]:
# getting the cost for 'PG-13' system rating
cost4 = []
for i in index_pg13:
    cost4.append(all_actionadventure_info1.Product_budget[i])
len(cost4)

42

In [129]:
# getiing the $profit for all 'PG-13' system rating
pg13_dollar = []
for i in index_pg13:
    pg13_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg13_dollar)

42

In [130]:
# getiing the system rating for all 'PG-13' system rating
pg13_sratings = []
for i in index_pg13:
    pg13_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg13_sratings)

42

In [131]:
# getting percentage profit for all 'PG-13' system rating
percent_profit3 = []
for i in index_pg13:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit3.append(round(i,0))
len(percent_profit3)

42

In [132]:
# turning float of percentage of profit into int
pp3= []
for i in percent_profit3:
    i = int(i)
    pp3.append(i)
len(pp3)

42

In [133]:
# converting integer to percentage
percentage_profit3= []
for i in pp3:
    percentage_profit3.append("{:}%".format(i))
len(percentage_profit3)

42

In [134]:
# index of all 'NR' system ratings
index_NR = []
for i,x in enumerate(system_rating):
    if x == 'NR':index_NR.append(i)

In [135]:
# getiing the profit for all 'NR' system rating
NR_profit = []
for i in index_NR:
    NR_profit.append(all_actionadventure_info1.Profit[i])
len(NR_profit)

42

In [136]:
# getiing the name for all 'NR' system rating
nr_name = []
for i in index_NR:
    nr_name.append(all_actionadventure_info1.Name[i])
len(nr_name)

42

In [137]:
# getting the cost for 'NR' system rating
cost5 = []
for i in index_NR:
    cost5.append(all_actionadventure_info1.Product_budget[i])
len(cost5)

42

In [138]:
# getiing the $profit for all 'NR' system rating
nr_dollar = []
for i in index_NR:
    nr_dollar.append(all_actionadventure_info1['Profit$'][i])
len(nr_dollar)

42

In [139]:
# getiing the system rating for all 'NR' system rating
nr_sratings = []
for i in index_NR:
    nr_sratings.append(all_actionadventure_info1.System_ratings[i])
len(nr_sratings)

42

In [140]:
# getting percentage profit for all 'NR' system rating
percent_profit4 = []
for i in index_NR:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit4.append(round(i,0))
len(percent_profit4)

42

In [141]:
# turning float of percentage of profit into int for 'NR' system rating
pp4= []
for i in percent_profit4:
    i = int(i)
    pp4.append(i)
len(pp4)

42

In [142]:
# converting integer to percentage for 'NR' system rating
percentage_profit4= []
for i in pp4:
    percentage_profit4.append("{:}%".format(i))
len(percentage_profit4)

42

In [146]:
rangee = list(range(42)) # x-axis range
# allows the garph to hover over the piont to show all information about the pionts  
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,box_select,hover"

# Graph 1
source = ColumnDataSource(data=dict(
    x = rangee, # x-axis
    y = r_profit,# y-axis
    name=r_name, # name of movie
    profit=r_dollar,# profit in currency($)
    system_rating=r_sratings ,# system rating of movie
    percent_profit=percentage_profit,# profit percentage based on cost
    cost1=cost1))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name"),# the name
    ("Cost","@cost1"),# the cost
    ("Profit","@profit"),# the profit
    ("(System-Rating)","@system_rating"),# the system rating
    ("(Profit-Percentage)","@percent_profit")]# the profit percentage
p3 = figure(title='Profit.Drama.System Rating R',tools=TOOLS,plot_height=300,
           plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p3.left[0].formatter.use_scientific=False 
# makes the digits more visible by turning it into millions on the y-axis
p3.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
p3.circle('x','y',color='#e74be7',width=3,source=source)
p3.line('x','y',color="#e74be7",# the style and color of the graph
        line_dash='dashed',line_width=2,source=source)

# Graph 2
source4 = ColumnDataSource(data=dict(
     o=rangee,# x-axis
     e=g_profit,# y-axis
     name1=g_name,# name of movies
     profit1=g_dollar,# profit of movies in curreny($)
     system_rating1=g_sratings,# system rating of movie
     percent_profit1=percentage_profit1,# profit percentage based on cost
     cost2=cost2))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name1"),# the name
    ("Cost","@cost2"),# the cost
    ("Profit","@profit1"),# the profit in dollars
    ("(System-Rating)","@system_rating1"),# the system rating
    ("(Profit-Percentage)","@percent_profit1")]# the profit percentage
p4 = figure(title='Profit.Drama.System Rating G',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p4.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p4.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
# the style and color of the graph
p4.circle(x='o',y='e',color='#ed78ed',width=3,source=source4)
p4.line(x='o',y='e',color='#ed78ed',source=source4)
 
# Graph 3
source1 = ColumnDataSource(data=dict(
       p=rangee,# x-axis
       q=pg_profit,# y-axis
       name2=pg_name,# name of movies
       profit2=pg_dollar,# profit of movies in currency ($)
       system_rating2=pg_sratings,# system rating of moives
       percent_profit2=percentage_profit2,# profit percnetage based on cost
       cost3=cost3))# cost of movies
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name2"),# the name 
    ("Cost","@cost3"),# the cost
    ("Profit","@profit2"),# the profit the dollars
    ("(System-Rating)","@system_rating2"),# the system rating
    ("(Profit-Percentage)","@percent_profit2")]# the profit percentage 
p5 = figure(title='Profit.Drama.System Rating PG',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p5.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p5.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of graph
p5.square(x='p',y='q',line_color='#ef4be7',fill_color=None,source=source1)
p5.line(x='p',y='q',line_color='#ef4be7',source=source1)

# Graph 4
source2 = ColumnDataSource(data=dict(
       r=rangee,# x-axis
       t=pg13_profit,# y-axis
       name3=pg13_name,# name of movies
       profit3=pg13_dollar,# profit of movies to currency ($)
       system_rating3=pg13_sratings,# system rating of movies
       percent_profit3=percentage_profit3,# profit percentage based on cost
       cost4=cost4))# cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name3"),# the name
    ("Cost","@cost4"),# the cost
    ("Profit","@profit3"),# the profit in dollars
    ("(System-Rating)","@system_rating3"),# the system rating
    ("(Profit-Percentage)","@percent_profit3")]# the profit percentage
p6 = figure(title='Profit.Drama.System Rating PG-13',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
#takes away the scientific notation off the y-axis
p6.left[0].formatter.use_scientific=False
# makes the digits more visible ny turning it into millions on the y-axis
p6.yaxis[0].formatter=NumeralTickFormatter(format='$0.a')
# the style and color of the graph
p6.triangle(x='r',y='t',color='#ff00ff',width=2,source=source2)
p6.line(x='r',y='t',color='#ff00ff',width=2,source=source2)

# Graph 5
source3 = ColumnDataSource(data=dict(
        l=rangee,# x-axis
        i=NR_profit,# y-axis
        name4=nr_name,# name of movies
        profit4=nr_dollar,# profit of movies to currency ($)
        system_rating4=nr_sratings,# system rating of movies
        percent_profit4=percentage_profit4,# profit percentage based on cost
        cost5=cost5))#cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name4"),# the name
    ("Cost","@cost5"),# the cost
    ("Profit","@profit4"),# the profit in dollars
    ("(System-Rating)","@system_rating4"),# the system rating
    ("(Profit-Percentage)","@percent_profit4")]# the profit percentage
p7 = figure(title='Profit.Drama.System Rating NR',tools=TOOLS,
            plot_height=300,plot_width=300,tooltips=TOOLTIPS)
#takes away the scientiifc notation off the y-axis
p7.left[0].formatter.use_scientific=False
#makes the digits more visible by turning it into millions  on the y-axis
p7.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of the graph
p7.circle(x='l',y='i',color='#800080',fill_color=None,width=2,source=source3)
p7.line(x='l',y='i',color='#800080',width=2,source=source3)

output_file("toolbar.thml")
show(row(p3,p4,p5,p6,p7))# this puts the graphs side by side

# Blueprint: Gross Profit Margin Percentage

This is the blueprint for creating the second visualiztion Gross Profit Margin Percentage, altair will be used to create this graph.

__Blueprint__:
 - 1. Understanding the dataframe format used to create this data visualiztion helps make the process easier, these are the key componets that make up the dataframe used for this graph.
   
    - The data frame that altair used to create this graph consist of four colunms;
     
       - Yield: This colunm is the only colunm that shows any type of informations that is in numbers 
       - Variety: This colunm is the only column that contains category or groupings among the other pionts in the dataframe
       - Year: This colunm is based on datasets that contains timeframes
       - Site: This is a colunm that pinpionts differiantion among the rest of the data pionts
       
 
 - 2. Create five dataframes for five different graphs based on the documented format that is supplied by Altair. 
   
    - The dataframes will consist of these six columns;
      
       - Name: This colunm shows the names of each movie
       - Type: The concept of this graph portrays the profit made compared to the Revenue, the two main elements that reflects that is the Revenue and the Profit ergo the 'Type' column are made up of those two elements.
       - Yield: This colunm shows how much the 'Type' column is in int, this is used to plot the pionts in the graph.
       - Type Yield: This colunm shows the 'Yield' colunm in currency which is a string, this is mostly used for the tooltip to make it easier to understand how much the elements in the 'Type' column is in dollars.
       - System Rating: This shows the System Rating of each movie.
       - Gross Profit Margin: This colunm shows the gross profit margin in percentage.
       
 
 - 3. The style of this graph is a Becker's Barkey Trellis Plot which is found in Altair's Gallery. There are two pionts shaped as a ring in each panel, the first ring projects the Renvue and the other ring projects the Profit, this set up allows the perseption of how much of a fraction do each movie actually walk away with when compared to the Revenue allowing the Profit to be seen from a differnt angle. This could make the movie look more profitable or seem over-rated. Each ring when hovered shows the Name of the movie, the Type choosing beteween Profit or Revenue, the Type Yield which is the amount of the Type in dollars, the Gross Profit Margin Percentage and the System Rating. The closer the Profit is to the Revenue the more buoyant it is!

In [124]:
# understanding how the data frame is formatted
# this was the eact dataframe used in Altairs example
from vega_datasets import data
source = data.barley()
source

        yield           variety  year             site
0    27.00000         Manchuria  1931  University Farm
1    48.86667         Manchuria  1931           Waseca
2    27.43334         Manchuria  1931           Morris
3    39.93333         Manchuria  1931        Crookston
4    32.96667         Manchuria  1931     Grand Rapids
..        ...               ...   ...              ...
115  58.16667  Wisconsin No. 38  1932           Waseca
116  47.16667  Wisconsin No. 38  1932           Morris
117  35.90000  Wisconsin No. 38  1932        Crookston
118  20.66667  Wisconsin No. 38  1932     Grand Rapids
119  29.33333  Wisconsin No. 38  1932           Duluth

[120 rows x 4 columns]

These are the variables needed to create the columns for the first dataframe; new_name,new_systems, new_total_gross, new_worldwide_gross, new_profit, new_currency_profit, gross_profit_margin_percentage.

This is all the names of the movie for the rated-R movies.

In [125]:
new_name=[]
name = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x=='R':
            name.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name):
    new_name.append( x)
len(new_name)

42

This is all the domestic revenue of each movie in the rated-R catagory of movies.

In [126]:
new_total_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_total_gross.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross)

42

This is all the world wide revenue of each movie in the rated-R catagory of movies.

In [127]:
new_worldwide_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_worldwide_gross.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross)

42

This is all the profit in dollars of each movie in the rated-R catagory, this is particularly used for tooltip.

In [128]:
new_currency_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_currency_profit.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit)

42

This is all the profit in int of each mvoie in the rated-R catagory, this is particularly used for the Y and X axis.

In [129]:
new_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_profit.append(all_actionadventure_info1.Profit[i])
len(new_profit)

42

In [130]:
# a list of rated-'r'
new_systems = list('R'*42)
len(new_systems)

42

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [131]:
# Creating the gross profit margin percentage column
p_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        p_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p_rev)

42

In [132]:
# turning float of percentage of profit into int
pp_rev= []
for i in p_rev:
    i = int(i)
    pp_rev.append(round(i,0))
len(pp_rev)

42

In [133]:
# converting integer to percentage
gross_profit_margin_percentage= []
for i in pp_rev:
    gross_profit_margin_percentage.append("{:}%".format(i))
len(gross_profit_margin_percentage)

42

These are the variables needed to create the columns for the second dataframe; new_name1, new_systems1, new_total_gross1, new_worldwide_gross1, new_profit1, new_currency_profit1, gross_profit_margin_percentage1

This is all the names of the movie for the rated-PG movies.

In [134]:
new_name1=[]
name1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            name1.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name1):
    new_name1.append( x)
len(new_name1)

42

This is all the domestic revenue of each movie in the rated-PG catagory of movies.

In [135]:
new_total_gross1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_total_gross1.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross1)

42

This is all the world wide revenue of each movie in the rated-PG catagory of movies.

In [136]:
new_worldwide_gross1= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_worldwide_gross1.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross1)

42

This is all the profit in dollars of each movie in the rated-PG catagory, this is particularly used for tooltip.

In [137]:
new_currency_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_currency_profit1.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit1)

42

This is all the profit in int of each mvoie in the rated-PG catagory, this is particularly used for the Y and X axis.

In [138]:
new_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_profit1.append(all_actionadventure_info1.Profit[i])
len(new_profit1)

42

In [139]:
# list of rated-'PG'
new_systems1 = []
for i in list(range(0,42)):
    new_systems1.append('PG')

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [140]:
# Creating the profit rev percentage column
p1_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        p1_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p1_rev)

42

In [141]:
# turning float of percentage of profit into int
pp1_rev= []
for i in p1_rev:
    i = int(i)
    pp1_rev.append(round(i,0))
len(pp1_rev)

42

In [142]:
# converting integer to percentage
gross_profit_margin_percent1= []
for i in pp1_rev:
    gross_profit_margin_percent1.append("{:}%".format(i))
gross_profit_margin_percent1
len(gross_profit_margin_percent1)

42

These are the variables needed to create the columns for the third dataframe; new_name2, new_systems2, new_total_gross2, new_worldwide_gross2, new_profit2, new_currency_profit2, gross_profit_margin_percentage2

In [143]:
new_name2=[]
name2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            name2.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name2):
    new_name2.append(x)
len(new_name2)

42

In [144]:
new_systems2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_systems2.append(all_actionadventure_info1.Total_gross[i])
len(new_systems2)

42

In [145]:
new_worldwide_gross2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_worldwide_gross2.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross2)

42

In [146]:
new_currency_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_currency_profit2.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit2)

42

In [147]:
new_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_profit2.append(all_actionadventure_info1.Profit[i])
len(new_profit2)

42

In [148]:
new_systems2 = list('G'*42)
len(new_systems2)

42

In [149]:
# Creating the profit rev percentage column
p2_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        p2_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p2_rev)

42

In [150]:
# turning float of percentage of profit into int
pp2_rev= []
for i in p2_rev:
    i = int(i)
    pp2_rev.append(round(i,0))
len(pp2_rev)

42

In [151]:
# converting integer to percentage
gross_profit_margin_percentage2= []
for i in pp2_rev:
    gross_profit_margin_percentage2.append("{:}%".format(i))
len(gross_profit_margin_percentage2)

42

These are the variables needed to create the columns for the fourth dataframe; new_name3, new_systems3, new_total_gross3, new_worldwide_gross3, new_profit3, new_currency_profit3, gross_profit_margin_percentage3

In [152]:
new_name3=[]
name3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            name3.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name3):
    new_name3.append( x)
len(new_name3)

42

In [153]:
new_total_gross3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_total_gross3.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross3)

42

In [154]:
new_worldwide_gross3= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_worldwide_gross3.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross3)

42

In [155]:
new_currency_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_currency_profit3.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit3)

42

In [156]:
new_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_profit3.append(all_actionadventure_info1.Profit[i])
len(new_profit3)

42

In [157]:
new_systems3 = []
for i in list(range(0,42)):
    new_systems3.append('PG-13')

In [158]:
p3_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            p3_rev.append(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100)

len(p3_rev)

42

In [159]:
# turning float of percentage of profit into int
pp3_rev= []
for i in p3_rev:
    i = int(i)
    pp3_rev.append(round(i,0))
len(pp3_rev)

42

In [160]:
# converting integer to percentage
gross_profit_margin_percentage3= []
for i in pp3_rev:
    gross_profit_margin_percentage3.append("{:}%".format(i))
len(gross_profit_margin_percentage3)

42

These are the variables needed to create the columns for the fivth dataframe; new_name4, new_systems4, new_total_gross4, new_worldwide_gross4, new_profit4, new_currency_profit4, gross_profit_margin_percentage4

In [161]:
new_name4=[]
name4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            name4.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name4):
    new_name4.append(x)
new_name4
len(new_name4)

42

In [162]:
new_total_gross4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_total_gross4.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross4)

42

In [163]:
new_worldwide_gross4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_worldwide_gross4.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross4)

42

In [164]:
new_currency_profit4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_currency_profit4.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit4)

42

In [165]:
new_profit4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_profit4.append(all_actionadventure_info1.Profit[i])
len(new_profit4)

42

In [166]:
new_systems4 = []
for i in list(range(0,42)):
    new_systems4.append('NR')

In [167]:
p4_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            p4_rev.append(round(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100,
                                0))
len(p4_rev)

42

In [168]:
# turning float of percentage of profit into int
pp4_rev= []
for i in p4_rev:
    i = int(i)
    pp4_rev.append(round(i,2))
len(pp4_rev)

42

In [169]:
# converting integer to percentage
gross_profit_margin_percent4= []
for i in pp4_rev:
    gross_profit_margin_percent4.append("{:}%".format(i))
len(gross_profit_margin_percent4)

42

In [170]:
# list for type colunm
l = []
for i in list(range(0,42)):
    l.append('Revenue')
for i in list(range(0,42)):
    l.append('Profit')
len(l)

84

In [171]:
df5 = pd.DataFrame({'Name':new_name4*2,'Yield':new_total_gross4+new_profit4,'Type Yield':new_worldwide_gross4+new_currency_profit4,
                    'System Ratings':new_systems4*2,'Gross Profit Margin %':gross_profit_margin_percent4*2,'Type':l})

df4 = pd.DataFrame({'Name':new_name3*2,'Yield':new_total_gross3+new_profit3,'Type Yield':new_worldwide_gross3+new_currency_profit3,
                  'System Ratings':new_systems3*2,'Gross Profit Margin %':gross_profit_margin_percentage3*2,'Type':l})

df3 = pd.DataFrame({'Name':new_name2*2,'Yield':new_total_gross4+new_profit2,'Type Yield':new_worldwide_gross2+new_currency_profit2,
                    'System Ratings':new_systems2*2,'Gross Profit Margin %':gross_profit_margin_percentage2*2,'Type':l})

df2 = pd.DataFrame({'Name':new_name1*2,'Yield':new_total_gross1+new_profit1,'Type Yield':new_worldwide_gross1+new_currency_profit1,
                  'System Ratings':new_systems1*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

df1 = pd.DataFrame({'Name':new_name*2,'Yield':new_total_gross+new_profit,'Type Yield':new_worldwide_gross+new_currency_profit,
                    'System Ratings':new_systems*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

In [172]:
df1

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Oz the Great and Powerful,490359051,"$490,359,051",R,63%,Revenue
1,Dumbo,345004422,"$345,004,422",R,35%,Revenue
2,Wreck-It Ralph,496511521,"$496,511,521",R,81%,Revenue
3,The Hunger Games: Mockingjay - Part 2,648986787,"$648,986,787",R,28%,Revenue
4,The Chronicles of Narnia: The Voyage of the Da...,418186950,"$418,186,950",R,-11%,Revenue
...,...,...,...,...,...,...
79,Bridesmaids,255883523,"$255,883,523",R,98%,Profit
80,22 Jump Street,281333876,"$281,333,876",R,97%,Profit
81,The Passion of the Christ,581486736,"$581,486,736",R,88%,Profit
82,Slumdog Millionaire,363410113,"$363,410,113",R,-8%,Profit
83,Stealing Beauty,-8887831,"$-8,887,831",R,78%,Profit

In [173]:
df2

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Trolls,344150134,"$344,150,134",PG,63%,Revenue
1,Dante's Peak,178200000,"$178,200,000",PG,35%,Revenue
2,Night at the Museum,579446407,"$579,446,407",PG,81%,Revenue
3,Legend of the Guardians: The Owls of Ga'Hoole,139716717,"$139,716,717",PG,28%,Revenue
4,In the Heart of the Sea,89693309,"$89,693,309",PG,-11%,Revenue
...,...,...,...,...,...,...
79,E.T. the Extra-Terrestrial,2168030400,"$2,168,030,400",PG,98%,Profit
80,Nanny McPhee,165313810,"$165,313,810",PG,97%,Profit
81,Big (film),301709188,"$301,709,188",PG,88%,Profit
82,Matilda,-4924024,"$-4,924,024",PG,-8%,Profit
83,Finding Neverland,129531208,"$129,531,208",PG,78%,Profit

In [174]:
df3

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,The Amazing Spider-Man,260002115,"$757,890,267",G,70%,Revenue
1,Dunkirk,960366855,"$499,837,368",G,69%,Revenue
2,The Da Vinci Code,585171547,"$767,820,459",G,83%,Revenue
3,Stuart Little 2,348902025,"$166,000,000",G,27%,Revenue
4,The Adventures of Pluto Nash,139630336,"$7,094,995",G,-1309%,Revenue
...,...,...,...,...,...,...
79,Pinocchio,2219462581,"$2,219,462,581",G,97%,Profit
80,Bambi,4489260987,"$4,489,260,987",G,99%,Profit
81,Snow White and the Seven Dwarfs,7749324763,"$7,749,324,763",G,99%,Profit
82,Mulan 1998,346093329,"$346,093,329",G,70%,Profit
83,A Man for All Seasons,200679654,"$200,679,654",G,86%,Profit

In [175]:
df4

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Captain Marvel,1123061550,"$1,123,061,550",PG-13,84%,Revenue
1,Thor: The Dark World,644602516,"$644,602,516",PG-13,76%,Revenue
2,Ready Player One,579290136,"$579,290,136",PG-13,74%,Revenue
3,The Hunger Games: Mockingjay - Part 1,766575131,"$766,575,131",PG-13,83%,Revenue
4,Fantastic Four: Rise of the Silver Surfer,289480691,"$289,480,691",PG-13,58%,Revenue
...,...,...,...,...,...,...
79,Skyfall,908561013,"$908,561,013",PG-13,81%,Profit
80,Clueless,65155986,"$65,155,986",PG-13,65%,Profit
81,The Sixth Sense,992158414,"$992,158,414",PG-13,94%,Profit
82,Wonder Woman 1984,621847012,"$621,847,012",PG-13,75%,Profit
83,The Addams Family,179044905,"$179,044,905",PG-13,88%,Profit

In [176]:
df5

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,The Lone Ranger,260002115,"$260,002,115",NR,-6%,Revenue
1,The Hobbit: The Desolation of Smaug,960366855,"$960,366,855",NR,74%,Revenue
2,Iron Man,585171547,"$585,171,547",NR,68%,Revenue
3,The Legend of Tarzan,348902025,"$348,902,025",NR,48%,Revenue
4,King Arthur: Legend of the Sword,139630336,"$139,630,336",NR,-25%,Revenue
...,...,...,...,...,...,...
79,The Lion King,906914868,"$906,914,868",NR,92%,Profit
80,Christopher Robin,122504758,"$122,504,758",NR,62%,Profit
81,Lady in the Water,-2214831,"$-2,214,831",NR,-3%,Profit
82,Sucker Punch,14758389,"$14,758,389",NR,16%,Profit
83,Inglourious Basterds,246915264,"$246,915,264",NR,78%,Profit

In [179]:
# this is the first graph: this is the System R rating category
a=alt.Chart(df1).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis = alt.Axis(grid=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem PG rating category
b=alt.Chart(df2).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
        axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem G rating category
c=alt.Chart(df3).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the third graph: this is the Sytem PG-13 rating category
d=alt.Chart(df4).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,#take away the grid
       scale=alt.Scale(zero=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the fourth graph: this is the Sytem NR rating category
e=alt.Chart(df5).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,
       scale=alt.Scale(zero=False),# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

f= alt.vconcat(b,c,d,e).configure_view(strokeOpacity=0).configure_axisLeft(labelColor='purple')
f&a # combines the graphs together

alt.VConcatChart(...)

# Blueprint: Budget and Revenue of Movies

This js the blueprint for creating the third visualization Budget and Revenue of Movies, altair will be used to create this graph. 

__Blueprint:__
   - The format of the dataframe needed for this graph is straight forward, based on the ideology of the persception of the chart, these are the colunms needed for thr dataframe;
        - Name,
        - System Ratings,
        - Budget,
        - Revenue,
        - Budget of Movie,
        - Renenue of Movies
   
  
  - The style of this chart is a Selection Histogram which is found in the Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis is the Revenue and the y-axis is the Budget, this set up projects wether a linear regression, meaning if the hypothesis which is, the higher the budget the higher the revenue is proven right projecting a linear regression.
  
  - The graph has an attachted histogram showing the amount of items in each category within the selection. In order to make a selection create a box by dragging the mouse. When the mouse hovers the pionts it projects the name, system rating, budget of the movies and the reevenue of the movies.

In [182]:
# variable for the range colunm neede for the dataframe below
listt = range(0,210)

In [183]:
# data frame created for the next three graphs
dataframe2 = pd.DataFrame({"Name":all_actionadventure_info1.Name,"System Rating":all_actionadventure_info1.System_ratings,"Budget":all_actionadventure_info1.Buget,'Range':listt,
                           "Revenue":all_actionadventure_info1.Total_gross,'Budget of Movie':all_actionadventure_info1.Product_budget,'Revenue of Movie':all_actionadventure_info1.Worlwide_gross})

In [184]:
#scatter graph
brush = alt.selection(type='interval')# to reate the selction box
points=alt.Chart(dataframe2).mark_circle(size=60).encode(
    x="Revenue:Q",# x-axis
    y='Budget',# y-axis
    color='System Rating', # color based on system rating put into category
    # interactive when the pionts are hovered the name, budget, revenue and system rating shows up
    tooltip=['Name','System Rating','Budget of Movie','Revenue of Movie']
).properties(height=400,width=500).add_selection(brush)# the size of graph

# histogram chart
bars=alt.Chart(dataframe2).mark_bar().encode(
        y='System Rating:N',# y-axis
        color='System Rating:N',# color put into groups based on system ratings
        x='count(Revenue):Q').transform_filter(brush)# x-axis
points&bars# graphs combined together

alt.VConcatChart(...)

# Blueprint: Revenue of Movies

This is the blueprint for creating the fourth visualization Revenue of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis shows the revenue of each movie and the y-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the revenue of the movie.

In [185]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
points1=base.mark_point(size=60).encode(
       y=alt.Y('Range',title='',axis=None),# y-axis
       x = alt.X('Revenue:Q',title='Revenue'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
x_ticks=base.mark_tick().encode(
    alt.X('Revenue',axis=tick_axis),# x-axis
    alt.Y('System Rating',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
points1&x_ticks# the two graphs combined

alt.VConcatChart(...)

# Blueprint: Budget of Movies

This is the blueprint for creating the fivth visualization Budget of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The y-axis shows the Budget of each movie and the x-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the budget of the movie.

In [186]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
pionts1=base.mark_point(size=60).encode(
       x=alt.X('Range',title='',axis=None),# y-axis
       y = alt.Y('Budget:Q',title='Budget'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
y_ticks=base.mark_tick().encode(
    alt.X('System Rating',axis=tick_axis),# x-axis
    alt.Y('Budget',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
y_ticks|pionts1# the two graphs combined

alt.HConcatChart(...)

# Blueprint: Movies that made Profit

This is the blueprint for creating the seventh visualization, Movies that made Profit. Highcharts will be used to create this graph. 

__Blueprint:__
- The graph used for this visualzation is Highcharts Lollipop series which is found in the Highcharts Demos. Lollipop charts are variants of column charts, with a circle marker for the data value and a line extending to the axis.The first approach to this chart is by understanding the format of the script. This graph has two types of code HTML and Javascript. JupyterLab has magic commands that supports HTML and Javascript, it uses the '%' syntax element for magics.

   Before the HTML and Javascript are scripted a dataframe needs to be made to extract all the movies that made profit in the action and adventure genre. The two variable needed from the parent dataframe '_all_actionadventure_info1_' is the name and profit made in integer. 
   
   - __HTML Section:__
      
      To start off the magic command '%%HTML' should be scripted first in the cell. The main scripted         lines that will be used to create highchart graph through out this project are;
          <script src="https://code.highcharts.com/highcharts.js"></script>
          <script src="https://code.highcharts.com/highcharts-more.js"></script>
          <script src="https://code.highcharts.com/modules/exporting.js"></script>
          <script src="https://code.highcharts.com/modules/accessibility.js"></script>
     For this particular graph this script will be used to get lollipop affect;
          <script src="https://code.highcharts.com/modules/dumbbell.js"></script>
          <script src="https://code.highcharts.com/modules/lollipop.js"></script>
     To close off the HTML script, this script is used and to indetify and differenate this claa from        other, the div id has to be named, and if thei graph is being used more than once the div id needs      to have a different name at all times or it will not work;
                       <figure class="highcharts-figure">
                       <div id="r1"></div> 
                       <p class= "highcharts-description">
                       </p>
                       </figure>
                       
   - __Javascript Section:__
   
      To start off, the magic command '%%JS' is used to script javascript in the jupyterlab cell. The         javascript section will have comments and explaination, but for futher information go to               Highcharts Demos.The normal layout is horizontal but for this graph its going to be vertical. The       main javascript used to create this lollipop graph is;
                         name: ' The Sound of Music ' 
                         low: 2303109231
      The name variable is where the name of the movies is put and the low variable is the amount of         profit made in integer is put.

In [1067]:
dataframe = pd.DataFrame({"Name":all_actionadventure_info1.Name,"Profit":all_actionadventure_info1.Profit})

In [1068]:
# get the largest movies in profit to the smallest for lollipop graph
new1 = []
for i,x in enumerate(dataframe.Profit):
    new1.append((i,x))
new1.sort(reverse=True,key=lambda x:x[1])
new1

[(159, 7749324763),
 (158, 4489260987),
 (157, 2219462581),
 (205, 2168030400),
 (99, 1927488188),
 (110, 1520400637),
 (145, 1507787834),
 (106, 1486843909),
 (186, 1272064256),
 (103, 1101283862),
 (172, 1019251311),
 (122, 992158414),
 (6, 948061550),
 (120, 908561013),
 (84, 906914868),
 (152, 899286958),
 (45, 874496193),
 (65, 835431568),
 (115, 820724923),
 (97, 818045358),
 (154, 817826064),
 (134, 813660789),
 (44, 784765137),
 (197, 773346348),
 (94, 753874057),
 (140, 750988612),
 (174, 724612155),
 (199, 716573581),
 (1, 710366855),
 (24, 682706375),
 (96, 668100000),
 (64, 666907323),
 (107, 666137188),
 (130, 648407405),
 (30, 642820459),
 (29, 641575131),
 (108, 623192705),
 (123, 621847012),
 (136, 619409043),
 (111, 616394724),
 (182, 581486736),
 (203, 560099082),
 (177, 542397137),
 (8, 540644566),
 (2, 537890267),
 (167, 529651467),
 (162, 522021436),
 (147, 517874560),
 (170, 499368315),
 (17, 494602516),
 (12, 488986787),
 (171, 488626372),
 (27, 474836535),
 (16, 474234272),
 (37, 469446407),
 (198, 464480841),
 (102, 455000000),
 (125, 452630685),
 (194, 449502590),
 (104, 445366247),
 (43, 439551353),
 (100, 436454868),
 (15, 435532684),
 (169, 433812793),
 (19, 429290136),
 (202, 424970494),
 (146, 424830090),
 (175, 420356209),
 (164, 419863600),
 (153, 410990117),
 (67, 410663443),
 (73, 408438212),
 (4, 399171547),
 (165, 397950503),
 (189, 384145992),
 (119, 376273243),
 (77, 365728529),
 (183, 363410113),
 (18, 349837368),
 (160, 346093329),
 (52, 342230516),
 (20, 334161265),
 (59, 332807404),
 (10, 331511521),
 (193, 329771510),
 (118, 320812364),
 (168, 312409852),
 (176, 308330363),
 (23, 301767803),
 (207, 301709188),
 (14, 297739855),
 (112, 292820831),
 (179, 292000694),
 (3, 290359051),
 (66, 281875536),
 (181, 281333876),
 (166, 273354469),
 (70, 272288147),
 (13, 263186950),
 (51, 263100280),
 (196, 259731909),
 (180, 255883523),
 (89, 246915264),
 (38, 238547523),
 (48, 238325007),
 (75, 238325007),
 (88, 237013181),
 (63, 234942531),
 (78, 230268353),
 (101, 229400000),
 (28, 226756621),
 (105, 223661946),
 (80, 219461782),
 (11, 219169424),
 (31, 219150134),
 (191, 207308101),
 (133, 204370759),
 (161, 200679654),
 (72, 199680778),
 (60, 198180937),
 (109, 188120004),
 (76, 183477501),
 (124, 179044905),
 (116, 178524556),
 (9, 175004422),
 (32, 169480691),
 (5, 168902025),
 (144, 167126930),
 (206, 165313810),
 (131, 162877160),
 (148, 162796250),
 (151, 162045765),
 (117, 157734111),
 (79, 155185089),
 (113, 152615465),
 (195, 151775880),
 (132, 144819862),
 (42, 141521247),
 (93, 134539441),
 (209, 129531208),
 (127, 128066132),
 (85, 122504758),
 (69, 120017848),
 (46, 112910991),
 (25, 108075434),
 (33, 107200000),
 (68, 107200000),
 (56, 104285587),
 (53, 102543519),
 (47, 101200000),
 (74, 96049020),
 (135, 86520319),
 (150, 86030539),
 (141, 84139368),
 (95, 84100704),
 (98, 82900533),
 (58, 82112435),
 (163, 78690254),
 (188, 78258481),
 (121, 65155986),
 (36, 63200000),
 (155, 58685412),
 (81, 56047317),
 (49, 53049560),
 (138, 51932573),
 (129, 50864900),
 (35, 47849187),
 (34, 46000000),
 (39, 39716717),
 (201, 35023296),
 (22, 30357126),
 (190, 29770160),
 (114, 29185657),
 (26, 28818556),
 (126, 28800274),
 (83, 28469033),
 (149, 27089296),
 (82, 19010667),
 (156, 15498203),
 (71, 15149422),
 (87, 14758389),
 (204, 9007222),
 (139, 8189219),
 (142, 7175405),
 (185, 6471023),
 (91, 5402370),
 (192, 2803180),
 (178, 0),
 (86, -2214831),
 (208, -4924024),
 (173, -5416635),
 (143, -5695267),
 (21, -7365642),
 (55, -8175367),
 (62, -8807575),
 (184, -8887831),
 (92, -9696633),
 (40, -10306691),
 (54, -11046681),
 (128, -12152932),
 (200, -12743495),
 (0, -14997885),
 (50, -24283874),
 (61, -27507986),
 (187, -28518962),
 (90, -29365490),
 (7, -35369664),
 (57, -48572910),
 (137, -76844562),
 (41, -92905005)]

In [1070]:
# getting the name of movies for the lollipop graph
new2 = []
for i in new1:
    new2.append(dataframe.Name[i[0]])
for i,x in enumerate(new2):
    print(i,x)

0 Snow White and the Seven Dwarfs
1 Bambi
2 Pinocchio
3 E.T. the Extra-Terrestrial
4 Titanic
5 Jurassic World
6 Fantasia
7 The Lord of the Rings: The Return of the King
8 Harry Potter and the Sorcerer's Stone
9 Forrest Gump
10 Joker
11 The Sixth Sense
12 Captain Marvel
13 Skyfall
14 The Lion King
15 Aladdin 1992
16 Jumanji: Welcome to the Jungle
17 Harry Potter and the Deathly Hallows: Part I
18 Spider-Man 2
19 The Dark Knight
20 Beauty and the Beast
21 Peter Pan 1953
22 Ice Age: Continental Drift
23 The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
24 Mrs. Doubtfire
25 The Rescuers
26 Deadpool
27 The Parent Trap
28 The Hobbit: The Desolation of Smaug
29 Spider-Man
30 Jumanji: The Next Level
31 Harry Potter and the Prisoner of Azkaban
32 Inception
33 The Black Stallion
34 The Da Vinci Code
35 The Hunger Games: Mockingjay - Part 1
36 Gravity
37 Wonder Woman 1984
38 Monsters, Inc
39 The Hunger Games
40 The Passion of the Christ
41 Up
42 American Beauty
43 Dawn of the Planet of the Apes
44 The Amazing Spider-Man
45 Fifty Shades of Grey
46 Logan
47 Oliver! (film)
48 Ted (film)
49 Thor: The Dark World
50 The Hunger Games: Mockingjay - Part 2
51 American Sniper
52 War of the Worlds
53 Hancock
54 Night at the Museum
55 Night at the Museum
56 Fantastic Beasts: The Crimes of Grindelwald
57 Cars
58 Hook (film)
59 Iron Man
60 Cinderella
61 Catch Me If You Can
62 I am Legend
63 The Hangover
64 Ready Player One
65 National Treasure: Book of Secrets
66 2001: A Space Odyssey
67 Indecent Proposal
68 Lucy
69 Sleeping Beauty
70 Sherlock Holmes: A Game of Shadows
71 Sherlock Holmes
72 Iron Man
73 The Revenant
74 Spirited Away
75 Jason Bourne
76 Ocean's Eleven
77 Slumdog Millionaire
78 Dunkirk
79 Mulan 1998
80 Cast Away
81 Troy
82 Taken 2
83 Wreck-It Ralph
84 Enchanted
85 Gremlins
86 Troy
87 Gone Girl
88 Men in Black 2
89 Big (film)
90 Pearl Harbor
91 The Ring
92 The Wolf of Wall Street
93 Oz the Great and Powerful
94 X-Men 2
95 22 Jump Street
96 Prometheus
97 Live Free or Die Hard
98 The Chronicles of Narnia: The Voyage of the Dawn Treader
99 Hannibal
100 The Goonies
101 Bridesmaids
102 Inglourious Basterds
103 The Smurfs 2
104 Now You See Me 2
105 Now You See Me 2
106 The SpongeBob Movie: Sponge Out of Water
107 Penguins of Madagascar
108 Air Force One
109 Knives Out
110 Night at the Museum: Secret of the Tomb
111 Batman Begins
112 Shutter Island
113 Independence Day: Resurgence
114 Trolls
115 My Girl
116 The Absent-Minded Professor
117 A Man for All Seasons
118 Sex and the City 2
119 Journey to the Center of the Earth
120 The Help
121 Tomb Raider
122 The Addams Family
123 Sully
124 Dumbo
125 Fantastic Four: Rise of the Silver Surfer
126 The Legend of Tarzan
127 The Italian Job
128 Nanny McPhee
129 The Land Before Time
130 The King and I
131 The Princess and the Frog
132 Mean Girls
133 Click
134 Ferris Bueller's Day Off
135 Bridge to Terabithia
136 Hercules
137 Alien: Covenant
138 Edward Scissorhands
139 Finding Neverland
140 My Neighbor Totoro
141 Christopher Robin
142 Gulliver's Travels
143 You Don't Mess With the Zohan
144 Hulk
145 Charlie's Angels: Full Throttle
146 Charlie's Angels: Full Throttle
147 Daddy Day Care
148 AVP: Alien Vs. Predator
149 Hollow Man
150 Atlantis: The Lost Empire
151 The Rookie 2002
152 Charlotte's Web
153 Whisper of the Heart
154 The Prestige
155 13 Going on 30
156 Zero Dark Thirty
157 Spotlight (film)
158 Nim's Island
159 Clueless
160 Dante's Peak
161 The Great Mouse Detective
162 Lost In Space
163 Spy Game
164 The Great Muppet Caper
165 The Cat Returns
166 Fantastic Four
167 Stuart Little 2
168 Legend of the Guardians: The Owls of Ga'Hoole
169 The Princess Bride
170 Flushed Away
171 Hugo (film)
172 Don't Tell Mom the Babysitter's Dead
173 Miami Vice
174 The Secret World of Arrietty
175 Pompeii
176 Alice in Wonderland 1951
177 The Wild
178 The Prince and the Pauper (1937 film)
179 Wonder Park
180 Sucker Punch
181 The Witches 1990
182 The Last Unicorn
183 Yellow Submarine (film)
184 Fantastic Mr. Fox
185 Greenland
186 Inkheart
187 Lost Highway
188 Lady in the Water
189 Matilda
190 Black Snake Moan
191 The Straight Story
192 The Wolfman
193 Elektra
194 The House
195 Stealing Beauty
196 Ladybugs
197 In the Heart of the Sea
198 The Legend of Hercules
199 A Little Princess
200 National Treasure
201 The Lone Ranger
202 K-19: The Widowmaker
203 Rebound
204 Labyrinth
205 News of the World
206 King Arthur: Legend of the Sword
207 Beyond Borders
208 Kiki's Delivery Service
209 The Adventures of Pluto Nash

Using a for loop to put the name and profit in html code which will be copied and pasted in the cell below.

In [1071]:
for x in range(len(new2)):
    print('        }, { \n           name:',"'",new2[x],"'",','+'\n           low:',new1[x][1])

        }, {
           name: ' Snow White and the Seven Dwarfs ' ,
           low: 7749324763
        }, {
           name: ' Bambi ' ,
           low: 4489260987
        }, {
           name: ' Pinocchio ' ,
           low: 2219462581
        }, {
           name: ' E.T. the Extra-Terrestrial ' ,
           low: 2168030400
        }, {
           name: ' Titanic ' ,
           low: 1927488188
        }, {
           name: ' Jurassic World ' ,
           low: 1520400637
        }, {
           name: ' Fantasia ' ,
           low: 1507787834
        }, {
           name: ' The Lord of the Rings: The Return of the King ' ,
           low: 1486843909
        }, {
           name: ' Harry Potter and the Sorcerer's Stone ' ,
           low: 1272064256
        }, {
           name: ' Forrest Gump ' ,
           low: 1101283862
        }, {
           name: ' Joker ' ,
           low: 1019251311
        }, {
           name: ' The Sixth Sense ' ,
           low: 992158414
        }, {
           name: ' Captain Marvel ' ,
           low: 948061550
        }, {
           name: ' Skyfall ' ,
           low: 908561013
        }, {
           name: ' The Lion King ' ,
           low: 906914868
        }, {
           name: ' Aladdin 1992 ' ,
           low: 899286958
        }, {
           name: ' Jumanji: Welcome to the Jungle ' ,
           low: 874496193
        }, {
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           low: 835431568
        }, {
           name: ' Spider-Man 2 ' ,
           low: 820724923
        }, {
           name: ' The Dark Knight ' ,
           low: 818045358
        }, {
           name: ' Beauty and the Beast ' ,
           low: 817826064
        }, {
           name: ' Peter Pan 1953 ' ,
           low: 813660789
        }, {
           name: ' Ice Age: Continental Drift ' ,
           low: 784765137
        }, {
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 773346348
        }, {
           name: ' Mrs. Doubtfire ' ,
           low: 753874057
        }, {
           name: ' The Rescuers ' ,
           low: 750988612
        }, {
           name: ' Deadpool ' ,
           low: 724612155
        }, {
           name: ' The Parent Trap ' ,
           low: 716573581
        }, {
           name: ' The Hobbit: The Desolation of Smaug ' ,
           low: 710366855
        }, {
           name: ' Spider-Man ' ,
           low: 682706375
        }, {
           name: ' Jumanji: The Next Level ' ,
           low: 668100000
        }, {
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           low: 666907323
        }, {
           name: ' Inception ' ,
           low: 666137188
        }, {
           name: ' The Black Stallion ' ,
           low: 648407405
        }, {
           name: ' The Da Vinci Code ' ,
           low: 642820459
        }, {
           name: ' The Hunger Games: Mockingjay - Part 1 ' ,
           low: 641575131
        }, {
           name: ' Gravity ' ,
           low: 623192705
        }, {
           name: ' Wonder Woman 1984 ' ,
           low: 621847012
        }, {
           name: ' Monsters, Inc ' ,
           low: 619409043
        }, {
           name: ' The Hunger Games ' ,
           low: 616394724
        }, {
           name: ' The Passion of the Christ ' ,
           low: 581486736
        }, {
           name: ' Up ' ,
           low: 560099082
        }, {
           name: ' American Beauty ' ,
           low: 542397137
        }, {
           name: ' Dawn of the Planet of the Apes ' ,
           low: 540644566
        }, {
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, {
           name: ' Fifty Shades of Grey ' ,
           low: 529651467
        }, {
           name: ' Logan ' ,
           low: 522021436
        }, {
           name: ' Oliver! (film) ' ,
           low: 517874560
        }, {
           name: ' Ted (film) ' ,
           low: 499368315
        }, {
           name: ' Thor: The Dark World ' ,
           low: 494602516
        }, {
           name: ' The Hunger Games: Mockingjay - Part 2 ' ,
           low: 488986787
        }, {
           name: ' American Sniper ' ,
           low: 488626372
        }, {
           name: ' War of the Worlds ' ,
           low: 474836535
        }, {
           name: ' Hancock ' ,
           low: 474234272
        }, {
           name: ' Night at the Museum ' ,
           low: 469446407
        }, {
           name: ' Night at the Museum ' ,
           low: 464480841
        }, {
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 455000000
        }, {
           name: ' Cars ' ,
           low: 452630685
        }, {
           name: ' Hook (film) ' ,
           low: 449502590
        }, {
           name: ' Iron Man ' ,
           low: 445366247
        }, {
           name: ' Cinderella ' ,
           low: 439551353
        }, {
           name: ' Catch Me If You Can ' ,
           low: 436454868
        }, {
           name: ' I am Legend ' ,
           low: 435532684
        }, {
           name: ' The Hangover ' ,
           low: 433812793
        }, {
           name: ' Ready Player One ' ,
           low: 429290136
        }, {
           name: ' National Treasure: Book of Secrets ' ,
           low: 424970494
        }, {
           name: ' 2001: A Space Odyssey ' ,
           low: 424830090
        }, {
           name: ' Indecent Proposal ' ,
           low: 420356209
        }, {
           name: ' Lucy ' ,
           low: 419863600
        }, {
           name: ' Sleeping Beauty ' ,
           low: 410990117
        }, {
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, {
           name: ' Sherlock Holmes ' ,
           low: 408438212
        }, {
           name: ' Iron Man ' ,
           low: 399171547
        }, {
           name: ' The Revenant ' ,
           low: 397950503
        }, {
           name: ' Spirited Away ' ,
           low: 384145992
        }, {
           name: ' Jason Bourne ' ,
           low: 376273243
        }, {
           name: ' Ocean's Eleven ' ,
           low: 365728529
        }, {
           name: ' Slumdog Millionaire ' ,
           low: 363410113
        }, {
           name: ' Dunkirk ' ,
           low: 349837368
        }, {
           name: ' Mulan 1998 ' ,
           low: 346093329
        }, {
           name: ' Cast Away ' ,
           low: 342230516
        }, {
           name: ' Troy ' ,
           low: 334161265
        }, {
           name: ' Taken 2 ' ,
           low: 332807404
        }, {
           name: ' Wreck-It Ralph ' ,
           low: 331511521
        }, {
           name: ' Enchanted ' ,
           low: 329771510
        }, {
           name: ' Gremlins ' ,
           low: 320812364
        }, {
           name: ' Troy ' ,
           low: 312409852
        }, {
           name: ' Gone Girl ' ,
           low: 308330363
        }, {
           name: ' Men in Black 2 ' ,
           low: 301767803
        }, {
           name: ' Big (film) ' ,
           low: 301709188
        }, {
           name: ' Pearl Harbor ' ,
           low: 297739855
        }, {
           name: ' The Ring ' ,
           low: 292820831
        }, {
           name: ' The Wolf of Wall Street ' ,
           low: 292000694
        }, {
           name: ' Oz the Great and Powerful ' ,
           low: 290359051
        }, {
           name: ' X-Men 2 ' ,
           low: 281875536
        }, {
           name: ' 22 Jump Street ' ,
           low: 281333876
        }, {
           name: ' Prometheus ' ,
           low: 273354469
        }, {
           name: ' Live Free or Die Hard ' ,
           low: 272288147
        }, {
           name: ' The Chronicles of Narnia: The Voyage of the Dawn Treader ' ,
           low: 263186950
        }, {
           name: ' Hannibal ' ,
           low: 263100280
        }, {
           name: ' The Goonies ' ,
           low: 259731909
        }, {
           name: ' Bridesmaids ' ,
           low: 255883523
        }, {
           name: ' Inglourious Basterds ' ,
           low: 246915264
        }, {
           name: ' The Smurfs 2 ' ,
           low: 238547523
        }, {
           name: ' Now You See Me 2 ' ,
           low: 238325007
        }, {
           name: ' Now You See Me 2 ' ,
           low: 238325007
        }, {
           name: ' The SpongeBob Movie: Sponge Out of Water ' ,
           low: 237013181
        }, {
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, {
           name: ' Air Force One ' ,
           low: 230268353
        }, {
           name: ' Knives Out ' ,
           low: 229400000
        }, {
           name: ' Night at the Museum: Secret of the Tomb ' ,
           low: 226756621
        }, {
           name: ' Batman Begins ' ,
           low: 223661946
        }, {
           name: ' Shutter Island ' ,
           low: 219461782
        }, {
           name: ' Independence Day: Resurgence ' ,
           low: 219169424
        }, {
           name: ' Trolls ' ,
           low: 219150134
        }, {
           name: ' My Girl ' ,
           low: 207308101
        }, {
           name: ' The Absent-Minded Professor ' ,
           low: 204370759
        }, {
           name: ' A Man for All Seasons ' ,
           low: 200679654
        }, {
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, {
           name: ' Journey to the Center of the Earth ' ,
           low: 198180937
        }, {
           name: ' The Help ' ,
           low: 188120004
        }, {
           name: ' Tomb Raider ' ,
           low: 183477501
        }, {
           name: ' The Addams Family ' ,
           low: 179044905
        }, {
           name: ' Sully ' ,
           low: 178524556
        }, {
           name: ' Dumbo ' ,
           low: 175004422
        }, {
           name: ' Fantastic Four: Rise of the Silver Surfer ' ,
           low: 169480691
        }, {
           name: ' The Legend of Tarzan ' ,
           low: 168902025
        }, {
           name: ' The Italian Job ' ,
           low: 167126930
        }, {
           name: ' Nanny McPhee ' ,
           low: 165313810
        }, {
           name: ' The Land Before Time ' ,
           low: 162877160
        }, {
           name: ' The King and I ' ,
           low: 162796250
        }, {
           name: ' The Princess and the Frog ' ,
           low: 162045765
        }, {
           name: ' Mean Girls ' ,
           low: 157734111
        }, {
           name: ' Click ' ,
           low: 155185089
        }, {
           name: ' Ferris Bueller's Day Off ' ,
           low: 152615465
        }, {
           name: ' Bridge to Terabithia ' ,
           low: 151775880
        }, {
           name: ' Hercules ' ,
           low: 144819862
        }, {
           name: ' Alien: Covenant ' ,
           low: 141521247
        }, {
           name: ' Edward Scissorhands ' ,
           low: 134539441
        }, {
           name: ' Finding Neverland ' ,
           low: 129531208
        }, {
           name: ' My Neighbor Totoro ' ,
           low: 128066132
        }, {
           name: ' Christopher Robin ' ,
           low: 122504758
        }, {
           name: ' Gulliver's Travels ' ,
           low: 120017848
        }, {
           name: ' You Don't Mess With the Zohan ' ,
           low: 112910991
        }, {
           name: ' Hulk ' ,
           low: 108075434
        }, {
           name: ' Charlie's Angels: Full Throttle ' ,
           low: 107200000
        }, {
           name: ' Charlie's Angels: Full Throttle ' ,
           low: 107200000
        }, {
           name: ' Daddy Day Care ' ,
           low: 104285587
        }, {
           name: ' AVP: Alien Vs. Predator ' ,
           low: 102543519
        }, {
           name: ' Hollow Man ' ,
           low: 101200000
        }, {
           name: ' Atlantis: The Lost Empire ' ,
           low: 96049020
        }, {
           name: ' The Rookie 2002 ' ,
           low: 86520319
        }, {
           name: ' Charlotte's Web ' ,
           low: 86030539
        }, {
           name: ' Whisper of the Heart ' ,
           low: 84139368
        }, {
           name: ' The Prestige ' ,
           low: 84100704
        }, {
           name: ' 13 Going on 30 ' ,
           low: 82900533
        }, {
           name: ' Zero Dark Thirty ' ,
           low: 82112435
        }, {
           name: ' Spotlight (film) ' ,
           low: 78690254
        }, {
           name: ' Nim's Island ' ,
           low: 78258481
        }, {
           name: ' Clueless ' ,
           low: 65155986
        }, {
           name: ' Dante's Peak ' ,
           low: 63200000
        }, {
           name: ' The Great Mouse Detective ' ,
           low: 58685412
        }, {
           name: ' Lost In Space ' ,
           low: 56047317
        }, {
           name: ' Spy Game ' ,
           low: 53049560
        }, {
           name: ' The Great Muppet Caper ' ,
           low: 51932573
        }, {
           name: ' The Cat Returns ' ,
           low: 50864900
        }, {
           name: ' Fantastic Four ' ,
           low: 47849187
        }, {
           name: ' Stuart Little 2 ' ,
           low: 46000000
        }, {
           name: ' Legend of the Guardians: The Owls of Ga'Hoole ' ,
           low: 39716717
        }, {
           name: ' The Princess Bride ' ,
           low: 35023296
        }, {
           name: ' Flushed Away ' ,
           low: 30357126
        }, {
           name: ' Hugo (film) ' ,
           low: 29770160
        }, {
           name: ' Don't Tell Mom the Babysitter's Dead ' ,
           low: 29185657
        }, {
           name: ' Miami Vice ' ,
           low: 28818556
        }, {
           name: ' The Secret World of Arrietty ' ,
           low: 28800274
        }, {
           name: ' Pompeii ' ,
           low: 28469033
        }, {
           name: ' Alice in Wonderland 1951 ' ,
           low: 27089296
        }, {
           name: ' The Wild ' ,
           low: 19010667
        }, {
           name: ' The Prince and the Pauper (1937 film) ' ,
           low: 15498203
        }, {
           name: ' Wonder Park ' ,
           low: 15149422
        }, {
           name: ' Sucker Punch ' ,
           low: 14758389
        }, {
           name: ' The Witches 1990 ' ,
           low: 9007222
        }, {
           name: ' The Last Unicorn ' ,
           low: 8189219
        }, {
           name: ' Yellow Submarine (film) ' ,
           low: 7175405
        }, {
           name: ' Fantastic Mr. Fox ' ,
           low: 6471023
        }, {
           name: ' Greenland ' ,
           low: 5402370
        }, {
           name: ' Inkheart ' ,
           low: 2803180
        }, {
           name: ' Lost Highway ' ,
           low: 0
        }, {
           name: ' Lady in the Water ' ,
           low: -2214831
        }, {
           name: ' Matilda ' ,
           low: -4924024
        }, {
           name: ' Black Snake Moan ' ,
           low: -5416635
        }, {
           name: ' The Straight Story ' ,
           low: -5695267
        }, {
           name: ' The Wolfman ' ,
           low: -7365642
        }, {
           name: ' Elektra ' ,
           low: -8175367
        }, {
           name: ' The House ' ,
           low: -8807575
        }, {
           name: ' Stealing Beauty ' ,
           low: -8887831
        }, {
           name: ' Ladybugs ' ,
           low: -9696633
        }, {
           name: ' In the Heart of the Sea ' ,
           low: -10306691
        }, {
           name: ' The Legend of Hercules ' ,
           low: -11046681
        }, {
           name: ' A Little Princess ' ,
           low: -12152932
        }, {
           name: ' National Treasure ' ,
           low: -12743495
        }, {
           name: ' The Lone Ranger ' ,
           low: -14997885
        }, {
           name: ' K-19: The Widowmaker ' ,
           low: -24283874
        }, {
           name: ' Rebound ' ,
           low: -27507986
        }, {
           name: ' Labyrinth ' ,
           low: -28518962
        }, {
           name: ' News of the World ' ,
           low: -29365490
        }, {
           name: ' King Arthur: Legend of the Sword ' ,
           low: -35369664
        }, {
           name: ' Beyond Borders ' ,
           low: -48572910
        }, {
           name: ' Kiki's Delivery Service ' ,
           low: -76844562
        }, {
           name: ' The Adventures of Pluto Nash ' ,
           low: -92905005

In [189]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/dumbbell.js"></script>
<script src="https://code.highcharts.com/modules/lollipop.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="r4"></div> 
    <p class= "highcharts-description">
    </p>
</figure>

In [213]:
%%js
Highcharts.chart('r4', { //name of grapg is r1

    chart: {
        type: 'lollipop', //type of graph is the lollipop graph
        inverted:true, //this makes the graph horizontal
        height:1700  //this allows the size of the graph to be ajusted
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. {xDescription}, {point.y}.'
        }
    },

    legend: {
        enabled: true,
        layout:'vertical',
        reversed:true
    },

    subtitle: {
        text: '209 Movies'
    },

    title: {
        text: 'Classic Genre'
    },

    tooltip: {
        shared: true //allows the tooltip to be enabled
    },

    xAxis: {
        type:'category',
        title:{
            text:'Movies' //name of x-axis
        }
    },
    yAxis:{
        title:{
            text:'Profit' //name of y-axis
        }
    },
    series: [{
        name: 'Profit',
        color:'#e600e6', //allows color to be adjusted
        dataSorting:{
            enabled: false
        },
        data: [ { 
           name: ' Snow White and the Seven Dwarfs ' ,//name of movie 
           low: 7749324763 //amount of profit made in int of the movie
        }, { 
           name: ' Bambi ' ,
           low: 4489260987
        }, { 
           name: ' Pinocchio ' ,
           low: 2219462581
        }, { 
           name: ' E.T. the Extra-Terrestrial ' ,
           low: 2168030400
        }, { 
           name: ' Titanic ' ,
           low: 1927488188
        }, { 
           name: ' Jurassic World ' ,
           low: 1520400637
        }, { 
           name: ' Fantasia ' ,
           low: 1507787834
        }, { 
           name: ' The Lord of the Rings: The Return of the King ' ,
           low: 1486843909
        }, { 
           name: ' Harry Potter and the Sorcerer\'s Stone ' ,
           low: 1272064256
        }, { 
           name: ' Forrest Gump ' ,
           low: 1101283862
        }, { 
           name: ' Joker ' ,
           low: 1019251311
        }, { 
           name: ' The Sixth Sense ' ,
           low: 992158414
        }, { 
           name: ' Captain Marvel ' ,
           low: 948061550
        }, { 
           name: ' Skyfall ' ,
           low: 908561013
        }, { 
           name: ' The Lion King ' ,
           low: 906914868
        }, { 
           name: ' Aladdin 1992 ' ,
           low: 899286958
        }, { 
           name: ' Jumanji: Welcome to the Jungle ' ,
           low: 874496193
        }, { 
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           low: 835431568
        }, { 
           name: ' Spider-Man 2 ' ,
           low: 820724923
        }, { 
           name: ' The Dark Knight ' ,
           low: 818045358
        }, { 
           name: ' Beauty and the Beast ' ,
           low: 817826064
        }, { 
           name: ' Peter Pan 1953 ' ,
           low: 813660789
        }, { 
           name: ' Ice Age: Continental Drift ' ,
           low: 784765137
        }, { 
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 773346348
        }, { 
           name: ' Mrs. Doubtfire ' ,
           low: 753874057
        }, { 
           name: ' The Rescuers ' ,
           low: 750988612
        }, { 
           name: ' Deadpool ' ,
           low: 724612155
        }, { 
           name: ' The Parent Trap ' ,
           low: 716573581
        }, { 
           name: ' The Hobbit: The Desolation of Smaug ' ,
           low: 710366855
        }, { 
           name: ' Spider-Man ' ,
           low: 682706375
        }, { 
           name: ' Jumanji: The Next Level ' ,
           low: 668100000
        }, { 
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           low: 666907323
        }, { 
           name: ' Inception ' ,
           low: 666137188
        }, { 
           name: ' The Black Stallion ' ,
           low: 648407405
        }, { 
           name: ' The Da Vinci Code ' ,
           low: 642820459
        }, { 
           name: ' The Hunger Games: Mockingjay - Part 1 ' ,
           low: 641575131
        }, { 
           name: ' Gravity ' ,
           low: 623192705
        }, { 
           name: ' Wonder Woman 1984 ' ,
           low: 621847012
        }, { 
           name: ' Monsters, Inc ' ,
           low: 619409043
        }, { 
           name: ' The Hunger Games ' ,
           low: 616394724
        }, { 
           name: ' The Passion of the Christ ' ,
           low: 581486736
        }, { 
           name: ' Up ' ,
           low: 560099082
        }, { 
           name: ' American Beauty ' ,
           low: 542397137
        }, { 
           name: ' Dawn of the Planet of the Apes ' ,
           low: 540644566
        }, { 
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, { 
           name: ' Fifty Shades of Grey ' ,
           low: 529651467
        }, { 
           name: ' Logan ' ,
           low: 522021436
        }, { 
           name: ' Oliver! (film) ' ,
           low: 517874560
        }, { 
           name: ' Ted (film) ' ,
           low: 499368315
        }, { 
           name: ' Thor: The Dark World ' ,
           low: 494602516
        }, { 
           name: ' The Hunger Games: Mockingjay - Part 2 ' ,
           low: 488986787
        }, { 
           name: ' American Sniper ' ,
           low: 488626372
        }, { 
           name: ' War of the Worlds ' ,
           low: 474836535
        }, { 
           name: ' Hancock ' ,
           low: 474234272
        }, { 
           name: ' Night at the Museum ' ,
           low: 469446407
        }, { 
           name: ' Night at the Museum ' ,
           low: 464480841
        }, { 
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 455000000
        }, { 
           name: ' Cars ' ,
           low: 452630685
        }, { 
           name: ' Hook (film) ' ,
           low: 449502590
        }, { 
           name: ' Iron Man ' ,
           low: 445366247
        }, { 
           name: ' Cinderella ' ,
           low: 439551353
        }, { 
           name: ' Catch Me If You Can ' ,
           low: 436454868
        }, { 
           name: ' I am Legend ' ,
           low: 435532684
        }, { 
           name: ' The Hangover ' ,
           low: 433812793
        }, { 
           name: ' Ready Player One ' ,
           low: 429290136
        }, { 
           name: ' National Treasure: Book of Secrets ' ,
           low: 424970494
        }, { 
           name: ' 2001: A Space Odyssey ' ,
           low: 424830090
        }, { 
           name: ' Indecent Proposal ' ,
           low: 420356209
        }, { 
           name: ' Lucy ' ,
           low: 419863600
        }, { 
           name: ' Sleeping Beauty ' ,
           low: 410990117
        }, { 
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, { 
           name: ' Sherlock Holmes ' ,
           low: 408438212
        }, { 
           name: ' Iron Man ' ,
           low: 399171547
        }, { 
           name: ' The Revenant ' ,
           low: 397950503
        }, { 
           name: ' Spirited Away ' ,
           low: 384145992
        }, { 
           name: ' Jason Bourne ' ,
           low: 376273243
        }, { 
           name: ' Ocean\'s Eleven ' ,
           low: 365728529
        }, { 
           name: ' Slumdog Millionaire ' ,
           low: 363410113
        }, { 
           name: ' Dunkirk ' ,
           low: 349837368
        }, { 
           name: ' Mulan 1998 ' ,
           low: 346093329
        }, { 
           name: ' Cast Away ' ,
           low: 342230516
        }, { 
           name: ' Troy ' ,
           low: 334161265
        }, { 
           name: ' Taken 2 ' ,
           low: 332807404
        }, { 
           name: ' Wreck-It Ralph ' ,
           low: 331511521
        }, { 
           name: ' Enchanted ' ,
           low: 329771510
        }, { 
           name: ' Gremlins ' ,
           low: 320812364
        }, { 
           name: ' Troy ' ,
           low: 312409852
        }, { 
           name: ' Gone Girl ' ,
           low: 308330363
        }, { 
           name: ' Men in Black 2 ' ,
           low: 301767803
        }, { 
           name: ' Big (film) ' ,
           low: 301709188
        }, { 
           name: ' Pearl Harbor ' ,
           low: 297739855
        }, { 
           name: ' The Ring ' ,
           low: 292820831
        }, { 
           name: ' The Wolf of Wall Street ' ,
           low: 292000694
        }, { 
           name: ' Oz the Great and Powerful ' ,
           low: 290359051
        }, { 
           name: ' X-Men 2 ' ,
           low: 281875536
        }, { 
           name: ' 22 Jump Street ' ,
           low: 281333876
        }, { 
           name: ' Prometheus ' ,
           low: 273354469
        }, { 
           name: ' Live Free or Die Hard ' ,
           low: 272288147
        }, { 
           name: ' The Chronicles of Narnia: The Voyage of the Dawn Treader ' ,
           low: 263186950
        }, { 
           name: ' Hannibal ' ,
           low: 263100280
        }, { 
           name: ' The Goonies ' ,
           low: 259731909
        }, { 
           name: ' Bridesmaids ' ,
           low: 255883523
        }, { 
           name: ' Inglourious Basterds ' ,
           low: 246915264
        }, { 
           name: ' The Smurfs 2 ' ,
           low: 238547523
        }, { 
           name: ' Now You See Me 2 ' ,
           low: 238325007
        }, { 
           name: ' Now You See Me 2 ' ,
           low: 238325007
        }, { 
           name: ' The SpongeBob Movie: Sponge Out of Water ' ,
           low: 237013181
        }, { 
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, { 
           name: ' Air Force One ' ,
           low: 230268353
        }, { 
           name: ' Knives Out ' ,
           low: 229400000
        }, { 
           name: ' Night at the Museum: Secret of the Tomb ' ,
           low: 226756621
        }, { 
           name: ' Batman Begins ' ,
           low: 223661946
        }, { 
           name: ' Shutter Island ' ,
           low: 219461782
        }, { 
           name: ' Independence Day: Resurgence ' ,
           low: 219169424
        }, { 
           name: ' Trolls ' ,
           low: 219150134
        }, { 
           name: ' My Girl ' ,
           low: 207308101
        }, { 
           name: ' The Absent-Minded Professor ' ,
           low: 204370759
        }, { 
           name: ' A Man for All Seasons ' ,
           low: 200679654
        }, { 
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, { 
           name: ' Journey to the Center of the Earth ' ,
           low: 198180937
        }, { 
           name: ' The Help ' ,
           low: 188120004
        }, { 
           name: ' Tomb Raider ' ,
           low: 183477501
        }, { 
           name: ' The Addams Family ' ,
           low: 179044905
        }, { 
           name: ' Sully ' ,
           low: 178524556
        }, { 
           name: ' Dumbo ' ,
           low: 175004422
        }, { 
           name: ' Fantastic Four: Rise of the Silver Surfer ' ,
           low: 169480691
        }, { 
           name: ' The Legend of Tarzan ' ,
           low: 168902025
        }, { 
           name: ' The Italian Job ' ,
           low: 167126930
        }, { 
           name: ' Nanny McPhee ' ,
           low: 165313810
        }, { 
           name: ' The Land Before Time ' ,
           low: 162877160
        }, { 
           name: ' The King and I ' ,
           low: 162796250
        }, { 
           name: ' The Princess and the Frog ' ,
           low: 162045765
        }, { 
           name: ' Mean Girls ' ,
           low: 157734111
        }, { 
           name: ' Click ' ,
           low: 155185089
        }, { 
           name: ' Ferris Bueller\'s Day Off ' ,
           low: 152615465
        }, { 
           name: ' Bridge to Terabithia ' ,
           low: 151775880
        }, { 
           name: ' Hercules ' ,
           low: 144819862
        }, { 
           name: ' Alien: Covenant ' ,
           low: 141521247
        }, { 
           name: ' Edward Scissorhands ' ,
           low: 134539441
        }, { 
           name: ' Finding Neverland ' ,
           low: 129531208
        }, { 
           name: ' My Neighbor Totoro ' ,
           low: 128066132
        }, { 
           name: ' Christopher Robin ' ,
           low: 122504758
        }, { 
           name: ' Gulliver\'s Travels ' ,
           low: 120017848
        }, { 
           name: ' You Don\'t Mess With the Zohan ' ,
           low: 112910991
        }, { 
           name: ' Hulk ' ,
           low: 108075434
        }, { 
           name: ' Charlie\'s Angels: Full Throttle ' ,
           low: 107200000
        }, { 
           name: ' Charlie\'s Angels: Full Throttle ' ,
           low: 107200000
        }, { 
           name: ' Daddy Day Care ' ,
           low: 104285587
        }, { 
           name: ' AVP: Alien Vs. Predator ' ,
           low: 102543519
        }, { 
           name: ' Hollow Man ' ,
           low: 101200000
        }, { 
           name: ' Atlantis: The Lost Empire ' ,
           low: 96049020
        }, { 
           name: ' The Rookie 2002 ' ,
           low: 86520319
        }, { 
           name: ' Charlotte\'s Web ' ,
           low: 86030539
        }, { 
           name: ' Whisper of the Heart ' ,
           low: 84139368
        }, { 
           name: ' The Prestige ' ,
           low: 84100704
        }, { 
           name: ' 13 Going on 30 ' ,
           low: 82900533
        }, { 
           name: ' Zero Dark Thirty ' ,
           low: 82112435
        }, { 
           name: ' Spotlight (film) ' ,
           low: 78690254
        }, { 
           name: ' Nim\'s Island ' ,
           low: 78258481
        }, { 
           name: ' Clueless ' ,
           low: 65155986
        }, { 
           name: ' Dante\'s Peak ' ,
           low: 63200000
        }, { 
           name: ' The Great Mouse Detective ' ,
           low: 58685412
        }, { 
           name: ' Lost In Space ' ,
           low: 56047317
        }, { 
           name: ' Spy Game ' ,
           low: 53049560
        }, { 
           name: ' The Great Muppet Caper ' ,
           low: 51932573
        }, { 
           name: ' The Cat Returns ' ,
           low: 50864900
        }, { 
           name: ' Fantastic Four ' ,
           low: 47849187
        }, { 
           name: ' Stuart Little 2 ' ,
           low: 46000000
        }, { 
           name: ' Legend of the Guardians: The Owls of Ga\'Hoole ' ,
           low: 39716717
        }, { 
           name: ' The Princess Bride ' ,
           low: 35023296
        }, { 
           name: ' Flushed Away ' ,
           low: 30357126
        }, { 
           name: ' Hugo (film) ' ,
           low: 29770160
        }, { 
           name: ' Don\'t Tell Mom the Babysitter\'s Dead ' ,
           low: 29185657
        }, { 
           name: ' Miami Vice ' ,
           low: 28818556
        }, { 
           name: ' The Secret World of Arrietty ' ,
           low: 28800274
        }, { 
           name: ' Pompeii ' ,
           low: 28469033
        }, { 
           name: ' Alice in Wonderland 1951 ' ,
           low: 27089296
        }, { 
           name: ' The Wild ' ,
           low: 19010667
        }, { 
           name: ' The Prince and the Pauper (1937 film) ' ,
           low: 15498203
        }, { 
           name: ' Wonder Park ' ,
           low: 15149422
        }, { 
           name: ' Sucker Punch ' ,
           low: 14758389
        }, { 
           name: ' The Witches 1990 ' ,
           low: 9007222
        }, { 
           name: ' The Last Unicorn ' ,
           low: 8189219
        }, { 
           name: ' Yellow Submarine (film) ' ,
           low: 7175405
        }, { 
           name: ' Fantastic Mr. Fox ' ,
           low: 6471023
        }, { 
           name: ' Greenland ' ,
           low: 5402370
        }, { 
           name: ' Inkheart ' ,
           low: 2803180
        }]
    }]
});

# Blueprint: Movies that did not make any Profit.

This is the blueprint for creating the eight visualization, movies that did not make any profit. Highcharts will be used to create this graph. 

__Blueprint:__
     
   - The graph used for this visualazation is Highcharts Column chart with negative values series which is found in the Highcharts Demos. Column charts are mostly used to compare categories with different values including negative value, they are very popular and transparant types of charts.
    
 The first approach to this chart is by understanding the format of the code script. Like the previous data visualization this graph is constructed by two different types of code HTML and Javascript. The HTML script is very similar to the previous graph, they allow the column graph to produce negative column and comparison between any particular value of the movie. Closing of the script is similar to the previous script but with a unique name to it self;
                              <figure class="highcharts-figure">
                              <div id="w1"></div> 
                              <p class="highcharts-description">
                              </p>
                              </figure>
The second approach is scripting the javascript section. The javascript section is entirely different to the previous graph, before diving into the javascript code there needs to be data extracted. The names of all the movies that didn't make any profit which will be extracted from the parent dataframe, also the cost, the loss and the revenue of all the movies that did not make any profit.

- There are five major sections in the javascript section that are very critical.
     - 1. The list that is called categories is where all the names of all the movies that were not profitable are scripted. 
                             categories:['Random Hearts','Gods of Egypt','Peter Pan','Children of Men','I Spy','Fantastica: A Boonie Bears','Thirteen Days','Downsizing','Mortal Engines','The Oegieloves','Spanglish','Mighty Joe Young', 'Land of the Lost','Windtalkers',"A Boy's Life",'R.I.P.D.','Soldier','Stealth','The Alamo', 'Renegades']
     
     - 2. The y-axis min, max and steps are very important values that are put in a specific way to allow most of the negative values to be visible, based on how large the other values were;
                              yAxis:{
                              min:-500000,
                              max:180000000,
                              step:50000,
                              },
     
     - 3. The series section has three sub-section;
         - The Cost category is a list consisting of all the amount of money spent to create the movies that were not profitable.
                name:'Cost',
                data:[64000000,140000000,100000000,76000000,70000000,90000000,80000000,
                     68000000,100000000,20000000,75000000,80000000,100000000,115000000,
                     90000000,130000000,75000000,138000000,92000000,77500000]
         - The Revenue category is a list consisting of all the money thta were made but not minus the cost of all the movies not profitable.
                name:'Revenue',
                data:[63200000,138836756,95255485,69845011,60279822,77151096,66554547,54462971,
                      85287417,1065907,54344321,50632037,69548641,77628265,42460000,
                      79076678,14623082,76416746,23911362,1521672]
         - The Loss category is a list showing all the amount of money that fell short, meaning the cost was higher than the revenue giving the loss negitative values. Each movie spent more tahn they anticipated to make. 
                name:'Loss',
                data:[-800000,-1163244,-4744515,-6154989,-9720178,-12848904,-13445453,
                  -13537029,-14712583,-18934093,-20655679,-29367963,-30451359,
                  -37371735,-47540000,-50923322,-60376918,-61583254,-68088638,
                  -75978328]

In [1079]:
# getting the Cost of the movies that had losses
new3 = []
for i in new1[-23:]:
    new3.append(all_actionadventure_info1.Buget[i[0]])
new3

[6240865,
 75000000,
 61088364,
 19853201,
 15892251,
 150000000,
 65000000,
 40000000,
 16968990,
 37269615,
 100000000,
 70000000,
 29579545,
 161484190,
 275000000,
 90000000,
 45000000,
 59577767,
 38000000,
 175000000,
 60000000,
 166152270,
 100000000]

In [1080]:
# getting the Revenue of the movies with losses
new4 = []
for i in new1[-23:]:
    new4.append(all_actionadventure_info1.Total_gross[i[0]])
new4

[6240865,
 72785169,
 56164340,
 14436566,
 10196984,
 142634358,
 56824633,
 31192425,
 8081159,
 27572982,
 89693309,
 58953319,
 17426613,
 148740695,
 260002115,
 65716126,
 17492014,
 31058805,
 8634510,
 139630336,
 11427090,
 89307708,
 7094995]

In [1081]:
# the the amount of money for thr movies with losses
for i in new1[-23:]:
    print(i[1])

0
-2214831
-4924024
-5416635
-5695267
-7365642
-8175367
-8807575
-8887831
-9696633
-10306691
-11046681
-12152932
-12743495
-14997885
-24283874
-27507986
-28518962
-29365490
-35369664
-48572910
-76844562
-92905005

In [1090]:
# the names of the movies with losses
new2[-43:-23]

['Stuart Little 2',
 "Legend of the Guardians: The Owls of Ga'Hoole",
 'The Princess Bride',
 'Flushed Away',
 'Hugo (film)',
 "Don't Tell Mom the Babysitter's Dead",
 'Miami Vice',
 'The Secret World of Arrietty',
 'Pompeii',
 'Alice in Wonderland 1951',
 'The Wild',
 'The Prince and the Pauper (1937 film)',
 'Wonder Park',
 'Sucker Punch',
 'The Witches 1990',
 'The Last Unicorn',
 'Yellow Submarine (film)',
 'Fantastic Mr. Fox',
 'Greenland',
 'Inkheart']

In [1]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="w4"></div> 
    <p class="highcharts-description">
    </p>
</figure>

In [2]:
%%js
Highcharts.chart('w4',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        //name of all the movies 
        categories:['Lost Highway','Lady in the Water','Matilda','Black Snake Moan',
                   'The Straight Story','The Wolfman','Elektra','The House',
                   'Stealing Beauty','Ladybugs','In the Heart of the Sea','The Legend of Hercules',
                   'A Little Princess','National Treasure','The Lone Ranger','K-19: The Widowmaker',
                   'Rebound','Labyrinth','News of the World','King Arthur: Legend of the Sword',
                   'Beyond Borders',"Kiki's Delivery Service",'The Adventures of Pluto Nash'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#b549d0','#660066','#BF5FFF'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[6240865,75000000,61088364,19853201,15892251,150000000,
             65000000,40000000,16968990,37269615,100000000,70000000,
             29579545,161484190,275000000,90000000,45000000,59577767,
             38000000,175000000,60000000,166152270,100000000]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[0,-2214831,-4924024,-5416635,-5695267,-7365642,
             -8175367,-8807575,-8887831,-9696633,-10306691,-11046681,
            -12152932,-12743495,-14997885,-24283874,-27507986,-28518962,
            -29365490,-35369664,-48572910,-76844562,-92905005]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[6240865,72785169,56164340,14436566,10196984,142634358,
             56824633,311924,8081159,27572982,89693309,58953319,
             17426613,148740695,260002115,65716126,17492014,31058805,
             8634510,139630336,11427090,89307708,7094995]
    }]
});

# Blueprint: Top 20 Highest Profitable Movies and Top 20 Lowest Profitable Movies

This is the blueprint for creating the ninth and tenth visualization, Top 20 Highest Profitable Movies and the Top 20 Lowest Profitable Movies. Highcharts will be used to create these garphs.

__Blueprint:__
  - The graph used for these visualization is Highcharts 3D Cylinder Chart for the Top 20 Highest Profitable Movies and Highcharts Chart Rotation Chart Series for thr Top 20 lowest Profitable Movies, which is all found in the highcharts demos. The chart rotation chart series have an Alpha, Beta and Depth angle which can be adjusted to rotate the graph around.
  
    The first approach to this chart is by understanding the format of the code script. Like the previous graph this chart is constructed by two different types of code HTML and Javascript. The HTML section is very similar to the previous graph but the only difference is this HTML code;
         <script src="https://code.highcharts.com/highcharts-3d.js"></script>
         <script src="https://code.highcharts.com/modules/cylinder.js"></script>
    This allows the graphs to be 3D and it also allows it to be cylinder. To close of two script is also similar to the previous script but with a unique name to it self. 
       
       This is for the cylinder graph;
                      <figure class="highcharts-figure">
                      <div id="b1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
                
       This if for the 3D column graph;
                      <figure class="highcharts-figure">
                      <div id="c1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
   The second approach is scripting the javascript section. The javascript section is very simple, brfore that there needs to be some data extracted from the parent dataframe. These are the elements needed to be extracted for this visualazation. For the Top 20 Highest Profitable Movies the name and amount of profit made is needed, for the Top 20 Lowest Profitable Movies the name and amount of profit made in integer of all the movies is needed in that category.
   
 There is just one sub-section in each graph that are particular, the data sub-section in the series section. It is a body of sequenences of list that consist of the name and amount of profit made in integer.
   
   This is from the first graph;
            ['Avatar|1st Highest',2351345279],
            ['The Sound of Music|2nd Highest', 2303109231],
            ['Black Panther|3rd Highest',1148258224]
       
   This is from the second graph;
            [' Miami Vice|170th Highest', 28818556 ],
            [' Space Chimps|171th Highest', 28097693 ],
            [' The Tale of Despereaux|172th Highest', 26957280 ],

Using a for loop to put the top 20 highest profitable movie name and profit in html code which will be pasted in the cell below.

In [1093]:
for i,x in enumerate(range(len(new2[:20]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Snow White and the Seven Dwarfs | 0 th Highest', 7749324763 ],
[' Bambi | 1 th Highest', 4489260987 ],
[' Pinocchio | 2 th Highest', 2219462581 ],
[' E.T. the Extra-Terrestrial | 3 th Highest', 2168030400 ],
[' Titanic | 4 th Highest', 1927488188 ],
[' Jurassic World | 5 th Highest', 1520400637 ],
[' Fantasia | 6 th Highest', 1507787834 ],
[' The Lord of the Rings: The Return of the King | 7 th Highest', 1486843909 ],
[' Harry Potter and the Sorcerer's Stone | 8 th Highest', 1272064256 ],
[' Forrest Gump | 9 th Highest', 1101283862 ],
[' Joker | 10 th Highest', 1019251311 ],
[' The Sixth Sense | 11 th Highest', 992158414 ],
[' Captain Marvel | 12 th Highest', 948061550 ],
[' Skyfall | 13 th Highest', 908561013 ],
[' The Lion King | 14 th Highest', 906914868 ],
[' Aladdin 1992 | 15 th Highest', 899286958 ],
[' Jumanji: Welcome to the Jungle | 16 th Highest', 874496193 ],
[' Harry Potter and the Deathly Hallows: Part I | 17 th Highest', 835431568 ],
[' Spider-Man 2 | 18 th Highest', 820724923 ],
[' The Dark Knight | 19 th Highest', 818045358 ],

In [250]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="httos://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="b4"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [251]:
%%js
new Highcharts.chart('b4',{ //name of graph
    chart:{
        type:'cylinder', // makes graph cylinder
        // adjust the position of graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:16,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Highest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // mkaes the graph one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Highest Profit',
        color:'#CC00FF',// color of cylinders in graph
           data:[
     // names and amount of profit made in integer of the ten most highest profitable movies
            [' Snow White and the Seven Dwarfs | 1st Highest', 7749324763 ],
            [' Bambi | 2nd Highest', 4489260987 ],
            [' Pinocchio | 3rd Highest', 2219462581 ],
            [' E.T. the Extra-Terrestrial | 4th Highest', 2168030400 ],
            [' Titanic | 5th Highest', 1927488188 ],
            [' Jurassic World | 6th Highest', 1520400637 ],
            [' Fantasia | 7th Highest', 1507787834 ],
            [' The Lord of the Rings: The Return of the King | 8th Highest', 1486843909 ],
            [' Harry Potter and the Sorcerer\'s Stone | 9th Highest', 1272064256 ],
            [' Forrest Gump | 10th Highest', 1101283862 ],
            [' Joker | 11th Highest', 1019251311 ],
            [' The Sixth Sense | 12th Highest', 992158414 ],
            [' Captain Marvel | 13th Highest', 948061550 ],
            [' Skyfall | 14th Highest', 908561013 ],
            [' The Lion King | 15th Highest', 906914868 ],
            [' Aladdin 1992 | 16th Highest', 899286958 ],
            [' Jumanji: Welcome to the Jungle | 17th Highest', 874496193 ],
            [' Harry Potter and the Deathly Hallows: Part I | 18th Highest', 835431568 ],
            [' Spider-Man 2 | 19th Highest', 820724923 ],
            [' The Dark Knight | 20th Highest', 818045358 ],
         ]
    }]
        
});

Using a for loop to put the top 20 lowest profitable movie name and profit in html code which will be pasted in the cell below

In [1100]:
for i,x in enumerate(range(len(new2[:]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Snow White and the Seven Dwarfs | 0 th Highest', 7749324763 ],
[' Bambi | 1 th Highest', 4489260987 ],
[' Pinocchio | 2 th Highest', 2219462581 ],
[' E.T. the Extra-Terrestrial | 3 th Highest', 2168030400 ],
[' Titanic | 4 th Highest', 1927488188 ],
[' Jurassic World | 5 th Highest', 1520400637 ],
[' Fantasia | 6 th Highest', 1507787834 ],
[' The Lord of the Rings: The Return of the King | 7 th Highest', 1486843909 ],
[' Harry Potter and the Sorcerer's Stone | 8 th Highest', 1272064256 ],
[' Forrest Gump | 9 th Highest', 1101283862 ],
[' Joker | 10 th Highest', 1019251311 ],
[' The Sixth Sense | 11 th Highest', 992158414 ],
[' Captain Marvel | 12 th Highest', 948061550 ],
[' Skyfall | 13 th Highest', 908561013 ],
[' The Lion King | 14 th Highest', 906914868 ],
[' Aladdin 1992 | 15 th Highest', 899286958 ],
[' Jumanji: Welcome to the Jungle | 16 th Highest', 874496193 ],
[' Harry Potter and the Deathly Hallows: Part I | 17 th Highest', 835431568 ],
[' Spider-Man 2 | 18 th Highest', 820724923 ],
[' The Dark Knight | 19 th Highest', 818045358 ],
[' Beauty and the Beast | 20 th Highest', 817826064 ],
[' Peter Pan 1953 | 21 th Highest', 813660789 ],
[' Ice Age: Continental Drift | 22 th Highest', 784765137 ],
[' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe | 23 th Highest', 773346348 ],
[' Mrs. Doubtfire | 24 th Highest', 753874057 ],
[' The Rescuers | 25 th Highest', 750988612 ],
[' Deadpool | 26 th Highest', 724612155 ],
[' The Parent Trap | 27 th Highest', 716573581 ],
[' The Hobbit: The Desolation of Smaug | 28 th Highest', 710366855 ],
[' Spider-Man | 29 th Highest', 682706375 ],
[' Jumanji: The Next Level | 30 th Highest', 668100000 ],
[' Harry Potter and the Prisoner of Azkaban | 31 th Highest', 666907323 ],
[' Inception | 32 th Highest', 666137188 ],
[' The Black Stallion | 33 th Highest', 648407405 ],
[' The Da Vinci Code | 34 th Highest', 642820459 ],
[' The Hunger Games: Mockingjay - Part 1 | 35 th Highest', 641575131 ],
[' Gravity | 36 th Highest', 623192705 ],
[' Wonder Woman 1984 | 37 th Highest', 621847012 ],
[' Monsters, Inc | 38 th Highest', 619409043 ],
[' The Hunger Games | 39 th Highest', 616394724 ],
[' The Passion of the Christ | 40 th Highest', 581486736 ],
[' Up | 41 th Highest', 560099082 ],
[' American Beauty | 42 th Highest', 542397137 ],
[' Dawn of the Planet of the Apes | 43 th Highest', 540644566 ],
[' The Amazing Spider-Man | 44 th Highest', 537890267 ],
[' Fifty Shades of Grey | 45 th Highest', 529651467 ],
[' Logan | 46 th Highest', 522021436 ],
[' Oliver! (film) | 47 th Highest', 517874560 ],
[' Ted (film) | 48 th Highest', 499368315 ],
[' Thor: The Dark World | 49 th Highest', 494602516 ],
[' The Hunger Games: Mockingjay - Part 2 | 50 th Highest', 488986787 ],
[' American Sniper | 51 th Highest', 488626372 ],
[' War of the Worlds | 52 th Highest', 474836535 ],
[' Hancock | 53 th Highest', 474234272 ],
[' Night at the Museum | 54 th Highest', 469446407 ],
[' Night at the Museum | 55 th Highest', 464480841 ],
[' Fantastic Beasts: The Crimes of Grindelwald | 56 th Highest', 455000000 ],
[' Cars | 57 th Highest', 452630685 ],
[' Hook (film) | 58 th Highest', 449502590 ],
[' Iron Man | 59 th Highest', 445366247 ],
[' Cinderella | 60 th Highest', 439551353 ],
[' Catch Me If You Can | 61 th Highest', 436454868 ],
[' I am Legend | 62 th Highest', 435532684 ],
[' The Hangover | 63 th Highest', 433812793 ],
[' Ready Player One | 64 th Highest', 429290136 ],
[' National Treasure: Book of Secrets | 65 th Highest', 424970494 ],
[' 2001: A Space Odyssey | 66 th Highest', 424830090 ],
[' Indecent Proposal | 67 th Highest', 420356209 ],
[' Lucy | 68 th Highest', 419863600 ],
[' Sleeping Beauty | 69 th Highest', 410990117 ],
[' Sherlock Holmes: A Game of Shadows | 70 th Highest', 410663443 ],
[' Sherlock Holmes | 71 th Highest', 408438212 ],
[' Iron Man | 72 th Highest', 399171547 ],
[' The Revenant | 73 th Highest', 397950503 ],
[' Spirited Away | 74 th Highest', 384145992 ],
[' Jason Bourne | 75 th Highest', 376273243 ],
[' Ocean's Eleven | 76 th Highest', 365728529 ],
[' Slumdog Millionaire | 77 th Highest', 363410113 ],
[' Dunkirk | 78 th Highest', 349837368 ],
[' Mulan 1998 | 79 th Highest', 346093329 ],
[' Cast Away | 80 th Highest', 342230516 ],
[' Troy | 81 th Highest', 334161265 ],
[' Taken 2 | 82 th Highest', 332807404 ],
[' Wreck-It Ralph | 83 th Highest', 331511521 ],
[' Enchanted | 84 th Highest', 329771510 ],
[' Gremlins | 85 th Highest', 320812364 ],
[' Troy | 86 th Highest', 312409852 ],
[' Gone Girl | 87 th Highest', 308330363 ],
[' Men in Black 2 | 88 th Highest', 301767803 ],
[' Big (film) | 89 th Highest', 301709188 ],
[' Pearl Harbor | 90 th Highest', 297739855 ],
[' The Ring | 91 th Highest', 292820831 ],
[' The Wolf of Wall Street | 92 th Highest', 292000694 ],
[' Oz the Great and Powerful | 93 th Highest', 290359051 ],
[' X-Men 2 | 94 th Highest', 281875536 ],
[' 22 Jump Street | 95 th Highest', 281333876 ],
[' Prometheus | 96 th Highest', 273354469 ],
[' Live Free or Die Hard | 97 th Highest', 272288147 ],
[' The Chronicles of Narnia: The Voyage of the Dawn Treader | 98 th Highest', 263186950 ],
[' Hannibal | 99 th Highest', 263100280 ],
[' The Goonies | 100 th Highest', 259731909 ],
[' Bridesmaids | 101 th Highest', 255883523 ],
[' Inglourious Basterds | 102 th Highest', 246915264 ],
[' The Smurfs 2 | 103 th Highest', 238547523 ],
[' Now You See Me 2 | 104 th Highest', 238325007 ],
[' Now You See Me 2 | 105 th Highest', 238325007 ],
[' The SpongeBob Movie: Sponge Out of Water | 106 th Highest', 237013181 ],
[' Penguins of Madagascar | 107 th Highest', 234942531 ],
[' Air Force One | 108 th Highest', 230268353 ],
[' Knives Out | 109 th Highest', 229400000 ],
[' Night at the Museum: Secret of the Tomb | 110 th Highest', 226756621 ],
[' Batman Begins | 111 th Highest', 223661946 ],
[' Shutter Island | 112 th Highest', 219461782 ],
[' Independence Day: Resurgence | 113 th Highest', 219169424 ],
[' Trolls | 114 th Highest', 219150134 ],
[' My Girl | 115 th Highest', 207308101 ],
[' The Absent-Minded Professor | 116 th Highest', 204370759 ],
[' A Man for All Seasons | 117 th Highest', 200679654 ],
[' Sex and the City 2 | 118 th Highest', 199680778 ],
[' Journey to the Center of the Earth | 119 th Highest', 198180937 ],
[' The Help | 120 th Highest', 188120004 ],
[' Tomb Raider | 121 th Highest', 183477501 ],
[' The Addams Family | 122 th Highest', 179044905 ],
[' Sully | 123 th Highest', 178524556 ],
[' Dumbo | 124 th Highest', 175004422 ],
[' Fantastic Four: Rise of the Silver Surfer | 125 th Highest', 169480691 ],
[' The Legend of Tarzan | 126 th Highest', 168902025 ],
[' The Italian Job | 127 th Highest', 167126930 ],
[' Nanny McPhee | 128 th Highest', 165313810 ],
[' The Land Before Time | 129 th Highest', 162877160 ],
[' The King and I | 130 th Highest', 162796250 ],
[' The Princess and the Frog | 131 th Highest', 162045765 ],
[' Mean Girls | 132 th Highest', 157734111 ],
[' Click | 133 th Highest', 155185089 ],
[' Ferris Bueller's Day Off | 134 th Highest', 152615465 ],
[' Bridge to Terabithia | 135 th Highest', 151775880 ],
[' Hercules | 136 th Highest', 144819862 ],
[' Alien: Covenant | 137 th Highest', 141521247 ],
[' Edward Scissorhands | 138 th Highest', 134539441 ],
[' Finding Neverland | 139 th Highest', 129531208 ],
[' My Neighbor Totoro | 140 th Highest', 128066132 ],
[' Christopher Robin | 141 th Highest', 122504758 ],
[' Gulliver's Travels | 142 th Highest', 120017848 ],
[' You Don't Mess With the Zohan | 143 th Highest', 112910991 ],
[' Hulk | 144 th Highest', 108075434 ],
[' Charlie's Angels: Full Throttle | 145 th Highest', 107200000 ],
[' Charlie's Angels: Full Throttle | 146 th Highest', 107200000 ],
[' Daddy Day Care | 147 th Highest', 104285587 ],
[' AVP: Alien Vs. Predator | 148 th Highest', 102543519 ],
[' Hollow Man | 149 th Highest', 101200000 ],
[' Atlantis: The Lost Empire | 150 th Highest', 96049020 ],
[' The Rookie 2002 | 151 th Highest', 86520319 ],
[' Charlotte's Web | 152 th Highest', 86030539 ],
[' Whisper of the Heart | 153 th Highest', 84139368 ],
[' The Prestige | 154 th Highest', 84100704 ],
[' 13 Going on 30 | 155 th Highest', 82900533 ],
[' Zero Dark Thirty | 156 th Highest', 82112435 ],
[' Spotlight (film) | 157 th Highest', 78690254 ],
[' Nim's Island | 158 th Highest', 78258481 ],
[' Clueless | 159 th Highest', 65155986 ],
[' Dante's Peak | 160 th Highest', 63200000 ],
[' The Great Mouse Detective | 161 th Highest', 58685412 ],
[' Lost In Space | 162 th Highest', 56047317 ],
[' Spy Game | 163 th Highest', 53049560 ],
[' The Great Muppet Caper | 164 th Highest', 51932573 ],
[' The Cat Returns | 165 th Highest', 50864900 ],
[' Fantastic Four | 166 th Highest', 47849187 ],
[' Stuart Little 2 | 167 th Highest', 46000000 ],
[' Legend of the Guardians: The Owls of Ga'Hoole | 168 th Highest', 39716717 ],
[' The Princess Bride | 169 th Highest', 35023296 ],
[' Flushed Away | 170 th Highest', 30357126 ],
[' Hugo (film) | 171 th Highest', 29770160 ],
[' Don't Tell Mom the Babysitter's Dead | 172 th Highest', 29185657 ],
[' Miami Vice | 173 th Highest', 28818556 ],
[' The Secret World of Arrietty | 174 th Highest', 28800274 ],
[' Pompeii | 175 th Highest', 28469033 ],
[' Alice in Wonderland 1951 | 176 th Highest', 27089296 ],
[' The Wild | 177 th Highest', 19010667 ],
[' The Prince and the Pauper (1937 film) | 178 th Highest', 15498203 ],
[' Wonder Park | 179 th Highest', 15149422 ],
[' Sucker Punch | 180 th Highest', 14758389 ],
[' The Witches 1990 | 181 th Highest', 9007222 ],
[' The Last Unicorn | 182 th Highest', 8189219 ],
[' Yellow Submarine (film) | 183 th Highest', 7175405 ],
[' Fantastic Mr. Fox | 184 th Highest', 6471023 ],
[' Greenland | 185 th Highest', 5402370 ],
[' Inkheart | 186 th Highest', 2803180 ],
[' Lost Highway | 187 th Highest', 0 ],
[' Lady in the Water | 188 th Highest', -2214831 ],
[' Matilda | 189 th Highest', -4924024 ],
[' Black Snake Moan | 190 th Highest', -5416635 ],
[' The Straight Story | 191 th Highest', -5695267 ],
[' The Wolfman | 192 th Highest', -7365642 ],
[' Elektra | 193 th Highest', -8175367 ],
[' The House | 194 th Highest', -8807575 ],
[' Stealing Beauty | 195 th Highest', -8887831 ],
[' Ladybugs | 196 th Highest', -9696633 ],
[' In the Heart of the Sea | 197 th Highest', -10306691 ],
[' The Legend of Hercules | 198 th Highest', -11046681 ],
[' A Little Princess | 199 th Highest', -12152932 ],
[' National Treasure | 200 th Highest', -12743495 ],
[' The Lone Ranger | 201 th Highest', -14997885 ],
[' K-19: The Widowmaker | 202 th Highest', -24283874 ],
[' Rebound | 203 th Highest', -27507986 ],
[' Labyrinth | 204 th Highest', -28518962 ],
[' News of the World | 205 th Highest', -29365490 ],
[' King Arthur: Legend of the Sword | 206 th Highest', -35369664 ],
[' Beyond Borders | 207 th Highest', -48572910 ],
[' Kiki's Delivery Service | 208 th Highest', -76844562 ],
[' The Adventures of Pluto Nash | 209 th Highest', -92905005 ],

In [248]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="c4"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [249]:
%%js
Highcharts.chart('c4',{ // name of graph
    chart:{
        type:'column', // makes the graph column
       // adjusting the graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:25,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Lowest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // allows the graph to be one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Lowest Profits',
        color :'#91219E', // the color of the graph
           data:[
// the name and amount of profit made in integer of the least most profitable movies
            [' Stuart Little 2 | 167th Highest', 46000000 ],
            [' Legend of the Guardians: The Owls of Ga\'Hoole | 168th Highest', 39716717 ],
            [' The Princess Bride | 169th Highest', 35023296 ],
            [' Flushed Away | 170th Highest', 30357126 ],
            [' Hugo (film) | 171th Highest', 29770160 ],
            [' Don\'t Tell Mom the Babysitter\'s Dead | 172th Highest', 29185657 ],
            [' Miami Vice | 173th Highest', 28818556 ],
            [' The Secret World of Arrietty | 174th Highest', 28800274 ],
            [' Pompeii | 175th Highest', 28469033 ],
            [' Alice in Wonderland 1951 | 176th Highest', 27089296 ],
            [' The Wild | 177th Highest', 19010667 ],
            [' The Prince and the Pauper (1937 film) | 178th Highest', 15498203 ],
            [' Wonder Park | 179th Highest', 15149422 ],
            [' Sucker Punch | 180th Highest', 14758389 ],
            [' The Witches 1990 | 181th Highest', 9007222 ],
            [' The Last Unicorn | 182th Highest', 8189219 ],
            [' Yellow Submarine (film) | 183th Highest', 7175405 ],
            [' Fantastic Mr. Fox | 184th Highest', 6471023 ],
            [' Greenland | 185th Highest', 5402370 ],
            [' Inkheart | 186th Highest', 2803180 ]
         ]
    }]
        
});

# Blueprint: What Movie is the most Successful.

Just because a movie has made the most profit dosen't mean it is more profitable than a movie that made less profit and or revenue. These were the five main factors that were used to better understand what movie was the most successful. The cost, the revenue, the profit, the gross profit margin percentage which is how much of the revenue is each movie walking away in percentageand the profit percenatge by cost which is comparing the profit with the cost in percentage. 
 
This is the blueprint for creating the elevnth, twelith, thirthith and fourthith visualization. Highcharts will be used to create these graphs.  

__Blueprint:__
   - The factors are split into half when it comes to what type of graph that will be used to analyze the data. The profit, revenue and cost varaiables will be analyzed using highcharts Combination Chart. This chart allows different combinations of senories to be combined in a single chart. This chart is a set of column series overlaid by a line and a pie chart. The line in Highchart was designed to illustrate the column averages while the pie is illustrating the column totals. However in this project the pie sereis will not be used and there will be two column series overlaid by a line series. The two columns will be revenue and profit, the line series will be the cost of all the movies in the blueprint. Like every other graph that used Highchart visualization, they all have two different types of code, HTML and javascript. The HTML section is very similar to all the previous graphs expect two main factors, the HTML code that allows the combination graph to be displayed is;
          <script src="https://code.highcharts.com/modules/series-label.js"></script>
          <script type="text/javascript" src="js/script.js"></script>
The other factors are the two different divs id for the combination chart;
          <div id="x1" display; inline-block></div>
          <div id="no1" display; inline-block></div>
 These are the names of the two combination chart that analyze ten movies each of the Top 20 Most     Profitable Movies.The javascript section for these graphs consist of four main subsection. The categories, the two types in the series section that are columns and the type in the series section that is spline. The categories subsection is a list of all the names of the movies that will be analyzed. The two types in the in the series subsection that are columns are the profit and revenue of all the movies and the third type in the spline series subsection is the cost of all the movies. 
     
     
                series:[{
                   type:'column',
                   color:"#111E6C",
                   name:'Profit',
                   data:                                  
                   [2351345279,2303109231,1148258224, 1135772799,1015392272,984846267,912044677,894039076,
          890069413,878000000]
      },{
          type:'column'
          color:Highcharts.getOptions().colors[1],
          name:'Revenue',
          data:[2776345279,2366000000,1348258224,
          1305772799,1215392272,1234846267,1027044677,1104039076,1140069413,1078000000]
     },{
          type:'spline',
          color:'gold',
          name:'Cost',
          data:[425000000,62890769,200000000,170000000,200000000,250000000,115000000,210000000,
                    250000000,200000000],


   The other factors are the two different divs id for the column chart;
            
            <div id="n1" display; inline-block></div>
            <div id="xo1" display; inline-block></div>

   The Gross Profit Margin Percentage and the Profit Percentage by Cost will all be analyzed using        highcharts combination chart but with only column. The two column will be The Percentage of Gross      Profit Margin and Profit by Cost of each movie.
   
   The javascript section for the columns chart consist of the category subsection which is the names      of all the movies. 
      
      categories:['Zootopia| 11th Highest',
      'Finding Nemo| 12th Highest',
      'The Jungle Book| 13th Highest',
      'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
      'Ice Age: Dawn of the Dinosaurs| 15th Highest',
      'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
      'The Hobbit: The Battle of the Five Armies| 17th Highest',
      'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
      'Inside Out| 19th Highest',
      'Deadpool 2| 20th Highest']

   It also consist of the series subsection that has two factors, the type column which is where the      gross profit margin percentage and profit by cost is scripted.
      
      series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[85.0, 97.0, 85.0, 87.0, 84.0, 80.0, 89.0, 81.0, 78.0, 81.0]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[553.0, 3662.0, 574.0, 668.0, 508.0, 394.0, 793.0, 426.0, 356.0, 439.0]
       }]

In [1119]:
#getting the profit of the movie
for i in new1[10:20]:
    print(all_actionadventure_info1.Profit[i[0]])

1019251311
992158414
948061550
908561013
906914868
899286958
874496193
835431568
820724923
818045358

In [1118]:
#getting the revenue of the movie
for i in new1[10:20]:
    print(all_actionadventure_info1.Total_gross[i[0]])

1074251311
1054873240
1123061550
1108561013
986214868
952175079
964496193
960431568
1099589817
1003045358

In [1117]:
#getting the cost of the movie
for i in new1[10:20]:
    print(all_actionadventure_info1.Buget[i[0]])

55000000
62714826
175000000
200000000
79300000
52888121
90000000
125000000
278864894
185000000

In [1116]:
#getting profit percent by cost of the top 20 highest most profitable movie
new5 = []
for i in new1:
    new5.append(round(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Buget[i[0]]
         *100,0))
new5[10:20]

[1853.0, 1582.0, 542.0, 454.0, 1144.0, 1700.0, 972.0, 668.0, 294.0, 442.0]

In [1115]:
#getting gross profit margin percent of the top 20 highest most profitable movie
new6 = []
for i in new1:
    new6.append(round(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Total_gross[i[0]]
         *100,0))
new6[10:20]

[95.0, 94.0, 84.0, 82.0, 92.0, 94.0, 91.0, 87.0, 75.0, 82.0]

Using a for loop to get the names of the highest most profitable and putting it into html code

In [1107]:
for i,x in enumerate(new2[:21]):
    print("'"+new2[i]+'|',i,'th','Highest'+"',")

'Snow White and the Seven Dwarfs| 0 th Highest',
'Bambi| 1 th Highest',
'Pinocchio| 2 th Highest',
'E.T. the Extra-Terrestrial| 3 th Highest',
'Titanic| 4 th Highest',
'Jurassic World| 5 th Highest',
'Fantasia| 6 th Highest',
'The Lord of the Rings: The Return of the King| 7 th Highest',
'Harry Potter and the Sorcerer's Stone| 8 th Highest',
'Forrest Gump| 9 th Highest',
'Joker| 10 th Highest',
'The Sixth Sense| 11 th Highest',
'Captain Marvel| 12 th Highest',
'Skyfall| 13 th Highest',
'The Lion King| 14 th Highest',
'Aladdin 1992| 15 th Highest',
'Jumanji: Welcome to the Jungle| 16 th Highest',
'Harry Potter and the Deathly Hallows: Part I| 17 th Highest',
'Spider-Man 2| 18 th Highest',
'The Dark Knight| 19 th Highest',
'Beauty and the Beast| 20 th Highest',

In [254]:
%%HTML
<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="x4" display; inline-block></div>
    <div id="n4" display; inline-block></div>
    <div id="no4" display; inline-block></div>
    <div id="xo4" display; inline-block></div>
    <p class="highcharts-description">
    </p>
</figure>

In [255]:
%%js
Highcharts.chart('x4',{ // name of graph
    title:{
        text:"What Movie Is The Most Successful?"
    },
    xAxis:{
        // name of movies
        categories:['Snow White and the Seven Dwarfs| 1st Highest',
                   'Bambi| 2nd Highest',
                   'Pinocchio| 3rd Highest',
                   'E.T. the Extra-Terrestrial| 4th Highest',
                   'Titanic| 5th Highest',
                   'Jurassic World| 6th Highest',
                   'Fantasia| 7th Highest',
                   'The Lord of the Rings: The Return of the King| 8th Highest',
                   'Harry Potter and the Sorcerer\'s Stone| 9th Highest',
                   'Forrest Gump| 10th Highest'],
        crosshair:{
            // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column', // makes graph to be colunm 
        color:"#800080",// color of colunm
        name:'Profit', // name of colunm
        // profit of each movie in integer 
        data:[7749324763,4489260987,2219462581,2168030400,1927488188,
              1520400637,1507787834,1486843909,1272064256,1101283862]
    },{
        type:'column',// makes graph to be colunm
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[7777009428,4503679483,2267836323,2197125900,2127488188,
             1670400637,1550207885,1620373792,1459186382,1198221927]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost', // name of spline
        // cost of each movie in integer
        data:[27684665,14418496,48373742,29095500,200000000,
             150000000,42420051,133529883,187122126,96938065],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [256]:
%%js
Highcharts.chart('n4',{ //name of graph
        title:{
            text:""
        },
        xAxis:{
        // name of movies 
           categories:['Snow White and the Seven Dwarfs| 1st Highest',
                   'Bambi| 2nd Highest',
                   'Pinocchio| 3rd Highest',
                   'E.T. the Extra-Terrestrial| 4th Highest',
                   'Titanic| 5th Highest',
                   'Jurassic World| 6th Highest',
                   'Fantasia| 7th Highest',
                   'The Lord of the Rings: The Return of the King| 8th Highest',
                   'Harry Potter and the Sorcerer\'s Stone| 9th Highest',
                   'Forrest Gump| 10th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#EE82EE',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
           // Gross Profit Margin Percentage of each movie in integer
           data:[100.0, 100.0, 98.0, 99.0, 91.0, 91.0, 97.0, 92.0, 87.0, 92.0]
       },{
           type:'column',// makes graph to be colunm
           color:'#B452CD',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[27991.0,1135.0,4588.0,7451.0,964.0,1014.0,3554.0,1113.0,680.0,1136.0]
       }]  
    
   });

In [257]:
%%js
Highcharts.chart('no4',{ //name of graph
    title:{
        text:""
    },
    xAxis:{
        // name of movies 
        categories:['Joker| 11th Highest',
                   'The Sixth Sense| 12th Highest',
                   'Captain Marvel| 13th Highest',
                   'Skyfall| 14th Highest',
                   'The Lion King| 15th Highest',
                   'Aladdin 1992| 16th Highest',
                   'Jumanji: Welcome to the Jungle| 17th Highest',
                   'Harry Potter and the Deathly Hallows: Part I| 18th Highest',
                   'Spider-Man 2| 19th Highest',
                   'The Dark Knight| 20th Highest'],
        crosshair:{
             // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',// makes graph  colunm 
        color:'#800080',// color of colunm
        name:'Profit',// name of column
        // profit of each movie in integer 
        data:[1019251311,992158414,948061550,908561013,906914868,
              899286958,874496193,835431568,820724923,818045358]
    },{
        type:'column',// makes graph  colunm 
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[1074251311,1054873240,1123061550,1108561013,986214868,
             952175079,964496193,960431568,1099589817,1003045358]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost',// name of spline
        // cost of each movie in integer
        data:[55000000,62714826,175000000,200000000,79300000,
             52888121,90000000,125000000,278864894,185000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [258]:
%%js
Highcharts.chart('xo4',{//name of graph
        title:{
            text:""
        },
        xAxis:{
           // name of movies 
           categories:['Joker| 11th Highest',
                   'The Sixth Sense| 12th Highest',
                   'Captain Marvel| 13th Highest',
                   'Skyfall| 14th Highest',
                   'The Lion King| 15th Highest',
                   'Aladdin 1992| 16th Highest',
                   'Jumanji: Welcome to the Jungle| 17th Highest',
                   'Harry Potter and the Deathly Hallows: Part I| 18th Highest',
                   'Spider-Man 2| 19th Highest',
                   'The Dark Knight| 20th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
            // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#EE82EE',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
          // Gross Profit Margin Percentage of each movie in integer
           data:[95.0, 94.0, 84.0, 82.0, 92.0, 94.0, 91.0, 87.0, 75.0, 82.0]
       },{
           type:'column',// makes graph to be colunm 
           color:'#B452CD',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[1853.0, 1582.0, 542.0, 454.0, 1144.0, 1700.0, 972.0, 668.0, 294.0, 442.0]
       }]  
    
   });

# Blueprint: Number of Tickets Sold.

This analysis objective is to axknowledge what system rating that best suit this genre, this allows the ideology of what kind of audience is drawn to this genre, to specify the audience and make them the target focus. This is the blueprint for creating the last visualization of this project, Highcharts will be used to create this graph.

__Blueprint:__
   - The graph used for this visualization is a Highchart Donut chart, it is basically a hallow pie chart which is commonly referred to as a donut charts. This pie charts also ahs an inner chart resulting in a hierachical type of visualization.
   - The first approach th this chart is the HTML section whcih is very simple, it has the div id which is where the graph is named and the style and height should be chosen.
               <div id='hraph2' style="height:700px"></div>
   - The second approach is the javascript code, it is divided into two sections the inner pie and the outer pie. The inner pie shows how much each sytem ratings occupies the most total tickets sold in percentage comparied to the total tickest sold in the whole entire parent dataframe '_all_actionadventure_info1_'. The outer pie shows the individule movies in the category the amount of tickets they sold.
        - <u>__Javascript Section__</u>:
         
             -<u>_First Section_</u>: The first section is a list called data it has consist of the name of the system ratings and the percenatge of tickets sold compared to the total of tickets sold. The color and the sliced adjustments and it also has the adjustments of the size of the ring pie.
                      data:[{
                  name:'System Rating: R',
                  y:28.0,
                  sliced:true,
                  color: '#4682B4',}
            
            -<u>_Second Section_</u>: The second section is a list also called data it requires the name of all the movies, the amount of tickest they sold , the option to slice that section and the color of the slice .       
                     data:[{ 
               name: ' Avatar ' ,
               y: 213565021 ,
               sliced:true,
               selected: true,
               color:"#4682B4",}

In [274]:
# getting the number of tickets sold in the r-rated category
var = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var.append(no_tickets[i])
len(var)

42

In [275]:
# getting the name of the r-rated movies 
var1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var1.append(all_actionadventure_info1['Name'][i])
len(var1)

42

In [276]:
# getting the profit of thr r-rated movies
var2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var2.append(all_actionadventure_info1['Profit'][i])
len(var2)

42

Using a for loop to put the name and the number of tickets sold in the R-rated genre in html code which will be pasted in the cell below.

In [277]:
for i,x in enumerate(range(len(var))):
    print('         },{ \n           name:',"'",var1[i],"'",','+'\n           y:',var[i],','+'\n           sliced:true,'+'\n           color:"#8E388E",')

         },{
           name: ' Oz the Great and Powerful ' ,
           y: 37719927 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Dumbo ' ,
           y: 26538802 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Wreck-It Ralph ' ,
           y: 38193194 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Hunger Games: Mockingjay - Part 2 ' ,
           y: 49922061 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Chronicles of Narnia: The Voyage of the Dawn Treader ' ,
           y: 32168227 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Pearl Harbor ' ,
           y: 34556912 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' I am Legend ' ,
           y: 45040976 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Troy ' ,
           y: 37243174 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Wolfman ' ,
           y: 10971874 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Spider-Man ' ,
           y: 63208183 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' War of the Worlds ' ,
           y: 46679733 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Night at the Museum: Secret of the Tomb ' ,
           y: 27212048 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Fantastic Four ' ,
           y: 12911476 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Alien: Covenant ' ,
           y: 18347788 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Cinderella ' ,
           y: 41119335 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Hollow Man ' ,
           y: 14707692 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Hannibal ' ,
           y: 26930791 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Cast Away ' ,
           y: 32863886 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The SpongeBob Movie: Sponge Out of Water ' ,
           y: 23924091 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Logan ' ,
           y: 47617034 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Spotlight (film) ' ,
           y: 7591558 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Lucy ' ,
           y: 35297200 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Revenant ' ,
           y: 40996193 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Prometheus ' ,
           y: 31027267 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Fifty Shades of Grey ' ,
           y: 43819344 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Troy ' ,
           y: 38262296 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Hangover ' ,
           y: 36062523 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Ted (film) ' ,
           y: 42259101 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' American Sniper ' ,
           y: 42109721 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Joker ' ,
           y: 82634716 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Black Snake Moan ' ,
           y: 1110505 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Deadpool ' ,
           y: 60200935 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Indecent Proposal ' ,
           y: 37700742 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Gone Girl ' ,
           y: 28410028 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' American Beauty ' ,
           y: 43556578 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Lost Highway ' ,
           y: 480067 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Wolf of Wall Street ' ,
           y: 30153900 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Bridesmaids ' ,
           y: 22183348 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' 22 Jump Street ' ,
           y: 25487221 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' The Passion of the Christ ' ,
           y: 47037441 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Slumdog Millionaire ' ,
           y: 29108470 ,
           sliced:true,
           color:"#8E388E",
         },{
           name: ' Stealing Beauty ' ,
           y: 621628 ,
           sliced:true,
           color:"#8E388E",

In [278]:
# getting the number of tickets sold in the NR-rated category
var3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var3.append(no_tickets[i])
len(var3)

42

In [279]:
# getting the name of the NR-rated movies 
var4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var4.append(all_actionadventure_info1['Name'][i])
len(var4)

42

In [280]:
# getting the profit of thr NR-rated movies
var5 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var5.append(all_actionadventure_info1['Profit'][i])
len(var5)

42

Using a for loop to put the name and the number of tickets sold in the NR-rated genre in html code which will be pasted in the cell below.

In [281]:
for i,x in enumerate(range(len(var4))):
    print('         },{ \n           name:',"'",var4[i],"'",','+'\n           y:',var3[i],',','\n           sliced:true,'+'\n           color:"#FF00FF",')

         },{
           name: ' The Lone Ranger ' ,
           y: 20000163 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' The Hobbit: The Desolation of Smaug ' ,
           y: 73874373 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Iron Man ' ,
           y: 45013196 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' The Legend of Tarzan ' ,
           y: 26838617 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' King Arthur: Legend of the Sword ' ,
           y: 10740795 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Dawn of the Planet of the Apes ' ,
           y: 54664967 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Independence Day: Resurgence ' ,
           y: 29551494 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Hancock ' ,
           y: 48018021 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Flushed Away ' ,
           y: 13796702 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Men in Black 2 ' ,
           y: 33982139 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Hulk ' ,
           y: 18851956 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Miami Vice ' ,
           y: 12601427 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Charlie's Angels: Full Throttle ' ,
           y: 17476923 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' The Smurfs 2 ' ,
           y: 26811348 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Ice Age: Continental Drift ' ,
           y: 67674241 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Now You See Me 2 ' ,
           y: 25255770 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Penguins of Madagascar ' ,
           y: 28226349 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           y: 61300563 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           y: 73879351 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' X-Men 2 ' ,
           y: 31298118 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           y: 41204880 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Charlie's Angels: Full Throttle ' ,
           y: 17476923 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Gulliver's Travels ' ,
           y: 17847527 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Live Free or Die Hard ' ,
           y: 29406781 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Wonder Park ' ,
           y: 8857648 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Sex and the City 2 ' ,
           y: 22667752 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Sherlock Holmes ' ,
           y: 38341401 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Atlantis: The Lost Empire ' ,
           y: 14311463 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Now You See Me 2 ' ,
           y: 25255770 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Tomb Raider ' ,
           y: 21036731 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Ocean's Eleven ' ,
           y: 34671425 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Air Force One ' ,
           y: 24251412 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Click ' ,
           y: 18283468 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Shutter Island ' ,
           y: 23035522 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Lost In Space ' ,
           y: 10465178 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' The Wild ' ,
           y: 7616205 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Pompeii ' ,
           y: 8343772 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' The Lion King ' ,
           y: 75862682 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Christopher Robin ' ,
           y: 15192674 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Lady in the Water ' ,
           y: 5598859 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Sucker Punch ' ,
           y: 6904491 ,
           sliced:true,
           color:"#FF00FF",
         },{
           name: ' Inglourious Basterds ' ,
           y: 24378097 ,
           sliced:true,
           color:"#FF00FF",

In [282]:
# getting the number of tickets sold in the pg-rated category
var6 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var6.append(no_tickets[i])
len(var6)

42

In [283]:
# getting the name of the pg-rated movies 
var7 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var7.append(all_actionadventure_info1['Name'][i])
len(var7)

42

In [284]:
# getting the profit of thr pg-rated movies
var8 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var8.append(all_actionadventure_info1['Profit'][i])
len(var8)

42

Using a for loop to put the name and the number of tickets sold in the PG-rated genre in html code which will be pasted in the cell below.

In [285]:
for i,x in enumerate(range(len(var7))):
    print('         },{ \n           name:',"'",var7[i],"'",','+'\n           y:',var6[i],',','\n           sliced:true,'+'\n           color:"#990099",')

         },{
           name: ' Trolls ' ,
           y: 26473087 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Dante's Peak ' ,
           y: 13707692 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Night at the Museum ' ,
           y: 44572801 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Legend of the Guardians: The Owls of Ga'Hoole ' ,
           y: 10747440 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' In the Heart of the Sea ' ,
           y: 6899485 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' You Don't Mess With the Zohan ' ,
           y: 15608538 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' K-19: The Widowmaker ' ,
           y: 5055087 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' AVP: Alien Vs. Predator ' ,
           y: 13272578 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Legend of Hercules ' ,
           y: 4534871 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Elektra ' ,
           y: 4371126 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Daddy Day Care ' ,
           y: 12637353 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Beyond Borders ' ,
           y: 879007 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Zero Dark Thirty ' ,
           y: 10354803 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Taken 2 ' ,
           y: 29062108 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Journey to the Center of the Earth ' ,
           y: 18706226 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Rebound ' ,
           y: 1345540 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The House ' ,
           y: 2399417 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Fantastic Mr. Fox ' ,
           y: 3574694 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Harry Potter and the Sorcerer's Stone ' ,
           y: 112245106 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Labyrinth ' ,
           y: 2389139 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Nim's Island ' ,
           y: 9549512 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Spirited Away ' ,
           y: 31658196 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Hugo (film) ' ,
           y: 14290012 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' My Girl ' ,
           y: 18193017 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Inkheart ' ,
           y: 4831014 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Enchanted ' ,
           y: 33806579 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Hook (film) ' ,
           y: 45059576 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Bridge to Terabithia ' ,
           y: 13660842 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Goonies ' ,
           y: 23594694 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           y: 78440167 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Night at the Museum ' ,
           y: 44190834 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Parent Trap ' ,
           y: 57046433 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' National Treasure ' ,
           y: 11441592 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Princess Bride ' ,
           y: 5595307 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' National Treasure: Book of Secrets ' ,
           y: 45597570 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Up ' ,
           y: 56546083 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' The Witches 1990 ' ,
           y: 2440691 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' E.T. the Extra-Terrestrial ' ,
           y: 169009685 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Nanny McPhee ' ,
           y: 12979669 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Big (film) ' ,
           y: 26333670 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Matilda ' ,
           y: 4320334 ,
           sliced:true,
           color:"#990099",
         },{
           name: ' Finding Neverland ' ,
           y: 12681853 ,
           sliced:true,
           color:"#990099",

In [286]:
# getting the number of tickets sold in the g-rated category
var9 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var9.append(no_tickets[i])
len(var9)

42

In [287]:
# getting the name of the g-rated movies
var10 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var10.append(all_actionadventure_info1['Name'][i])
len(var10)

42

In [288]:
# getting the profit of thr g-rated movies
var11 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var11.append(all_actionadventure_info1['Profit'][i])
len(var11)

42

Using a for loop to put the name and the number of tickets sold in the G-rated genre in html code which will be pasted in the cell below.

In [289]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var10[i],"'",','+'\n           y:',var9[i],',','\n           sliced:true,'+'\n           color:"#820BBB",')

         },{
           name: ' The Amazing Spider-Man ' ,
           y: 58299251 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Dunkirk ' ,
           y: 38449028 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Da Vinci Code ' ,
           y: 59063112 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Stuart Little 2 ' ,
           y: 12769231 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Adventures of Pluto Nash ' ,
           y: 545769 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Cars ' ,
           y: 47035100 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Secret World of Arrietty ' ,
           y: 11446175 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' My Neighbor Totoro ' ,
           y: 10493658 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' A Little Princess ' ,
           y: 1340509 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Cat Returns ' ,
           y: 6180535 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Black Stallion ' ,
           y: 53714262 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Land Before Time ' ,
           y: 14664614 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Hercules ' ,
           y: 18832297 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Absent-Minded Professor ' ,
           y: 17065557 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Peter Pan 1953 ' ,
           y: 65591009 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Rookie 2002 ' ,
           y: 9150045 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Monsters, Inc ' ,
           y: 60889338 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Kiki's Delivery Service ' ,
           y: 6869824 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Great Muppet Caper ' ,
           y: 7245224 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Last Unicorn ' ,
           y: 1375978 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Rescuers ' ,
           y: 58181478 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Whisper of the Heart ' ,
           y: 8813289 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Yellow Submarine (film) ' ,
           y: 753905 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Straight Story ' ,
           y: 784383 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Italian Job ' ,
           y: 19501510 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Fantasia ' ,
           y: 119246760 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' 2001: A Space Odyssey ' ,
           y: 38885221 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Oliver! (film) ' ,
           y: 45746965 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The King and I ' ,
           y: 15924501 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Alice in Wonderland 1951 ' ,
           y: 4488167 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Charlotte's Web ' ,
           y: 15271693 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Princess and the Frog ' ,
           y: 20541982 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Aladdin 1992 ' ,
           y: 73244237 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Sleeping Beauty ' ,
           y: 35774443 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Beauty and the Beast ' ,
           y: 65904684 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Great Mouse Detective ' ,
           y: 7080689 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' The Prince and the Pauper (1937 film) ' ,
           y: 2420118 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Pinocchio ' ,
           y: 174448948 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Bambi ' ,
           y: 346436883 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Snow White and the Seven Dwarfs ' ,
           y: 598231494 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' Mulan 1998 ' ,
           y: 37802238 ,
           sliced:true,
           color:"#820BBB",
         },{
           name: ' A Man for All Seasons ' ,
           y: 17894198 ,
           sliced:true,
           color:"#820BBB",

In [290]:
# getting the number of tickets sold in the pg13-rated category
var12 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var12.append(no_tickets[i])
len(var12)

42

In [291]:
# getting the name of the pg13-rated movies
var13 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var13.append(all_actionadventure_info1['Name'][i])
len(var13)

42

In [292]:
# getting the profit of thr pg13-rated movies
var14 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var14.append(all_actionadventure_info1['Profit'][i])
len(var14)

42

Using a for loop to put the name and the number of tickets sold in the PG-13-rated genre in html code which will be pasted in the cell below.

In [293]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var13[i],"'",','+'\n           y:',var12[i],',','\n           sliced:true,'+'\n           color:"#2E0859",')

         },{
           name: ' Captain Marvel ' ,
           y: 86389350 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Thor: The Dark World ' ,
           y: 49584809 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Ready Player One ' ,
           y: 44560780 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Hunger Games: Mockingjay - Part 1 ' ,
           y: 58967318 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Fantastic Four: Rise of the Silver Surfer ' ,
           y: 22267745 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Jumanji: Welcome to the Jungle ' ,
           y: 74192015 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Spy Game ' ,
           y: 11003812 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' News of the World ' ,
           y: 664193 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Greenland ' ,
           y: 3107875 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Ladybugs ' ,
           y: 2120999 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Edward Scissorhands ' ,
           y: 13484355 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Mrs. Doubtfire ' ,
           y: 61472911 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Prestige ' ,
           y: 10487015 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Jumanji: The Next Level ' ,
           y: 61546154 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Dark Knight ' ,
           y: 77157335 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' 13 Going on 30 ' ,
           y: 10345426 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Titanic ' ,
           y: 163652938 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Catch Me If You Can ' ,
           y: 39390633 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Knives Out ' ,
           y: 23953846 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           y: 50384615 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Forrest Gump ' ,
           y: 92170917 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Iron Man ' ,
           y: 45028173 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Batman Begins ' ,
           y: 28743227 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Lord of the Rings: The Return of the King ' ,
           y: 124644138 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Inception ' ,
           y: 63549014 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Gravity ' ,
           y: 55630208 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Help ' ,
           y: 16393846 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Jurassic World ' ,
           y: 128492357 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Hunger Games ' ,
           y: 53414979 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Ring ' ,
           y: 27894385 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Ferris Bueller's Day Off ' ,
           y: 12788598 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Don't Tell Mom the Babysitter's Dead ' ,
           y: 3722422 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Spider-Man 2 ' ,
           y: 84583832 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Sully ' ,
           y: 18348043 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Mean Girls ' ,
           y: 13956741 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Gremlins ' ,
           y: 26645653 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Jason Bourne ' ,
           y: 40698643 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Skyfall ' ,
           y: 85273924 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Clueless ' ,
           y: 7652911 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Sixth Sense ' ,
           y: 81144095 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Wonder Woman 1984 ' ,
           y: 63219001 ,
           sliced:true,
           color:"#2E0859",
         },{
           name: ' The Addams Family ' ,
           y: 15618839 ,
           sliced:true,
           color:"#2E0859",

In [294]:
# putting all the number of tickest that each movie made in a list
ttl = var3+var6+var9+var12+var
ttl

[20000163,
 73874373,
 45013196,
 26838617,
 10740795,
 54664967,
 29551494,
 48018021,
 13796702,
 33982139,
 18851956,
 12601427,
 17476923,
 26811348,
 67674241,
 25255770,
 28226349,
 61300563,
 73879351,
 31298118,
 41204880,
 17476923,
 17847527,
 29406781,
 8857648,
 22667752,
 38341401,
 14311463,
 25255770,
 21036731,
 34671425,
 24251412,
 18283468,
 23035522,
 10465178,
 7616205,
 8343772,
 75862682,
 15192674,
 5598859,
 6904491,
 24378097,
 26473087,
 13707692,
 44572801,
 10747440,
 6899485,
 15608538,
 5055087,
 13272578,
 4534871,
 4371126,
 12637353,
 879007,
 10354803,
 29062108,
 18706226,
 1345540,
 2399417,
 3574694,
 112245106,
 2389139,
 9549512,
 31658196,
 14290012,
 18193017,
 4831014,
 33806579,
 45059576,
 13660842,
 23594694,
 78440167,
 44190834,
 57046433,
 11441592,
 5595307,
 45597570,
 56546083,
 2440691,
 169009685,
 12979669,
 26333670,
 4320334,
 12681853,
 58299251,
 38449028,
 59063112,
 12769231,
 545769,
 47035100,
 11446175,
 10493658,
 1340509,
 6180535,
 53714262,
 14664614,
 18832297,
 17065557,
 65591009,
 9150045,
 60889338,
 6869824,
 7245224,
 1375978,
 58181478,
 8813289,
 753905,
 784383,
 19501510,
 119246760,
 38885221,
 45746965,
 15924501,
 4488167,
 15271693,
 20541982,
 73244237,
 35774443,
 65904684,
 7080689,
 2420118,
 174448948,
 346436883,
 598231494,
 37802238,
 17894198,
 86389350,
 49584809,
 44560780,
 58967318,
 22267745,
 74192015,
 11003812,
 664193,
 3107875,
 2120999,
 13484355,
 61472911,
 10487015,
 61546154,
 77157335,
 10345426,
 163652938,
 39390633,
 23953846,
 50384615,
 92170917,
 45028173,
 28743227,
 124644138,
 63549014,
 55630208,
 16393846,
 128492357,
 53414979,
 27894385,
 12788598,
 3722422,
 84583832,
 18348043,
 13956741,
 26645653,
 40698643,
 85273924,
 7652911,
 81144095,
 63219001,
 15618839,
 37719927,
 26538802,
 38193194,
 49922061,
 32168227,
 34556912,
 45040976,
 37243174,
 10971874,
 63208183,
 46679733,
 27212048,
 12911476,
 18347788,
 41119335,
 14707692,
 26930791,
 32863886,
 23924091,
 47617034,
 7591558,
 35297200,
 40996193,
 31027267,
 43819344,
 38262296,
 36062523,
 42259101,
 42109721,
 82634716,
 1110505,
 60200935,
 37700742,
 28410028,
 43556578,
 480067,
 30153900,
 22183348,
 25487221,
 47037441,
 29108470,
 621628]

In [295]:
# adding all the number of tickects ech movie made
tt2 = 0
for i in ttl:
    tt2+=i

In [296]:
# average of no tickets of R system rating
v = 0
for i in var:
    v+=i
round(v/tt2*100,0)

18.0

In [297]:
# average of no tickets of NR system rating
v1 = 0
for i in var3:
    v1+=i
round(v1/tt2*100,0)

15.0

In [298]:
# average of no tickets of PG system rating
v2 = 0
for i in var6:
    v2+=i
round(v2/tt2*100,0)

14.0

In [299]:
# average of no tickets of G system rating
v3 = 0
for i in var9:
    v3+=i
round(v3/tt2*100,0)

28.0

In [300]:
# average of no tickets of PG13 system rating
v4= 0
for i in var12:
    v4+=i
round(v4/tt2*100,0)

25.0

In [1]:
%%html
<script src="http://code.highcharts.com/highchart.js"></script>
<div id='hraph4' style="height:700px"></div>

In [2]:
%%js
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'hraph4'//name of graph 
    },
    title:{
        text:'Number of Tickets Sold'
    },
    subtitle:{
        text:'Classic Genre'
    },
    series:[{
        type:'pie',// makes the graph pie 
        name: 'Percentage of Tickets Sold',
        tooltip:{
            // turns digits to percentage
            valueSuffix:'%'
        },
        shadow: true,
        data:[{
            name:'System Rating: R',// name of category
            y:18.0,// amount of tickets sold in percentage
            sliced:true,
            color: '#8E388E',// color of section
        },{
            name:'System Rating: PG-13',// name of category
            y:25.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#2E0859',// color of section
        },{
            name:'System Rating: PG',// name of category
            y:14.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#990099',// color of section
        },{
            name:'System Rating: NR',// name of category
            y:15.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#FF00FF',// color of section
        },{
            name:'System Rating: G',// name of category
            y:28.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#820BBB',// color of section
        }],
        innerSize:'80%',// size of inner pie
        size:'83%'// size of outer pie
       },{
        type:'pie',
        shadow: true,
        dataLabels: false,
        name: 'No. of Tickets Sold',
        data:[{ 
           name: ' Oz the Great and Powerful ' ,
           y: 37719927 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Dumbo ' ,
           y: 26538802 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Wreck-It Ralph ' ,
           y: 38193194 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' The Hunger Games: Mockingjay - Part 2 ' ,
           y: 49922061 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The Chronicles of Narnia: The Voyage of the Dawn Treader ' ,
           y: 32168227 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Pearl Harbor ' ,
           y: 34556912 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' I am Legend ' ,
           y: 45040976 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Troy ' ,
           y: 37243174 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The Wolfman ' ,
           y: 10971874 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Spider-Man ' ,
           y: 63208183 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' War of the Worlds ' ,
           y: 46679733 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Night at the Museum: Secret of the Tomb ' ,
           y: 27212048 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Fantastic Four ' ,
           y: 12911476 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Alien: Covenant ' ,
           y: 18347788 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Cinderella ' ,
           y: 41119335 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Hollow Man ' ,
           y: 14707692 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Hannibal ' ,
           y: 26930791 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Cast Away ' ,
           y: 32863886 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The SpongeBob Movie: Sponge Out of Water ' ,
           y: 23924091 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Logan ' ,
           y: 47617034 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Spotlight (film) ' ,
           y: 7591558 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Lucy ' ,
           y: 35297200 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The Revenant ' ,
           y: 40996193 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Prometheus ' ,
           y: 31027267 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Fifty Shades of Grey ' ,
           y: 43819344 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Troy ' ,
           y: 38262296 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The Hangover ' ,
           y: 36062523 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Ted (film) ' ,
           y: 42259101 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' American Sniper ' ,
           y: 42109721 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Joker ' ,
           y: 82634716 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Black Snake Moan ' ,
           y: 1110505 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Deadpool ' ,
           y: 60200935 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Indecent Proposal ' ,
           y: 37700742 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Gone Girl ' ,
           y: 28410028 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' American Beauty ' ,
           y: 43556578 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Lost Highway ' ,
           y: 480067 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' The Wolf of Wall Street ' ,
           y: 30153900 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Bridesmaids ' ,
           y: 22183348 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' 22 Jump Street ' ,
           y: 25487221 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' The Passion of the Christ ' ,
           y: 47037441 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Slumdog Millionaire ' ,
           y: 29108470 ,
           sliced:true,
           color:"#8E388E",
         },{ 
           name: ' Stealing Beauty ' ,
           y: 621628 ,
           sliced:false,
           color:"#8E388E",
         },{ 
           name: ' Captain Marvel ' ,
           y: 86389350 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Thor: The Dark World ' ,
           y: 49584809 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Ready Player One ' ,
           y: 44560780 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' The Hunger Games: Mockingjay - Part 1 ' ,
           y: 58967318 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Fantastic Four: Rise of the Silver Surfer ' ,
           y: 22267745 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Jumanji: Welcome to the Jungle ' ,
           y: 74192015 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Spy Game ' ,
           y: 11003812 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' News of the World ' ,
           y: 664193 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Greenland ' ,
           y: 3107875 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Ladybugs ' ,
           y: 2120999 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Edward Scissorhands ' ,
           y: 13484355 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Mrs. Doubtfire ' ,
           y: 61472911 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' The Prestige ' ,
           y: 10487015 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Jumanji: The Next Level ' ,
           y: 61546154 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' The Dark Knight ' ,
           y: 77157335 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' 13 Going on 30 ' ,
           y: 10345426 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Titanic ' ,
           y: 163652938 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Catch Me If You Can ' ,
           y: 39390633 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Knives Out ' ,
           y: 23953846 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           y: 50384615 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Forrest Gump ' ,
           y: 92170917 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Iron Man ' ,
           y: 45028173 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Batman Begins ' ,
           y: 28743227 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' The Lord of the Rings: The Return of the King ' ,
           y: 124644138 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Inception ' ,
           y: 63549014 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Gravity ' ,
           y: 55630208 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' The Help ' ,
           y: 16393846 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Jurassic World ' ,
           y: 128492357 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' The Hunger Games ' ,
           y: 53414979 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' The Ring ' ,
           y: 27894385 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Ferris Bueller\'s Day Off ' ,
           y: 12788598 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Don\'t Tell Mom the Babysitter\'s Dead ' ,
           y: 3722422 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Spider-Man 2 ' ,
           y: 84583832 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Sully ' ,
           y: 18348043 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Mean Girls ' ,
           y: 13956741 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Gremlins ' ,
           y: 26645653 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Jason Bourne ' ,
           y: 40698643 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' Skyfall ' ,
           y: 85273924 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Clueless ' ,
           y: 7652911 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' The Sixth Sense ' ,
           y: 81144095 , 
           sliced:false,
           color:"#2E0859",
         },{ 
           name: ' Wonder Woman 1984 ' ,
           y: 63219001 , 
           sliced:true,
           color:"#2E0859",
         },{ 
           name: ' The Addams Family ' ,
           y: 15618839 , 
           sliced:true,
           color:"#2E0859",
         },{
           name: ' Trolls ' ,
           y: 26473087 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Dante\'s Peak ' ,
           y: 13707692 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Night at the Museum ' ,
           y: 44572801 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Legend of the Guardians: The Owls of Ga\'Hoole ' ,
           y: 10747440 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' In the Heart of the Sea ' ,
           y: 6899485 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' You Don\'t Mess With the Zohan ' ,
           y: 15608538 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' K-19: The Widowmaker ' ,
           y: 5055087 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' AVP: Alien Vs. Predator ' ,
           y: 13272578 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' The Legend of Hercules ' ,
           y: 4534871 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Elektra ' ,
           y: 4371126 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Daddy Day Care ' ,
           y: 12637353 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Beyond Borders ' ,
           y: 879007 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Zero Dark Thirty ' ,
           y: 10354803 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Taken 2 ' ,
           y: 29062108 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Journey to the Center of the Earth ' ,
           y: 18706226 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Rebound ' ,
           y: 1345540 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' The House ' ,
           y: 2399417 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Fantastic Mr. Fox ' ,
           y: 3574694 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Harry Potter and the Sorcerer\'s Stone ' ,
           y: 112245106 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Labyrinth ' ,
           y: 2389139 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Nim\'s Island ' ,
           y: 9549512 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Spirited Away ' ,
           y: 31658196 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Hugo (film) ' ,
           y: 14290012 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' My Girl ' ,
           y: 18193017 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Inkheart ' ,
           y: 4831014 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Enchanted ' ,
           y: 33806579 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Hook (film) ' ,
           y: 45059576 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Bridge to Terabithia ' ,
           y: 13660842 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' The Goonies ' ,
           y: 23594694 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           y: 78440167 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Night at the Museum ' ,
           y: 44190834 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' The Parent Trap ' ,
           y: 57046433 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' National Treasure ' ,
           y: 11441592 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' The Princess Bride ' ,
           y: 5595307 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' National Treasure: Book of Secrets ' ,
           y: 45597570 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Up ' ,
           y: 56546083 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' The Witches 1990 ' ,
           y: 2440691 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' E.T. the Extra-Terrestrial ' ,
           y: 169009685 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Nanny McPhee ' ,
           y: 12979669 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Big (film) ' ,
           y: 26333670 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' Matilda ' ,
           y: 4320334 , 
           sliced:false,
           color:"#990099",
         },{ 
           name: ' Finding Neverland ' ,
           y: 12681853 , 
           sliced:true,
           color:"#990099",
         },{ 
           name: ' The Lone Ranger ' ,
           y: 20000163 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' The Hobbit: The Desolation of Smaug ' ,
           y: 73874373 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Iron Man ' ,
           y: 45013196 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' The Legend of Tarzan ' ,
           y: 26838617 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' King Arthur: Legend of the Sword ' ,
           y: 10740795 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Dawn of the Planet of the Apes ' ,
           y: 54664967 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Independence Day: Resurgence ' ,
           y: 29551494 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Hancock ' ,
           y: 48018021 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Flushed Away ' ,
           y: 13796702 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Men in Black 2 ' ,
           y: 33982139 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Hulk ' ,
           y: 18851956 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Miami Vice ' ,
           y: 12601427 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Charlie\'s Angels: Full Throttle ' ,
           y: 17476923 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' The Smurfs 2 ' ,
           y: 26811348 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Ice Age: Continental Drift ' ,
           y: 67674241 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Now You See Me 2 ' ,
           y: 25255770 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Penguins of Madagascar ' ,
           y: 28226349 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           y: 61300563 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           y: 73879351 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' X-Men 2 ' ,
           y: 31298118 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           y: 41204880 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Charlie\'s Angels: Full Throttle ' ,
           y: 17476923 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Gulliver\'s Travels ' ,
           y: 17847527 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Live Free or Die Hard ' ,
           y: 29406781 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Wonder Park ' ,
           y: 8857648 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Sex and the City 2 ' ,
           y: 22667752 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Sherlock Holmes ' ,
           y: 38341401 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Atlantis: The Lost Empire ' ,
           y: 14311463 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Now You See Me 2 ' ,
           y: 25255770 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Tomb Raider ' ,
           y: 21036731 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Ocean\'s Eleven ' ,
           y: 34671425 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Air Force One ' ,
           y: 24251412 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Click ' ,
           y: 18283468 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Shutter Island ' ,
           y: 23035522 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Lost In Space ' ,
           y: 10465178 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' The Wild ' ,
           y: 7616205 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Pompeii ' ,
           y: 8343772 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' The Lion King ' ,
           y: 75862682 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Christopher Robin ' ,
           y: 15192674 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Lady in the Water ' ,
           y: 5598859 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' Sucker Punch ' ,
           y: 6904491 , 
           sliced:false,
           color:"#FF00FF",
         },{ 
           name: ' Inglourious Basterds ' ,
           y: 24378097 , 
           sliced:true,
           color:"#FF00FF",
         },{ 
           name: ' The Amazing Spider-Man ' ,
           y: 58299251 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Dunkirk ' ,
           y: 38449028 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Da Vinci Code ' ,
           y: 59063112 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Stuart Little 2 ' ,
           y: 12769231 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Adventures of Pluto Nash ' ,
           y: 545769 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Cars ' ,
           y: 47035100 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Secret World of Arrietty ' ,
           y: 11446175 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' My Neighbor Totoro ' ,
           y: 10493658 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' A Little Princess ' ,
           y: 1340509 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Cat Returns ' ,
           y: 6180535 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Black Stallion ' ,
           y: 53714262 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Land Before Time ' ,
           y: 14664614 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Hercules ' ,
           y: 18832297 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Absent-Minded Professor ' ,
           y: 17065557 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Peter Pan 1953 ' ,
           y: 65591009 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Rookie 2002 ' ,
           y: 9150045 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Monsters, Inc ' ,
           y: 60889338 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Kiki\'s Delivery Service ' ,
           y: 6869824 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Great Muppet Caper ' ,
           y: 7245224 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Last Unicorn ' ,
           y: 1375978 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Rescuers ' ,
           y: 58181478 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Whisper of the Heart ' ,
           y: 8813289 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Yellow Submarine (film) ' ,
           y: 753905 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Straight Story ' ,
           y: 784383 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Italian Job ' ,
           y: 19501510 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Fantasia ' ,
           y: 119246760 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' 2001: A Space Odyssey ' ,
           y: 38885221 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Oliver! (film) ' ,
           y: 45746965 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The King and I ' ,
           y: 15924501 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Alice in Wonderland 1951 ' ,
           y: 4488167 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Charlotte\'s Web ' ,
           y: 15271693 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Princess and the Frog ' ,
           y: 20541982 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Aladdin 1992 ' ,
           y: 73244237 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Sleeping Beauty ' ,
           y: 35774443 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Beauty and the Beast ' ,
           y: 65904684 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' The Great Mouse Detective ' ,
           y: 7080689 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' The Prince and the Pauper (1937 film) ' ,
           y: 2420118 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Pinocchio ' ,
           y: 174448948 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Bambi ' ,
           y: 346436883 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' Snow White and the Seven Dwarfs ' ,
           y: 598231494 , 
           sliced:true,
           color:"#820BBB",
         },{ 
           name: ' Mulan 1998 ' ,
           y: 37802238 , 
           sliced:false,
           color:"#820BBB",
         },{ 
           name: ' A Man for All Seasons ' ,
           y: 17894198 , 
           sliced:true,
           color:"#820BBB"
        
        }],
    innerSize:'93%',// size of inner pie
    size:'100%'// size of outer pie
    }]
});