  # Objective

__Microsoft sees all the big companies creating original video content, and they want to get in on the fun. They have decided to create a new movie studio, but the problem is they don't know anything about creating movies. They have hired you to help them better understand the movie industry. Your team is in charge with doing data analysis that explores what type of films are currently doing the best at the box office. You must then translate
those findings into actionable insights that the CEO can use when deciding what type of films they should be creating.__

# Datasets

There are 10 datasests in this project 

_Name.basics.csv_
  - _Colunms in the dataset_
     - _nconst_
     - _primary_name_
     - _birth_year_
     - _death_year_
     - _primary_profession_
     - _known_for_titles_

_Bom.movie_gross.csv_
   - _Colunms in the dataset_
      - _title_
      - _studio_
      - _domestic_gross_
      - _foreign_gross_
      - _year_
     
_Rt.movie_info.tsv_
   - _Columns in the dataset_
     - _id_
     - _synopsis_
     - _rating_
     - _genre_
     - _director_
     - _writer_
     - _theater_date_
     - _currency_
     - _box_office_
     - _runtime_
     - _studio_
     
_Title.akas.csv_
   - _Columns in the dataset_
     - _title_id_
     - _ordering_
     - _title_
     - _region_
     - _language_
     - _types_
     - _attributes_
     - _is_original_title_
     
_Title.basics.csv_
  - _Columns in the dataset_
    - _tconst_
    - _primary_title_
    - _original_title_
    - _start_year_
    - _runtime_mintues_
    - _genres_
    
_Title.crew.csv_
  - _Columns in the dataset_
    - _tconst_
    - _directors_
    - _writers_
    
_Title.principals.csv_
  - _Columns in the dataset_
    - _tconst_
    - _ordering_
    - _nconst_
    - _category_
    - _job_
    - _charactors_

_Title.ratings.csv_
  - _Columns in the dataset_
    - _tconst_
    - _averagerating_
    - _numvoters_
    
_Tmdb.movies.csv_
  - _Columns in the dataset_
    - _genre_ids_
    - _id_
    - _original_language_
    - _original_title_
    - _popularity_
    - _release_date_
    - _title_
    - _vote_average_
    - _vote_count_
    
_Tn.movie_budgets_
   - _Columns in the dataset_
     - _id_
     - _release_date_
     - _movie_
     - _production_budget_
     - _domestic_gross_
     - _worldwide_gross_

# Approaches

Based on the datasets there are nine main genres; Action and Adventures, Drama, Comedy, Documentry, Classics, Art House and International, Musical and Performing Arts, Horror, Mystrey and Suspense, Animation, Special Interest, Kids and Family and there are also five main System Ratings; System R Rating, System PG-13 Rating, System PG Rating, System G Rating and System NR Rating. In this Project the genres that are being chosen are Classic, Drama, Comedy, Classics and Art House and International which will all have indivisual data analysis based on the same data visualization concepts and the system ratings are being compared among one another and also analyised to view which one best fit the genres. There will be eleven differnt graphs for each genres describing and protarying insights on the activity of the data.

## Graphs
These are the elven main graphs.
  - __Profit Percentage baised on cost__:
     - This data visualization shows the name, cost, profit, the type of system rating and profit percenatge by cost. The purpose of this notion is to view past the profit and better understand how successful the movie really is by analysing the cost and calculating how much more was made compared to it. This allows the idea of higher profit dosn't mean more profitable to be considered as a justification based on the results proving so. The system rating were added to be compared among eachother, to observe which one was better and to also know which one was the best fit for any particular genere by calculating the average of the reults of each system rating
   
  
  
  - __Gross Profit Margin Percentage__:
     - This data visualization has two pionts about the movie on one panel. The fisrt piont shows the name, amount of profit made in dollars, type of system rating and Gross Profit Margin Percentage. The other piont shows the name, revenue made in dollars and the type of system rating. The graph was designed this way to compare the profit amount against the revenue amount, allowing the Gross Profit Margin Percntage to be more visible and inderectly see the expenses made from a graph perpsective.
     
 
 - __Budget and Revenue of Movies__:
    - This graph is a scatter plot with an x-axis and a y-axis, the x-axis is the revenue of the movies in dollars and the y-axis is the budget of the movies in dollars. This graph is a blueprint to better understand  wether the amount of money spent on the movie effected the amount of revenue generted and to also spot movies that spent less money than the average with a higher revenue.
 
 
 - __Revenue of Movies/Budget of Movies__:
    - The revenue graph has an x-axis that shows the revnue of the movies, name and the type of system ratings with no y-axis. The budget graph has an x-axis that shows the budget of the movies and also the name and system ratings with no y-axis. Both graphs have a table split into catagories of the system ratings showing were they are postions in the axis. These graphs were constructed to predict how much will be made depending on how much is spent based on the pattern of budget of movies to revenue of movies and to indirectly spot anomalies.
    
 
 - __Movies that mdae Profit__:
    - This graph simply shows all the movies that made profit, from the highest to the lowest.


 - __Movies that had losses__:
   - This graph is a colunm graph that shows the movies that did not make any profit. It shows the cost of the movie, revenue and by how much was not made to prevent a loss by the movie. It also shows the name and system ratings it belongs to. This dilema was created to percieve what agenda was not making any money, to try and understand the other half of film industry that is overlooked.
   
   
 
 - __Top 20 Highest Profitable Movies/ Top 20 Lowest Profitable Mobies__:
    - The top 20 highest profitable graph is a 3D chart that shows the top 20 most profitable movies with an x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. The top 20 lowest profitable graph is also a 3D chart that shows the top 20 movies that had the lowest profit, with the x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. These graphs were creted to really spot what movis were the kings and queens of the movie industry and what movie was barely making sales. This brings a lot of questioning to what each of the movies did do britiantally or failed to do.
    

- __Most Successful Moive__:
   - This graph is built up of two sections, the first section is an x-axis whcih shows the names and a y-axis which shows the budget, revenu and profit of the movies in dollars, the second section compares the gross profit margin percentage to the profit percnatge by cost of the movies whcih is all compared to all other movies in the data frame. The sections data is based on the top 20 most profitable movies. The concept of the visualization is to  dive deep into detail to anlayze what movie were actually more succesfull than the other, other than just focusing on the highets profits made. Factors like budget and revenue expressed in gross profit margin percentage and proft percentage by cost allows the differences among the most profitable movies to become more disguishable, whcih can open a new perspcetive on anyalzing numbers.
   
 
 - __Tickets Sold__:
    - This graph simply shows what system ratings have the highest tickets sold to better understand what audience best fist this genre through the sales of the system ratings.

Before starting any data extracting, liabreis such as Altair, Pandas, Pandas_highcharts, Collections need to be installed to help create great insightful interactive graphs.

In [1]:
import altair as alt # used to create interactive graphs
import pandas as pd # used to make for dataframes
import collections# used to put data into sections
import matplotlib.pyplot as plt# used to make graphs

In [2]:
# helps create highcharts graphs
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import json

Before the graphs are made the data is extracted from the rt.movie_info.tsv file and made into a dataframe.

In [3]:
# The data frame is called movie_info
movie_info = pd.read_csv("rt.movie_info.tsv.gz",error_bad_lines=False,sep='\t')

In [4]:
movie_info.head()

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN

In [5]:
# Getting first 500 movies 
first_500 = []
for i in movie_info.genre[:500].dropna():
    first_500.append(i)
len(first_500)

496

The movies form the data frame have been selected and put into genres groups for the first 500 movies

In [6]:
# putting movies into groups
grouped_500 = []
for i in first_500:
    grouped_500.append(i.split('|',1)[0])
grouped_500=collections.Counter(grouped_500)
grouped_500

Counter({'Action and Adventure': 117,
         'Drama': 103,
         'Comedy': 115,
         'Documentary': 11,
         'Classics': 53,
         'Art House and International': 55,
         'Musical and Performing Arts': 3,
         'Horror': 23,
         'Mystery and Suspense': 7,
         'Animation': 6,
         'Special Interest': 2,
         'Kids and Family': 1})

# Blueprint: Profit Percentage Based on Cost

The amount of movies in the genre groups are all uneven, the goal through out the project is to make sure they all have the same amount of movies that are being analyzed to give it a fair comparison which will be done later on in the project.

The next step is to choose a genre to select and start analyzing. For this section Action and Adventure is being analyzed.

This is the blueprint for creating the first visualization Profit Percentage by cost, bokeh will be used to create these graphs.
Blueprint:
 1. Create a new dataframe for the graph, the dataframe columns will consist of these key infomation of the moives in the Action and Adventure Genre;
    - The Names 
    - Product Budget 
    - System Ratings 
    - Ratings 
    - Domestic Gross 
    - World Wide Gross
    - Profit
    - No. of Tickets
    - Product Budget in integers
    - Profit in integers
    - Total Gross in integers
    - Domestic total in integers
 
 
 2. Install bokeh and create the componets needed for the format of the code script for the graph.There will be five graphs and in each graph are key information of the movies based on the same system rating which are R, PG-13, PG, G and NR. These are the key componets needed in each graph based on the same system rating;
    - X-axis Range
    - Y-axis Range
    - Name
    - Profit in integers
    - System Rating
    - Percentage Profit by Cost
    - Cost


3. The graphs has to have visual componets that convey the information smoothly and also differentiate from one another due to that fact that they are all in groups, these are the formats to help do so; 
    - Color
    - Tooltips (make the graph interactive)
    - Type and shape of pionts in the graph

Below is the code script used to create a new dataframe needed for the graphs

In [7]:
# Getting the names of the first 200 movies in the Action and Adventure genre
movie_buddget = pd.read_csv('tn.movie_budgets.csv.gz')
name_movies = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': # 'Cl' is the first two words for Action and Adventure
        name_movies.append(movie_buddget.movie[x])
len(name_movies)

55

In [8]:
# Getting product budget of the first 200 movies in Action and Adventure genre
product_budget = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar':product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

55

In [9]:
# Getting ratings of the first 200 movies in Action and Adventure genre
ratings = pd.read_csv('imdb.title.ratings.csv.gz')
rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': rating.append(ratings.averagerating[x])
len(rating)

55

In [10]:
# Getting system ratings of the first 200 movies in Action and Adventure genre
system_rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': system_rating.append(movie_info.rating[x])
len(system_rating)

55

In [11]:
# Getting domestic gross of the first 200 movies in Action and Adventure genre
domestic_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

55

In [110]:
# Getting worldwide gross of the first 200 movies in Action and Adventure genre
worldwide_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Ar': worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

55

The amount of movies per system rating all have to be the same. The code bellow caluclates how much movies are currently in each system rating.

In [12]:
# putting system ratings into groups
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating
# need all groups to be even, all groups need 42 records

Counter({'PG-13': 10, 'R': 21, 'PG': 4, 'NR': 19, 'G': 1})

'R' has the highest count of movies, so all system rating will have to have 42 movies based on all the previous genre analysis to make it a fair analysis

Due to the fact that the amount of movies per system rating is not tha same, the following codes caluclate how much is needed for each misiing amount in each group and also getting the indexes of what is needed.

In [112]:
# making sure all system_rating have the same amout of records
# getting the index of  system PG-13: need 32
index_PG13 = movie_info[movie_info['rating']=='PG-13'].index
index_PG13[250:300]

Int64Index([], dtype='int64')

Based on the indexes on the 'PG-13' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-13-rated. The 35 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [113]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Godzilla':
        print('yes')

In [13]:
#informations on the movies needed for pg-13
# the name of the movies
name_mojo1 = ['The Fountain','Primer','The Tree of Life','Another Earth',' The New World','Restless ',
             'The Box','Departures','The Chorus','The Kite Runner','Radio Flyer ',
             'The Cider House Rules','A Better Life','A Separation','Crouching Tiger, Hidden Dragon ',' Dear Frankie',
             'Invictus','Life Is Beautiful','The Diving Bell and the Butterfly',
             'The Perks of Being a Wallflower','The Impossible','The Sea Inside','The Perks of Being a Wallflower'
              ,'Back to the Future','Apollo 13','Finding Neverland','Groundhog Day', 'Hidden Figures',
             'Boy Erased','The Imposter','happy as lazzaro','My Life as a Zucchini','Godzilla']
# ratings of the movies
rating_mojo1 = [7.2,6.9,6.8, 7,6.7,6.8,
              5.6,8.1,7.9,7.6,8,7,
              7.4,7.2,8.3,7.8,7.7,5.8,
              7.3,8.6,7,8,8,7.6,
              8,8,6.1,7,8,6,
             7,6,6.4]
# worldwide gross
worldwide_gross_mojo1 = ['$21,796,621','$1,189,906','$58,409,247','$2,304,064','$71,036,076','$4,066,191',
             '$33,333,531','$70,636,951','$115,937,265','$96,820,727','$8,786,940','$140,718,085',
             '$1,863,506','$22,926,076','$330,451,697','$2,341,621','$122,233,971','$228,847,384',
             '$29,370,408','$33,384,127','$279,959,676','$61,741,311','$33,384,127','$549,313,764',
             '$389,471,114','$164,864,089','$130,158,018','$235,956,898','$11,862,650','$3,232,717',
             '$1,802,696','$5,872,598','$535,000,000']
# domestic gross
domestic_gross_mojo1 = ['$13,426,071','$600,319','$13,303,319','$1,570,117','$18,303,867','$263,647',
             '$15,051,977','$1,498,210','$2,949,769','$20,394,001','$8,786,940','$91,452,106',
             '$1,759,252','$7,099,055','$198,207,571','$25,475','$37,491,364','$57,247,384',
             '$7,731,708','$17,742,948','$26,881,089','$2,974,919','$17,742,948','$520,972,147',
             '$299,399,485','$73,040,998','$130,158,018','$169,607,287','$6,788,692','$901,954',
             '$502,508','$309,766','$201,000,000']
# product budget
product_budget_mojo1 = ['$46,324,136','$9,893','$32,000,000','$118,840','$43,196,351','$12,918,735',
             '$30,000,000','$2,757,562','$7,490,570','$25,815,064','$66,110,152','$38,141,403',
             '$10,000,000','$500,000','$26,310,505','$4,893,180','$60,000,000','$20,000,000',
             '$18,070,545','$13,000,000','$63,599,186','$17,129,013','$13,000,0000','$46,999,107',
             '$107,878,343','$35,332,881','$26,800,002','$25,000,000','$11,000,000','$1,000,000',
             '$7,271,623','$8,000,000','$160,000,000']

In [116]:

# making sure all system_rating have the same amout of records
# getting system PG: need 38
index_PG = movie_info[movie_info['rating']=='PG'].index
index_PG[250:300]

Int64Index([], dtype='int64')

In [117]:
movie_info.iloc[[1307, 1309, 1313, 1318, 1336, 1348, 1351, 1363, 1370, 1380, 1386,
            1391, 1393, 1404, 1409, 1417, 1424, 1425, 1438, 1459, 1461, 1462,
            1463, 1466, 1468, 1471, 1473, 1476, 1485, 1486, 1493, 1498, 1511,
            1514, 1530, 1531, 1546, 1553, 1556, 1558]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1307,1690,Fifteen-year-old Jim Hawkins stumbles upon a m...,PG,Action and Adventure|Animation|Kids and Family...,Ron Clements|John Musker,Sam Levine|Alex Mann|Ron Clements|John Musker|...,"Nov 27, 2002","Apr 29, 2003",$,"38,120,554",95 minutes,Buena Vista Distribution Compa
1309,1692,"Long before Grease was even thought of, the Br...",PG,Classics|Drama|Musical and Performing Arts,Claude Whatham,Ray Connolly,"Jan 1, 1973","Nov 28, 2000",NaN,NaN,90 minutes,NaN
1313,1698,John Hughes continues the trend he began with ...,PG,Comedy|Kids and Family,NaN,John Hughes,"Jun 25, 1993","Jan 28, 2003",NaN,NaN,94 minutes,NaN
1318,1703,"In this film, filmmaker Akira Kurosawa spins t...",PG,Art House and International|Classics|Drama,Akira Kurosawa,Akira Kurosawa|Masato Ide,"Oct 10, 1980","Mar 29, 2005",NaN,NaN,179 minutes,NaN
1336,1730,Television sitcom star Tim Allen made his big ...,PG,Action and Adventure|Comedy|Kids and Family|Sc...,John Pasquin,Leo Benvenuti|Steve Rudnick,"Nov 11, 1994","Oct 13, 1998",NaN,NaN,97 minutes,NaN
1348,1742,Robin Wright and Cary Elwes star in this fairy...,PG,Action and Adventure|Comedy|Kids and Family|Sc...,Rob Reiner,William Goldman,"Sep 25, 1987","Jan 26, 1999",NaN,NaN,98 minutes,20th Century Fox
1351,1745,"When a retired stock car driver, Brewster Bake...",PG,Comedy|Drama,NaN,Mike Marvin|Alex Matter,"Jul 16, 1982","Apr 4, 2006",NaN,NaN,110 minutes,NaN
1363,1760,Basketball superstar Michael Jordan and cartoo...,PG,Comedy|Kids and Family,Joe Pytka,Leo Benvenuti|Steve Rudnick|Timothy Harris|Her...,"Nov 15, 1996","Aug 27, 1997",NaN,NaN,88 minutes,NaN
1370,1769,"After sitting on the shelf for some time, Teen...",PG,Comedy|Science Fiction and Fantasy,Rod Daniel,Matthew Weisman|Jeph Loeb,"Aug 23, 1985","Sep 9, 2014",NaN,NaN,92 minutes,NaN
1380,1779,"In this film, Kit is a war-scarred veteran of ...",PG,Action and Adventure|Drama|Mystery and Suspens...,Richard Wallace,NaN,NaN,NaN,NaN,NaN,91 minutes,NaN
1386,1788,London 1818: a secret love affair begins betwe...,PG,Drama|Romance,Jane Campion,Jane Campion,"May 15, 2009","Jan 26, 2010",$,"4,341,275",119 minutes,Apparition Films
1391,1795,"One of the first recognizable ""vigilante"" film...",PG,Action and Adventure|Art House and Internation...,NaN,Tom Laughlin,"Jul 12, 1967","Oct 31, 2000",NaN,NaN,112 minutes,NaN
1393,1798,For the Tibetan Mastiffs living on Snow Mounta...,PG,Animation|Comedy|Kids and Family,Ash Brannon,Ash Brannon|Kurt Voelker,"Feb 24, 2017","May 23, 2017",$,"9,404,922",80 minutes,Summit Premiere
1404,1812,An Army officer comes into conflict with a sma...,PG,Action and Adventure|Comedy,NaN,Dan Gordon|Bob Gale,"Mar 16, 1984","Jun 15, 1998",NaN,NaN,114 minutes,NaN
1409,1818,From Dr. No director Terence Young comes this ...,PG,Action and Adventure|Mystery and Suspense,Terence Young|Gail Harvey,Shimon Wincelberg|Dorothea Bennett|Albert Simo...,NaN,NaN,NaN,NaN,90 minutes,NaN
1417,1826,"This (13th) time around, 007 (once again playe...",PG,Action and Adventure|Drama|Mystery and Suspense,John Glen,NaN,"Jun 10, 1983","Oct 17, 2000",NaN,NaN,131 minutes,NaN
1424,1837,"""Becoming Jane,"" is the story of the great, un...",PG,Drama|Romance,Julian Jarrold,Sarah Williams|Kevin Hood,"Aug 3, 2007","Feb 12, 2008",$,"18,602,895",120 minutes,Miramax Films
1425,1839,The musicians of the Buena Vista Social Club e...,PG,Documentary,Lucy Walker,NaN,"May 26, 2017","Sep 12, 2017",$,"118,253",111 minutes,NaN
1438,1854,"The ""mermaids"" are really tribal pearl divers ...",PG,Action and Adventure|Drama|Romance,Robert Florey,Carroll Young,NaN,NaN,NaN,NaN,68 minutes,NaN
1459,1879,Thornton Wilder's award-winning novel is given...,PG,Art House and International|Drama|Faith and Sp...,Mary McGuckian,Mary McGuckian,"Jun 10, 2005","Oct 11, 2005",NaN,NaN,120 minutes,NaN
1461,1881,"""Bicentennial Man,"" follows the life and times...",PG,Comedy|Drama|Science Fiction and Fantasy,Chris Columbus,Nicholas Kazan,"Dec 17, 1999","Jan 15, 2002",NaN,NaN,131 minutes,Buena Vista Pictures
1462,1882,"In ""Ralph Breaks the Internet,"" video-game bad...",PG,Animation|Comedy|Kids and Family|Science Ficti...,Phil Johnston|Rich Moore,Phil Johnston|Pamela Ribon,NaN,NaN,NaN,NaN,114 minutes,Walt Disney Animation Studios
1463,1883,Burt Lancaster and Alain Delon play cat-and-mo...,PG,Action and Adventure|Drama|Mystery and Suspense,Michael Winner,NaN,"Apr 19, 1973","Jan 18, 2000",NaN,NaN,114 minutes,NaN
1466,1886,"""Houston, we have a problem."" Those words were...",PG,Action and Adventure|Drama,Ron Howard,Al Reinert|William Broyles,"Jun 30, 1995","Sep 7, 2004",NaN,NaN,140 minutes,Universal Pictures
1468,1889,Milos Foreman's cinematic adaptation of E.L. D...,PG,Drama,Milos Forman,NaN,"Nov 20, 1981","Nov 16, 2004",NaN,NaN,155 minutes,NaN
1471,1892,"Based on Peter Benchley's best-selling novel, ...",PG,Action and Adventure|Drama|Mystery and Suspense,Steven Spielberg,Howard Sackler|Carl Gottlieb|Peter Benchley,"Jun 1, 1975","Jul 11, 2000",NaN,NaN,124 minutes,Universal Pictures
1473,1896,"In the epic conclusion of the saga, the Empire...",PG,Action and Adventure|Drama|Science Fiction and...,Richard Marquand,George Lucas|Lawrence Kasdan,"May 25, 1983","Sep 12, 2006",NaN,NaN,133 minutes,Twentieth Century Fox
1476,1899,Thanks to the carelessness of a cute little do...,PG,Comedy|Horror|Science Fiction and Fantasy,Tim Burton,Warren Skaaren|Michael McDowell|Larry Wilson|M...,"Mar 30, 1988","Jun 26, 1997",NaN,NaN,93 minutes,NaN
1485,1911,This breathlessly paced high-tech thriller sta...,PG,Classics|Drama|Mystery and Suspense,Sidney Lumet,Lawrence Sanders|Frank Pierson,"Jun 17, 1971","Jan 6, 2003",NaN,NaN,95 minutes,NaN
1486,1912,"In the sequel to the hit comedy Sister Act, Wh...",PG,Comedy,Bill Duke,James Orr|Jim Cruickshank|Judi Ann Mason|James...,"Dec 10, 1993","Feb 20, 2001",NaN,NaN,106 minutes,NaN
1493,1923,"Cocoon 2: The Return, like most sequels, relie...",PG,Comedy|Drama|Science Fiction and Fantasy,NaN,NaN,"Nov 23, 1988","Jun 1, 2004",NaN,NaN,116 minutes,NaN
1498,1930,Sharp-tongued East End spy Harry Palmer once a...,PG,Action and Adventure|Art House and Internation...,Guy Hamilton,Evan Jones,"Jan 1, 1966","Aug 14, 2001",NaN,NaN,102 minutes,NaN
1511,1945,"Left on a nun's doorstep, Larry, Curly and Moe...",PG,Comedy,Bobby Farrelly|Peter Farrelly,Bobby Farrelly|Peter Farrelly|Mike Cerrone,"Apr 13, 2012","Jul 17, 2012",$,"41,800,000",92 minutes,20th Century Fox
1514,1949,"A sweet, innocent and none-too-educated Southe...",PG,Comedy|Romance,Barnet Kellman,Craig Bolotin|Patricia Resnick|Susan Berman,"Apr 3, 1992","May 6, 2003",NaN,NaN,91 minutes,NaN
1530,1968,"This holiday season, acclaimed filmmaker Camer...",PG,Comedy|Drama,Cameron Crowe,Aline Brosh McKenna|Cameron Crowe,"Dec 23, 2011","Apr 3, 2012",$,"72,700,000",126 minutes,20th Century Fox
1531,1969,Melvin Frank's burlesque amalgam of McCabe and...,PG,Action and Adventure|Comedy|Western,Melvin Frank,NaN,"Apr 1, 1976","Jun 7, 2005",NaN,NaN,104 minutes,NaN
1546,1986,Aki Kaurismaki's The Man Without a Past opens ...,PG,Art House and International|Comedy|Drama,NaN,NaN,"Aug 30, 2002","Oct 7, 2003",$,"794,306",97 minutes,NaN
1553,1993,A former child actor turned talent agent is hi...,PG,Comedy,James Lapine,NaN,"Jun 4, 1993","Apr 8, 2003",NaN,NaN,95 minutes,NaN
1556,1997,The popular Saturday Night Live sketch was exp...,PG,Comedy|Science Fiction and Fantasy,Steve Barron,Terry Turner|Tom Davis|Dan Aykroyd|Bonnie Turner,"Jul 23, 1993","Apr 17, 2001",NaN,NaN,88 minutes,Paramount Vantage
1558,1999,The Sandlot is a coming-of-age story about a g...,PG,Comedy|Drama|Kids and Family|Sports and Fitness,David Mickey Evans,David Mickey Evans|Robert Gunter,"Apr 1, 1993","Jan 29, 2002",NaN,NaN,101 minutes,NaN

In [118]:
#checking if the names are already used
for i in name_movies:
    if i == 'Sound of Music':
        print('yes!')
else:print('no')

no

In [119]:
movie_buddget.iloc[[543,653,928,934,954,1028,1252,1459,1546]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
543,44,"May 7, 1999",The Mummy,"$80,000,000","$155,385,488","$416,385,488"
653,54,"Jun 4, 2010",Killers,"$75,000,000","$47,059,963","$95,572,749"
928,29,"May 13, 2011",Priest,"$60,000,000","$29,136,626","$84,154,026"
934,35,"Aug 14, 1998",The Avengers,"$60,000,000","$23,385,416","$48,585,416"
954,55,"Jan 25, 2019",The Kid Who Would Be King,"$59,000,000","$16,790,790","$28,348,446"
1028,29,"Jun 4, 1999",Instinct,"$55,000,000","$34,105,207","$34,105,207"
1252,53,"Nov 20, 1998",A Bug's Life,"$45,000,000","$162,798,565","$363,095,319"
1459,60,"Aug 26, 2011",Colombiana,"$40,000,000","$36,665,854","$72,295,262"
1546,47,"Feb 2, 2007",Because I Said So,"$39,000,000","$42,674,040","$69,538,833"

In [14]:
#new name index for pg
no1=[543,653,928,934,954,1028,1252,1459,1546]

Based on the indexes on the 'PG' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-rated. The 25 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [121]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Cars':
        print('yes')

In [15]:
#informtions on the movies needed for pg
# the name of the movies
name_mojo2 = ['Lagaan','April and the Extraordinary World',' Badlands','Where the Wild Things Are','Andrei Rublev',
              'Tokyo Story',
             'Bicycle Thieves','Days of Heaven','Suspiria','Under the Skin','Midnight in Paris','Frida',
             'Girl with a Pearl Earring','Mr. Turner','The Tree of Life','Waste Land','Rivers and Tides','Moonlight',
             '3 Ninjas','Karate Kid','Walt Before Mickey','Loving Vincent','The Best Offer ','Basquiat (film)',
             'La Belle Noiseuse','Mona Lisa Smile drawing','Days of Heaven','Solaris','The Conformist']
# ratings of the movies
rating_mojo2 = [9.5,9.1,7.8,6.7,8.2,7.8,
             8,5,7,6.4,8.9,7.4
             ,6.9,6.8,7.4,5.3,8,7
             ,7.3,6,8,5.4,7.8,7,5
             ,7.8,6.2,8]
# worldwide gross
worldwide_gross_mojo2 = ['$40,717,774','$495,879','$67,458','$100,140,096','$145,491','$59,654',
             '$428,978','$15,355,298','$7,942,093','$5,735,963','$153,959,590',' $56,300,000',
             '$31,466,789','$22,200,000','$58,409,247','$291,307','$5,042,641','$65,300,000',
             '$54,777,551','$335,299,206','$476,046','$42,187,665','$20,596,350','$5,109,693',
             '$777,754','$187,067,435','$22,436,801','$190,144,486','$2,768,810']
# domestic gross
domestic_gross_mojo2 = ['$835,767','$295,488','$67,458','$77,233,467','$124,189','$59,654',
             '$371,111','$14,457,141','$2,483,472','$2,614,251','$56,817,045','$25,900,000 ',
             '$11,670,971','$3,958,500','$13,303,319','$187,716','$3,293,762','$27,854,932',
             '$54,776,983','$233,515,218','$476,046','$6,735,118','$100,035','$5,109,693',
             '$777,754','$84,522,942','$21,124,435','$94,894,810','$405,268']
          
# product budget
product_budget_mojoo2 = ['$5,138,425','$10,400,000','$558,062','$100,000,000','$1,300,000','$35,000',
             '$133,000','$12,583,285','$20,000,000','$13,300,000','$17,000,000','$12,000,000',
             '$12,000,000','$11,641,518','$32,000,000','$1,500,000','$$898,186','$4,000,000',
             '$4,722,153','$20,570,503','$568,000','$5,500,000','$18,000,000','$5,599,766',
             '$1,168,044','$63,860,942','$18,386,400','$5,253,842','$5,181,843']

In [123]:
# making sure all system_rating have the same amout of records
# getting system NR: need 23
index_PG = movie_info[movie_info['rating']=='NR'].index
index_PG[200:250]

Int64Index([618, 628, 629, 630, 638, 642, 644, 645, 647, 648, 654, 656, 658,
            661, 669, 677, 678, 679, 688, 693, 697, 699, 700, 711, 713, 714,
            715, 718, 720, 722, 724, 727, 731, 734, 735, 739, 742, 743, 745,
            747, 750, 767, 768, 770, 771, 772, 773, 776, 788, 789],
           dtype='int64')

In [124]:
movie_info.iloc[[ 618, 628, 629, 630, 638, 642, 644, 645, 647, 648, 654, 656, 658,
            661, 669, 677, 678, 679, 688, 693, 697, 699, 700, 711, 713, 714,
            715, 718, 720, 722, 724, 727, 731, 734, 735, 739, 742, 743, 745,
            747, 750, 767, 768, 770, 771, 772, 773, 776, 788, 789]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
618,798,"Celia, who calls herself Ginevra, is a movie a...",NR,Drama,Ingemo Engstrom,NaN,NaN,NaN,NaN,NaN,157 minutes,NaN
628,810,This frothy romantic comedy from Korea begins ...,NR,Comedy|Drama|Romance,Jae-young Kwak,Jae-young Kwak|Ho-sik Kim,"Jul 27, 2001","Feb 19, 2013",NaN,NaN,123 minutes,NaN
629,811,The trials and tribulations of four teenagers-...,NR,Art House and International|Drama,Eli Cohen,NaN,"Jan 1, 1994","Jan 24, 2006",NaN,NaN,141 minutes,NaN
630,812,Hands of a Stranger was adapted by playwright ...,NR,Drama|Mystery and Suspense,Larry Elikann,NaN,NaN,NaN,NaN,NaN,179 minutes,NaN
638,821,"In this drama, set in a Scandinavian hospital ...",NR,Art House and International|Comedy|Drama,Mai Zetterling,David Hughes|Mai Zetterling,NaN,NaN,NaN,NaN,113 minutes,NaN
642,826,"Stanley Kubrick's second film, Killer's Kiss w...",NR,Classics|Drama|Mystery and Suspense,Stanley Kubrick,NaN,"Sep 28, 1955","May 15, 2001",NaN,NaN,67 minutes,NaN
644,828,Robert Stack and Dorothy Malone are Cliff and ...,NR,Action and Adventure|Classics|Drama,NaN,NaN,"Feb 19, 1960","Oct 24, 2006",NaN,NaN,91 minutes,NaN
645,829,International sex symbol Jane Birkin (of BLOW-...,NR,Art House and International|Horror|Mystery and...,Antonio Margheriti,Giovanni Simonelli|Antonio Margheriti,"Jan 1, 1973","Oct 25, 2005",NaN,NaN,95 minutes,Blue Underground
647,831,"Filming weddings is a thankless job, so when A...",NR,Comedy,Pavan Moondi,Pavan Moondi,NaN,NaN,NaN,NaN,98 minutes,Factory 25
648,832,"Based on Russian folklore, this slapstick sati...",NR,Art House and International,Alexander Medvedkin,NaN,NaN,NaN,NaN,NaN,69 minutes,NaN
654,838,The Weight of Water is the story of a blind ad...,NR,Action and Adventure|Documentary,Michael Brown,NaN,NaN,NaN,NaN,NaN,79 minutes,NaN
656,840,"Wrongfully convicted for a hold-up, a war vet ...",NR,Classics|Drama|Mystery and Suspense,Mervyn Le Roy,Sheridan Gibney|Brown Holmes,"Nov 19, 1932","May 10, 2005",NaN,NaN,90 minutes,NaN
658,843,Miners want to drill for billions of dollars w...,NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60 minutes,NaN
661,847,"In this Alfred Hitchcock film, Derrick De Marn...",NR,Classics|Drama|Mystery and Suspense,Alfred Hitchcock,Alma Reville|Charles Bennett|Gerald Savory|Edw...,"Feb 17, 1938","Jul 30, 2002",NaN,NaN,80 minutes,NaN
669,857,Gary Cooper stars as an island drifter who fal...,NR,Drama|Romance,Mark Robson,NaN,NaN,NaN,NaN,NaN,100 minutes,NaN
677,866,Judith Allen stars as Telephone Operator Helen...,NR,Drama,Scott Pembroke,NaN,NaN,NaN,NaN,NaN,61 minutes,NaN
678,867,An original comedy that casts Marcello Mastroi...,NR,Comedy|Romance,Vittorio De Sica,Eduardo De Filippo|Isabella Quarantotti|Cesare...,"Dec 19, 1963","Jun 29, 2004",NaN,NaN,119 minutes,NaN
679,868,Filmmaker Irene Lusztig unearths a dark family...,NR,Art House and International|Documentary|Specia...,Irene Lusztig,Irene Lusztig,NaN,NaN,NaN,NaN,90 minutes,NaN
688,880,"In this musical western, ranch owner ""Lucky"" L...",NR,Western,Joseph Kane,Betty Burbridge,NaN,NaN,NaN,NaN,60 minutes,NaN
693,888,The Knute Rockne legend is largely founded on ...,NR,Classics|Drama,Lloyd Bacon,Robert Buckner,"Jan 1, 1940","Aug 15, 2006",NaN,NaN,98 minutes,NaN
697,895,"After a sexual assault by a random stranger, S...",NR,Drama|Horror|Mystery and Suspense,Eric England,Eric England,"Nov 22, 2013","Mar 18, 2014",$,"3,328",84 minutes,IFC Films
699,897,Just before his demotion to the ranks of minor...,NR,Action and Adventure|Drama,NaN,Frederick Hugh Herbert,NaN,NaN,NaN,NaN,70 minutes,NaN
700,898,To quell the rumors that musical stars Alice F...,NR,Classics|Drama|Musical and Performing Arts|Rom...,Walter Lang,Robert Ellis|Helen Logan,"Nov 22, 1940","Jul 19, 1994",NaN,NaN,94 minutes,NaN
711,913,"For recent retiree Caroline (Fanny Ardant, 8 W...",NR,Comedy|Drama,Marion Vernoux,Marion Vernoux|Fanny Chesnel,NaN,NaN,NaN,NaN,94 minutes,Tribeca Film
713,915,An experiment gone wrong gives new meaning to ...,NR,Horror|Science Fiction and Fantasy,Ian Curteis,NaN,NaN,NaN,NaN,NaN,77 minutes,NaN
714,918,Max Shulman and Robert Paul Smith's Broadway h...,NR,Classics|Comedy|Musical and Performing Arts|Ro...,Charles Walters,NaN,"Jan 1, 1955","May 13, 2008",NaN,NaN,111 minutes,NaN
715,919,The PBS series Great Performances first presen...,NR,Drama,Fielder Cook,Ronald Ribman,"Sep 9, 1986","Feb 18, 2003",NaN,NaN,93 minutes,NaN
718,923,Director Howard Hawks' second western was also...,NR,Action and Adventure|Western,Howard Hawks,Borden Chase|Charles Schnee,NaN,NaN,NaN,NaN,133 minutes,NaN
720,925,"Adapted from the book by David Foster Wallace,...",NR,Comedy|Drama,John Krasinski,John Krasinski,"Sep 25, 2009","Mar 16, 2010",NaN,NaN,80 minutes,IFC
722,928,Cecil B. DeMille's The Greatest Show on Earth ...,NR,Classics|Drama|Kids and Family|Romance,NaN,NaN,"Feb 21, 1952","Apr 6, 2004",NaN,NaN,92 minutes,NaN
724,931,Dilwale Dulhania Le Jayenge (Brave Heart Will ...,NR,Art House and International|Comedy|Kids and Fa...,Aditya Chopra,Aditya Chopra,"Oct 19, 1995","May 18, 2004",NaN,NaN,192 minutes,NaN
727,934,A young man is in danger of losing his inherit...,NR,Classics|Mystery and Suspense,NaN,John Krafft,"Oct 28, 1936","Mar 15, 2005",NaN,NaN,70 minutes,NaN
731,939,When North Korean soldiers attempt to assassin...,NR,Action and Adventure|Art House and Internation...,Woo-Suk Kang|Kang Woo-seok,Kim Heui-jae,"Apr 24, 2003","Dec 1, 2014",NaN,NaN,134 minutes,Cinema Service
734,943,"Classic, heartbreaking neo-realist drama of tw...",NR,Art House and International|Classics|Drama,Vittorio De Sica,Sergio Amidei|Adolfo Franci|Cesare Giulio Viol...,"Aug 26, 1947","May 17, 2011",NaN,NaN,90 minutes,NaN
735,944,The producers of Quartet and Trio concluded th...,NR,Classics|Comedy|Drama,Harold French|Pat Jackson|Anthony Pelissier,NaN,NaN,NaN,NaN,NaN,85 minutes,NaN
739,950,A young man trying to break out of his blue co...,NR,Drama,Chris Kentis,Laura Lau|Chris Kentis,"Apr 11, 1997","Feb 13, 2001",NaN,NaN,96 minutes,NaN
742,957,"J.J. Hunsecker, a powerful New York newspaper ...",NR,Classics|Drama,Alexander Mackendrick,Clifford Odets|Ernest Lehman,"Jun 27, 1957","Jun 19, 2001",NaN,NaN,96 minutes,NaN
743,959,Two young women try to climb the corporate lad...,NR,Art House and International|Drama|Romance,Jean-Claude Brisseau,Jean-Claude Brisseau,"Apr 9, 2003","Nov 23, 2004",NaN,NaN,115 minutes,NaN
745,962,"Punk rocker, performance artist, and persona n...",NR,Documentary|Musical and Performing Arts,Todd Phillips,NaN,"Jan 1, 1994","Jan 25, 2000",NaN,NaN,120 minutes,NaN
747,964,"In 1995, during the making of his TV series Tr...",NR,Documentary|Special Interest,Jonathan Challis|Susan Crook|John Coffey|Ian L...,NaN,"May 11, 2012","Oct 22, 2012",$,"104,286",70 minutes,Magnolia Pictures
750,968,Arnab a typical Bengali man is making his way ...,NR,Art House and International|Horror|Mystery and...,Prosit Roy,Abhishek Bannerjee|Prosit Roy|Rajat Kapoor,NaN,NaN,NaN,NaN,NaN,NaN
767,988,NaN,NR,Horror,NaN,NaN,NaN,NaN,NaN,NaN,83 minutes,NaN
768,992,"In 1988, Taileen slips into a coma after a car...",NR,Horror|Mystery and Suspense,Luis Almeida,Luis Almeida,"Nov 21, 2006","Nov 21, 2006",NaN,NaN,106 minutes,NaN
770,996,A depressed ex-boxer finds his future looking ...,NR,Comedy|Drama|Mystery and Suspense,Nicanor Loreti,NaN,"Nov 5, 2011","Jun 18, 2013",NaN,NaN,85 minutes,NaN
771,997,John Denver stars in this thrilling drama--ori...,NR,Action and Adventure,NaN,NaN,NaN,NaN,NaN,NaN,96 minutes,NaN
772,998,Set amidst the political and economic havoc ca...,NR,Comedy|Mystery and Suspense,Ilkka Jarvilaturi,Paul Kolsby,NaN,NaN,NaN,NaN,99 minutes,NaN
773,999,Yet another teenager discovers how difficult g...,NR,Comedy,Holly Goldberg Sloan,Holly Goldberg Sloan,NaN,NaN,NaN,NaN,90 minutes,NaN
776,1002,No film critic of 1989 could write an assessme...,NR,Action and Adventure|Art House and Internation...,Jacques Rivette,Pascal Bonitzer|Christine Laurent,"Dec 22, 1989","Jan 2, 2002",NaN,NaN,150 minutes,NaN
788,1020,The title character of the Russian Little Vera...,NR,Art House and International|Drama|Romance,Vasili Pichul,Mariya Khmelik,"Apr 14, 1989","Aug 28, 2000",NaN,NaN,130 minutes,NaN
789,1021,NaN,NR,Documentary,Henri Cartier-Bresson,Alfred Lewis Levitt,NaN,NaN,NaN,NaN,33 minutes,NaN

In [125]:
movie_buddget.iloc[[331,335,352,363,364,371,386,394,429,451,483,506,529,547,555,
                   558,560,564,578,592,598,629,638]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
331,32,"Jun 11, 2010",The A-Team,"$110,000,000","$77,222,099","$177,241,171"
335,36,"Nov 1, 2013",Ender's Game,"$110,000,000","$61,737,191","$127,983,283"
352,53,"Apr 27, 2001",Town & Country,"$105,000,000","$6,712,451","$10,364,769"
363,64,"Nov 15, 2002",Harry Potter and the Chamber of Secrets,"$100,000,000","$262,233,381","$879,225,135"
364,65,"Jul 2, 1991",Terminator 2: Judgment Day,"$100,000,000","$203,464,105","$515,419,827"
371,72,"Nov 2, 2007",American Gangster,"$100,000,000","$130,164,645","$267,985,456"
386,87,"Jun 11, 2004",The Stepford Wives,"$100,000,000","$59,475,623","$96,221,971"
394,95,"Jul 23, 2004",Catwoman,"$100,000,000","$40,202,379","$82,145,379"
429,30,"Jul 18, 2001",Jurassic Park III,"$93,000,000","$181,166,115","$365,900,000"
451,52,"Jul 11, 1997",Contact,"$90,000,000","$100,920,329","$165,900,000"
483,84,"Sep 14, 2018",The Predator,"$88,000,000","$51,024,708","$159,487,563"
506,7,"Mar 30, 2012",Mirror Mirror,"$85,000,000","$64,935,167","$173,613,482"
529,30,"Dec 15, 2006",Charlotte's Web,"$82,500,000","$82,985,708","$143,985,708"
547,48,"Jul 12, 2013",Grown Ups 2,"$80,000,000","$133,668,525","$247,023,808"
555,56,"Dec 25, 2008",Bedtime Stories,"$80,000,000","$110,101,975","$221,468,935"
558,59,"Feb 14, 2003",Daredevil,"$80,000,000","$102,543,518","$182,782,518"
560,61,"Jun 6, 1997",Con Air,"$80,000,000","$101,117,573","$224,117,573"
564,65,"Nov 26, 1997",Flubber,"$80,000,000","$92,993,801","$177,993,801"
578,79,"Jul 30, 2004",The Manchurian Candidate,"$80,000,000","$65,948,711","$96,148,711"
592,93,"Dec 20, 2013",Walking with Dinosaurs,"$80,000,000","$36,076,121","$123,368,842"
598,99,"Nov 14, 2003",Looney Tunes: Back in Action,"$80,000,000","$20,950,820","$54,540,662"
629,30,"Jun 30, 2017",Despicable Me 3,"$75,000,000","$264,624,300","$1,034,727,750"
638,39,"Feb 13, 2004",50 First Dates,"$75,000,000","$120,776,832","$196,320,329"

In [16]:
# new names index for NR
no3=[331,335,352,363,364,371,386,394,429,451,483,506,529,547,555,
                   558,560,564,578,592,598,629]

In [127]:
# making sure all system_rating have the same amout of records
# getting system G: need 37
index_G = movie_info[movie_info['rating']=='G'].index
index_G[:50]

Int64Index([  21,   30,   65,   90,  143,  154,  168,  170,  248,  254,  264,
             279,  294,  381,  401,  404,  433,  454,  501,  548,  593,  634,
             702,  704,  792,  795,  810,  892,  894,  958,  994, 1041, 1051,
            1075, 1080, 1102, 1105, 1123, 1147, 1156, 1208, 1209, 1227, 1241,
            1314, 1323, 1325, 1349, 1405, 1439],
           dtype='int64')

In [128]:
movie_info.iloc[[ 21,   30,   65,   90,  143,  154,  168,  170,  248,  254,  264,
             279,  294,  381,  401,  404,  433,  454,  501,  548,  593,  634,
             702,  704,  792,  795,  810,  892,  894,  958,  994, 1041, 1051,
            1075, 1080, 1102, 1105, 1123, 1147, 1156, 1208, 1209, 1227, 1241,
            1314, 1323, 1325, 1349, 1405, 1439]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
21,28,Elvis goes Hawaiian for the second time in thi...,G,Classics|Comedy|Musical and Performing Arts|Ro...,NaN,Allan Weiss|Anthony Lawrence,"Jun 15, 1966","Jan 7, 2003",NaN,NaN,90 minutes,NaN
30,42,"Warner Bros.' ""Perry Mason"" series quietly sli...",G,Action and Adventure|Classics|Drama|Mystery an...,NaN,Frederick Hugh Herbert,NaN,NaN,NaN,NaN,65 minutes,NaN
65,83,"Told in flashback, Affair with a Stranger reco...",G,Comedy|Drama|Kids and Family|Romance,Roy Rowland,Richard Flournoy,NaN,NaN,NaN,NaN,89 minutes,NaN
90,115,"""Toy Story 2"" is the exciting, all-new sequel ...",G,Animation|Comedy|Kids and Family|Science Ficti...,John Lasseter,Doug Chamberlain|Rita Hsiao|Doug Chamberlin|Ch...,"Nov 24, 1999","Oct 17, 2000",NaN,NaN,92 minutes,Buena Vista Pictures
143,187,Tommy (Anthony Rogers) is a young stamp collec...,G,Action and Adventure|Kids and Family|Science F...,Michael Rubbo,Michael Rubbo,"Dec 8, 1988","Oct 24, 2006",NaN,NaN,101 minutes,NaN
154,200,It took some doing to persuade the staunchly C...,G,Classics|Comedy|Drama|Musical and Performing Arts,Leo McCarey,Frank Corvett|Frank Butler|Frank Cavett|Leo Mc...,"May 3, 1944","Feb 6, 2007",NaN,NaN,126 minutes,NaN
168,222,Inasmuch as the spectacular Richard Rodgers an...,G,Action and Adventure|Classics|Comedy|Musical a...,Charles Walters,Sidney Sheldon,"Jan 1, 1962","Apr 26, 2005",NaN,NaN,124 minutes,NaN
170,224,"Steve McQueen stars as the Cincinnati Kid, a c...",G,Classics|Drama,Norman Jewison,NaN,"Oct 15, 1965","May 31, 2005",NaN,NaN,113 minutes,NaN
248,323,"Yes, Paul Newman is a blue-eyed Indian in Homb...",G,Action and Adventure|Western,Martin Ritt,NaN,"Jan 1, 1967","Jun 4, 2002",NaN,NaN,111 minutes,NaN
254,332,ACP Ajay Rathore is transferred to Mumbai to e...,G,Action and Adventure|Art House and International,John Mathew Matthan,NaN,"Apr 30, 1999","Jul 27, 1999",NaN,NaN,155 minutes,NaN
264,349,Lewis Carroll's classic fantasy about a young ...,G,Kids and Family|Science Fiction and Fantasy,John Henderson,NaN,"Jun 1, 1998","Jan 11, 2005",NaN,NaN,83 minutes,NaN
279,368,"Originally Tokyo Monogatari, Yasujiro Ozu's To...",G,Art House and International|Drama,Yasujiro Ozu,NaN,"Nov 3, 1953","Oct 30, 2003",NaN,NaN,134 minutes,NaN
294,388,"Hard-hitting and gritty, this prison film chro...",G,Classics|Drama,Jules Dassin,Richard Brooks,"Jan 1, 1947","Apr 17, 2007",NaN,NaN,94 minutes,Criterion Collection
381,494,This superbly animated children's tale is dire...,G,Animation|Drama|Kids and Family|Science Fictio...,Hayao Miyazaki,Hayao Miyazaki,"Jan 1, 1988","Mar 7, 2006",NaN,NaN,87 minutes,NaN
401,522,A large-format Imax film about the career of M...,G,Documentary|Special Interest|Sports and Fitness,NaN,Jonathan Hock,"May 5, 2000","Feb 13, 2001",NaN,NaN,45 minutes,NaN
404,526,Norman Jewison's adaptation of the long-runnin...,G,Classics|Comedy|Drama|Kids and Family|Musical ...,Norman Jewison,Joseph Stein,"Nov 3, 1971","Jun 30, 1998",NaN,NaN,179 minutes,NaN
433,566,Both actress Judy Davis and director Gillian A...,G,Art House and International|Drama|Romance,Gillian Armstrong,Eleanor Witcombe,"Aug 17, 1979","May 31, 2005",NaN,NaN,101 minutes,Westchester Films
454,596,"""Arctic Tale"" is an epic adventure that explor...",G,Documentary|Special Interest,Adam Ravetch|Sarah Robertson,Linda Woolverton|Mose Richards|Kristin Gore,"Aug 17, 2007","Aug 1, 2017",$,"598,103",86 minutes,Paramount Vantage
501,656,This is the large-screen debut of famous (or i...,G,Kids and Family,Steve Gomer,Stephen White,"Apr 3, 1998","Sep 1, 1998",NaN,NaN,75 minutes,NaN
548,717,One of the first important distinctions to be ...,G,Drama|Special Interest,NaN,NaN,NaN,NaN,NaN,NaN,73 minutes,NaN
593,766,In a film designed to bring smiles to the post...,G,Action and Adventure|Animation|Comedy|Kids and...,Arna Selznick,Peter Sauder,"Dec 31, 1985","Aug 6, 2002",NaN,NaN,76 minutes,NaN
634,817,Based on the Broadway play by Robert Fryer and...,G,Classics|Comedy|Romance,Walter Lang,Phoebe Ephron|Henry Ephron,"May 15, 1957","May 4, 2004",NaN,NaN,104 minutes,NaN
702,901,Winged Migration co-directors Jacques Cluzaud ...,G,Documentary|Drama,Jacques Cluzaud|Jacques Perrin,NaN,"Apr 22, 2010","Oct 19, 2010",$,"19,000,000",103 minutes,Disneynature
704,903,Director James Cameron journeys back to the si...,G,Comedy|Documentary|Science Fiction and Fantasy...,James Cameron,NaN,"Apr 11, 2003","Apr 27, 2004",$,"16,302,332",59 minutes,Buena Vista Distribution
792,1024,"In this musical, Fred Astaire and Burgess Mere...",G,Classics|Comedy|Musical and Performing Arts|Ro...,NaN,Johnny Mercer|Ian McLellan Hunter|Frank Cavett...,"Jan 1, 1940","Jul 25, 2006",NaN,NaN,83 minutes,NaN
795,1028,"Brian Henson, the son of Muppet founder Jim He...",G,Kids and Family|Science Fiction and Fantasy,Brian Henson,Jerry Juhl,"Jan 1, 1992","Oct 8, 2002",NaN,NaN,120 minutes,NaN
810,1047,NaN,G,Drama|Musical and Performing Arts,Nils Tavernier,NaN,NaN,NaN,NaN,NaN,95 minutes,Les Films du Losange
892,1154,Darrell Rooney directed this direct-to-video s...,G,Action and Adventure|Animation|Comedy|Drama|Ki...,Rob LaDuca|Darrell Rooney,Flip Kobler|Cindy Marcus,"Oct 27, 1998","Oct 27, 1998",NaN,NaN,75 minutes,NaN
894,1156,"A blend of live-action and animation, Fun and ...",G,Action and Adventure|Animation|Classics|Comedy...,Jack Kinney|Hamilton Luske|Bill Roberts|Willia...,Ted Sears|Eldon Dedini|Homer Brightman|Harry R...,"Sep 27, 1947","Jun 20, 2000",NaN,NaN,96 minutes,NaN
958,1239,Something mysterious is happening in the Hundr...,G,Animation|Kids and Family,Frank Nissen,Brian Hohlfeld|Evan Spiliotopoulos,"Feb 11, 2005","May 24, 2005",$,"18,013,938",67 minutes,Buena Vista
994,1287,Powaqqatsi was the second of the feature-lengt...,G,Art House and International|Documentary|Drama|...,Godfrey Reggio,Godfrey Reggio|Ken Richards,"Apr 29, 1988","Sep 17, 2002",NaN,NaN,95 minutes,NaN
1041,1346,This moving prison drama tells the fascinating...,G,Classics|Drama|Mystery and Suspense,John Frankenheimer,Elizabeth Stroud|Guy Trosper|Guy Troper,"Jul 3, 1962","Mar 6, 2001",NaN,NaN,143 minutes,NaN
1051,1358,"Returning to the Ireland of his birth, directo...",G,Classics|Comedy|Drama|Romance,John Ford,NaN,"Aug 14, 1952","Feb 20, 2001",NaN,NaN,129 minutes,NaN
1075,1386,A pair of bumbling vampire-hunters attempts to...,G,Art House and International|Comedy|Horror,Roman Polanski,NaN,"Nov 13, 1967","Oct 5, 2004",NaN,NaN,107 minutes,NaN
1080,1391,Murder by Contract was more professionally ben...,G,Drama|Mystery and Suspense,Irving Lerner,Benjamin Simcoe,"Dec 1, 1958","Nov 3, 2009",NaN,NaN,81 minutes,NaN
1102,1418,A comedy drama set on a Yorkshire chicken farm...,G,Action and Adventure|Animation|Comedy|Drama|Ki...,Peter Lord|Nick Park,Jack Rosenthal|Karey Kirkpatrick,"Jun 21, 2000","Nov 21, 2000",$,"106,604,314",85 minutes,NaN
1105,1423,"In this comical Disney espionage adventure, a ...",G,Action and Adventure|Comedy|Kids and Family|My...,Robert Stevenson,Bill Walsh,"Aug 6, 1975","Nov 18, 1988",NaN,NaN,93 minutes,NaN
1123,1448,"Frank D. Gilroy's Pulitzer-winning ""kitchen si...",G,Classics|Drama,Ulu Grosbard,NaN,"Oct 13, 1968","May 30, 1996",NaN,NaN,108 minutes,NaN
1147,1477,In this sequel to the Academy Award -winning h...,G,Comedy|Kids and Family|Science Fiction and Fan...,George Miller,Dick-King Smith|Judy Morris|Mark Lamprell,"Nov 25, 1998","May 4, 1999",NaN,NaN,90 minutes,Universal Studios
1156,1488,"Christopher Lloyd, Kelly Ripa, Nicollette Sher...",G,Animation|Kids and Family|Science Fiction and ...,Ben Stassen,Domonic Paris|Dominic Paris,"Aug 15, 2008","Dec 2, 2008",$,"13,592,311",84 minutes,Summit Entertainment
1208,1554,The movie chronicles the adventures of a young...,G,Kids and Family|Musical and Performing Arts,Britt Allcroft,Britt Allcroft,"Jul 26, 2000","Oct 31, 2000",$,"2,027,042",95 minutes,Destination Films
1209,1555,This western spoof tells the story of a tough ...,G,Classics|Comedy|Musical and Performing Arts|We...,Elliot Silverstein|Elliott Silverstein,Walter Newman|Roy Chanslor|Frank Pierson,"Jun 24, 1965","Aug 8, 2000",NaN,NaN,97 minutes,NaN
1227,1583,This stark British/Norwegian film closely adhe...,G,Art House and International|Drama,Casper Wrede|Caspar Wrede,Ronald Harwood,NaN,NaN,NaN,NaN,100 minutes,NaN
1241,1604,Children's book authors Jean and Laurent de Br...,G,Animation|Art House and International|Kids and...,Alan Bunce,NaN,"Jul 28, 1989","Jan 20, 2004",NaN,NaN,75 minutes,NaN
1314,1699,The popular animated duo of cat and mouse team...,G,Animation|Comedy|Kids and Family,Phil Roman,Dennis Marks,"Jan 1, 1992","Mar 12, 2002",NaN,NaN,80 minutes,NaN
1323,1711,"Directed by Garry Marshall, The Princess Diari...",G,Comedy|Kids and Family,Garry Marshall,Shonda Rhimes,"Aug 11, 2004","Dec 14, 2004",$,"95,111,012",113 minutes,NaN
1325,1713,"In this second of his saga of four seasons, wr...",G,Drama|Romance,Eric Rohmer,NaN,"Jan 29, 1992","Feb 9, 2015",NaN,NaN,114 minutes,Big World Pictures
1349,1743,This animated feature chronicles the trials an...,G,Animation|Kids and Family|Science Fiction and ...,Art Vitello,NaN,NaN,NaN,NaN,NaN,100 minutes,NaN
1405,1813,Astronauts unwittingly bring some alien goo ab...,G,Drama|Horror|Science Fiction and Fantasy,Kinji Fukasaku,Charles Sinclair|Tom Rowe|William Finger,"Jan 1, 1969","Sep 25, 1991",NaN,NaN,90 minutes,NaN
1439,1855,Following the surprisingly successful children...,G,Action and Adventure|Kids and Family|Science F...,NaN,Michael Ende|Karin Howard,"Jun 1, 1991","Sep 4, 2001",NaN,NaN,90 minutes,NaN

In [129]:
movie_buddget.iloc[[433,994,1075,1227]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
433,34,"Feb 14, 2013",A Good Day to Die Hard,"$92,000,000","$67,349,198","$304,249,198"
994,95,"Nov 10, 2017",Murder on the Orient Express,"$55,000,000","$102,826,543","$345,922,730"
1075,76,"Apr 16, 2003",Bulletproof Monk,"$52,000,000","$23,010,607","$23,010,607"
1227,28,"Oct 20, 2000",Bedazzled,"$48,000,000","$37,879,996","$90,376,224"

In [17]:
# new names index for G
no4 = [433,994,1075,1227]

Based on the indexes on the 'G' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was G-rated. The 37 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [131]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Ace Wonder':
        print('yes')

In [18]:
#informtions on the movies needed for g
# the name of the movies
name_mojo3 = ['The Sound of Music','Mary Poppins','The Little Mermaid','Singin\' in the Rain','The Great Muppet Caper',
              'Snow White and the Seven Dwarfs',
             'Fiddler on the Roof','The Swan Princess','The Jungle Book(1967) ','Space Buddies','Muppets From Space','',
             'The League of Extraordinary Gentlemen','Timeline','Walking Tall','The Last Starfighter','WALL• E',
             'Dark Star','Ice Station Zebra (1968)','Fear of Rain','Angry Men','Fight Club ','Rear Window',
             'Psycho','The Usual Suspects','Se7en','Memento','Reindeer Games','The Little Prince',
             'Clue','Rear Window','The Night of the Hunter','The Lady Vanishes','North by Northwest',
             'Palm Springs','Tell No One','']
# ratings of the movies
rating_mojo3 = [8,7.8,6,8.2,7.2,8.4,8
             ,6.5,7.6,5.3,5.8,2.6,6.3
             ,6.4,7.5,6.3,6.6,8.9,5
             ,7.4,3,5,6.2,7,9
             ,5,6,4,8,9,7
             ,8,9,8.4,8.2,7.8,8.3,
            7.6]
# worldwide gross
worldwide_gross_mojo3 = ['$2,389,466,546','$862,312,959','$480,525,371','$71,120,067','$94,187,915','$7,777,009,429',
             '$526,845,491','$17,457,221','$2,992,680,000','$32,193,471','$35,477,245','$179,265,204',
             '$43,935,763','$57,223,890','$73,882,280','$521,311,860','$210,026','$120,632,501',
             '$18,874,928','$160,279,319','$267,162,411','$442,982,993','$59,940,959','$570,929,851',
             '$61,478,513','$49,787,168','$97,571,250','$36,223,936','$18,595,479','$358,606,989','$9,069,890',
             '$153,037','$120,500,680','$922,560','$765,535','$44,206,461','$10,741,196']
# domestic gross
domestic_gross_mojo3 = ['$1,362,598,652','$862,111,155','$241,113,495','$70,770,294','$94,187,915','$3,440,591,503',
             '$526,838,116','$17,457,221','$583,818,411','$32,193,471','$26,422,150','$66,465,204',
             '$19,481,943','$46,437,717','$73,882,280','$223,808,164','$210,026','$35,344,555',
             '$18,874,928','$58,849,169','$267,162,411','$442,982,993','$40,613,705','$174,215,943',
             '$39,535,197','$36,167,651','$1,339,152','$36,223,936','$18,473,333','$252,778,746','$9,069,890',
             '$153,037','$120,500,680','$922,560','$164,000','$44,206,461','$2,395,378']
             
# product budget
product_budget_mojo3 = ['$68,457,910','$42,147,896','$86,464,398','$24,976,016','$42,255,342','$27,721,876',
             '$58,901,156','$37,516,831','$31,668,571','$9,000,000','$38,141,403','$78,000,000',
             '$80,000,000','$46,000,000','$38,569,694','$180,000,000','$203,761','$61,468,791',
             '$3,208,738','$100,121,184','$19,366,097','$7,149,276','$10,439,840','$57,419,118',
             '$13,929,091','$55,716,364','$77,500,000','$36,115,104','$12,673,316','$19,366,097','$7,755,687',
             '$9,618,685','$27,949,131','$1,241,979','$5,000,000','$18,804,194','$5,783,721']

In [133]:
# making sure all system_rating have the same amout of records
# getting the index of  system R: need 21
index_R = movie_info[movie_info['rating']=='R'].index
index_R[300:350]

Int64Index([839, 842, 843, 846, 848, 849, 858, 861, 862, 864, 868, 872, 874,
            875, 876, 880, 881, 898, 899, 900, 901, 903, 906, 909, 910, 912,
            915, 917, 925, 927, 930, 935, 938, 939, 942, 943, 947, 951, 953,
            955, 967, 968, 971, 973, 975, 977, 979, 982, 996, 997],
           dtype='int64')

In [134]:
movie_info.iloc[[839, 842, 843, 846, 848, 849, 858, 861, 862, 864, 868, 872, 874,
            875, 876, 880, 881, 898, 899, 900, 901, 903, 906, 909, 910, 912,
            915, 917, 925, 927, 930, 935, 938, 939, 942, 943, 947, 951, 953,
            955, 967, 968, 971, 973, 975, 977, 979, 982, 996, 997]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
839,1084,"Shy, sensitive April (Emma Roberts) is the cla...",R,Drama,Gia Coppola,Gia Coppola,"May 9, 2014","Sep 9, 2014",$,"406,235",100 minutes,Tribeca Film
842,1089,Writer/director Gus Van Sant's early bid for b...,R,Comedy|Drama|Science Fiction and Fantasy,Gus Van Sant,Gus Van Sant,"May 20, 1994","Nov 2, 2004",NaN,NaN,100 minutes,NaN
843,1090,Voter apathy in the United States is at an all...,R,Classics|Comedy,NaN,Jack Margolis,"Apr 1, 1975","Sep 2, 2008",NaN,NaN,95 minutes,NaN
846,1093,Tennessee Williams' 27 Wagons Full of Cotton w...,R,Classics|Comedy,Elia Kazan,Tennessee Williams,"Dec 18, 1956","Jul 9, 2003",NaN,NaN,114 minutes,NaN
848,1095,Kevin Smith's follow-up to his unexpected hit ...,R,Comedy,Kevin Smith,Kevin Smith,"Oct 20, 1995","Jul 18, 2000",NaN,NaN,95 minutes,NaN
849,1096,Harry Hook directed this second screen adaptat...,R,Action and Adventure|Drama,Harry Hook,Jay Presson Allen|Sara Schiff,"Jan 1, 1989","Nov 20, 2001",NaN,NaN,90 minutes,NaN
858,1108,Chris has a job interview in Raleigh in three ...,R,Horror|Mystery and Suspense,Rob Schmidt,NaN,"May 30, 2003","Oct 14, 2003",$,"15,176,515",95 minutes,20th Century Fox Distribution
861,1113,"Luke Wilson, Giovanni Ribisi, and Gabriel Mach...",R,Comedy|Drama,George Gallo,George Gallo|Andy Weiss,"Aug 6, 2010","Feb 8, 2011",$,"723,714",112 minutes,Paramount Pictures
862,1114,"When four lifelong friends-Regina Hall, Queen ...",R,Comedy|Drama,NaN,Kenya Barris|Tracy Oliver,"Jul 21, 2017","Oct 17, 2017",$,"115,088,305",122 minutes,Universal Pictures
864,1116,In director Dennis Hopper's comedy reminiscent...,R,Comedy,Dennis Hopper,John Rice|Joe Batteer|Dan Gilroy|Joe Gayton,"Apr 22, 1994","Dec 5, 2000",NaN,NaN,105 minutes,NaN
868,1122,TOUCHY FEELY is a closely observed examination...,R,Drama,Lynn Shelton,Lynn Shelton,"Sep 6, 2013","Dec 10, 2013",$,"35,966",90 minutes,Magnolia Pictures
872,1128,When an aging executive takes a vacation to Ri...,R,Comedy|Romance,Stanley Donen,Charlie Peters|Larry Gelbart,"Feb 17, 1984","May 22, 2001",NaN,NaN,90 minutes,NaN
874,1132,Driven over the edge by drugs and crime at the...,R,Action and Adventure|Drama,Albert Pyun,John Stockwell|Marty Ross|Scott Fields,"Jun 1, 1986","Feb 24, 2015",NaN,NaN,96 minutes,NaN
875,1133,This contemporary western stars Dermot Mulrone...,R,Drama|Mystery and Suspense,Michael Fields,Richard Ford Grayling,"Jun 1, 1991","Feb 5, 1992",NaN,NaN,94 minutes,NaN
876,1134,"A homage to Von Sternberg's 'The Blue Angel,' ...",R,Documentary|Drama|Special Interest,Rainer Werner Fassbinder,NaN,NaN,NaN,NaN,NaN,57 minutes,NaN
880,1140,Johnny Knoxville and his crew of fun-loving ma...,R,Comedy|Documentary,Jeff Tremaine,Jeff Tremaine|Johnny Knoxville,"Oct 25, 2002","Mar 25, 2003",$,"64,209,101",84 minutes,Paramount Pictures
881,1141,"While traveling in the Midwest, two aging fur-...",R,Action and Adventure|Western,Richard Lang,NaN,NaN,NaN,NaN,NaN,102 minutes,NaN
898,1161,Screenwriter Nimrod Antal makes an impressive ...,R,Action and Adventure|Art House and Internation...,NaN,NaN,"Apr 1, 2005","Aug 30, 2005",$,"116,783",105 minutes,ThinkFilm Inc.
899,1162,SNL alumni Tina Fey steps into the well worn s...,R,Comedy|Drama,Glenn Ficarra|John Requa,Robert Carlock,"Mar 4, 2016","Jun 28, 2016",$,"18,356,529",111 minutes,Paramount Pictures
900,1163,"Based on Peter Turner's memoir, the film follo...",R,Art House and International|Drama|Romance,Paul McGuigan,Matt Greenhalgh,"Dec 29, 2017","Apr 24, 2018",NaN,NaN,105 minutes,Sony Pictures Classics
901,1164,"""Mary Queen of Scots"" explores the turbulent l...",R,Drama,Josie Rourke,Beau Willimon,NaN,NaN,NaN,NaN,112 minutes,Focus Features
903,1167,"In this wickedly funny screwball satire, Mel C...",R,Comedy,NaN,NaN,"Mar 22, 1996","Jun 15, 1999",NaN,NaN,93 minutes,Miramax Films
906,1170,A violent and psychotic rapist is released fro...,R,Art House and International|Comedy|Drama,Tony Bill,John Patrick Shanley,"Jan 1, 1987","Sep 18, 2007",NaN,NaN,92 minutes,NaN
909,1173,"In this film, set in the 15th century, Anatoly...",R,Art House and International|Drama,Andrei Tarkovsky,Andrey Konchalovskiy|Andrei Tarkovsky,"Jan 1, 1973","Feb 2, 1999",NaN,NaN,205 minutes,NaN
910,1175,This Chinese saga chronicles 30 years in the l...,R,Art House and International|Drama,Yimou Zhang,Lu Wei|Yu Hua,"Dec 16, 1994","Jul 1, 2003",NaN,NaN,125 minutes,NaN
912,1179,Loosely based on former policeman Joseph Wamba...,R,Comedy|Drama,Robert Aldrich,Christopher Knopf|Joseph Wambaugh,NaN,NaN,NaN,NaN,119 minutes,NaN
915,1183,After making a striking directorial debut with...,R,Comedy|Drama|Romance,Sofia Coppola,Sofia Coppola,"Sep 26, 2003","Feb 3, 2004",$,"44,566,004",102 minutes,Focus Features
917,1186,In the time just preceding Castro's takeover o...,R,Drama|Romance,Sydney Pollack,David Rayfiel|Judith Rascoe|Paul Schrader,"Jan 1, 1990","Nov 17, 1998",NaN,NaN,144 minutes,NaN
925,1197,1967-1976 As one of history's greatest fashion...,R,Art House and International|Drama|Special Inte...,Bertrand Bonello,Bertrand Bonello|Thomas Bidegain,"May 8, 2015","Sep 22, 2015",NaN,NaN,135 minutes,Sony Pictures Classics
927,1200,In 1881 a younger member of the notorious Jame...,R,Action and Adventure|Drama|Western,Andrew Dominik,Andrew Dominik,"Oct 5, 2007","Feb 5, 2008",$,"3,900,000",159 minutes,Warner Bros. Pictures
930,1207,"Directed by Nicholas Racz, The Burial Society ...",R,Drama|Mystery and Suspense,Nicholas Racz,NaN,"Jan 11, 2003","Aug 29, 2006",NaN,NaN,95 minutes,Regent Releasing
935,1214,"Sissy Spacek, Troy Garity, and music icon Dave...",R,Drama|Mystery and Suspense,Perry Moore|Hunter Hill,Hunter Hill|Perry Moore,"Nov 7, 2008","Mar 3, 2009",NaN,NaN,93 minutes,Screen Media Films
938,1217,"For decades, the South American metropolis of ...",R,Action and Adventure|Drama,NaN,NaN,"Aug 17, 2007","Oct 28, 2008",NaN,NaN,114 minutes,IFC Films
939,1218,A young woman searches for love in New York Ci...,R,Comedy|Romance,Christian Ditter,Abby Kohn|Marc Silverstein|Dana Fox,"Feb 12, 2016","May 24, 2016",NaN,NaN,110 minutes,Warner Bros. Pictures
942,1221,"Jim Jarmusch takes his quirky, uniquely modern...",R,Drama|Science Fiction and Fantasy|Western,Jim Jarmusch,Jim Jarmusch,"May 26, 1995","Jul 3, 2001",NaN,NaN,121 minutes,NaN
943,1222,American independent filmmaker Paul F. Ryan ma...,R,Drama,NaN,NaN,"Sep 5, 2003","Oct 14, 2003",NaN,NaN,132 minutes,DEJ Productions
947,1226,Kiefer Sutherland won a Genie Award for his pe...,R,Drama,NaN,NaN,NaN,NaN,NaN,NaN,107 minutes,NaN
951,1231,"THE ROVER, David Michod's highly anticipated f...",R,Mystery and Suspense|Science Fiction and Fanta...,NaN,NaN,"Jun 13, 2014","Sep 23, 2014",$,"709,133",103 minutes,A24 Films
953,1234,Guy Maddin and George Toles wrote this bizarre...,R,Comedy|Drama|Special Interest,Guy Maddin,Guy Maddin,"Aug 27, 1993","Mar 24, 2009",NaN,NaN,100 minutes,NaN
955,1236,"AMERICAN PASTORAL follows Seymour ""Swede"" Levo...",R,Drama,Ewan McGregor,John Romano,"Oct 21, 2016","Feb 7, 2017",$,"541,457",126 minutes,Lakeshore Entertainment
967,1256,Marc Forster's psychological thriller Stay sta...,R,Drama|Mystery and Suspense|Science Fiction and...,Marc Forster,David Benioff,"Oct 21, 2005","Mar 28, 2006",$,"3,349,167",99 minutes,20th Century Fox
968,1257,"Ribald, violent, surreal and satirical, Marqui...",R,Animation|Art House and International|Comedy|S...,Henri Xhonneux,Henri Xhonneux|Roland Topor,NaN,NaN,NaN,NaN,88 minutes,NaN
971,1261,"In the tradition of Fried Green Tomatoes, this...",R,Comedy|Drama,Herbert Ross,Don Roos,"Feb 3, 1995","Nov 6, 2001",NaN,NaN,115 minutes,NaN
973,1264,The Super centers on the mysterious disappeara...,R,Mystery and Suspense,Stephan Rick,NaN,"Oct 19, 2018","Dec 18, 2018",NaN,NaN,90 minutes,NaN
975,1266,"Slow-moving and dark, this Klute clone stars T...",R,Drama|Mystery and Suspense,Gordon Willis,NaN,NaN,NaN,NaN,NaN,96 minutes,NaN
977,1268,"After ten years of marriage, Jeff and Nealy La...",R,Comedy,Jacob Aaron Estes,Jacob Aaron Estes,"Nov 2, 2012","Apr 30, 2013",$,"63,595",91 minutes,The Weinstein Company
979,1271,"In 2003, respected filmmaker and screenwriter ...",R,Horror,Paul Schrader,NaN,"May 20, 2005","Oct 25, 2005",NaN,NaN,111 minutes,NaN
982,1274,Set during the 1950s in a small coastal Englis...,R,Comedy|Drama,Philip Goodhew,Philip Goodhew,"Sep 10, 1996","Feb 10, 1998",NaN,NaN,105 minutes,NaN
996,1289,"In this film, Susan Anspach, an American house...",R,Art House and International|Comedy|Drama,Dusan Makavejev,NaN,"Nov 8, 1981","Sep 11, 2001",NaN,NaN,98 minutes,NaN
997,1290,It has been two decades since master filmmaker...,R,Action and Adventure|Drama|Horror|Mystery and ...,NaN,NaN,"Jun 24, 2005","Oct 18, 2005",$,"20,433,940",92 minutes,Universal Pictures

In [135]:
movie_buddget.iloc[[568,572,590,599,603,613,636,639,646,650,668,706,738,752,763,816,900,
                   906,909,910,925]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
568,69,"Sep 28, 2018",Smallfoot,"$80,000,000","$83,240,103","$213,691,277"
572,73,"Aug 8, 1997",Conspiracy Theory,"$80,000,000","$76,118,990","$142,783,718"
590,91,"Dec 13, 1996",Mars Attacks!,"$80,000,000","$37,771,017","$101,371,017"
599,100,"Dec 18, 2009",Nine,"$80,000,000","$19,676,965","$53,508,858"
603,4,"Dec 25, 1997",The Postman,"$80,000,000","$17,650,704","$20,841,123"
613,14,"Oct 4, 2002",Red Dragon,"$78,000,000","$92,955,420","$206,455,420"
636,37,"Jun 27, 2008",Wanted,"$75,000,000","$134,508,551","$342,416,460"
639,40,"Jul 20, 2007",Hairspray,"$75,000,000","$118,871,849","$203,035,572"
646,47,"Feb 18, 2005",Constantine,"$75,000,000","$75,976,178","$221,594,911"
650,51,"Apr 16, 1999",Life,"$75,000,000","$64,062,587","$73,521,587"
668,69,"Jan 15, 1999",Virus,"$75,000,000","$14,010,690","$30,626,690"
706,7,"Dec 14, 2001",Vanilla Sky,"$70,000,000","$100,614,858","$202,726,605"
738,39,"Jan 16, 1998",Hard Rain,"$70,000,000","$19,870,567","$19,870,567"
752,53,"Jun 30, 2010",The Twilight Saga: Eclipse,"$68,000,000","$300,531,751","$706,102,828"
763,64,"Oct 10, 2008",Body of Lies,"$67,500,000","$39,394,666","$118,556,530"
816,17,"Dec 25, 2016",Live by Night,"$65,000,000","$10,378,555","$21,774,432"
900,1,"Nov 26, 1997",Alien: Resurrection,"$60,000,000","$47,795,018","$160,700,000"
906,7,"Jun 19, 2009",Year One,"$60,000,000","$43,337,279","$57,604,723"
909,10,"Feb 19, 2002",Reign of Fire,"$60,000,000","$43,061,982","$82,150,183"
910,11,"Nov 20, 2009",Planet 51,"$60,000,000","$42,194,060","$108,996,113"
925,26,"Aug 21, 2013",The Mortal Instruments: City of Bones,"$60,000,000","$31,165,421","$75,965,567"

In [19]:
# new names index for R
no5 = [568,572,590,599,603,613,636,639,646,650,668,706,738,752,763,816,900,
                   906,909]

Based on the indexes on the 'R' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was R-rated. The 24 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [20]:
# getting system PG name:need 35
names1=[]
for i in no1:
    names1.append(movie_buddget.movie[i])
names1[:8]

['The Mummy',
 'Killers',
 'Priest',
 'The Avengers',
 'The Kid Who Would Be King',
 'Instinct',
 "A Bug's Life",
 'Colombiana']

In [21]:
# aading names1, the names of the PG movies to the orignal 
for i in names1:
    name_movies.append(i)
len(name_movies)

64

In [22]:
# getting system NR name:need 26
names4=[]
for i in no3:
    names4.append(movie_buddget.movie[i])
names4[:9]

['The A-Team',
 "Ender's Game",
 'Town & Country',
 'Harry Potter and the Chamber of Secrets',
 'Terminator 2: Judgment Day',
 'American Gangster',
 'The Stepford Wives',
 'Catwoman',
 'Jurassic Park III']

In [23]:
# getting system R name:need 26
names5=[]
for i in no5:
    names5.append(movie_buddget.movie[i])
names5[:9]

['Smallfoot',
 'Conspiracy Theory',
 'Mars Attacks!',
 'Nine',
 'The Postman',
 'Red Dragon',
 'Wanted',
 'Hairspray',
 'Constantine']

In [24]:
# getting system G name:need 41
names3=[]
for i in no4:
    names3.append(movie_buddget.movie[i])
names3[:9]

['A Good Day to Die Hard',
 'Murder on the Orient Express',
 'Bulletproof Monk',
 'Bedazzled']

In [25]:
# aading names4, the names of the NR movies to the orignal 
for i in names4:
    name_movies.append(i)
len(name_movies)

86

In [26]:
# aading names4, the names of the R movies to the orignal 
for i in names5:
    name_movies.append(i)
len(name_movies)

105

In [27]:
# aading names4, the names of the G movies to the orignal 
for i in names3:
    name_movies.append(i)
len(name_movies)

109

In [28]:
#getting the index of the names to get other info from dataframe
index = []
for i in name_movies:
    index.append(list(movie_buddget[movie_buddget['movie']==i].index))
len(index)

109

In [29]:
#checking index to see integers that are not needed
index

[[18],
 [25],
 [45],
 [68],
 [72],
 [74],
 [90],
 [99],
 [100],
 [106],
 [125],
 [134, 2485],
 [145],
 [146],
 [155],
 [179],
 [184],
 [187],
 [193],
 [211],
 [219],
 [237],
 [238],
 [241],
 [255],
 [263],
 [275],
 [285],
 [296],
 [311],
 [312],
 [313],
 [317],
 [322],
 [327],
 [331],
 [348],
 [359, 3381],
 [360],
 [362],
 [363],
 [364],
 [367],
 [382],
 [384],
 [387],
 [390],
 [38, 408],
 [425],
 [428],
 [429],
 [447],
 [467],
 [473],
 [479],
 [64, 543],
 [653],
 [928],
 [26, 934],
 [954],
 [1028],
 [1252],
 [1459],
 [1546],
 [331],
 [335],
 [352],
 [363],
 [364],
 [371],
 [386],
 [394],
 [429],
 [451],
 [483],
 [506],
 [529],
 [547],
 [555],
 [558],
 [560],
 [564],
 [578],
 [592],
 [598],
 [629],
 [568],
 [572],
 [590],
 [599],
 [603],
 [613],
 [636],
 [639],
 [646],
 [650, 965],
 [668],
 [706],
 [738],
 [752],
 [763],
 [816],
 [900],
 [906],
 [909],
 [433],
 [994],
 [1075],
 [1227]]

In [30]:
# Turning nested list to regular list
from funcy import flatten,isa
flat_list = flatten(index)

In [31]:
# converting list of list into int 
newflat_list = []
for i in flat_list:
    i=int(i)
    newflat_list.append(i)
len(newflat_list)

115

In [32]:
# removing integers that are not needed
newflat_list1 = []
for i in newflat_list:
    if i == 2485:continue
    if i == 3381:continue
    if i == 965:continue
    if i == 408:continue
    
    else: newflat_list1.append(i)

In [33]:
len(newflat_list1)

111

Now that the names have been updated with the new indexes, we use it to get the rest of the key components from the original dataframe to add to the new dataframe.

In [34]:
# using the updated indexes to get the new and old ratings
rating = []
for x in newflat_list1:
    rating.append(ratings.averagerating[x])
len(rating)

111

In [35]:
# using the updated indexes to get the new and old ratings
name_movies = []
for x in newflat_list1:
    name_movies.append(movie_buddget.movie[x])
len(rating)

111

In [36]:
#using the updated indexes to get thenew and old system ratings
system_rating = []
for x in newflat_list1:
    system_rating.append(movie_info.rating[x])
len(system_rating)

111

In [37]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'PG-13': 9, 'R': 42, 'PG': 13, 'NR': 42, 'G': 5})

In [38]:
#using the updated indexes to get the new and old product budgets
product_budget = []
for x in newflat_list1:
    product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

111

In [39]:
#using the updated indexes to get the new and old domestic gross
domestic_gross = []
for x in newflat_list1:
    domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

111

In [40]:
# using the updated indexes to get the new and old worldwide gross
worldwide_gross = []
for x in newflat_list1:
    worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

111

In [41]:
# getting system PG-13 name:need 29
names2=[]
for i in name_mojo1:
    names2.append(i)
len(names2)

33

In [42]:
# getting system G name:need 37
names3=[]
for i in name_mojo3:
    names3.append(i)
len(names3)

37

In [43]:
# getting system PG name:need 25
names1=[]
for i in name_mojo2:
    names1.append(i)
len(names1)

29

In [44]:
# add new 'PG-13' names to the original
for i in names2:
    name_movies.append(i)
len(name_movies)

144

In [45]:
# add new 'PG-13' worldwide gross to the original
for i in worldwide_gross_mojo1:
    worldwide_gross.append(i)
len(worldwide_gross)

144

In [46]:
# add new 'PG-13' domestic gross to the original
for i in domestic_gross_mojo1:
    domestic_gross.append(i)
len(domestic_gross)

144

In [47]:
# add new 'PG-13' product budget to the original
for i in product_budget_mojo1:
    product_budget.append(i)
len(product_budget)

144

In [48]:
pg13 = ['PG-13']*33
for i in pg13:
    system_rating.append(i)
len(system_rating)

144

In [49]:
# add new 'G' names to the original
for i in names3:
    name_movies.append(i)
len(name_movies)

181

In [50]:
# add new 'G' worldwide gross to the original
for i in worldwide_gross_mojo3:
    worldwide_gross.append(i)
len(worldwide_gross)

181

In [51]:
# add new 'G' domestic gross to the original
for i in domestic_gross_mojo3:
    domestic_gross.append(i)
len(domestic_gross)

181

In [52]:
# add new 'G' product budget to the original
for i in product_budget_mojo3:
    product_budget.append(i)
len(product_budget)

181

In [53]:
pg13 = ['G']*37
for i in pg13:
    system_rating.append(i)
len(system_rating)

181

In [54]:
# add new 'PG' names to the original
for i in names1:
    name_movies.append(i)
len(name_movies)

210

In [55]:
# add new 'PG' worldwide gross to the original
for i in worldwide_gross_mojo2:
    worldwide_gross.append(i)
len(worldwide_gross)

210

In [56]:
# add new 'PG' domestic gross to the original
for i in domestic_gross_mojo2:
    domestic_gross.append(i)
len(domestic_gross)

210

In [57]:
# add new 'PG' product budget to the original
for i in product_budget_mojoo2:
    product_budget.append(i)
len(product_budget)

210

In [58]:
pg1 = ['PG']*29
for i in pg1:
    system_rating.append(i)
len(system_rating)

210

In [59]:
# adding rating from mojo to the original
for i in rating_mojo1:
    rating.append(i)
len(rating)

144

In [60]:
# adding rating from mojo to the original
for i in rating_mojo3:
    rating.append(i)
len(rating)

182

In [61]:
# adding rating from mojo to the original
for i in rating_mojo2:
    rating.append(i)
len(rating)

210

In [62]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'PG-13': 42, 'R': 42, 'PG': 42, 'NR': 42, 'G': 42})

Now that all the new indexs has been idnetified they will be added to the new dataframe needed to create the five interactive graphs.

All the information have been gathered, the script below uses it to create a new and updated dataframe.

In [63]:
all_ArtHouseandIntern_info = pd.DataFrame({'Name':name_movies,'System_ratings':system_rating,'Rating':rating,'Worlwide_gross':worldwide_gross,
                               'Domestic_gross':domestic_gross,'Product_budget':product_budget})
all_ArtHouseandIntern_info1=all_ArtHouseandIntern_info.dropna()
all_ArtHouseandIntern_info1 = all_ArtHouseandIntern_info[all_ArtHouseandIntern_info.Name !='Moonfall']

Now that the dataframe has been updated, Worldwide Gross, Product Budget and Domestic Gross has to be converted from string to int.

In [64]:
# turning Worldwide gross into int
storage1 = []
storage2 = []
total_gross=[]
for i in  all_ArtHouseandIntern_info1.dropna().Worlwide_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    total_gross.append(i)
len(total_gross)

210

In [65]:
# turning Produt budget  into int
storage1 = []
storage2 = []
budget=[]
for i in  all_ArtHouseandIntern_info1.dropna().Product_budget:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    budget.append(i)
len(budget)

210

In [66]:
# turning Domestic gross into int
storage1 = []
storage2 = []
Doomestic_gross=[]
for i in  all_ArtHouseandIntern_info1.dropna().Domestic_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    Doomestic_gross.append(i)
len(Doomestic_gross)

210

In [67]:
#drop all the NA from the dataframe
all_ArtHouseandIntern_info1 = all_ArtHouseandIntern_info1.dropna()


#adding all the string componnets that have been converted to dataframe
all_ArtHouseandIntern_info1['Buget']=budget
all_ArtHouseandIntern_info1['Total_gross']=total_gross
all_ArtHouseandIntern_info1['Domestic_total']=Doomestic_gross
all_ArtHouseandIntern_info1[190:]

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total
190,Under the Skin,PG,7.0,"$5,735,963","$2,614,251","$13,300,000",13300000,5735963,2614251
191,Midnight in Paris,PG,6.4,"$153,959,590","$56,817,045","$17,000,000",17000000,153959590,56817045
192,Frida,PG,8.9,"$56,300,000","$25,900,000","$12,000,000",12000000,56300000,25900000
193,Girl with a Pearl Earring,PG,7.4,"$31,466,789","$11,670,971","$12,000,000",12000000,31466789,11670971
194,Mr. Turner,PG,6.9,"$22,200,000","$3,958,500","$11,641,518",11641518,22200000,3958500
195,The Tree of Life,PG,6.8,"$58,409,247","$13,303,319","$32,000,000",32000000,58409247,13303319
196,Waste Land,PG,7.4,"$291,307","$187,716","$1,500,000",1500000,291307,187716
197,Rivers and Tides,PG,5.3,"$5,042,641","$3,293,762","$$898,186",898186,5042641,3293762
198,Moonlight,PG,8.0,"$65,300,000","$27,854,932","$4,000,000",4000000,65300000,27854932
199,3 Ninjas,PG,7.0,"$54,777,551","$54,776,983","$4,722,153",4722153,54777551,54776983
200,Karate Kid,PG,7.3,"$335,299,206","$233,515,218","$20,570,503",20570503,335299206,233515218
201,Walt Before Mickey,PG,6.0,"$476,046","$476,046","$568,000",568000,476046,476046
202,Loving Vincent,PG,8.0,"$42,187,665","$6,735,118","$5,500,000",5500000,42187665,6735118
203,The Best Offer,PG,5.4,"$20,596,350","$100,035","$18,000,000",18000000,20596350,100035
204,Basquiat (film),PG,7.8,"$5,109,693","$5,109,693","$5,599,766",5599766,5109693,5109693
205,La Belle Noiseuse,PG,7.0,"$777,754","$777,754","$1,168,044",1168044,777754,777754
206,Mona Lisa Smile drawing,PG,5.0,"$187,067,435","$84,522,942","$63,860,942",63860942,187067435,84522942
207,Days of Heaven,PG,7.8,"$22,436,801","$21,124,435","$18,386,400",18386400,22436801,21124435
208,Solaris,PG,6.2,"$190,144,486","$94,894,810","$5,253,842",5253842,190144486,94894810
209,The Conformist,PG,8.0,"$2,768,810","$405,268","$5,181,843",5181843,2768810,405268

In [68]:
# getting profit
profit = []
for x,y in enumerate(total_gross):
    profit.append(y-budget[x])
len(profit)

210

In [69]:
all_ArtHouseandIntern_info1['Profit']=profit

In [70]:
all_ArtHouseandIntern_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit
0,The Hobbit: An Unexpected Journey,PG-13,5.0,"$1,017,003,568","$303,003,568","$250,000,000",250000000,1017003568,303003568,767003568
1,Quantum of Solace,R,4.4,"$591,692,078","$169,368,427","$230,000,000",230000000,591692078,169368427,361692078
2,Finding Dory,PG,2.1,"$1,021,215,193","$486,295,561","$200,000,000",200000000,1021215193,486295561,821215193
3,World War Z,NR,4.9,"$531,514,650","$202,359,711","$190,000,000",190000000,531514650,202359711,341514650
4,The Good Dinosaur,NR,6.9,"$333,771,037","$123,087,120","$187,500,000",187500000,333771037,123087120,146271037
...,...,...,...,...,...,...,...,...,...,...
205,La Belle Noiseuse,PG,7.0,"$777,754","$777,754","$1,168,044",1168044,777754,777754,-390290
206,Mona Lisa Smile drawing,PG,5.0,"$187,067,435","$84,522,942","$63,860,942",63860942,187067435,84522942,123206493
207,Days of Heaven,PG,7.8,"$22,436,801","$21,124,435","$18,386,400",18386400,22436801,21124435,4050401
208,Solaris,PG,6.2,"$190,144,486","$94,894,810","$5,253,842",5253842,190144486,94894810,184890644
209,The Conformist,PG,8.0,"$2,768,810","$405,268","$5,181,843",5181843,2768810,405268,-2413033

In [71]:
# Creating Box office column
# dividing total gross by the avg price of tickets, to get an estimsted number of tickes sold
no_tickets = []
for i in all_ArtHouseandIntern_info1.Total_gross:
    no_tickets.append(round(i/13)) 
no_tickets[:10]

[78231044,
 45514775,
 78555015,
 40885742,
 25674695,
 77076631,
 13998655,
 57389222,
 56266414,
 17017641]

In [72]:
# converting integer of no. of tickets into string
tickets_string = []
for i in no_tickets:
    tickets_string.append("{:,.0f}".format(i))
len(tickets_string)

210

In [73]:
# converting integer of profit to currency
currency = []
for i in all_ArtHouseandIntern_info1.Profit:
    currency.append("${:,.0f}".format(i))
len(currency)

210

In [74]:
all_ArtHouseandIntern_info1['No.Tickets']=tickets_string
all_ArtHouseandIntern_info1['Profit$']= currency
all_ArtHouseandIntern_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit,No.Tickets,Profit$
0,The Hobbit: An Unexpected Journey,PG-13,5.0,"$1,017,003,568","$303,003,568","$250,000,000",250000000,1017003568,303003568,767003568,"78,231,044","$767,003,568"
1,Quantum of Solace,R,4.4,"$591,692,078","$169,368,427","$230,000,000",230000000,591692078,169368427,361692078,"45,514,775","$361,692,078"
2,Finding Dory,PG,2.1,"$1,021,215,193","$486,295,561","$200,000,000",200000000,1021215193,486295561,821215193,"78,555,015","$821,215,193"
3,World War Z,NR,4.9,"$531,514,650","$202,359,711","$190,000,000",190000000,531514650,202359711,341514650,"40,885,742","$341,514,650"
4,The Good Dinosaur,NR,6.9,"$333,771,037","$123,087,120","$187,500,000",187500000,333771037,123087120,146271037,"25,674,695","$146,271,037"
...,...,...,...,...,...,...,...,...,...,...,...,...
205,La Belle Noiseuse,PG,7.0,"$777,754","$777,754","$1,168,044",1168044,777754,777754,-390290,"59,827","$-390,290"
206,Mona Lisa Smile drawing,PG,5.0,"$187,067,435","$84,522,942","$63,860,942",63860942,187067435,84522942,123206493,"14,389,803","$123,206,493"
207,Days of Heaven,PG,7.8,"$22,436,801","$21,124,435","$18,386,400",18386400,22436801,21124435,4050401,"1,725,908","$4,050,401"
208,Solaris,PG,6.2,"$190,144,486","$94,894,810","$5,253,842",5253842,190144486,94894810,184890644,"14,626,499","$184,890,644"
209,The Conformist,PG,8.0,"$2,768,810","$405,268","$5,181,843",5181843,2768810,405268,-2413033,"212,985","$-2,413,033"

After the dataframe has been updated, bokeh is being installed.

In [75]:
from bokeh.layouts import gridplot,row
from bokeh.plotting import figure,output_file,ColumnDataSource
from bokeh.io import push_notebook,show,output_notebook
from bokeh.models import NumeralTickFormatter
output_notebook()

Bokeh is successfully installed, now the key componets need to be creted for each system rating group to make the graphs.

A reminder of the componets;
 - Cost
 - Proft
 - Name
 - Profit Percntage by Cost
 - Type of System Rating

In [243]:
# index of all 'R' system ratings
index_r = []
for i,x in enumerate(system_rating):
    if x == 'R':index_r.append(i)

In [244]:
# getiing the profit for all 'R' system rating
r_profit = []
for i in index_r:
    r_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(r_profit)

42

In [245]:
# getting the cost for 'R' system rating
cost1 = []
for i in index_r:
    cost1.append(all_ArtHouseandIntern_info1.Product_budget[i])
len(cost1)

42

In [246]:
# getiing the name for all 'R' system rating
r_name = []
for i in index_r:
    r_name.append(all_ArtHouseandIntern_info1.Name[i])
len(r_name)

42

In [247]:
# getiing the $profit for all 'R' system rating
r_dollar = []
for i in index_r:
    r_dollar.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(r_dollar)

42

In [248]:
# getiing the system rating for all 'R' system rating
r_sratings = []
for i in index_r:
    r_sratings.append(all_ArtHouseandIntern_info1.System_ratings[i])
len(r_sratings)

42

In [249]:
# getting percentage profit for all 'R' system rating
percent_profit = []
for i in index_r:
    i = (all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Buget[i])*100
    percent_profit.append(round(i,0))
len(percent_profit)

42

In [250]:
# turning float of percentage of profit into int for 'R' system rating
pp = []
for i in percent_profit:
    i = int(i)
    pp.append(i)
len(pp)

42

In [251]:
# converting integer to percentage for 'R' system rating
percentage_profit = []
for i in pp:
    percentage_profit.append("{:}%".format(i))
len(percentage_profit)

42

In [252]:
# index of all 'G' system ratings
index_g = []
for i,x in enumerate(system_rating):
    if x == 'G':index_g.append(i)

In [253]:
# getiing the profit for all 'G' system rating
g_profit = []
for i in index_g:
    g_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(g_profit)

42

In [254]:
# getting the cost for 'G' system rating
cost2 = []
for i in index_g:
    cost2.append(all_ArtHouseandIntern_info1.Product_budget[i])
len(cost2)

42

In [255]:
# getiing the name for all 'G' system rating
g_name = []
for i in index_g:
    g_name.append(all_ArtHouseandIntern_info1.Name[i])
len(g_name)

42

In [256]:
# getiing the $profit for all 'G' system rating
g_dollar = []
for i in index_g:
    g_dollar.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(g_dollar)

42

In [257]:
# getiing the system rating for all 'G' system rating
g_sratings = []
for i in index_g:
    g_sratings.append(all_ArtHouseandIntern_info1.System_ratings[i])
len(g_sratings)

42

In [258]:
# getting percentage profit for all 'G' system rating
percent_profit1 = []
for i in index_g:
    i = (all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Buget[i])*100
    percent_profit1.append(round(i,0))
len(percent_profit1)

42

In [259]:
# turning float of percentage of profit into int for 'G' system rating
pp1= []
for i in percent_profit1:
    i = int(i)
    pp1.append(i)
len(pp1)

42

In [260]:
# converting integer to percentage for 'G' system rating
percentage_profit1 = []
for i in pp1:
    percentage_profit1.append("{:}%".format(i))
len(percentage_profit1)

42

In [261]:
# index of all 'PG' system ratings
index_pg = []
for i,x in enumerate(system_rating):
    if x == 'PG':index_pg.append(i)

In [262]:
# getiing the profit for all 'PG' system rating
pg_profit = []
for i in index_pg:
    pg_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(pg_profit)

42

In [263]:
# getting the cost for 'PG' system rating
cost3 = []
for i in index_pg:
    cost3.append(all_ArtHouseandIntern_info1.Product_budget[i])
len(cost3)

42

In [264]:
# getiing the name for all 'PG' system rating
pg_name = []
for i in index_pg:
    pg_name.append(all_ArtHouseandIntern_info1.Name[i])
len(pg_name)

42

In [265]:
# getiing the $profit for all 'PG' system rating
pg_dollar = []
for i in index_pg:
    pg_dollar.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(pg_dollar)

42

In [266]:
# getiing the system rating for all 'PG' system rating
pg_sratings = []
for i in index_pg:
    pg_sratings.append(all_ArtHouseandIntern_info1.System_ratings[i])
len(pg_sratings)

42

In [267]:
# getting percentage profit for all 'PG' system rating
percent_profit2 = []
for i in index_pg:
    i = (all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Buget[i])*100
    percent_profit2.append(round(i,0))
len(percent_profit2)

42

In [268]:
# turning float of percentage of profit into int for 'PG' system rating
pp2= []
for i in percent_profit2:
    i = int(i)
    pp2.append(i)
len(pp2)

42

In [269]:
# converting integer to percentage for 'PG' system rating
percentage_profit2= []
for i in pp2:
    percentage_profit2.append("{:}%".format(i))
len(percentage_profit2)

42

In [270]:
# index of all 'PG-13' system ratings
index_pg13 = []
for i,x in enumerate(system_rating):
    if x == 'PG-13':index_pg13.append(i)

In [271]:
# getiing the profit for all 'PG-13' system rating
pg13_profit = []
for i in index_pg13:
    pg13_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(pg13_profit)

42

In [272]:
# getiing the name for all 'PG-13' system rating
pg13_name = []
for i in index_pg13:
    pg13_name.append(all_ArtHouseandIntern_info1.Name[i])
len(pg13_name)

42

In [273]:
# getting the cost for 'PG-13' system rating
cost4 = []
for i in index_pg13:
    cost4.append(all_ArtHouseandIntern_info1.Product_budget[i])
len(cost4)

42

In [274]:
# getiing the $profit for all 'PG-13' system rating
pg13_dollar = []
for i in index_pg13:
    pg13_dollar.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(pg13_dollar)

42

In [275]:
# getiing the system rating for all 'PG-13' system rating
pg13_sratings = []
for i in index_pg13:
    pg13_sratings.append(all_ArtHouseandIntern_info1.System_ratings[i])
len(pg13_sratings)

42

In [276]:
# getting percentage profit for all 'PG-13' system rating
percent_profit3 = []
for i in index_pg13:
    i = (all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Buget[i])*100
    percent_profit3.append(round(i,0))
len(percent_profit3)

42

In [277]:
# turning float of percentage of profit into int
pp3= []
for i in percent_profit3:
    i = int(i)
    pp3.append(i)
len(pp3)

42

In [278]:
# converting integer to percentage
percentage_profit3= []
for i in pp3:
    percentage_profit3.append("{:}%".format(i))
len(percentage_profit3)

42

In [279]:
# index of all 'NR' system ratings
index_NR = []
for i,x in enumerate(system_rating):
    if x == 'NR':index_NR.append(i)

In [280]:
# getiing the profit for all 'NR' system rating
NR_profit = []
for i in index_NR:
    NR_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(NR_profit)

42

In [281]:
# getiing the name for all 'NR' system rating
nr_name = []
for i in index_NR:
    nr_name.append(all_ArtHouseandIntern_info1.Name[i])
len(nr_name)

42

In [282]:
# getting the cost for 'NR' system rating
cost5 = []
for i in index_NR:
    cost5.append(all_ArtHouseandIntern_info1.Product_budget[i])
len(cost5)

42

In [283]:
# getiing the $profit for all 'NR' system rating
nr_dollar = []
for i in index_NR:
    nr_dollar.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(nr_dollar)

42

In [284]:
# getiing the system rating for all 'NR' system rating
nr_sratings = []
for i in index_NR:
    nr_sratings.append(all_ArtHouseandIntern_info1.System_ratings[i])
len(nr_sratings)

42

In [285]:
# getting percentage profit for all 'NR' system rating
percent_profit4 = []
for i in index_NR:
    i = (all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Buget[i])*100
    percent_profit4.append(round(i,0))
len(percent_profit4)

42

In [286]:
# turning float of percentage of profit into int for 'NR' system rating
pp4= []
for i in percent_profit4:
    i = int(i)
    pp4.append(i)
len(pp4)

42

In [287]:
# converting integer to percentage for 'NR' system rating
percentage_profit4= []
for i in pp4:
    percentage_profit4.append("{:}%".format(i))
len(percentage_profit4)

42

In [290]:
rangee = list(range(42)) # x-axis range
# allows the garph to hover over the piont to show all information about the pionts  
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,box_select,hover"

# Graph 1
source = ColumnDataSource(data=dict(
    x = rangee, # x-axis
    y = r_profit,# y-axis
    name=r_name, # name of movie
    profit=r_dollar,# profit in currency($)
    system_rating=r_sratings ,# system rating of movie
    percent_profit=percentage_profit,# profit percentage based on cost
    cost1=cost1))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name"),# the name
    ("Cost","@cost1"),# the cost
    ("Profit","@profit"),# the profit
    ("(System-Rating)","@system_rating"),# the system rating
    ("(Profit-Percentage)","@percent_profit")]# the profit percentage
p3 = figure(title='Profit.Drama.System Rating R',tools=TOOLS,plot_height=300,
           plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p3.left[0].formatter.use_scientific=False 
# makes the digits more visible by turning it into millions on the y-axis
p3.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
p3.circle('x','y',color='#fff099',width=3,source=source)
p3.line('x','y',color="#fff099",# the style and color of the graph
        line_dash='dashed',line_width=2,source=source)

# Graph 2
source4 = ColumnDataSource(data=dict(
     o=rangee,# x-axis
     e=g_profit,# y-axis
     name1=g_name,# name of movies
     profit1=g_dollar,# profit of movies in curreny($)
     system_rating1=g_sratings,# system rating of movie
     percent_profit1=percentage_profit1,# profit percentage based on cost
     cost2=cost2))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name1"),# the name
    ("Cost","@cost2"),# the cost
    ("Profit","@profit1"),# the profit in dollars
    ("(System-Rating)","@system_rating1"),# the system rating
    ("(Profit-Percentage)","@percent_profit1")]# the profit percentage
p4 = figure(title='Profit.Drama.System Rating G',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p4.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p4.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
# the style and color of the graph
p4.circle(x='o',y='e',color='#ffe866',width=3,source=source4)
p4.line(x='o',y='e',color='#ffe866',source=source4)
 
# Graph 3
source1 = ColumnDataSource(data=dict(
       p=rangee,# x-axis
       q=pg_profit,# y-axis
       name2=pg_name,# name of movies
       profit2=pg_dollar,# profit of movies in currency ($)
       system_rating2=pg_sratings,# system rating of moives
       percent_profit2=percentage_profit2,# profit percnetage based on cost
       cost3=cost3))# cost of movies
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name2"),# the name 
    ("Cost","@cost3"),# the cost
    ("Profit","@profit2"),# the profit the dollars
    ("(System-Rating)","@system_rating2"),# the system rating
    ("(Profit-Percentage)","@percent_profit2")]# the profit percentage 
p5 = figure(title='Profit.Drama.System Rating PG',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p5.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p5.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of graph
p5.square(x='p',y='q',line_color='#ffdd1a',fill_color=None,source=source1)
p5.line(x='p',y='q',line_color='#ffdd1a',source=source1)

# Graph 4
source2 = ColumnDataSource(data=dict(
       r=rangee,# x-axis
       t=pg13_profit,# y-axis
       name3=pg13_name,# name of movies
       profit3=pg13_dollar,# profit of movies to currency ($)
       system_rating3=pg13_sratings,# system rating of movies
       percent_profit3=percentage_profit3,# profit percentage based on cost
       cost4=cost4))# cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name3"),# the name
    ("Cost","@cost4"),# the cost
    ("Profit","@profit3"),# the profit in dollars
    ("(System-Rating)","@system_rating3"),# the system rating
    ("(Profit-Percentage)","@percent_profit3")]# the profit percentage
p6 = figure(title='Profit.Drama.System Rating PG-13',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
#takes away the scientific notation off the y-axis
p6.left[0].formatter.use_scientific=False
# makes the digits more visible ny turning it into millions on the y-axis
p6.yaxis[0].formatter=NumeralTickFormatter(format='$0.a')
# the style and color of the graph
p6.triangle(x='r',y='t',color='#e6c300',width=2,source=source2)
p6.line(x='r',y='t',color='#e6c300',width=2,source=source2)

# Graph 5
source3 = ColumnDataSource(data=dict(
        l=rangee,# x-axis
        i=NR_profit,# y-axis
        name4=nr_name,# name of movies
        profit4=nr_dollar,# profit of movies to currency ($)
        system_rating4=nr_sratings,# system rating of movies
        percent_profit4=percentage_profit4,# profit percentage based on cost
        cost5=cost5))#cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name4"),# the name
    ("Cost","@cost5"),# the cost
    ("Profit","@profit4"),# the profit in dollars
    ("(System-Rating)","@system_rating4"),# the system rating
    ("(Profit-Percentage)","@percent_profit4")]# the profit percentage
p7 = figure(title='Profit.Drama.System Rating NR',tools=TOOLS,
            plot_height=300,plot_width=300,tooltips=TOOLTIPS)
#takes away the scientiifc notation off the y-axis
p7.left[0].formatter.use_scientific=False
#makes the digits more visible by turning it into millions  on the y-axis
p7.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of the graph
p7.circle(x='l',y='i',color='#998200',fill_color=None,width=2,source=source3)
p7.line(x='l',y='i',color='#998200',width=2,source=source3)

output_file("toolbar.thml")
show(row(p3,p4,p5,p6,p7))# this puts the graphs side by side

# Blueprint: Gross Profit Margin Percentage

This is the blueprint for creating the second visualiztion Gross Profit Margin Percentage, altair will be used to create this graph.

__Blueprint__:
 - 1. Understanding the dataframe format used to create this data visualiztion helps make the process easier, these are the key componets that make up the dataframe used for this graph.
   
    - The data frame that altair used to create this graph consist of four colunms;
     
       - Yield: This colunm is the only colunm that shows any type of informations that is in numbers 
       - Variety: This colunm is the only column that contains category or groupings among the other pionts in the dataframe
       - Year: This colunm is based on datasets that contains timeframes
       - Site: This is a colunm that pinpionts differiantion among the rest of the data pionts
       
 
 - 2. Create five dataframes for five different graphs based on the documented format that is supplied by Altair. 
   
    - The dataframes will consist of these six columns;
      
       - Name: This colunm shows the names of each movie
       - Type: The concept of this graph portrays the profit made compared to the Revenue, the two main elements that reflects that is the Revenue and the Profit ergo the 'Type' column are made up of those two elements.
       - Yield: This colunm shows how much the 'Type' column is in int, this is used to plot the pionts in the graph.
       - Type Yield: This colunm shows the 'Yield' colunm in currency which is a string, this is mostly used for the tooltip to make it easier to understand how much the elements in the 'Type' column is in dollars.
       - System Rating: This shows the System Rating of each movie.
       - Gross Profit Margin: This colunm shows the gross profit margin in percentage.
       
 
 - 3. The style of this graph is a Becker's Barkey Trellis Plot which is found in Altair's Gallery. There are two pionts shaped as a ring in each panel, the first ring projects the Renvue and the other ring projects the Profit, this set up allows the perseption of how much of a fraction do each movie actually walk away with when compared to the Revenue allowing the Profit to be seen from a differnt angle. This could make the movie look more profitable or seem over-rated. Each ring when hovered shows the Name of the movie, the Type choosing beteween Profit or Revenue, the Type Yield which is the amount of the Type in dollars, the Gross Profit Margin Percentage and the System Rating. The closer the Profit is to the Revenue the more buoyant it is!

In [124]:
# understanding how the data frame is formatted
# this was the eact dataframe used in Altairs example
from vega_datasets import data
source = data.barley()
source

        yield           variety  year             site
0    27.00000         Manchuria  1931  University Farm
1    48.86667         Manchuria  1931           Waseca
2    27.43334         Manchuria  1931           Morris
3    39.93333         Manchuria  1931        Crookston
4    32.96667         Manchuria  1931     Grand Rapids
..        ...               ...   ...              ...
115  58.16667  Wisconsin No. 38  1932           Waseca
116  47.16667  Wisconsin No. 38  1932           Morris
117  35.90000  Wisconsin No. 38  1932        Crookston
118  20.66667  Wisconsin No. 38  1932     Grand Rapids
119  29.33333  Wisconsin No. 38  1932           Duluth

[120 rows x 4 columns]

These are the variables needed to create the columns for the first dataframe; new_name,new_systems, new_total_gross, new_worldwide_gross, new_profit, new_currency_profit, gross_profit_margin_percentage.

This is all the names of the movie for the rated-R movies.

In [291]:
new_name=[]
name = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x=='R':
            name.append(all_ArtHouseandIntern_info1.Name[i])
for i,x in enumerate(name):
    new_name.append( x)
len(new_name)

42

This is all the domestic revenue of each movie in the rated-R catagory of movies.

In [292]:
new_total_gross = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='R':
            new_total_gross.append(all_ArtHouseandIntern_info1.Total_gross[i])
len(new_total_gross)

42

This is all the world wide revenue of each movie in the rated-R catagory of movies.

In [293]:
new_worldwide_gross = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='R':
            new_worldwide_gross.append(all_ArtHouseandIntern_info1.Worlwide_gross[i])
len(new_worldwide_gross)

42

This is all the profit in dollars of each movie in the rated-R catagory, this is particularly used for tooltip.

In [294]:
new_currency_profit = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='R':
            new_currency_profit.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(new_currency_profit)

42

This is all the profit in int of each mvoie in the rated-R catagory, this is particularly used for the Y and X axis.

In [295]:
new_profit = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='R':
            new_profit.append(all_ArtHouseandIntern_info1.Profit[i])
len(new_profit)

42

In [296]:
# a list of rated-'r'
new_systems = list('R'*42)
len(new_systems)

42

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [301]:
# Creating the gross profit margin percentage column
p_rev = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'R':
        p_rev.append((all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Total_gross[i])*100)
len(p_rev)
p_rev.pop(20)

<ipython-input-301-ed159d9d60ea>:5: RuntimeWarning: divide by zero encountered in longlong_scalars
  p_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)

-inf

In [302]:
# turning float of percentage of profit into int
pp_rev= []
for i in p_rev:
    i = int(i)
    pp_rev.append(round(i,0))
len(pp_rev)

41

In [303]:
# converting integer to percentage
gross_profit_margin_percentage= []
for i in pp_rev:
    gross_profit_margin_percentage.append("{:}%".format(i))
len(gross_profit_margin_percentage)

41

These are the variables needed to create the columns for the second dataframe; new_name1, new_systems1, new_total_gross1, new_worldwide_gross1, new_profit1, new_currency_profit1, gross_profit_margin_percentage1

This is all the names of the movie for the rated-PG movies.

In [304]:
new_name1=[]
name1 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG':
            name1.append(all_ArtHouseandIntern_info1.Name[i])
for i,x in enumerate(name1):
    new_name1.append( x)
len(new_name1)

42

This is all the domestic revenue of each movie in the rated-PG catagory of movies.

In [305]:
new_total_gross1 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG':
            new_total_gross1.append(all_ArtHouseandIntern_info1.Total_gross[i])
len(new_total_gross1)

42

This is all the world wide revenue of each movie in the rated-PG catagory of movies.

In [306]:
new_worldwide_gross1= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG':
            new_worldwide_gross1.append(all_ArtHouseandIntern_info1.Worlwide_gross[i])
len(new_worldwide_gross1)

42

This is all the profit in dollars of each movie in the rated-PG catagory, this is particularly used for tooltip.

In [307]:
new_currency_profit1 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG':
            new_currency_profit1.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(new_currency_profit1)

42

This is all the profit in int of each mvoie in the rated-PG catagory, this is particularly used for the Y and X axis.

In [308]:
new_profit1 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG':
            new_profit1.append(all_ArtHouseandIntern_info1.Profit[i])
len(new_profit1)

42

In [309]:
# list of rated-'PG'
new_systems1 = []
for i in list(range(0,42)):
    new_systems1.append('PG')

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [310]:
# Creating the profit rev percentage column
p1_rev = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG':
        p1_rev.append((all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Total_gross[i])*100)
len(p1_rev)

42

In [311]:
# turning float of percentage of profit into int
pp1_rev= []
for i in p1_rev:
    i = int(i)
    pp1_rev.append(round(i,0))
len(pp1_rev)

42

In [312]:
# converting integer to percentage
gross_profit_margin_percent1= []
for i in pp1_rev:
    gross_profit_margin_percent1.append("{:}%".format(i))
gross_profit_margin_percent1
len(gross_profit_margin_percent1)

42

These are the variables needed to create the columns for the third dataframe; new_name2, new_systems2, new_total_gross2, new_worldwide_gross2, new_profit2, new_currency_profit2, gross_profit_margin_percentage2

In [313]:
new_name2=[]
name2 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='G':
            name2.append(all_ArtHouseandIntern_info1.Name[i])
for i,x in enumerate(name2):
    new_name2.append(x)
len(new_name2)

42

In [314]:
new_systems2= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='G':
            new_systems2.append(all_ArtHouseandIntern_info1.Total_gross[i])
len(new_systems2)

42

In [315]:
new_worldwide_gross2= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='G':
            new_worldwide_gross2.append(all_ArtHouseandIntern_info1.Worlwide_gross[i])
len(new_worldwide_gross2)

42

In [316]:
new_currency_profit2 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='G':
            new_currency_profit2.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(new_currency_profit2)

42

In [317]:
new_profit2 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='G':
            new_profit2.append(all_ArtHouseandIntern_info1.Profit[i])
len(new_profit2)

42

In [318]:
new_systems2 = list('G'*42)
len(new_systems2)

42

In [319]:
# Creating the profit rev percentage column
p2_rev = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'G':
        p2_rev.append((all_ArtHouseandIntern_info1.Profit[i] / all_ArtHouseandIntern_info1.Total_gross[i])*100)
len(p2_rev)

42

In [320]:
# turning float of percentage of profit into int
pp2_rev= []
for i in p2_rev:
    i = int(i)
    pp2_rev.append(round(i,0))
len(pp2_rev)

42

In [321]:
# converting integer to percentage
gross_profit_margin_percentage2= []
for i in pp2_rev:
    gross_profit_margin_percentage2.append("{:}%".format(i))
len(gross_profit_margin_percentage2)

42

These are the variables needed to create the columns for the fourth dataframe; new_name3, new_systems3, new_total_gross3, new_worldwide_gross3, new_profit3, new_currency_profit3, gross_profit_margin_percentage3

In [322]:
new_name3=[]
name3 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            name3.append(all_ArtHouseandIntern_info1.Name[i])
for i,x in enumerate(name3):
    new_name3.append( x)
len(new_name3)

42

In [323]:
new_total_gross3 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            new_total_gross3.append(all_ArtHouseandIntern_info1.Total_gross[i])
len(new_total_gross3)

42

In [324]:
new_worldwide_gross3= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            new_worldwide_gross3.append(all_ArtHouseandIntern_info1.Worlwide_gross[i])
len(new_worldwide_gross3)

42

In [325]:
new_currency_profit3 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            new_currency_profit3.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(new_currency_profit3)

42

In [326]:
new_profit3 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            new_profit3.append(all_ArtHouseandIntern_info1.Profit[i])
len(new_profit3)

42

In [327]:
new_systems3 = []
for i in list(range(0,42)):
    new_systems3.append('PG-13')

In [328]:
p3_rev = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='PG-13':
            p3_rev.append(all_ArtHouseandIntern_info1.Profit[i]/all_ArtHouseandIntern_info1.Total_gross[i]*100)

len(p3_rev)

42

In [329]:
# turning float of percentage of profit into int
pp3_rev= []
for i in p3_rev:
    i = int(i)
    pp3_rev.append(round(i,0))
len(pp3_rev)

42

In [330]:
# converting integer to percentage
gross_profit_margin_percentage3= []
for i in pp3_rev:
    gross_profit_margin_percentage3.append("{:}%".format(i))
len(gross_profit_margin_percentage3)

42

These are the variables needed to create the columns for the fivth dataframe; new_name4, new_systems4, new_total_gross4, new_worldwide_gross4, new_profit4, new_currency_profit4, gross_profit_margin_percentage4

In [331]:
new_name4=[]
name4= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            name4.append(all_ArtHouseandIntern_info1.Name[i])
for i,x in enumerate(name4):
    new_name4.append(x)
new_name4
len(new_name4)

42

In [332]:
new_total_gross4 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            new_total_gross4.append(all_ArtHouseandIntern_info1.Total_gross[i])
len(new_total_gross4)

42

In [333]:
new_worldwide_gross4= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            new_worldwide_gross4.append(all_ArtHouseandIntern_info1.Worlwide_gross[i])
len(new_worldwide_gross4)

42

In [334]:
new_currency_profit4 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            new_currency_profit4.append(all_ArtHouseandIntern_info1['Profit$'][i])
len(new_currency_profit4)

42

In [335]:
new_profit4= []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            new_profit4.append(all_ArtHouseandIntern_info1.Profit[i])
len(new_profit4)

42

In [336]:
new_systems4 = []
for i in list(range(0,42)):
    new_systems4.append('NR')

In [337]:
p4_rev = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
        if x =='NR':
            p4_rev.append(round(all_ArtHouseandIntern_info1.Profit[i]/all_ArtHouseandIntern_info1.Total_gross[i]*100,
                                0))
len(p4_rev)

42

In [338]:
# turning float of percentage of profit into int
pp4_rev= []
for i in p4_rev:
    i = int(i)
    pp4_rev.append(round(i,2))
len(pp4_rev)

42

In [339]:
# converting integer to percentage
gross_profit_margin_percent4= []
for i in pp4_rev:
    gross_profit_margin_percent4.append("{:}%".format(i))
len(gross_profit_margin_percent4)

42

In [340]:
# list for type colunm
l = []
for i in list(range(0,42)):
    l.append('Revenue')
for i in list(range(0,42)):
    l.append('Profit')
len(l)

84

In [341]:
df5 = pd.DataFrame({'Name':new_name4*2,'Yield':new_total_gross4+new_profit4,'Type Yield':new_worldwide_gross4+new_currency_profit4,
                    'System Ratings':new_systems4*2,'Gross Profit Margin %':gross_profit_margin_percent4*2,'Type':l})

df4 = pd.DataFrame({'Name':new_name3*2,'Yield':new_total_gross3+new_profit3,'Type Yield':new_worldwide_gross3+new_currency_profit3,
                  'System Ratings':new_systems3*2,'Gross Profit Margin %':gross_profit_margin_percentage3*2,'Type':l})

df3 = pd.DataFrame({'Name':new_name2*2,'Yield':new_total_gross4+new_profit2,'Type Yield':new_worldwide_gross2+new_currency_profit2,
                    'System Ratings':new_systems2*2,'Gross Profit Margin %':gross_profit_margin_percentage2*2,'Type':l})

df2 = pd.DataFrame({'Name':new_name1*2,'Yield':new_total_gross1+new_profit1,'Type Yield':new_worldwide_gross1+new_currency_profit1,
                  'System Ratings':new_systems1*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

df1 = pd.DataFrame({'Name':new_name*2,'Yield':new_total_gross+new_profit,'Type Yield':new_worldwide_gross+new_currency_profit,
                    'System Ratings':new_systems*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

In [342]:
df1

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Quantum of Solace,591692078,"$591,692,078",R,80%,Revenue
1,The Dark Knight,1001996207,"$1,001,996,207",R,-11%,Revenue
2,Suicide Squad,746059887,"$746,059,887",R,59%,Revenue
3,Wild Wild West,221229335,"$221,229,335",R,36%,Revenue
4,Frozen,1272469910,"$1,272,469,910",R,80%,Revenue
...,...,...,...,...,...,...
79,Body of Lies,51056530,"$51,056,530",R,-50%,Profit
80,Live by Night,-43225568,"$-43,225,568",R,65%,Profit
81,Alien: Resurrection,100700000,"$100,700,000",R,18%,Profit
82,Year One,-2395277,"$-2,395,277",R,97%,Profit
83,Reign of Fire,22150183,"$22,150,183",R,-87%,Profit

In [343]:
df2

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Finding Dory,1021215193,"$1,021,215,193",PG,80%,Revenue
1,The Chronicles of Riddick,107212751,"$107,212,751",PG,-11%,Revenue
2,Eragon,249488115,"$249,488,115",PG,59%,Revenue
3,The Devil's Own,140900000,"$140,900,000",PG,36%,Revenue
4,The Mummy,416385488,"$416,385,488",PG,80%,Revenue
...,...,...,...,...,...,...
79,La Belle Noiseuse,-390290,"$-390,290",PG,-50%,Profit
80,Mona Lisa Smile drawing,123206493,"$123,206,493",PG,65%,Profit
81,Days of Heaven,4050401,"$4,050,401",PG,18%,Profit
82,Solaris,184890644,"$184,890,644",PG,97%,Profit
83,The Conformist,-2413033,"$-2,413,033",PG,-87%,Profit

In [344]:
df3

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Jupiter Ascending,531514650,"$181,982,519",G,1%,Revenue
1,A Good Day to Die Hard,333771037,"$304,249,198",G,69%,Revenue
2,Murder on the Orient Express,731463377,"$345,922,730",G,84%,Revenue
3,Bulletproof Monk,1259199706,"$23,010,607",G,-125%,Revenue
4,Bedazzled,425522281,"$90,376,224",G,46%,Revenue
...,...,...,...,...,...,...
79,The Lady Vanishes,92551549,"$92,551,549",G,76%,Profit
80,North by Northwest,-319419,"$-319,419",G,-34%,Profit
81,Palm Springs,-4234465,"$-4,234,465",G,-553%,Profit
82,Tell No One,25402267,"$25,402,267",G,57%,Profit
83,,4957475,"$4,957,475",G,46%,Profit

In [345]:
df4

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,The Hobbit: An Unexpected Journey,1017003568,"$1,017,003,568",PG-13,75%,Revenue
1,Alice Through the Looking Glass,276928112,"$276,928,112",PG-13,38%,Revenue
2,Watchmen,186976250,"$186,976,250",PG-13,26%,Revenue
3,The Bourne Legacy,280355920,"$280,355,920",PG-13,55%,Revenue
4,Passengers,302239672,"$302,239,672",PG-13,63%,Revenue
...,...,...,...,...,...,...
79,Boy Erased,862650,"$862,650",PG-13,7%,Profit
80,The Imposter,2232717,"$2,232,717",PG-13,69%,Profit
81,happy as lazzaro,-5468927,"$-5,468,927",PG-13,-303%,Profit
82,My Life as a Zucchini,-2127402,"$-2,127,402",PG-13,-36%,Profit
83,Godzilla,375000000,"$375,000,000",PG-13,70%,Profit

In [346]:
df5

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,World War Z,531514650,"$531,514,650",NR,64%,Revenue
1,The Good Dinosaur,333771037,"$333,771,037",NR,44%,Revenue
2,Up,731463377,"$731,463,377",NR,76%,Revenue
3,Beauty and the Beast,1259199706,"$1,259,199,706",NR,87%,Revenue
4,Warcraft,425522281,"$425,522,281",NR,62%,Revenue
...,...,...,...,...,...,...
79,Flubber,97993801,"$97,993,801",NR,55%,Profit
80,The Manchurian Candidate,16148711,"$16,148,711",NR,17%,Profit
81,Walking with Dinosaurs,43368842,"$43,368,842",NR,35%,Profit
82,Looney Tunes: Back in Action,-25459338,"$-25,459,338",NR,-47%,Profit
83,Despicable Me 3,959727750,"$959,727,750",NR,93%,Profit

In [348]:
# this is the first graph: this is the System R rating category
a=alt.Chart(df1).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis = alt.Axis(grid=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem PG rating category
b=alt.Chart(df2).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
        axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem G rating category
c=alt.Chart(df3).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the third graph: this is the Sytem PG-13 rating category
d=alt.Chart(df4).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,#take away the grid
       scale=alt.Scale(zero=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the fourth graph: this is the Sytem NR rating category
e=alt.Chart(df5).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,
       scale=alt.Scale(zero=False),# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

f= alt.vconcat(b,c,d,e).configure_view(strokeOpacity=0).configure_axisLeft(labelColor='gold')
f&a # combines the graphs together

alt.VConcatChart(...)

# Blueprint: Budget and Revenue of Movies

This js the blueprint for creating the third visualization Budget and Revenue of Movies, altair will be used to create this graph. 

__Blueprint:__
   - The format of the dataframe needed for this graph is straight forward, based on the ideology of the persception of the chart, these are the colunms needed for thr dataframe;
        - Name,
        - System Ratings,
        - Budget,
        - Revenue,
        - Budget of Movie,
        - Renenue of Movies
   
  
  - The style of this chart is a Selection Histogram which is found in the Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis is the Revenue and the y-axis is the Budget, this set up projects wether a linear regression, meaning if the hypothesis which is, the higher the budget the higher the revenue is proven right projecting a linear regression.
  
  - The graph has an attachted histogram showing the amount of items in each category within the selection. In order to make a selection create a box by dragging the mouse. When the mouse hovers the pionts it projects the name, system rating, budget of the movies and the reevenue of the movies.

In [349]:
# variable for the range colunm neede for the dataframe below
listt = range(0,210)

In [350]:
# data frame created for the next three graphs
dataframe2 = pd.DataFrame({"Name":all_ArtHouseandIntern_info1.Name,"System Rating":all_ArtHouseandIntern_info1.System_ratings,"Budget":all_ArtHouseandIntern_info1.Buget,'Range':listt,
                           "Revenue":all_ArtHouseandIntern_info1.Total_gross,'Budget of Movie':all_ArtHouseandIntern_info1.Product_budget,'Revenue of Movie':all_ArtHouseandIntern_info1.Worlwide_gross})

In [351]:
#scatter graph
brush = alt.selection(type='interval')# to reate the selction box
points=alt.Chart(dataframe2).mark_circle(size=60).encode(
    x="Revenue:Q",# x-axis
    y='Budget',# y-axis
    color='System Rating', # color based on system rating put into category
    # interactive when the pionts are hovered the name, budget, revenue and system rating shows up
    tooltip=['Name','System Rating','Budget of Movie','Revenue of Movie']
).properties(height=400,width=500).add_selection(brush)# the size of graph

# histogram chart
bars=alt.Chart(dataframe2).mark_bar().encode(
        y='System Rating:N',# y-axis
        color='System Rating:N',# color put into groups based on system ratings
        x='count(Revenue):Q').transform_filter(brush)# x-axis
points&bars# graphs combined together

alt.VConcatChart(...)

# Blueprint: Revenue of Movies

This is the blueprint for creating the fourth visualization Revenue of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis shows the revenue of each movie and the y-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the revenue of the movie.

In [352]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
points1=base.mark_point(size=60).encode(
       y=alt.Y('Range',title='',axis=None),# y-axis
       x = alt.X('Revenue:Q',title='Revenue'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
x_ticks=base.mark_tick().encode(
    alt.X('Revenue',axis=tick_axis),# x-axis
    alt.Y('System Rating',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
points1&x_ticks# the two graphs combined

alt.VConcatChart(...)

# Blueprint: Budget of Movies

This is the blueprint for creating the fivth visualization Budget of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The y-axis shows the Budget of each movie and the x-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the budget of the movie.

In [353]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
pionts1=base.mark_point(size=60).encode(
       x=alt.X('Range',title='',axis=None),# y-axis
       y = alt.Y('Budget:Q',title='Budget'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
y_ticks=base.mark_tick().encode(
    alt.X('System Rating',axis=tick_axis),# x-axis
    alt.Y('Budget',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
y_ticks|pionts1# the two graphs combined

alt.HConcatChart(...)

# Blueprint: Movies that made Profit

This is the blueprint for creating the seventh visualization, Movies that made Profit. Highcharts will be used to create this graph. 

__Blueprint:__
- The graph used for this visualzation is Highcharts Lollipop series which is found in the Highcharts Demos. Lollipop charts are variants of column charts, with a circle marker for the data value and a line extending to the axis.The first approach to this chart is by understanding the format of the script. This graph has two types of code HTML and Javascript. JupyterLab has magic commands that supports HTML and Javascript, it uses the '%' syntax element for magics.

   Before the HTML and Javascript are scripted a dataframe needs to be made to extract all the movies that made profit in the action and adventure genre. The two variable needed from the parent dataframe '_all_ArtHouseandIntern_info1_' is the name and profit made in integer. 
   
   - __HTML Section:__
      
      To start off the magic command '%%HTML' should be scripted first in the cell. The main scripted         lines that will be used to create highchart graph through out this project are;
          <script src="https://code.highcharts.com/highcharts.js"></script>
          <script src="https://code.highcharts.com/highcharts-more.js"></script>
          <script src="https://code.highcharts.com/modules/exporting.js"></script>
          <script src="https://code.highcharts.com/modules/accessibility.js"></script>
     For this particular graph this script will be used to get lollipop affect;
          <script src="https://code.highcharts.com/modules/dumbbell.js"></script>
          <script src="https://code.highcharts.com/modules/lollipop.js"></script>
     To close off the HTML script, this script is used and to indetify and differenate this claa from        other, the div id has to be named, and if thei graph is being used more than once the div id needs      to have a different name at all times or it will not work;
                       <figure class="highcharts-figure">
                       <div id="r1"></div> 
                       <p class= "highcharts-description">
                       </p>
                       </figure>
                       
   - __Javascript Section:__
   
      To start off, the magic command '%%JS' is used to script javascript in the jupyterlab cell. The         javascript section will have comments and explaination, but for futher information go to               Highcharts Demos.The normal layout is horizontal but for this graph its going to be vertical. The       main javascript used to create this lollipop graph is;
                         name: ' The Sound of Music ' 
                         low: 2303109231
      The name variable is where the name of the movies is put and the low variable is the amount of         profit made in integer is put.

In [76]:
dataframe1 = pd.DataFrame({"Name":all_ArtHouseandIntern_info1.Name,"Profit":all_ArtHouseandIntern_info1.Profit})

In [77]:
dataframe1

                                  Name     Profit
0    The Hobbit: An Unexpected Journey  767003568
1                    Quantum of Solace  361692078
2                         Finding Dory  821215193
3                          World War Z  341514650
4                    The Good Dinosaur  146271037
..                                 ...        ...
205                  La Belle Noiseuse    -390290
206            Mona Lisa Smile drawing  123206493
207                     Days of Heaven    4050401
208                            Solaris  184890644
209                     The Conformist   -2413033

[210 rows x 2 columns]

In [78]:
# get the largest movies in profit to the smallest for lollipop graph
neww = []
for i,x in enumerate(dataframe1.Profit):
    neww.append((i,x))
neww.sort(reverse=True,key=lambda x:x[1])
neww

[(149, 7749287553),
 (152, 2961011429),
 (144, 2321008636),
 (59, 1292935897),
 (14, 1122469910),
 (11, 1099199706),
 (48, 1047403341),
 (87, 959727750),
 (25, 835431568),
 (2, 821215193),
 (145, 820165063),
 (5, 816996207),
 (40, 779225135),
 (69, 779225135),
 (0, 767003568),
 (21, 734868047),
 (22, 666907323),
 (101, 638102828),
 (7, 571059887),
 (8, 556463377),
 (167, 513510733),
 (134, 502314657),
 (23, 501910531),
 (37, 492420283),
 (150, 467944335),
 (165, 435833717),
 (41, 415419827),
 (70, 415419827),
 (146, 394060973),
 (24, 390258283),
 (32, 376124090),
 (143, 375000000),
 (1, 361692078),
 (3, 341514650),
 (159, 341311860),
 (173, 339240892),
 (56, 336385488),
 (63, 318095319),
 (200, 314728703),
 (49, 310561724),
 (125, 304141192),
 (27, 296168316),
 (108, 290922730),
 (135, 281592771),
 (50, 272900000),
 (74, 272900000),
 (94, 267416460),
 (12, 265522281),
 (38, 256824714),
 (33, 252989076),
 (164, 247796314),
 (15, 247501348),
 (42, 231323410),
 (131, 216360490),
 (55, 214953905),
 (107, 212249198),
 (138, 210956898),
 (128, 208847384),
 (36, 193815224),
 (34, 192239672),
 (208, 184890644),
 (31, 178847930),
 (44, 178731369),
 (51, 169736090),
 (71, 167985456),
 (79, 167023808),
 (26, 155355920),
 (43, 149488115),
 (96, 146594911),
 (4, 146271037),
 (19, 145400000),
 (82, 144117573),
 (16, 142817841),
 (80, 141468935),
 (191, 136959590),
 (88, 133691277),
 (99, 132726605),
 (136, 129531208),
 (93, 128455420),
 (95, 128035572),
 (206, 123206493),
 (30, 120017848),
 (47, 112459006),
 (119, 108446695),
 (10, 106928112),
 (137, 103358016),
 (81, 102782518),
 (122, 102576682),
 (155, 101265204),
 (104, 100700000),
 (83, 97993801),
 (176, 92551549),
 (77, 88613482),
 (52, 79400000),
 (75, 75900000),
 (76, 71487563),
 (120, 71005663),
 (118, 67879389),
 (35, 67241171),
 (66, 67241171),
 (89, 62783718),
 (127, 62233971),
 (78, 61485708),
 (198, 61300000),
 (163, 60158135),
 (161, 59163710),
 (148, 51932573),
 (102, 51056530),
 (53, 50900000),
 (199, 50055398),
 (166, 49501119),
 (20, 48976250),
 (168, 47549422),
 (9, 46229335),
 (147, 46144051),
 (45, 45395745),
 (17, 45080579),
 (132, 44612298),
 (192, 44300000),
 (85, 43368842),
 (110, 42376224),
 (202, 36687665),
 (181, 35579349),
 (158, 35312586),
 (64, 32295262),
 (65, 30538833),
 (39, 28673154),
 (115, 27839725),
 (113, 26409247),
 (195, 26409247),
 (179, 25402267),
 (58, 24154026),
 (153, 23193471),
 (124, 22426076),
 (106, 22150183),
 (90, 21371017),
 (46, 21100000),
 (57, 20572749),
 (130, 20384127),
 (170, 20071250),
 (29, 19499811),
 (193, 19466789),
 (67, 17983283),
 (84, 16148711),
 (162, 15666190),
 (129, 11299863),
 (157, 11223890),
 (194, 10558482),
 (172, 5922163),
 (180, 4957475),
 (197, 4144455),
 (207, 4050401),
 (117, 3333531),
 (6, 2982519),
 (188, 2772013),
 (203, 2596350),
 (140, 2232717),
 (114, 2185224),
 (174, 1314203),
 (112, 1180013),
 (139, 862650),
 (187, 295978),
 (184, 140096),
 (171, 108832),
 (186, 24654),
 (160, 6265),
 (201, -91954),
 (177, -319419),
 (205, -390290),
 (204, -490073),
 (183, -490604),
 (185, -1154509),
 (196, -1208693),
 (97, -1478413),
 (142, -2127402),
 (105, -2395277),
 (209, -2413033),
 (126, -2551559),
 (154, -2664158),
 (72, -3778029),
 (178, -4234465),
 (141, -5468927),
 (169, -5929196),
 (190, -7564037),
 (123, -8136494),
 (116, -8852544),
 (175, -9465648),
 (182, -9904121),
 (60, -11414584),
 (189, -12057907),
 (28, -12787249),
 (73, -17854621),
 (151, -20059610),
 (62, -20894793),
 (111, -24527515),
 (86, -25459338),
 (91, -26491142),
 (109, -28989393),
 (61, -30651554),
 (13, -33396176),
 (156, -36064237),
 (103, -43225568),
 (98, -44373310),
 (100, -50129433),
 (121, -57323212),
 (92, -59158877),
 (54, -90000000),
 (68, -94635231),
 (133, -96615873),
 (18, -110450242)]

In [80]:
# getting the name of movies for the lollipop graph
new21 = []
for i in neww:
    new21.append(dataframe1.Name[i[0]])
for i,x in enumerate(new21):
    print(i,x)

0 Snow White and the Seven Dwarfs
1 The Jungle Book(1967)
2 The Sound of Music
3 The Avengers
4 Frozen
5 Beauty and the Beast
6 The Lord of the Rings: The Return of the King
7 Despicable Me 3
8 Harry Potter and the Deathly Hallows: Part I
9 Finding Dory
10 Mary Poppins
11 The Dark Knight
12 Harry Potter and the Chamber of Secrets
13 Harry Potter and the Chamber of Secrets
14 The Hobbit: An Unexpected Journey
15 The Hunger Games: Catching Fire
16 Harry Potter and the Prisoner of Azkaban
17 The Twilight Saga: Eclipse
18 Suicide Squad
19 Up
20 Psycho
21 Back to the Future
22 Kung Fu Panda
23 Casino Royale
24 Fiddler on the Roof
25 Fight Club
26 Terminator 2: Judgment Day
27 Terminator 2: Judgment Day
28 The Little Mermaid
29 How to Train Your Dragon: The Hidden World
30 Mr. and Mrs. Smith
31 Godzilla
32 Quantum of Solace
33 World War Z
34 The Last Starfighter
35 Clue
36 The Mummy
37 A Bug's Life
38 Karate Kid
39 Kingsman: The Secret Service
40 Crouching Tiger, Hidden Dragon
41 Jason Bourne
42 Murder on the Orient Express
43 Apollo 13
44 Jurassic Park III
45 Jurassic Park III
46 Wanted
47 Warcraft
48 Minority Report
49 Ocean's Twelve
50 Angry Men
51 Mission: Impossible III
52 National Treasure
53 The Impossible
54 The Mummy
55 A Good Day to Die Hard
56 Hidden Figures
57 Life Is Beautiful
58 Stuart Little
59 Passengers
60 Solaris
61 Ferdinand
62 The Tourist
63 Charlie's Angels
64 American Gangster
65 Grown Ups 2
66 The Bourne Legacy
67 Eragon
68 Constantine
69 The Good Dinosaur
70 Lethal Weapon 4
71 Con Air
72 G-Force
73 Bedtime Stories
74 Midnight in Paris
75 Smallfoot
76 Vanilla Sky
77 Finding Neverland
78 Red Dragon
79 Hairspray
80 Mona Lisa Smile drawing
81 Gulliver's Travels
82 Robin Hood
83 The Chorus
84 Alice Through the Looking Glass
85 Groundhog Day
86 Daredevil
87 The Cider House Rules
88
89 Alien: Resurrection
90 Flubber
91 The Lady Vanishes
92 Mirror Mirror
93 The Saint
94 Contact
95 The Predator
96 The Kite Runner
97 Departures
98 The A-Team
99 The A-Team
100 Conspiracy Theory
101 Invictus
102 Charlotte's Web
103 Moonlight
104 Fear of Rain
105 Dark Star
106 The Great Muppet Caper
107 Body of Lies
108 The Devil's Own
109 3 Ninjas
110 Rear Window
111 Watchmen
112 The Usual Suspects
113 Wild Wild West
114 Singin' in the Rain
115 Surf's Up
116 Beowulf
117 The Sea Inside
118 Frida
119 Walking with Dinosaurs
120 Bedazzled
121 Loving Vincent
122 Lagaan
123 Walking Tall
124 Colombiana
125 Because I Said So
126 Cloud Atlas
127  The New World
128 The Tree of Life
129 The Tree of Life
130 Tell No One
131 Priest
132 Space Buddies
133 A Separation
134 Reign of Fire
135 Mars Attacks!
136 Starship Troopers
137 Killers
138 The Perks of Being a Wallflower
139 Memento
140 AstÃ©rix aux Jeux Olympiques
141 Girl with a Pearl Earring
142 Ender's Game
143 The Manchurian Candidate
144 Ice Station Zebra (1968)
145 The Diving Bell and the Butterfly
146 Timeline
147 Mr. Turner
148 The Little Prince
149
150 Rivers and Tides
151 Days of Heaven
152 The Box
153 Jupiter Ascending
154 Days of Heaven
155 The Best Offer
156 The Imposter
157 Another Earth
158 Rear Window
159 Primer
160 Boy Erased
161 Bicycle Thieves
162 Where the Wild Things Are
163 Reindeer Games
164 Tokyo Story
165 WALL• E
166 Walt Before Mickey
167 North by Northwest
168 La Belle Noiseuse
169 Basquiat (film)
170  Badlands
171 Andrei Rublev
172 Waste Land
173 Life
174 My Life as a Zucchini
175 Year One
176 The Conformist
177  Dear Frankie
178 Muppets From Space
179 The Stepford Wives
180 Palm Springs
181 happy as lazzaro
182 Se7en
183 Under the Skin
184 A Better Life
185 Restless
186 The Night of the Hunter
187 April and the Extraordinary World
188 The Avengers
189 Suspiria
190 The Chronicles of Riddick
191 Catwoman
192 The Swan Princess
193 Instinct
194 The Fountain
195 Looney Tunes: Back in Action
196 Nine
197 Bulletproof Monk
198 The Kid Who Would Be King
199 Deepwater Horizon
200 The League of Extraordinary Gentlemen
201 Live by Night
202 Virus
203 Hard Rain
204 Radio Flyer
205 The Postman
206 Bright
207 Town & Country
208 The Perks of Being a Wallflower
209 Mars Needs Moms

Using a for loop to put the name and profit in html code which will be copied and pasted in the cell below.

In [81]:
for x in range(len(new21)):
    print('        }, { \n           name:',"'",new21[x],"'",','+'\n           low:',neww[x][1])

        }, {
           name: ' Snow White and the Seven Dwarfs ' ,
           low: 7749287553
        }, {
           name: ' The Jungle Book(1967)  ' ,
           low: 2961011429
        }, {
           name: ' The Sound of Music ' ,
           low: 2321008636
        }, {
           name: ' The Avengers ' ,
           low: 1292935897
        }, {
           name: ' Frozen ' ,
           low: 1122469910
        }, {
           name: ' Beauty and the Beast ' ,
           low: 1099199706
        }, {
           name: ' The Lord of the Rings: The Return of the King ' ,
           low: 1047403341
        }, {
           name: ' Despicable Me 3 ' ,
           low: 959727750
        }, {
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           low: 835431568
        }, {
           name: ' Finding Dory ' ,
           low: 821215193
        }, {
           name: ' Mary Poppins ' ,
           low: 820165063
        }, {
           name: ' The Dark Knight ' ,
           low: 816996207
        }, {
           name: ' Harry Potter and the Chamber of Secrets ' ,
           low: 779225135
        }, {
           name: ' Harry Potter and the Chamber of Secrets ' ,
           low: 779225135
        }, {
           name: ' The Hobbit: An Unexpected Journey ' ,
           low: 767003568
        }, {
           name: ' The Hunger Games: Catching Fire ' ,
           low: 734868047
        }, {
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           low: 666907323
        }, {
           name: ' The Twilight Saga: Eclipse ' ,
           low: 638102828
        }, {
           name: ' Suicide Squad ' ,
           low: 571059887
        }, {
           name: ' Up ' ,
           low: 556463377
        }, {
           name: ' Psycho ' ,
           low: 513510733
        }, {
           name: ' Back to the Future ' ,
           low: 502314657
        }, {
           name: ' Kung Fu Panda ' ,
           low: 501910531
        }, {
           name: ' Casino Royale ' ,
           low: 492420283
        }, {
           name: ' Fiddler on the Roof ' ,
           low: 467944335
        }, {
           name: ' Fight Club  ' ,
           low: 435833717
        }, {
           name: ' Terminator 2: Judgment Day ' ,
           low: 415419827
        }, {
           name: ' Terminator 2: Judgment Day ' ,
           low: 415419827
        }, {
           name: ' The Little Mermaid ' ,
           low: 394060973
        }, {
           name: ' How to Train Your Dragon: The Hidden World ' ,
           low: 390258283
        }, {
           name: ' Mr. and Mrs. Smith ' ,
           low: 376124090
        }, {
           name: ' Godzilla ' ,
           low: 375000000
        }, {
           name: ' Quantum of Solace ' ,
           low: 361692078
        }, {
           name: ' World War Z ' ,
           low: 341514650
        }, {
           name: ' The Last Starfighter ' ,
           low: 341311860
        }, {
           name: ' Clue ' ,
           low: 339240892
        }, {
           name: ' The Mummy ' ,
           low: 336385488
        }, {
           name: ' A Bug's Life ' ,
           low: 318095319
        }, {
           name: ' Karate Kid ' ,
           low: 314728703
        }, {
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, {
           name: ' Crouching Tiger, Hidden Dragon  ' ,
           low: 304141192
        }, {
           name: ' Jason Bourne ' ,
           low: 296168316
        }, {
           name: ' Murder on the Orient Express ' ,
           low: 290922730
        }, {
           name: ' Apollo 13 ' ,
           low: 281592771
        }, {
           name: ' Jurassic Park III ' ,
           low: 272900000
        }, {
           name: ' Jurassic Park III ' ,
           low: 272900000
        }, {
           name: ' Wanted ' ,
           low: 267416460
        }, {
           name: ' Warcraft ' ,
           low: 265522281
        }, {
           name: ' Minority Report ' ,
           low: 256824714
        }, {
           name: ' Ocean's Twelve ' ,
           low: 252989076
        }, {
           name: ' Angry Men ' ,
           low: 247796314
        }, {
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, {
           name: ' National Treasure ' ,
           low: 231323410
        }, {
           name: ' The Impossible ' ,
           low: 216360490
        }, {
           name: ' The Mummy ' ,
           low: 214953905
        }, {
           name: ' A Good Day to Die Hard ' ,
           low: 212249198
        }, {
           name: ' Hidden Figures ' ,
           low: 210956898
        }, {
           name: ' Life Is Beautiful ' ,
           low: 208847384
        }, {
           name: ' Stuart Little ' ,
           low: 193815224
        }, {
           name: ' Passengers ' ,
           low: 192239672
        }, {
           name: ' Solaris ' ,
           low: 184890644
        }, {
           name: ' Ferdinand ' ,
           low: 178847930
        }, {
           name: ' The Tourist ' ,
           low: 178731369
        }, {
           name: ' Charlie's Angels ' ,
           low: 169736090
        }, {
           name: ' American Gangster ' ,
           low: 167985456
        }, {
           name: ' Grown Ups 2 ' ,
           low: 167023808
        }, {
           name: ' The Bourne Legacy ' ,
           low: 155355920
        }, {
           name: ' Eragon ' ,
           low: 149488115
        }, {
           name: ' Constantine ' ,
           low: 146594911
        }, {
           name: ' The Good Dinosaur ' ,
           low: 146271037
        }, {
           name: ' Lethal Weapon 4 ' ,
           low: 145400000
        }, {
           name: ' Con Air ' ,
           low: 144117573
        }, {
           name: ' G-Force ' ,
           low: 142817841
        }, {
           name: ' Bedtime Stories ' ,
           low: 141468935
        }, {
           name: ' Midnight in Paris ' ,
           low: 136959590
        }, {
           name: ' Smallfoot ' ,
           low: 133691277
        }, {
           name: ' Vanilla Sky ' ,
           low: 132726605
        }, {
           name: ' Finding Neverland ' ,
           low: 129531208
        }, {
           name: ' Red Dragon ' ,
           low: 128455420
        }, {
           name: ' Hairspray ' ,
           low: 128035572
        }, {
           name: ' Mona Lisa Smile drawing ' ,
           low: 123206493
        }, {
           name: ' Gulliver's Travels ' ,
           low: 120017848
        }, {
           name: ' Robin Hood ' ,
           low: 112459006
        }, {
           name: ' The Chorus ' ,
           low: 108446695
        }, {
           name: ' Alice Through the Looking Glass ' ,
           low: 106928112
        }, {
           name: ' Groundhog Day ' ,
           low: 103358016
        }, {
           name: ' Daredevil ' ,
           low: 102782518
        }, {
           name: ' The Cider House Rules ' ,
           low: 102576682
        }, {
           name: '  ' ,
           low: 101265204
        }, {
           name: ' Alien: Resurrection ' ,
           low: 100700000
        }, {
           name: ' Flubber ' ,
           low: 97993801
        }, {
           name: ' The Lady Vanishes ' ,
           low: 92551549
        }, {
           name: ' Mirror Mirror ' ,
           low: 88613482
        }, {
           name: ' The Saint ' ,
           low: 79400000
        }, {
           name: ' Contact ' ,
           low: 75900000
        }, {
           name: ' The Predator ' ,
           low: 71487563
        }, {
           name: ' The Kite Runner ' ,
           low: 71005663
        }, {
           name: ' Departures ' ,
           low: 67879389
        }, {
           name: ' The A-Team ' ,
           low: 67241171
        }, {
           name: ' The A-Team ' ,
           low: 67241171
        }, {
           name: ' Conspiracy Theory ' ,
           low: 62783718
        }, {
           name: ' Invictus ' ,
           low: 62233971
        }, {
           name: ' Charlotte's Web ' ,
           low: 61485708
        }, {
           name: ' Moonlight ' ,
           low: 61300000
        }, {
           name: ' Fear of Rain ' ,
           low: 60158135
        }, {
           name: ' Dark Star ' ,
           low: 59163710
        }, {
           name: ' The Great Muppet Caper ' ,
           low: 51932573
        }, {
           name: ' Body of Lies ' ,
           low: 51056530
        }, {
           name: ' The Devil's Own ' ,
           low: 50900000
        }, {
           name: ' 3 Ninjas ' ,
           low: 50055398
        }, {
           name: ' Rear Window ' ,
           low: 49501119
        }, {
           name: ' Watchmen ' ,
           low: 48976250
        }, {
           name: ' The Usual Suspects ' ,
           low: 47549422
        }, {
           name: ' Wild Wild West ' ,
           low: 46229335
        }, {
           name: ' Singin' in the Rain ' ,
           low: 46144051
        }, {
           name: ' Surf's Up ' ,
           low: 45395745
        }, {
           name: ' Beowulf ' ,
           low: 45080579
        }, {
           name: ' The Sea Inside ' ,
           low: 44612298
        }, {
           name: ' Frida ' ,
           low: 44300000
        }, {
           name: ' Walking with Dinosaurs ' ,
           low: 43368842
        }, {
           name: ' Bedazzled ' ,
           low: 42376224
        }, {
           name: ' Loving Vincent ' ,
           low: 36687665
        }, {
           name: ' Lagaan ' ,
           low: 35579349
        }, {
           name: ' Walking Tall ' ,
           low: 35312586
        }, {
           name: ' Colombiana ' ,
           low: 32295262
        }, {
           name: ' Because I Said So ' ,
           low: 30538833
        }, {
           name: ' Cloud Atlas ' ,
           low: 28673154
        }, {
           name: '  The New World ' ,
           low: 27839725
        }, {
           name: ' The Tree of Life ' ,
           low: 26409247
        }, {
           name: ' The Tree of Life ' ,
           low: 26409247
        }, {
           name: ' Tell No One ' ,
           low: 25402267
        }, {
           name: ' Priest ' ,
           low: 24154026
        }, {
           name: ' Space Buddies ' ,
           low: 23193471
        }, {
           name: ' A Separation ' ,
           low: 22426076
        }, {
           name: ' Reign of Fire ' ,
           low: 22150183
        }, {
           name: ' Mars Attacks! ' ,
           low: 21371017
        }, {
           name: ' Starship Troopers ' ,
           low: 21100000
        }, {
           name: ' Killers ' ,
           low: 20572749
        }, {
           name: ' The Perks of Being a Wallflower ' ,
           low: 20384127
        }, {
           name: ' Memento ' ,
           low: 20071250
        }, {
           name: ' AstÃ©rix aux Jeux Olympiques ' ,
           low: 19499811
        }, {
           name: ' Girl with a Pearl Earring ' ,
           low: 19466789
        }, {
           name: ' Ender's Game ' ,
           low: 17983283
        }, {
           name: ' The Manchurian Candidate ' ,
           low: 16148711
        }, {
           name: ' Ice Station Zebra (1968) ' ,
           low: 15666190
        }, {
           name: ' The Diving Bell and the Butterfly ' ,
           low: 11299863
        }, {
           name: ' Timeline ' ,
           low: 11223890
        }, {
           name: ' Mr. Turner ' ,
           low: 10558482
        }, {
           name: ' The Little Prince ' ,
           low: 5922163
        }, {
           name: '  ' ,
           low: 4957475
        }, {
           name: ' Rivers and Tides ' ,
           low: 4144455
        }, {
           name: ' Days of Heaven ' ,
           low: 4050401
        }, {
           name: ' The Box ' ,
           low: 3333531
        }, {
           name: ' Jupiter Ascending ' ,
           low: 2982519
        }, {
           name: ' Days of Heaven ' ,
           low: 2772013
        }, {
           name: ' The Best Offer  ' ,
           low: 2596350
        }, {
           name: ' The Imposter ' ,
           low: 2232717
        }, {
           name: ' Another Earth ' ,
           low: 2185224
        }, {
           name: ' Rear Window ' ,
           low: 1314203
        }, {
           name: ' Primer ' ,
           low: 1180013
        }, {
           name: ' Boy Erased ' ,
           low: 862650
        }, {
           name: ' Bicycle Thieves ' ,
           low: 295978
        }, {
           name: ' Where the Wild Things Are ' ,
           low: 140096
        }, {
           name: ' Reindeer Games ' ,
           low: 108832
        }, {
           name: ' Tokyo Story ' ,
           low: 24654
        }, {
           name: ' WALL• E ' ,
           low: 6265
        }, {
           name: ' Walt Before Mickey ' ,
           low: -91954
        }, {
           name: ' North by Northwest ' ,
           low: -319419
        }, {
           name: ' La Belle Noiseuse ' ,
           low: -390290
        }, {
           name: ' Basquiat (film) ' ,
           low: -490073
        }, {
           name: '  Badlands ' ,
           low: -490604
        }, {
           name: ' Andrei Rublev ' ,
           low: -1154509
        }, {
           name: ' Waste Land ' ,
           low: -1208693
        }, {
           name: ' Life ' ,
           low: -1478413
        }, {
           name: ' My Life as a Zucchini ' ,
           low: -2127402
        }, {
           name: ' Year One ' ,
           low: -2395277
        }, {
           name: ' The Conformist ' ,
           low: -2413033
        }, {
           name: '  Dear Frankie ' ,
           low: -2551559
        }, {
           name: ' Muppets From Space ' ,
           low: -2664158
        }, {
           name: ' The Stepford Wives ' ,
           low: -3778029
        }, {
           name: ' Palm Springs ' ,
           low: -4234465
        }, {
           name: ' happy as lazzaro ' ,
           low: -5468927
        }, {
           name: ' Se7en ' ,
           low: -5929196
        }, {
           name: ' Under the Skin ' ,
           low: -7564037
        }, {
           name: ' A Better Life ' ,
           low: -8136494
        }, {
           name: ' Restless  ' ,
           low: -8852544
        }, {
           name: ' The Night of the Hunter ' ,
           low: -9465648
        }, {
           name: ' April and the Extraordinary World ' ,
           low: -9904121
        }, {
           name: ' The Avengers ' ,
           low: -11414584
        }, {
           name: ' Suspiria ' ,
           low: -12057907
        }, {
           name: ' The Chronicles of Riddick ' ,
           low: -12787249
        }, {
           name: ' Catwoman ' ,
           low: -17854621
        }, {
           name: ' The Swan Princess ' ,
           low: -20059610
        }, {
           name: ' Instinct ' ,
           low: -20894793
        }, {
           name: ' The Fountain ' ,
           low: -24527515
        }, {
           name: ' Looney Tunes: Back in Action ' ,
           low: -25459338
        }, {
           name: ' Nine ' ,
           low: -26491142
        }, {
           name: ' Bulletproof Monk ' ,
           low: -28989393
        }, {
           name: ' The Kid Who Would Be King ' ,
           low: -30651554
        }, {
           name: ' Deepwater Horizon ' ,
           low: -33396176
        }, {
           name: ' The League of Extraordinary Gentlemen ' ,
           low: -36064237
        }, {
           name: ' Live by Night ' ,
           low: -43225568
        }, {
           name: ' Virus ' ,
           low: -44373310
        }, {
           name: ' Hard Rain ' ,
           low: -50129433
        }, {
           name: ' Radio Flyer  ' ,
           low: -57323212
        }, {
           name: ' The Postman ' ,
           low: -59158877
        }, {
           name: ' Bright ' ,
           low: -90000000
        }, {
           name: ' Town & Country ' ,
           low: -94635231
        }, {
           name: ' The Perks of Being a Wallflower ' ,
           low: -96615873
        }, {
           name: ' Mars Needs Moms ' ,
           low: -110450242

In [37]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/dumbbell.js"></script>
<script src="https://code.highcharts.com/modules/lollipop.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="r7" style-"min-width:310 px; max-width: 800px; height: 400px; margin: 0 auto"></div> 
    <p class= "highcharts-description">
    </p>
</figure>

In [38]:
%%js
Highcharts.chart('r7', { //name of grapg is r1

    chart: {
        type: 'lollipop', //type of graph is the lollipop graph
        inverted:true, //this makes the graph horizontal
        height: 1600, //this allows the size of the graph to be ajusted
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. {xDescription}, {point.y}.'
        }
    },

    legend: {
        enabled: true,
        layout:'horizontal',
        reversed:true
    },

    subtitle: {
        text: '158 Movies'
    },

    title: {
        text: 'Classic Genre'
    },

    tooltip: {
        shared: true //allows the tooltip to be enabled
    },

    xAxis: {
        type:'category',
        title:{
            text:'Movies' //name of x-axis
        }
    },
    yAxis:{
        title:{
            text:'Profit' //name of y-axis
        }
    },
    series: [{
        name: 'Profit',
        color:'gold', //allows color to be adjusted
        dataSorting:{
            enabled: false
        },
        data: [{ 
           name: ' Snow White and the Seven Dwarfs ' ,//name of movie
           low: 7749287553//amount of profit made in int of the movie
        }, { 
           name: ' The Jungle Book(1967)  ' ,
           low: 2961011429
        }, { 
           name: ' The Sound of Music ' ,
           low: 2321008636
        }, { 
           name: ' The Avengers ' ,
           low: 1292935897
        }, { 
           name: ' Frozen ' ,
           low: 1122469910
        }, { 
           name: ' Beauty and the Beast ' ,
           low: 1099199706
        }, { 
           name: ' The Lord of the Rings: The Return of the King ' ,
           low: 1047403341
        }, { 
           name: ' Despicable Me 3 ' ,
           low: 959727750
        }, { 
           name: ' Harry Potter and the Deathly Hallows: Part I ' ,
           low: 835431568
        }, { 
           name: ' Finding Dory ' ,
           low: 821215193
        }, { 
           name: ' Mary Poppins ' ,
           low: 820165063
        }, { 
           name: ' The Dark Knight ' ,
           low: 816996207
        }, { 
           name: ' Harry Potter and the Chamber of Secrets ' ,
           low: 779225135
        }, { 
           name: ' Harry Potter and the Chamber of Secrets ' ,
           low: 779225135
        }, { 
           name: ' The Hobbit: An Unexpected Journey ' ,
           low: 767003568
        }, { 
           name: ' The Hunger Games: Catching Fire ' ,
           low: 734868047
        }, { 
           name: ' Harry Potter and the Prisoner of Azkaban ' ,
           low: 666907323
        }, { 
           name: ' The Twilight Saga: Eclipse ' ,
           low: 638102828
        }, { 
           name: ' Suicide Squad ' ,
           low: 571059887
        }, { 
           name: ' Up ' ,
           low: 556463377
        }, { 
           name: ' Psycho ' ,
           low: 513510733
        }, { 
           name: ' Back to the Future ' ,
           low: 502314657
        }, { 
           name: ' Kung Fu Panda ' ,
           low: 501910531
        }, { 
           name: ' Casino Royale ' ,
           low: 492420283
        }, { 
           name: ' Fiddler on the Roof ' ,
           low: 467944335
        }, { 
           name: ' Fight Club  ' ,
           low: 435833717
        }, { 
           name: ' Terminator 2: Judgment Day ' ,
           low: 415419827
        }, { 
           name: ' Terminator 2: Judgment Day ' ,
           low: 415419827
        }, { 
           name: ' The Little Mermaid ' ,
           low: 394060973
        }, { 
           name: ' How to Train Your Dragon: The Hidden World ' ,
           low: 390258283
        }, { 
           name: ' Mr. and Mrs. Smith ' ,
           low: 376124090
        }, { 
           name: ' Godzilla ' ,
           low: 375000000
        }, { 
           name: ' Quantum of Solace ' ,
           low: 361692078
        }, { 
           name: ' World War Z ' ,
           low: 341514650
        }, { 
           name: ' The Last Starfighter ' ,
           low: 341311860
        }, { 
           name: ' Clue ' ,
           low: 339240892
        }, { 
           name: ' The Mummy ' ,
           low: 336385488
        }, { 
           name: ' A Bug\'s Life ' ,
           low: 318095319
        }, { 
           name: ' Karate Kid ' ,
           low: 314728703
        }, { 
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, { 
           name: ' Crouching Tiger, Hidden Dragon  ' ,
           low: 304141192
        }, { 
           name: ' Jason Bourne ' ,
           low: 296168316
        }, { 
           name: ' Murder on the Orient Express ' ,
           low: 290922730
        }, { 
           name: ' Apollo 13 ' ,
           low: 281592771
        }, { 
           name: ' Jurassic Park III ' ,
           low: 272900000
        }, { 
           name: ' Jurassic Park III ' ,
           low: 272900000
        }, { 
           name: ' Wanted ' ,
           low: 267416460
        }, { 
           name: ' Warcraft ' ,
           low: 265522281
        }, { 
           name: ' Minority Report ' ,
           low: 256824714
        }, { 
           name: ' Ocean\'s Twelve ' ,
           low: 252989076
        }, { 
           name: ' Angry Men ' ,
           low: 247796314
        }, { 
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, { 
           name: ' National Treasure ' ,
           low: 231323410
        }, { 
           name: ' The Impossible ' ,
           low: 216360490
        }, { 
           name: ' The Mummy ' ,
           low: 214953905
        }, { 
           name: ' A Good Day to Die Hard ' ,
           low: 212249198
        }, { 
           name: ' Hidden Figures ' ,
           low: 210956898
        }, { 
           name: ' Life Is Beautiful ' ,
           low: 208847384
        }, { 
           name: ' Stuart Little ' ,
           low: 193815224
        }, { 
           name: ' Passengers ' ,
           low: 192239672
        }, { 
           name: ' Solaris ' ,
           low: 184890644
        }, { 
           name: ' Ferdinand ' ,
           low: 178847930
        }, { 
           name: ' The Tourist ' ,
           low: 178731369
        }, { 
           name: ' Charlie\'s Angels ' ,
           low: 169736090
        }, { 
           name: ' American Gangster ' ,
           low: 167985456
        }, { 
           name: ' Grown Ups 2 ' ,
           low: 167023808
        }, { 
           name: ' The Bourne Legacy ' ,
           low: 155355920
        }, { 
           name: ' Eragon ' ,
           low: 149488115
        }, { 
           name: ' Constantine ' ,
           low: 146594911
        }, { 
           name: ' The Good Dinosaur ' ,
           low: 146271037
        }, { 
           name: ' Lethal Weapon 4 ' ,
           low: 145400000
        }, { 
           name: ' Con Air ' ,
           low: 144117573
        }, { 
           name: ' G-Force ' ,
           low: 142817841
        }, { 
           name: ' Bedtime Stories ' ,
           low: 141468935
        }, { 
           name: ' Midnight in Paris ' ,
           low: 136959590
        }, { 
           name: ' Smallfoot ' ,
           low: 133691277
        }, { 
           name: ' Vanilla Sky ' ,
           low: 132726605
        }, { 
           name: ' Finding Neverland ' ,
           low: 129531208
        }, { 
           name: ' Red Dragon ' ,
           low: 128455420
        }, { 
           name: ' Hairspray ' ,
           low: 128035572
        }, { 
           name: ' Mona Lisa Smile drawing ' ,
           low: 123206493
        }, { 
           name: ' Gulliver\'s Travels ' ,
           low: 120017848
        }, { 
           name: ' Robin Hood ' ,
           low: 112459006
        }, { 
           name: ' The Chorus ' ,
           low: 108446695
        }, { 
           name: ' Alice Through the Looking Glass ' ,
           low: 106928112
        }, { 
           name: ' Groundhog Day ' ,
           low: 103358016
        }, { 
           name: ' Daredevil ' ,
           low: 102782518
        }, { 
           name: ' The Cider House Rules ' ,
           low: 102576682
        }, { 
           name: ' o' ,
           low: 101265204
        }, { 
           name: ' Alien: Resurrection ' ,
           low: 100700000
        }, { 
           name: ' Flubber ' ,
           low: 97993801
        }, { 
           name: ' The Lady Vanishes ' ,
           low: 92551549
        }, { 
           name: ' Mirror Mirror ' ,
           low: 88613482
        }, { 
           name: ' The Saint ' ,
           low: 79400000
        }, { 
           name: ' Contact ' ,
           low: 75900000
        }, { 
           name: ' The Predator ' ,
           low: 71487563
        }, { 
           name: ' The Kite Runner ' ,
           low: 71005663
        }, { 
           name: ' Departures ' ,
           low: 67879389
        }, { 
           name: ' The A-Team ' ,
           low: 67241171
        }, { 
           name: ' The A-Team ' ,
           low: 67241171
        }, { 
           name: ' Conspiracy Theory ' ,
           low: 62783718
        }, { 
           name: ' Invictus ' ,
           low: 62233971
        }, { 
           name: ' Charlotte\'s Web ' ,
           low: 61485708
        }, { 
           name: ' Moonlight ' ,
           low: 61300000
        }, { 
           name: ' Fear of Rain ' ,
           low: 60158135
        }, { 
           name: ' Dark Star ' ,
           low: 59163710
        }, { 
           name: ' The Great Muppet Caper ' ,
           low: 51932573
        }, { 
           name: ' Body of Lies ' ,
           low: 51056530
        }, { 
           name: ' The Devil\'s Own ' ,
           low: 50900000
        }, { 
           name: ' 3 Ninjas ' ,
           low: 50055398
        }, { 
           name: ' Rear Window ' ,
           low: 49501119
        }, { 
           name: ' Watchmen ' ,
           low: 48976250
        }, { 
           name: ' The Usual Suspects ' ,
           low: 47549422
        }, { 
           name: ' Wild Wild West ' ,
           low: 46229335
        }, { 
           name: ' Singin\' in the Rain ' ,
           low: 46144051
        }, { 
           name: ' Surf\'s Up ' ,
           low: 45395745
        }, { 
           name: ' Beowulf ' ,
           low: 45080579
        }, { 
           name: ' The Sea Inside ' ,
           low: 44612298
        }, { 
           name: ' Frida ' ,
           low: 44300000
        }, { 
           name: ' Walking with Dinosaurs ' ,
           low: 43368842
        }, { 
           name: ' Bedazzled ' ,
           low: 42376224
        }, { 
           name: ' Loving Vincent ' ,
           low: 36687665
        }, { 
           name: ' Lagaan ' ,
           low: 35579349
        }, { 
           name: ' Walking Tall ' ,
           low: 35312586
        }, { 
           name: ' Colombiana ' ,
           low: 32295262
        }, { 
           name: ' Because I Said So ' ,
           low: 30538833
        }, { 
           name: ' Cloud Atlas ' ,
           low: 28673154
        }, { 
           name: '  The New World ' ,
           low: 27839725
        }, { 
           name: ' The Tree of Life ' ,
           low: 26409247
        }, { 
           name: ' The Tree of Life ' ,
           low: 26409247
        }, { 
           name: ' Tell No One ' ,
           low: 25402267
        }, { 
           name: ' Priest ' ,
           low: 24154026
        }, { 
           name: ' Space Buddies ' ,
           low: 23193471
        }, { 
           name: ' A Separation ' ,
           low: 22426076
        }, { 
           name: ' Reign of Fire ' ,
           low: 22150183
        }, { 
           name: ' Mars Attacks! ' ,
           low: 21371017
        }, { 
           name: ' Starship Troopers ' ,
           low: 21100000
        }, { 
           name: ' Killers ' ,
           low: 20572749
        }, { 
           name: ' The Perks of Being a Wallflower ' ,
           low: 20384127
        }, { 
           name: ' Memento ' ,
           low: 20071250
        }, { 
           name: ' AstÃ©rix aux Jeux Olympiques ' ,
           low: 19499811
        }, { 
           name: ' Girl with a Pearl Earring ' ,
           low: 19466789
        }, { 
           name: ' Ender\'s Game ' ,
           low: 17983283
        }, { 
           name: ' The Manchurian Candidate ' ,
           low: 16148711
        }, { 
           name: ' Ice Station Zebra (1968) ' ,
           low: 15666190
        }, { 
           name: ' The Diving Bell and the Butterfly ' ,
           low: 11299863
        }, { 
           name: ' Timeline ' ,
           low: 11223890
        }, { 
           name: ' Mr. Turner ' ,
           low: 10558482
        }, { 
           name: ' The Little Prince ' ,
           low: 5922163
        }, { 
           name: ' 0 ' ,
           low: 4957475
        }, { 
           name: ' Rivers and Tides ' ,
           low: 4144455
        }, { 
           name: ' Days of Heaven ' ,
           low: 4050401
        }, { 
           name: ' The Box ' ,
           low: 3333531
        }, { 
           name: ' Jupiter Ascending ' ,
           low: 2982519
        }, { 
           name: ' Days of Heaven ' ,
           low: 2772013
        }, { 
           name: ' The Best Offer  ' ,
           low: 2596350
        }, { 
           name: ' The Imposter ' ,
           low: 2232717
        }, { 
           name: ' Another Earth ' ,
           low: 2185224
        }, { 
           name: ' Rear Window ' ,
           low: 1314203
        }, { 
           name: ' Primer ' ,
           low: 1180013
        }, { 
           name: ' Boy Erased ' ,
           low: 862650
        }, { 
           name: ' Bicycle Thieves ' ,
           low: 295978
        }, { 
           name: ' Where the Wild Things Are ' ,
           low: 140096
        }, { 
           name: ' Reindeer Games ' ,
           low: 108832
        }, { 
           name: ' Tokyo Story ' ,
           low: 24654
        }, { 
           name: ' WALL• E ' ,
           low: 6265
        }]
    }]
});

# Blueprint: Movies that did not make any Profit.

This is the blueprint for creating the eight visualization, movies that did not make any profit. Highcharts will be used to create this graph. 

__Blueprint:__
     
   - The graph used for this visualazation is Highcharts Column chart with negative values series which is found in the Highcharts Demos. Column charts are mostly used to compare categories with different values including negative value, they are very popular and transparant types of charts.
    
 The first approach to this chart is by understanding the format of the code script. Like the previous data visualization this graph is constructed by two different types of code HTML and Javascript. The HTML script is very similar to the previous graph, they allow the column graph to produce negative column and comparison between any particular value of the movie. Closing of the script is similar to the previous script but with a unique name to it self;
                              <figure class="highcharts-figure">
                              <div id="w1"></div> 
                              <p class="highcharts-description">
                              </p>
                              </figure>
The second approach is scripting the javascript section. The javascript section is entirely different to the previous graph, before diving into the javascript code there needs to be data extracted. The names of all the movies that didn't make any profit which will be extracted from the parent dataframe, also the cost, the loss and the revenue of all the movies that did not make any profit.

- There are five major sections in the javascript section that are very critical.
     - 1. The list that is called categories is where all the names of all the movies that were not profitable are scripted. 
                             categories:['Random Hearts','Gods of Egypt','Peter Pan','Children of Men','I Spy','Fantastica: A Boonie Bears','Thirteen Days','Downsizing','Mortal Engines','The Oegieloves','Spanglish','Mighty Joe Young', 'Land of the Lost','Windtalkers',"A Boy's Life",'R.I.P.D.','Soldier','Stealth','The Alamo', 'Renegades']
     
     - 2. The y-axis min, max and steps are very important values that are put in a specific way to allow most of the negative values to be visible, based on how large the other values were;
                              yAxis:{
                              min:-500000,
                              max:180000000,
                              step:50000,
                              },
     
     - 3. The series section has three sub-section;
         - The Cost category is a list consisting of all the amount of money spent to create the movies that were not profitable.
                name:'Cost',
                data:[64000000,140000000,100000000,76000000,70000000,90000000,80000000,
                     68000000,100000000,20000000,75000000,80000000,100000000,115000000,
                     90000000,130000000,75000000,138000000,92000000,77500000]
         - The Revenue category is a list consisting of all the money thta were made but not minus the cost of all the movies not profitable.
                name:'Revenue',
                data:[63200000,138836756,95255485,69845011,60279822,77151096,66554547,54462971,
                      85287417,1065907,54344321,50632037,69548641,77628265,42460000,
                      79076678,14623082,76416746,23911362,1521672]
         - The Loss category is a list showing all the amount of money that fell short, meaning the cost was higher than the revenue giving the loss negitative values. Each movie spent more tahn they anticipated to make. 
                name:'Loss',
                data:[-800000,-1163244,-4744515,-6154989,-9720178,-12848904,-13445453,
                  -13537029,-14712583,-18934093,-20655679,-29367963,-30451359,
                  -37371735,-47540000,-50923322,-60376918,-61583254,-68088638,
                  -75978328]

In [84]:
# getting the Cost of the movies that had losses
new3 = []
for i in neww[-44:]:
    new3.append(all_ArtHouseandIntern_info1.Buget[i[0]])
new3

[568000,
 1241979,
 1168044,
 5599766,
 558062,
 1300000,
 1500000,
 75000000,
 8000000,
 60000000,
 5181843,
 4893180,
 38141403,
 100000000,
 5000000,
 7271623,
 55716364,
 13300000,
 10000000,
 12918735,
 9618685,
 10400000,
 60000000,
 20000000,
 120000000,
 100000000,
 37516831,
 55000000,
 46324136,
 80000000,
 80000000,
 52000000,
 59000000,
 156000000,
 80000000,
 65000000,
 75000000,
 70000000,
 66110152,
 80000000,
 90000000,
 105000000,
 130000000,
 150000000]

In [85]:
# getting the Revenue of the movies with losses
new4 = []
for i in neww[-44:]:
    new4.append(all_ArtHouseandIntern_info1.Total_gross[i[0]])
new4

[476046,
 922560,
 777754,
 5109693,
 67458,
 145491,
 291307,
 73521587,
 5872598,
 57604723,
 2768810,
 2341621,
 35477245,
 96221971,
 765535,
 1802696,
 49787168,
 5735963,
 1863506,
 4066191,
 153037,
 495879,
 48585416,
 7942093,
 107212751,
 82145379,
 17457221,
 34105207,
 21796621,
 54540662,
 53508858,
 23010607,
 28348446,
 122603824,
 43935763,
 21774432,
 30626690,
 19870567,
 8786940,
 20841123,
 0,
 10364769,
 33384127,
 39549758]

In [88]:
# the the amount of losses for the movies with losses
for i in neww[-44:]:
    print(i[1])

-91954
-319419
-390290
-490073
-490604
-1154509
-1208693
-1478413
-2127402
-2395277
-2413033
-2551559
-2664158
-3778029
-4234465
-5468927
-5929196
-7564037
-8136494
-8852544
-9465648
-9904121
-11414584
-12057907
-12787249
-17854621
-20059610
-20894793
-24527515
-25459338
-26491142
-28989393
-30651554
-33396176
-36064237
-43225568
-44373310
-50129433
-57323212
-59158877
-90000000
-94635231
-96615873
-110450242

In [90]:
# the names of the movies with losses
new21[-44:]

['Walt Before Mickey',
 'North by Northwest',
 'La Belle Noiseuse',
 'Basquiat (film)',
 ' Badlands',
 'Andrei Rublev',
 'Waste Land',
 'Life',
 'My Life as a Zucchini',
 'Year One',
 'The Conformist',
 ' Dear Frankie',
 'Muppets From Space',
 'The Stepford Wives',
 'Palm Springs',
 'happy as lazzaro',
 'Se7en',
 'Under the Skin',
 'A Better Life',
 'Restless ',
 'The Night of the Hunter',
 'April and the Extraordinary World',
 'The Avengers',
 'Suspiria',
 'The Chronicles of Riddick',
 'Catwoman',
 'The Swan Princess',
 'Instinct',
 'The Fountain',
 'Looney Tunes: Back in Action',
 'Nine',
 'Bulletproof Monk',
 'The Kid Who Would Be King',
 'Deepwater Horizon',
 'The League of Extraordinary Gentlemen',
 'Live by Night',
 'Virus',
 'Hard Rain',
 'Radio Flyer ',
 'The Postman',
 'Bright',
 'Town & Country',
 'The Perks of Being a Wallflower',
 'Mars Needs Moms']

In [27]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="w9"></div> 
    <div id='w9a'></div>
    <p class="highcharts-description">
    </p>
</figure>

In [91]:
%%js
Highcharts.chart('w9',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        //name of all the movies 
        categories:['Walt Before Mickey','North by Northwest','La Belle Noiseuse','Basquiat (film)',
                   'Badlands','Andrei Rublev','Waste Land','Life','My Life as a Zucchini',
                   'Year One','The Conformist',' Dear Frankie','Muppets From Space','The Stepford Wives',
                   'Palm Springs','Happy as Lazzaro','Se7en','Under the Skin','A Better Life',
                   'Restless','The Night of the Hunter','April and the Extraordinary World'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#DAA520','#D2691E','#FFD700'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[568000,1241979,1168044,5599766,558062,
             1300000,1500000,75000000,8000000,60000000,
             5181843,4893180,38141403,100000000,5000000,
             7271623,55716364,13300000,10000000,12918735,
             9618685,10400000]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[-91954,-319419,-390290,-490073,-490604,
             -1154509,-1208693,-1478413,-2127402,-2395277,
             -2413033,-2551559,-2664158,-3778029,-4234465,
             -5468927,-5929196,-7564037,-8136494,-8852544,
             -9465648,-9904121]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[476046,922560,777754,5109693,67458,
              145491,291307,73521587,5872598,57604723,
              2768810,2341621,35477245,96221971,765535,
              1802696,49787168,5735963,1863506,4066191,
              153037,495879,]
    }]
});

In [92]:
%%js
Highcharts.chart('w9a',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        //name of all the movies 
        categories:['The Avengers','Suspiria','The Chronicles of Riddick','Catwoman',
                    'The Swan Princess','Instinct','The Fountain','Looney Tunes: Back in Action',
                    'Nine','Bulletproof Monk','The Kid Who Would Be King','Deepwater Horizon',
                    'The League of Extraordinary Gentlemen','Live by Night','Virus','Hard Rain',
                    'Radio Flyer ','The Postman','Bright','Town & Country','The Perks of Being a Wallflower',
                    'Mars Needs Moms'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#DAA520','#D2691E','#FFD700'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[60000000,20000000,120000000,100000000,37516831,
              55000000,46324136,80000000,80000000,52000000,
              59000000,156000000,80000000,65000000,75000000,
              70000000,66110152,80000000,90000000,105000000,
              130000000,150000000]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[-11414584,-12057907,-12787249,-17854621,-20059610,
              -20894793,-24527515,-25459338,-26491142,-28989393,
              -30651554,-33396176,-36064237,-43225568,-44373310,
              -50129433,-57323212,-59158877,-90000000,-94635231,
              -96615873,-110450242]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[48585416,7942093,107212751,82145379,17457221,
             34105207,21796621,54540662,53508858,23010607,
             28348446,122603824,43935763,21774432,30626690,
             19870567,8786940,20841123,0,10364769,33384127,
             39549758]
    }]
});

# Blueprint: Top 20 Highest Profitable Movies and Top 20 Lowest Profitable Movies

This is the blueprint for creating the ninth and tenth visualization, Top 20 Highest Profitable Movies and the Top 20 Lowest Profitable Movies. Highcharts will be used to create these garphs.

__Blueprint:__
  - The graph used for these visualization is Highcharts 3D Cylinder Chart for the Top 20 Highest Profitable Movies and Highcharts Chart Rotation Chart Series for thr Top 20 lowest Profitable Movies, which is all found in the highcharts demos. The chart rotation chart series have an Alpha, Beta and Depth angle which can be adjusted to rotate the graph around.
  
    The first approach to this chart is by understanding the format of the code script. Like the previous graph this chart is constructed by two different types of code HTML and Javascript. The HTML section is very similar to the previous graph but the only difference is this HTML code;
         <script src="https://code.highcharts.com/highcharts-3d.js"></script>
         <script src="https://code.highcharts.com/modules/cylinder.js"></script>
    This allows the graphs to be 3D and it also allows it to be cylinder. To close of two script is also similar to the previous script but with a unique name to it self. 
       
       This is for the cylinder graph;
                      <figure class="highcharts-figure">
                      <div id="b1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
                
       This if for the 3D column graph;
                      <figure class="highcharts-figure">
                      <div id="c1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
   The second approach is scripting the javascript section. The javascript section is very simple, brfore that there needs to be some data extracted from the parent dataframe. These are the elements needed to be extracted for this visualazation. For the Top 20 Highest Profitable Movies the name and amount of profit made is needed, for the Top 20 Lowest Profitable Movies the name and amount of profit made in integer of all the movies is needed in that category.
   
 There is just one sub-section in each graph that are particular, the data sub-section in the series section. It is a body of sequenences of list that consist of the name and amount of profit made in integer.
   
   This is from the first graph;
            ['Avatar|1st Highest',2351345279],
            ['The Sound of Music|2nd Highest', 2303109231],
            ['Black Panther|3rd Highest',1148258224]
       
   This is from the second graph;
            [' Miami Vice|170th Highest', 28818556 ],
            [' Space Chimps|171th Highest', 28097693 ],
            [' The Tale of Despereaux|172th Highest', 26957280 ],

Using a for loop to put the top 20 highest profitable movie name and profit in html code which will be pasted in the cell below.

In [95]:
for i,x in enumerate(range(len(new21[:20]))):
    print('['+"'",new21[x],'|',i,'th','Highest'+"'"+',',neww[x][1],'],')

[' Snow White and the Seven Dwarfs | 0 th Highest', 7749287553 ],
[' The Jungle Book(1967)  | 1 th Highest', 2961011429 ],
[' The Sound of Music | 2 th Highest', 2321008636 ],
[' The Avengers | 3 th Highest', 1292935897 ],
[' Frozen | 4 th Highest', 1122469910 ],
[' Beauty and the Beast | 5 th Highest', 1099199706 ],
[' The Lord of the Rings: The Return of the King | 6 th Highest', 1047403341 ],
[' Despicable Me 3 | 7 th Highest', 959727750 ],
[' Harry Potter and the Deathly Hallows: Part I | 8 th Highest', 835431568 ],
[' Finding Dory | 9 th Highest', 821215193 ],
[' Mary Poppins | 10 th Highest', 820165063 ],
[' The Dark Knight | 11 th Highest', 816996207 ],
[' Harry Potter and the Chamber of Secrets | 12 th Highest', 779225135 ],
[' Harry Potter and the Chamber of Secrets | 13 th Highest', 779225135 ],
[' The Hobbit: An Unexpected Journey | 14 th Highest', 767003568 ],
[' The Hunger Games: Catching Fire | 15 th Highest', 734868047 ],
[' Harry Potter and the Prisoner of Azkaban | 16 th Highest', 666907323 ],
[' The Twilight Saga: Eclipse | 17 th Highest', 638102828 ],
[' Suicide Squad | 18 th Highest', 571059887 ],
[' Up | 19 th Highest', 556463377 ],

In [29]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="httos://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="b7"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [96]:
%%js
new Highcharts.chart('b7',{ //name of graph
    chart:{
        type:'cylinder', // makes graph cylinder
        // adjust the position of graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:16,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Highest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // mkaes the graph one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Highest Profit',
        color:'#ffda05',// color of cylinders in graph
           data:[
     // names and amount of profit made in integer of the ten most highest profitable movies
            [' Snow White and the Seven Dwarfs | 1st Highest', 7749287553 ],
            [' The Jungle Book(1967)  | 2nd Highest', 2961011429 ],
            [' The Sound of Music | 3rd Highest', 2321008636 ],
            [' The Avengers | 4th Highest', 1292935897 ],
            [' Frozen | 5th Highest', 1122469910 ],
            [' Beauty and the Beast | 6th Highest', 1099199706 ],
            [' The Lord of the Rings: The Return of the King | 7th Highest', 1047403341 ],
            [' Despicable Me 3 | 8th Highest', 959727750 ],
            [' Harry Potter and the Deathly Hallows: Part I | 9th Highest', 835431568 ],
            [' Finding Dory | 10th Highest', 821215193 ],
            [' Mary Poppins | 11th Highest', 820165063 ],
            [' The Dark Knight | 12th Highest', 816996207 ],
            [' Harry Potter and the Chamber of Secrets | 13th Highest', 779225135 ],
            [' Harry Potter and the Chamber of Secrets | 14th Highest', 779225135 ],
            [' The Hobbit: An Unexpected Journey | 15th Highest', 767003568 ],
            [' The Hunger Games: Catching Fire | 16th Highest', 734868047 ],
            [' Harry Potter and the Prisoner of Azkaban | 17th Highest', 666907323 ],
            [' The Twilight Saga: Eclipse | 18th Highest', 638102828 ],
            [' Suicide Squad | 19th Highest', 571059887 ],
            [' Up | 20th Highest', 556463377 ],
         ]
    }]
        
});

Using a for loop to put the top 20 lowest profitable movie name and profit in html code which will be pasted in the cell below

In [99]:
for i,x in enumerate(range(len(new21[:]))):
    print('['+"'",new21[x],'|',i,'th','Highest'+"'"+',',neww[x][1],'],')

[' Snow White and the Seven Dwarfs | 0 th Highest', 7749287553 ],
[' The Jungle Book(1967)  | 1 th Highest', 2961011429 ],
[' The Sound of Music | 2 th Highest', 2321008636 ],
[' The Avengers | 3 th Highest', 1292935897 ],
[' Frozen | 4 th Highest', 1122469910 ],
[' Beauty and the Beast | 5 th Highest', 1099199706 ],
[' The Lord of the Rings: The Return of the King | 6 th Highest', 1047403341 ],
[' Despicable Me 3 | 7 th Highest', 959727750 ],
[' Harry Potter and the Deathly Hallows: Part I | 8 th Highest', 835431568 ],
[' Finding Dory | 9 th Highest', 821215193 ],
[' Mary Poppins | 10 th Highest', 820165063 ],
[' The Dark Knight | 11 th Highest', 816996207 ],
[' Harry Potter and the Chamber of Secrets | 12 th Highest', 779225135 ],
[' Harry Potter and the Chamber of Secrets | 13 th Highest', 779225135 ],
[' The Hobbit: An Unexpected Journey | 14 th Highest', 767003568 ],
[' The Hunger Games: Catching Fire | 15 th Highest', 734868047 ],
[' Harry Potter and the Prisoner of Azkaban | 16 th Highest', 666907323 ],
[' The Twilight Saga: Eclipse | 17 th Highest', 638102828 ],
[' Suicide Squad | 18 th Highest', 571059887 ],
[' Up | 19 th Highest', 556463377 ],
[' Psycho | 20 th Highest', 513510733 ],
[' Back to the Future | 21 th Highest', 502314657 ],
[' Kung Fu Panda | 22 th Highest', 501910531 ],
[' Casino Royale | 23 th Highest', 492420283 ],
[' Fiddler on the Roof | 24 th Highest', 467944335 ],
[' Fight Club  | 25 th Highest', 435833717 ],
[' Terminator 2: Judgment Day | 26 th Highest', 415419827 ],
[' Terminator 2: Judgment Day | 27 th Highest', 415419827 ],
[' The Little Mermaid | 28 th Highest', 394060973 ],
[' How to Train Your Dragon: The Hidden World | 29 th Highest', 390258283 ],
[' Mr. and Mrs. Smith | 30 th Highest', 376124090 ],
[' Godzilla | 31 th Highest', 375000000 ],
[' Quantum of Solace | 32 th Highest', 361692078 ],
[' World War Z | 33 th Highest', 341514650 ],
[' The Last Starfighter | 34 th Highest', 341311860 ],
[' Clue | 35 th Highest', 339240892 ],
[' The Mummy | 36 th Highest', 336385488 ],
[' A Bug's Life | 37 th Highest', 318095319 ],
[' Karate Kid | 38 th Highest', 314728703 ],
[' Kingsman: The Secret Service | 39 th Highest', 310561724 ],
[' Crouching Tiger, Hidden Dragon  | 40 th Highest', 304141192 ],
[' Jason Bourne | 41 th Highest', 296168316 ],
[' Murder on the Orient Express | 42 th Highest', 290922730 ],
[' Apollo 13 | 43 th Highest', 281592771 ],
[' Jurassic Park III | 44 th Highest', 272900000 ],
[' Jurassic Park III | 45 th Highest', 272900000 ],
[' Wanted | 46 th Highest', 267416460 ],
[' Warcraft | 47 th Highest', 265522281 ],
[' Minority Report | 48 th Highest', 256824714 ],
[' Ocean's Twelve | 49 th Highest', 252989076 ],
[' Angry Men | 50 th Highest', 247796314 ],
[' Mission: Impossible III | 51 th Highest', 247501348 ],
[' National Treasure | 52 th Highest', 231323410 ],
[' The Impossible | 53 th Highest', 216360490 ],
[' The Mummy | 54 th Highest', 214953905 ],
[' A Good Day to Die Hard | 55 th Highest', 212249198 ],
[' Hidden Figures | 56 th Highest', 210956898 ],
[' Life Is Beautiful | 57 th Highest', 208847384 ],
[' Stuart Little | 58 th Highest', 193815224 ],
[' Passengers | 59 th Highest', 192239672 ],
[' Solaris | 60 th Highest', 184890644 ],
[' Ferdinand | 61 th Highest', 178847930 ],
[' The Tourist | 62 th Highest', 178731369 ],
[' Charlie's Angels | 63 th Highest', 169736090 ],
[' American Gangster | 64 th Highest', 167985456 ],
[' Grown Ups 2 | 65 th Highest', 167023808 ],
[' The Bourne Legacy | 66 th Highest', 155355920 ],
[' Eragon | 67 th Highest', 149488115 ],
[' Constantine | 68 th Highest', 146594911 ],
[' The Good Dinosaur | 69 th Highest', 146271037 ],
[' Lethal Weapon 4 | 70 th Highest', 145400000 ],
[' Con Air | 71 th Highest', 144117573 ],
[' G-Force | 72 th Highest', 142817841 ],
[' Bedtime Stories | 73 th Highest', 141468935 ],
[' Midnight in Paris | 74 th Highest', 136959590 ],
[' Smallfoot | 75 th Highest', 133691277 ],
[' Vanilla Sky | 76 th Highest', 132726605 ],
[' Finding Neverland | 77 th Highest', 129531208 ],
[' Red Dragon | 78 th Highest', 128455420 ],
[' Hairspray | 79 th Highest', 128035572 ],
[' Mona Lisa Smile drawing | 80 th Highest', 123206493 ],
[' Gulliver's Travels | 81 th Highest', 120017848 ],
[' Robin Hood | 82 th Highest', 112459006 ],
[' The Chorus | 83 th Highest', 108446695 ],
[' Alice Through the Looking Glass | 84 th Highest', 106928112 ],
[' Groundhog Day | 85 th Highest', 103358016 ],
[' Daredevil | 86 th Highest', 102782518 ],
[' The Cider House Rules | 87 th Highest', 102576682 ],
['  | 88 th Highest', 101265204 ],
[' Alien: Resurrection | 89 th Highest', 100700000 ],
[' Flubber | 90 th Highest', 97993801 ],
[' The Lady Vanishes | 91 th Highest', 92551549 ],
[' Mirror Mirror | 92 th Highest', 88613482 ],
[' The Saint | 93 th Highest', 79400000 ],
[' Contact | 94 th Highest', 75900000 ],
[' The Predator | 95 th Highest', 71487563 ],
[' The Kite Runner | 96 th Highest', 71005663 ],
[' Departures | 97 th Highest', 67879389 ],
[' The A-Team | 98 th Highest', 67241171 ],
[' The A-Team | 99 th Highest', 67241171 ],
[' Conspiracy Theory | 100 th Highest', 62783718 ],
[' Invictus | 101 th Highest', 62233971 ],
[' Charlotte's Web | 102 th Highest', 61485708 ],
[' Moonlight | 103 th Highest', 61300000 ],
[' Fear of Rain | 104 th Highest', 60158135 ],
[' Dark Star | 105 th Highest', 59163710 ],
[' The Great Muppet Caper | 106 th Highest', 51932573 ],
[' Body of Lies | 107 th Highest', 51056530 ],
[' The Devil's Own | 108 th Highest', 50900000 ],
[' 3 Ninjas | 109 th Highest', 50055398 ],
[' Rear Window | 110 th Highest', 49501119 ],
[' Watchmen | 111 th Highest', 48976250 ],
[' The Usual Suspects | 112 th Highest', 47549422 ],
[' Wild Wild West | 113 th Highest', 46229335 ],
[' Singin' in the Rain | 114 th Highest', 46144051 ],
[' Surf's Up | 115 th Highest', 45395745 ],
[' Beowulf | 116 th Highest', 45080579 ],
[' The Sea Inside | 117 th Highest', 44612298 ],
[' Frida | 118 th Highest', 44300000 ],
[' Walking with Dinosaurs | 119 th Highest', 43368842 ],
[' Bedazzled | 120 th Highest', 42376224 ],
[' Loving Vincent | 121 th Highest', 36687665 ],
[' Lagaan | 122 th Highest', 35579349 ],
[' Walking Tall | 123 th Highest', 35312586 ],
[' Colombiana | 124 th Highest', 32295262 ],
[' Because I Said So | 125 th Highest', 30538833 ],
[' Cloud Atlas | 126 th Highest', 28673154 ],
['  The New World | 127 th Highest', 27839725 ],
[' The Tree of Life | 128 th Highest', 26409247 ],
[' The Tree of Life | 129 th Highest', 26409247 ],
[' Tell No One | 130 th Highest', 25402267 ],
[' Priest | 131 th Highest', 24154026 ],
[' Space Buddies | 132 th Highest', 23193471 ],
[' A Separation | 133 th Highest', 22426076 ],
[' Reign of Fire | 134 th Highest', 22150183 ],
[' Mars Attacks! | 135 th Highest', 21371017 ],
[' Starship Troopers | 136 th Highest', 21100000 ],
[' Killers | 137 th Highest', 20572749 ],
[' The Perks of Being a Wallflower | 138 th Highest', 20384127 ],
[' Memento | 139 th Highest', 20071250 ],
[' AstÃ©rix aux Jeux Olympiques | 140 th Highest', 19499811 ],
[' Girl with a Pearl Earring | 141 th Highest', 19466789 ],
[' Ender's Game | 142 th Highest', 17983283 ],
[' The Manchurian Candidate | 143 th Highest', 16148711 ],
[' Ice Station Zebra (1968) | 144 th Highest', 15666190 ],
[' The Diving Bell and the Butterfly | 145 th Highest', 11299863 ],
[' Timeline | 146 th Highest', 11223890 ],
[' Mr. Turner | 147 th Highest', 10558482 ],
[' The Little Prince | 148 th Highest', 5922163 ],
['  | 149 th Highest', 4957475 ],
[' Rivers and Tides | 150 th Highest', 4144455 ],
[' Days of Heaven | 151 th Highest', 4050401 ],
[' The Box | 152 th Highest', 3333531 ],
[' Jupiter Ascending | 153 th Highest', 2982519 ],
[' Days of Heaven | 154 th Highest', 2772013 ],
[' The Best Offer  | 155 th Highest', 2596350 ],
[' The Imposter | 156 th Highest', 2232717 ],
[' Another Earth | 157 th Highest', 2185224 ],
[' Rear Window | 158 th Highest', 1314203 ],
[' Primer | 159 th Highest', 1180013 ],
[' Boy Erased | 160 th Highest', 862650 ],
[' Bicycle Thieves | 161 th Highest', 295978 ],
[' Where the Wild Things Are | 162 th Highest', 140096 ],
[' Reindeer Games | 163 th Highest', 108832 ],
[' Tokyo Story | 164 th Highest', 24654 ],
[' WALL• E | 165 th Highest', 6265 ],
[' Walt Before Mickey | 166 th Highest', -91954 ],
[' North by Northwest | 167 th Highest', -319419 ],
[' La Belle Noiseuse | 168 th Highest', -390290 ],
[' Basquiat (film) | 169 th Highest', -490073 ],
['  Badlands | 170 th Highest', -490604 ],
[' Andrei Rublev | 171 th Highest', -1154509 ],
[' Waste Land | 172 th Highest', -1208693 ],
[' Life | 173 th Highest', -1478413 ],
[' My Life as a Zucchini | 174 th Highest', -2127402 ],
[' Year One | 175 th Highest', -2395277 ],
[' The Conformist | 176 th Highest', -2413033 ],
['  Dear Frankie | 177 th Highest', -2551559 ],
[' Muppets From Space | 178 th Highest', -2664158 ],
[' The Stepford Wives | 179 th Highest', -3778029 ],
[' Palm Springs | 180 th Highest', -4234465 ],
[' happy as lazzaro | 181 th Highest', -5468927 ],
[' Se7en | 182 th Highest', -5929196 ],
[' Under the Skin | 183 th Highest', -7564037 ],
[' A Better Life | 184 th Highest', -8136494 ],
[' Restless  | 185 th Highest', -8852544 ],
[' The Night of the Hunter | 186 th Highest', -9465648 ],
[' April and the Extraordinary World | 187 th Highest', -9904121 ],
[' The Avengers | 188 th Highest', -11414584 ],
[' Suspiria | 189 th Highest', -12057907 ],
[' The Chronicles of Riddick | 190 th Highest', -12787249 ],
[' Catwoman | 191 th Highest', -17854621 ],
[' The Swan Princess | 192 th Highest', -20059610 ],
[' Instinct | 193 th Highest', -20894793 ],
[' The Fountain | 194 th Highest', -24527515 ],
[' Looney Tunes: Back in Action | 195 th Highest', -25459338 ],
[' Nine | 196 th Highest', -26491142 ],
[' Bulletproof Monk | 197 th Highest', -28989393 ],
[' The Kid Who Would Be King | 198 th Highest', -30651554 ],
[' Deepwater Horizon | 199 th Highest', -33396176 ],
[' The League of Extraordinary Gentlemen | 200 th Highest', -36064237 ],
[' Live by Night | 201 th Highest', -43225568 ],
[' Virus | 202 th Highest', -44373310 ],
[' Hard Rain | 203 th Highest', -50129433 ],
[' Radio Flyer  | 204 th Highest', -57323212 ],
[' The Postman | 205 th Highest', -59158877 ],
[' Bright | 206 th Highest', -90000000 ],
[' Town & Country | 207 th Highest', -94635231 ],
[' The Perks of Being a Wallflower | 208 th Highest', -96615873 ],
[' Mars Needs Moms | 209 th Highest', -110450242 ],

In [31]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="c7"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [100]:
%%js
Highcharts.chart('c7',{ // name of graph
    chart:{
        type:'column', // makes the graph column
       // adjusting the graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:25,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Lowest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // allows the graph to be one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Lowest Profits',
        color :'#bda000', // the color of the graph
           data:[
// the name and amount of profit made in integer of the least most profitable movies
            [' Timeline | 146th Highest', 11223890 ],
            [' Mr. Turner | 147th Highest', 10558482 ],
            [' The Little Prince | 148th Highest', 5922163 ],
            ['  | 149th Highest', 4957475 ],
            [' Rivers and Tides | 150th Highest', 4144455 ],
            [' Days of Heaven | 151th Highest', 4050401 ],
            [' The Box | 152th Highest', 3333531 ],
            [' Jupiter Ascending | 153th Highest', 2982519 ],
            [' Days of Heaven | 154th Highest', 2772013 ],
            [' The Best Offer  | 155th Highest', 2596350 ],
            [' The Imposter | 156th Highest', 2232717 ],
            [' Another Earth | 157th Highest', 2185224 ],
            [' Rear Window | 158th Highest', 1314203 ],
            [' Primer | 159th Highest', 1180013 ],
            [' Boy Erased | 160th Highest', 862650 ],
            [' Bicycle Thieves | 161th Highest', 295978 ],
            [' Where the Wild Things Are | 162th Highest', 140096 ],
            [' Reindeer Games | 163th Highest', 108832 ],
            [' Tokyo Story | 164th Highest', 24654 ],
            [' WALL• E | 165th Highest', 6265 ],
         ]
    }]
        
});

# Blueprint: What Movie is the most Successful.

Just because a movie has made the most profit dosen't mean it is more profitable than a movie that made less profit and or revenue. These were the five main factors that were used to better understand what movie was the most successful. The cost, the revenue, the profit, the gross profit margin percentage which is how much of the revenue is each movie walking away in percentageand the profit percenatge by cost which is comparing the profit with the cost in percentage. 
 
This is the blueprint for creating the elevnth, twelith, thirthith and fourthith visualization. Highcharts will be used to create these graphs.  

__Blueprint:__
   - The factors are split into half when it comes to what type of graph that will be used to analyze the data. The profit, revenue and cost varaiables will be analyzed using highcharts Combination Chart. This chart allows different combinations of senories to be combined in a single chart. This chart is a set of column series overlaid by a line and a pie chart. The line in Highchart was designed to illustrate the column averages while the pie is illustrating the column totals. However in this project the pie sereis will not be used and there will be two column series overlaid by a line series. The two columns will be revenue and profit, the line series will be the cost of all the movies in the blueprint. Like every other graph that used Highchart visualization, they all have two different types of code, HTML and javascript. The HTML section is very similar to all the previous graphs expect two main factors, the HTML code that allows the combination graph to be displayed is;
          <script src="https://code.highcharts.com/modules/series-label.js"></script>
          <script type="text/javascript" src="js/script.js"></script>
The other factors are the two different divs id for the combination chart;
          <div id="x1" display; inline-block></div>
          <div id="no1" display; inline-block></div>
 These are the names of the two combination chart that analyze ten movies each of the Top 20 Most     Profitable Movies.The javascript section for these graphs consist of four main subsection. The categories, the two types in the series section that are columns and the type in the series section that is spline. The categories subsection is a list of all the names of the movies that will be analyzed. The two types in the in the series subsection that are columns are the profit and revenue of all the movies and the third type in the spline series subsection is the cost of all the movies. 
     
     
                series:[{
                   type:'column',
                   color:"#111E6C",
                   name:'Profit',
                   data:                                  
                   [2351345279,2303109231,1148258224, 1135772799,1015392272,984846267,912044677,894039076,
          890069413,878000000]
      },{
          type:'column'
          color:Highcharts.getOptions().colors[1],
          name:'Revenue',
          data:[2776345279,2366000000,1348258224,
          1305772799,1215392272,1234846267,1027044677,1104039076,1140069413,1078000000]
     },{
          type:'spline',
          color:'gold',
          name:'Cost',
          data:[425000000,62890769,200000000,170000000,200000000,250000000,115000000,210000000,
                    250000000,200000000],


   The other factors are the two different divs id for the column chart;
            
            <div id="n1" display; inline-block></div>
            <div id="xo1" display; inline-block></div>

   The Gross Profit Margin Percentage and the Profit Percentage by Cost will all be analyzed using        highcharts combination chart but with only column. The two column will be The Percentage of Gross      Profit Margin and Profit by Cost of each movie.
   
   The javascript section for the columns chart consist of the category subsection which is the names      of all the movies. 
      
      categories:['Zootopia| 11th Highest',
      'Finding Nemo| 12th Highest',
      'The Jungle Book| 13th Highest',
      'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
      'Ice Age: Dawn of the Dinosaurs| 15th Highest',
      'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
      'The Hobbit: The Battle of the Five Armies| 17th Highest',
      'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
      'Inside Out| 19th Highest',
      'Deadpool 2| 20th Highest']

   It also consist of the series subsection that has two factors, the type column which is where the      gross profit margin percentage and profit by cost is scripted.
      
      series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[85.0, 97.0, 85.0, 87.0, 84.0, 80.0, 89.0, 81.0, 78.0, 81.0]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[553.0, 3662.0, 574.0, 668.0, 508.0, 394.0, 793.0, 426.0, 356.0, 439.0]
       }]

In [101]:
#getting the profit of the movie
for i in neww[:20]:
    print(all_ArtHouseandIntern_info1.Profit[i[0]])

7749287553
2961011429
2321008636
1292935897
1122469910
1099199706
1047403341
959727750
835431568
821215193
820165063
816996207
779225135
779225135
767003568
734868047
666907323
638102828
571059887
556463377

In [102]:
#getting the revenue of the movie
for i in neww[:20]:
    print(all_ArtHouseandIntern_info1.Total_gross[i[0]])

7777009429
2992680000
2389466546
1517935897
1272469910
1259199706
1141403341
1034727750
960431568
1021215193
862312959
1001996207
879225135
879225135
1017003568
864868047
796907323
706102828
746059887
731463377

In [103]:
#getting the cost of the movie
for i in neww[:20]:
    print(all_ArtHouseandIntern_info1.Buget[i[0]])

27721876
31668571
68457910
225000000
150000000
160000000
94000000
75000000
125000000
200000000
42147896
185000000
100000000
100000000
250000000
130000000
130000000
68000000
175000000
175000000

In [104]:
#getting profit percent by cost of the top 20 highest most profitable movie
new5 = []
for i in neww:
    new5.append(round(all_ArtHouseandIntern_info1.Profit[i[0]]/all_ArtHouseandIntern_info1.Buget[i[0]]
         *100,0))
new5[:20]

[27954.0,
 9350.0,
 3390.0,
 575.0,
 748.0,
 687.0,
 1114.0,
 1280.0,
 668.0,
 411.0,
 1946.0,
 442.0,
 779.0,
 779.0,
 307.0,
 565.0,
 513.0,
 938.0,
 326.0,
 318.0]

In [105]:
#getting gross profit margin percent of the top 20 highest most profitable movie
new6 = []
for i in neww:
    new6.append(round(all_ArtHouseandIntern_info1.Profit[i[0]]/all_ArtHouseandIntern_info1.Total_gross[i[0]]
         *100,0))
new6[:20]

<ipython-input-105-2f7a5ebc6189>:4: RuntimeWarning: divide by zero encountered in longlong_scalars
  new6.append(round(all_ArtHouseandIntern_info1.Profit[i[0]]/all_ArtHouseandIntern_info1.Total_gross[i[0]]

[100.0,
 99.0,
 97.0,
 85.0,
 88.0,
 87.0,
 92.0,
 93.0,
 87.0,
 80.0,
 95.0,
 82.0,
 89.0,
 89.0,
 75.0,
 85.0,
 84.0,
 90.0,
 77.0,
 76.0]

Using a for loop to get the names of the highest most profitable and putting it into html code

In [107]:
for i,x in enumerate(new21[:20]):
    print("'"+new21[i]+'|',i,'th','Highest'+"',")

'Snow White and the Seven Dwarfs| 0 th Highest',
'The Jungle Book(1967) | 1 th Highest',
'The Sound of Music| 2 th Highest',
'The Avengers| 3 th Highest',
'Frozen| 4 th Highest',
'Beauty and the Beast| 5 th Highest',
'The Lord of the Rings: The Return of the King| 6 th Highest',
'Despicable Me 3| 7 th Highest',
'Harry Potter and the Deathly Hallows: Part I| 8 th Highest',
'Finding Dory| 9 th Highest',
'Mary Poppins| 10 th Highest',
'The Dark Knight| 11 th Highest',
'Harry Potter and the Chamber of Secrets| 12 th Highest',
'Harry Potter and the Chamber of Secrets| 13 th Highest',
'The Hobbit: An Unexpected Journey| 14 th Highest',
'The Hunger Games: Catching Fire| 15 th Highest',
'Harry Potter and the Prisoner of Azkaban| 16 th Highest',
'The Twilight Saga: Eclipse| 17 th Highest',
'Suicide Squad| 18 th Highest',
'Up| 19 th Highest',

In [34]:
%%HTML
<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="x7" display; inline-block></div>
    <div id="n7" display; inline-block></div>
    <div id="no7" display; inline-block></div>
    <div id="xo7" display; inline-block></div>
    <p class="highcharts-description">
    </p>
</figure>

In [108]:
%%js
Highcharts.chart('x7',{ // name of graph
    title:{
        text:"What Movie Is The Most Successful?"
    },
    xAxis:{
        // name of movies
        categories:['Snow White and the Seven Dwarfs| 1st Highest',
                    'The Jungle Book(1967) | 2nd Highest',
                    'The Sound of Music| 3rd Highest',
                    'The Avengers| 4th Highest',
                    'Frozen| 5th Highest',
                    'Beauty and the Beast| 6th Highest',
                    'The Lord of the Rings: The Return of the King| 7th Highest',
                    'Despicable Me 3| 8th Highest',
                    'Harry Potter and the Deathly Hallows: Part I| 9th Highest',
                    'Finding Dory| 10th Highest'],
        crosshair:{
            // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column', // makes graph to be colunm 
        color:"#da9100",// color of colunm
        name:'Profit', // name of colunm
        // profit of each movie in integer 
        data:[7749287553,2961011429,2321008636,1292935897,1122469910,
             1099199706,1047403341,959727750,835431568,821215193]
    },{
        type:'column',// makes graph to be colunm
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[7777009429,2992680000,2389466546,1517935897,1272469910,
            1259199706,1141403341,1034727750,960431568,1021215193]
    },{
        type:'spline',// makes graph spline
        color:'#ffeb7a',// color of spline
        name:'Cost', // name of spline
        // cost of each movie in integer
        data:[27721876,31668571,68457910,225000000,150000000,
             160000000,94000000,75000000,125000000,200000000],
        marker:{
            lineWidth: 2,
            lineColor: '#ffeb7a',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [109]:
%%js
Highcharts.chart('n7',{ //name of graph
        title:{
            text:""
        },
        xAxis:{
        // name of movies 
           categories:['Snow White and the Seven Dwarfs| 1st Highest',
                    'The Jungle Book(1967) | 2nd Highest',
                    'The Sound of Music| 3rd Highest',
                    'The Avengers| 4th Highest',
                    'Frozen| 5th Highest',
                    'Beauty and the Beast| 6th Highest',
                    'The Lord of the Rings: The Return of the King| 7th Highest',
                    'Despicable Me 3| 8th Highest',
                    'Harry Potter and the Deathly Hallows: Part I| 9th Highest',
                    'Finding Dory| 10th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#ffcc33',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
           // Gross Profit Margin Percentage of each movie in integer
           data:[100.0,99.0,97.0,85.0,88.0,87.0,92.0,93.0,87.0,80.0]
       },{
           type:'column',// makes graph to be colunm
           color:'#e1a957',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[27954.0,9350.0,3390.0,575.0,748.0,687.0,1114.0,1280.0,668.0,411.0]
       }]  
    
   });

In [111]:
%%js
Highcharts.chart('no7',{ //name of graph
    title:{
        text:""
    },
    xAxis:{
        // name of movies 
        categories:[' Mary Poppins | 11th Highest', 820165063 ],
            [' The Dark Knight | 12th Highest', 816996207 ],
            [' Harry Potter and the Chamber of Secrets | 13th Highest', 779225135 ],
            [' Harry Potter and the Chamber of Secrets | 14th Highest', 779225135 ],
            [' The Hobbit: An Unexpected Journey | 15th Highest', 767003568 ],
            [' The Hunger Games: Catching Fire | 16th Highest', 734868047 ],
            [' Harry Potter and the Prisoner of Azkaban | 17th Highest', 666907323 ],
            [' The Twilight Saga: Eclipse | 18th Highest', 638102828 ],
            [' Suicide Squad | 19th Highest', 571059887 ],
            [' Up | 20th Highest', 556463377 ],
        crosshair:{
             // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',// makes graph  colunm 
        color:'#da9100',// color of colunm
        name:'Profit',// name of column
        // profit of each movie in integer 
        data:[820165063,816996207,779225135,779225135,767003568,
              734868047,666907323,638102828,571059887,556463377]
    },{
        type:'column',// makes graph  colunm 
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[862312959,1001996207,879225135,879225135,1017003568,
            864868047,796907323,706102828,746059887,731463377]
    },{
        type:'spline',// makes graph spline
        color:'#ffeb7a',// color of spline
        name:'Cost',// name of spline
        // cost of each movie in integer
        data:[42147896,185000000,100000000,100000000,250000000,
             130000000,130000000,68000000,175000000,175000000],
        marker:{
            lineWidth: 2,
            lineColor: '#ffeb7a',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [110]:
%%js
Highcharts.chart('xo7',{//name of graph
        title:{
            text:""
        },
        xAxis:{
           // name of movies 
           categories:[' Mary Poppins | 11th Highest', 820165063 ],
            [' The Dark Knight | 12th Highest', 816996207 ],
            [' Harry Potter and the Chamber of Secrets | 13th Highest', 779225135 ],
            [' Harry Potter and the Chamber of Secrets | 14th Highest', 779225135 ],
            [' The Hobbit: An Unexpected Journey | 15th Highest', 767003568 ],
            [' The Hunger Games: Catching Fire | 16th Highest', 734868047 ],
            [' Harry Potter and the Prisoner of Azkaban | 17th Highest', 666907323 ],
            [' The Twilight Saga: Eclipse | 18th Highest', 638102828 ],
            [' Suicide Squad | 19th Highest', 571059887 ],
            [' Up | 20th Highest', 556463377 ],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
            // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#ffcc33',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
          // Gross Profit Margin Percentage of each movie in integer
           data:[95.0,82.0,89.0,89.0,75.0,85.0,84.0,90.0,77.0,76.0]
       },{
           type:'column',// makes graph to be colunm 
           color:'#e1a95f',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[1946.0,442.0,779.0,779.0,307.0,565.0,513.0,938.0,326.0,318.0]
       }]  
    
   });

# Blueprint: Number of Tickets Sold.

This analysis objective is to axknowledge what system rating that best suit this genre, this allows the ideology of what kind of audience is drawn to this genre, to specify the audience and make them the target focus. This is the blueprint for creating the last visualization of this project, Highcharts will be used to create this graph.

__Blueprint:__
   - The graph used for this visualization is a Highchart Donut chart, it is basically a hallow pie chart which is commonly referred to as a donut charts. This pie charts also ahs an inner chart resulting in a hierachical type of visualization.
   - The first approach th this chart is the HTML section whcih is very simple, it has the div id which is where the graph is named and the style and height should be chosen.
               <div id='hraph2' style="height:700px"></div>
   - The second approach is the javascript code, it is divided into two sections the inner pie and the outer pie. The inner pie shows how much each sytem ratings occupies the most total tickets sold in percentage comparied to the total tickest sold in the whole entire parent dataframe '_all_ArtHouseandIntern_info1_'. The outer pie shows the individule movies in the category the amount of tickets they sold.
        - <u>__Javascript Section__</u>:
         
             -<u>_First Section_</u>: The first section is a list called data it has consist of the name of the system ratings and the percenatge of tickets sold compared to the total of tickets sold. The color and the sliced adjustments and it also has the adjustments of the size of the ring pie.
                      data:[{
                  name:'System Rating: R',
                  y:28.0,
                  sliced:true,
                  color: '#4682B4',}
            
            -<u>_Second Section_</u>: The second section is a list also called data it requires the name of all the movies, the amount of tickest they sold , the option to slice that section and the color of the slice .       
                     data:[{ 
               name: ' Avatar ' ,
               y: 213565021 ,
               sliced:true,
               selected: true,
               color:"#4682B4",}

In [112]:
# getting the number of tickets sold in the r-rated category
var = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'R':
        var.append(no_tickets[i])
len(var)

42

In [113]:
# getting the name of the r-rated movies 
var1 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'R':
        var1.append(all_ArtHouseandIntern_info1['Name'][i])
len(var1)

42

In [114]:
# getting the profit of thr r-rated movies
var2 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'R':
        var2.append(all_ArtHouseandIntern_info1['Profit'][i])
len(var2)

42

Using a for loop to put the name and the number of tickets sold in the R-rated genre in html code which will be pasted in the cell below.

In [134]:
for i,x in enumerate(range(len(var))):
    print('         },{ \n           name:',"'",var1[i],"'",','+'\n           y:',var[i],','+'\n           sliced:true,'+'\n           color:"#CD853F",')

         },{
           name: ' Quantum of Solace ' ,
           y: 45514775 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Dark Knight ' ,
           y: 77076631 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Suicide Squad ' ,
           y: 57389222 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Wild Wild West ' ,
           y: 17017641 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Frozen ' ,
           y: 97882301 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' G-Force ' ,
           y: 22524449 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Beowulf ' ,
           y: 15006198 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Mars Needs Moms ' ,
           y: 3042289 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Lethal Weapon 4 ' ,
           y: 21953846 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Kung Fu Panda ' ,
           y: 48608502 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' How to Train Your Dragon: The Hidden World ' ,
           y: 39942945 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Jason Bourne ' ,
           y: 32012947 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' AstÃ©rix aux Jeux Olympiques ' ,
           y: 10230755 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Ferdinand ' ,
           y: 22295995 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Mr. and Mrs. Smith ' ,
           y: 37394161 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Ocean's Twelve ' ,
           y: 27922237 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' National Treasure ' ,
           y: 25486416 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Starship Troopers ' ,
           y: 9315385 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Lord of the Rings: The Return of the King ' ,
           y: 87800257 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Saint ' ,
           y: 13030769 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Bright ' ,
           y: 0 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Mummy ' ,
           y: 31534916 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Avengers ' ,
           y: 116764300 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Smallfoot ' ,
           y: 16437791 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Conspiracy Theory ' ,
           y: 10983363 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Mars Attacks! ' ,
           y: 7797771 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Nine ' ,
           y: 4116066 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Postman ' ,
           y: 1603163 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Red Dragon ' ,
           y: 15881186 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Wanted ' ,
           y: 26339728 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Hairspray ' ,
           y: 15618121 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Constantine ' ,
           y: 17045762 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Life ' ,
           y: 5655507 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Virus ' ,
           y: 2355899 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Vanilla Sky ' ,
           y: 15594354 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Hard Rain ' ,
           y: 1528505 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' The Twilight Saga: Eclipse ' ,
           y: 54315602 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Body of Lies ' ,
           y: 9119733 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Live by Night ' ,
           y: 1674956 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Alien: Resurrection ' ,
           y: 12361538 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Year One ' ,
           y: 4431133 ,
           sliced:true,
           color:"#CD853F",
         },{
           name: ' Reign of Fire ' ,
           y: 6319245 ,
           sliced:true,
           color:"#CD853F",

In [115]:
# getting the number of tickets sold in the NR-rated category
var3 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'NR':
        var3.append(no_tickets[i])
len(var3)

42

In [116]:
# getting the name of the NR-rated movies 
var4 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'NR':
        var4.append(all_ArtHouseandIntern_info1['Name'][i])
len(var4)

42

In [117]:
# getting the profit of thr NR-rated movies
var5 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'NR':
        var5.append(all_ArtHouseandIntern_info1['Profit'][i])
len(var5)

42

Using a for loop to put the name and the number of tickets sold in the NR-rated genre in html code which will be pasted in the cell below.

In [139]:
for i,x in enumerate(range(len(var4))):
    print('         },{ \n           name:',"'",var7[i],"'",','+'\n           y:',var6[i],',','\n           sliced:true,'+'\n           color:"gold",')

         },{
           name: ' Finding Dory ' ,
           y: 78555015 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Chronicles of Riddick ' ,
           y: 8247135 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Eragon ' ,
           y: 19191393 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Devil's Own ' ,
           y: 10838462 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Mummy ' ,
           y: 32029653 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Killers ' ,
           y: 7351750 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Priest ' ,
           y: 6473387 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Avengers ' ,
           y: 3737340 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Kid Who Would Be King ' ,
           y: 2180650 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Instinct ' ,
           y: 2623477 ,
           sliced:true,
           color:"gold",
         },{
           name: ' A Bug's Life ' ,
           y: 27930409 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Colombiana ' ,
           y: 5561174 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Because I Said So ' ,
           y: 5349141 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Lagaan ' ,
           y: 3132136 ,
           sliced:true,
           color:"gold",
         },{
           name: ' April and the Extraordinary World ' ,
           y: 38145 ,
           sliced:true,
           color:"gold",
         },{
           name: '  Badlands ' ,
           y: 5189 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Where the Wild Things Are ' ,
           y: 7703084 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Andrei Rublev ' ,
           y: 11192 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Tokyo Story ' ,
           y: 4589 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Bicycle Thieves ' ,
           y: 32998 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Days of Heaven ' ,
           y: 1181177 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Suspiria ' ,
           y: 610930 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Under the Skin ' ,
           y: 441228 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Midnight in Paris ' ,
           y: 11843045 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Frida ' ,
           y: 4330769 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Girl with a Pearl Earring ' ,
           y: 2420522 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Mr. Turner ' ,
           y: 1707692 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Tree of Life ' ,
           y: 4493019 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Waste Land ' ,
           y: 22408 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Rivers and Tides ' ,
           y: 387895 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Moonlight ' ,
           y: 5023077 ,
           sliced:true,
           color:"gold",
         },{
           name: ' 3 Ninjas ' ,
           y: 4213658 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Karate Kid ' ,
           y: 25792247 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Walt Before Mickey ' ,
           y: 36619 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Loving Vincent ' ,
           y: 3245205 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Best Offer  ' ,
           y: 1584335 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Basquiat (film) ' ,
           y: 393053 ,
           sliced:true,
           color:"gold",
         },{
           name: ' La Belle Noiseuse ' ,
           y: 59827 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Mona Lisa Smile drawing ' ,
           y: 14389803 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Days of Heaven ' ,
           y: 1725908 ,
           sliced:true,
           color:"gold",
         },{
           name: ' Solaris ' ,
           y: 14626499 ,
           sliced:true,
           color:"gold",
         },{
           name: ' The Conformist ' ,
           y: 212985 ,
           sliced:true,
           color:"gold",

In [118]:
# getting the number of tickets sold in the pg-rated category
var6 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG':
        var6.append(no_tickets[i])
len(var6)

42

In [119]:
# getting the name of the pg-rated movies 
var7 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG':
        var7.append(all_ArtHouseandIntern_info1['Name'][i])
len(var7)

42

In [120]:
# getting the profit of thr pg-rated movies
var8 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG':
        var8.append(all_ArtHouseandIntern_info1['Profit'][i])
len(var8)

42

Using a for loop to put the name and the number of tickets sold in the PG-rated genre in html code which will be pasted in the cell below.

In [140]:
for i,x in enumerate(range(len(var7))):
    print('         },{ \n           name:',"'",var7[i],"'",','+'\n           y:',var6[i],',','\n           sliced:true,'+'\n           color:"#8B4513",')

         },{
           name: ' Finding Dory ' ,
           y: 78555015 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Chronicles of Riddick ' ,
           y: 8247135 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Eragon ' ,
           y: 19191393 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Devil's Own ' ,
           y: 10838462 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Mummy ' ,
           y: 32029653 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Killers ' ,
           y: 7351750 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Priest ' ,
           y: 6473387 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Avengers ' ,
           y: 3737340 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Kid Who Would Be King ' ,
           y: 2180650 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Instinct ' ,
           y: 2623477 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' A Bug's Life ' ,
           y: 27930409 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Colombiana ' ,
           y: 5561174 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Because I Said So ' ,
           y: 5349141 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Lagaan ' ,
           y: 3132136 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' April and the Extraordinary World ' ,
           y: 38145 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: '  Badlands ' ,
           y: 5189 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Where the Wild Things Are ' ,
           y: 7703084 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Andrei Rublev ' ,
           y: 11192 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Tokyo Story ' ,
           y: 4589 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Bicycle Thieves ' ,
           y: 32998 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Days of Heaven ' ,
           y: 1181177 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Suspiria ' ,
           y: 610930 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Under the Skin ' ,
           y: 441228 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Midnight in Paris ' ,
           y: 11843045 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Frida ' ,
           y: 4330769 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Girl with a Pearl Earring ' ,
           y: 2420522 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Mr. Turner ' ,
           y: 1707692 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Tree of Life ' ,
           y: 4493019 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Waste Land ' ,
           y: 22408 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Rivers and Tides ' ,
           y: 387895 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Moonlight ' ,
           y: 5023077 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' 3 Ninjas ' ,
           y: 4213658 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Karate Kid ' ,
           y: 25792247 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Walt Before Mickey ' ,
           y: 36619 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Loving Vincent ' ,
           y: 3245205 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Best Offer  ' ,
           y: 1584335 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Basquiat (film) ' ,
           y: 393053 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' La Belle Noiseuse ' ,
           y: 59827 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Mona Lisa Smile drawing ' ,
           y: 14389803 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Days of Heaven ' ,
           y: 1725908 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' Solaris ' ,
           y: 14626499 ,
           sliced:true,
           color:"#8B4513",
         },{
           name: ' The Conformist ' ,
           y: 212985 ,
           sliced:true,
           color:"#8B4513",

In [121]:
# getting the number of tickets sold in the g-rated category
var9 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'G':
        var9.append(no_tickets[i])
len(var9)

42

In [122]:
# getting the name of the g-rated movies
var10 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'G':
        var10.append(all_ArtHouseandIntern_info1['Name'][i])
len(var10)

42

In [123]:
# getting the profit of thr g-rated movies
var11 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'G':
        var11.append(all_ArtHouseandIntern_info1['Profit'][i])
len(var11)

42

Using a for loop to put the name and the number of tickets sold in the G-rated genre in html code which will be pasted in the cell below.

In [141]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var10[i],"'",','+'\n           y:',var9[i],',','\n           sliced:true,'+'\n           color:"#D4AF37",')

         },{
           name: ' Jupiter Ascending ' ,
           y: 13998655 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' A Good Day to Die Hard ' ,
           y: 23403784 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Murder on the Orient Express ' ,
           y: 26609441 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Bulletproof Monk ' ,
           y: 1770047 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Bedazzled ' ,
           y: 6952017 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Sound of Music ' ,
           y: 183805119 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Mary Poppins ' ,
           y: 66331766 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Little Mermaid ' ,
           y: 36963490 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Singin' in the Rain ' ,
           y: 5470774 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Great Muppet Caper ' ,
           y: 7245224 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Snow White and the Seven Dwarfs ' ,
           y: 598231495 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Fiddler on the Roof ' ,
           y: 40526576 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Swan Princess ' ,
           y: 1342863 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Jungle Book(1967)  ' ,
           y: 230206154 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Space Buddies ' ,
           y: 2476421 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Muppets From Space ' ,
           y: 2729019 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: '  ' ,
           y: 13789631 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The League of Extraordinary Gentlemen ' ,
           y: 3379674 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Timeline ' ,
           y: 4401838 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Walking Tall ' ,
           y: 5683252 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Last Starfighter ' ,
           y: 40100912 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' WALL• E ' ,
           y: 16156 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Dark Star ' ,
           y: 9279423 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Ice Station Zebra (1968) ' ,
           y: 1451918 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Fear of Rain ' ,
           y: 12329178 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Angry Men ' ,
           y: 20550955 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Fight Club  ' ,
           y: 34075615 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Rear Window ' ,
           y: 4610843 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Psycho ' ,
           y: 43917681 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Usual Suspects ' ,
           y: 4729116 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Se7en ' ,
           y: 3829782 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Memento ' ,
           y: 7505481 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Reindeer Games ' ,
           y: 2786457 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Little Prince ' ,
           y: 1430421 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Clue ' ,
           y: 27585153 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Rear Window ' ,
           y: 697684 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Night of the Hunter ' ,
           y: 11772 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' The Lady Vanishes ' ,
           y: 9269283 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' North by Northwest ' ,
           y: 70966 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Palm Springs ' ,
           y: 58887 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: ' Tell No One ' ,
           y: 3400497 ,
           sliced:true,
           color:"#D4AF37",
         },{
           name: '  ' ,
           y: 826246 ,
           sliced:true,
           color:"#D4AF37",

In [124]:
# getting the number of tickets sold in the pg13-rated category
var12 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG-13':
        var12.append(no_tickets[i])
len(var12)

42

In [125]:
# getting the name of the pg13-rated movies
var13 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG-13':
        var13.append(all_ArtHouseandIntern_info1['Name'][i])
len(var13)

42

In [126]:
# getting the profit of thr pg13-rated movies
var14 = []
for i,x in enumerate(all_ArtHouseandIntern_info1.System_ratings):
    if x == 'PG-13':
        var14.append(all_ArtHouseandIntern_info1['Profit'][i])
len(var14)

42

Using a for loop to put the name and the number of tickets sold in the PG-13-rated genre in html code which will be pasted in the cell below.

In [143]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var13[i],"'",','+'\n           y:',var12[i],',','\n           sliced:true,'+'\n           color:"#996515",')

         },{
           name: ' The Hobbit: An Unexpected Journey ' ,
           y: 78231044 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Alice Through the Looking Glass ' ,
           y: 21302162 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Watchmen ' ,
           y: 14382788 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Bourne Legacy ' ,
           y: 21565840 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Passengers ' ,
           y: 23249206 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Casino Royale ' ,
           y: 45724637 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Minority Report ' ,
           y: 27601901 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Tourist ' ,
           y: 21440875 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Kingsman: The Secret Service ' ,
           y: 31120133 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Fountain ' ,
           y: 1676663 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Primer ' ,
           y: 91531 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Tree of Life ' ,
           y: 4493019 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Another Earth ' ,
           y: 177236 ,
           sliced:true,
           color:"#996515",
         },{
           name: '  The New World ' ,
           y: 5464314 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Restless  ' ,
           y: 312784 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Box ' ,
           y: 2564118 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Departures ' ,
           y: 5433612 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Chorus ' ,
           y: 8918251 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Kite Runner ' ,
           y: 7447748 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Radio Flyer  ' ,
           y: 675918 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Cider House Rules ' ,
           y: 10824468 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' A Better Life ' ,
           y: 143347 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' A Separation ' ,
           y: 1763544 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Crouching Tiger, Hidden Dragon  ' ,
           y: 25419361 ,
           sliced:true,
           color:"#996515",
         },{
           name: '  Dear Frankie ' ,
           y: 180125 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Invictus ' ,
           y: 9402613 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Life Is Beautiful ' ,
           y: 17603645 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Diving Bell and the Butterfly ' ,
           y: 2259262 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Perks of Being a Wallflower ' ,
           y: 2568010 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Impossible ' ,
           y: 21535360 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Sea Inside ' ,
           y: 4749332 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Perks of Being a Wallflower ' ,
           y: 2568010 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Back to the Future ' ,
           y: 42254905 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Apollo 13 ' ,
           y: 29959316 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Finding Neverland ' ,
           y: 12681853 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Groundhog Day ' ,
           y: 10012155 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Hidden Figures ' ,
           y: 18150531 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Boy Erased ' ,
           y: 912512 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' The Imposter ' ,
           y: 248671 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' happy as lazzaro ' ,
           y: 138669 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' My Life as a Zucchini ' ,
           y: 451738 ,
           sliced:true,
           color:"#996515",
         },{
           name: ' Godzilla ' ,
           y: 41153846 ,
           sliced:true,
           color:"#996515",

In [127]:
# putting all the number of tickest that each movie made in a list
ttl = var3+var6+var9+var12+var
ttl

[40885742,
 25674695,
 56266414,
 96861516,
 32732483,
 9431063,
 30577027,
 66528311,
 61300563,
 73879351,
 17847527,
 13633936,
 22985786,
 10051781,
 67632703,
 39647679,
 11184288,
 24804539,
 28146154,
 19979699,
 13633936,
 9844868,
 797290,
 67632703,
 39647679,
 20614266,
 7401690,
 6318875,
 28146154,
 12761538,
 12268274,
 13354883,
 11075824,
 19001831,
 17036072,
 14060194,
 17239813,
 13691831,
 7396055,
 9489911,
 4195436,
 79594442,
 78555015,
 8247135,
 19191393,
 10838462,
 32029653,
 7351750,
 6473387,
 3737340,
 2180650,
 2623477,
 27930409,
 5561174,
 5349141,
 3132136,
 38145,
 5189,
 7703084,
 11192,
 4589,
 32998,
 1181177,
 610930,
 441228,
 11843045,
 4330769,
 2420522,
 1707692,
 4493019,
 22408,
 387895,
 5023077,
 4213658,
 25792247,
 36619,
 3245205,
 1584335,
 393053,
 59827,
 14389803,
 1725908,
 14626499,
 212985,
 13998655,
 23403784,
 26609441,
 1770047,
 6952017,
 183805119,
 66331766,
 36963490,
 5470774,
 7245224,
 598231495,
 40526576,
 1342863,
 230206154,
 2476421,
 2729019,
 13789631,
 3379674,
 4401838,
 5683252,
 40100912,
 16156,
 9279423,
 1451918,
 12329178,
 20550955,
 34075615,
 4610843,
 43917681,
 4729116,
 3829782,
 7505481,
 2786457,
 1430421,
 27585153,
 697684,
 11772,
 9269283,
 70966,
 58887,
 3400497,
 826246,
 78231044,
 21302162,
 14382788,
 21565840,
 23249206,
 45724637,
 27601901,
 21440875,
 31120133,
 1676663,
 91531,
 4493019,
 177236,
 5464314,
 312784,
 2564118,
 5433612,
 8918251,
 7447748,
 675918,
 10824468,
 143347,
 1763544,
 25419361,
 180125,
 9402613,
 17603645,
 2259262,
 2568010,
 21535360,
 4749332,
 2568010,
 42254905,
 29959316,
 12681853,
 10012155,
 18150531,
 912512,
 248671,
 138669,
 451738,
 41153846,
 45514775,
 77076631,
 57389222,
 17017641,
 97882301,
 22524449,
 15006198,
 3042289,
 21953846,
 48608502,
 39942945,
 32012947,
 10230755,
 22295995,
 37394161,
 27922237,
 25486416,
 9315385,
 87800257,
 13030769,
 0,
 31534916,
 116764300,
 16437791,
 10983363,
 7797771,
 4116066,
 1603163,
 15881186,
 26339728,
 15618121,
 17045762,
 5655507,
 2355899,
 15594354,
 1528505,
 54315602,
 9119733,
 1674956,
 12361538,
 4431133,
 6319245]

In [128]:
# adding all the number of tickects ech movie made
tt2 = 0
for i in ttl:
    tt2+=i

In [129]:
# average of no tickets of R system rating
v = 0
for i in var:
    v+=i
round(v/tt2*100,0)

23.0

In [130]:
# average of no tickets of NR system rating
v1 = 0
for i in var3:
    v1+=i
round(v1/tt2*100,0)

25.0

In [131]:
# average of no tickets of PG system rating
v2 = 0
for i in var6:
    v2+=i
round(v2/tt2*100,0)

7.0

In [132]:
# average of no tickets of G system rating
v3 = 0
for i in var9:
    v3+=i
round(v3/tt2*100,0)

32.0

In [133]:
# average of no tickets of PG13 system rating
v4= 0
for i in var12:
    v4+=i
round(v4/tt2*100,0)

12.0

In [3]:
%%html
<script src="http://code.highcharts.com/highchart.js"></script>
<div id='hraph7' style="height:700px"></div>

In [9]:
%%js
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'hraph7'//name of graph 
    },
    title:{
        text:'Number of Tickets Sold'
    },
    subtitle:{
        text:'Art House and International Genre'
    },
    series:[{
        type:'pie',// makes the graph pie 
        name: 'Percentage of Tickets Sold',
        tooltip:{
            // turns digits to percentage
            valueSuffix:'%'
        },
        shadow: true,
        data:[{
            name:'System Rating: R',// name of category
            y:23.0,// amount of tickets sold in percentage
            sliced:true,
            color: '#CD853F',// color of section
        },{
            name:'System Rating: PG-13',// name of category
            y:12.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#996515',// color of section
        },{
            name:'System Rating: PG',// name of category
            y:7.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#8B4513',// color of section
        },{
            name:'System Rating: NR',// name of category
            y:25.0,// amount of tickets sold in percentage
            sliced:true,
            color:'gold',// color of section
        },{
            name:'System Rating: G',// name of category
            y:32.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#D4AF37',// color of section
        }],
        innerSize:'80%',// size of inner pie
        size:'83%'// size of outer pie
       },{
        type:'pie',
        shadow: true,
        dataLabels: false,
        name: 'No. of Tickets Sold',
        data:[{ 
           name: ' Quantum of Solace ' ,
           y: 45514775 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' The Dark Knight ' ,
           y: 77076631 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Suicide Squad ' ,
           y: 57389222 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Wild Wild West ' ,
           y: 17017641 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Frozen ' ,
           y: 97882301 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' G-Force ' ,
           y: 22524449 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Beowulf ' ,
           y: 15006198 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Mars Needs Moms ' ,
           y: 3042289 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Lethal Weapon 4 ' ,
           y: 21953846 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Kung Fu Panda ' ,
           y: 48608502 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' How to Train Your Dragon: The Hidden World ' ,
           y: 39942945 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Jason Bourne ' ,
           y: 32012947 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' AstÃ©rix aux Jeux Olympiques ' ,
           y: 10230755 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Ferdinand ' ,
           y: 22295995 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Mr. and Mrs. Smith ' ,
           y: 37394161 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Ocean\'s Twelve ' ,
           y: 27922237 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' National Treasure ' ,
           y: 25486416 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Starship Troopers ' ,
           y: 9315385 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' The Lord of the Rings: The Return of the King ' ,
           y: 87800257 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' The Saint ' ,
           y: 13030769 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Bright ' ,
           y: 0 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' The Mummy ' ,
           y: 31534916 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' The Avengers ' ,
           y: 116764300 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Smallfoot ' ,
           y: 16437791 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Conspiracy Theory ' ,
           y: 10983363 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Mars Attacks! ' ,
           y: 7797771 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Nine ' ,
           y: 4116066 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' The Postman ' ,
           y: 1603163 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Red Dragon ' ,
           y: 15881186 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Wanted ' ,
           y: 26339728 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Hairspray ' ,
           y: 15618121 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Constantine ' ,
           y: 17045762 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Life ' ,
           y: 5655507 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Virus ' ,
           y: 2355899 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Vanilla Sky ' ,
           y: 15594354 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Hard Rain ' ,
           y: 1528505 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' The Twilight Saga: Eclipse ' ,
           y: 54315602 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Body of Lies ' ,
           y: 9119733 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Live by Night ' ,
           y: 1674956 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Alien: Resurrection ' ,
           y: 12361538 ,
           sliced:false,
           color:"#CD853F",
         },{ 
           name: ' Year One ' ,
           y: 4431133 ,
           sliced:true,
           color:"#CD853F",
         },{ 
           name: ' Reign of Fire ' ,
           y: 6319245 ,
           sliced:false,
           color:"#CD853F",
        },{ 
           name: ' The Hobbit: An Unexpected Journey ' ,
           y: 78231044 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Alice Through the Looking Glass ' ,
           y: 21302162 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Watchmen ' ,
           y: 14382788 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Bourne Legacy ' ,
           y: 21565840 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Passengers ' ,
           y: 23249206 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Casino Royale ' ,
           y: 45724637 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Minority Report ' ,
           y: 27601901 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Tourist ' ,
           y: 21440875 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Kingsman: The Secret Service ' ,
           y: 31120133 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Fountain ' ,
           y: 1676663 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Primer ' ,
           y: 91531 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Tree of Life ' ,
           y: 4493019 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Another Earth ' ,
           y: 177236 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: '  The New World ' ,
           y: 5464314 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Restless  ' ,
           y: 312784 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Box ' ,
           y: 2564118 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Departures ' ,
           y: 5433612 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Chorus ' ,
           y: 8918251 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' The Kite Runner ' ,
           y: 7447748 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Radio Flyer  ' ,
           y: 675918 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' The Cider House Rules ' ,
           y: 10824468 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' A Better Life ' ,
           y: 143347 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' A Separation ' ,
           y: 1763544 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Crouching Tiger, Hidden Dragon  ' ,
           y: 25419361 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: '  Dear Frankie ' ,
           y: 180125 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Invictus ' ,
           y: 9402613 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Life Is Beautiful ' ,
           y: 17603645 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Diving Bell and the Butterfly ' ,
           y: 2259262 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' The Perks of Being a Wallflower ' ,
           y: 2568010 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Impossible ' ,
           y: 21535360 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' The Sea Inside ' ,
           y: 4749332 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' The Perks of Being a Wallflower ' ,
           y: 2568010 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Back to the Future ' ,
           y: 42254905 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Apollo 13 ' ,
           y: 29959316 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Finding Neverland ' ,
           y: 12681853 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Groundhog Day ' ,
           y: 10012155 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' Hidden Figures ' ,
           y: 18150531 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Boy Erased ' ,
           y: 912512 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' The Imposter ' ,
           y: 248671 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' happy as lazzaro ' ,
           y: 138669 , 
           sliced:false,
           color:"#996515",
         },{ 
           name: ' My Life as a Zucchini ' ,
           y: 451738 , 
           sliced:true,
           color:"#996515",
         },{ 
           name: ' Godzilla ' ,
           y: 41153846 , 
           sliced:false,
           color:"#996515",
        },{ 
           name: ' Finding Dory ' ,
           y: 78555015 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Chronicles of Riddick ' ,
           y: 8247135 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Eragon ' ,
           y: 19191393 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Devil\'s Own ' ,
           y: 10838462 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' The Mummy ' ,
           y: 32029653 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Killers ' ,
           y: 7351750 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Priest ' ,
           y: 6473387 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Avengers ' ,
           y: 3737340 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' The Kid Who Would Be King ' ,
           y: 2180650 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Instinct ' ,
           y: 2623477 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' A Bug\'s Life ' ,
           y: 27930409 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Colombiana ' ,
           y: 5561174 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Because I Said So ' ,
           y: 5349141 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Lagaan ' ,
           y: 3132136 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' April and the Extraordinary World ' ,
           y: 38145 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: '  Badlands ' ,
           y: 5189 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Where the Wild Things Are ' ,
           y: 7703084 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Andrei Rublev ' ,
           y: 11192 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Tokyo Story ' ,
           y: 4589 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Bicycle Thieves ' ,
           y: 32998 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Days of Heaven ' ,
           y: 1181177 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Suspiria ' ,
           y: 610930 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Under the Skin ' ,
           y: 441228 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Midnight in Paris ' ,
           y: 11843045 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Frida ' ,
           y: 4330769 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Girl with a Pearl Earring ' ,
           y: 2420522 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Mr. Turner ' ,
           y: 1707692 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Tree of Life ' ,
           y: 4493019 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Waste Land ' ,
           y: 22408 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Rivers and Tides ' ,
           y: 387895 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Moonlight ' ,
           y: 5023077 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' 3 Ninjas ' ,
           y: 4213658 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Karate Kid ' ,
           y: 25792247 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Walt Before Mickey ' ,
           y: 36619 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Loving Vincent ' ,
           y: 3245205 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Best Offer  ' ,
           y: 1584335 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Basquiat (film) ' ,
           y: 393053 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' La Belle Noiseuse ' ,
           y: 59827 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Mona Lisa Smile drawing ' ,
           y: 14389803 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' Days of Heaven ' ,
           y: 1725908 , 
           sliced:true,
           color:"#8B4513",
         },{ 
           name: ' Solaris ' ,
           y: 14626499 , 
           sliced:false,
           color:"#8B4513",
         },{ 
           name: ' The Conformist ' ,
           y: 212985 , 
           sliced:true,
           color:"#8B4513",
        },{ 
           name: ' Finding Dory ' ,
           y: 78555015 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Chronicles of Riddick ' ,
           y: 8247135 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Eragon ' ,
           y: 19191393 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Devil\'s Own ' ,
           y: 10838462 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' The Mummy ' ,
           y: 32029653 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Killers ' ,
           y: 7351750 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Priest ' ,
           y: 6473387 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Avengers ' ,
           y: 3737340 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' The Kid Who Would Be King ' ,
           y: 2180650 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Instinct ' ,
           y: 2623477 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' A Bug\'s Life ' ,
           y: 27930409 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Colombiana ' ,
           y: 5561174 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Because I Said So ' ,
           y: 5349141 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Lagaan ' ,
           y: 3132136 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' April and the Extraordinary World ' ,
           y: 38145 , 
           sliced:false,
           color:"gold",
         },{ 
           name: '  Badlands ' ,
           y: 5189 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Where the Wild Things Are ' ,
           y: 7703084 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Andrei Rublev ' ,
           y: 11192 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Tokyo Story ' ,
           y: 4589 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Bicycle Thieves ' ,
           y: 32998 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Days of Heaven ' ,
           y: 1181177 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Suspiria ' ,
           y: 610930 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Under the Skin ' ,
           y: 441228 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Midnight in Paris ' ,
           y: 11843045 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Frida ' ,
           y: 4330769 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Girl with a Pearl Earring ' ,
           y: 2420522 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Mr. Turner ' ,
           y: 1707692 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Tree of Life ' ,
           y: 4493019 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Waste Land ' ,
           y: 22408 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Rivers and Tides ' ,
           y: 387895 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Moonlight ' ,
           y: 5023077 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' 3 Ninjas ' ,
           y: 4213658 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Karate Kid ' ,
           y: 25792247 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Walt Before Mickey ' ,
           y: 36619 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Loving Vincent ' ,
           y: 3245205 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Best Offer  ' ,
           y: 1584335 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Basquiat (film) ' ,
           y: 393053 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' La Belle Noiseuse ' ,
           y: 59827 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Mona Lisa Smile drawing ' ,
           y: 14389803 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' Days of Heaven ' ,
           y: 1725908 , 
           sliced:true,
           color:"gold",
         },{ 
           name: ' Solaris ' ,
           y: 14626499 , 
           sliced:false,
           color:"gold",
         },{ 
           name: ' The Conformist ' ,
           y: 212985 , 
           sliced:true,
           color:"gold",
        },{ 
           name: ' Jupiter Ascending ' ,
           y: 13998655 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' A Good Day to Die Hard ' ,
           y: 23403784 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Murder on the Orient Express ' ,
           y: 26609441 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Bulletproof Monk ' ,
           y: 1770047 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Bedazzled ' ,
           y: 6952017 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Sound of Music ' ,
           y: 183805119 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Mary Poppins ' ,
           y: 66331766 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Little Mermaid ' ,
           y: 36963490 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Singin\' in the Rain ' ,
           y: 5470774 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Great Muppet Caper ' ,
           y: 7245224 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Fiddler on the Roof ' ,
           y: 40526576 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' The Swan Princess ' ,
           y: 1342863 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Jungle Book(1967)  ' ,
           y: 230206154 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Space Buddies ' ,
           y: 2476421 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Muppets From Space ' ,
           y: 2729019 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: '  ' ,
           y: 13789631 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The League of Extraordinary Gentlemen ' ,
           y: 3379674 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Timeline ' ,
           y: 4401838 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Walking Tall ' ,
           y: 5683252 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' The Last Starfighter ' ,
           y: 40100912 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' WALL• E ' ,
           y: 16156 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Dark Star ' ,
           y: 9279423 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Ice Station Zebra (1968) ' ,
           y: 1451918 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Fear of Rain ' ,
           y: 12329178 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Angry Men ' ,
           y: 20550955 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Fight Club  ' ,
           y: 34075615 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Rear Window ' ,
           y: 4610843 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Psycho ' ,
           y: 43917681 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Usual Suspects ' ,
           y: 4729116 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Se7en ' ,
           y: 3829782 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Memento ' ,
           y: 7505481 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Reindeer Games ' ,
           y: 2786457 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Little Prince ' ,
           y: 1430421 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Clue ' ,
           y: 27585153 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Rear Window ' ,
           y: 697684 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' The Night of the Hunter ' ,
           y: 11772 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' The Lady Vanishes ' ,
           y: 9269283 , 
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' North by Northwest ' ,
           y: 70966 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: ' Palm Springs ' ,
           y: 58887 , 
           sliced:true,
           color:"#D4AF37",
         },{
           name:'Snow White and the Seven Dwarfs ' ,
           y: 198231495,
           sliced:true,
           color:"#D4AF37",
         },{ 
           name: ' Tell No One ' ,
           y: 3400497 , 
           sliced:false,
           color:"#D4AF37",
         },{ 
           name: '  ' ,
           y: 826246 , 
           sliced:true,
           color:"#D4AF37"
        }],
    innerSize:'93%',// size of inner pie
    size:'100%'// size of outer pie
    }]
});