  # Objective

__Microsoft sees all the big companies creating original video content, and they want to get in on the fun. They have decided to create a new movie studio, but the problem is they don't know anything about creating movies. They have hired you to help them better understand the movie industry. Your team is in charge with doing data analysis that explores what type of films are currently doing the best at the box office. You must then translate
those findings into actionable insights that the CEO can use when deciding what type of films they should be creating.__

# Datasets

There are 10 datasests in this project 

_Name.basics.csv_
  - _Colunms in the dataset_
     - _nconst_
     - _primary_name_
     - _birth_year_
     - _death_year_
     - _primary_profession_
     - _known_for_titles_

_Bom.movie_gross.csv_
   - _Colunms in the dataset_
      - _title_
      - _studio_
      - _domestic_gross_
      - _foreign_gross_
      - _year_
     
_Rt.movie_info.tsv_
   - _Columns in the dataset_
     - _id_
     - _synopsis_
     - _rating_
     - _genre_
     - _director_
     - _writer_
     - _theater_date_
     - _currency_
     - _box_office_
     - _runtime_
     - _studio_
     
_Title.akas.csv_
   - _Columns in the dataset_
     - _title_id_
     - _ordering_
     - _title_
     - _region_
     - _language_
     - _types_
     - _attributes_
     - _is_original_title_
     
_Title.basics.csv_
  - _Columns in the dataset_
    - _tconst_
    - _primary_title_
    - _original_title_
    - _start_year_
    - _runtime_mintues_
    - _genres_
    
_Title.crew.csv_
  - _Columns in the dataset_
    - _tconst_
    - _directors_
    - _writers_
    
_Title.principals.csv_
  - _Columns in the dataset_
    - _tconst_
    - _ordering_
    - _nconst_
    - _category_
    - _job_
    - _charactors_

_Title.ratings.csv_
  - _Columns in the dataset_
    - _tconst_
    - _averagerating_
    - _numvoters_
    
_Tmdb.movies.csv_
  - _Columns in the dataset_
    - _genre_ids_
    - _id_
    - _original_language_
    - _original_title_
    - _popularity_
    - _release_date_
    - _title_
    - _vote_average_
    - _vote_count_
    
_Tn.movie_budgets_
   - _Columns in the dataset_
     - _id_
     - _release_date_
     - _movie_
     - _production_budget_
     - _domestic_gross_
     - _worldwide_gross_

# Approaches

Based on the datasets there are nine main genres; Action and Adventures, Drama, Comedy, Documentry, Classics, Art House and International, Musical and Performing Arts, Horror, Mystrey and Suspense, Animation, Special Interest, Kids and Family and there are also five main System Ratings; System R Rating, System PG-13 Rating, System PG Rating, System G Rating and System NR Rating. In this Project the genres that are being chosen are Action & Adventure, Drama, Comedy, Classics and Art House and International which will all have indivisual data analysis based on the same data visualization concepts and the system ratings are being compared among one another and also analyised to view which one best fit the genres. There will be eleven differnt graphs for each genres describing and protarying insights on the activity of the data.

## Graphs
These are the elven main graphs.
  - __Profit Percentage baised on cost__:
     - This data visualization shows the name, cost, profit, the type of system rating and profit percenatge by cost. The purpose of this notion is to view past the profit and better understand how successful the movie really is by analysing the cost and calculating how much more was made compared to it. This allows the idea of higher profit dosn't mean more profitable to be considered as a justification based on the results proving so. The system rating were added to be compared among eachother, to observe which one was better and to also know which one was the best fit for any particular genere by calculating the average of the reults of each system rating
   
  
  
  - __Gross Profit Margin Percentage__:
     - This data visualization has two pionts about the movie on one panel. The fisrt piont shows the name, amount of profit made in dollars, type of system rating and Gross Profit Margin Percentage. The other piont shows the name, revenue made in dollars and the type of system rating. The graph was designed this way to compare the profit amount against the revenue amount, allowing the Gross Profit Margin Percntage to be more visible and inderectly see the expenses made from a graph perpsective.
     
 
 - __Budget and Revenue of Movies__:
    - This graph is a scatter plot with an x-axis and a y-axis, the x-axis is the revenue of the movies in dollars and the y-axis is the budget of the movies in dollars. This graph is a blueprint to better understand  wether the amount of money spent on the movie effected the amount of revenue generted and to also spot movies that spent less money than the average with a higher revenue.
 
 
 - __Revenue of Movies/Budget of Movies__:
    - The revenue graph has an x-axis that shows the revnue of the movies, name and the type of system ratings with no y-axis. The budget graph has an x-axis that shows the budget of the movies and also the name and system ratings with no y-axis. Both graphs have a table split into catagories of the system ratings showing were they are postions in the axis. These graphs were constructed to predict how much will be made depending on how much is spent based on the pattern of budget of movies to revenue of movies and to indirectly spot anomalies.
    
 
 - __Movies that mdae Profit__:
    - This graph simply shows all the movies that made profit, from the highest to the lowest.


 - __Movies that had losses__:
   - This graph is a colunm graph that shows the movies that did not make any profit. It shows the cost of the movie, revenue and by how much was not made to prevent a loss by the movie. It also shows the name and system ratings it belongs to. This dilema was created to percieve what agenda was not making any money, to try and understand the other half of film industry that is overlooked.
   
   
 
 - __Top 20 Highest Profitable Movies/ Top 20 Lowest Profitable Mobies__:
    - The top 20 highest profitable graph is a 3D chart that shows the top 20 most profitable movies with an x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. The top 20 lowest profitable graph is also a 3D chart that shows the top 20 movies that had the lowest profit, with the x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. These graphs were creted to really spot what movis were the kings and queens of the movie industry and what movie was barely making sales. This brings a lot of questioning to what each of the movies did do britiantally or failed to do.
    

- __Most Successful Moive__:
   - This graph is built up of two sections, the first section is an x-axis whcih shows the names and a y-axis which shows the budget, revenu and profit of the movies in dollars, the second section compares the gross profit margin percentage to the profit percnatge by cost of the movies whcih is all compared to all other movies in the data frame. The sections data is based on the top 20 most profitable movies. The concept of the visualization is to  dive deep into detail to anlayze what movie were actually more succesfull than the other, other than just focusing on the highets profits made. Factors like budget and revenue expressed in gross profit margin percentage and proft percentage by cost allows the differences among the most profitable movies to become more disguishable, whcih can open a new perspcetive on anyalzing numbers.
   
 
 - __Tickets Sold__:
    - This graph simply shows what system ratings have the highest tickets sold to better understand what audience best fist this genre through the sales of the system ratings.

Before starting any data extracting, liabreis such as Altair, Pandas, Pandas_highcharts, Collections need to be installed to help create great insightful interactive graphs.

In [1]:
import altair as alt # used to create interactive graphs
import pandas as pd # used to make for dataframes
import collections# used to put data into sections
import matplotlib.pyplot as plt# used to make graphs

In [2]:
# helps create highcharts graphs
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import json

Before the graphs are made the data is extracted from the rt.movie_info.tsv file and made into a dataframe.

In [3]:
# The data frame is called movie_info
movie_info = pd.read_csv("rt.movie_info.tsv.gz",error_bad_lines=False,sep='\t')

In [4]:
movie_info.head()

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN

In [5]:
# Getting first 500 movies 
first_500 = []
for i in movie_info.genre[:500].dropna():
    first_500.append(i)
len(first_500)

496

The movies form the data frame have been selected and put into genres groups for the first 500 movies

In [6]:
# putting movies into groups
grouped_500 = []
for i in first_500:
    grouped_500.append(i.split('|',1)[0])
grouped_500=collections.Counter(grouped_500)
grouped_500

Counter({'Action and Adventure': 117,
         'Drama': 103,
         'Comedy': 115,
         'Documentary': 11,
         'Classics': 53,
         'Art House and International': 55,
         'Musical and Performing Arts': 3,
         'Horror': 23,
         'Mystery and Suspense': 7,
         'Animation': 6,
         'Special Interest': 2,
         'Kids and Family': 1})

# Blueprint: Profit Percentage Based on Cost

The amount of movies in the genre groups are all uneven, the goal through out the project is to make sure they all have the same amount of movies that are being analyzed to give it a fair comparison which will be done later on in the project.

The next step is to choose a genre to select and start analyzing. For this section Action and Adventure is being analyzed.

This is the blueprint for creating the first visualization Profit Percentage by cost, bokeh will be used to create these graphs.
Blueprint:
 1. Create a new dataframe for the graph, the dataframe columns will consist of these key infomation of the moives in the Action and Adventure Genre;
    - The Names 
    - Product Budget 
    - System Ratings 
    - Ratings 
    - Domestic Gross 
    - World Wide Gross
    - Profit
    - No. of Tickets
    - Product Budget in integers
    - Profit in integers
    - Total Gross in integers
    - Domestic total in integers
 
 
 2. Install bokeh and create the componets needed for the format of the code script for the graph.There will be five graphs and in each graph are key information of the movies based on the same system rating which are R, PG-13, PG, G and NR. These are the key componets needed in each graph based on the same system rating;
    - X-axis Range
    - Y-axis Range
    - Name
    - Profit in integers
    - System Rating
    - Percentage Profit by Cost
    - Cost


3. The graphs has to have visual componets that convey the information smoothly and also differentiate from one another due to that fact that they are all in groups, these are the formats to help do so; 
    - Color
    - Tooltips (make the graph interactive)
    - Type and shape of pionts in the graph

Below is the code script used to create a new dataframe needed for the graphs

In [7]:
# Getting the names of the first 200 movies in the Action and Adventure genre
movie_buddget = pd.read_csv('tn.movie_budgets.csv.gz')
name_movies = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl': # 'Cl' is the first two words for Action and Adventure
        name_movies.append(movie_buddget.movie[x])
len(name_movies)

53

In [8]:
# Getting product budget of the first 200 movies in Action and Adventure genre
product_budget = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl':product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

53

In [9]:
# Getting ratings of the first 200 movies in Action and Adventure genre
ratings = pd.read_csv('imdb.title.ratings.csv.gz')
rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl': rating.append(ratings.averagerating[x])
len(rating)

53

In [10]:
# Getting system ratings of the first 200 movies in Action and Adventure genre
system_rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl': system_rating.append(movie_info.rating[x])
len(system_rating)

53

In [11]:
# Getting domestic gross of the first 200 movies in Action and Adventure genre
domestic_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl': domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

53

In [12]:
# Getting worldwide gross of the first 200 movies in Action and Adventure genre
worldwide_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Cl': worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

53

The amount of movies per system rating all have to be the same. The code bellow caluclates how much movies are currently in each system rating.

In [12]:
# putting system ratings into groups
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating
# need all groups to be even, all groups need 42 records

Counter({'NR': 16, 'G': 5, 'R': 18, 'PG-13': 7, 'PG': 7})

'NR' has the highest count of movies, so all system rating will have to have 42 movies based on all the previous genre analysis to make it a fair analysis

Due to the fact that the amount of movies per system rating is not tha same, the following codes caluclate how much is needed for each misiing amount in each group and also getting the indexes of what is needed.

In [27]:
# making sure all system_rating have the same amout of records
# getting the index of  system PG-13: need 35
index_PG13 = movie_info[movie_info['rating']=='PG-13'].index
index_PG13[250:300]

Int64Index([], dtype='int64')

Based on the indexes on the 'PG-13' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-13-rated. The 35 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [66]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Jumanji: The Next Level':
        print('yes')

In [13]:
#informations on the movies needed for pg-13
# the name of the movies
name_mojo1 = ['News of the World','Greenland','Ladybugs','Edward Scissorhands','Mrs. Doubtfire','The Prestige',
             'Jumanji: The Next Level','The Dark Knight','13 Going on 30','Titanic','Catch Me If You Can','Knives Out',
             'Fantastic Beasts: The Crimes of Grindelwald','Forrest Gump','Iron Man','Batman Begins',
             'The Lord of the Rings: The Return of the King','Inception','Gravity','The Help','Jurassic World',
              'The Hunger Games','The Ring','Ferris Bueller\'s Day Off','Don\'t Tell Mom the Babysitter\'s Dead'
             ,'Spider-Man 2','Sully','Mean Girls','Gremlins','Jason Bourne','Skyfall','Clueless','The Sixth Sense',
             'Wonder Woman 1984','The Addams Family','School of Rock','Harry Potter and the Order of the Phoenix',
             'Jurassic Park']
# ratings of the movies
rating_mojo1 = [6.9,6.4,5.5,7.9,7,8.5,6.7,9,6.2,7.8,8.1,7.9,6.6,8.8,7.9,8.2,8.9,8.8,7.7,8,7,7.2,7.1,7.8,6.3,7.3,7.4,7,7.3,6.6,7.7,
               6.8,8.1,5.5,5.8,7.1,7.5,8.1]
# worldwide gross
worldwide_gross_mojo1 = ['$8,634,510','$40,402,370','$$27,572,982','$$175,296,617','$799,147,841','$136,331,191','$800,100,000'
                         ,'$1,003,045,358','$134,490,538','$2,127,488,188','$512,078,229','$311,400,000','$655,000,000',
                        '$1,198,221,927','$585,366,247','$373,661,946','$1,620,373,792','$826,137,188','$723,192,705','$213,120,004'
                         ,'$1,670,400,637','$694,394,724','$362,627,010','$166,251,779','$48,391,486','$1,099,589,817',
                        '$238,524,556','$181,437,627','$346,393,486','$529,082,360','$1,108,561,013','$99,487,849','$1,054,873,240',
                        '$821,847,012','$203,044,905','$186,225,341','$940,743,940','$1,652,797,272']
# domestic gross
domestic_gross_mojo1 = ['$8,634,510','$40,402,370','$$27,572,982',' $$114,858,517','$396,951,926','$69,322,772','$319,200,000'
                       ,'$533,345,358','$79,799,625','$600,788,188','$239,399,350','$165,400,000','$160,000,000',
                       '$581,894,777','$318,604,126','$206,852,432','$535,578,882','$292,576,195','$274,092,705','$169,705,587',
                       '$652,270,625','$408,010,692','$187,790,451','$164,896,827','$48,391,486','$520,899,857',
                       '$125,070,033','$119,992,852','$344,574,131','$206,845,490','$304,360,277','$97,156,558','$460,179,901',
                       '$412,563,408','$100,044,905','$115,433,995','$292,137,260','$646,632,689']
# product budget
product_budget_mojo1 = ['$38,000,000','$35,000,000','$37,269,615',' $40,757,176','$45,273,784','$52,230,487','$132,000,000'
                       ,'$185,000,000','$51,590,005','$200,000,000','$75,623,361','$82,000,000',' $200,000,000',
                       '$96,938,065','$140,000,000','$150,000,000','$133,529,883','$160,000,000','$100,000,000','$25,000,000',
                       '$150,000,000','$78,000,000','$69,806,179','$13,636,314','$19,205,829','$278,864,894',
                       '$60,000,000','$23,703,516','$25,581,122','$152,809,117','$200,000,000','$34,331,863','$62,714,826',
                       '$200,000,000','$24,000,000','$49,718,573','$150,000,000','$114,089,936']

In [39]:

# making sure all system_rating have the same amout of records
# getting system PG: need 35
index_PG = movie_info[movie_info['rating']=='PG'].index
index_PG[250:300]

Int64Index([], dtype='int64')

In [81]:
movie_info.iloc[[  710,741,811,854,949,1065,1253,1258,1309,1485]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
710,912,George Cukor's remake of the 1940 film Gasligh...,PG,Classics|Drama|Mystery and Suspense,George Cukor,NaN,"May 11, 1944","Feb 3, 2004",NaN,NaN,114 minutes,NaN
741,953,This is the labyrinthine study of the life of ...,PG,Classics|Drama|Mystery and Suspense,Orson Welles,NaN,"May 1, 1941","Sep 25, 2001",NaN,NaN,119 minutes,NaN
811,1048,"In this film, Jerry Mathers stumbles upon Harr...",PG,Classics|Comedy|Mystery and Suspense,Alfred Hitchcock,John Michael Hayes|John Hayes,"Oct 3, 1955","Mar 6, 2001",NaN,NaN,100 minutes,NaN
854,1102,"Teenaged Anne Frank, a Dutch Jew, perished alo...",PG,Classics|Drama,George Stevens,Albert Hackett|Frances Goodrich,"Mar 18, 1959","Feb 3, 2004",NaN,NaN,156 minutes,NaN
949,1228,This film follows the unconventional romance b...,PG,Classics|Comedy|Musical and Performing Arts|Ro...,Milton Katselas,Leonard Gershe|Jay Presson Allen,NaN,NaN,NaN,NaN,108 minutes,NaN
1065,1375,"Joseph P. ""Kotch"" Kotcher is an irksome 72-yea...",PG,Classics|Comedy|Drama,Jack Lemmon,John Paxton,"Sep 17, 1971","Jul 6, 2004",NaN,NaN,113 minutes,NaN
1253,1616,Chuck Scott gets a job as chauffeur to tough g...,PG,Classics|Drama|Mystery and Suspense,Arthur Ripley,Philip Yordan,"Nov 16, 1946","Aug 5, 2003",NaN,NaN,86 minutes,NaN
1258,1624,This second film adaptation of Richard Matheso...,PG,Classics|Science Fiction and Fantasy,Boris Sagal,NaN,"Aug 1, 1971","Mar 6, 2000",NaN,NaN,99 minutes,NaN
1309,1692,"Long before Grease was even thought of, the Br...",PG,Classics|Drama|Musical and Performing Arts,Claude Whatham,Ray Connolly,"Jan 1, 1973","Nov 28, 2000",NaN,NaN,90 minutes,NaN
1485,1911,This breathlessly paced high-tech thriller sta...,PG,Classics|Drama|Mystery and Suspense,Sidney Lumet,Lawrence Sanders|Frank Pierson,"Jun 17, 1971","Jan 6, 2003",NaN,NaN,95 minutes,NaN

In [93]:
#checking if the names are already used
for i in name_movies:
    if i == 'Sound of Music':
        print('yes!')
else:print('no')

no

In [82]:
movie_buddget.iloc[[710,741,811,854,949,1065,1253,1258,1309,1485]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
710,11,"Aug 13, 2004",AVP: Alien Vs. Predator,"$70,000,000","$80,281,096","$172,543,519"
741,42,"Jan 10, 2014",The Legend of Hercules,"$70,000,000","$18,848,538","$58,953,319"
811,12,"Jan 14, 2005",Elektra,"$65,000,000","$24,409,722","$56,824,633"
854,55,"May 9, 2003",Daddy Day Care,"$60,000,000","$104,148,781","$164,285,587"
949,50,"Oct 24, 2003",Beyond Borders,"$60,000,000","$4,426,297","$11,427,090"
1065,66,"Dec 19, 2012",Zero Dark Thirty,"$52,500,000","$95,720,716","$134,612,435"
1253,54,"Oct 5, 2012",Taken 2,"$45,000,000","$139,854,287","$377,807,404"
1258,59,"Jul 11, 2008",Journey to the Center of the Earth,"$45,000,000","$101,704,370","$243,180,937"
1309,10,"Jul 1, 2005",Rebound,"$45,000,000","$16,809,014","$17,492,014"
1485,86,"Jun 30, 2017",The House,"$40,000,000","$25,584,504","$31,192,425"

In [14]:
#new name index for pg
no1=[710,741,811,854,949,1065,1253,1258,1309,1485]

Based on the indexes on the 'PG' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was PG-rated. The 25 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [21]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'Cars':
        print('yes')

In [3]:
#informtions on the movies needed for pg
# the name of the movies
name_mojo2 = ['Fantastic Mr. Fox','Harry Potter and the Sorcerer\'s Stone','Labyrinth','Nim\'s Island','Spirited Away',
             'Hugo (film)','My Girl','Inkheart','Enchanted','Hook (film)','Bridge to Terabithia','The Goonies',
              'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe','Night at the Museum','The Parent Trap',
             'National Treasure','The Princess Bride','National Treasure: Book of Secrets','Up','The Witches 1990',
             'E.T. the Extra-Terrestrial','Nanny McPhee','Big (film)','Matilda','Finding Neverland','October Sky',
             'Free Willy','Karate Kid','The Iron Giant','Harry Potter and the Chamber of Secrets','Superman II',
             'The Lego Movie','Home Alone','Beethoven 1992','Race to Witch Mountain']
# ratings of the movies
rating_mojo2 = [7.9,7.6,7.4,6,8.6,7.5,6.9,6.1,7,6.8,7.1,7.8,6.9,6.4,6.5,6.9,8,6.5,8.9,6.9,7.8,6.5,7.3,6.9,7.6,7.8,
               6,7.3,8,7.4,6.8,7.7,0,7.6,5.7]
# worldwide gross
worldwide_gross_mojo2 = ['$46,471,023','$1,459,186,382','$31,058,805','$124,143,653','$411,556,547','$185,770,160',
                        '$236,509,222','$62,803,180','$439,485,533','$585,774,488','$177,590,944','$306,731,016',
                        '$1,019,722,175','$574,480,841','$741,603,630','$148,740,695','$72,738,988','$592,768,412','$735,099,082',
                        '$31,728,982','$2,197,125,900','$168,735,696','$342,337,714','$56,164,340','$164,864,089',
                        '$55,144,022','$281,950,714','$233,515,218','$49,742,746','1,295,706,514','$732,559,078',
                        '$1,203,631,583','$984,678,475','$278,040,411','$106,300,000']
# domestic gross
domestic_gross_mojo2 = ['$21,002,919','$475,403,297','$12,729,917','$59,535,095','$15,053,389','$73,864,507',
                       '$115,811,254','$17,303,424','$164,967,635','$585,774,488','$106,193,419','$156,828,600',
                        '$399,280,713','$250,863,268','$107,077,773','$355,207,271','$37,715,692','$167,797,918','$72,738,988','$283,919,389',
                        '$293,004,000','$21,400,909','$995,334,989','$64,528,717','$260,084,100','$51,762,151',
                        '$142,624,888','$233,515,218','$49,742,746','$386,198,007','$416,241,707',
                        '$1,203,631,583','$590,272,593','$107,880,527','$67,172,594']
# product budget
product_budget_mojo2 = ['$40,000,000','$187,122,126','$59,577,767','$45,885,172','$27,410,555','$156,000,000',
                        '$29,201,121','$60,000,000','$109,714,023','$136,271,898','$25,815,064','$46,999,107',
                        '$246,375,827','$110,000,000','$25,030,049','$161,484,190','$37,715,692','$167,797,918','$175,000,000',
                        '$22,721,760','$29,095,500','$34,218,86','$40,628,526','$61,088,364','$35,332,881',
                        '$31,784,502','$36,712,332','$20,570,503','$76,282,806','$147,410,299','$207,763,604',
                        '$167,135,340','$30,984,218','$33,999,506','$50,000,000']

In [50]:
# making sure all system_rating have the same amout of records
# getting system NR: need 26
index_PG = movie_info[movie_info['rating']=='NR'].index
index_PG[200:250]

Int64Index([618, 628, 629, 630, 638, 642, 644, 645, 647, 648, 654, 656, 658,
            661, 669, 677, 678, 679, 688, 693, 697, 699, 700, 711, 713, 714,
            715, 718, 720, 722, 724, 727, 731, 734, 735, 739, 742, 743, 745,
            747, 750, 767, 768, 770, 771, 772, 773, 776, 788, 789],
           dtype='int64')

In [86]:
movie_info.iloc[[ 236,238,263,265,268,290,312,320,393,415,441,456,465,469,478,489,491,528,551,577,591,
                   596,608,642,656,661,673,700,714,722,727,735,742]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
236,306,X the Unknown is a well-crafted imitation of t...,NR,Classics|Horror|Mystery and Suspense|Science F...,Joseph Losey|Leslie Norman,Jimmy Sangster,"Nov 5, 1956","Jul 26, 2004",NaN,NaN,90 minutes,NaN
238,309,The first person the audience sees in Ship of ...,NR,Classics|Documentary|Drama|Romance,Stanley Kramer,Abby Mann,"Jul 29, 1965","Dec 2, 2003",NaN,NaN,52 minutes,NaN
263,348,Dean Martin and Jerry Lewis made their last jo...,NR,Classics|Comedy,Frank Tashlin,Erna Lazarus,"Jan 1, 1956","Jun 5, 2007",NaN,NaN,95 minutes,NaN
265,350,An atomic bomb test in the Arctic Circle awake...,NR,Classics|Horror|Science Fiction and Fantasy,NaN,NaN,"Jun 13, 1953","Oct 21, 2003",NaN,NaN,80 minutes,NaN
268,354,Bob Hope's first starring vehicle for producer...,NR,Classics|Comedy|Musical and Performing Arts,David Butler,Frank Fenton|Harry Kurnitz|Lynn Root,"Mar 4, 1943","Aug 21, 2003",NaN,NaN,95 minutes,NaN
290,384,"In this romantic comedy, New York sportswriter...",NR,Classics|Comedy|Romance,George Stevens,NaN,"Jan 19, 1942","Aug 27, 1997",NaN,NaN,114 minutes,NaN
312,411,"In this bizarre, rarely seen melodrama, a soci...",NR,Classics|Drama|Mystery and Suspense,Jack Bernhard,NaN,"Jul 24, 1948","Sep 30, 2003",NaN,NaN,78 minutes,NaN
320,420,This tuneful melodrama is set during the heigh...,NR,Classics|Drama|Musical and Performing Arts|Mys...,Jack Webb,NaN,"Jul 31, 1955","Jul 22, 2008",NaN,NaN,95 minutes,NaN
393,509,After several years' service with the Marines ...,NR,Classics|Drama|Romance,Edmund Goulding,NaN,"Jan 1, 1946","May 24, 2005",NaN,NaN,146 minutes,NaN
415,544,Charlie Chan (Sidney Toler) lumbers through an...,NR,Classics|Drama|Mystery and Suspense,Phil Karlson,NaN,"Sep 29, 1945","Jul 6, 2004",NaN,NaN,64 minutes,NaN
441,580,"In this western, John Wayne stars as Rocklin, ...",NR,Classics|Western|Romance,NaN,Paul Fix,"Sep 29, 1944","May 3, 2005",NaN,NaN,79 minutes,NaN
456,598,"In this slick melodrama, a sort of film-noir f...",NR,Classics|Drama|Mystery and Suspense,Vincent Sherman,NaN,"Feb 22, 1947","Jul 7, 2009",NaN,NaN,111 minutes,NaN
465,609,"In this brooding WW II-era mystery, a Nazi age...",NR,Classics|Drama|Mystery and Suspense,Anatole Litvak,Paul Dehn|Joseph Kessel,"Feb 2, 1967","May 1, 2007",NaN,NaN,144 minutes,NaN
469,613,Casbah is a musical remake of the 1938 film Al...,NR,Classics|Musical and Performing Arts,John Berry,Leslie Bush-Fekete,NaN,NaN,NaN,NaN,94 minutes,NaN
478,624,An ex-husband and wife team star in a musical ...,NR,Classics|Comedy|Musical and Performing Arts,George Sidney,Dorothy Kingsley|Bella Spewack|Sam Spewack,"Nov 26, 1953","Apr 22, 2003",NaN,NaN,110 minutes,NaN
489,640,Parole officer Griff Marat (Cornel Wilde) is l...,NR,Classics|Drama|Mystery and Suspense,Douglas Sirk,Helen Deutsch|Samuel Fuller,"Jan 1, 1949","Oct 27, 2009",NaN,NaN,79 minutes,NaN
491,642,"Cary Grant stars as Alec Walker, a man whose w...",NR,Classics|Drama|Romance,John Cromwell,Richard Sherman,NaN,NaN,NaN,NaN,102 minutes,NaN
528,690,"Six days a week, a man is a model husband, but...",NR,Classics|Comedy|Romance,Robert Ellis Miller,NaN,NaN,NaN,NaN,NaN,109 minutes,NaN
551,720,"In this Vegas-set crime comedy, a petty crook ...",NR,Classics|Comedy,William Castle,Ben Starr,"Mar 12, 1967","Jul 22, 2008",NaN,NaN,101 minutes,NaN
577,747,"Widely regarded as a comedy in 1960, The Apart...",NR,Classics|Comedy|Drama|Romance,Billy Wilder,NaN,"Jun 15, 1960","Jun 19, 2001",NaN,NaN,125 minutes,NaN
591,763,In Old Chicago was 20th Century-Fox's spin on ...,NR,Classics|Drama|Mystery and Suspense,Henry King,Niven Busch|Sonya Levien|Lamar Trotti,"Jan 1, 1937","Aug 9, 2005",NaN,NaN,110 minutes,NaN
596,770,Henry Koster directed this cloying family musi...,NR,Classics|Comedy|Drama|Musical and Performing Arts,Henry Koster,NaN,"Apr 2, 1966","Sep 12, 2011",NaN,NaN,98 minutes,NaN
608,785,The Opposite Sex is an opulent musical remake ...,NR,Classics|Comedy|Musical and Performing Arts|Ro...,David Miller,Fay Kanin|Michael Kanin,"Oct 26, 1956","Jan 30, 1991",NaN,NaN,117 minutes,NaN
642,826,"Stanley Kubrick's second film, Killer's Kiss w...",NR,Classics|Drama|Mystery and Suspense,Stanley Kubrick,NaN,"Sep 28, 1955","May 15, 2001",NaN,NaN,67 minutes,NaN
656,840,"Wrongfully convicted for a hold-up, a war vet ...",NR,Classics|Drama|Mystery and Suspense,Mervyn Le Roy,Sheridan Gibney|Brown Holmes,"Nov 19, 1932","May 10, 2005",NaN,NaN,90 minutes,NaN
661,847,"In this Alfred Hitchcock film, Derrick De Marn...",NR,Classics|Drama|Mystery and Suspense,Alfred Hitchcock,Alma Reville|Charles Bennett|Gerald Savory|Edw...,"Feb 17, 1938","Jul 30, 2002",NaN,NaN,80 minutes,NaN
673,861,A traveling vending-machine salesman begins a ...,R,Drama|Mystery and Suspense|Romance,Steve Kloves,Steve Kloves,"Nov 5, 1993","Apr 16, 2002",NaN,NaN,126 minutes,NaN
700,898,To quell the rumors that musical stars Alice F...,NR,Classics|Drama|Musical and Performing Arts|Rom...,Walter Lang,Robert Ellis|Helen Logan,"Nov 22, 1940","Jul 19, 1994",NaN,NaN,94 minutes,NaN
714,918,Max Shulman and Robert Paul Smith's Broadway h...,NR,Classics|Comedy|Musical and Performing Arts|Ro...,Charles Walters,NaN,"Jan 1, 1955","May 13, 2008",NaN,NaN,111 minutes,NaN
722,928,Cecil B. DeMille's The Greatest Show on Earth ...,NR,Classics|Drama|Kids and Family|Romance,NaN,NaN,"Feb 21, 1952","Apr 6, 2004",NaN,NaN,92 minutes,NaN
727,934,A young man is in danger of losing his inherit...,NR,Classics|Mystery and Suspense,NaN,John Krafft,"Oct 28, 1936","Mar 15, 2005",NaN,NaN,70 minutes,NaN
735,944,The producers of Quartet and Trio concluded th...,NR,Classics|Comedy|Drama,Harold French|Pat Jackson|Anthony Pelissier,NaN,NaN,NaN,NaN,NaN,85 minutes,NaN
742,957,"J.J. Hunsecker, a powerful New York newspaper ...",NR,Classics|Drama,Alexander Mackendrick,Clifford Odets|Ernest Lehman,"Jun 27, 1957","Jun 19, 2001",NaN,NaN,96 minutes,NaN

In [85]:
movie_buddget.iloc[[236,238,263,265,268,290,312,320,393,415,441,456,465,469,478,489,491,528,551,577,591,
                   596,608,642,656,661,673,700,714,722,727,735,742]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
236,37,"Nov 26, 2014",Penguins of Madagascar,"$132,000,000","$83,350,911","$366,942,531"
238,39,"Jun 4, 2004",Harry Potter and the Prisoner of Azkaban,"$130,000,000","$249,757,726","$796,907,323"
263,64,"Nov 19, 2010",Harry Potter and the Deathly Hallows: Part I,"$125,000,000","$296,131,568","$960,431,568"
265,66,"May 2, 2003",X-Men 2,"$125,000,000","$214,949,694","$406,875,536"
268,69,"Dec 16, 2011",Sherlock Holmes: A Game of Shadows,"$125,000,000","$186,848,418","$535,663,443"
290,91,"Jun 27, 2003",Charlie's Angels: Full Throttle,"$120,000,000","$100,814,328","$227,200,000"
312,13,"Dec 25, 2010",Gulliver's Travels,"$112,000,000","$42,779,261","$232,017,848"
320,21,"Jun 27, 2007",Live Free or Die Hard,"$110,000,000","$134,529,403","$382,288,147"
393,94,"Mar 15, 2019",Wonder Park,"$100,000,000","$45,216,793","$115,149,422"
415,16,"May 27, 2010",Sex and the City 2,"$95,000,000","$95,347,692","$294,680,778"
441,42,"Dec 25, 2009",Sherlock Holmes,"$90,000,000","$209,028,679","$498,438,212"
456,57,"Jun 8, 2001",Atlantis: The Lost Empire,"$90,000,000","$84,052,762","$186,049,020"
465,66,"Jun 10, 2016",Now You See Me 2,"$90,000,000","$65,075,540","$328,325,007"
469,70,"Mar 16, 2018",Tomb Raider,"$90,000,000","$58,250,803","$273,477,501"
478,79,"Nov 24, 2010",The Nutcracker in 3D,"$90,000,000","$195,459","$20,466,016"
489,90,"Dec 7, 2001",Ocean's Eleven,"$85,000,000","$183,417,150","$450,728,529"
491,92,"Jul 25, 1997",Air Force One,"$85,000,000","$172,956,409","$315,268,353"
528,29,"Jun 23, 2006",Click,"$82,500,000","$137,355,633","$237,685,089"
551,52,"Feb 19, 2010",Shutter Island,"$80,000,000","$128,012,934","$299,461,782"
577,78,"Apr 3, 1998",Lost In Space,"$80,000,000","$69,117,629","$136,047,317"
591,92,"Apr 14, 2006",The Wild,"$80,000,000","$37,384,046","$99,010,667"
596,97,"Feb 21, 2014",Pompeii,"$80,000,000","$23,169,033","$108,469,033"
608,9,"Jun 15, 1994",The Lion King,"$79,300,000","$421,785,283","$986,214,868"
642,43,"Aug 3, 2018",Christopher Robin,"$75,000,000","$99,215,042","$197,504,758"
656,57,"Jul 21, 2006",Lady in the Water,"$75,000,000","$42,285,169","$72,785,169"
661,62,"Mar 25, 2011",Sucker Punch,"$75,000,000","$36,392,502","$89,758,389"
673,74,"Feb 6, 2015",The SpongeBob Movie: Sponge Out of Water,"$74,000,000","$162,994,032","$311,013,181"
700,1,"Aug 21, 2009",Inglourious Basterds,"$70,000,000","$120,774,594","$316,915,264"
714,15,"Sep 23, 2016",Storks,"$70,000,000","$72,679,278","$183,353,431"
722,23,"Aug 9, 1989",The Abyss,"$70,000,000","$54,243,125","$54,243,125"
727,28,"Aug 10, 2007",Stardust,"$70,000,000","$38,634,938","$137,022,245"
735,36,"Jan 29, 2016",The Finest Hours,"$70,000,000","$27,569,558","$49,252,761"
742,43,"Apr 27, 2007",Next,"$70,000,000","$18,211,013","$73,591,500"

In [14]:
# new names index for NR
no3=[236,238,263,265,268,290,312,320,393,415,441,456,465,469,489,491,528,551,577,591,
                   596,608,642,656,661,673]

In [63]:
# making sure all system_rating have the same amout of records
# getting system G: need 37
index_G = movie_info[movie_info['rating']=='G'].index
index_G[50:100]

Int64Index([1441, 1450, 1522, 1528, 1540, 1544, 1557], dtype='int64')

Based on the indexes on the 'G' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was G-rated. The 37 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [1]:
#checking if the names are already in dataframe
for i in name_movies:
    if i == 'The Prince and the Pauper':
        print('yes')

NameError: name 'name_movies' is not defined

In [4]:
#informtions on the movies needed for g
# the name of the movies
name_mojo3 = ['Cars','The Secret World of Arrietty','My Neighbor Totoro','A Little Princess','The Cat Returns',
             'The Black Stallion','The Land Before Time','Hercules','The Absent-Minded Professor','Peter Pan 1953',
             'The Rookie 2002','Monsters, Inc','Kiki\'s Delivery Service','The Great Muppet Caper','The Last Unicorn',
             'The Rescuers','Whisper of the Heart','Yellow Submarine (film)','The Straight Story','The Italian Job',
             'Fantasia','2001: A Space Odyssey','Oliver! (film)','The King and I','Alice in Wonderland 1951',
             'Charlotte\'s Web','The Princess and the Frog','Aladdin 1992','Sleeping Beauty','Beauty and the Beast',
             'The Great Mouse Detective','The Prince and the Pauper (1937 film)','Pinocchio','Bambi','Snow White and the Seven Dwarfs',
              'Mulan 1998']
# ratings of the movies
rating_mojo3 = [7.1,7.6,8.2,7.7,7.2,7.3,7.4,7.3,6.8,7.3,6.9,8.1,7.8,7.2,7.5,6.9,7.9,7.4,8,7.3,7.7,8.3,7.4,0,7.4,4.2,7.1,8,7.2,7.1
                ,7.2,7.2,6.2,7.3,7.6,7.6]
# worldwide gross
worldwide_gross_mojo3 = ['$611,456,294','$148,800,274','$136,417,551','$17,426,613','$80,346,959','$698,285,405',
                        '$190,639,986','$244,819,862','$221,852,235','$852,683,111','$118,950,584','$791,561,399',
                        '$89,307,708','$94,187,914','$17,887,719','$756,359,209','$114,572,756','$9,800,760',
                        '$10,196,984','$253,519,633','$1,550,207,885','$505,507,877','$594,710,548','$207,018,514',
                        '$58,346,176','$198,532,012','$267,045,765','$952,175,079','$465,067,764','$856,760,892',
                        '$92,048,961','$31,461,538','$2,267,836,323','$4,503,679,483','$7,777,009,428','$491,429,100']
# domestic gross
domestic_gross_mojo3 = ['$323,055,237','$19,202,743','$5,079,046','$17,426,613','$830,978','$698,285,405',
                        '$108,552,304','$72,688,614','$221,852,235','$852,683,111','$111,442,292','$383,036,373',
                        '$89,307,708','$94,187,914','$17,887,719','$218,295,109','$114,572,756','$7,632,771',
                        '$9,858,033','$152,812,278','$797,236,492','$464,134,940','$409,374,884','$116,562,319',
                        '$58,346,176','$109,835,463','$104,400,899','$410,544,459','$328,790,336','$283,958,248',
                        '$60,380,385','$31,461,538','$1,567,572,849','$1,727,480,372','$3,440,591,502','$194,782,641']
# product budget
product_budget_mojo3 = ['$158,825,609','$120,000,000','$8,351,419','$29,579,545','$29,482,059','$49,878,000',
                        '$27,762,826','$100,000,000','$17,481,476','$39,022,322','$32,430,265','$172,152,356',
                        '$166,152,270','$42,255,341','$9,698,500','$5,370,597','$30,433,388','$2,625,355',
                        '$15,892,251','$86,392,703','$42,420,051','$80,677,787','$76,835,988','$44,222,264',
                        '$31,256,880','$112,501,473','$105,000,000','$52,888,121','$54,077,647','$38,934,828',
                        '$33,363,549','$15,963,335','$48,373,742','$14,418,496','$27,684,665','$145,335,771']

In [77]:
# making sure all system_rating have the same amout of records
# getting the index of  system R: need 24
index_PG13 = movie_info[movie_info['rating']=='R'].index
index_PG13[550:600]

Int64Index([], dtype='int64')

Based on the indexes on the 'R' genre there wasn't enough movies in this specific category needed to get the amount needed.

The data set did not have enough movies in the Classic genre that was R-rated. The 24 movies needed were from Box Office Mojo.

After making sure all the movies missed are gotten, it is stored in multiple avairables used later on and added back to the dataframe. This is being repeted through out the next few coding script.

In [79]:
#informtions on the movies needed for r
# the name of the movies
name_mojo4 = []
# ratings of the movies
rating_mojo4 = []
# worldwide gross
worldwide_gross_mojo4 = []
# domestic gross
domestic_gross_mojo4 = []
# product budget
product_budget_mojo4 = []

In [107]:
# getting system R name 
names=[]
for i in name_mojo4:
    names.append(name_mojo1)
names

['Megamind',
 'The Twilight Saga: Breaking Dawn, Part 1',
 'The Day After Tomorrow',
 'Jason Bourne',
 'Life of Pi',
 'Venom',
 'Windtalkers',
 'Ferdinand',
 "Ocean's Twelve",
 'Around the World in 80 Days',
 'Kingsman: The Golden Circle',
 'Bumblebee',
 'Little Fockers',
 'Epic',
 'End of Days',
 'Starship Troopers',
 'Point Break',
 'The Peanuts Movie',
 'Unstoppable',
 'Ben-Hur',
 'Die Hard: With a Vengeance',
 'Lara Croft: Tomb Raider: The Cradle of Life',
 'Cinderella Man',
 'Cast Away']

In [15]:
# getting system PG name:need 35
names1=[]
for i in no1:
    names1.append(movie_buddget.movie[i])
names1[:8]

['AVP: Alien Vs. Predator',
 'The Legend of Hercules',
 'Elektra',
 'Daddy Day Care',
 'Beyond Borders',
 'Zero Dark Thirty',
 'Taken 2',
 'Journey to the Center of the Earth']

In [ ]:
# getting system PG name:need 25
names1=[]
for i in name_mojo2:
    names1.append(name_mojo2)
names1[:8]

In [109]:
# getting system PG-13 name:need 24
names2=[]
for i in name_mojo1:
    names2.append(name_mojo1)
names2[:8]

['Moana',
 'The Matrix Revolutions',
 'Salt',
 'The Hunger Games: Mockingjay - Part 1',
 'The Bourne Legacy',
 'Fantastic Four: Rise of the Silver Surfer',
 'The Patriot',
 'Miss Peregrineâ\x80\x99s Home for Peculiar Children']

In [17]:
# getting system NR name:need 26
names4=[]
for i in no3:
    names4.append(movie_buddget.movie[i])
names4[:9]

['Penguins of Madagascar',
 'Harry Potter and the Prisoner of Azkaban',
 'Harry Potter and the Deathly Hallows: Part I',
 'X-Men 2',
 'Sherlock Holmes: A Game of Shadows',
 "Charlie's Angels: Full Throttle",
 "Gulliver's Travels",
 'Live Free or Die Hard',
 'Wonder Park']

In [ ]:
# getting system G name:need 37
names3=[]
for i in name_mojo3:
    names3.append(name_mojo3)
names3[:8]

Now that all the new indexs has been idnetified they will be added to the new dataframe needed to create the five interactive graphs.

In [114]:
# add new 'R' names to the original
for i in names:
    name_movies.append(i)
len(name_movies)

77

In [18]:
# add new 'PG' names to the original
for i in names1:
    name_movies.append(i)
len(name_movies)

63

In [116]:
# add new 'PG-13' names to the original
for i in names2:
    name_movies.append(i)
len(name_movies)

147

In [117]:
# add new 'G' names to the original
for i in names3:
    name_movies.append(i)
len(name_movies)

173

In [19]:
# add new 'NR' names to the original
for i in names4:
    name_movies.append(i)
len(name_movies)

89

Now that the names have been updated with the new indexes, we use it to get the rest of the key components from the original dataframe to add to the new dataframe.

In [118]:
#getting the index of the names to get other info from dataframe
index = []
for i in name_movies:
    index.append(list(movie_buddget[movie_buddget['movie']==i].index))
len(index)

173

In [119]:
#checking index to see integers that are not needed
index

[[12],
 [20],
 [30],
 [53],
 [73],
 [87],
 [95],
 [110],
 [116],
 [121],
 [130],
 [132],
 [138],
 [147],
 [152],
 [160],
 [162],
 [165],
 [168],
 [177],
 [181],
 [190],
 [195],
 [208],
 [218],
 [222],
 [233],
 [235],
 [259],
 [261],
 [264],
 [272],
 [286],
 [290],
 [294],
 [297, 484],
 [308],
 [316],
 [332],
 [389],
 [400],
 [404],
 [411],
 [412, 4775],
 [413],
 [437],
 [452],
 [461],
 [465],
 [466],
 [474],
 [485],
 [487],
 [246],
 [256],
 [269],
 [285],
 [287],
 [302, 2313],
 [310],
 [313],
 [322],
 [340, 4120],
 [353],
 [361],
 [369],
 [376],
 [385],
 [390],
 [399, 2340],
 [406],
 [418],
 [422, 3007],
 [453],
 [464],
 [482],
 [487],
 [114],
 [120],
 [127],
 [173],
 [182],
 [243, 3455, 5459],
 [296],
 [344],
 [378],
 [382],
 [389],
 [426],
 [439],
 [455],
 [474],
 [504],
 [505],
 [511],
 [531],
 [575],
 [601],
 [640],
 [682],
 [694],
 [695],
 [278, 779],
 [784],
 [813],
 [818],
 [847],
 [853],
 [869],
 [887],
 [957],
 [962],
 [986],
 [161],
 [176],
 [249],
 [261],
 [275],
 [286],
 [324],
 [329],
 [351],
 [358],
 [384],
 [424],
 [430],
 [434, 3409],
 [437],
 [442],
 [462],
 [492],
 [495],
 [499],
 [574],
 [597],
 [631],
 [674],
 [690],
 [736],
 [757],
 [781],
 [804],
 [838],
 [879],
 [884],
 [889],
 [926],
 [563],
 [628],
 [647],
 [678],
 [711],
 [720],
 [770],
 [772],
 [773],
 [819],
 [866],
 [873],
 [886],
 [937],
 [959],
 [963],
 [992],
 [1042],
 [1043],
 [1093],
 [1116],
 [1148],
 [1211],
 [1244],
 [1288],
 [1358]]

In [120]:
#Turning nested list to regular list
from funcy import flatten,isa
flat_list = flatten(index)

In [121]:
#converting list of list into int 
newflat_list = []
for i in flat_list:
    i=int(i)
    newflat_list.append(i)

In [122]:
# removing integers that are not needed
newflat_list1 = []
for i in newflat_list:
    if i == 484:continue
    if i == 4775:continue
    if i == 2313:continue
    if i == 4120:continue
    if i == 2340:continue
    if i == 3007:continue
    if i == 3455:continue
    if i == 5459:continue
    if i == 779:continue
    if i == 3409:continue
    
    else: newflat_list1.append(i)

In [123]:
len(newflat_list1)

173

In [124]:
#using the updated indexes to get the new and old product budgets
product_budget = []
for x in newflat_list1:
    product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

173

In [125]:
# using the updated indexes to get the new and old ratings
rating = []
for x in newflat_list1:
    rating.append(ratings.averagerating[x])
len(rating)

173

In [126]:
#using the updated indexes to get thenew and old system ratings
system_rating = []
for x in newflat_list1:
    system_rating.append(movie_info.rating[x])
len(system_rating)

173

In [127]:
# all system ratings have the same amout of records 42 except for 'G' system rating
# 'G' rating needs 23 movies 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'NR': 42, 'G': 5, 'R': 42, 'PG-13': 42, 'PG': 42})

In [33]:
# adding names from mojo to the original
for i in name_mojo:
    name_movies.append(i)
len(name_movies)

210

In [34]:
g = 'G'*23
g= list(g)
for i in g:
    system_rating.append(i)
len(system_rating)

210

In [35]:
# adding rating from mojo to the original
for i in rating_mojo:
    rating.append(i)
len(rating)

210

In [36]:
# adding product budget from mojo to the original
for i in product_budget_mojo:
    product_budget.append(i)
len(product_budget)

210

In [37]:
#using the updated indexes to get the new and old domestic gross
domestic_gross = []
for x in newflat_list1:
    domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

187

In [38]:
# adding product budget from mojo to the original
for i in domestic_gross_mojo:
    domestic_gross.append(i)
len(domestic_gross)

210

In [39]:
### using the updated indexes to get the new and old worldwide gross
worldwide_gross = []
for x in newflat_list1:
    worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

187

In [40]:
# adding product budget from mojo to the original
for i in worldwide_gross_mojo:
    worldwide_gross.append(i)
len(worldwide_gross)

210

In [128]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'R': 42, 'PG-13': 42, 'PG': 42, 'G': 42, 'NR': 42})

All the information have been gathered, the script below uses it to create a new and updated dataframe.

In [41]:
all_actionadventure_info = pd.DataFrame({'Name':name_movies,'System_ratings':system_rating,'Rating':rating,'Worlwide_gross':worldwide_gross,
                               'Domestic_gross':domestic_gross,'Product_budget':product_budget})
all_actionadventure_info1=all_actionadventure_info.dropna()
all_actionadventure_info1 = all_actionadventure_info[all_actionadventure_info.Name !='Moonfall']

Now that the dataframe has been updated, Worldwide Gross, Product Budget and Domestic Gross has to be converted from string to int.

In [42]:
# turning Worldwide gross into int
storage1 = []
storage2 = []
total_gross=[]
for i in  all_actionadventure_info1.dropna().Worlwide_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    total_gross.append(i)
len(total_gross)

210

In [43]:
# turning Produt budget  into int
storage1 = []
storage2 = []
budget=[]
for i in  all_actionadventure_info1.dropna().Product_budget:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    budget.append(i)
len(budget)

210

In [44]:
# turning Domestic gross into int
storage1 = []
storage2 = []
Doomestic_gross=[]
for i in  all_actionadventure_info1.dropna().Domestic_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    Doomestic_gross.append(i)
len(Doomestic_gross)

210

In [45]:
#drop all the NA from the dataframe
all_actionadventure_info1 = all_actionadventure_info1.dropna()


#adding all the string componnets that have been converted to dataframe
all_actionadventure_info1['Buget']=budget
all_actionadventure_info1['Total_gross']=total_gross
all_actionadventure_info1['Domestic_total']=Doomestic_gross
all_actionadventure_info1[190:]

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total
190,The Tale of Despereaux,G,6.1,"$86,957,280","$50,877,145","$60,000,000",60000000,86957280,50877145
191,Monsters University,G,7.3,"$743,539,607","$268,492,764","$200,000,000",200000000,743539607,268492764
192,Herbie: Fully Loaded,G,4.8,"$144,146,816","$66,023,816","$50,000,000",50000000,144146816,66023816
193,Wallace & Gomit: The Curse of the Were-Rabbit,G,7.4,"$194,111,171","$56,110,897","$30,000,000",30000000,194111171,56110897
194,A Boy's Life,G,7.3,"$424,600,00","$204,400,000","$90,000,000",90000000,42460000,204400000
195,Ozzy,G,5.2,"$12,852,439",$0,"$10,000,000",10000000,12852439,0
196,Ponyo,G,7.7,"$202,551,810","$15,090,399","$34,000,000",34000000,202551810,15090399
197,Gnomeo & Juliet,G,6.9,"$193,900,000","$94,000,000","$36,000,000",36000000,193900000,94000000
198,Yellow Submarine,G,7.4,"$1,278,261","$992,303","$250,000",250000,1278261,992303
199,Curious George 1,G,6.5,"$69,800,000","$58,400,000","$50,000,000",50000000,69800000,58400000
200,Fantastica: A Boonie Bears,G,6.4,"$77,151,096","$76,630,780","$90,000,000",90000000,77151096,76630780
201,Ice Age 2: The Meltdown,G,6.8,"$660,998,756","$195,336,621","$80,000,00",8000000,660998756,195336621
202,The Fox and the Child,G,8.0,"$29,610,210","$29,610,210","$13,000,000",13000000,29610210,29610210
203,Space Chimps,G,4.5,"$65,097,693","$30,105,968","$37,000,000",37000000,65097693,30105968
204,The Oegieloves,G,2.1,"$1,065,907","$1,065,907","$20,000,000",20000000,1065907,1065907
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164

In [46]:
# getting profit
profit = []
for x,y in enumerate(total_gross):
    profit.append(y-budget[x])
len(profit)

210

In [47]:
all_actionadventure_info1['Profit']=profit

In [48]:
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit
0,Avatar,R,8.3,"$2,776,345,279","$760,507,625","$425,000,000",425000000,2776345279,760507625,2351345279
1,Spectre,PG-13,4.2,"$879,620,923","$200,074,175","$300,000,000",300000000,879620923,200074175,579620923
2,Captain America: Civil War,R,7.6,"$1,140,069,413","$408,084,349","$250,000,000",250000000,1140069413,408084349,890069413
3,Batman v Superman: Dawn of Justice,PG,6.5,"$867,500,281","$330,360,194","$250,000,000",250000000,867500281,330360194,617500281
4,The Hobbit: The Battle of the Five Armies,G,6.6,"$945,577,621","$255,119,788","$250,000,000",250000000,945577621,255119788,695577621
...,...,...,...,...,...,...,...,...,...,...
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277,204397798
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354,3182426
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891,32172482
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665,164432837
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164,341311860

In [49]:
# Creating Box office column
# dividing total gross by the avg price of tickets, to get an estimsted number of tickes sold
no_tickets = []
for i in all_actionadventure_info1.Total_gross:
    no_tickets.append(round(i/13)) 
no_tickets[:10]

[213565021,
 67663148,
 87697647,
 66730791,
 72736740,
 94988174,
 28775774,
 32103176,
 50324114,
 64347669]

In [50]:
# converting integer of no. of tickets into string
tickets_string = []
for i in no_tickets:
    tickets_string.append("{:,.0f}".format(i))
len(tickets_string)

210

In [51]:
# converting integer of profit to currency
currency = []
for i in all_actionadventure_info1.Profit:
    currency.append("${:,.0f}".format(i))
len(currency)

210

In [52]:
all_actionadventure_info1['No.Tickets']=tickets_string
all_actionadventure_info1['Profit$']= currency
all_actionadventure_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit,No.Tickets,Profit$
0,Avatar,R,8.3,"$2,776,345,279","$760,507,625","$425,000,000",425000000,2776345279,760507625,2351345279,"213,565,021","$2,351,345,279"
1,Spectre,PG-13,4.2,"$879,620,923","$200,074,175","$300,000,000",300000000,879620923,200074175,579620923,"67,663,148","$579,620,923"
2,Captain America: Civil War,R,7.6,"$1,140,069,413","$408,084,349","$250,000,000",250000000,1140069413,408084349,890069413,"87,697,647","$890,069,413"
3,Batman v Superman: Dawn of Justice,PG,6.5,"$867,500,281","$330,360,194","$250,000,000",250000000,867500281,330360194,617500281,"66,730,791","$617,500,281"
4,The Hobbit: The Battle of the Five Armies,G,6.6,"$945,577,621","$255,119,788","$250,000,000",250000000,945577621,255119788,695577621,"72,736,740","$695,577,621"
...,...,...,...,...,...,...,...,...,...,...,...,...
205,Brother Bears 1,G,6.8,"$250,397,798","$85,336,277","$46,000,000",46000000,250397798,85336277,204397798,"19,261,369","$204,397,798"
206,Cliffords,G,5.4,"$3,252,426","$2,922,354","$70,000",70000,3252426,2922354,3182426,"250,187","$3,182,426"
207,The Wizard of Oz,G,8.0,"$34,949,482","$34,685,891","$2,777,000",2777000,34949482,34685891,32172482,"2,688,422","$32,172,482"
208,Chicken Little,G,5.7,"$314,432,837","$135,386,665","$150,000,000",150000000,314432837,135386665,164432837,"24,187,141","$164,432,837"
209,Wall-E,G,8.4,"$521,311,860","$223,808,164","$180,000,000",180000000,521311860,223808164,341311860,"40,100,912","$341,311,860"

After the dataframe has been updated, bokeh is being installed.

In [53]:
from bokeh.layouts import gridplot,row
from bokeh.plotting import figure,output_file,ColumnDataSource
from bokeh.io import push_notebook,show,output_notebook
from bokeh.models import NumeralTickFormatter
output_notebook()

Bokeh is successfully installed, now the key componets need to be creted for each system rating group to make the graphs.

A reminder of the componets;
 - Cost
 - Proft
 - Name
 - Profit Percntage by Cost
 - Type of System Rating

In [54]:
# index of all 'R' system ratings
index_r = []
for i,x in enumerate(system_rating):
    if x == 'R':index_r.append(i)

In [55]:
# getiing the profit for all 'R' system rating
r_profit = []
for i in index_r:
    r_profit.append(all_actionadventure_info1.Profit[i])
len(r_profit)

42

In [56]:
# getting the cost for 'R' system rating
cost1 = []
for i in index_r:
    cost1.append(all_actionadventure_info1.Product_budget[i])
len(cost1)

42

In [57]:
# getiing the name for all 'R' system rating
r_name = []
for i in index_r:
    r_name.append(all_actionadventure_info1.Name[i])
len(r_name)

42

In [58]:
# getiing the $profit for all 'R' system rating
r_dollar = []
for i in index_r:
    r_dollar.append(all_actionadventure_info1['Profit$'][i])
len(r_dollar)

42

In [59]:
# getiing the system rating for all 'R' system rating
r_sratings = []
for i in index_r:
    r_sratings.append(all_actionadventure_info1.System_ratings[i])
len(r_sratings)

42

In [60]:
# getting percentage profit for all 'R' system rating
percent_profit = []
for i in index_r:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit.append(round(i,0))
len(percent_profit)

42

In [61]:
# turning float of percentage of profit into int for 'R' system rating
pp = []
for i in percent_profit:
    i = int(i)
    pp.append(i)
len(pp)

42

In [62]:
# converting integer to percentage for 'R' system rating
percentage_profit = []
for i in pp:
    percentage_profit.append("{:}%".format(i))
len(percentage_profit)

42

In [63]:
# index of all 'G' system ratings
index_g = []
for i,x in enumerate(system_rating):
    if x == 'G':index_g.append(i)

In [64]:
# getiing the profit for all 'G' system rating
g_profit = []
for i in index_g:
    g_profit.append(all_actionadventure_info1.Profit[i])
len(g_profit)

42

In [65]:
# getting the cost for 'G' system rating
cost2 = []
for i in index_g:
    cost2.append(all_actionadventure_info1.Product_budget[i])
len(cost2)

42

In [66]:
# getiing the name for all 'G' system rating
g_name = []
for i in index_g:
    g_name.append(all_actionadventure_info1.Name[i])
len(g_name)

42

In [67]:
# getiing the $profit for all 'G' system rating
g_dollar = []
for i in index_g:
    g_dollar.append(all_actionadventure_info1['Profit$'][i])
len(g_dollar)

42

In [68]:
# getiing the system rating for all 'G' system rating
g_sratings = []
for i in index_g:
    g_sratings.append(all_actionadventure_info1.System_ratings[i])
len(g_sratings)

42

In [69]:
# getting percentage profit for all 'G' system rating
percent_profit1 = []
for i in index_g:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit1.append(round(i,0))
len(percent_profit1)

42

In [70]:
# turning float of percentage of profit into int for 'G' system rating
pp1= []
for i in percent_profit1:
    i = int(i)
    pp1.append(i)
len(pp1)

42

In [71]:
# converting integer to percentage for 'G' system rating
percentage_profit1 = []
for i in pp1:
    percentage_profit1.append("{:}%".format(i))
len(percentage_profit1)

42

In [72]:
# index of all 'PG' system ratings
index_pg = []
for i,x in enumerate(system_rating):
    if x == 'PG':index_pg.append(i)

In [73]:
# getiing the profit for all 'PG' system rating
pg_profit = []
for i in index_pg:
    pg_profit.append(all_actionadventure_info1.Profit[i])
len(pg_profit)

42

In [74]:
# getting the cost for 'PG' system rating
cost3 = []
for i in index_pg:
    cost3.append(all_actionadventure_info1.Product_budget[i])
len(cost3)

42

In [75]:
# getiing the name for all 'PG' system rating
pg_name = []
for i in index_pg:
    pg_name.append(all_actionadventure_info1.Name[i])
len(pg_name)

42

In [76]:
# getiing the $profit for all 'PG' system rating
pg_dollar = []
for i in index_pg:
    pg_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg_dollar)

42

In [77]:
# getiing the system rating for all 'PG' system rating
pg_sratings = []
for i in index_pg:
    pg_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg_sratings)

42

In [78]:
# getting percentage profit for all 'PG' system rating
percent_profit2 = []
for i in index_pg:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit2.append(round(i,0))
len(percent_profit2)

42

In [79]:
# turning float of percentage of profit into int for 'PG' system rating
pp2= []
for i in percent_profit2:
    i = int(i)
    pp2.append(i)
len(pp2)

42

In [80]:
# converting integer to percentage for 'PG' system rating
percentage_profit2= []
for i in pp2:
    percentage_profit2.append("{:}%".format(i))
len(percentage_profit2)

42

In [81]:
# index of all 'PG-13' system ratings
index_pg13 = []
for i,x in enumerate(system_rating):
    if x == 'PG-13':index_pg13.append(i)

In [82]:
# getiing the profit for all 'PG-13' system rating
pg13_profit = []
for i in index_pg13:
    pg13_profit.append(all_actionadventure_info1.Profit[i])
len(pg13_profit)

42

In [83]:
# getiing the name for all 'PG-13' system rating
pg13_name = []
for i in index_pg13:
    pg13_name.append(all_actionadventure_info1.Name[i])
len(pg13_name)

42

In [84]:
# getting the cost for 'PG-13' system rating
cost4 = []
for i in index_pg13:
    cost4.append(all_actionadventure_info1.Product_budget[i])
len(cost4)

42

In [85]:
# getiing the $profit for all 'PG-13' system rating
pg13_dollar = []
for i in index_pg13:
    pg13_dollar.append(all_actionadventure_info1['Profit$'][i])
len(pg13_dollar)

42

In [86]:
# getiing the system rating for all 'PG-13' system rating
pg13_sratings = []
for i in index_pg13:
    pg13_sratings.append(all_actionadventure_info1.System_ratings[i])
len(pg13_sratings)

42

In [87]:
# getting percentage profit for all 'PG-13' system rating
percent_profit3 = []
for i in index_pg13:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit3.append(round(i,0))
len(percent_profit3)

42

In [88]:
# turning float of percentage of profit into int
pp3= []
for i in percent_profit3:
    i = int(i)
    pp3.append(i)
len(pp3)

42

In [89]:
# converting integer to percentage
percentage_profit3= []
for i in pp3:
    percentage_profit3.append("{:}%".format(i))
len(percentage_profit3)

42

In [90]:
# index of all 'NR' system ratings
index_NR = []
for i,x in enumerate(system_rating):
    if x == 'NR':index_NR.append(i)

In [91]:
# getiing the profit for all 'NR' system rating
NR_profit = []
for i in index_NR:
    NR_profit.append(all_actionadventure_info1.Profit[i])
len(NR_profit)

42

In [92]:
# getiing the name for all 'NR' system rating
nr_name = []
for i in index_NR:
    nr_name.append(all_actionadventure_info1.Name[i])
len(nr_name)

42

In [93]:
# getting the cost for 'NR' system rating
cost5 = []
for i in index_NR:
    cost5.append(all_actionadventure_info1.Product_budget[i])
len(cost5)

42

In [94]:
# getiing the $profit for all 'NR' system rating
nr_dollar = []
for i in index_NR:
    nr_dollar.append(all_actionadventure_info1['Profit$'][i])
len(nr_dollar)

42

In [95]:
# getiing the system rating for all 'NR' system rating
nr_sratings = []
for i in index_NR:
    nr_sratings.append(all_actionadventure_info1.System_ratings[i])
len(nr_sratings)

42

In [96]:
# getting percentage profit for all 'NR' system rating
percent_profit4 = []
for i in index_NR:
    i = (all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Buget[i])*100
    percent_profit4.append(round(i,0))
len(percent_profit4)

42

In [97]:
# turning float of percentage of profit into int for 'NR' system rating
pp4= []
for i in percent_profit4:
    i = int(i)
    pp4.append(i)
len(pp4)

42

In [98]:
# converting integer to percentage for 'NR' system rating
percentage_profit4= []
for i in pp4:
    percentage_profit4.append("{:}%".format(i))
len(percentage_profit4)

42

In [99]:
rangee = list(range(42)) # x-axis range
# allows the garph to hover over the piont to show all information about the pionts  
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,box_select,hover"

# Graph 1
source = ColumnDataSource(data=dict(
    x = rangee, # x-axis
    y = r_profit,# y-axis
    name=r_name, # name of movie
    profit=r_dollar,# profit in currency($)
    system_rating=r_sratings ,# system rating of movie
    percent_profit=percentage_profit,# profit percentage based on cost
    cost1=cost1))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name"),# the name
    ("Cost","@cost1"),# the cost
    ("Profit","@profit"),# the profit
    ("(System-Rating)","@system_rating"),# the system rating
    ("(Profit-Percentage)","@percent_profit")]# the profit percentage
p3 = figure(title='Profit.Drama.System Rating R',tools=TOOLS,plot_height=300,
           plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p3.left[0].formatter.use_scientific=False 
# makes the digits more visible by turning it into millions on the y-axis
p3.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
p3.circle('x','y',color="#054D6B",width=3,source=source)
p3.line('x','y',color="#054D6B",# the style and color of the graph
        line_dash='dashed',line_width=2,source=source)

# Graph 2
source4 = ColumnDataSource(data=dict(
     o=rangee,# x-axis
     e=g_profit,# y-axis
     name1=g_name,# name of movies
     profit1=g_dollar,# profit of movies in curreny($)
     system_rating1=g_sratings,# system rating of movie
     percent_profit1=percentage_profit1,# profit percentage based on cost
     cost2=cost2))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name1"),# the name
    ("Cost","@cost2"),# the cost
    ("Profit","@profit1"),# the profit in dollars
    ("(System-Rating)","@system_rating1"),# the system rating
    ("(Profit-Percentage)","@percent_profit1")]# the profit percentage
p4 = figure(title='Profit.Drama.System Rating G',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p4.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p4.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
# the style and color of the graph
p4.circle(x='o',y='e',color='#05C4FB',width=3,source=source4)
p4.line(x='o',y='e',color='#05C4FB',source=source4)
 
# Graph 3
source1 = ColumnDataSource(data=dict(
       p=rangee,# x-axis
       q=pg_profit,# y-axis
       name2=pg_name,# name of movies
       profit2=pg_dollar,# profit of movies in currency ($)
       system_rating2=pg_sratings,# system rating of moives
       percent_profit2=percentage_profit2,# profit percnetage based on cost
       cost3=cost3))# cost of movies
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name2"),# the name 
    ("Cost","@cost3"),# the cost
    ("Profit","@profit2"),# the profit the dollars
    ("(System-Rating)","@system_rating2"),# the system rating
    ("(Profit-Percentage)","@percent_profit2")]# the profit percentage 
p5 = figure(title='Profit.Drama.System Rating PG',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p5.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p5.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of graph
p5.square(x='p',y='q',line_color='#1215D7',fill_color=None,source=source1)
p5.line(x='p',y='q',line_color='#1215D7',source=source1)

# Graph 4
source2 = ColumnDataSource(data=dict(
       r=rangee,# x-axis
       t=pg13_profit,# y-axis
       name3=pg13_name,# name of movies
       profit3=pg13_dollar,# profit of movies to currency ($)
       system_rating3=pg13_sratings,# system rating of movies
       percent_profit3=percentage_profit3,# profit percentage based on cost
       cost4=cost4))# cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name3"),# the name
    ("Cost","@cost4"),# the cost
    ("Profit","@profit3"),# the profit in dollars
    ("(System-Rating)","@system_rating3"),# the system rating
    ("(Profit-Percentage)","@percent_profit3")]# the profit percentage
p6 = figure(title='Profit.Drama.System Rating PG-13',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
#takes away the scientific notation off the y-axis
p6.left[0].formatter.use_scientific=False
# makes the digits more visible ny turning it into millions on the y-axis
p6.yaxis[0].formatter=NumeralTickFormatter(format='$0.a')
# the style and color of the graph
p6.triangle(x='r',y='t',color='#04B2FB',width=2,source=source2)
p6.line(x='r',y='t',color='#04B2FB',width=2,source=source2)

# Graph 5
source3 = ColumnDataSource(data=dict(
        l=rangee,# x-axis
        i=NR_profit,# y-axis
        name4=nr_name,# name of movies
        profit4=nr_dollar,# profit of movies to currency ($)
        system_rating4=nr_sratings,# system rating of movies
        percent_profit4=percentage_profit4,# profit percentage based on cost
        cost5=cost5))#cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name4"),# the name
    ("Cost","@cost5"),# the cost
    ("Profit","@profit4"),# the profit in dollars
    ("(System-Rating)","@system_rating4"),# the system rating
    ("(Profit-Percentage)","@percent_profit4")]# the profit percentage
p7 = figure(title='Profit.Drama.System Rating NR',tools=TOOLS,
            plot_height=300,plot_width=300,tooltips=TOOLTIPS)
#takes away the scientiifc notation off the y-axis
p7.left[0].formatter.use_scientific=False
#makes the digits more visible by turning it into millions  on the y-axis
p7.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of the graph
p7.circle(x='l',y='i',color='#2889B2',fill_color=None,width=2,source=source3)
p7.line(x='l',y='i',color='#2889B2',width=2,source=source3)

output_file("toolbar.thml")
show(row(p3,p4,p5,p6,p7))# this puts the graphs side by side

# Blueprint: Gross Profit Margin Percentage

This is the blueprint for creating the second visualiztion Gross Profit Margin Percentage, altair will be used to create this graph.

__Blueprint__:
 - 1. Understanding the dataframe format used to create this data visualiztion helps make the process easier, these are the key componets that make up the dataframe used for this graph.
   
    - The data frame that altair used to create this graph consist of four colunms;
     
       - Yield: This colunm is the only colunm that shows any type of informations that is in numbers 
       - Variety: This colunm is the only column that contains category or groupings among the other pionts in the dataframe
       - Year: This colunm is based on datasets that contains timeframes
       - Site: This is a colunm that pinpionts differiantion among the rest of the data pionts
       
 
 - 2. Create five dataframes for five different graphs based on the documented format that is supplied by Altair. 
   
    - The dataframes will consist of these six columns;
      
       - Name: This colunm shows the names of each movie
       - Type: The concept of this graph portrays the profit made compared to the Revenue, the two main elements that reflects that is the Revenue and the Profit ergo the 'Type' column are made up of those two elements.
       - Yield: This colunm shows how much the 'Type' column is in int, this is used to plot the pionts in the graph.
       - Type Yield: This colunm shows the 'Yield' colunm in currency which is a string, this is mostly used for the tooltip to make it easier to understand how much the elements in the 'Type' column is in dollars.
       - System Rating: This shows the System Rating of each movie.
       - Gross Profit Margin: This colunm shows the gross profit margin in percentage.
       
 
 - 3. The style of this graph is a Becker's Barkey Trellis Plot which is found in Altair's Gallery. There are two pionts shaped as a ring in each panel, the first ring projects the Renvue and the other ring projects the Profit, this set up allows the perseption of how much of a fraction do each movie actually walk away with when compared to the Revenue allowing the Profit to be seen from a differnt angle. This could make the movie look more profitable or seem over-rated. Each ring when hovered shows the Name of the movie, the Type choosing beteween Profit or Revenue, the Type Yield which is the amount of the Type in dollars, the Gross Profit Margin Percentage and the System Rating. The closer the Profit is to the Revenue the more buoyant it is!

In [101]:
# understanding how the data frame is formatted
# this was the eact dataframe used in Altairs example
from vega_datasets import data
source = data.barley()
source

        yield           variety  year             site
0    27.00000         Manchuria  1931  University Farm
1    48.86667         Manchuria  1931           Waseca
2    27.43334         Manchuria  1931           Morris
3    39.93333         Manchuria  1931        Crookston
4    32.96667         Manchuria  1931     Grand Rapids
..        ...               ...   ...              ...
115  58.16667  Wisconsin No. 38  1932           Waseca
116  47.16667  Wisconsin No. 38  1932           Morris
117  35.90000  Wisconsin No. 38  1932        Crookston
118  20.66667  Wisconsin No. 38  1932     Grand Rapids
119  29.33333  Wisconsin No. 38  1932           Duluth

[120 rows x 4 columns]

These are the variables needed to create the columns for the first dataframe; new_name,new_systems, new_total_gross, new_worldwide_gross, new_profit, new_currency_profit, gross_profit_margin_percentage.

This is all the names of the movie for the rated-R movies.

In [102]:
new_name=[]
name = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x=='R':
            name.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name):
    new_name.append( x)
len(new_name)

42

This is all the domestic revenue of each movie in the rated-R catagory of movies.

In [103]:
new_total_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_total_gross.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross)

42

This is all the world wide revenue of each movie in the rated-R catagory of movies.

In [104]:
new_worldwide_gross = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_worldwide_gross.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross)

42

This is all the profit in dollars of each movie in the rated-R catagory, this is particularly used for tooltip.

In [105]:
new_currency_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_currency_profit.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit)

42

This is all the profit in int of each mvoie in the rated-R catagory, this is particularly used for the Y and X axis.

In [106]:
new_profit = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='R':
            new_profit.append(all_actionadventure_info1.Profit[i])
len(new_profit)

42

In [107]:
# a list of rated-'r'
new_systems = list('R'*42)
len(new_systems)

42

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [108]:
# Creating the gross profit margin percentage column
p_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        p_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p_rev)

42

In [109]:
# turning float of percentage of profit into int
pp_rev= []
for i in p_rev:
    i = int(i)
    pp_rev.append(round(i,0))
len(pp_rev)

42

In [110]:
# converting integer to percentage
gross_profit_margin_percentage= []
for i in pp_rev:
    gross_profit_margin_percentage.append("{:}%".format(i))
len(gross_profit_margin_percentage)

42

These are the variables needed to create the columns for the second dataframe; new_name1, new_systems1, new_total_gross1, new_worldwide_gross1, new_profit1, new_currency_profit1, gross_profit_margin_percentage1

This is all the names of the movie for the rated-PG movies.

In [111]:
new_name1=[]
name1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            name1.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name1):
    new_name1.append( x)
len(new_name1)

42

This is all the domestic revenue of each movie in the rated-PG catagory of movies.

In [112]:
new_total_gross1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_total_gross1.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross1)

42

This is all the world wide revenue of each movie in the rated-PG catagory of movies.

In [113]:
new_worldwide_gross1= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_worldwide_gross1.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross1)

42

This is all the profit in dollars of each movie in the rated-PG catagory, this is particularly used for tooltip.

In [114]:
new_currency_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_currency_profit1.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit1)

42

This is all the profit in int of each mvoie in the rated-PG catagory, this is particularly used for the Y and X axis.

In [115]:
new_profit1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG':
            new_profit1.append(all_actionadventure_info1.Profit[i])
len(new_profit1)

42

In [116]:
# list of rated-'PG'
new_systems1 = []
for i in list(range(0,42)):
    new_systems1.append('PG')

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [117]:
# Creating the profit rev percentage column
p1_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        p1_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p1_rev)

42

In [118]:
# turning float of percentage of profit into int
pp1_rev= []
for i in p1_rev:
    i = int(i)
    pp1_rev.append(round(i,0))
len(pp1_rev)

42

In [119]:
# converting integer to percentage
gross_profit_margin_percent1= []
for i in pp1_rev:
    gross_profit_margin_percent1.append("{:}%".format(i))
gross_profit_margin_percent1
len(gross_profit_margin_percent1)

42

These are the variables needed to create the columns for the third dataframe; new_name2, new_systems2, new_total_gross2, new_worldwide_gross2, new_profit2, new_currency_profit2, gross_profit_margin_percentage2

In [120]:
new_name2=[]
name2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            name2.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name2):
    new_name2.append(x)
len(new_name2)

42

In [121]:
new_systems2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_systems2.append(all_actionadventure_info1.Total_gross[i])
len(new_systems2)

42

In [122]:
new_worldwide_gross2= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_worldwide_gross2.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross2)

42

In [123]:
new_currency_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_currency_profit2.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit2)

42

In [124]:
new_profit2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='G':
            new_profit2.append(all_actionadventure_info1.Profit[i])
len(new_profit2)

42

In [125]:
new_systems2 = list('G'*42)
len(new_systems2)

42

In [126]:
# Creating the profit rev percentage column
p2_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        p2_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)
len(p2_rev)

42

In [127]:
# turning float of percentage of profit into int
pp2_rev= []
for i in p2_rev:
    i = int(i)
    pp2_rev.append(round(i,0))
len(pp2_rev)

42

In [128]:
# converting integer to percentage
gross_profit_margin_percentage2= []
for i in pp2_rev:
    gross_profit_margin_percentage2.append("{:}%".format(i))
len(gross_profit_margin_percentage2)

42

These are the variables needed to create the columns for the fourth dataframe; new_name3, new_systems3, new_total_gross3, new_worldwide_gross3, new_profit3, new_currency_profit3, gross_profit_margin_percentage3

In [129]:
new_name3=[]
name3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            name3.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name3):
    new_name3.append( x)
len(new_name3)

42

In [130]:
new_total_gross3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_total_gross3.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross3)

42

In [131]:
new_worldwide_gross3= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_worldwide_gross3.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross3)

42

In [132]:
new_currency_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_currency_profit3.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit3)

42

In [133]:
new_profit3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            new_profit3.append(all_actionadventure_info1.Profit[i])
len(new_profit3)

42

In [134]:
new_systems3 = []
for i in list(range(0,42)):
    new_systems3.append('PG-13')

In [135]:
p3_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='PG-13':
            p3_rev.append(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100)

len(p3_rev)

42

In [136]:
# turning float of percentage of profit into int
pp3_rev= []
for i in p3_rev:
    i = int(i)
    pp3_rev.append(round(i,0))
len(pp3_rev)

42

In [137]:
# converting integer to percentage
gross_profit_margin_percentage3= []
for i in pp3_rev:
    gross_profit_margin_percentage3.append("{:}%".format(i))
len(gross_profit_margin_percentage3)

42

These are the variables needed to create the columns for the fivth dataframe; new_name4, new_systems4, new_total_gross4, new_worldwide_gross4, new_profit4, new_currency_profit4, gross_profit_margin_percentage4

In [138]:
new_name4=[]
name4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            name4.append(all_actionadventure_info1.Name[i])
for i,x in enumerate(name4):
    new_name4.append(x)
new_name4
len(new_name4)

42

In [139]:
new_total_gross4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_total_gross4.append(all_actionadventure_info1.Total_gross[i])
len(new_total_gross4)

42

In [140]:
new_worldwide_gross4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_worldwide_gross4.append(all_actionadventure_info1.Worlwide_gross[i])
len(new_worldwide_gross4)

42

In [141]:
new_currency_profit4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_currency_profit4.append(all_actionadventure_info1['Profit$'][i])
len(new_currency_profit4)

42

In [142]:
new_profit4= []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            new_profit4.append(all_actionadventure_info1.Profit[i])
len(new_profit4)

42

In [143]:
new_systems4 = []
for i in list(range(0,42)):
    new_systems4.append('NR')

In [144]:
p4_rev = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
        if x =='NR':
            p4_rev.append(round(all_actionadventure_info1.Profit[i]/all_actionadventure_info1.Total_gross[i]*100,
                                0))
len(p4_rev)

42

In [145]:
# turning float of percentage of profit into int
pp4_rev= []
for i in p4_rev:
    i = int(i)
    pp4_rev.append(round(i,2))
len(pp4_rev)

42

In [146]:
# converting integer to percentage
gross_profit_margin_percent4= []
for i in pp4_rev:
    gross_profit_margin_percent4.append("{:}%".format(i))
len(gross_profit_margin_percent4)

42

In [147]:
# list for type colunm
l = []
for i in list(range(0,42)):
    l.append('Revenue')
for i in list(range(0,42)):
    l.append('Profit')
len(l)

84

In [148]:
df5 = pd.DataFrame({'Name':new_name4*2,'Yield':new_total_gross4+new_profit4,'Type Yield':new_worldwide_gross4+new_currency_profit4,
                    'System Ratings':new_systems4*2,'Gross Profit Margin %':gross_profit_margin_percent4*2,'Type':l})

df4 = pd.DataFrame({'Name':new_name3*2,'Yield':new_total_gross3+new_profit3,'Type Yield':new_worldwide_gross3+new_currency_profit3,
                  'System Ratings':new_systems3*2,'Gross Profit Margin %':gross_profit_margin_percentage3*2,'Type':l})

df3 = pd.DataFrame({'Name':new_name2*2,'Yield':new_total_gross4+new_profit2,'Type Yield':new_worldwide_gross2+new_currency_profit2,
                    'System Ratings':new_systems2*2,'Gross Profit Margin %':gross_profit_margin_percentage2*2,'Type':l})

df2 = pd.DataFrame({'Name':new_name1*2,'Yield':new_total_gross1+new_profit1,'Type Yield':new_worldwide_gross1+new_currency_profit1,
                  'System Ratings':new_systems1*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

df1 = pd.DataFrame({'Name':new_name*2,'Yield':new_total_gross+new_profit,'Type Yield':new_worldwide_gross+new_currency_profit,
                    'System Ratings':new_systems*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l})

In [149]:
df1

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Avatar,2776345279,"$2,776,345,279",R,71%,Revenue
1,Captain America: Civil War,1140069413,"$1,140,069,413",R,79%,Revenue
2,Superman Returns,374085065,"$374,085,065",R,50%,Revenue
3,The Chronicles of Narnia: Prince Caspian,417341288,"$417,341,288",R,67%,Revenue
4,Men in Black 3,654213485,"$654,213,485",R,72%,Revenue
...,...,...,...,...,...,...
79,What Lies Beneath,198693989,"$198,693,989",R,-1%,Profit
80,Mulan,213500000,"$213,500,000",R,72%,Profit
81,Lara Croft: Tomb Raider: The Cradle of Life,67092943,"$67,092,943",R,72%,Profit
82,Mission to Mars,16000000,"$16,000,000",R,74%,Profit
83,Horton Hears a Who,214477886,"$214,477,886",R,-412%,Profit

In [150]:
df2

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Batman v Superman: Dawn of Justice,867500281,"$867,500,281",PG,71%,Revenue
1,The Fate of the Furious,1234846267,"$1,234,846,267",PG,79%,Revenue
2,Tron: Legacy,400062763,"$400,062,763",PG,50%,Revenue
3,X-Men: Apocalypse,542537546,"$542,537,546",PG,67%,Revenue
4,Iron Man 2,621156389,"$621,156,389",PG,72%,Revenue
...,...,...,...,...,...,...
79,Random Hearts,-800000,"$-800,000",PG,-1%,Profit
80,The Prince of Egypt,158613188,"$158,613,188",PG,72%,Profit
81,Grown Ups,197223430,"$197,223,430",PG,72%,Profit
82,X-Men,221872367,"$221,872,367",PG,74%,Profit
83,Soldier,-60376918,"$-60,376,918",PG,-412%,Profit

In [151]:
df3

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,The Hobbit: The Battle of the Five Armies,836519699,"$945,577,621",G,73%,Revenue
1,Wonder Woman,1348258224,"$821,133,378",G,81%,Revenue
2,Madagascar: Escape 2 Africa,962854547,"$599,680,774",G,74%,Revenue
3,Assassinâs Creed,798008101,"$240,759,682",G,48%,Revenue
4,Transcendence,714401889,"$103,039,258",G,2%,Revenue
...,...,...,...,...,...,...
79,Brother Bears 1,204397798,"$204,397,798",G,81%,Profit
80,Cliffords,3182426,"$3,182,426",G,97%,Profit
81,The Wizard of Oz,32172482,"$32,172,482",G,92%,Profit
82,Chicken Little,164432837,"$164,432,837",G,52%,Profit
83,Wall-E,341311860,"$341,311,860",G,65%,Profit

In [152]:
df4

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Spectre,879620923,"$879,620,923",PG-13,65%,Revenue
1,Green Lantern,219535492,"$219,535,492",PG-13,8%,Revenue
2,"The Chronicles of Narnia: The Lion, the Witch ...",720539572,"$720,539,572",PG-13,75%,Revenue
3,Inside Out,854235992,"$854,235,992",PG-13,79%,Revenue
4,Godzilla: King of the Monsters,299276941,"$299,276,941",PG-13,43%,Revenue
...,...,...,...,...,...,...
79,Inferno,144519367,"$144,519,367",PG-13,65%,Profit
80,Big Fish,53954323,"$53,954,323",PG-13,43%,Profit
81,I Spy,-9720178,"$-9,720,178",PG-13,-16%,Profit
82,Broken Arrow,83345997,"$83,345,997",PG-13,56%,Profit
83,Death Race,7516819,"$7,516,819",PG-13,10%,Profit

In [153]:
df5

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Transformers: Revenge of the Fallen,836519699,"$836,519,699",NR,75%,Revenue
1,Black Panther,1348258224,"$1,348,258,224",NR,85%,Revenue
2,The Jungle Book,962854547,"$962,854,547",NR,82%,Revenue
3,Coco,798008101,"$798,008,101",NR,78%,Revenue
4,Captain America: The Winter Soldier,714401889,"$714,401,889",NR,76%,Revenue
...,...,...,...,...,...,...
79,Flushed Away,30357126,"$30,357,126",NR,17%,Profit
80,Madagascar 3: Europe's Most Wanted,601921271,"$601,921,271",NR,81%,Profit
81,Miami Vice,28818556,"$28,818,556",NR,18%,Profit
82,The Adventures of Tintin,243993951,"$243,993,951",NR,65%,Profit
83,Power Rangers,22531552,"$22,531,552",NR,16%,Profit

In [154]:
# this is the first graph: this is the System R rating category
a=alt.Chart(df1).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis = alt.Axis(grid=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem PG rating category
b=alt.Chart(df2).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
        axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem G rating category
c=alt.Chart(df3).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the third graph: this is the Sytem PG-13 rating category
d=alt.Chart(df4).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,#take away the grid
       scale=alt.Scale(zero=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the fourth graph: this is the Sytem NR rating category
e=alt.Chart(df5).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,
       scale=alt.Scale(zero=False),# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

f= alt.vconcat(b,c,d,e).configure_view(strokeOpacity=0).configure_axisLeft(labelColor='#080CFE')
f&a # combines the graphs together

alt.VConcatChart(...)

# Blueprint: Budget and Revenue of Movies

This js the blueprint for creating the third visualization Budget and Revenue of Movies, altair will be used to create this graph. 

__Blueprint:__
   - The format of the dataframe needed for this graph is straight forward, based on the ideology of the persception of the chart, these are the colunms needed for thr dataframe;
        - Name,
        - System Ratings,
        - Budget,
        - Revenue,
        - Budget of Movie,
        - Renenue of Movies
   
  
  - The style of this chart is a Selection Histogram which is found in the Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis is the Revenue and the y-axis is the Budget, this set up projects wether a linear regression, meaning if the hypothesis which is, the higher the budget the higher the revenue is proven right projecting a linear regression.
  
  - The graph has an attachted histogram showing the amount of items in each category within the selection. In order to make a selection create a box by dragging the mouse. When the mouse hovers the pionts it projects the name, system rating, budget of the movies and the reevenue of the movies.

In [160]:
# variable for the range colunm neede for the dataframe below
listt = range(0,210)

In [161]:
# data frame created for the next three graphs
dataframe2 = pd.DataFrame({"Name":all_actionadventure_info1.Name,"System Rating":all_actionadventure_info1.System_ratings,"Budget":all_actionadventure_info1.Buget,'Range':listt,
                           "Revenue":all_actionadventure_info1.Total_gross,'Budget of Movie':all_actionadventure_info1.Product_budget,'Revenue of Movie':all_actionadventure_info1.Worlwide_gross})

In [157]:
#scatter graph
brush = alt.selection(type='interval')# to reate the selction box
points=alt.Chart(dataframe2).mark_circle(size=60).encode(
    x="Revenue:Q",# x-axis
    y='Budget',# y-axis
    color='System Rating', # color based on system rating put into category
    # interactive when the pionts are hovered the name, budget, revenue and system rating shows up
    tooltip=['Name','System Rating','Budget of Movie','Revenue of Movie']
).properties(height=400,width=500).add_selection(brush)# the size of graph

# histogram chart
bars=alt.Chart(dataframe2).mark_bar().encode(
        y='System Rating:N',# y-axis
        color='System Rating:N',# color put into groups based on system ratings
        x='count(Revenue):Q').transform_filter(brush)# x-axis
points&bars# graphs combined together

alt.VConcatChart(...)

# Blueprint: Revenue of Movies

This is the blueprint for creating the fourth visualization Revenue of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis shows the revenue of each movie and the y-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the revenue of the movie.

In [158]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
points1=base.mark_point(size=60).encode(
       y=alt.Y('Range',title='',axis=None),# y-axis
       x = alt.X('Revenue:Q',title='Revenue'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
x_ticks=base.mark_tick().encode(
    alt.X('Revenue',axis=tick_axis),# x-axis
    alt.Y('System Rating',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
points1&x_ticks# the two graphs combined

alt.VConcatChart(...)

# Blueprint: Budget of Movies

This is the blueprint for creating the fivth visualization Budget of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The y-axis shows the Budget of each movie and the x-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the budget of the movie.

In [159]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
pionts1=base.mark_point(size=60).encode(
       x=alt.X('Range',title='',axis=None),# y-axis
       y = alt.Y('Budget:Q',title='Budget'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
y_ticks=base.mark_tick().encode(
    alt.X('System Rating',axis=tick_axis),# x-axis
    alt.Y('Budget',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
y_ticks|pionts1# the two graphs combined

alt.HConcatChart(...)

# Blueprint: Movies that made Profit

This is the blueprint for creating the seventh visualization, Movies that made Profit. Highcharts will be used to create this graph. 

__Blueprint:__
- The graph used for this visualzation is Highcharts Lollipop series which is found in the Highcharts Demos. Lollipop charts are variants of column charts, with a circle marker for the data value and a line extending to the axis.The first approach to this chart is by understanding the format of the script. This graph has two types of code HTML and Javascript. JupyterLab has magic commands that supports HTML and Javascript, it uses the '%' syntax element for magics.

   Before the HTML and Javascript are scripted a dataframe needs to be made to extract all the movies that made profit in the action and adventure genre. The two variable needed from the parent dataframe '_all_actionadventure_info1_' is the name and profit made in integer. 
   
   - __HTML Section:__
      
      To start off the magic command '%%HTML' should be scripted first in the cell. The main scripted         lines that will be used to create highchart graph through out this project are;
          <script src="https://code.highcharts.com/highcharts.js"></script>
          <script src="https://code.highcharts.com/highcharts-more.js"></script>
          <script src="https://code.highcharts.com/modules/exporting.js"></script>
          <script src="https://code.highcharts.com/modules/accessibility.js"></script>
     For this particular graph this script will be used to get lollipop affect;
          <script src="https://code.highcharts.com/modules/dumbbell.js"></script>
          <script src="https://code.highcharts.com/modules/lollipop.js"></script>
     To close off the HTML script, this script is used and to indetify and differenate this claa from        other, the div id has to be named, and if thei graph is being used more than once the div id needs      to have a different name at all times or it will not work;
                       <figure class="highcharts-figure">
                       <div id="r1"></div> 
                       <p class= "highcharts-description">
                       </p>
                       </figure>
                       
   - __Javascript Section:__
   
      To start off, the magic command '%%JS' is used to script javascript in the jupyterlab cell. The         javascript section will have comments and explaination, but for futher information go to               Highcharts Demos.The normal layout is horizontal but for this graph its going to be vertical. The       main javascript used to create this lollipop graph is;
                         name: ' The Sound of Music ' 
                         low: 2303109231
      The name variable is where the name of the movies is put and the low variable is the amount of         profit made in integer is put.

In [164]:
dataframe = pd.DataFrame({"Name":all_actionadventure_info1.Name,"Profit":all_actionadventure_info1.Profit})

In [165]:
# get the largest movies in profit to the smallest for lollipop graph
new1 = []
for i,x in enumerate(dataframe.Profit):
    new1.append((i,x))
new1.sort(reverse=True,key=lambda x:x[1])
new1

[(0, 2351345279),
 (189, 2303109231),
 (11, 1148258224),
 (26, 1135772799),
 (12, 1015392272),
 (5, 984846267),
 (155, 912044677),
 (10, 894039076),
 (2, 890069413),
 (187, 878000000),
 (150, 869429616),
 (103, 842429370),
 (21, 787854547),
 (85, 778210985),
 (108, 769701857),
 (72, 733998877),
 (4, 695577621),
 (54, 693524737),
 (22, 679235992),
 (75, 676680557),
 (31, 675524642),
 (37, 671133378),
 (13, 662316233),
 (201, 652998756),
 (32, 629300444),
 (9, 626519699),
 (23, 623008101),
 (3, 617500281),
 (183, 601921271),
 (1, 579620923),
 (87, 547271443),
 (28, 544401889),
 (191, 543539607),
 (73, 541695615),
 (19, 540539572),
 (117, 537890267),
 (106, 522726752),
 (41, 514837547),
 (14, 508996336),
 (67, 500912003),
 (48, 494954103),
 (38, 476549695),
 (16, 452220086),
 (27, 451156389),
 (40, 449680774),
 (188, 442400000),
 (8, 439213485),
 (151, 429290136),
 (59, 424987477),
 (63, 410663443),
 (55, 397938302),
 (33, 369076069),
 (134, 368214888),
 (20, 364537546),
 (90, 363195589),
 (120, 362846291),
 (130, 360155383),
 (62, 360004754),
 (119, 349837368),
 (24, 349283695),
 (156, 346258539),
 (209, 341311860),
 (181, 340875846),
 (133, 314043396),
 (161, 310561724),
 (69, 308056280),
 (177, 299326618),
 (47, 289942139),
 (93, 289870414),
 (43, 277300260),
 (35, 277150894),
 (140, 265300000),
 (91, 262211740),
 (42, 261258433),
 (89, 259000072),
 (159, 256824714),
 (180, 247501348),
 (49, 246839614),
 (185, 243993951),
 (138, 243629585),
 (58, 234942531),
 (77, 229504276),
 (132, 226730660),
 (178, 224825760),
 (61, 222831065),
 (172, 221872367),
 (179, 220098020),
 (135, 219150134),
 (116, 214477886),
 (110, 213500000),
 (39, 209142722),
 (66, 208711434),
 (25, 208541369),
 (205, 204397798),
 (15, 200062763),
 (101, 199680778),
 (109, 198693989),
 (171, 197223430),
 (34, 195408305),
 (7, 192341288),
 (157, 192239672),
 (79, 185986876),
 (76, 185075882),
 (104, 179330185),
 (152, 178015029),
 (131, 169631958),
 (102, 168898761),
 (196, 168551810),
 (136, 167916633),
 (70, 166192091),
 (208, 164432837),
 (193, 164111171),
 (88, 164065678),
 (44, 160043823),
 (149, 158613188),
 (197, 157900000),
 (46, 155270083),
 (142, 154041804),
 (80, 153880341),
 (57, 151896578),
 (169, 144519367),
 (60, 143271982),
 (6, 142085065),
 (29, 141365187),
 (45, 137594577),
 (18, 136359676),
 (126, 135798265),
 (139, 129343008),
 (30, 129276941),
 (50, 128314513),
 (53, 128073859),
 (144, 125500000),
 (154, 122981799),
 (65, 115759682),
 (115, 113877963),
 (64, 113317814),
 (141, 112910991),
 (125, 109745279),
 (68, 109545589),
 (158, 108853353),
 (78, 98370892),
 (162, 96861183),
 (192, 94146816),
 (99, 91325698),
 (164, 90805525),
 (100, 86124621),
 (175, 83345997),
 (56, 77912137),
 (147, 72768975),
 (112, 72753837),
 (111, 72525156),
 (92, 70936470),
 (105, 70339667),
 (94, 69296573),
 (113, 67092943),
 (129, 63332135),
 (81, 62022517),
 (118, 57986320),
 (84, 57910690),
 (170, 53954323),
 (124, 53461527),
 (163, 53049560),
 (153, 48976250),
 (167, 44512771),
 (71, 43018913),
 (82, 42364370),
 (83, 40468000),
 (207, 32172482),
 (123, 30482317),
 (182, 30357126),
 (184, 28818556),
 (203, 28097693),
 (190, 26957280),
 (86, 24818283),
 (186, 22531552),
 (199, 19800000),
 (17, 19535492),
 (145, 19173475),
 (202, 16610210),
 (114, 16000000),
 (160, 13874967),
 (137, 13266661),
 (36, 12297191),
 (128, 10071069),
 (127, 9851591),
 (176, 7516819),
 (206, 3182426),
 (97, 3039258),
 (195, 2852439),
 (198, 1028261),
 (148, -800000),
 (51, -1163244),
 (96, -4744515),
 (143, -6154989),
 (174, -9720178),
 (200, -12848904),
 (122, -13445453),
 (146, -13537029),
 (98, -14712583),
 (204, -18934093),
 (168, -20655679),
 (165, -29367963),
 (95, -30451359),
 (74, -37371735),
 (194, -47540000),
 (121, -50923322),
 (173, -60376918),
 (52, -61583254),
 (107, -68088638),
 (166, -75978328)]

In [166]:
# getting the name of movies for the lollipop graph
new2 = []
for i in new1:
    new2.append(dataframe.Name[i[0]])
for i,x in enumerate(new2):
    print(i,x)

0 Avatar
1 The Sound of Music
2 Black Panther
3 Jurassic World: Fallen Kingdom
4 Iron Man 3
5 The Fate of the Furious
6 Star Wars Ep. I: The Phantom Menace
7 Transformers: Age of Extinction
8 Captain America: Civil War
9 Thor:Ragnarok
10 Zootopia
11 Finding Nemo
12 The Jungle Book
13 The Lord of the Rings: The Fellowship of the Ring
14 Ice Age: Dawn of the Dinosaurs
15 Star Wars Ep. III: Revenge of the Sith
16 The Hobbit: The Battle of the Five Armies
17 The Twilight Saga: Breaking Dawn, Part 2
18 Inside Out
19 Deadpool 2
20 Inception
21 Wonder Woman
22 Guardians of the Galaxy Vol 2
23 Ice Age 2: The Meltdown
24 Fast and Furious 6
25 Transformers: Revenge of the Fallen
26 Coco
27 Batman v Superman: Dawn of Justice
28 Madagascar 3: Europe's Most Wanted
29 Spectre
30 The Martian
31 Captain America: The Winter Soldier
32 Monsters University
33 Star Wars Ep. II: Attack of the Clones
34 The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
35 The Amazing Spider-Man
36 The Incredibles
37 Kung Fu Panda 2
38 The Amazing Spider-Man 2
39 Life of Pi
40 Pirates of the Caribbean: The Curse of the Black Pearl
41 Ratatouille
42 Fantastic Beasts: The Crimes of Grindelwald
43 Iron Man 2
44 Madagascar: Escape 2 Africa
45 Cinderella
46 Men in Black 3
47 Ready Player One
48 Puss in Boots
49 Sherlock Holmes: A Game of Shadows
50 The Revenant
51 Godzilla
52 Clash of the Titans
53 X-Men: Apocalypse
54 Bumblebee
55 Rio 2
56 Cars 2
57 Teenage Mutant Ninja Turtles
58 Dunkirk
59 Ralph Breaks The Internet
60 San Andreas
61 Wall-E
62 Angels & Demons
63 The Bourne Ultimatum
64 Kingsman: The Secret Service
65 Rampage
66 Thor
67 Die Another Day
68 The Wolf of Wall Street
69 The Matrix Revolutions
70 Terminator: Genisys
71 True Lies
72 Planet of the Apes
73 PokÃ©mon: Detective Pikachu
74 The Hangover 3
75 Minority Report
76 Mission: Impossible III
77 Star Trek
78 The Adventures of Tintin
79 I, Robot
80 Penguins of Madagascar
81 Tomorrow Never Dies
82 The World is Not Enough
83 X-Men Origins: Wolverine
84 Noah
85 X-Men
86 Mad Max: Fury Road
87 Trolls
88 Horton Hears a Who
89 Mulan
90 Batman Begins
91 The Perfect Storm
92 Cars 3
93 Brother Bears 1
94 Tron: Legacy
95 Sex and the City 2
96 What Lies Beneath
97 Grown Ups
98 X-Men: First Class
99 The Chronicles of Narnia: Prince Caspian
100 Passengers
101 Miss Peregrineâs Home for Peculiar Children
102 The Divergent Series: Insurgent
103 Lara Croft: Tomb Raider
104 Bolt
105 The Curious Case of Benjamin Button
106 The Fifth Element
107 Ponyo
108 Oblivion
109 Elysium
110 Chicken Little
111 Wallace & Gomit: The Curse of the Were-Rabbit
112 10,000 B.C.
113 Chicken Little
114 The Prince of Egypt
115 Gnomeo & Juliet
116 Wrath of the Titans
117 Pixels
118 Real Steel
119 Turbo
120 Inferno
121 Bad Boys II
122 Superman Returns
123 The Polar Express
124 Bee Movie
125 Prince of Persia: Sands of Time
126 Inside Man
127 Gone in 60 Seconds
128 Godzilla: King of the Monsters
129 Exodus: Gods and Kings
130 The Incredible Hulk
131 The Sum of All Fears
132 RoboCop
133 Assassinâs Creed
134 King Arthur
135 Batman & Robin
136 You Don't Mess With the Zohan
137 Stepmom
138 Ghost Rider
139 Kingdom of Heaven
140 The Aviator
141 The Secret Life of Walter Mitty
142 Herbie: Fully Loaded
143 The LEGO Movie 2: The Second Part
144 Zookeeper
145 Gangs of New York
146 Broken Arrow
147 Master and Commander: The Far Side of the World
148 Peteâs Dragon
149 The Interpreter
150 The Magnificent Seven
151 The Other Guys
152 The Spiderwick Chronicles
153 The Emperor's New Groove
154 Lara Croft: Tomb Raider: The Cradle of Life
155 The Time Traveler's Wife
156 The Divergent Series: Allegiant
157 The Sorcerer's Apprentice
158 Ghost in the Shell
159 Big Fish
160 The Dark Tower
161 Spy Game
162 Watchmen
163 Charlie Wilson's War
164 The Island
165 The Taking of Pelham 123
166 Speed 2: Cruise Control
167 The Wizard of Oz
168 The Tale of Despereaux
169 Flushed Away
170 Miami Vice
171 Space Chimps
172 The Tale of Despereaux
173 The Cat in the Hat
174 Power Rangers
175 Curious George 1
176 Green Lantern
177 Hall Pass
178 The Fox and the Child
179 Mission to Mars
180 Seventh Son
181 Allied
182 Alexander
183 Fever Pitch
184 Legal Eagles
185 Death Race
186 Cliffords
187 Transcendence
188 Ozzy
189 Yellow Submarine
190 Random Hearts
191 Gods of Egypt
192 Peter Pan
193 Children of Men
194 I Spy
195 Fantastica: A Boonie Bears
196 Thirteen Days
197 Downsizing
198 Mortal Engines
199 The Oegieloves
200 Spanglish
201 Mighty Joe Young
202 Land of the Lost
203 Windtalkers
204 A Boy's Life
205 R.I.P.D.
206 Soldier
207 Stealth
208 The Alamo
209 Renegades

Using a for loop to put the name and profit in html code which will be copied and pasted in the cell below.

In [58]:
for x in range(len(new2)):
    print('        }, { \n           name:',"'",new2[x],"'",','+'\n           low:',new1[x][1])

        }, {
           name: ' Avatar ' ,
           low: 2351345279
        }, {
           name: ' The Sound of Music ' ,
           low: 2303109231
        }, {
           name: ' Black Panther ' ,
           low: 1148258224
        }, {
           name: ' Jurassic World: Fallen Kingdom ' ,
           low: 1135772799
        }, {
           name: ' Iron Man 3 ' ,
           low: 1015392272
        }, {
           name: ' The Fate of the Furious ' ,
           low: 984846267
        }, {
           name: ' Star Wars Ep. I: The Phantom Menace ' ,
           low: 912044677
        }, {
           name: ' Transformers: Age of Extinction ' ,
           low: 894039076
        }, {
           name: ' Captain America: Civil War ' ,
           low: 890069413
        }, {
           name: ' Captain America: Winter Soldier ' ,
           low: 878000000
        }, {
           name: ' Zootopia ' ,
           low: 869429616
        }, {
           name: ' Finding Nemo ' ,
           low: 842429370
        }, {
           name: ' The Jungle Book ' ,
           low: 787854547
        }, {
           name: ' The Lord of the Rings: The Fellowship of the Ring ' ,
           low: 778210985
        }, {
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, {
           name: ' Star Wars Ep. III: Revenge of the Sith ' ,
           low: 733998877
        }, {
           name: ' The Hobbit: The Battle of the Five Armies ' ,
           low: 695577621
        }, {
           name: ' The Twilight Saga: Breaking Dawn, Part 2 ' ,
           low: 693524737
        }, {
           name: ' Inside Out ' ,
           low: 679235992
        }, {
           name: ' Deadpool 2 ' ,
           low: 676680557
        }, {
           name: ' Inception ' ,
           low: 675524642
        }, {
           name: ' Wonder Woman ' ,
           low: 671133378
        }, {
           name: ' Guardians of the Galaxy Vol 2 ' ,
           low: 662316233
        }, {
           name: ' Ice Age 2: The Meltdown ' ,
           low: 652998756
        }, {
           name: ' Fast and Furious 6 ' ,
           low: 629300444
        }, {
           name: ' Transformers: Revenge of the Fallen ' ,
           low: 626519699
        }, {
           name: ' Coco ' ,
           low: 623008101
        }, {
           name: ' Batman v Superman: Dawn of Justice ' ,
           low: 617500281
        }, {
           name: ' Madagascar 3: Europe's Most Wanted ' ,
           low: 601921271
        }, {
           name: ' Spectre ' ,
           low: 579620923
        }, {
           name: ' The Martian ' ,
           low: 547271443
        }, {
           name: ' Captain America: The Winter Soldier ' ,
           low: 544401889
        }, {
           name: ' Monsters University ' ,
           low: 543539607
        }, {
           name: ' Star Wars Ep. II: Attack of the Clones ' ,
           low: 541695615
        }, {
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 540539572
        }, {
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, {
           name: ' The Incredibles ' ,
           low: 522726752
        }, {
           name: ' Kung Fu Panda 2 ' ,
           low: 514837547
        }, {
           name: ' The Amazing Spider-Man 2 ' ,
           low: 508996336
        }, {
           name: ' Life of Pi ' ,
           low: 500912003
        }, {
           name: ' Pirates of the Caribbean: The Curse of the Black Pearl ' ,
           low: 494954103
        }, {
           name: ' Ratatouille ' ,
           low: 476549695
        }, {
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 452220086
        }, {
           name: ' Iron Man 2 ' ,
           low: 451156389
        }, {
           name: ' Madagascar: Escape 2 Africa ' ,
           low: 449680774
        }, {
           name: ' Cinderella ' ,
           low: 442400000
        }, {
           name: ' Men in Black 3 ' ,
           low: 439213485
        }, {
           name: ' Ready Player One ' ,
           low: 429290136
        }, {
           name: ' Puss in Boots ' ,
           low: 424987477
        }, {
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, {
           name: ' The Revenant ' ,
           low: 397938302
        }, {
           name: ' Godzilla ' ,
           low: 369076069
        }, {
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, {
           name: ' X-Men: Apocalypse ' ,
           low: 364537546
        }, {
           name: ' Bumblebee ' ,
           low: 363195589
        }, {
           name: ' Rio 2 ' ,
           low: 362846291
        }, {
           name: ' Cars 2 ' ,
           low: 360155383
        }, {
           name: ' Teenage Mutant Ninja Turtles ' ,
           low: 360004754
        }, {
           name: ' Dunkirk ' ,
           low: 349837368
        }, {
           name: ' Ralph Breaks The Internet ' ,
           low: 349283695
        }, {
           name: ' San Andreas ' ,
           low: 346258539
        }, {
           name: ' Wall-E ' ,
           low: 341311860
        }, {
           name: ' Angels & Demons ' ,
           low: 340875846
        }, {
           name: ' The Bourne Ultimatum ' ,
           low: 314043396
        }, {
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, {
           name: ' Rampage ' ,
           low: 308056280
        }, {
           name: ' Thor ' ,
           low: 299326618
        }, {
           name: ' Die Another Day ' ,
           low: 289942139
        }, {
           name: ' The Wolf of Wall Street ' ,
           low: 289870414
        }, {
           name: ' The Matrix Revolutions ' ,
           low: 277300260
        }, {
           name: ' Terminator: Genisys ' ,
           low: 277150894
        }, {
           name: ' True Lies ' ,
           low: 265300000
        }, {
           name: ' Planet of the Apes ' ,
           low: 262211740
        }, {
           name: ' PokÃ©mon: Detective Pikachu ' ,
           low: 261258433
        }, {
           name: ' The Hangover 3 ' ,
           low: 259000072
        }, {
           name: ' Minority Report ' ,
           low: 256824714
        }, {
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, {
           name: ' Star Trek ' ,
           low: 246839614
        }, {
           name: ' The Adventures of Tintin ' ,
           low: 243993951
        }, {
           name: ' I, Robot ' ,
           low: 243629585
        }, {
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, {
           name: ' Tomorrow Never Dies ' ,
           low: 229504276
        }, {
           name: ' The World is Not Enough ' ,
           low: 226730660
        }, {
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, {
           name: ' Noah ' ,
           low: 222831065
        }, {
           name: ' X-Men ' ,
           low: 221872367
        }, {
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, {
           name: ' Trolls ' ,
           low: 219150134
        }, {
           name: ' Horton Hears a Who ' ,
           low: 214477886
        }, {
           name: ' Mulan ' ,
           low: 213500000
        }, {
           name: ' Batman Begins ' ,
           low: 209142722
        }, {
           name: ' The Perfect Storm ' ,
           low: 208711434
        }, {
           name: ' Cars 3 ' ,
           low: 208541369
        }, {
           name: ' Brother Bears 1 ' ,
           low: 204397798
        }, {
           name: ' Tron: Legacy ' ,
           low: 200062763
        }, {
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, {
           name: ' What Lies Beneath ' ,
           low: 198693989
        }, {
           name: ' Grown Ups ' ,
           low: 197223430
        }, {
           name: ' X-Men: First Class ' ,
           low: 195408305
        }, {
           name: ' The Chronicles of Narnia: Prince Caspian ' ,
           low: 192341288
        }, {
           name: ' Passengers ' ,
           low: 192239672
        }, {
           name: ' Miss Peregrineâs Home for Peculiar Children ' ,
           low: 185986876
        }, {
           name: ' The Divergent Series: Insurgent ' ,
           low: 185075882
        }, {
           name: ' Lara Croft: Tomb Raider ' ,
           low: 179330185
        }, {
           name: ' Bolt ' ,
           low: 178015029
        }, {
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, {
           name: ' The Fifth Element ' ,
           low: 168898761
        }, {
           name: ' Ponyo ' ,
           low: 168551810
        }, {
           name: ' Oblivion ' ,
           low: 167916633
        }, {
           name: ' Elysium ' ,
           low: 166192091
        }, {
           name: ' Chicken Little ' ,
           low: 164432837
        }, {
           name: ' Wallace & Gomit: The Curse of the Were-Rabbit ' ,
           low: 164111171
        }, {
           name: ' 10,000 B.C. ' ,
           low: 164065678
        }, {
           name: ' Chicken Little ' ,
           low: 160043823
        }, {
           name: ' The Prince of Egypt ' ,
           low: 158613188
        }, {
           name: ' Gnomeo & Juliet ' ,
           low: 157900000
        }, {
           name: ' Wrath of the Titans ' ,
           low: 155270083
        }, {
           name: ' Pixels ' ,
           low: 154041804
        }, {
           name: ' Real Steel ' ,
           low: 153880341
        }, {
           name: ' Turbo ' ,
           low: 151896578
        }, {
           name: ' Inferno ' ,
           low: 144519367
        }, {
           name: ' Bad Boys II ' ,
           low: 143271982
        }, {
           name: ' Superman Returns ' ,
           low: 142085065
        }, {
           name: ' The Polar Express ' ,
           low: 141365187
        }, {
           name: ' Bee Movie ' ,
           low: 137594577
        }, {
           name: ' Prince of Persia: Sands of Time ' ,
           low: 136359676
        }, {
           name: ' Inside Man ' ,
           low: 135798265
        }, {
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, {
           name: ' Godzilla: King of the Monsters ' ,
           low: 129276941
        }, {
           name: ' Exodus: Gods and Kings ' ,
           low: 128314513
        }, {
           name: ' The Incredible Hulk ' ,
           low: 128073859
        }, {
           name: ' The Sum of All Fears ' ,
           low: 125500000
        }, {
           name: ' RoboCop ' ,
           low: 122981799
        }, {
           name: ' Assassinâs Creed ' ,
           low: 115759682
        }, {
           name: ' King Arthur ' ,
           low: 113877963
        }, {
           name: ' Batman & Robin ' ,
           low: 113317814
        }, {
           name: ' You Don't Mess With the Zohan ' ,
           low: 112910991
        }, {
           name: ' Stepmom ' ,
           low: 109745279
        }, {
           name: ' Ghost Rider ' ,
           low: 109545589
        }, {
           name: ' Kingdom of Heaven ' ,
           low: 108853353
        }, {
           name: ' The Aviator ' ,
           low: 98370892
        }, {
           name: ' The Secret Life of Walter Mitty ' ,
           low: 96861183
        }, {
           name: ' Herbie: Fully Loaded ' ,
           low: 94146816
        }, {
           name: ' The LEGO Movie 2: The Second Part ' ,
           low: 91325698
        }, {
           name: ' Zookeeper ' ,
           low: 90805525
        }, {
           name: ' Gangs of New York ' ,
           low: 86124621
        }, {
           name: ' Broken Arrow ' ,
           low: 83345997
        }, {
           name: ' Master and Commander: The Far Side of the World ' ,
           low: 77912137
        }, {
           name: ' Peteâs Dragon ' ,
           low: 72768975
        }, {
           name: ' The Interpreter ' ,
           low: 72753837
        }, {
           name: ' The Magnificent Seven ' ,
           low: 72525156
        }, {
           name: ' The Other Guys ' ,
           low: 70936470
        }, {
           name: ' The Spiderwick Chronicles ' ,
           low: 70339667
        }, {
           name: ' The Emperor's New Groove ' ,
           low: 69296573
        }, {
           name: ' Lara Croft: Tomb Raider: The Cradle of Life ' ,
           low: 67092943
        }, {
           name: ' The Time Traveler's Wife ' ,
           low: 63332135
        }, {
           name: ' The Divergent Series: Allegiant ' ,
           low: 62022517
        }, {
           name: ' The Sorcerer's Apprentice ' ,
           low: 57986320
        }, {
           name: ' Ghost in the Shell ' ,
           low: 57910690
        }, {
           name: ' Big Fish ' ,
           low: 53954323
        }, {
           name: ' The Dark Tower ' ,
           low: 53461527
        }, {
           name: ' Spy Game ' ,
           low: 53049560
        }, {
           name: ' Watchmen ' ,
           low: 48976250
        }, {
           name: ' Charlie Wilson's War ' ,
           low: 44512771
        }, {
           name: ' The Island ' ,
           low: 43018913
        }, {
           name: ' The Taking of Pelham 123 ' ,
           low: 42364370
        }, {
           name: ' Speed 2: Cruise Control ' ,
           low: 40468000
        }, {
           name: ' The Wizard of Oz ' ,
           low: 32172482
        }, {
           name: ' The Tale of Despereaux ' ,
           low: 30482317
        }, {
           name: ' Flushed Away ' ,
           low: 30357126
        }, {
           name: ' Miami Vice ' ,
           low: 28818556
        }, {
           name: ' Space Chimps ' ,
           low: 28097693
        }, {
           name: ' The Tale of Despereaux ' ,
           low: 26957280
        }, {
           name: ' The Cat in the Hat ' ,
           low: 24818283
        }, {
           name: ' Power Rangers ' ,
           low: 22531552
        }, {
           name: ' Curious George 1 ' ,
           low: 19800000
        }, {
           name: ' Green Lantern ' ,
           low: 19535492
        }, {
           name: ' Hall Pass ' ,
           low: 19173475
        }, {
           name: ' The Fox and the Child ' ,
           low: 16610210
        }, {
           name: ' Mission to Mars ' ,
           low: 16000000
        }, {
           name: ' Seventh Son ' ,
           low: 13874967
        }, {
           name: ' Allied ' ,
           low: 13266661
        }, {
           name: ' Alexander ' ,
           low: 12297191
        }, {
           name: ' Fever Pitch ' ,
           low: 10071069
        }, {
           name: ' Legal Eagles ' ,
           low: 9851591
        }, {
           name: ' Death Race ' ,
           low: 7516819
        }, {
           name: ' Cliffords ' ,
           low: 3182426
        }, {
           name: ' Transcendence ' ,
           low: 3039258
        }, {
           name: ' Ozzy ' ,
           low: 2852439
        }, {
           name: ' Yellow Submarine ' ,
           low: 1028261
        }, {
           name: ' Random Hearts ' ,
           low: -800000
        }, {
           name: ' Gods of Egypt ' ,
           low: -1163244
        }, {
           name: ' Peter Pan ' ,
           low: -4744515
        }, {
           name: ' Children of Men ' ,
           low: -6154989
        }, {
           name: ' I Spy ' ,
           low: -9720178
        }, {
           name: ' Fantastica: A Boonie Bears ' ,
           low: -12848904
        }, {
           name: ' Thirteen Days ' ,
           low: -13445453
        }, {
           name: ' Downsizing ' ,
           low: -13537029
        }, {
           name: ' Mortal Engines ' ,
           low: -14712583
        }, {
           name: ' The Oegieloves ' ,
           low: -18934093
        }, {
           name: ' Spanglish ' ,
           low: -20655679
        }, {
           name: ' Mighty Joe Young ' ,
           low: -29367963
        }, {
           name: ' Land of the Lost ' ,
           low: -30451359
        }, {
           name: ' Windtalkers ' ,
           low: -37371735
        }, {
           name: ' A Boy's Life ' ,
           low: -47540000
        }, {
           name: ' R.I.P.D. ' ,
           low: -50923322
        }, {
           name: ' Soldier ' ,
           low: -60376918
        }, {
           name: ' Stealth ' ,
           low: -61583254
        }, {
           name: ' The Alamo ' ,
           low: -68088638
        }, {
           name: ' Renegades ' ,
           low: -75978328

In [191]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/dumbbell.js"></script>
<script src="https://code.highcharts.com/modules/lollipop.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="r1"></div> 
    <p class= "highcharts-description">
    </p>
</figure>

In [192]:
%%js
Highcharts.chart('r1', { //name of grapg is r1

    chart: {
        type: 'lollipop', //type of graph is the lollipop graph
        inverted:true, //this makes the graph horizontal
        height:1800  //this allows the size of the graph to be ajusted
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. {xDescription}, {point.y}.'
        }
    },

    legend: {
        enabled: true,
        layout:'vertical',
        reversed:true
    },

    subtitle: {
        text: '209 Movies'
    },

    title: {
        text: 'Action & Adventure Genre'
    },

    tooltip: {
        shared: true //allows the tooltip to be enabled
    },

    xAxis: {
        type:'category',
        title:{
            text:'Movies' //name of x-axis
        }
    },
    yAxis:{
        title:{
            text:'Profit' //name of y-axis
        }
    },
    series: [{
        name: 'Profit',
        color:'blue', //allows color to be adjusted
        dataSorting:{
            enabled: false
        },
        data: [{
           name: ' Avatar ' , //name of movie 
           low: 2351345279 //amount of profit made in int of the movie
        }, { 
           name: ' The Sound of Music ' ,
           low: 2303109231
        }, { 
           name: ' Black Panther ' ,
           low: 1148258224
        }, { 
           name: ' Jurassic World: Fallen Kingdom ' ,
           low: 1135772799
        }, { 
           name: ' Iron Man 3 ' ,
           low: 1015392272
        }, { 
           name: ' The Fate of the Furious ' ,
           low: 984846267
        }, { 
           name: ' Star Wars Ep. I: The Phantom Menace ' ,
           low: 912044677
        }, { 
           name: ' Transformers: Age of Extinction ' ,
           low: 894039076
        }, { 
           name: ' Captain America: Civil War ' ,
           low: 890069413
        }, { 
           name: 'Thor: Ragnarok ' ,
           low: 878000000
        }, { 
           name: ' Zootopia ' ,
           low: 869429616
        }, { 
           name: ' Finding Nemo ' ,
           low: 842429370
        }, { 
           name: ' The Jungle Book ' ,
           low: 787854547
        }, { 
           name: ' The Lord of the Rings: The Fellowship of the Ring ' ,
           low: 778210985
        }, { 
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, { 
           name: ' Star Wars Ep. III: Revenge of the Sith ' ,
           low: 733998877
        }, { 
           name: ' The Hobbit: The Battle of the Five Armies ' ,
           low: 695577621
        }, { 
           name: ' The Twilight Saga: Breaking Dawn, Part 2 ' ,
           low: 693524737
        }, { 
           name: ' Inside Out ' ,
           low: 679235992
        }, { 
           name: ' Deadpool 2 ' ,
           low: 676680557
        }, { 
           name: ' Inception ' ,
           low: 675524642
        }, { 
           name: ' Wonder Woman ' ,
           low: 671133378
        }, { 
           name: ' Guardians of the Galaxy Vol 2 ' ,
           low: 662316233
        }, { 
           name: ' Ice Age 2: The Meltdown ' ,
           low: 652998756
        }, { 
           name: ' Fast and Furious 6 ' ,
           low: 629300444
        }, { 
           name: ' Transformers: Revenge of the Fallen ' ,
           low: 626519699
        }, { 
           name: ' Coco ' ,
           low: 623008101
        }, { 
           name: ' Batman v Superman: Dawn of Justice ' ,
           low: 617500281
        }, { 
           name: ' Madagascar 3: Europe\'s Most Wanted ' ,
           low: 601921271
        }, { 
           name: ' Spectre ' ,
           low: 579620923
        }, { 
           name: ' The Martian ' ,
           low: 547271443
        }, { 
           name: ' Captain America: The Winter Soldier ' ,
           low: 544401889
        }, { 
           name: ' Monsters University ' ,
           low: 543539607
        }, { 
           name: ' Star Wars Ep. II: Attack of the Clones ' ,
           low: 541695615
        }, { 
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           low: 540539572
        }, { 
           name: ' The Amazing Spider-Man ' ,
           low: 537890267
        }, { 
           name: ' The Incredibles ' ,
           low: 522726752
        }, { 
           name: ' Kung Fu Panda 2 ' ,
           low: 514837547
        }, { 
           name: ' The Amazing Spider-Man 2 ' ,
           low: 508996336
        }, { 
           name: ' Life of Pi ' ,
           low: 500912003
        }, { 
           name: ' Pirates of the Caribbean: The Curse of the Black Pearl ' ,
           low: 494954103
        }, { 
           name: ' Ratatouille ' ,
           low: 476549695
        }, { 
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           low: 452220086
        }, { 
           name: ' Iron Man 2 ' ,
           low: 451156389
        }, { 
           name: ' Madagascar: Escape 2 Africa ' ,
           low: 449680774
        }, { 
           name: ' Cinderella ' ,
           low: 442400000
        }, { 
           name: ' Men in Black 3 ' ,
           low: 439213485
        }, { 
           name: ' Ready Player One ' ,
           low: 429290136
        }, { 
           name: ' Puss in Boots ' ,
           low: 424987477
        }, { 
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           low: 410663443
        }, { 
           name: ' The Revenant ' ,
           low: 397938302
        }, { 
           name: ' Godzilla ' ,
           low: 369076069
        }, { 
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, { 
           name: ' X-Men: Apocalypse ' ,
           low: 364537546
        }, { 
           name: ' Bumblebee ' ,
           low: 363195589
        }, { 
           name: ' Rio 2 ' ,
           low: 362846291
        }, { 
           name: ' Cars 2 ' ,
           low: 360155383
        }, { 
           name: ' Teenage Mutant Ninja Turtles ' ,
           low: 360004754
        }, { 
           name: ' Dunkirk ' ,
           low: 349837368
        }, { 
           name: ' Ralph Breaks The Internet ' ,
           low: 349283695
        }, { 
           name: ' San Andreas ' ,
           low: 346258539
        }, { 
           name: ' Wall-E ' ,
           low: 341311860
        }, { 
           name: ' Angels & Demons ' ,
           low: 340875846
        }, { 
           name: ' The Bourne Ultimatum ' ,
           low: 314043396
        }, { 
           name: ' Kingsman: The Secret Service ' ,
           low: 310561724
        }, { 
           name: ' Rampage ' ,
           low: 308056280
        }, { 
           name: ' Thor ' ,
           low: 299326618
        }, { 
           name: ' Die Another Day ' ,
           low: 289942139
        }, { 
           name: ' The Wolf of Wall Street ' ,
           low: 289870414
        }, { 
           name: ' The Matrix Revolutions ' ,
           low: 277300260
        }, { 
           name: ' Terminator: Genisys ' ,
           low: 277150894
        }, { 
           name: ' True Lies ' ,
           low: 265300000
        }, { 
           name: ' Planet of the Apes ' ,
           low: 262211740
        }, { 
           name: ' PokÃ©mon: Detective Pikachu ' ,
           low: 261258433
        }, { 
           name: ' The Hangover 3 ' ,
           low: 259000072
        }, { 
           name: ' Minority Report ' ,
           low: 256824714
        }, { 
           name: ' Mission: Impossible III ' ,
           low: 247501348
        }, { 
           name: ' Star Trek ' ,
           low: 246839614
        }, { 
           name: ' The Adventures of Tintin ' ,
           low: 243993951
        }, { 
           name: ' I, Robot ' ,
           low: 243629585
        }, { 
           name: ' Penguins of Madagascar ' ,
           low: 234942531
        }, { 
           name: ' Tomorrow Never Dies ' ,
           low: 229504276
        }, { 
           name: ' The World is Not Enough ' ,
           low: 226730660
        }, { 
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, { 
           name: ' Noah ' ,
           low: 222831065
        }, { 
           name: ' X-Men ' ,
           low: 221872367
        }, { 
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, { 
           name: ' Trolls ' ,
           low: 219150134
        }, { 
           name: ' Horton Hears a Who ' ,
           low: 214477886
        }, { 
           name: ' Mulan ' ,
           low: 213500000
        }, { 
           name: ' Batman Begins ' ,
           low: 209142722
        }, { 
           name: ' The Perfect Storm ' ,
           low: 208711434
        }, { 
           name: ' Cars 3 ' ,
           low: 208541369
        }, { 
           name: ' Brother Bears 1 ' ,
           low: 204397798
        }, { 
           name: ' Tron: Legacy ' ,
           low: 200062763
        }, { 
           name: ' Sex and the City 2 ' ,
           low: 199680778
        }, { 
           name: ' What Lies Beneath ' ,
           low: 198693989
        }, { 
           name: ' Grown Ups ' ,
           low: 197223430
        }, { 
           name: ' X-Men: First Class ' ,
           low: 195408305
        }, { 
           name: ' The Chronicles of Narnia: Prince Caspian ' ,
           low: 192341288
        }, { 
           name: ' Passengers ' ,
           low: 192239672
        }, { 
           name: ' Miss Peregrineâs Home for Peculiar Children ' ,
           low: 185986876
        }, { 
           name: ' The Divergent Series: Insurgent ' ,
           low: 185075882
        }, { 
           name: ' Lara Croft: Tomb Raider ' ,
           low: 179330185
        }, { 
           name: ' Bolt ' ,
           low: 178015029
        }, { 
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, { 
           name: ' The Fifth Element ' ,
           low: 168898761
        }, { 
           name: ' Ponyo ' ,
           low: 168551810
        }, { 
           name: ' Oblivion ' ,
           low: 167916633
        }, { 
           name: ' Elysium ' ,
           low: 166192091
        }, { 
           name: ' Chicken Little ' ,
           low: 164432837
        }, { 
           name: ' Wallace & Gomit: The Curse of the Were-Rabbit ' ,
           low: 164111171
        }, { 
           name: ' 10,000 B.C. ' ,
           low: 164065678
        }, { 
           name: ' Chicken Little ' ,
           low: 160043823
        }, { 
           name: ' The Prince of Egypt ' ,
           low: 158613188
        }, { 
           name: ' Gnomeo & Juliet ' ,
           low: 157900000
        }, { 
           name: ' Wrath of the Titans ' ,
           low: 155270083
        }, { 
           name: ' Pixels ' ,
           low: 154041804
        }, { 
           name: ' Real Steel ' ,
           low: 153880341
        }, { 
           name: ' Turbo ' ,
           low: 151896578
        }, { 
           name: ' Inferno ' ,
           low: 144519367
        }, { 
           name: ' Bad Boys II ' ,
           low: 143271982
        }, { 
           name: ' Superman Returns ' ,
           low: 142085065
        }, { 
           name: ' The Polar Express ' ,
           low: 141365187
        }, { 
           name: ' Bee Movie ' ,
           low: 137594577
        }, { 
           name: ' Prince of Persia: Sands of Time ' ,
           low: 136359676
        }, { 
           name: ' Inside Man ' ,
           low: 135798265
        }, { 
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, { 
           name: ' Godzilla: King of the Monsters ' ,
           low: 129276941
        }, { 
           name: ' Exodus: Gods and Kings ' ,
           low: 128314513
        }, { 
           name: ' The Incredible Hulk ' ,
           low: 128073859
        }, { 
           name: ' The Sum of All Fears ' ,
           low: 125500000
        }, { 
           name: ' RoboCop ' ,
           low: 122981799
        }, { 
           name: ' Assassinâs Creed ' ,
           low: 115759682
        }, { 
           name: ' King Arthur ' ,
           low: 113877963
        }, { 
           name: ' Batman & Robin ' ,
           low: 113317814
        }, { 
           name: ' You Don\'t Mess With the Zohan ' ,
           low: 112910991
        }, { 
           name: ' Stepmom ' ,
           low: 109745279
        }, { 
           name: ' Ghost Rider ' ,
           low: 109545589
        }, { 
           name: ' Kingdom of Heaven ' ,
           low: 108853353
        }, { 
           name: ' The Aviator ' ,
           low: 98370892
        }, { 
           name: ' The Secret Life of Walter Mitty ' ,
           low: 96861183
        }, { 
           name: ' Herbie: Fully Loaded ' ,
           low: 94146816
        }, { 
           name: ' The LEGO Movie 2: The Second Part ' ,
           low: 91325698
        }, { 
           name: ' Zookeeper ' ,
           low: 90805525
        }, { 
           name: ' Gangs of New York ' ,
           low: 86124621
        }, { 
           name: ' Broken Arrow ' ,
           low: 83345997
        }, { 
           name: ' Master and Commander: The Far Side of the World ' ,
           low: 77912137
        }, { 
           name: ' Peteâs Dragon ' ,
           low: 72768975
        }, { 
           name: ' The Interpreter ' ,
           low: 72753837
        }, { 
           name: ' The Magnificent Seven ' ,
           low: 72525156
        }, { 
           name: ' The Other Guys ' ,
           low: 70936470
        }, { 
           name: ' The Spiderwick Chronicles ' ,
           low: 70339667
        }, { 
           name: ' The Emperor\'s New Groove ' ,
           low: 69296573
        }, { 
           name: ' Lara Croft: Tomb Raider: The Cradle of Life ' ,
           low: 67092943
        }, { 
           name: ' The Time Traveler\'s Wife ' ,
           low: 63332135
        }, { 
           name: ' The Divergent Series: Allegiant ' ,
           low: 62022517
        }, { 
           name: ' The Sorcerer\'s Apprentice ' ,
           low: 57986320
        }, { 
           name: ' Ghost in the Shell ' ,
           low: 57910690
        }, { 
           name: ' Big Fish ' ,
           low: 53954323
        }, { 
           name: ' The Dark Tower ' ,
           low: 53461527
        }, { 
           name: ' Spy Game ' ,
           low: 53049560
        }, { 
           name: ' Watchmen ' ,
           low: 48976250
        }, { 
           name: ' Charlie Wilson\'s War ' ,
           low: 44512771
        }, { 
           name: ' The Island ' ,
           low: 43018913
        }, { 
           name: ' The Taking of Pelham 123 ' ,
           low: 42364370
        }, { 
           name: ' Speed 2: Cruise Control ' ,
           low: 40468000
        }, { 
           name: ' The Wizard of Oz ' ,
           low: 32172482
        }, { 
           name: ' The Tale of Despereaux ' ,
           low: 30482317
        }, { 
           name: ' Flushed Away ' ,
           low: 30357126
        }, { 
           name: ' Miami Vice ' ,
           low: 28818556
        }, { 
           name: ' Space Chimps ' ,
           low: 28097693
        }, { 
           name: ' The Tale of Despereaux ' ,
           low: 26957280
        }, { 
           name: ' The Cat in the Hat ' ,
           low: 24818283
        }, { 
           name: ' Power Rangers ' ,
           low: 22531552
        }, { 
           name: ' Curious George 1 ' ,
           low: 19800000
        }, { 
           name: ' Green Lantern ' ,
           low: 19535492
        }, { 
           name: ' Hall Pass ' ,
           low: 19173475
        }, { 
           name: ' The Fox and the Child ' ,
           low: 16610210
        }, { 
           name: ' Mission to Mars ' ,
           low: 16000000
        }, { 
           name: ' Seventh Son ' ,
           low: 13874967
        }, { 
           name: ' Allied ' ,
           low: 13266661
        }, { 
           name: ' Alexander ' ,
           low: 12297191
        }, { 
           name: ' Fever Pitch ' ,
           low: 10071069
        }, { 
           name: ' Legal Eagles ' ,
           low: 9851591
        }, { 
           name: ' Death Race ' ,
           low: 7516819
        }, { 
           name: ' Cliffords ' ,
           low: 3182426
        }, { 
           name: ' Transcendence ' ,
           low: 3039258
        }, { 
           name: ' Ozzy ' ,
           low: 2852439
        }, { 
           name: ' Yellow Submarine ' ,
           low: 1028261
        }]
    }]
});

# Blueprint: Movies that did not make any Profit.

This is the blueprint for creating the eight visualization, movies that did not make any profit. Highcharts will be used to create this graph. 

__Blueprint:__
     
   - The graph used for this visualazation is Highcharts Column chart with negative values series which is found in the Highcharts Demos. Column charts are mostly used to compare categories with different values including negative value, they are very popular and transparant types of charts.
    
 The first approach to this chart is by understanding the format of the code script. Like the previous data visualization this graph is constructed by two different types of code HTML and Javascript. The HTML script is very similar to the previous graph, they allow the column graph to produce negative column and comparison between any particular value of the movie. Closing of the script is similar to the previous script but with a unique name to it self;
                              <figure class="highcharts-figure">
                              <div id="w1"></div> 
                              <p class="highcharts-description">
                              </p>
                              </figure>
The second approach is scripting the javascript section. The javascript section is entirely different to the previous graph, before diving into the javascript code there needs to be data extracted. The names of all the movies that didn't make any profit which will be extracted from the parent dataframe, also the cost, the loss and the revenue of all the movies that did not make any profit.

- There are five major sections in the javascript section that are very critical.
     - 1. The list that is called categories is where all the names of all the movies that were not profitable are scripted. 
                             categories:['Random Hearts','Gods of Egypt','Peter Pan','Children of Men','I Spy','Fantastica: A Boonie Bears','Thirteen Days','Downsizing','Mortal Engines','The Oegieloves','Spanglish','Mighty Joe Young', 'Land of the Lost','Windtalkers',"A Boy's Life",'R.I.P.D.','Soldier','Stealth','The Alamo', 'Renegades']
     
     - 2. The y-axis min, max and steps are very important values that are put in a specific way to allow most of the negative values to be visible, based on how large the other values were;
                              yAxis:{
                              min:-500000,
                              max:180000000,
                              step:50000,
                              },
     
     - 3. The series section has three sub-section;
         - The Cost category is a list consisting of all the amount of money spent to create the movies that were not profitable.
                name:'Cost',
                data:[64000000,140000000,100000000,76000000,70000000,90000000,80000000,
                     68000000,100000000,20000000,75000000,80000000,100000000,115000000,
                     90000000,130000000,75000000,138000000,92000000,77500000]
         - The Revenue category is a list consisting of all the money thta were made but not minus the cost of all the movies not profitable.
                name:'Revenue',
                data:[63200000,138836756,95255485,69845011,60279822,77151096,66554547,54462971,
                      85287417,1065907,54344321,50632037,69548641,77628265,42460000,
                      79076678,14623082,76416746,23911362,1521672]
         - The Loss category is a list showing all the amount of money that fell short, meaning the cost was higher than the revenue giving the loss negitative values. Each movie spent more tahn they anticipated to make. 
                name:'Loss',
                data:[-800000,-1163244,-4744515,-6154989,-9720178,-12848904,-13445453,
                  -13537029,-14712583,-18934093,-20655679,-29367963,-30451359,
                  -37371735,-47540000,-50923322,-60376918,-61583254,-68088638,
                  -75978328]

In [59]:
# getting the Cost of the movies that had losses
new3 = []
for i in new1[190:]:
    new3.append(all_actionadventure_info1.Buget[i[0]])
new3

[64000000,
 140000000,
 100000000,
 76000000,
 70000000,
 90000000,
 80000000,
 68000000,
 100000000,
 20000000,
 75000000,
 80000000,
 100000000,
 115000000,
 90000000,
 130000000,
 75000000,
 138000000,
 92000000,
 77500000]

In [60]:
# getting the Revenue of the movies with losses
new4 = []
for i in new1[190:]:
    new4.append(all_actionadventure_info1.Total_gross[i[0]])
new4

[63200000,
 138836756,
 95255485,
 69845011,
 60279822,
 77151096,
 66554547,
 54462971,
 85287417,
 1065907,
 54344321,
 50632037,
 69548641,
 77628265,
 42460000,
 79076678,
 14623082,
 76416746,
 23911362,
 1521672]

In [70]:
# the the amount of money for thr movies with losses
for i in new1[190:]:
    print(i[1])

-800000
-1163244
-4744515
-6154989
-9720178
-12848904
-13445453
-13537029
-14712583
-18934093
-20655679
-29367963
-30451359
-37371735
-47540000
-50923322
-60376918
-61583254
-68088638
-75978328

In [69]:
# the names of the movies with losses
new2[190:]

['Random Hearts',
 'Gods of Egypt',
 'Peter Pan',
 'Children of Men',
 'I Spy',
 'Fantastica: A Boonie Bears',
 'Thirteen Days',
 'Downsizing',
 'Mortal Engines',
 'The Oegieloves',
 'Spanglish',
 'Mighty Joe Young',
 'Land of the Lost',
 'Windtalkers',
 "A Boy's Life",
 'R.I.P.D.',
 'Soldier',
 'Stealth',
 'The Alamo',
 'Renegades']

In [185]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="w1"></div> 
    <p class="highcharts-description">
    </p>
</figure>

In [188]:
%%js
Highcharts.chart('w1',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        //name of all the movies 
        categories:['Random Hearts','Gods of Egypt','Peter Pan','Children of Men','I Spy','Fantastica: A Boonie Bears',
                    'Thirteen Days','Downsizing','Mortal Engines','The Oegieloves','Spanglish','Mighty Joe Young',
                    'Land of the Lost','Windtalkers',"A Boy's Life",'R.I.P.D.','Soldier','Stealth','The Alamo',
                    'Renegades'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#5179D6','#2F5E8C','#33CCFF'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[64000000,140000000,100000000,76000000,70000000,90000000,80000000,
             68000000,100000000,20000000,75000000,80000000,100000000,115000000,
             90000000,130000000,75000000,138000000,92000000,77500000]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[-800000,-1163244,-4744515,-6154989,-9720178,-12848904,-13445453,
             -13537029,-14712583,-18934093,-20655679,-29367963,-30451359,
             -37371735,-47540000,-50923322,-60376918,-61583254,-68088638,
             -75978328]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[63200000,138836756,95255485,69845011,60279822,77151096,66554547,54462971,
              85287417,1065907,54344321,50632037,69548641,77628265,42460000,79076678,
              14623082,76416746,23911362,1521672]
    }]
});

# Blueprint: Top 20 Highest Profitable Movies and Top 20 Lowest Profitable Movies

This is the blueprint for creating the ninth and tenth visualization, Top 20 Highest Profitable Movies and the Top 20 Lowest Profitable Movies. Highcharts will be used to create these garphs.

__Blueprint:__
  - The graph used for these visualization is Highcharts 3D Cylinder Chart for the Top 20 Highest Profitable Movies and Highcharts Chart Rotation Chart Series for thr Top 20 lowest Profitable Movies, which is all found in the highcharts demos. The chart rotation chart series have an Alpha, Beta and Depth angle which can be adjusted to rotate the graph around.
  
    The first approach to this chart is by understanding the format of the code script. Like the previous graph this chart is constructed by two different types of code HTML and Javascript. The HTML section is very similar to the previous graph but the only difference is this HTML code;
         <script src="https://code.highcharts.com/highcharts-3d.js"></script>
         <script src="https://code.highcharts.com/modules/cylinder.js"></script>
    This allows the graphs to be 3D and it also allows it to be cylinder. To close of two script is also similar to the previous script but with a unique name to it self. 
       
       This is for the cylinder graph;
                      <figure class="highcharts-figure">
                      <div id="b1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
                
       This if for the 3D column graph;
                      <figure class="highcharts-figure">
                      <div id="c1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
   The second approach is scripting the javascript section. The javascript section is very simple, brfore that there needs to be some data extracted from the parent dataframe. These are the elements needed to be extracted for this visualazation. For the Top 20 Highest Profitable Movies the name and amount of profit made is needed, for the Top 20 Lowest Profitable Movies the name and amount of profit made in integer of all the movies is needed in that category.
   
 There is just one sub-section in each graph that are particular, the data sub-section in the series section. It is a body of sequenences of list that consist of the name and amount of profit made in integer.
   
   This is from the first graph;
            ['Avatar|1st Highest',2351345279],
            ['The Sound of Music|2nd Highest', 2303109231],
            ['Black Panther|3rd Highest',1148258224]
       
   This is from the second graph;
            [' Miami Vice|170th Highest', 28818556 ],
            [' Space Chimps|171th Highest', 28097693 ],
            [' The Tale of Despereaux|172th Highest', 26957280 ],

Using a for loop to put the top 20 highest profitable movie name and profit in html code which will be pasted in the cell below.

In [146]:
for i,x in enumerate(range(len(new2[:20]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Avatar | 0 th Highest', 2351345279 ],
[' The Sound of Music | 1 th Highest', 2303109231 ],
[' Black Panther | 2 th Highest', 1148258224 ],
[' Jurassic World: Fallen Kingdom | 3 th Highest', 1135772799 ],
[' Iron Man 3 | 4 th Highest', 1015392272 ],
[' The Fate of the Furious | 5 th Highest', 984846267 ],
[' Star Wars Ep. I: The Phantom Menace | 6 th Highest', 912044677 ],
[' Transformers: Age of Extinction | 7 th Highest', 894039076 ],
[' Captain America: Civil War | 8 th Highest', 890069413 ],
[' Thor:Ragnarok | 9 th Highest', 878000000 ],
[' Zootopia | 10 th Highest', 869429616 ],
[' Finding Nemo | 11 th Highest', 842429370 ],
[' The Jungle Book | 12 th Highest', 787854547 ],
[' The Lord of the Rings: The Fellowship of the Ring | 13 th Highest', 778210985 ],
[' Ice Age: Dawn of the Dinosaurs | 14 th Highest', 769701857 ],
[' Star Wars Ep. III: Revenge of the Sith | 15 th Highest', 733998877 ],
[' The Hobbit: The Battle of the Five Armies | 16 th Highest', 695577621 ],
[' The Twilight Saga: Breaking Dawn, Part 2 | 17 th Highest', 693524737 ],
[' Inside Out | 18 th Highest', 679235992 ],
[' Deadpool 2 | 19 th Highest', 676680557 ],

In [168]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="httos://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="b1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [193]:
%%js
new Highcharts.chart('b1',{ //name of graph
    chart:{
        type:'cylinder', // makes graph cylinder
        // adjust the position of graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:16,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Highest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // mkaes the graph one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Highest Profit',
        color:'#0080FF',// color of cylinders in graph
           data:[
     // names and amount of profit made in integer of the ten most highest profitable movies
            ['Avatar|1st Highest',2351345279],
            ['The Sound of Music|2nd Highest', 2303109231],
            ['Black Panther|3rd Highest',1148258224],
            ['Jurassic World: Fallen Kingdom|4th Highest',1135772799],
            ['Iron Man 3|5th Highest',1015392272],
            ['The Fate of the Furious|6th Highest',984846267],
            ['Star Wars Ep. I: The Phantom Menace|7th Highest', 912044677],
            ['Transformers: Age of Extinction|8th Highest', 894039076],
            ['Captain America: Civil War|9th Highest', 890069413],
            ['Thor: Ragnarok|10th Highest', 878000000],
            ['Zootopia|11th Highest', 869429616],
            ['Finding Nemo|12th Highest', 842429370],
            ['The Jungle Book|13th Highest', 787854547],
            ['The Lord of the Rings: The Fellowship of the Ring|14th Highest', 778210985],
            ['Ice Age: Dawn of the Dinosaurs|15th Highest', 769701857],
            ['Star Wars Ep. III: Revenge of the Sith|16th Highest', 733998877],
            ['The Hobbit: The Battle of the Five Armies|17th Highest', 695577621],
            ['The Twilight Saga: Breaking Dawn, Part 2|18th Highest', 693524737],
            ['Inside Out|19th Highest',679235992],
            ['Deadpool 2|20th Highest',676680557]
         ]
    }]
        
});

Using a for loop to put the top 20 lowest profitable movie name and profit in html code which will be pasted in the cell below

In [148]:
for i,x in enumerate(range(len(new2[:]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Avatar | 0 th Highest', 2351345279 ],
[' The Sound of Music | 1 th Highest', 2303109231 ],
[' Black Panther | 2 th Highest', 1148258224 ],
[' Jurassic World: Fallen Kingdom | 3 th Highest', 1135772799 ],
[' Iron Man 3 | 4 th Highest', 1015392272 ],
[' The Fate of the Furious | 5 th Highest', 984846267 ],
[' Star Wars Ep. I: The Phantom Menace | 6 th Highest', 912044677 ],
[' Transformers: Age of Extinction | 7 th Highest', 894039076 ],
[' Captain America: Civil War | 8 th Highest', 890069413 ],
[' Thor:Ragnarok | 9 th Highest', 878000000 ],
[' Zootopia | 10 th Highest', 869429616 ],
[' Finding Nemo | 11 th Highest', 842429370 ],
[' The Jungle Book | 12 th Highest', 787854547 ],
[' The Lord of the Rings: The Fellowship of the Ring | 13 th Highest', 778210985 ],
[' Ice Age: Dawn of the Dinosaurs | 14 th Highest', 769701857 ],
[' Star Wars Ep. III: Revenge of the Sith | 15 th Highest', 733998877 ],
[' The Hobbit: The Battle of the Five Armies | 16 th Highest', 695577621 ],
[' The Twilight Saga: Breaking Dawn, Part 2 | 17 th Highest', 693524737 ],
[' Inside Out | 18 th Highest', 679235992 ],
[' Deadpool 2 | 19 th Highest', 676680557 ],
[' Inception | 20 th Highest', 675524642 ],
[' Wonder Woman | 21 th Highest', 671133378 ],
[' Guardians of the Galaxy Vol 2 | 22 th Highest', 662316233 ],
[' Ice Age 2: The Meltdown | 23 th Highest', 652998756 ],
[' Fast and Furious 6 | 24 th Highest', 629300444 ],
[' Transformers: Revenge of the Fallen | 25 th Highest', 626519699 ],
[' Coco | 26 th Highest', 623008101 ],
[' Batman v Superman: Dawn of Justice | 27 th Highest', 617500281 ],
[' Madagascar 3: Europe's Most Wanted | 28 th Highest', 601921271 ],
[' Spectre | 29 th Highest', 579620923 ],
[' The Martian | 30 th Highest', 547271443 ],
[' Captain America: The Winter Soldier | 31 th Highest', 544401889 ],
[' Monsters University | 32 th Highest', 543539607 ],
[' Star Wars Ep. II: Attack of the Clones | 33 th Highest', 541695615 ],
[' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe | 34 th Highest', 540539572 ],
[' The Amazing Spider-Man | 35 th Highest', 537890267 ],
[' The Incredibles | 36 th Highest', 522726752 ],
[' Kung Fu Panda 2 | 37 th Highest', 514837547 ],
[' The Amazing Spider-Man 2 | 38 th Highest', 508996336 ],
[' Life of Pi | 39 th Highest', 500912003 ],
[' Pirates of the Caribbean: The Curse of the Black Pearl | 40 th Highest', 494954103 ],
[' Ratatouille | 41 th Highest', 476549695 ],
[' Fantastic Beasts: The Crimes of Grindelwald | 42 th Highest', 452220086 ],
[' Iron Man 2 | 43 th Highest', 451156389 ],
[' Madagascar: Escape 2 Africa | 44 th Highest', 449680774 ],
[' Cinderella | 45 th Highest', 442400000 ],
[' Men in Black 3 | 46 th Highest', 439213485 ],
[' Ready Player One | 47 th Highest', 429290136 ],
[' Puss in Boots | 48 th Highest', 424987477 ],
[' Sherlock Holmes: A Game of Shadows | 49 th Highest', 410663443 ],
[' The Revenant | 50 th Highest', 397938302 ],
[' Godzilla | 51 th Highest', 369076069 ],
[' Clash of the Titans | 52 th Highest', 368214888 ],
[' X-Men: Apocalypse | 53 th Highest', 364537546 ],
[' Bumblebee | 54 th Highest', 363195589 ],
[' Rio 2 | 55 th Highest', 362846291 ],
[' Cars 2 | 56 th Highest', 360155383 ],
[' Teenage Mutant Ninja Turtles | 57 th Highest', 360004754 ],
[' Dunkirk | 58 th Highest', 349837368 ],
[' Ralph Breaks The Internet | 59 th Highest', 349283695 ],
[' San Andreas | 60 th Highest', 346258539 ],
[' Wall-E | 61 th Highest', 341311860 ],
[' Angels & Demons | 62 th Highest', 340875846 ],
[' The Bourne Ultimatum | 63 th Highest', 314043396 ],
[' Kingsman: The Secret Service | 64 th Highest', 310561724 ],
[' Rampage | 65 th Highest', 308056280 ],
[' Thor | 66 th Highest', 299326618 ],
[' Die Another Day | 67 th Highest', 289942139 ],
[' The Wolf of Wall Street | 68 th Highest', 289870414 ],
[' The Matrix Revolutions | 69 th Highest', 277300260 ],
[' Terminator: Genisys | 70 th Highest', 277150894 ],
[' True Lies | 71 th Highest', 265300000 ],
[' Planet of the Apes | 72 th Highest', 262211740 ],
[' PokÃ©mon: Detective Pikachu | 73 th Highest', 261258433 ],
[' The Hangover 3 | 74 th Highest', 259000072 ],
[' Minority Report | 75 th Highest', 256824714 ],
[' Mission: Impossible III | 76 th Highest', 247501348 ],
[' Star Trek | 77 th Highest', 246839614 ],
[' The Adventures of Tintin | 78 th Highest', 243993951 ],
[' I, Robot | 79 th Highest', 243629585 ],
[' Penguins of Madagascar | 80 th Highest', 234942531 ],
[' Tomorrow Never Dies | 81 th Highest', 229504276 ],
[' The World is Not Enough | 82 th Highest', 226730660 ],
[' X-Men Origins: Wolverine | 83 th Highest', 224825760 ],
[' Noah | 84 th Highest', 222831065 ],
[' X-Men | 85 th Highest', 221872367 ],
[' Mad Max: Fury Road | 86 th Highest', 220098020 ],
[' Trolls | 87 th Highest', 219150134 ],
[' Horton Hears a Who | 88 th Highest', 214477886 ],
[' Mulan | 89 th Highest', 213500000 ],
[' Batman Begins | 90 th Highest', 209142722 ],
[' The Perfect Storm | 91 th Highest', 208711434 ],
[' Cars 3 | 92 th Highest', 208541369 ],
[' Brother Bears 1 | 93 th Highest', 204397798 ],
[' Tron: Legacy | 94 th Highest', 200062763 ],
[' Sex and the City 2 | 95 th Highest', 199680778 ],
[' What Lies Beneath | 96 th Highest', 198693989 ],
[' Grown Ups | 97 th Highest', 197223430 ],
[' X-Men: First Class | 98 th Highest', 195408305 ],
[' The Chronicles of Narnia: Prince Caspian | 99 th Highest', 192341288 ],
[' Passengers | 100 th Highest', 192239672 ],
[' Miss Peregrineâs Home for Peculiar Children | 101 th Highest', 185986876 ],
[' The Divergent Series: Insurgent | 102 th Highest', 185075882 ],
[' Lara Croft: Tomb Raider | 103 th Highest', 179330185 ],
[' Bolt | 104 th Highest', 178015029 ],
[' The Curious Case of Benjamin Button | 105 th Highest', 169631958 ],
[' The Fifth Element | 106 th Highest', 168898761 ],
[' Ponyo | 107 th Highest', 168551810 ],
[' Oblivion | 108 th Highest', 167916633 ],
[' Elysium | 109 th Highest', 166192091 ],
[' Chicken Little | 110 th Highest', 164432837 ],
[' Wallace & Gomit: The Curse of the Were-Rabbit | 111 th Highest', 164111171 ],
[' 10,000 B.C. | 112 th Highest', 164065678 ],
[' Chicken Little | 113 th Highest', 160043823 ],
[' The Prince of Egypt | 114 th Highest', 158613188 ],
[' Gnomeo & Juliet | 115 th Highest', 157900000 ],
[' Wrath of the Titans | 116 th Highest', 155270083 ],
[' Pixels | 117 th Highest', 154041804 ],
[' Real Steel | 118 th Highest', 153880341 ],
[' Turbo | 119 th Highest', 151896578 ],
[' Inferno | 120 th Highest', 144519367 ],
[' Bad Boys II | 121 th Highest', 143271982 ],
[' Superman Returns | 122 th Highest', 142085065 ],
[' The Polar Express | 123 th Highest', 141365187 ],
[' Bee Movie | 124 th Highest', 137594577 ],
[' Prince of Persia: Sands of Time | 125 th Highest', 136359676 ],
[' Inside Man | 126 th Highest', 135798265 ],
[' Gone in 60 Seconds | 127 th Highest', 129343008 ],
[' Godzilla: King of the Monsters | 128 th Highest', 129276941 ],
[' Exodus: Gods and Kings | 129 th Highest', 128314513 ],
[' The Incredible Hulk | 130 th Highest', 128073859 ],
[' The Sum of All Fears | 131 th Highest', 125500000 ],
[' RoboCop | 132 th Highest', 122981799 ],
[' Assassinâs Creed | 133 th Highest', 115759682 ],
[' King Arthur | 134 th Highest', 113877963 ],
[' Batman & Robin | 135 th Highest', 113317814 ],
[' You Don't Mess With the Zohan | 136 th Highest', 112910991 ],
[' Stepmom | 137 th Highest', 109745279 ],
[' Ghost Rider | 138 th Highest', 109545589 ],
[' Kingdom of Heaven | 139 th Highest', 108853353 ],
[' The Aviator | 140 th Highest', 98370892 ],
[' The Secret Life of Walter Mitty | 141 th Highest', 96861183 ],
[' Herbie: Fully Loaded | 142 th Highest', 94146816 ],
[' The LEGO Movie 2: The Second Part | 143 th Highest', 91325698 ],
[' Zookeeper | 144 th Highest', 90805525 ],
[' Gangs of New York | 145 th Highest', 86124621 ],
[' Broken Arrow | 146 th Highest', 83345997 ],
[' Master and Commander: The Far Side of the World | 147 th Highest', 77912137 ],
[' Peteâs Dragon | 148 th Highest', 72768975 ],
[' The Interpreter | 149 th Highest', 72753837 ],
[' The Magnificent Seven | 150 th Highest', 72525156 ],
[' The Other Guys | 151 th Highest', 70936470 ],
[' The Spiderwick Chronicles | 152 th Highest', 70339667 ],
[' The Emperor's New Groove | 153 th Highest', 69296573 ],
[' Lara Croft: Tomb Raider: The Cradle of Life | 154 th Highest', 67092943 ],
[' The Time Traveler's Wife | 155 th Highest', 63332135 ],
[' The Divergent Series: Allegiant | 156 th Highest', 62022517 ],
[' The Sorcerer's Apprentice | 157 th Highest', 57986320 ],
[' Ghost in the Shell | 158 th Highest', 57910690 ],
[' Big Fish | 159 th Highest', 53954323 ],
[' The Dark Tower | 160 th Highest', 53461527 ],
[' Spy Game | 161 th Highest', 53049560 ],
[' Watchmen | 162 th Highest', 48976250 ],
[' Charlie Wilson's War | 163 th Highest', 44512771 ],
[' The Island | 164 th Highest', 43018913 ],
[' The Taking of Pelham 123 | 165 th Highest', 42364370 ],
[' Speed 2: Cruise Control | 166 th Highest', 40468000 ],
[' The Wizard of Oz | 167 th Highest', 32172482 ],
[' The Tale of Despereaux | 168 th Highest', 30482317 ],
[' Flushed Away | 169 th Highest', 30357126 ],
[' Miami Vice | 170 th Highest', 28818556 ],
[' Space Chimps | 171 th Highest', 28097693 ],
[' The Tale of Despereaux | 172 th Highest', 26957280 ],
[' The Cat in the Hat | 173 th Highest', 24818283 ],
[' Power Rangers | 174 th Highest', 22531552 ],
[' Curious George 1 | 175 th Highest', 19800000 ],
[' Green Lantern | 176 th Highest', 19535492 ],
[' Hall Pass | 177 th Highest', 19173475 ],
[' The Fox and the Child | 178 th Highest', 16610210 ],
[' Mission to Mars | 179 th Highest', 16000000 ],
[' Seventh Son | 180 th Highest', 13874967 ],
[' Allied | 181 th Highest', 13266661 ],
[' Alexander | 182 th Highest', 12297191 ],
[' Fever Pitch | 183 th Highest', 10071069 ],
[' Legal Eagles | 184 th Highest', 9851591 ],
[' Death Race | 185 th Highest', 7516819 ],
[' Cliffords | 186 th Highest', 3182426 ],
[' Transcendence | 187 th Highest', 3039258 ],
[' Ozzy | 188 th Highest', 2852439 ],
[' Yellow Submarine | 189 th Highest', 1028261 ],
[' Random Hearts | 190 th Highest', -800000 ],
[' Gods of Egypt | 191 th Highest', -1163244 ],
[' Peter Pan | 192 th Highest', -4744515 ],
[' Children of Men | 193 th Highest', -6154989 ],
[' I Spy | 194 th Highest', -9720178 ],
[' Fantastica: A Boonie Bears | 195 th Highest', -12848904 ],
[' Thirteen Days | 196 th Highest', -13445453 ],
[' Downsizing | 197 th Highest', -13537029 ],
[' Mortal Engines | 198 th Highest', -14712583 ],
[' The Oegieloves | 199 th Highest', -18934093 ],
[' Spanglish | 200 th Highest', -20655679 ],
[' Mighty Joe Young | 201 th Highest', -29367963 ],
[' Land of the Lost | 202 th Highest', -30451359 ],
[' Windtalkers | 203 th Highest', -37371735 ],
[' A Boy's Life | 204 th Highest', -47540000 ],
[' R.I.P.D. | 205 th Highest', -50923322 ],
[' Soldier | 206 th Highest', -60376918 ],
[' Stealth | 207 th Highest', -61583254 ],
[' The Alamo | 208 th Highest', -68088638 ],
[' Renegades | 209 th Highest', -75978328 ],

In [170]:
%%HTML
src="https://code.jpuery.com/jpue<script ry-3.1.1.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="c1"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [171]:
%%js
Highcharts.chart('c1',{ // name of graph
    chart:{
        type:'column', // makes the graph column
       // adjusting the graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:25,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Lowest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // allows the graph to be one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Lowest Profits',
        color :'#0F52BA', // the color of the graph
           data:[
// the name and amount of profit made in integer of the least most profitable movies
            [' Miami Vice|170th Highest', 28818556 ],
            [' Space Chimps|171th Highest', 28097693 ],
            [' The Tale of Despereaux|172th Highest', 26957280 ],
            [' The Cat in the Hat|173th Highest', 24818283 ],
            [' Power Rangers|174th Highest', 22531552 ],
            [' Curious George 1|175th Highest', 19800000 ],
            [' Green Lantern|176th Highest', 19535492 ],
            [' Hall Pass|177th Highest', 19173475 ],
            [' The Fox and the Child|178th Highest', 16610210 ],
            [' Mission to Mars|179th Highest', 16000000 ],
            [' Seventh Son|180th Highest', 13874967 ],
            [' Allied|181th Highest', 13266661 ],
            [' Alexander|182th Highest', 12297191 ],
            [' Fever Pitch|183th Highest', 10071069 ],
            [' Legal Eagles|184th Highest', 9851591 ],
            [' Death Race|185th Highest', 7516819 ],
            [' Cliffords|186th Highest', 3182426 ],
            [' Transcendence|187th Highest', 3039258 ],
            [' Ozzy|188th Highest', 2852439 ],
            [' Yellow Submarine|189th Highest', 1028261 ]
         ]
    }]
        
});

# Blueprint: What Movie is the most Successful.

Just because a movie has made the most profit dosen't mean it is more profitable than a movie that made less profit and or revenue. These were the five main factors that were used to better understand what movie was the most successful. The cost, the revenue, the profit, the gross profit margin percentage which is how much of the revenue is each movie walking away in percentageand the profit percenatge by cost which is comparing the profit with the cost in percentage. 
 
This is the blueprint for creating the elevnth, twelith, thirthith and fourthith visualization. Highcharts will be used to create these graphs.  

__Blueprint:__
   - The factors are split into half when it comes to what type of graph that will be used to analyze the data. The profit, revenue and cost varaiables will be analyzed using highcharts Combination Chart. This chart allows different combinations of senories to be combined in a single chart. This chart is a set of column series overlaid by a line and a pie chart. The line in Highchart was designed to illustrate the column averages while the pie is illustrating the column totals. However in this project the pie sereis will not be used and there will be two column series overlaid by a line series. The two columns will be revenue and profit, the line series will be the cost of all the movies in the blueprint. Like every other graph that used Highchart visualization, they all have two different types of code, HTML and javascript. The HTML section is very similar to all the previous graphs expect two main factors, the HTML code that allows the combination graph to be displayed is;
          <script src="https://code.highcharts.com/modules/series-label.js"></script>
          <script type="text/javascript" src="js/script.js"></script>
The other factors are the two different divs id for the combination chart;
          <div id="x1" display; inline-block></div>
          <div id="no1" display; inline-block></div>
 These are the names of the two combination chart that analyze ten movies each of the Top 20 Most     Profitable Movies.The javascript section for these graphs consist of four main subsection. The categories, the two types in the series section that are columns and the type in the series section that is spline. The categories subsection is a list of all the names of the movies that will be analyzed. The two types in the in the series subsection that are columns are the profit and revenue of all the movies and the third type in the spline series subsection is the cost of all the movies. 
     
     
                series:[{
                   type:'column',
                   color:"#111E6C",
                   name:'Profit',
                   data:                                  
                   [2351345279,2303109231,1148258224, 1135772799,1015392272,984846267,912044677,894039076,
          890069413,878000000]
      },{
          type:'column'
          color:Highcharts.getOptions().colors[1],
          name:'Revenue',
          data:[2776345279,2366000000,1348258224,
          1305772799,1215392272,1234846267,1027044677,1104039076,1140069413,1078000000]
     },{
          type:'spline',
          color:'gold',
          name:'Cost',
          data:[425000000,62890769,200000000,170000000,200000000,250000000,115000000,210000000,
                    250000000,200000000],


   The other factors are the two different divs id for the column chart;
            
            <div id="n1" display; inline-block></div>
            <div id="xo1" display; inline-block></div>

   The Gross Profit Margin Percentage and the Profit Percentage by Cost will all be analyzed using        highcharts combination chart but with only column. The two column will be The Percentage of Gross      Profit Margin and Profit by Cost of each movie.
   
   The javascript section for the columns chart consist of the category subsection which is the names      of all the movies. 
      
      categories:['Zootopia| 11th Highest',
      'Finding Nemo| 12th Highest',
      'The Jungle Book| 13th Highest',
      'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
      'Ice Age: Dawn of the Dinosaurs| 15th Highest',
      'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
      'The Hobbit: The Battle of the Five Armies| 17th Highest',
      'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
      'Inside Out| 19th Highest',
      'Deadpool 2| 20th Highest']

   It also consist of the series subsection that has two factors, the type column which is where the      gross profit margin percentage and profit by cost is scripted.
      
      series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[85.0, 97.0, 85.0, 87.0, 84.0, 80.0, 89.0, 81.0, 78.0, 81.0]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[553.0, 3662.0, 574.0, 668.0, 508.0, 394.0, 793.0, 426.0, 356.0, 439.0]
       }]

In [151]:
#getting the profit of the movie
for i in new1[:21]:
    print(all_actionadventure_info1.Profit[i[0]])

2351345279
2303109231
1148258224
1135772799
1015392272
984846267
912044677
894039076
890069413
878000000
869429616
842429370
787854547
778210985
769701857
733998877
695577621
693524737
679235992
676680557
675524642

In [152]:
#getting the revenue of the movie
for i in new1[:21]:
    print(all_actionadventure_info1.Total_gross[i[0]])

2776345279
2366000000
1348258224
1305772799
1215392272
1234846267
1027044677
1104039076
1140069413
1078000000
1019429616
936429370
962854547
887210985
859701857
848998877
945577621
829724737
854235992
786680557
835524642

In [156]:
#getting the cost of the movie
for i in new1[:21]:
    print(all_actionadventure_info1.Buget[i[0]])

425000000
62890769
200000000
170000000
200000000
250000000
115000000
210000000
250000000
200000000
150000000
94000000
175000000
109000000
90000000
115000000
250000000
136200000
175000000
110000000
160000000

In [171]:
#getting profit percent by cost of the top 20 highest most profitable movie
new5 = []
for i in new1:
    new5.append(round(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Buget[i[0]]
         *100,0))
new5[11:21]

[896.0, 450.0, 714.0, 855.0, 638.0, 278.0, 509.0, 388.0, 615.0, 422.0]

In [170]:
#getting gross profit margin percent of the top 20 highest most profitable movie
new6 = []
for i in new1:
    new6.append(round(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Total_gross[i[0]]
         *100,0))
new6[11:21]

[90.0, 82.0, 88.0, 90.0, 86.0, 74.0, 84.0, 80.0, 86.0, 81.0]

Using a for loop to get the names of the highest most profitable and putting it into html code

In [149]:
for i,x in enumerate(new2[:21]):
    print("'"+new2[i]+'|',i,'th','Highest'+"',")

'Avatar| 0 th Highest',
'The Sound of Music| 1 th Highest',
'Black Panther| 2 th Highest',
'Jurassic World: Fallen Kingdom| 3 th Highest',
'Iron Man 3| 4 th Highest',
'The Fate of the Furious| 5 th Highest',
'Star Wars Ep. I: The Phantom Menace| 6 th Highest',
'Transformers: Age of Extinction| 7 th Highest',
'Captain America: Civil War| 8 th Highest',
'Thor:Ragnarok| 9 th Highest',
'Zootopia| 10 th Highest',
'Finding Nemo| 11 th Highest',
'The Jungle Book| 12 th Highest',
'The Lord of the Rings: The Fellowship of the Ring| 13 th Highest',
'Ice Age: Dawn of the Dinosaurs| 14 th Highest',
'Star Wars Ep. III: Revenge of the Sith| 15 th Highest',
'The Hobbit: The Battle of the Five Armies| 16 th Highest',
'The Twilight Saga: Breaking Dawn, Part 2| 17 th Highest',
'Inside Out| 18 th Highest',
'Deadpool 2| 19 th Highest',
'Inception| 20 th Highest',

In [172]:
%%HTML
<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="x1" display; inline-block></div>
    <div id="n1" display; inline-block></div>
    <div id="no1" display; inline-block></div>
    <div id="xo1" display; inline-block></div>
    <p class="highcharts-description">
    </p>
</figure>

In [195]:
%%js
Highcharts.chart('x1',{ // name of graph
    title:{
        text:"What Movie Is The Most Successful?"
    },
    xAxis:{
        // name of movies
        categories:['Avatar|1st Highest',
                  'The Sound of Music|2nd Highest',
                  'Black Panther|3rd Highest',
                  'Jurassic World:Fallen Kingdom|4th Highest',
                  'Iron Man 3|5th Highest',
                  'The Fate of the Furious|6th Highest',
                  'Star Wars Ep. I:The Phantom Menace|7th Highest',
                  'Transformers:Age of Extinction|8th Highest',
                  'Captain America:Civil War|9th Highest',
                  'Thor: Ragnarok|10th Highest'],
        crosshair:{
            // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column', // makes graph to be colunm 
        color:"#111E6C",// color of colunm
        name:'Profit', // name of colunm
        // profit of each movie in integer 
        data:[2351345279,2303109231,1148258224,1135772799,1015392272,984846267,912044677,894039076,890069413,
             878000000]
    },{
        type:'column',// makes graph to be colunm
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[2776345279,2366000000,1348258224,1305772799,1215392272,1234846267,1027044677,1104039076,
              1140069413,1078000000]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost', // name of spline
        // cost of each movie in integer
        data:[425000000,62890769,200000000,170000000,200000000,250000000,115000000,210000000,
              250000000,200000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [6]:
%%js
Highcharts.chart('n1',{ //name of graph
        title:{
            text:""
        },
        xAxis:{
        // name of movies 
           categories:['Avatar| 1st Highest',
              'The Sound of Music| 2nd Highest',
              'Black Panther| 3rd Highest',
              'Jurassic World: Fallen Kingdom| 4th Highest',
              'Iron Man 3| 5th Highest',
              'The Fate of the Furious| 6th Highest',
              'Star Wars Ep. I: The Phantom Menace| 7th Highest',
              'Transformers: Age of Extinction| 8th Highest',
              'Captain America: Civil War| 9th Highest',
              'Thor:Ragnarok| 10th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#3FE0D0',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
           // Gross Profit Margin Percentage of each movie in integer
           data:[85.0, 97.0, 85.0, 87.0, 84.0, 80.0, 89.0, 81.0, 78.0, 81.0]
       },{
           type:'column',// makes graph to be colunm
           color:'#008081',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[553.0, 3662.0, 574.0, 668.0, 508.0, 394.0, 793.0, 426.0, 356.0, 439.0]
       }]  
    
   });

In [175]:
%%js
Highcharts.chart('no1',{ //name of graph
    title:{
        text:""
    },
    xAxis:{
        // name of movies 
        categories:['Zootopia| 11th Highest',
                    'Finding Nemo| 12th Highest',
                    'The Jungle Book| 13th Highest',
               'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
                    'Ice Age: Dawn of the Dinosaurs| 15th Highest',
                   'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
                    'The Hobbit: The Battle of the Five Armies| 17th Highest',
                    'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
                    'Inside Out| 19th Highest',
                    'Deadpool 2| 20th Highest'],
        crosshair:{
             // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',// makes graph  colunm 
        color:'#111E6C',// color of colunm
        name:'Profit',// name of column
        // profit of each movie in integer 
        data:[869429616,842429370,787854547,778210985,769701857,733998877,
             695577621,693524737,679235992,676680557]
    },{
        type:'column',// makes graph  colunm 
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[1019429616,936429370,962854547,887210985,859701857,848998877,945577621,
              829724737,854235992,786680557]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost',// name of spline
        // cost of each movie in integer
        data:[150000000,94000000,175000000,109000000,90000000,115000000,
              250000000,136200000,175000000,110000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [176]:
%%js
Highcharts.chart('xo1',{//name of graph
        title:{
            text:""
        },
        xAxis:{
           // name of movies 
           categories:['Zootopia| 11th Highest',
                      'Finding Nemo| 12th Highest',
                      'The Jungle Book| 13th Highest',
                      'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
                      'Ice Age: Dawn of the Dinosaurs| 15th Highest',
                      'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
                      'The Hobbit: The Battle of the Five Armies| 17th Highest',
                      'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
                      'Inside Out| 19th Highest',
                      'Deadpool 2| 20th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
            // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#3FE0D0',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
          // Gross Profit Margin Percentage of each movie in integer
           data:[90.0, 82.0, 88.0, 90.0, 86.0, 74.0, 84.0, 80.0, 86.0, 81.0]
       },{
           type:'column',// makes graph to be colunm 
           color:'#008081',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[896.0, 450.0, 714.0, 855.0, 638.0, 278.0, 509.0, 388.0, 615.0, 422.0]
       }]  
    
   });

# Blueprint: Number of Tickets Sold.

This analysis objective is to axknowledge what system rating that best suit this genre, this allows the ideology of what kind of audience is drawn to this genre, to specify the audience and make them the target focus. This is the blueprint for creating the last visualization of this project, Highcharts will be used to create this graph.

__Blueprint:__
   - The graph used for this visualization is a Highchart Donut chart, it is basically a hallow pie chart which is commonly referred to as a donut charts. This pie charts also ahs an inner chart resulting in a hierachical type of visualization.
   - The first approach th this chart is the HTML section whcih is very simple, it has the div id which is where the graph is named and the style and height should be chosen.
               <div id='hraph2' style="height:700px"></div>
   - The second approach is the javascript code, it is divided into two sections the inner pie and the outer pie. The inner pie shows how much each sytem ratings occupies the most total tickets sold in percentage comparied to the total tickest sold in the whole entire parent dataframe '_all_actionadventure_info1_'. The outer pie shows the individule movies in the category the amount of tickets they sold.
        - <u>__Javascript Section__</u>:
         
             -<u>_First Section_</u>: The first section is a list called data it has consist of the name of the system ratings and the percenatge of tickets sold compared to the total of tickets sold. The color and the sliced adjustments and it also has the adjustments of the size of the ring pie.
                      data:[{
                  name:'System Rating: R',
                  y:28.0,
                  sliced:true,
                  color: '#4682B4',}
            
            -<u>_Second Section_</u>: The second section is a list also called data it requires the name of all the movies, the amount of tickest they sold , the option to slice that section and the color of the slice .       
                     data:[{ 
               name: ' Avatar ' ,
               y: 213565021 ,
               sliced:true,
               selected: true,
               color:"#4682B4",}

In [2]:
# getting the number of tickets sold in the r-rated category
var = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var.append(no_tickets[i])
len(var)

NameError: name 'all_actionadventure_info1' is not defined

In [3]:
# getting the name of the r-rated movies 
var1 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var1.append(all_actionadventure_info1['Name'][i])
len(var1)

NameError: name 'all_actionadventure_info1' is not defined

In [4]:
# getting the profit of thr r-rated movies
var2 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'R':
        var2.append(all_actionadventure_info1['Profit'][i])
len(var2)

NameError: name 'all_actionadventure_info1' is not defined

Using a for loop to put the name and the number of tickets sold in the R-rated genre in html code which will be pasted in the cell below.

In [5]:
for i,x in enumerate(range(len(var))):
    print('         },{ \n           name:',"'",var1[i],"'",','+'\n           y:',var[i],','+'\n           sliced:true,'+'\n           color:"#468284",')

In [6]:
# getting the number of tickets sold in the NR-rated category
var3 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var3.append(no_tickets[i])
len(var3)

NameError: name 'all_actionadventure_info1' is not defined

In [7]:
# getting the name of the NR-rated movies 
var4 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var4.append(all_actionadventure_info1['Name'][i])
len(var4)

NameError: name 'all_actionadventure_info1' is not defined

In [8]:
# getting the profit of thr NR-rated movies
var5 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'NR':
        var5.append(all_actionadventure_info1['Profit'][i])
len(var5)

NameError: name 'all_actionadventure_info1' is not defined

Using a for loop to put the name and the number of tickets sold in the NR-rated genre in html code which will be pasted in the cell below.

In [9]:
for i,x in enumerate(range(len(var4))):
    print('         },{ \n           name:',"'",var4[i],"'",','+'\n           y:',var3[i],',','\n           sliced:true,'+'\n           color:"#1D2951",')

In [10]:
# getting the number of tickets sold in the pg-rated category
var6 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var6.append(no_tickets[i])
len(var6)

NameError: name 'all_actionadventure_info1' is not defined

In [11]:
# getting the name of the pg-rated movies 
var7 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var7.append(all_actionadventure_info1['Name'][i])
len(var7)

NameError: name 'all_actionadventure_info1' is not defined

In [12]:
# getting the profit of thr pg-rated movies
var8 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG':
        var8.append(all_actionadventure_info1['Profit'][i])
len(var8)

NameError: name 'all_actionadventure_info1' is not defined

Using a for loop to put the name and the number of tickets sold in the PG-rated genre in html code which will be pasted in the cell below.

In [13]:
for i,x in enumerate(range(len(var7))):
    print('         },{ \n           name:',"'",var7[i],"'",','+'\n           y:',var6[i],',','\n           sliced:true,'+'\n           color:"#588BAE",')

In [14]:
# getting the number of tickets sold in the g-rated category
var9 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var9.append(no_tickets[i])
len(var9)

NameError: name 'all_actionadventure_info1' is not defined

In [15]:
# getting the name of the g-rated movies
var10 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var10.append(all_actionadventure_info1['Name'][i])
len(var10)

NameError: name 'all_actionadventure_info1' is not defined

In [16]:
# getting the profit of thr g-rated movies
var11 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'G':
        var11.append(all_actionadventure_info1['Profit'][i])
len(var11)

NameError: name 'all_actionadventure_info1' is not defined

Using a for loop to put the name and the number of tickets sold in the G-rated genre in html code which will be pasted in the cell below.

In [17]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var10[i],"'",','+'\n           y:',var9[i],',','\n           sliced:true,'+'\n           color:"#73C2FB",')

In [18]:
# getting the number of tickets sold in the pg13-rated category
var12 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var12.append(no_tickets[i])
len(var12)

NameError: name 'all_actionadventure_info1' is not defined

In [19]:
# getting the name of the pg13-rated movies
var13 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var13.append(all_actionadventure_info1['Name'][i])
len(var13)

NameError: name 'all_actionadventure_info1' is not defined

In [20]:
# getting the profit of thr pg13-rated movies
var14 = []
for i,x in enumerate(all_actionadventure_info1.System_ratings):
    if x == 'PG-13':
        var14.append(all_actionadventure_info1['Profit'][i])
len(var14)

NameError: name 'all_actionadventure_info1' is not defined

Using a for loop to put the name and the number of tickets sold in the PG-13-rated genre in html code which will be pasted in the cell below.

In [21]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var13[i],"'",','+'\n           y:',var12[i],',','\n           sliced:true,'+'\n           color:"#000080",')

In [207]:
# putting all the number of tickest that each movie made in a list
ttl = var3+var6+var9+var12+var
ttl

[64347669,
 103712171,
 74065734,
 61385239,
 54953991,
 23951168,
 40698159,
 27339100,
 48196130,
 22122660,
 23482314,
 20639578,
 5878211,
 20428758,
 28226349,
 27140851,
 37308058,
 41204880,
 25285495,
 32927406,
 22014776,
 50515047,
 60513889,
 22698145,
 26115714,
 10293714,
 13148959,
 13022813,
 6560571,
 14086509,
 22667752,
 21025399,
 34563586,
 28832751,
 28469078,
 30577027,
 37759680,
 13796702,
 57455482,
 12601427,
 28768765,
 10963966,
 66730791,
 94988174,
 30774059,
 41733657,
 47781261,
 60715419,
 27626363,
 51141350,
 31635264,
 48842623,
 29756893,
 10679750,
 16028530,
 13232501,
 27846159,
 29990032,
 14640438,
 12526128,
 15682920,
 43088876,
 25356304,
 27825435,
 34157184,
 37939607,
 26473087,
 22147433,
 9174359,
 26817660,
 17895616,
 28100000,
 15608538,
 18772446,
 5372693,
 14884615,
 6705652,
 4189459,
 10597613,
 4861538,
 16816399,
 20940264,
 22836336,
 1124852,
 72736740,
 63164106,
 46129290,
 18519976,
 7926097,
 12501935,
 58299251,
 16768178,
 38449028,
 37911253,
 6082821,
 5119581,
 6960178,
 8727810,
 12288098,
 14292174,
 3834738,
 3851621,
 7871703,
 82923077,
 41723077,
 182000000,
 6689022,
 57195354,
 11088217,
 14931629,
 3266154,
 988649,
 15580908,
 14915385,
 98328,
 5369231,
 5934700,
 50846058,
 2277708,
 5007515,
 81993,
 19261369,
 250187,
 2688422,
 24187141,
 40100912,
 67663148,
 16887346,
 55426121,
 65710461,
 23021303,
 12869015,
 32869251,
 40995254,
 16377857,
 22068968,
 12539916,
 22768221,
 20298488,
 12916207,
 72033028,
 1839336,
 66130912,
 12519526,
 78417663,
 44560780,
 25231925,
 14382788,
 18690908,
 79003437,
 35096811,
 23249206,
 16834873,
 27601901,
 8374997,
 31120133,
 14450860,
 11003812,
 13138887,
 3894772,
 117052,
 9193290,
 4180332,
 16886105,
 9534948,
 4636909,
 11411231,
 5578217,
 213565021,
 87697647,
 28775774,
 32103176,
 50324114,
 84926083,
 93491713,
 66332018,
 54538180,
 50170776,
 25873821,
 40329515,
 29503182,
 100444061,
 64271126,
 33242376,
 23849525,
 33226318,
 63824980,
 42691344,
 21020922,
 18332140,
 47762462,
 17657353,
 65307606,
 5971405,
 11720336,
 11574462,
 68246999,
 50405496,
 20697360,
 35784276,
 27862442,
 5349895,
 7327345,
 20299905,
 47286673,
 22207230,
 23346154,
 12084073,
 8153846,
 23036760]

In [208]:
# adding all the number of tickects ech movie made
tt2 = 0
for i in ttl:
    tt2+=i

In [215]:
# average of no tickets of R system rating
v = 0
for i in var:
    v+=i
round(v/tt2*100,0)

28.0

In [216]:
# average of no tickets of NR system rating
v1 = 0
for i in var3:
    v1+=i
round(v1/tt2*100,0)

21.0

In [217]:
# average of no tickets of PG system rating
v2 = 0
for i in var6:
    v2+=i
round(v2/tt2*100,0)

18.0

In [218]:
# average of no tickets of G system rating
v3 = 0
for i in var9:
    v3+=i
round(v3/tt2*100,0)

16.0

In [219]:
# average of no tickets of PG13 system rating
v4= 0
for i in var12:
    v4+=i
round(v4/tt2*100,0)

17.0

In [177]:
%%html
<script src="http://code.highcharts.com/highchart.js"></script>
<div id='hraph2' style="height:700px"></div>

In [8]:
%%js
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'hraph2'//name of graph 
    },
    title:{
        text:'Number of Tickets Sold'
    },
    subtitle:{
        text:'Action & Adventure Genre'
    },
    series:[{
        type:'pie',// makes the graph pie 
        name: 'Percentage of Tickets Sold',
        tooltip:{
            // turns digits to percentage
            valueSuffix:'%'
        },
        shadow: true,
        data:[{
            name:'System Rating: R',// name of category
            y:28.0,// amount of tickets sold in percentage
            sliced:true,
            color: '#4682B4',// color of section
        },{
            name:'System Rating: PG-13',// name of category
            y:17.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#1D2951',// color of section
        },{
            name:'System Rating: PG',// name of category
            y:18.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#588BAE',// color of section
        },{
            name:'System Rating: NR',// name of category
            y:21.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#73C2FB',// color of section
        },{
            name:'System Rating: G',// name of category
            y:16.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#000080',// color of section
        }],
        innerSize:'80%',// size of inner pie
        size:'83%'// size of outer pie
       },{
        type:'pie',
        shadow: true,
        dataLabels: false,
        name: 'No. of Tickets Sold',
        data:[{ 
            name: ' Avatar ' ,// name of movie
           y: 213565021 ,// amount of tickets sold
           sliced:true,
           selected: true,
           color:"#4682B4",// color of section
         },{ 
           name: ' Captain America: Civil War ' ,
           y: 87697647 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Superman Returns ' ,
           y: 28775774 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' The Chronicles of Narnia: Prince Caspian ' ,
           y: 32103176 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Men in Black 3 ' ,
           y: 50324114 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Transformers: Age of Extinction ' ,
           y: 84926083 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Iron Man 3 ' ,
           y: 93491713 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Guardians of the Galaxy Vol 2 ' ,
           y: 66332018 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' The Amazing Spider-Man 2 ' ,
           y: 54538180 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Fantastic Beasts: The Crimes of Grindelwald ' ,
           y: 50170776 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Prince of Persia: Sands of Time ' ,
           y: 25873821 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Ralph Breaks The Internet ' ,
           y: 40329515 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Cars 3 ' ,
           y: 29503182 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Jurassic World: Fallen Kingdom ' ,
           y: 100444061 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Inception ' ,
           y: 64271126 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Terminator: Genisys ' ,
           y: 33242376 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Chicken Little ' ,
           y: 23849525 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Die Another Day ' ,
           y: 33226318 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' The Twilight Saga: Breaking Dawn, Part 2 ' ,
           y: 63824980 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Puss in Boots ' ,
           y: 42691344 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Bad Boys II ' ,
           y: 21020922 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Batman & Robin ' ,
           y: 18332140 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Life of Pi ' ,
           y: 47762462 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Ghost Rider ' ,
           y: 17657353 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Star Wars Ep. III: Revenge of the Sith ' ,
           y: 65307606 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Windtalkers ' ,
           y: 5971405 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' The Taking of Pelham 123 ' ,
           y: 11720336 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Speed 2: Cruise Control ' ,
           y: 11574462 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' The Lord of the Rings: The Fellowship of the Ring ' ,
           y: 68246999 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' The Martian ' ,
           y: 50405496 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' 10,000 B.C. ' ,
           y: 20697360 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Bumblebee ' ,
           y: 35784276 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Planet of the Apes ' ,
           y: 27862442 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Land of the Lost ' ,
           y: 5349895 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Peter Pan ' ,
           y: 7327345 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' The Fifth Element ' ,
           y: 20299905 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' The Incredibles ' ,
           y: 47286673 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' What Lies Beneath ' ,
           y: 22207230 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Mulan ' ,
           y: 23346154 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Lara Croft: Tomb Raider: The Cradle of Life ' ,
           y: 12084073 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Mission to Mars ' ,
           y: 8153846 ,
           sliced:true,
           color:"#4682B4",
         },{ 
           name: ' Horton Hears a Who ' ,
           y: 23036760 ,
           sliced:false,
           color:"#4682B4",
         },{ 
           name: ' Transformers: Revenge of the Fallen ' ,
           y: 64347669 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Black Panther ' ,
           y: 103712171 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' The Jungle Book ' ,
           y: 74065734 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Coco ' ,
           y: 61385239 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Captain America: The Winter Soldier ' ,
           y: 54953991 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' The Polar Express ' ,
           y: 23951168 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Godzilla ' ,
           y: 40698159 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' X-Men: First Class ' ,
           y: 27339100 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Ratatouille ' ,
           y: 48196130 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Bee Movie ' ,
           y: 22122660 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Wrath of the Titans ' ,
           y: 23482314 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Exodus: Gods and Kings ' ,
           y: 20639578 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Stealth ' ,
           y: 5878211 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' The Incredible Hulk ' ,
           y: 20428758 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Penguins of Madagascar ' ,
           y: 28226349 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Noah ' ,
           y: 27140851 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Teenage Mutant Ninja Turtles ' ,
           y: 37308058 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Sherlock Holmes: A Game of Shadows ' ,
           y: 41204880 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' The Perfect Storm ' ,
           y: 25285495 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Rampage ' ,
           y: 32927406 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Elysium ' ,
           y: 22014776 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Star Wars Ep. II: Attack of the Clones ' ,
           y: 50515047 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Deadpool 2 ' ,
           y: 60513889 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' The Divergent Series: Insurgent ' ,
           y: 22698145 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Tomorrow Never Dies ' ,
           y: 26115714 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' The Cat in the Hat ' ,
           y: 10293714 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' The Other Guys ' ,
           y: 13148959 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' The Emperor\'s New Groove ' ,
           y: 13022813 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Mortal Engines ' ,
           y: 6560571 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Gangs of New York ' ,
           y: 14086509 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Sex and the City 2 ' ,
           y: 22667752 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Lara Croft: Tomb Raider ' ,
           y: 21025399 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Thor ' ,
           y: 34563586 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' X-Men Origins: Wolverine ' ,
           y: 28832751 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Mad Max: Fury Road ' ,
           y: 28469078 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Mission: Impossible III ' ,
           y: 30577027 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Angels & Demons ' ,
           y: 37759680 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Flushed Away ' ,
           y: 13796702 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Madagascar 3: Europe\'s Most Wanted ' ,
           y: 57455482 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Miami Vice ' ,
           y: 12601427 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' The Adventures of Tintin ' ,
           y: 28768765 , 
           sliced:true,
           color:"#1D2951",
         },{ 
           name: ' Power Rangers ' ,
           y: 10963966 , 
           sliced:false,
           color:"#1D2951",
         },{ 
           name: ' Batman v Superman: Dawn of Justice ' ,
           y: 66730791 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The Fate of the Furious ' ,
           y: 94988174 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Tron: Legacy ' ,
           y: 30774059 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' X-Men: Apocalypse ' ,
           y: 41733657 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Iron Man 2 ' ,
           y: 47781261 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Fast and Furious 6 ' ,
           y: 60715419 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Batman Begins ' ,
           y: 27626363 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Kung Fu Panda 2 ' ,
           y: 51141350 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' PokÃ©mon: Detective Pikachu ' ,
           y: 31635264 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Pirates of the Caribbean: The Curse of the Black Pearl ' ,
           y: 48842623 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Star Trek ' ,
           y: 29756893 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Gods of Egypt ' ,
           y: 10679750 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The Aviator ' ,
           y: 16028530 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The Divergent Series: Allegiant ' ,
           y: 13232501 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The Hangover 3 ' ,
           y: 27846159 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The Wolf of Wall Street ' ,
           y: 29990032 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The LEGO Movie 2: The Second Part ' ,
           y: 14640438 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The Spiderwick Chronicles ' ,
           y: 12526128 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' King Arthur ' ,
           y: 15682920 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Cars 2 ' ,
           y: 43088876 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The Curious Case of Benjamin Button ' ,
           y: 25356304 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The World is Not Enough ' ,
           y: 27825435 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The Bourne Ultimatum ' ,
           y: 34157184 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Clash of the Titans ' ,
           y: 37939607 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Trolls ' ,
           y: 26473087 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Oblivion ' ,
           y: 22147433 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Allied ' ,
           y: 9174359 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' I, Robot ' ,
           y: 26817660 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Gone in 60 Seconds ' ,
           y: 17895616 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' True Lies ' ,
           y: 28100000 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' You Don\'t Mess With the Zohan ' ,
           y: 15608538 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Pixels ' ,
           y: 18772446 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Children of Men ' ,
           y: 5372693 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' The Sum of All Fears ' ,
           y: 14884615 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Hall Pass ' ,
           y: 6705652 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Downsizing ' ,
           y: 4189459 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' Peteâs Dragon ' ,
           y: 10597613 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Random Hearts ' ,
           y: 4861538 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' The Prince of Egypt ' ,
           y: 16816399 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Grown Ups ' ,
           y: 20940264 , 
           sliced:false,
           color:"#588BAE",
         },{ 
           name: ' X-Men ' ,
           y: 22836336 , 
           sliced:true,
           color:"#588BAE",
         },{ 
           name: ' Soldier ' ,
           y: 1124852 , 
           sliced:false,
           color:"#588BAE",
          },{ 
           name: ' The Hobbit: The Battle of the Five Armies ' ,
           y: 72736740 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Wonder Woman ' ,
           y: 63164106 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Madagascar: Escape 2 Africa ' ,
           y: 46129290 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Assassinâs Creed ' ,
           y: 18519976 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Transcendence ' ,
           y: 7926097 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' The Magnificent Seven ' ,
           y: 12501935 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Amazing Spider-Man ' ,
           y: 58299251 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' The Sorcerer\'s Apprentice ' ,
           y: 16768178 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Dunkirk ' ,
           y: 38449028 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Rio 2 ' ,
           y: 37911253 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' R.I.P.D. ' ,
           y: 6082821 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Thirteen Days ' ,
           y: 5119581 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Tale of Despereaux ' ,
           y: 6960178 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' The Dark Tower ' ,
           y: 8727810 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Stepmom ' ,
           y: 12288098 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Inside Man ' ,
           y: 14292174 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Legal Eagles ' ,
           y: 3834738 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Fever Pitch ' ,
           y: 3851621 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Time Traveler\'s Wife ' ,
           y: 7871703 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Thor:Ragnarok ' ,
           y: 82923077 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Cinderella ' ,
           y: 41723077 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' The Sound of Music ' ,
           y: 182000000 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Tale of Despereaux ' ,
           y: 6689022 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Monsters University ' ,
           y: 57195354 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Herbie: Fully Loaded ' ,
           y: 11088217 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Wallace & Gomit: The Curse of the Were-Rabbit ' ,
           y: 14931629 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' A Boy\'s Life ' ,
           y: 3266154 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Ozzy ' ,
           y: 988649 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Ponyo ' ,
           y: 15580908 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Gnomeo & Juliet ' ,
           y: 14915385 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Yellow Submarine ' ,
           y: 98328 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Curious George 1 ' ,
           y: 5369231 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Fantastica: A Boonie Bears ' ,
           y: 5934700 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Ice Age 2: The Meltdown ' ,
           y: 50846058 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Fox and the Child ' ,
           y: 2277708 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Space Chimps ' ,
           y: 5007515 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' The Oegieloves ' ,
           y: 81993 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Brother Bears 1 ' ,
           y: 19261369 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Cliffords ' ,
           y: 250187 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' The Wizard of Oz ' ,
           y: 2688422 , 
           sliced:false,
           color:"#73C2FB",
         },{ 
           name: ' Chicken Little ' ,
           y: 24187141 , 
           sliced:true,
           color:"#73C2FB",
         },{ 
           name: ' Wall-E ' ,
           y: 40100912 , 
           sliced:false,
           color:"#73C2FB",
        },{ 
            name: ' Spectre ' ,
           y: 67663148 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Green Lantern ' ,
           y: 16887346 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' The Chronicles of Narnia: The Lion, the Witch and the Wardrobe ' ,
           y: 55426121 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Inside Out ' ,
           y: 65710461 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Godzilla: King of the Monsters ' ,
           y: 23021303 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Alexander ' ,
           y: 12869015 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' The Matrix Revolutions ' ,
           y: 32869251 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' The Revenant ' ,
           y: 40995254 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Master and Commander: The Far Side of the World ' ,
           y: 16377857 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Turbo ' ,
           y: 22068968 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' The Island ' ,
           y: 12539916 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Miss Peregrineâs Home for Peculiar Children ' ,
           y: 22768221 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Real Steel ' ,
           y: 20298488 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Ghost in the Shell ' ,
           y: 12916207 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Finding Nemo ' ,
           y: 72033028 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' The Alamo ' ,
           y: 1839336 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           y: 66130912 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' The Interpreter ' ,
           y: 12519526 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Zootopia ' ,
           y: 78417663 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Ready Player One ' ,
           y: 44560780 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Bolt ' ,
           y: 25231925 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Watchmen ' ,
           y: 14382788 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' RoboCop ' ,
           y: 18690908 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Star Wars Ep. I: The Phantom Menace ' ,
           y: 79003437 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' San Andreas ' ,
           y: 35096811 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Passengers ' ,
           y: 23249206 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Kingdom of Heaven ' ,
           y: 16834873 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Minority Report ' ,
           y: 27601901 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Seventh Son ' ,
           y: 8374997 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Kingsman: The Secret Service ' ,
           y: 31120133 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' The Secret Life of Walter Mitty ' ,
           y: 14450860 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Spy Game ' ,
           y: 11003812 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Zookeeper ' ,
           y: 13138887 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Mighty Joe Young ' ,
           y: 3894772 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Renegades ' ,
           y: 117052 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Charlie Wilson\'s War ' ,
           y: 9193290 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Spanglish ' ,
           y: 4180332 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Inferno ' ,
           y: 16886105 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Big Fish ' ,
           y: 9534948 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' I Spy ' ,
           y: 4636909 , 
           sliced:false,
           color:"#000080",
         },{ 
           name: ' Broken Arrow ' ,
           y: 11411231 , 
           sliced:true,
           color:"#000080",
         },{ 
           name: ' Death Race ' ,
           y: 5578217 , 
           sliced:false,
           color:"#000080"
        }],
    innerSize:'93%',// size of inner pie
    size:'100%'// size of outer pie
    }]
});