  # Objective

__Microsoft sees all the big companies creating original video content, and they want to get in on the fun. They have decided to create a new movie studio, but the problem is they don't know anything about creating movies. They have hired you to help them better understand the movie industry. Your team is in charge with doing data analysis that explores what type of films are currently doing the best at the box office. You must then translate
those findings into actionable insights that the CEO can use when deciding what type of films they should be creating.__

# Datasets

There are 10 datasests in this project 

_Name.basics.csv_
  - _Colunms in the dataset_
     - _nconst_
     - _primary_name_
     - _birth_year_
     - _death_year_
     - _primary_profession_
     - _known_for_titles_

_Bom.movie_gross.csv_
   - _Colunms in the dataset_
      - _title_
      - _studio_
      - _domestic_gross_
      - _foreign_gross_
      - _year_
     
_Rt.movie_info.tsv_
   - _Columns in the dataset_
     - _id_
     - _synopsis_
     - _rating_
     - _genre_
     - _director_
     - _writer_
     - _theater_date_
     - _currency_
     - _box_office_
     - _runtime_
     - _studio_
     
_Title.akas.csv_
   - _Columns in the dataset_
     - _title_id_
     - _ordering_
     - _title_
     - _region_
     - _language_
     - _types_
     - _attributes_
     - _is_original_title_
     
_Title.basics.csv_
  - _Columns in the dataset_
    - _tconst_
    - _primary_title_
    - _original_title_
    - _start_year_
    - _runtime_mintues_
    - _genres_
    
_Title.crew.csv_
  - _Columns in the dataset_
    - _tconst_
    - _directors_
    - _writers_
    
_Title.principals.csv_
  - _Columns in the dataset_
    - _tconst_
    - _ordering_
    - _nconst_
    - _category_
    - _job_
    - _charactors_

_Title.ratings.csv_
  - _Columns in the dataset_
    - _tconst_
    - _averagerating_
    - _numvoters_
    
_Tmdb.movies.csv_
  - _Columns in the dataset_
    - _genre_ids_
    - _id_
    - _original_language_
    - _original_title_
    - _popularity_
    - _release_date_
    - _title_
    - _vote_average_
    - _vote_count_
    
_Tn.movie_budgets_
   - _Columns in the dataset_
     - _id_
     - _release_date_
     - _movie_
     - _production_budget_
     - _domestic_gross_
     - _worldwide_gross_

# Approaches

Based on the datasets there are nine main genres; Comedys, Drama, Comedy, Documentry, Classics, Art House and International, Musical and Performing Arts, Horror, Mystrey and Suspense, Animation, Special Interest, Kids and Family and there are also five main System Ratings; System R Rating, System PG-13 Rating, System PG Rating, System G Rating and System NR Rating. In this Project the genres that are being chosen are Comedy, Drama, Comedy, Classics and Art House and International which will all have indivisual data analysis based on the same data visualization concepts and the system ratings are being compared among one another and also analyised to view which one best fit the genres. There will be eleven differnt graphs for each genres describing and protarying insights on the activity of the data.

## Graphs
These are the elven main graphs.
  - __Profit Percentage baised on cost__:
     - This data visualization shows the name, cost, profit, the type of system rating and profit percenatge by cost. The purpose of this notion is to view past the profit and better understand how successful the movie really is by analysing the cost and calculating how much more was made compared to it. This allows the idea of higher profit dosn't mean more profitable to be considered as a justification based on the results proving so. The system rating were added to be compared among eachother, to observe which one was better and to also know which one was the best fit for any particular genere by calculating the average of the reults of each system rating
   
  
  
  - __Gross Profit Margin Percentage__:
     - This data visualization has two pionts about the movie on one panel. The fisrt piont shows the name, amount of profit made in dollars, type of system rating and Gross Profit Margin Percentage. The other piont shows the name, revenue made in dollars and the type of system rating. The graph was designed this way to compare the profit amount against the revenue amount, allowing the Gross Profit Margin Percntage to be more visible and inderectly see the expenses made from a graph perpsective.
     
 
 - __Budget and Revenue of Movies__:
    - This graph is a scatter plot with an x-axis and a y-axis, the x-axis is the revenue of the movies in dollars and the y-axis is the budget of the movies in dollars. This graph is a blueprint to better understand  wether the amount of money spent on the movie effected the amount of revenue generted and to also spot movies that spent less money than the average with a higher revenue.
 
 
 - __Revenue of Movies/Budget of Movies__:
    - The revenue graph has an x-axis that shows the revnue of the movies, name and the type of system ratings with no y-axis. The budget graph has an x-axis that shows the budget of the movies and also the name and system ratings with no y-axis. Both graphs have a table split into catagories of the system ratings showing were they are postions in the axis. These graphs were constructed to predict how much will be made depending on how much is spent based on the pattern of budget of movies to revenue of movies and to indirectly spot anomalies.
    
 
 - __Movies that mdae Profit__:
    - This graph simply shows all the movies that made profit, from the highest to the lowest.


 - __Movies that had losses__:
   - This graph is a colunm graph that shows the movies that did not make any profit. It shows the cost of the movie, revenue and by how much was not made to prevent a loss by the movie. It also shows the name and system ratings it belongs to. This dilema was created to percieve what agenda was not making any money, to try and understand the other half of film industry that is overlooked.
   
   
 
 - __Top 20 Highest Profitable Movies/ Top 20 Lowest Profitable Mobies__:
    - The top 20 highest profitable graph is a 3D chart that shows the top 20 most profitable movies with an x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. The top 20 lowest profitable graph is also a 3D chart that shows the top 20 movies that had the lowest profit, with the x-axis being the names of the movie and the y-axis being the amount of profit made in dollars. These graphs were creted to really spot what movis were the kings and queens of the movie industry and what movie was barely making sales. This brings a lot of questioning to what each of the movies did do britiantally or failed to do.
    

- __Most Successful Moive__:
   - This graph is built up of two sections, the first section is an x-axis whcih shows the names and a y-axis which shows the budget, revenu and profit of the movies in dollars, the second section compares the gross profit margin percentage to the profit percnatge by cost of the movies whcih is all compared to all other movies in the data frame. The sections data is based on the top 20 most profitable movies. The concept of the visualization is to  dive deep into detail to anlayze what movie were actually more succesfull than the other, other than just focusing on the highets profits made. Factors like budget and revenue expressed in gross profit margin percentage and proft percentage by cost allows the differences among the most profitable movies to become more disguishable, whcih can open a new perspcetive on anyalzing numbers.
   
 
 - __Tickets Sold__:
    - This graph simply shows what system ratings have the highest tickets sold to better understand what audience best fist this genre through the sales of the system ratings.

Before starting any data extracting, liabreis such as Altair, Pandas, Pandas_highcharts, Collections need to be installed to help create great insightful interactive graphs.

In [1]:
import altair as alt # used to create interactive graphs
import pandas as pd # used to make for dataframes
import collections# used to put data into sections
import matplotlib.pyplot as plt# used to make graphs

In [2]:
# helps create highcharts graphs
from pandas_highcharts.core import serialize
from pandas_highcharts.display import display_charts
import json

Before the graphs are made the data is extracted from the rt.movie_info.tsv file and made into a dataframe.

In [3]:
# The data frame is called movie_info
movie_info = pd.read_csv("rt.movie_info.tsv.gz",error_bad_lines=False,sep='\t')

In [4]:
movie_info.head()

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
0,1,"This gritty, fast-paced, and innovative police...",R,Action and Adventure|Classics|Drama,William Friedkin,Ernest Tidyman,"Oct 9, 1971","Sep 25, 2001",NaN,NaN,104 minutes,NaN
1,3,"New York City, not-too-distant-future: Eric Pa...",R,Drama|Science Fiction and Fantasy,David Cronenberg,David Cronenberg|Don DeLillo,"Aug 17, 2012","Jan 1, 2013",$,"600,000",108 minutes,Entertainment One
2,5,Illeana Douglas delivers a superb performance ...,R,Drama|Musical and Performing Arts,Allison Anders,Allison Anders,"Sep 13, 1996","Apr 18, 2000",NaN,NaN,116 minutes,NaN
3,6,Michael Douglas runs afoul of a treacherous su...,R,Drama|Mystery and Suspense,Barry Levinson,Paul Attanasio|Michael Crichton,"Dec 9, 1994","Aug 27, 1997",NaN,NaN,128 minutes,NaN
4,7,NaN,NR,Drama|Romance,Rodney Bennett,Giles Cooper,NaN,NaN,NaN,NaN,200 minutes,NaN

In [5]:
# Getting first 500 movies 
first_500 = []
for i in movie_info.genre[:500].dropna():
    first_500.append(i)
len(first_500)

496

The movies form the data frame have been selected and put into genres groups for the first 500 movies

In [6]:
# putting movies into groups
grouped_500 = []
for i in first_500:
    grouped_500.append(i.split('|',1)[0])
grouped_500=collections.Counter(grouped_500)
grouped_500

Counter({'Action and Adventure': 117,
         'Drama': 103,
         'Comedy': 115,
         'Documentary': 11,
         'Classics': 53,
         'Art House and International': 55,
         'Musical and Performing Arts': 3,
         'Horror': 23,
         'Mystery and Suspense': 7,
         'Animation': 6,
         'Special Interest': 2,
         'Kids and Family': 1})

# Blueprint: Profit Percentage Based on Cost

The amount of movies in the genre groups are all uneven, the goal through out the project is to make sure they all have the same amount of movies that are being analyzed to give it a fair comparison which will be done later on in the project.

The next step is to choose a genre to select and start analyzing. For this section Comedy is being analyzed.

This is the blueprint for creating the first visualization Profit Percentage by cost, bokeh will be used to create these graphs.
Blueprint:
 1. Create a new dataframe for the graph, the dataframe columns will consist of these key infomation of the moives in the Comedy Genre;
    - The Names 
    - Product Budget 
    - System Ratings 
    - Ratings 
    - Domestic Gross 
    - World Wide Gross
    - Profit
    - No. of Tickets
    - Product Budget in integers
    - Profit in integers
    - Total Gross in integers
    - Domestic total in integers
 
 
 2. Install bokeh and create the componets needed for the format of the code script for the graph.There will be five graphs and in each graph are key information of the movies based on the same system rating which are R, PG-13, PG, G and NR. These are the key componets needed in each graph based on the same system rating;
    - X-axis Range
    - Y-axis Range
    - Name
    - Profit in integers
    - System Rating
    - Percentage Profit by Cost
    - Cost


3. The graphs has to have visual componets that convey the information smoothly and also differentiate from one another due to that fact that they are all in groups, these are the formats to help do so; 
    - Color
    - Tooltips (make the graph interactive)
    - Type and shape of pionts in the graph

Below is the code script used to create a new dataframe needed for the graphs

In [7]:
# Getting the names of the first 200 movies in the Comedy genre
movie_buddget = pd.read_csv('tn.movie_budgets.csv.gz')
name_movies = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co': # 'Ac' is the first two words for Comedy
        name_movies.append(movie_buddget.movie[x])
len(name_movies)

115

In [8]:
# Getting product budget of the first 200 movies in Comedy genre
product_budget = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co':product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

115

In [9]:
# Getting ratings of the first 200 movies in Comedy genre
ratings = pd.read_csv('imdb.title.ratings.csv.gz')
rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co': rating.append(ratings.averagerating[x])
len(rating)

115

In [10]:
# Getting system ratings of the first 200 movies in Comedy genre
system_rating = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co': system_rating.append(movie_info.rating[x])
len(system_rating)

115

In [11]:
# Getting domestic gross of the first 200 movies in Comedy genre
domestic_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co': domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

115

In [12]:
# Getting worldwide gross of the first 200 movies in Comedy genre
worldwide_gross = []
for x,y in enumerate(first_500):
    if y[0:2]=='Co': worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

115

The amount of movies per system rating all have to be the same. The code bellow caluclates how much movies are currently in each system rating.

In [13]:
# putting system ratings into groups
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating
# need all groups to be even, all groups need 42 records

Counter({'PG-13': 16, 'R': 45, 'NR': 31, 'PG': 21, 'G': 2})

'R' has the highest count of movies, based on the previous genere analysis all system rating will have to have 42 movies.

Due to the fact that the amount of movies per system rating is not tha same, the following codes caluclate how much is needed for each misiing amount in each group and also getting the indexes of what is needed.

In [14]:
# making sure all system_rating have the same amout of records
# getting the index of  system PG-13: need 26
index_PG13 = movie_info[movie_info['rating']=='PG-13'].index
index_PG13[100:150]

Int64Index([ 732,  736,  757,  764,  769,  775,  777,  781,  787,  791,  802,
             804,  806,  832,  835,  838,  844,  845,  877,  879,  883,  884,
             889,  893,  905,  907,  926,  929,  933,  944,  948,  956,  961,
             964,  965,  966,  972,  974,  985,  988,  998, 1004, 1008, 1013,
            1016, 1020, 1025, 1030, 1033, 1036],
           dtype='int64')

Based on the indexed that are found, the code below double checks to make sure each index fits all the critra  needed to fit.

In [15]:
# using data frame to see ifno
movie_info.iloc[[732,  736,  757,  764,  769,  775,  777,  781,  787,  791,  802,
             804,  806,  832,  835,  838,  844,  845,  877,  879,  883,  884,
             889,  893,  905,  907,  926,  929,  933,  944,  948,  956,  961,
             964,  965,  966,  972,  974,  985,  988,  998, 1004, 1008, 1013,
            1016, 1020, 1025, 1030, 1033, 1036]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
732,940,A woman is forced to prove her own sanity to s...,PG-13,Action and Adventure|Drama|Mystery and Suspense,Robert Schwentke,NaN,"Sep 23, 2005","Jan 24, 2006",$,"89,602,378",98 minutes,Touchstone Pictures
736,946,Tom is a twentysomething loser with no life. M...,PG-13,Comedy,Matt Reeves|Natt Reeves,Matt Reeves|Jason Katims,"May 3, 1996","Apr 3, 2001",NaN,NaN,97 minutes,NaN
757,975,"On her deathbed, a mother makes her son promis...",PG-13,Comedy|Romance,Andrew Bergman,Andrew Bergman,"Aug 28, 1992","May 15, 2001",NaN,NaN,95 minutes,NaN
764,984,A teenager and his kid brother spar with their...,PG-13,Drama|Mystery and Suspense,Michael Apted,Ron Koslow,"Jun 1, 1984","Jul 31, 2012",NaN,NaN,103 minutes,NaN
769,994,"Fresh Horses features Molly Ringwald as Jewel,...",PG-13,Drama|Romance,David Anspaugh,Larry Ketron,"Nov 18, 1988","Mar 23, 2004",NaN,NaN,102 minutes,NaN
775,1001,Based on the 2009 investigative book by BBC co...,PG-13,Drama,Stephen Frears,Jeff Pope|Steve Coogan,"Nov 22, 2013","Apr 15, 2014",NaN,NaN,98 minutes,The Weinstein Company
777,1004,Based on the Pulitzer Prize-winning novel by A...,PG-13,Drama,Steven Spielberg,Menno Meyjes,"Dec 16, 1985","Feb 18, 2003",NaN,NaN,154 minutes,NaN
781,1009,Director James L. Brooks returns to the helm f...,PG-13,Comedy|Drama|Romance,NaN,NaN,"Dec 17, 2010","Mar 22, 2011",$,"30,212,620",121 minutes,Columbia Pictures
787,1017,David Fincher's The Curious Case of Benjamin B...,PG-13,Drama|Science Fiction and Fantasy|Romance,David Fincher,Eric Roth|Robin Swicord,"Dec 25, 2008","May 5, 2009",$,"127,490,802",166 minutes,Paramount
791,1023,"Lorraine Gary stars as Ellen Brody, the widow ...",PG-13,Action and Adventure|Horror|Mystery and Suspense,Joseph Sargent,Michael De Guzman,"Jan 1, 1987","Jan 15, 1999",NaN,NaN,89 minutes,NaN
802,1036,"With THE FITZGERALD FAMILY CHRISTMAS, Burns re...",PG-13,Drama,Edward Burns,Edward Burns,"Dec 7, 2012","Nov 5, 2013",NaN,NaN,99 minutes,Tribeca Film
804,1038,Two New Yorkers fight the battle of the sexes ...,PG-13,Comedy|Drama|Romance,Donald Petrie,Burr Steers|Brian Regan|Kristen Buckley,"Feb 7, 2003","Jul 1, 2003",$,"105,765,605",115 minutes,Paramount Pictures
806,1043,"In the Holy Bible, the Book of Revelations spe...",PG-13,Action and Adventure|Drama|Mystery and Suspens...,Vic Sarin|Victor Sarin,NaN,"Jan 26, 2001","Oct 31, 2000",NaN,NaN,100 minutes,Cloud Ten Pictures
832,1077,Steven Spielberg's phenomenally successful sci...,PG-13,Action and Adventure|Mystery and Suspense|Scie...,Steven Spielberg,Michael Crichton|David Koepp|Malia Scotch Marmo,"Jun 11, 1993","Oct 10, 2000",$,"45,299,680",126 minutes,NaN
835,1080,After being denied a promotion at the universi...,PG-13,Drama|Musical and Performing Arts|Romance,Maggie Greenwald,Maggie Greenwald,"Jun 29, 2001","Oct 23, 2001",$,"1,634,064",112 minutes,Lions Gate
838,1083,Hollywood 1927. George Valentin (Jean Dujardin...,PG-13,Comedy|Drama|Romance,Michel Hazanavicius,Michel Hazanavicius,"Nov 25, 2011","Jun 26, 2012",$,"44,667,095",100 minutes,The Weinstein Company
844,1091,For thirteen extraordinary days in October of ...,PG-13,Drama,Roger Donaldson,David Self,"Dec 25, 2000","Jul 10, 2001",NaN,NaN,145 minutes,New Line Cinema
845,1092,"A proud military man, Colonel Claus von Stauff...",PG-13,Drama|Mystery and Suspense,Bryan Singer,Christopher McQuarrie|Nathan Alexander,"Dec 25, 2008","May 19, 2009",$,"82,989,109",120 minutes,MGM
877,1136,The Hobbit: An Unexpected Journey follows titl...,PG-13,Action and Adventure|Science Fiction and Fantasy,Peter Jackson,Peter Jackson|Philippa Boyens|Guillermo del To...,"Dec 14, 2012","Mar 19, 2013",$,"303,001,229",170 minutes,Warner Bros.
879,1138,When once-up-and-coming indie film starlet Hal...,PG-13,Comedy,Michael Urie,Halley Feiffer|Ryan Spahn,"May 10, 2013","Sep 23, 2013",NaN,NaN,96 minutes,Gravitas Ventures
883,1144,"In New York, during the height of World War II...",PG-13,Drama,Neal Slavin,Kendrew Lascelles,"Oct 19, 2001","Mar 19, 2002",NaN,NaN,106 minutes,Paramount Classics
884,1145,"In this Mel Brooks comedy, the writer-director...",PG-13,Comedy,Mel Brooks,Mel Brooks|Steve Haberman|Rudy De Luca|Ron Clark,"Jul 26, 1991","Feb 18, 2003",NaN,NaN,93 minutes,NaN
889,1150,A laid-back health inspector's comfortable rou...,PG-13,Comedy,Trent Cooper,Jonathan Bernstein|James Greer,"Mar 24, 2006","Aug 8, 2006",$,"15,655,665",89 minutes,Lions Gate Films
893,1155,"""Valentino: The Last Emperor"" provides a first...",PG-13,Documentary|Special Interest,Matt Tynauer|Matt Tyrnauer,NaN,"Mar 18, 2009","Sep 8, 2009",$,"1,569,618",96 minutes,Truly Indie
905,1169,From masters of horror Blumhouse Productions- ...,PG-13,Horror,David Gelb,Luke Dawson|Jeremy Slater,"Feb 27, 2015","Jun 16, 2015",$,"20,467,547",83 minutes,Relativity Media
907,1171,Academy Award-nominated writer/director J.C. C...,PG-13,Action and Adventure|Mystery and Suspense,NaN,NaN,"Oct 18, 2013","Feb 11, 2014",$,"4,300,353",105 minutes,Lionsgate/Roadside Attractions
926,1199,"In this John Hughes film, spoiled, self-center...",PG-13,Comedy,Peter Faiman,John Hughes,"Jul 19, 1991","Mar 22, 2005",NaN,NaN,107 minutes,NaN
929,1206,An effort to circumvent global catastrophe bec...,PG-13,Mystery and Suspense|Science Fiction and Fantasy,Antony Hoffman|Anthony Hoffman,Chuck Pfarrer|Jonathan Lemkin|Channing Gibson,"Nov 10, 2000","Mar 27, 2001",NaN,NaN,108 minutes,Warner Bros.
933,1210,A woman finds herself drafted into the battle ...,PG-13,Comedy|Drama|Romance,Gary David Goldberg,Gary David Goldberg,"Jul 29, 2005","Dec 20, 2005",$,"43,800,000",98 minutes,Warner Bros. Pictures
944,1223,A once-loving Chicago couple whose happily-eve...,PG-13,Comedy|Drama|Romance,Peyton Reed,Vince Vaughn|Jeremy Garelick|Jay Lavender,"Jun 1, 2006","Oct 17, 2006",$,"118,683,135",107 minutes,Universal Pictures
948,1227,"In 1854 Utah, 13-year old Nick Wilson (Blake H...",PG-13,Action and Adventure|Drama|Western,Tom Shell,Eliizabeth Hansen,"Nov 27, 2001","Nov 27, 2001",NaN,NaN,97 minutes,NaN
956,1237,"Sarah Jessica Parker, Greg Kinnear, Pierce Bro...",PG-13,Comedy,Douglas McGrath,Aline Brosh McKenna,"Sep 16, 2011","Jan 3, 2012",$,"9,500,000",89 minutes,The Weinstein Co.
961,1243,The true-life story of a coach who tries to te...,PG-13,Drama,Thomas Carter,Mark Schwahn|John Gatins,"Jan 14, 2005","Jun 21, 2005",$,"67,169,549",136 minutes,Paramount Pictures
964,1252,The Wild West meets the Far East in a battle f...,PG-13,Action and Adventure|Comedy|Western,Tom Dey,Miles Millar|Alfred Gough,"May 26, 2000","Oct 10, 2000",NaN,NaN,110 minutes,Buena Vista Internationa
965,1253,"Set in Norway during the 1950s, this dark come...",PG-13,Art House and International|Comedy|Drama,Berit Nesheim,Berit Nesheim|Lasse Glomm,"Oct 1, 1997","Jul 4, 2000",NaN,NaN,100 minutes,NaN
966,1255,Mission: Impossible III director and Alias cre...,PG-13,Action and Adventure|Drama|Science Fiction and...,NaN,Gene Roddenberry|Alex Kurtzman|Roberto Orci,"May 7, 2009","Nov 17, 2009",$,"257,704,099",127 minutes,IMAX
972,1263,A man who writes the book on ending a romance ...,PG-13,Comedy|Romance,Daniel Taplitz,Daniel Taplitz,"May 14, 2004","Oct 12, 2004",$,"11,827,301",86 minutes,Screen Gems
974,1265,Beth (Diane Keaton) saves a bedraggled lost do...,PG-13,Comedy|Drama,Lawrence Kasdan,Lawrence Kasdan|Meg Kasdan,"Apr 20, 2012","Aug 28, 2012",$,"793,352",103 minutes,Sony Pictures Classics
985,1277,Love means never having to say that you're ugl...,PG-13,Action and Adventure|Drama|Horror|Science Fict...,Wolfgang Petersen,Edward Khmara,"Dec 20, 1985","Mar 27, 2001",NaN,NaN,109 minutes,NaN
988,1281,Judy Davis stars as French novelist George San...,PG-13,Comedy|Romance,James Lapine,Sarah Kernochan,"Apr 12, 1991","Mar 19, 2002",NaN,NaN,108 minutes,NaN
998,1291,"St Trinian's, the infamous school for ""young l...",PG-13,Comedy,Barnaby Thompson|Oliver Parker,Nick Moorcroft|Piers Ashworth|Barnaby Thompson...,"Dec 10, 2007","Apr 14, 2008",NaN,NaN,101 minutes,NeoClassics Films
1004,1298,"Jessica Spencer, a somewhat mean-spirited teen...",PG-13,Comedy|Science Fiction and Fantasy,Tom Brady,Rob Schneider|Tom Brady,"Dec 13, 2002","Jan 25, 2005",NaN,NaN,101 minutes,NaN
1008,1307,HITCHCOCK is a love story about one of the mos...,PG-13,Drama,Sacha Gervasi,NaN,"Nov 23, 2012","Mar 12, 2013",$,"6,002,708",98 minutes,Fox Searchlight Pictures
1013,1313,Despite the many adventures they suffered in N...,PG-13,Comedy,Amy Heckerling,John Hughes|Robert Klane,"Jul 26, 1985","Apr 2, 2002",NaN,NaN,95 minutes,NaN
1016,1317,"For an awkward, self-conscious girl like Kiki,...",PG-13,Comedy|Drama|Romance,Joe Roth,Donna Roth|Billy Crystal|Peter Tolan,"Jul 20, 2001","Nov 13, 2001",$,"93,008,426",103 minutes,Columbia Pictures
1020,1321,In his follow-up to the four-time Academy Awar...,PG-13,Drama,Tate Taylor,Tate Taylor|Jez Butterworth|John-Henry Butterw...,"Aug 1, 2014","Jan 6, 2015",$,"22,838,662",138 minutes,Universal Pictures
1025,1327,Charles S. Dutton's feature-length directorial...,PG-13,Drama,NaN,Cheryl Edwards,"Feb 20, 2004","Jul 13, 2004",$,"5,696,752",110 minutes,Paramount Pictures
1030,1334,Dating guru Matthew Taylor (Shemar Moore) fall...,PG-13,Comedy|Romance,Youssef Delara,Victor Teran|Youssef Delara|Staci Robinson,"Dec 9, 2016","Apr 4, 2017",$,"320,676",104 minutes,NaN
1033,1337,"On the morning of his re-election, the Preside...",PG-13,Comedy|Drama,Paul Weitz,Paul Weitz,"Apr 21, 2006","Oct 3, 2006",$,"7,156,725",108 minutes,Universal Pictures
1036,1340,"Produced by MTV Films, The Perfect Score is a ...",PG-13,Comedy|Drama|Mystery and Suspense,Brian Robbins,Mark Schwahn|Marc Hyman|Jon Zack,"Jan 30, 2004","Jun 29, 2004",$,"10,279,192",92 minutes,Paramount Pictures

In [16]:
#checking if the names are already used
for i in name_movies:
    if i == 'Thor:Ragnarok':
        print('yes!')
else:print('no')

no

In [17]:
#checking info in the dataframe
movie_buddget.iloc[[358,384,424,430,434,437,442,462,492,495,499,574,597,631,674,690,736,757,781,804,838,879,
                   884,889,926,953]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
358,59,"Jul 1, 2009",Public Enemies,"$102,500,000","$97,104,620","$212,282,709"
384,85,"Dec 10, 2010",The Tourist,"$100,000,000","$67,631,157","$278,731,369"
424,25,"May 30, 2003",Finding Nemo,"$94,000,000","$380,529,370","$936,429,370"
430,31,"Aug 5, 2011",Rise of the Planet of the Apes,"$93,000,000","$176,760,185","$470,986,200"
434,35,"Apr 9, 2004",The Alamo,"$92,000,000","$22,406,362","$23,911,362"
437,38,"Dec 20, 2017",Jumanji: Welcome to the Jungle,"$90,000,000","$404,508,916","$964,496,193"
442,43,"Jul 1, 2009",Ice Age: Dawn of the Dinosaurs,"$90,000,000","$196,573,705","$859,701,857"
462,63,"Apr 22, 2005",The Interpreter,"$90,000,000","$72,708,161","$162,753,837"
492,93,"Apr 3, 2009",Fast & Furious,"$85,000,000","$155,064,265","$363,064,265"
495,96,"Sep 28, 2012",Hotel Transylvania,"$85,000,000","$148,313,048","$378,505,812"
499,100,"Jul 20, 2007",I Now Pronounce You Chuck and Larry,"$85,000,000","$119,725,280","$185,708,462"
574,75,"May 24, 2002",Spirit: Stallion of the Cimarron,"$80,000,000","$73,215,310","$106,515,310"
597,98,"May 12, 2000",Battlefield Earth: A Saga of the Year 3000,"$80,000,000","$21,471,685","$29,725,663"
631,32,"Mar 31, 2006",Ice Age: The Meltdown,"$75,000,000","$195,330,621","$651,899,282"
674,75,"Nov 22, 2000",Unbreakable,"$73,243,106","$94,999,143","$248,099,143"
690,91,"Jun 26, 1998",Doctor Dolittle,"$71,500,000","$144,156,605","$294,156,605"
736,37,"Oct 18, 2013",Escape Plan,"$70,000,000","$25,135,965","$103,735,965"
757,58,"Nov 22, 1995",Money Train,"$68,000,000","$35,324,232","$77,224,232"
781,82,"Dec 25, 2014",Unbroken,"$65,000,000","$115,637,895","$163,527,824"
804,5,"Mar 20, 1998",Primary Colors,"$65,000,000","$39,017,984","$39,017,984"
838,39,"Aug 2, 2013",2 Guns,"$61,000,000","$75,612,460","$132,493,015"
879,80,"Mar 4, 2016",London Has Fallen,"$60,000,000","$62,524,260","$195,194,085"
884,85,"Oct 21, 2016",Jack Reacher: Never Go Back,"$60,000,000","$58,697,076","$159,946,489"
889,90,"Nov 14, 1997",The Jackal,"$60,000,000","$54,956,941","$159,356,941"
926,27,"Nov 3, 2000",The Legend of Bagger Vance,"$60,000,000","$30,695,227","$39,235,486"
953,54,"Mar 23, 2018",Sherlock Gnomes,"$59,000,000","$43,242,871","$87,527,651"

In [18]:
# checking if the nmaes are already used
for i,x in enumerate(system_rating):
    if x == 'PG-13':
        print(name_movies[i])

Avengers: Infinity War
John Carter
Alice in Wonderland
Blade Runner 2049
Guardians of the Galaxy
Alita: Battle Angel
The Matrix Reloaded
Teenage Mutant Ninja Turtles: Out of the Shadows
Ant-Man and the Wasp
After Earth
Total Recall
The 13th Warrior
San Andreas
The Campaign
Rise of the Planet of the Apes
Hotel Transylvania

After making sure the index fits properly, it is stored in a avairable used later on to add it back to the dataframe. This is being repeted through out the next few coding script.

In [19]:
# new names index for pg-13
no2 = [358,384,424,430,434,437,442,462,492,495,499,574,597,631,674,690,736,757,781,804,838,879,
                   884,889,926,953]

In [20]:
# making sure all system_rating have the same amout of records
# getting system PG: need 21
index_PG = movie_info[movie_info['rating']=='PG'].index
index_PG[150:200]

Int64Index([ 986,  995, 1001, 1007, 1012, 1015, 1018, 1028, 1035, 1037, 1038,
            1048, 1050, 1053, 1056, 1065, 1068, 1069, 1073, 1087, 1090, 1092,
            1117, 1135, 1145, 1152, 1157, 1164, 1173, 1180, 1182, 1200, 1201,
            1204, 1217, 1218, 1223, 1238, 1239, 1252, 1253, 1256, 1258, 1267,
            1271, 1277, 1281, 1297, 1298, 1303],
           dtype='int64')

In [21]:
movie_info.iloc[[505,511,531,575,601,640,671,682,694,695,779,784,813,818,847,869,887,957,962,986,995,1001, 1007, 1012, 1015, 1018, 1028, 1035, 1037, 1038,
            1048, 1050, 1053, 1056, 1065,]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
505,663,A pair of high-school dweebs get a chance to b...,PG,Comedy|Science Fiction and Fantasy,Les Mayfield,Shawn Schepps|Dana Olsen|George Zaloom,"May 22, 1992","May 15, 2001",NaN,NaN,88 minutes,NaN
511,671,Everybody's favorite underdog youth hockey tea...,PG,Comedy|Kids and Family,NaN,Steven Brill|Jim Burnstein,"Oct 4, 1996","Sep 3, 2002",NaN,NaN,104 minutes,NaN
531,693,Three Men and a Baby is an Americanized remake...,PG,Comedy,Leonard Nimoy,James Orr|Jim Cruickshank|Coline Serreau,"Nov 25, 1987","Apr 2, 2002",NaN,NaN,102 minutes,NaN
575,745,"In this subtly humorous, alien-invasion film b...",PG,Comedy|Cult Movies|Mystery and Suspense|Scienc...,Michael Laughlin,Michael Laughlin|Bill Condon|Walter Halsey Davis,"Sep 16, 1983","Nov 20, 2001",NaN,NaN,94 minutes,NaN
601,776,"Loosely based on Fellini's 8 1/2, this Woody A...",PG,Comedy|Drama,Woody Allen,Woody Allen,"Sep 26, 1980","Jul 5, 2000",NaN,NaN,88 minutes,NaN
640,824,"Making great fun of the '70s, this lively sci-...",PG,Comedy|Musical and Performing Arts|Science Fic...,Lucas Reiner,Lucas Reiner|Roman Coppola,"Jan 1, 1990","Jun 3, 2003",NaN,NaN,82 minutes,NaN
671,859,"Slow-witted and annoying as all get out, comme...",PG,Comedy|Kids and Family,NaN,Ben Kline|Eric Luke|Thom Eberhardt,"Nov 11, 1988","Sep 3, 2002",NaN,NaN,91 minutes,NaN
682,872,Versatile Canadian comedian Martin Short plays...,PG,Comedy|Kids and Family,Paul Flaherty,Will Aldis|Jay Dee Rock|Steven Kampmann|Bobby ...,"Apr 1, 1994","Mar 2, 2004",NaN,NaN,89 minutes,NaN
694,889,"As the result of a poorly considered wish, a s...",PG,Comedy,Amy Holden Jones,Perry Howze|Randy Howze,"Jan 1, 1987","Jun 18, 2002",NaN,NaN,100 minutes,NaN
695,891,This is a baseball comedy with a twist. This t...,PG,Comedy|Drama,Richard Michaels|Michael Daves,Kevin Sellers|Arlene Sellers,"Jun 1, 1983","Apr 29, 1992",NaN,NaN,96 minutes,NaN
779,1007,Ernest (Jim Varney) gets a job as a fix-it man...,PG,Comedy|Kids and Family,NaN,Coke Sams|John Cherry,"May 22, 1987","Sep 3, 2002",NaN,NaN,92 minutes,NaN
784,1014,When a young American travels to the city of V...,PG,Comedy|Drama|Romance,Gary Winick,Jose Rivera|Tim Sullivan,"May 14, 2010","Sep 14, 2010",$,"53,021,560",105 minutes,Summit Entertainment
813,1050,In the tradition of Amblin classics where fant...,PG,Comedy|Kids and Family|Science Fiction and Fan...,Eli Roth,Eric Kripke,"Sep 21, 2018","Nov 27, 2018",NaN,NaN,104 minutes,Universal Pictures
818,1060,A conniving nephew (Anthony Geary) wishes to g...,PG,Comedy,Michael Schultz,Mitchell Klebanoff|Mark Feldberg,"Aug 14, 1987","Feb 15, 2005",NaN,NaN,86 minutes,NaN
847,1094,When a soap-opera scriptwriter (John Candy) is...,PG,Comedy|Science Fiction and Fantasy,Tom Mankiewicz,NaN,"Aug 9, 1991","Apr 16, 2002",NaN,NaN,96 minutes,NaN
869,1123,The sequel to the cult classic The Rocky Horro...,PG,Comedy|Musical and Performing Arts|Television,Jim Sharman,NaN,"Oct 13, 1981","Sep 5, 2006",NaN,NaN,94 minutes,20th Century Fox
887,1148,Bill Forsyth displays some of the fey quirkine...,PG,Comedy|Drama,Bill Forsyth,NaN,NaN,NaN,NaN,NaN,82 minutes,NaN
957,1238,An air-traffic controller (Chevy Chase) is hav...,PG,Comedy,Ken Shapiro,Ken Shapiro,"Dec 25, 1981","Feb 22, 2005",NaN,NaN,91 minutes,NaN
962,1244,"In this romantic comedy fantasy, an angel (Emm...",PG,Comedy|Romance,Tom McLoughlin,Tom McLoughlin,"Jan 1, 1987","May 21, 2002",NaN,NaN,114 minutes,NaN
986,1279,A handful of kids stranded without their paren...,PG,Comedy|Kids and Family,Paul Feig,Mya Stark|Jacob Meszaros,"Dec 8, 2006","Aug 7, 2007",$,"16,614,132",89 minutes,Warner Bros.
995,1288,A New Jersey rent-a-cop gets his moment to shi...,PG,Comedy,Steve Carr,Kevin James|Nick Bakay,"Jan 16, 2009","May 19, 2009",$,"146,336,178",91 minutes,Sony Pictures/Columbia Pictures
1001,1295,"""Maleficent"" explores the untold story of Disn...",PG,Science Fiction and Fantasy,Robert Stromberg,Linda Woolverton,"May 30, 2014","Nov 4, 2014",$,"190,871,149",97 minutes,Walt Disney Pictures
1007,1305,"A cow learns to walk like a man, both literall...",PG,Animation|Comedy|Kids and Family,Steve Oedekerk,Steve Oedekerk,"Aug 4, 2006","Dec 12, 2006",$,"72,601,713",90 minutes,Paramount Pictures
1012,1311,Director Richard Lester proves to be as skillf...,PG,Action and Adventure|Art House and Internation...,Richard Lester,NaN,"Sep 25, 1974","Jul 15, 2003",NaN,NaN,126 minutes,NaN
1015,1315,Gregorio and Ingrid are the two greatest secre...,PG,Action and Adventure|Comedy|Kids and Family|My...,Robert Rodriguez,Robert Rodriguez,"Mar 30, 2001","Sep 18, 2001",NaN,NaN,88 minutes,Dimension Films
1018,1319,"H.B. Halicki, who wrote and directed the car c...",PG,Action and Adventure|Comedy,NaN,NaN,"Jan 28, 1983","Feb 19, 2002",NaN,NaN,96 minutes,NaN
1028,1331,"In this Canadian film, Nick Mancusco plays an ...",PG,Art House and International|Drama,NaN,Anne Cameron,NaN,NaN,NaN,NaN,109 minutes,NaN
1035,1339,When her director husband is occupied with wor...,PG,Comedy|Romance,Eleanor Coppola,Eleanor Coppola,"May 12, 2017","Sep 5, 2017",$,"5,617,321",92 minutes,Sony Pictures Classics
1037,1341,Two Oscar-winning actors add a family-oriented...,PG,Action and Adventure|Comedy|Kids and Family,Brian Levant,NaN,"Jan 18, 2002","May 14, 2002",$,"81,110,575",99 minutes,Buena Vista Distribution Compa
1038,1342,It is not easy being a 9 year old in a new cou...,PG,Action and Adventure|Comedy|Kids and Family,Uli Edel|Ulrich Edel,Karey Kirkpatrick|Larry Wilson|Nicholas Waller,"Oct 27, 2000","Mar 6, 2001",$,"13,432,508",105 minutes,New Line Cinema
1048,1354,Two rival gangs of children battle out their d...,PG,Action and Adventure|Comedy|Drama|Kids and Family,John Roberts,Colin Welland,"Jun 1, 1995","Sep 10, 1996",NaN,NaN,94 minutes,NaN
1050,1357,After years of wooing director John Huston via...,PG,Action and Adventure|Classics|Drama|Romance,John Huston,John Huston|James Agee|Peter Viertel,"Dec 23, 1951","Jul 9, 2004",NaN,NaN,105 minutes,NaN
1053,1361,Fu Manchu (Christopher Lee) plots to destroy t...,PG,Action and Adventure|Classics|Drama|Horror|Mys...,NaN,NaN,"Sep 24, 1968","Jan 13, 2004",NaN,NaN,91 minutes,Blue Underground
1056,1364,This junior-level Ground Hog Day stars Erik Vo...,PG,Comedy,Larry Peerce,Stephen Alix|Nancey Silvers,NaN,NaN,NaN,NaN,92 minutes,NaN
1065,1375,"Joseph P. ""Kotch"" Kotcher is an irksome 72-yea...",PG,Classics|Comedy|Drama,Jack Lemmon,John Paxton,"Sep 17, 1971","Jul 6, 2004",NaN,NaN,113 minutes,NaN

In [22]:
#checking if the names are already used
for i in name_movies:
    if i == 'Car 2':
        print('yes!')
else:print('no')

no

In [23]:
movie_buddget.iloc[[505,511,531,575,601,640,671,682,694,695,779,784,813,818,847,869,887,957,962,986,995]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
505,6,"Nov 22, 2000",102 Dalmatians,"$85,000,000","$66,941,559","$66,941,559"
511,12,"Jun 18, 1993",Last Action Hero,"$85,000,000","$50,016,394","$137,298,489"
531,32,"Jul 11, 2008",Hellboy II: The Golden Army,"$82,500,000","$75,986,503","$160,388,063"
575,76,"Jun 8, 2001",Swordfish,"$80,000,000","$69,772,969","$147,080,413"
601,2,"Apr 22, 2010",Oceans,"$80,000,000","$19,422,319","$86,787,530"
640,41,"May 31, 2013",Now You See Me,"$75,000,000","$117,723,989","$342,769,200"
671,72,"Dec 31, 2019",355,"$75,000,000",$0,$0
682,83,"Sep 28, 2007",The Kingdom,"$72,500,000","$47,467,250","$86,509,602"
694,95,"Dec 23, 2009",Alvin and the Chipmunks: The Squeakquel,"$70,000,000","$219,614,612","$443,483,213"
695,96,"Jun 22, 1988",Who Framed Roger Rabbit?,"$70,000,000","$154,112,492","$351,500,000"
779,80,"Jun 1, 1990",Total Recall,"$65,000,000","$119,394,839","$261,400,000"
784,85,"Jul 25, 2008",Step Brothers,"$65,000,000","$100,468,793","$128,468,793"
813,14,"Jan 24, 2014","I, Frankenstein","$65,000,000","$19,075,290","$74,575,290"
818,19,"Sep 23, 2005",Oliver Twist,"$65,000,000","$2,070,920","$26,670,920"
847,48,"Dec 10, 1999",The Green Mile,"$60,000,000","$136,801,374","$290,701,374"
869,70,"Dec 22, 2000",The Family Man,"$60,000,000","$75,764,085","$124,715,863"
887,88,"Dec 25, 2015",Joy,"$60,000,000","$56,451,232","$101,134,059"
957,58,"Oct 16, 2015",Goosebumps,"$58,000,000","$80,069,458","$158,905,324"
962,63,"Jun 7, 2013",The Internship,"$58,000,000","$44,672,764","$93,672,764"
986,87,"Dec 15, 2006",The Pursuit of Happyness,"$55,000,000","$162,586,036","$307,311,093"
995,96,"Sep 26, 2014",The Equalizer,"$55,000,000","$101,530,738","$192,903,624"

In [24]:
# checking if the nmaes are already used
for i,x in enumerate(system_rating):
    if x == 'PG':
        print(name_movies[i])

Jurassic World
The Golden Compass
Cars 2
The Great Gatsby
Edge of Tomorrow
Waterworld
Van Helsing
The Curious Case of Benjamin Button
Home
Clash of the Titans
Oblivion
Speed Racer
Knight and Day
The Huntsman: Winterâs War
I, Robot
Gone in 60 Seconds
Lemony Snicket's A Series of Unfortunate Events
The Hunchback of Notre Dame
The Lord of the Rings: The Two Towers
Pixels
Bicentennial Man

In [25]:
#new name index for pg
no1=[505,511,531,575,601,640,671,682,694,695,779,784,813,818,847,869,887,957,962,986,995,1035]

In [26]:
# making sure all system_rating have the same amout of records
# getting system NR: need 11
index_PG = movie_info[movie_info['rating']=='NR'].index
index_PG[400:450]

Int64Index([1207, 1210, 1211, 1214, 1219, 1221, 1225, 1228, 1232, 1236, 1244,
            1246, 1250, 1251, 1259, 1262, 1263, 1264, 1266, 1269, 1272, 1278,
            1280, 1282, 1284, 1285, 1286, 1287, 1288, 1291, 1293, 1294, 1296,
            1299, 1301, 1306, 1315, 1320, 1324, 1326, 1327, 1332, 1334, 1339,
            1340, 1341, 1342, 1344, 1345, 1352],
           dtype='int64')

In [27]:
movie_info.iloc[[1207, 1210, 1211, 1214, 1219, 1221, 1225, 1228, 1232, 1236, 1244,
            1246, 1250, 1251, 1259, 1262, 1263, 1264, 1266, 1269, 1272, 1278,
            1280, 1282, 1284, 1285, 1286, 1287, 1288, 1291, 1293, 1294, 1296,
            1299, 1301, 1306, 1315, 1320, 1324, 1326, 1327, 1332, 1334, 1339,
            1340, 1341, 1342, 1344, 1345, 1352]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1207,1553,Captain Virat Bakshi (Akshay Kumar) is a soldi...,NR,Action and Adventure|Drama|Mystery and Suspens...,NaN,NaN,NaN,NaN,$,"707,672",161 minutes,Reliance Entertainment
1210,1557,"L'Homme Que J'Aime (The Man I Love), a Gallic ...",NR,Art House and International|Drama,NaN,NaN,"Apr 27, 2001","Nov 11, 2003",NaN,NaN,87 minutes,NaN
1211,1560,It is 1944 and World War II is reaching its cl...,NR,Comedy|Drama,Oliver Parker,Hamish McColl|Jimmy Perry,NaN,NaN,$,"4,683,159",100 minutes,Universal Pictures International
1214,1565,NaN,NR,Documentary,NaN,NaN,NaN,NaN,NaN,NaN,60 minutes,NaN
1219,1573,Eighty-four-year-old Kung Fu Grandmaster Zhou ...,NR,Documentary,Daston Kalili,Jessica Cauffiel|Daston Kalili,NaN,NaN,NaN,NaN,71 minutes,NaN
1221,1575,The inauguration of a stage line created the e...,NR,Action and Adventure|Western,William Witney|John English,Rex Taylor Smith|Sol Shore|Franklin Adreon|Ron...,NaN,NaN,NaN,NaN,196 minutes,NaN
1225,1581,Three twenty-something addicts fight to retain...,NR,Art House and International|Drama|Horror|Myste...,Carl Bessai,Arne Olsen,NaN,NaN,NaN,NaN,85 minutes,Film Sales Company
1228,1584,Six Vietnam war vets combine to pull off a hei...,NR,Action and Adventure|Drama,Michael Thornhill,NaN,NaN,NaN,NaN,NaN,91 minutes,NaN
1232,1591,A man who acknowledges a side of himself he's ...,NR,Art House and International|Drama|Romance,Haim Tabakman,Merav Doster,"Feb 5, 2010","Nov 16, 2010",$,"463,914",91 minutes,Regent Releasing
1236,1599,Horror legend Lucio Fulci directed this substa...,NR,Art House and International|Horror|Mystery and...,Lucio Fulci,Lucio Fulci,"Jan 1, 1987","Sep 4, 2001",NaN,NaN,85 minutes,NaN
1244,1607,Acclaimed Czech director Jiri Menzel has pulle...,NR,Comedy,NaN,Bohumil Hrabal,NaN,NaN,NaN,NaN,85 minutes,NaN
1246,1609,"In this flawed and overly long film, an aristo...",NR,Art House and International,Peque Gallaga,NaN,NaN,NaN,NaN,NaN,195 minutes,NaN
1250,1613,Farrah Fawcett earned Emmy and Golden Globe no...,NR,Drama|Mystery and Suspense|Television,Robert Greenwald,Rose Leiman Goldemberg,"Oct 8, 1984","Sep 7, 2004",NaN,NaN,95 minutes,NaN
1251,1614,Canadian filmmaker Brent Leung embarks on a gl...,NR,Documentary|Special Interest,Brent Leung,NaN,NaN,NaN,NaN,NaN,89 minutes,Knowledge Matters
1259,1626,This Korean horror movie offers a feminist twi...,NR,Art House and International|Comedy|Horror|Myst...,Cheol-su Park,NaN,"May 3, 1996","Jan 11, 2005",NaN,NaN,99 minutes,NaN
1262,1629,Painter Yeong-soo's mother is in her death bed...,NR,Art House and International|Drama,Hong Sang-soo,Hong Sang-soo,NaN,NaN,NaN,NaN,86 minutes,NaN
1263,1630,The sun drenched beach is the setting for Gidg...,NR,Classics|Comedy|Romance,Paul Wendkos,Gabrielle Upton,"Jan 1, 1959","Aug 3, 2004",NaN,NaN,95 minutes,NaN
1264,1631,Originally issued under the title Appuntamento...,NR,Art House and International|Mystery and Suspense,Antonio Bonifacio,NaN,NaN,NaN,NaN,NaN,88 minutes,NaN
1266,1633,Norbu and Dolma are banished tribal Tibetans w...,NR,Art House and International|Drama,Tian Zhuangzhuang,Rui Zhang,"Jan 1, 1986","Mar 20, 1991",NaN,NaN,88 minutes,NaN
1269,1639,In this darkly erotic drama from cult filmmake...,NR,Art House and International|Drama,Jeanne Labrune,Jeanne Labrune|Richard Debuisne,"Aug 26, 2011","Jan 17, 2012",$,"8,856",95 minutes,First Run Features
1272,1642,"In this frantic service comedy, a group of bor...",NR,Classics|Comedy|Drama,Richard Quine,Arthur Carter|Blake Edwards|Jed Harris,"Aug 17, 1957","Jun 9, 2009",NaN,NaN,105 minutes,NaN
1278,1650,This low-budget film is about a scientist (Ken...,NR,Science Fiction and Fantasy,Terry Marcel,Terry Marcel,NaN,NaN,NaN,NaN,94 minutes,NaN
1280,1653,NaN,NR,Drama,Kira Muratova,Natalya Ryazantseva,NaN,NaN,NaN,NaN,97 minutes,NaN
1282,1655,Vinod Verma is an employee of the Indian Railw...,NR,Action and Adventure|Art House and Internation...,Ravi Chopra,NaN,NaN,NaN,NaN,NaN,142 minutes,NaN
1284,1657,Famed action director Dante Lam returns with t...,NR,Action and Adventure,Dante Lam,Ji Feng,"Feb 23, 2018","Jul 24, 2018",$,"1,526,248",141 minutes,NaN
1285,1659,Zachary Scott made his screen debut in this cl...,NR,Mystery and Suspense,Jean Negulesco,Frank Gruber,NaN,NaN,NaN,NaN,95 minutes,NaN
1286,1660,"At a quaint Scottish inn, several disparate tr...",NR,Science Fiction and Fantasy,David MacDonald,NaN,"Apr 27, 1955","Jan 30, 2001",NaN,NaN,76 minutes,NaN
1287,1661,Daniel Auteuil stars as the infamous Marquis d...,NR,Art House and International|Drama,NaN,Jacques Fieschi|Bernard Minoret,"Nov 17, 2000","Dec 9, 2003",NaN,NaN,97 minutes,NaN
1288,1663,"Welcome to The Beverly Hillbillies, Dutch styl...",NR,Comedy,Dick Maas,Dick Maas,NaN,NaN,NaN,NaN,111 minutes,NaN
1291,1668,A Canadian production shot along the British C...,NR,Comedy|Drama|Musical and Performing Arts,NaN,NaN,NaN,NaN,NaN,NaN,100 minutes,NaN
1293,1671,"For decades, Isaiah Zagar has been one of Phil...",NR,Documentary|Musical and Performing Arts,Jeremiah Zagar,NaN,"Mar 8, 2008","Sep 29, 2009",NaN,NaN,80 minutes,International Film Circuit
1294,1672,"Tom Destry (James Stewart), son of a legendary...",NR,Classics|Comedy|Western,George Marshall,Felix Jackson|Gertrude Purcell|Henry Myers,"Dec 29, 1939","May 6, 2003",NaN,NaN,94 minutes,NaN
1296,1674,"""I don't think most people really understood t...",NR,Documentary|Special Interest,Leslie Cockburn,Leslie Cockburn|Andrew Cockburn,NaN,NaN,NaN,NaN,89 minutes,Argot Pictures
1299,1679,NaN,NR,Horror,NaN,NaN,NaN,NaN,NaN,NaN,97 minutes,NaN
1301,1681,Hanna is an unhappy adolescent in 1960s Quebec...,NR,Art House and International|Drama,NaN,NaN,"Jan 1, 1999","Oct 24, 2000",NaN,NaN,94 minutes,NaN
1306,1689,Adapted by Philip Dunne from the novel by Irvi...,NR,Classics|Drama,Carol Reed,Philip Dunne|Carol Reed,"Sep 16, 1965","Feb 22, 2005",NaN,NaN,140 minutes,NaN
1315,1700,NaN,NR,Drama,Loc Do,NaN,NaN,NaN,NaN,NaN,119 minutes,NaN
1320,1705,"After escaping from a psychiatric hospital, bi...",NR,Drama|Television,Ian Madden,Jimmy Gardner,"Jan 13, 2006","Sep 5, 2006",NaN,NaN,120 minutes,NaN
1324,1712,This romantic German drama pays tribute to the...,NR,Art House and International|Drama,Helma Sanders-Brahms,NaN,"Jan 1, 1997","Dec 23, 2008",NaN,NaN,105 minutes,NaN
1326,1714,"Through the prism of J, notions of in-between-...",NR,Drama,Anahita Ghazvinizadeh,Anahita Ghazvinizadeh,NaN,NaN,NaN,NaN,80 minutes,NaN
1327,1716,Jean and Colette are teen-aged sisters living ...,NR,Drama,Claude Gagnon,Claude Cagnon,"Feb 6, 1992","Jun 19, 2001",$,"32,000,000",113 minutes,NaN
1332,1723,PC is a super smart Jack Russell Terrier (Forr...,NR,Action and Adventure|Kids and Family,Karl Zwicky,Harry Cripps,NaN,NaN,NaN,NaN,83 minutes,NaN
1334,1727,Cattleman Gene Autry is put out-to say the lea...,NR,Western,Joseph Santley,Olive Cooper,NaN,NaN,NaN,NaN,71 minutes,NaN
1339,1733,A detective investigates the world of high fas...,NR,Drama,Nathan Hill,Nick Levy,NaN,NaN,NaN,NaN,90 minutes,NaN
1340,1734,"Two-time Academy Award-winner Jane Fonda (""On ...",NR,Classics|Drama|Musical and Performing Arts,George Cukor,Gene Allen|Wyatt Cooper,"Oct 5, 1962","Sep 13, 2012",NaN,NaN,125 minutes,NaN
1341,1735,NaN,NR,Art House and International|Drama,Alain Tanner,Alain Tanner,"Jan 1, 1983","Jul 15, 1992",NaN,NaN,108 minutes,NaN
1342,1736,NaN,NR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1344,1738,A boy wishes for a different set of parents fo...,NR,Drama,Emilio Ferrari,NaN,NaN,NaN,NaN,NaN,120 minutes,NaN
1345,1739,This film recounts a defining period of 20th c...,NR,Documentary|Drama|Special Interest,Jayne Loader|Kevin Rafferty|Pierce Rafferty,NaN,"Mar 17, 1982","Mar 26, 2002",NaN,NaN,88 minutes,NaN
1352,1746,Director Sergei Paradjanov made a practice of ...,NR,Art House and International|Drama|Special Inte...,Sergei Parajanov,Sergei Parajanov|Sayat Nova,"Oct 6, 1980","Mar 8, 2005",NaN,NaN,90 minutes,NaN

In [28]:
movie_buddget.iloc[[963,992,1042,1043,1093,1116,1148,1211,1244,1288,1291]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
963,64,"Apr 28, 2000",The Flintstones in Viva Rock Vegas,"$58,000,000","$35,231,365","$59,431,365"
992,93,"Jul 16, 1997",George Of The Jungle,"$55,000,000","$105,263,257","$174,463,257"
1042,43,"Sep 22, 2006",All the King's Men,"$55,000,000","$7,221,458","$9,521,458"
1043,44,"Jul 30, 2004",Thunderbirds,"$55,000,000","$6,768,055","$28,231,444"
1093,94,"Jun 28, 2002",Mr. Deeds,"$50,000,000","$126,293,452","$171,269,535"
1116,17,"Nov 24, 2004",Christmas with the Kranks,"$50,000,000","$73,701,902","$96,469,187"
1148,49,"Oct 3, 2003",Out of Time,"$50,000,000","$41,083,108","$55,489,826"
1211,12,"Jul 11, 1990",The Adventures of Ford Fairlane,"$49,000,000","$20,423,389","$20,423,389"
1244,45,"Jul 20, 2001",America's Sweethearts,"$46,000,000","$93,607,673","$160,648,493"
1288,89,"Sep 30, 1994",The River Wild,"$45,000,000","$46,815,000","$94,215,000"
1291,92,"Jan 13, 2006",Last Holiday,"$45,000,000","$38,399,961","$43,343,247"

In [29]:
# checking if the nmaes are already used
for i,x in enumerate(system_rating):
    if x == 'NR':
        print(name_movies[i])

Battleship
Robin Hood
X-Men: Days of Future Past
Transformers: Dark of the Moon
Star Trek Beyond
Aladdin
Fantastic Beasts and Where to Find Them
47 Ronin
Shrek Forever After
Pacific Rim: Uprising
X-Men Origins: Wolverine
Mad Max: Fury Road
Angels & Demons
The BFG
Dinosaur
X-Men 2
How the Grinch Stole Christmas
Monsters, Inc.
Live Free or Die Hard
300: Rise of an Empire
Batman Forever
Cloudy with a Chance of Meatballs
The Stepford Wives
The Expendables 3
The Road to El Dorado
Men in Black
Tropic Thunder
Contact
The Nutcracker in 3D
The Predator
Air Force One

In [30]:
# new names index for NR
no3=[963,992,1042,1043,1093,1116,1148,1211,1244,1288,1291]

In [31]:
# making sure all system_rating have the same amout of records
# getting system G: need 40
index_G = movie_info[movie_info['rating']=='G'].index
index_G[100:150]

Int64Index([], dtype='int64')

In [32]:
movie_info.iloc[[1441, 1450, 1522, 1528, 1540, 1544, 1557]]

,id,synopsis,rating,genre,director,writer,theater_date,dvd_date,currency,box_office,runtime,studio
1441,1858,"One of Elvis Presley's most popular vehicles, ...",G,Classics|Comedy|Musical and Performing Arts|Ro...,Boris Sagal,NaN,NaN,NaN,NaN,NaN,96 minutes,NaN
1450,1867,"Filmed in panoramic Cinerama, this star-studde...",G,Action and Adventure|Classics|Drama|Western,John Ford|Henry Hathaway|George Marshall|Richa...,NaN,"Feb 20, 1963","Sep 30, 2006",NaN,NaN,180 minutes,NaN
1522,1958,Twenty-nine-year-old Iranian-American writer C...,G,Drama,Amir Motlagh,Amir Motlagh,NaN,NaN,NaN,NaN,74 minutes,NaN
1528,1965,"Because of a misunderstanding on his part, Cli...",G,Animation|Kids and Family,Robert Ramirez,Robert Ramirez|Rhett Reese,"Apr 23, 2004","Aug 24, 2004",$,"2,782,548",73 minutes,Warner Bros. Pictures
1540,1979,"In this taut crime drama, a radio broadcaster ...",G,Classics|Drama|Mystery and Suspense,Michael Curtiz,Ranald MacDougall|Bess Meredyth,NaN,NaN,NaN,NaN,103 minutes,NaN
1544,1983,This animated children's film spoofs the Sherl...,G,Action and Adventure|Animation|Kids and Family,Burny Mattinson|Ron Clements|John Musker|Dave ...,NaN,"Jul 2, 1986","Jul 23, 2002",NaN,NaN,74 minutes,NaN
1557,1998,"Based on a novel by Richard Powell, when the l...",G,Classics|Comedy|Drama|Musical and Performing Arts,Gordon Douglas,NaN,"Jan 1, 1962","May 11, 2004",NaN,NaN,111 minutes,NaN

In [33]:
movie_buddget.iloc[[1147,1323]]

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
1147,48,"Sep 26, 1997",The Peacemaker,"$50,000,000","$41,263,140","$62,967,368"
1323,24,"Dec 25, 2002",Pinocchio,"$45,000,000","$3,681,811","$31,681,811"

In [34]:
# checking if the nmaes are already used
for i,x in enumerate(system_rating):
    if x == 'G':
        print(name_movies[i])

Where the Wild Things Are
A Good Day to Die Hard

In [35]:
# new name index for G
no = [1147,1323]

In [36]:
# getting system G name:need 40,couldnt get all missed 38
names=[]
for i in no:
    names.append(movie_buddget.movie[i])
names

['The Peacemaker', 'Pinocchio']

In [37]:
# getting system PG name:need 23
names1=[]
for i in no1:
    names1.append(movie_buddget.movie[i])
names1[:8]

['102 Dalmatians',
 'Last Action Hero',
 'Hellboy II: The Golden Army',
 'Swordfish',
 'Oceans',
 'Now You See Me',
 '355',
 'The Kingdom']

In [38]:
# getting system PG-13 name:need 24
names2=[]
for i in no2:
    names2.append(movie_buddget.movie[i])
names2[:8]

['Public Enemies',
 'The Tourist',
 'Finding Nemo',
 'Rise of the Planet of the Apes',
 'The Alamo',
 'Jumanji: Welcome to the Jungle',
 'Ice Age: Dawn of the Dinosaurs',
 'The Interpreter']

In [39]:
# getting system NR name:need 10
names3=[]
for i in no3:
    names3.append(movie_buddget.movie[i])
names3[:9]

['The Flintstones in Viva Rock Vegas',
 'George Of The Jungle',
 "All the King's Men",
 'Thunderbirds',
 'Mr. Deeds',
 'Christmas with the Kranks',
 'Out of Time',
 'The Adventures of Ford Fairlane',
 "America's Sweethearts"]

Now that all the new indexs has been idnetified they will be added to the new dataframe needed to create the five interactive graphs.

In [40]:
# add new 'R' names to the original
for i in names:
    name_movies.append(i)
len(name_movies)

117

In [41]:
# add new 'PG' names to the original
for i in names1:
    name_movies.append(i)
len(name_movies)

139

In [42]:
# add new 'PG-13' names to the original
for i in names2:
    name_movies.append(i)
len(name_movies)

165

In [43]:
# add new 'G' names to the original
for i in names3:
    name_movies.append(i)
len(name_movies)

176

Now that the names have been updated with the new indexes, we use it to get the rest of the key components from the original dataframe to add to the new dataframe.

In [44]:
#getting the index of the names to get other info from dataframe
index = []
for i in name_movies:
    index.append(list(movie_buddget[movie_buddget['movie']==i].index))
len(index)

176

In [45]:
#checking index to see integers that are not needed
index

[[6],
 [13],
 [14],
 [31],
 [32],
 [33],
 [38, 408],
 [40],
 [43],
 [44],
 [49],
 [50, 4759],
 [54],
 [56],
 [58],
 [60],
 [63],
 [64, 543],
 [69, 3999],
 [70],
 [76],
 [77],
 [78],
 [79],
 [80, 2032],
 [84],
 [85],
 [86],
 [91],
 [93],
 [94],
 [109],
 [111],
 [113],
 [118],
 [119],
 [120],
 [123],
 [126],
 [133],
 [142],
 [149],
 [159],
 [171],
 [172],
 [174],
 [180],
 [199],
 [201],
 [207],
 [209],
 [212],
 [216],
 [231],
 [240],
 [243, 3455, 5459],
 [246],
 [252],
 [257],
 [265],
 [271, 3050],
 [278, 779],
 [280],
 [281],
 [282],
 [283],
 [292],
 [298],
 [301],
 [302, 2313],
 [306],
 [309],
 [318],
 [320],
 [325],
 [336],
 [340, 4120],
 [347],
 [349],
 [354],
 [357],
 [365],
 [368],
 [369],
 [372],
 [374],
 [378],
 [380],
 [381],
 [385],
 [386],
 [395],
 [402],
 [406],
 [414],
 [416],
 [417],
 [418],
 [420],
 [422, 3007],
 [426],
 [430],
 [433],
 [435],
 [438],
 [449],
 [451],
 [458],
 [460],
 [470],
 [478],
 [483],
 [488],
 [491],
 [495],
 [1147],
 [1323, 4867],
 [505],
 [511],
 [531],
 [575],
 [601],
 [640],
 [671],
 [682],
 [694],
 [695],
 [278, 779],
 [784],
 [813],
 [818],
 [847],
 [869],
 [887],
 [957],
 [962],
 [986],
 [995],
 [1035],
 [358],
 [384],
 [424],
 [430],
 [434, 3409],
 [437],
 [442],
 [462],
 [492],
 [495],
 [499],
 [574],
 [597],
 [631],
 [674],
 [690],
 [736],
 [757],
 [781],
 [804],
 [838],
 [879],
 [884],
 [889],
 [926],
 [953],
 [963],
 [992],
 [1042],
 [1043],
 [1093],
 [1116],
 [1148],
 [1211],
 [1244],
 [1288],
 [1291]]

In [46]:
#Turning nested list to regular list
from funcy import flatten,isa
flat_list = flatten(index)

In [47]:
#converting list of list into int 
newflat_list = []
for i in flat_list:
    i=int(i)
    newflat_list.append(i)

In [48]:
# removing integers that are not needed
newflat_list1 = []
for i in newflat_list:
    if i == 3409:continue
    if i == 779:continue
    if i == 4867:continue
    if i == 3007:continue
    if i == 4120:continue
    if i == 2313:continue
    if i == 779:continue
    if i == 3050:continue
    if i == 3455:continue
    if i == 5459:continue
    if i == 2032:continue
    if i == 3999:continue
    if i == 543:continue
    if i == 4759:continue
    if i == 408:continue
    else: newflat_list1.append(i)

In [49]:
len(newflat_list1)

176

In [50]:
#using the updated indexes to get the new and old product budgets
product_budget = []
for x in newflat_list1:
    product_budget.append(movie_buddget.production_budget[x])
len(product_budget)

176

In [51]:
# using the updated indexes to get the new and old ratings
rating = []
for x in newflat_list1:
    rating.append(ratings.averagerating[x])
len(rating)

176

In [52]:
#using the updated indexes to get thenew and old system ratings
system_rating = []
for x in newflat_list1:
    system_rating.append(movie_info.rating[x])
len(system_rating)

176

In [53]:
# all system ratings have the same amout of records 42 except for 'G' system rating
# 'G' rating needs 23 movies 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'PG-13': 42, 'R': 46, 'NR': 42, 'PG': 42, 'G': 4})

The data set did not have enough movies in the Comedy genre that was G-rated. The 38 movies needed were from Box Office Mojo, they will be added to the data frame.

In [54]:
# name of all the movies selected
name_movies

['Avengers: Infinity War',
 'John Carter',
 'Tangled',
 'Battleship',
 'Transformers: The Last Knight',
 'Jurassic World',
 'Robin Hood',
 'The Golden Compass',
 'Incredibles 2',
 'Rogue One: A Star Wars Story',
 'Spider-Man 2',
 'Alice in Wonderland',
 'X-Men: Days of Future Past',
 'Cars 2',
 '2012',
 'Terminator Salvation',
 'Transformers: Dark of the Moon',
 'The Mummy',
 'The Great Gatsby',
 'Disneyâ\x80\x99s A Christmas Carol',
 'Brave',
 'Kong: Skull Island',
 'Star Trek Beyond',
 'Blade Runner 2049',
 'Aladdin',
 'Fantastic Beasts and Where to Find Them',
 'WALL-E',
 'Rush Hour 3',
 'Mission: Impossibleâ\x80\x94Fallout',
 'The Meg',
 'Edge of Tomorrow',
 'Waterworld',
 '47 Ronin',
 'Guardians of the Galaxy',
 'Snow White and the Huntsman',
 'Terminator 3: Rise of the Machines',
 'Van Helsing',
 'Alita: Battle Angel',
 'Shrek Forever After',
 'Cowboys and Aliens',
 'The Curious Case of Benjamin Button',
 'Pacific Rim: Uprising',
 'The Matrix Reloaded',
 'X-Men Origins: Wolverine',
 'Night at the Museum: Battle of the Smithsonian',
 'Mad Max: Fury Road',
 'Angels & Demons',
 'Tarzan',
 'Rise of the Guardians',
 'Armageddon',
 'Captain America: The First Avenger',
 'G.I. Joe: Retaliation',
 'The BFG',
 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 'Ant-Man and the Wasp',
 'Home',
 'Megamind',
 'After Earth',
 'Dinosaur',
 'X-Men 2',
 'Clash of the Titans',
 'Total Recall',
 'Monster Trucks',
 'The 13th Warrior',
 'How the Grinch Stole Christmas',
 'Mission: Impossible 2',
 'Oblivion',
 'Speed Racer',
 'Knight and Day',
 'Venom',
 'Monsters, Inc.',
 'The Huntsman: Winterâ\x80\x99s War',
 'San Andreas',
 'Live Free or Die Hard',
 '300: Rise of an Empire',
 'Home on the Range',
 'Around the World in 80 Days',
 'I, Robot',
 'The Princess and the Frog',
 'Gone in 60 Seconds',
 'A Wrinkle in Time',
 'Batman Forever',
 'Django Unchained',
 'Little Fockers',
 'Cloudy with a Chance of Meatballs',
 "Lemony Snicket's A Series of Unfortunate Events",
 'The Hunchback of Notre Dame',
 'The Expendables 2',
 'Where the Wild Things Are',
 'End of Days',
 'The Stepford Wives',
 'The Expendables 3',
 'Son of the Mask',
 'The Peanuts Movie',
 'Black Hawk Down',
 'Percy Jackson & the Olympians: The Lightning Thief',
 'The Campaign',
 'Unstoppable',
 'The Road to El Dorado',
 'Ben-Hur',
 'The Lord of the Rings: The Two Towers',
 'Rise of the Planet of the Apes',
 'A Good Day to Die Hard',
 'Cutthroat Island',
 'Men in Black',
 'Tropic Thunder',
 'Contact',
 'Pixels',
 'The Haunted Mansion',
 'Bicentennial Man',
 'The Nutcracker in 3D',
 'The Predator',
 'Happy Feet',
 'Air Force One',
 'Hotel Transylvania',
 'The Peacemaker',
 'Pinocchio',
 '102 Dalmatians',
 'Last Action Hero',
 'Hellboy II: The Golden Army',
 'Swordfish',
 'Oceans',
 'Now You See Me',
 '355',
 'The Kingdom',
 'Alvin and the Chipmunks: The Squeakquel',
 'Who Framed Roger Rabbit?',
 'Total Recall',
 'Step Brothers',
 'I, Frankenstein',
 'Oliver Twist',
 'The Green Mile',
 'The Family Man',
 'Joy',
 'Goosebumps',
 'The Internship',
 'The Pursuit of Happyness',
 'The Equalizer',
 'Chain Reaction',
 'Public Enemies',
 'The Tourist',
 'Finding Nemo',
 'Rise of the Planet of the Apes',
 'The Alamo',
 'Jumanji: Welcome to the Jungle',
 'Ice Age: Dawn of the Dinosaurs',
 'The Interpreter',
 'Fast & Furious',
 'Hotel Transylvania',
 'I Now Pronounce You Chuck and Larry',
 'Spirit: Stallion of the Cimarron',
 'Battlefield Earth: A Saga of the Year 3000',
 'Ice Age: The Meltdown',
 'Unbreakable',
 'Doctor Dolittle',
 'Escape Plan',
 'Money Train',
 'Unbroken',
 'Primary Colors',
 '2 Guns',
 'London Has Fallen',
 'Jack Reacher: Never Go Back',
 'The Jackal',
 'The Legend of Bagger Vance',
 'Sherlock Gnomes',
 'The Flintstones in Viva Rock Vegas',
 'George Of The Jungle',
 "All the King's Men",
 'Thunderbirds',
 'Mr. Deeds',
 'Christmas with the Kranks',
 'Out of Time',
 'The Adventures of Ford Fairlane',
 "America's Sweethearts",
 'The River Wild',
 'Last Holiday']

In [55]:
#Checking if the new movies selected are already in the old ones
for i in name_movies:
    if i == "Hannah Montana: The Movie":print('yes')

In [56]:
# the name of the movies
name_mojo = ['Chicken Run',"The Emperor's New Groove",'Ramona and Beezus','Wallace & Gromit: The Curse of the Were-Rabbit',
            'Africa Screams','Meet the Robinsons','Horton Hears a Who!',"A Bug's Life",'The Apple Dumpling Gang'
            ,'The Muppets','The Odd Couple','A Shaun the Sheep Movie: Farmageddon','The Absent-Minded Professor',
            'Bringing Up Baby','Alvin and the Chipmunks: Chipwrecked','Herbie Rides Again','Son of Flubber','The Love Bug',
             'A Night at the Opera','Babe',"Mr. Magorium's Wonder Emporium",'The Court Jester'
            ,'101 Dalmatians','Garfield: The Movie','Freaky Friday','The Return of the Pink Panthe','Yogi Bear',
            'The Swan Princess','The Sword in the Stone','Willy Wonka & the Chocolate Factory','Mary Poppins','Pinocchio','Winnie the Pooh',
             '102 Dalmatians','Hannah Montana: The Movie','The Land Before Time','My Fair Lady (1964)','Funny Girl']
        
# ratings of the movies
rating_mojo = [7,7.4,6.5,7.4,6.2,6.8,6.8,7.2,6.5,7.6,7.7,6.9,6.8,7.8,4.3,5.7,6.1,6.5,7.9,7.9,6.8,6.2,7.9,7.8,5.8,8.6,
               6.3,7.1,6.6,7.2,7.8,7.8,6.2,7.2,4.9,4.5,7.4,7.8]
# worldwide gross
worldwide_gross_mojo = ['$224,834,564','$169,296,573','$27,293,743','$192,600,000','$15,994,232','$169,333,034',' $297,000,000','$363,300,000','$182,471,345',
                       '$165,184,237','$44,527,234','$43,100,248','$219,031,530','$22,538,761','$342,695,435','$271,457,746','$186,813,335',
                       '$370,621,656','$34,806,552','$404,658,375','$69,474,661','$21,173,887','$900,300,000','$11,400,000','$208,094,550','$166,685,837',
                       '$206,965,572','$17,222,647','$187,509,473','$29,054,849','$850,726,024','$60,083,611','$49,871,429','$280,335,272',
                       '$155,545,279','$188,165,537','$599,370,116','$445,022,994']
# domestic gross
domestic_gross_mojo = ['$106,834,564','$89,296,573','$26,167,002','$56,100,000','0','$97,822,171','$155,000,000','$162,800,000','0',
                      '$76,657,000','0','0','$218,871,197','0','$133,110,742','$193,352,588','0','0','0','$101,417,760','$32,061,555','0','$136,189,294',
                      '$75,367,693','0','0','0','$17,222,647','$101,437,105','$29,054,849','$850,526,931','$5,345,581','$26,692,846','$102,300,998',
                      '$79,576,189','0','598,774,368','$445,022,994']
# product budget
product_budget_mojo = ['$45,000,000','$100,000,000','$15,000,000','$30,000,000','$5,331,410','$150,000,000','$85,000,000','$45,000,000','$26,984,745','$8,000,000',
                      '$1,200,000','$25,000,000','$20,535,559','$19,629,958','$75,000,000','$50,000,000','$16,906,184','$36,193,521',
                      '$20,270,262','$47,794,296','$65,000,000','$38,497,977','$75,000,000','$50,000,000','$23,150,810','$24,756,647',
                      '$80,000,000','$37,012,716','$25,359,276','$19,369,899','$33,265,242','43,000,000','$30,000,000','$129,784,848',
                      '$45,000,000','$27,389,776','$141,377,281','$66,707,115']

In [57]:
# adding names from mojo to the original
for i in name_mojo:
    name_movies.append(i)
len(name_movies)

214

In [58]:
g1 = 'G'*38
g1= list(g1)
for i in g1:
    system_rating.append(i)
len(system_rating)

214

In [59]:
# adding rating from mojo to the original
for i in rating_mojo:
    rating.append(i)
len(rating)

214

In [60]:
# adding product budget from mojo to the original
for i in product_budget_mojo:
    product_budget.append(i)
len(product_budget)

214

In [61]:
#using the updated indexes to get the new and old domestic gross
domestic_gross = []
for x in newflat_list1:
    domestic_gross.append(movie_buddget.domestic_gross[x])
len(domestic_gross)

176

In [62]:
# adding product budget from mojo to the original
for i in domestic_gross_mojo:
    domestic_gross.append(i)
len(domestic_gross)

214

In [63]:
### using the updated indexes to get the new and old worldwide gross
worldwide_gross = []
for x in newflat_list1:
    worldwide_gross.append(movie_buddget.worldwide_gross[x])
len(worldwide_gross)

176

In [64]:
# adding product budget from mojo to the original
for i in worldwide_gross_mojo:
    worldwide_gross.append(i)
len(worldwide_gross)

214

In [65]:
# checking all the index of the 'R' system rating to get rid of 4 movies we do not need
for i,x in enumerate(system_rating):
    if x == 'R':
        print(i,name_movies[i]) #we will choose index 14,20,29,17

2 Tangled
4 Transformers: The Last Knight
8 Incredibles 2
9 Rogue One: A Star Wars Story
10 Spider-Man 2
14 2012
15 Terminator Salvation
17 The Mummy
19 Disneyâs A Christmas Carol
20 Brave
21 Kong: Skull Island
26 WALL-E
27 Rush Hour 3
28 Mission: ImpossibleâFallout
29 The Meg
34 Snow White and the Huntsman
35 Terminator 3: Rise of the Machines
39 Cowboys and Aliens
44 Night at the Museum: Battle of the Smithsonian
47 Tarzan
48 Rise of the Guardians
49 Armageddon
50 Captain America: The First Avenger
51 G.I. Joe: Retaliation
56 Megamind
62 Monster Trucks
65 Mission: Impossible 2
69 Venom
75 Home on the Range
76 Around the World in 80 Days
78 The Princess and the Frog
80 A Wrinkle in Time
82 Django Unchained
83 Little Fockers
87 The Expendables 2
89 End of Days
92 Son of the Mask
93 The Peanuts Movie
94 Black Hawk Down
95 Percy Jackson & the Olympians: The Lightning Thief
97 Unstoppable
99 Ben-Hur
103 Cutthroat Island
108 The Haunted Mansion
112 Happy Feet
164 Sherlock Gnomes

In [66]:
#removing the elements with the indexes but putting each index less than the actual one 
for i in [14,19,27,16]:
    name_movies.pop(i)
    system_rating.pop(i)
    rating.pop(i)
    domestic_gross.pop(i)
    product_budget.pop(i)
    worldwide_gross.pop(i)

In [67]:
# all system ratings have the same amout of records 42 
grouped_rating = []
grouped_rating=(collections.Counter(system_rating))
grouped_rating

Counter({'PG-13': 42, 'R': 42, 'NR': 42, 'PG': 42, 'G': 42})

All the information have been gathered, the script below uses it to create a new and updated dataframe.

In [68]:
all_Comedy_info = pd.DataFrame({'Name':name_movies,'System_ratings':system_rating,'Rating':rating,'Worlwide_gross':worldwide_gross,
                               'Domestic_gross':domestic_gross,'Product_budget':product_budget})
all_Comedy_info1=all_Comedy_info.dropna()
all_Comedy_info1 = all_Comedy_info[all_Comedy_info.Name !='Moonfall']

Now that the dataframe has been updated, Worldwide Gross, Product Budget and Domestic Gross has to be converted from string to int.

In [69]:
# turning Worldwide gross into int
storage1 = []
storage2 = []
total_gross=[]
for i in  all_Comedy_info1.dropna().Worlwide_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    total_gross.append(i)
len(total_gross)

210

In [70]:
# turning Produt budget  into int
storage1 = []
storage2 = []
budget=[]
for i in  all_Comedy_info1.dropna().Product_budget:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    budget.append(i)
len(budget)

210

In [71]:
# turning Domestic gross into int
storage1 = []
storage2 = []
Doomestic_gross=[]
for i in  all_Comedy_info1.dropna().Domestic_gross:
    storage1.append(i.replace('$',''))
for i in storage1:
    storage2.append(i.replace(',',''))
for i in storage2:   
    i = int(i)
    Doomestic_gross.append(i)
len(Doomestic_gross)

210

In [72]:
#drop all the NA from the dataframe
all_Comedy_info1 = all_Comedy_info1.dropna()


#adding all the string componnets that have been converted to dataframe
all_Comedy_info1['Buget']=budget
all_Comedy_info1['Total_gross']=total_gross
all_Comedy_info1['Domestic_total']=Doomestic_gross
all_Comedy_info1[190:]

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total
190,A Night at the Opera,G,7.9,"$34,806,552",0,"$20,270,262",20270262,34806552,0
191,Babe,G,7.9,"$404,658,375","$101,417,760","$47,794,296",47794296,404658375,101417760
192,Mr. Magorium's Wonder Emporium,G,6.8,"$69,474,661","$32,061,555","$65,000,000",65000000,69474661,32061555
193,The Court Jester,G,6.2,"$21,173,887",0,"$38,497,977",38497977,21173887,0
194,101 Dalmatians,G,7.9,"$900,300,000","$136,189,294","$75,000,000",75000000,900300000,136189294
195,Garfield: The Movie,G,7.8,"$11,400,000","$75,367,693","$50,000,000",50000000,11400000,75367693
196,Freaky Friday,G,5.8,"$208,094,550",0,"$23,150,810",23150810,208094550,0
197,The Return of the Pink Panthe,G,8.6,"$166,685,837",0,"$24,756,647",24756647,166685837,0
198,Yogi Bear,G,6.3,"$206,965,572",0,"$80,000,000",80000000,206965572,0
199,The Swan Princess,G,7.1,"$17,222,647","$17,222,647","$37,012,716",37012716,17222647,17222647
200,The Sword in the Stone,G,6.6,"$187,509,473","$101,437,105","$25,359,276",25359276,187509473,101437105
201,Willy Wonka & the Chocolate Factory,G,7.2,"$29,054,849","$29,054,849","$19,369,899",19369899,29054849,29054849
202,Mary Poppins,G,7.8,"$850,726,024","$850,526,931","$33,265,242",33265242,850726024,850526931
203,Pinocchio,G,7.8,"$60,083,611","$5,345,581","43,000,000",43000000,60083611,5345581
204,Winnie the Pooh,G,6.2,"$49,871,429","$26,692,846","$30,000,000",30000000,49871429,26692846
205,102 Dalmatians,G,7.2,"$280,335,272","$102,300,998","$129,784,848",129784848,280335272,102300998
206,Hannah Montana: The Movie,G,4.9,"$155,545,279","$79,576,189","$45,000,000",45000000,155545279,79576189
207,The Land Before Time,G,4.5,"$188,165,537",0,"$27,389,776",27389776,188165537,0
208,My Fair Lady (1964),G,7.4,"$599,370,116","598,774,368","$141,377,281",141377281,599370116,598774368
209,Funny Girl,G,7.8,"$445,022,994","$445,022,994","$66,707,115",66707115,445022994,445022994

In [73]:
# getting profit
profit = []
for x,y in enumerate(total_gross):
    profit.append(y-budget[x])
len(profit)

210

In [74]:
all_Comedy_info1['Profit']=profit

In [75]:
all_Comedy_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit
0,Avengers: Infinity War,PG-13,7.0,"$2,048,134,200","$678,815,482","$300,000,000",300000000,2048134200,678815482,1748134200
1,John Carter,PG-13,8.0,"$282,778,100","$73,058,679","$275,000,000",275000000,282778100,73058679,7778100
2,Tangled,R,5.5,"$586,477,240","$200,821,936","$260,000,000",260000000,586477240,200821936,326477240
3,Battleship,NR,5.4,"$313,477,717","$65,233,400","$220,000,000",220000000,313477717,65233400,93477717
4,Transformers: The Last Knight,R,3.4,"$602,893,340","$130,168,683","$217,000,000",217000000,602893340,130168683,385893340
...,...,...,...,...,...,...,...,...,...,...
205,102 Dalmatians,G,7.2,"$280,335,272","$102,300,998","$129,784,848",129784848,280335272,102300998,150550424
206,Hannah Montana: The Movie,G,4.9,"$155,545,279","$79,576,189","$45,000,000",45000000,155545279,79576189,110545279
207,The Land Before Time,G,4.5,"$188,165,537",0,"$27,389,776",27389776,188165537,0,160775761
208,My Fair Lady (1964),G,7.4,"$599,370,116","598,774,368","$141,377,281",141377281,599370116,598774368,457992835
209,Funny Girl,G,7.8,"$445,022,994","$445,022,994","$66,707,115",66707115,445022994,445022994,378315879

In [76]:
# Creating Box office column
# dividing total gross by the avg price of tickets, to get an estimsted number of tickes sold
no_tickets = []
for i in all_Comedy_info1.Total_gross:
    no_tickets.append(round(i/13)) 
no_tickets[:10]

[157548785,
 21752162,
 45113634,
 24113671,
 46376411,
 126834990,
 24804539,
 28250966,
 95578516,
 80700220]

In [77]:
# converting integer of no. of tickets into string
tickets_string = []
for i in no_tickets:
    tickets_string.append("{:,.0f}".format(i))
len(tickets_string)

210

In [78]:
# converting integer of profit to currency
currency = []
for i in all_Comedy_info1.Profit:
    currency.append("${:,.0f}".format(i))
len(currency)

210

In [79]:
all_Comedy_info1['No.Tickets']=tickets_string
all_Comedy_info1['Profit$']= currency
all_Comedy_info1

,Name,System_ratings,Rating,Worlwide_gross,Domestic_gross,Product_budget,Buget,Total_gross,Domestic_total,Profit,No.Tickets,Profit$
0,Avengers: Infinity War,PG-13,7.0,"$2,048,134,200","$678,815,482","$300,000,000",300000000,2048134200,678815482,1748134200,"157,548,785","$1,748,134,200"
1,John Carter,PG-13,8.0,"$282,778,100","$73,058,679","$275,000,000",275000000,282778100,73058679,7778100,"21,752,162","$7,778,100"
2,Tangled,R,5.5,"$586,477,240","$200,821,936","$260,000,000",260000000,586477240,200821936,326477240,"45,113,634","$326,477,240"
3,Battleship,NR,5.4,"$313,477,717","$65,233,400","$220,000,000",220000000,313477717,65233400,93477717,"24,113,671","$93,477,717"
4,Transformers: The Last Knight,R,3.4,"$602,893,340","$130,168,683","$217,000,000",217000000,602893340,130168683,385893340,"46,376,411","$385,893,340"
...,...,...,...,...,...,...,...,...,...,...,...,...
205,102 Dalmatians,G,7.2,"$280,335,272","$102,300,998","$129,784,848",129784848,280335272,102300998,150550424,"21,564,252","$150,550,424"
206,Hannah Montana: The Movie,G,4.9,"$155,545,279","$79,576,189","$45,000,000",45000000,155545279,79576189,110545279,"11,965,021","$110,545,279"
207,The Land Before Time,G,4.5,"$188,165,537",0,"$27,389,776",27389776,188165537,0,160775761,"14,474,272","$160,775,761"
208,My Fair Lady (1964),G,7.4,"$599,370,116","598,774,368","$141,377,281",141377281,599370116,598774368,457992835,"46,105,394","$457,992,835"
209,Funny Girl,G,7.8,"$445,022,994","$445,022,994","$66,707,115",66707115,445022994,445022994,378315879,"34,232,538","$378,315,879"

After the dataframe has been updated, bokeh is being installed.

In [80]:
from bokeh.layouts import gridplot,row
from bokeh.plotting import figure,output_file,ColumnDataSource
from bokeh.io import push_notebook,show,output_notebook
from bokeh.models import NumeralTickFormatter
output_notebook()

Bokeh is successfully installed, now the key componets need to be creted for each system rating group to make the graphs.

A reminder of the componets;
 - Cost
 - Proft
 - Name
 - Profit Percntage by Cost
 - Type of System Rating

In [81]:
# index of all 'R' system ratings
index_r = []
for i,x in enumerate(system_rating):
    if x == 'R':index_r.append(i)

In [82]:
# getiing the profit for all 'R' system rating
r_profit = []
for i in index_r:
    r_profit.append(all_Comedy_info1.Profit[i])
len(r_profit)

42

In [83]:
# getting the cost for 'R' system rating
cost1 = []
for i in index_r:
    cost1.append(all_Comedy_info1.Product_budget[i])
len(cost1)

42

In [84]:
# getiing the name for all 'R' system rating
r_name = []
for i in index_r:
    r_name.append(all_Comedy_info1.Name[i])
len(r_name)

42

In [85]:
# getiing the $profit for all 'R' system rating
r_dollar = []
for i in index_r:
    r_dollar.append(all_Comedy_info1['Profit$'][i])
len(r_dollar)

42

In [86]:
# getiing the system rating for all 'R' system rating
r_sratings = []
for i in index_r:
    r_sratings.append(all_Comedy_info1.System_ratings[i])
len(r_sratings)

42

In [87]:
# getting percentage profit for all 'R' system rating
percent_profit = []
for i in index_r:
    i = (all_Comedy_info1.Profit[i] / all_Comedy_info1.Buget[i])*100
    percent_profit.append(round(i,0))
len(percent_profit)

42

In [88]:
# turning float of percentage of profit into int for 'R' system rating
pp = []
for i in percent_profit:
    i = int(i)
    pp.append(i)
len(pp)

42

In [89]:
# converting integer to percentage for 'R' system rating
percentage_profit = []
for i in pp:
    percentage_profit.append("{:}%".format(i))
len(percentage_profit)

42

In [90]:
# index of all 'G' system ratings
index_g = []
for i,x in enumerate(system_rating):
    if x == 'G':index_g.append(i)

In [91]:
# getiing the profit for all 'G' system rating
g_profit = []
for i in index_g:
    g_profit.append(all_Comedy_info1.Profit[i])
len(g_profit)

42

In [92]:
# getting the cost for 'G' system rating
cost2 = []
for i in index_g:
    cost2.append(all_Comedy_info1.Product_budget[i])
len(cost2)

42

In [93]:
# getiing the name for all 'G' system rating
g_name = []
for i in index_g:
    g_name.append(all_Comedy_info1.Name[i])
len(g_name)

42

In [94]:
# getiing the $profit for all 'G' system rating
g_dollar = []
for i in index_g:
    g_dollar.append(all_Comedy_info1['Profit$'][i])
len(g_dollar)

42

In [95]:
# getiing the system rating for all 'G' system rating
g_sratings = []
for i in index_g:
    g_sratings.append(all_Comedy_info1.System_ratings[i])
len(g_sratings)

42

In [96]:
# getting percentage profit for all 'G' system rating
percent_profit1 = []
for i in index_g:
    i = (all_Comedy_info1.Profit[i] / all_Comedy_info1.Buget[i])*100
    percent_profit1.append(round(i,0))
len(percent_profit1)

42

In [97]:
# turning float of percentage of profit into int for 'G' system rating
pp1= []
for i in percent_profit1:
    i = int(i)
    pp1.append(i)
len(pp1)

42

In [98]:
# converting integer to percentage for 'G' system rating
percentage_profit1 = []
for i in pp1:
    percentage_profit1.append("{:}%".format(i))
len(percentage_profit1)

42

In [99]:
# index of all 'PG' system ratings
index_pg = []
for i,x in enumerate(system_rating):
    if x == 'PG':index_pg.append(i)

In [100]:
# getiing the profit for all 'PG' system rating
pg_profit = []
for i in index_pg:
    pg_profit.append(all_Comedy_info1.Profit[i])
len(pg_profit)

42

In [101]:
# getting the cost for 'PG' system rating
cost3 = []
for i in index_pg:
    cost3.append(all_Comedy_info1.Product_budget[i])
len(cost3)

42

In [102]:
# getiing the name for all 'PG' system rating
pg_name = []
for i in index_pg:
    pg_name.append(all_Comedy_info1.Name[i])
len(pg_name)

42

In [103]:
# getiing the $profit for all 'PG' system rating
pg_dollar = []
for i in index_pg:
    pg_dollar.append(all_Comedy_info1['Profit$'][i])
len(pg_dollar)

42

In [104]:
# getiing the system rating for all 'PG' system rating
pg_sratings = []
for i in index_pg:
    pg_sratings.append(all_Comedy_info1.System_ratings[i])
len(pg_sratings)

42

In [105]:
# getting percentage profit for all 'PG' system rating
percent_profit2 = []
for i in index_pg:
    i = (all_Comedy_info1.Profit[i] / all_Comedy_info1.Buget[i])*100
    percent_profit2.append(round(i,0))
len(percent_profit2)

42

In [106]:
# turning float of percentage of profit into int for 'PG' system rating
pp2= []
for i in percent_profit2:
    i = int(i)
    pp2.append(i)
len(pp2)

42

In [107]:
# converting integer to percentage for 'PG' system rating
percentage_profit2= []
for i in pp2:
    percentage_profit2.append("{:}%".format(i))
len(percentage_profit2)

42

In [108]:
# index of all 'PG-13' system ratings
index_pg13 = []
for i,x in enumerate(system_rating):
    if x == 'PG-13':index_pg13.append(i)

In [109]:
# getiing the profit for all 'PG-13' system rating
pg13_profit = []
for i in index_pg13:
    pg13_profit.append(all_Comedy_info1.Profit[i])
len(pg13_profit)

42

In [110]:
# getiing the name for all 'PG-13' system rating
pg13_name = []
for i in index_pg13:
    pg13_name.append(all_Comedy_info1.Name[i])
len(pg13_name)

42

In [111]:
# getting the cost for 'PG-13' system rating
cost4 = []
for i in index_pg13:
    cost4.append(all_Comedy_info1.Product_budget[i])
len(cost4)

42

In [112]:
# getiing the $profit for all 'PG-13' system rating
pg13_dollar = []
for i in index_pg13:
    pg13_dollar.append(all_Comedy_info1['Profit$'][i])
len(pg13_dollar)

42

In [113]:
# getiing the system rating for all 'PG-13' system rating
pg13_sratings = []
for i in index_pg13:
    pg13_sratings.append(all_Comedy_info1.System_ratings[i])
len(pg13_sratings)

42

In [114]:
# getting percentage profit for all 'PG-13' system rating
percent_profit3 = []
for i in index_pg13:
    i = (all_Comedy_info1.Profit[i] / all_Comedy_info1.Buget[i])*100
    percent_profit3.append(round(i,0))
len(percent_profit3)

42

In [115]:
# turning float of percentage of profit into int
pp3= []
for i in percent_profit3:
    i = int(i)
    pp3.append(i)
len(pp3)

42

In [116]:
# converting integer to percentage
percentage_profit3= []
for i in pp3:
    percentage_profit3.append("{:}%".format(i))
len(percentage_profit3)

42

In [117]:
# index of all 'NR' system ratings
index_NR = []
for i,x in enumerate(system_rating):
    if x == 'NR':index_NR.append(i)

In [118]:
# getiing the profit for all 'NR' system rating
NR_profit = []
for i in index_NR:
    NR_profit.append(all_Comedy_info1.Profit[i])
len(NR_profit)

42

In [119]:
# getiing the name for all 'NR' system rating
nr_name = []
for i in index_NR:
    nr_name.append(all_Comedy_info1.Name[i])
len(nr_name)

42

In [120]:
# getting the cost for 'NR' system rating
cost5 = []
for i in index_NR:
    cost5.append(all_Comedy_info1.Product_budget[i])
len(cost5)

42

In [121]:
# getiing the $profit for all 'NR' system rating
nr_dollar = []
for i in index_NR:
    nr_dollar.append(all_Comedy_info1['Profit$'][i])
len(nr_dollar)

42

In [122]:
# getiing the system rating for all 'NR' system rating
nr_sratings = []
for i in index_NR:
    nr_sratings.append(all_Comedy_info1.System_ratings[i])
len(nr_sratings)

42

In [123]:
# getting percentage profit for all 'NR' system rating
percent_profit4 = []
for i in index_NR:
    i = (all_Comedy_info1.Profit[i] / all_Comedy_info1.Buget[i])*100
    percent_profit4.append(round(i,0))
len(percent_profit4)

42

In [124]:
# turning float of percentage of profit into int for 'NR' system rating
pp4= []
for i in percent_profit4:
    i = int(i)
    pp4.append(i)
len(pp4)

42

In [125]:
# converting integer to percentage for 'NR' system rating
percentage_profit4= []
for i in pp4:
    percentage_profit4.append("{:}%".format(i))
len(percentage_profit4)

42

In [128]:
rangee = list(range(42)) # x-axis range
# allows the garph to hover over the piont to show all information about the pionts  
TOOLS = "pan,wheel_zoom,box_zoom,reset,save,box_select,hover"

# Graph 1
source = ColumnDataSource(data=dict(
    x = rangee, # x-axis
    y = r_profit,# y-axis
    name=r_name, # name of movie
    profit=r_dollar,# profit in currency($)
    system_rating=r_sratings ,# system rating of movie
    percent_profit=percentage_profit,# profit percentage based on cost
    cost1=cost1))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name"),# the name
    ("Cost","@cost1"),# the cost
    ("Profit","@profit"),# the profit
    ("(System-Rating)","@system_rating"),# the system rating
    ("(Profit-Percentage)","@percent_profit")]# the profit percentage
p3 = figure(title='Profit.Drama.System Rating R',tools=TOOLS,plot_height=300,
           plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p3.left[0].formatter.use_scientific=False 
# makes the digits more visible by turning it into millions on the y-axis
p3.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
p3.circle('x','y',color="#41FA02",width=3,source=source)
p3.line('x','y',color="#41FA02",# the style and color of the graph
        line_dash='dashed',line_width=2,source=source)

# Graph 2
source4 = ColumnDataSource(data=dict(
     o=rangee,# x-axis
     e=g_profit,# y-axis
     name1=g_name,# name of movies
     profit1=g_dollar,# profit of movies in curreny($)
     system_rating1=g_sratings,# system rating of movie
     percent_profit1=percentage_profit1,# profit percentage based on cost
     cost2=cost2))# cost of movie
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name1"),# the name
    ("Cost","@cost2"),# the cost
    ("Profit","@profit1"),# the profit in dollars
    ("(System-Rating)","@system_rating1"),# the system rating
    ("(Profit-Percentage)","@percent_profit1")]# the profit percentage
p4 = figure(title='Profit.Drama.System Rating G',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p4.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p4.yaxis[0].formatter=NumeralTickFormatter(format="$0.a")
# the style and color of the graph
p4.circle(x='o',y='e',color='#1EBD51',width=3,source=source4)
p4.line(x='o',y='e',color='#1EBD51',source=source4)
 
# Graph 3
source1 = ColumnDataSource(data=dict(
       p=rangee,# x-axis
       q=pg_profit,# y-axis
       name2=pg_name,# name of movies
       profit2=pg_dollar,# profit of movies in currency ($)
       system_rating2=pg_sratings,# system rating of moives
       percent_profit2=percentage_profit2,# profit percnetage based on cost
       cost3=cost3))# cost of movies
# tooltips information, this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name2"),# the name 
    ("Cost","@cost3"),# the cost
    ("Profit","@profit2"),# the profit the dollars
    ("(System-Rating)","@system_rating2"),# the system rating
    ("(Profit-Percentage)","@percent_profit2")]# the profit percentage 
p5 = figure(title='Profit.Drama.System Rating PG',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
# takes away the scientific notation off the y-axis
p5.left[0].formatter.use_scientific=False
# makes the digits more visible by turning it into millions on the y-axis
p5.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of graph
p5.square(x='p',y='q',line_color='#40BC12',fill_color=None,source=source1)
p5.line(x='p',y='q',line_color='#40BC12',source=source1)

# Graph 4
source2 = ColumnDataSource(data=dict(
       r=rangee,# x-axis
       t=pg13_profit,# y-axis
       name3=pg13_name,# name of movies
       profit3=pg13_dollar,# profit of movies to currency ($)
       system_rating3=pg13_sratings,# system rating of movies
       percent_profit3=percentage_profit3,# profit percentage based on cost
       cost4=cost4))# cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name3"),# the name
    ("Cost","@cost4"),# the cost
    ("Profit","@profit3"),# the profit in dollars
    ("(System-Rating)","@system_rating3"),# the system rating
    ("(Profit-Percentage)","@percent_profit3")]# the profit percentage
p6 = figure(title='Profit.Drama.System Rating PG-13',tools=TOOLS,plot_height=300,
            plot_width=300,tooltips=TOOLTIPS)
#takes away the scientific notation off the y-axis
p6.left[0].formatter.use_scientific=False
# makes the digits more visible ny turning it into millions on the y-axis
p6.yaxis[0].formatter=NumeralTickFormatter(format='$0.a')
# the style and color of the graph
p6.triangle(x='r',y='t',color='#118A1E',width=2,source=source2)
p6.line(x='r',y='t',color='#118A1E',width=2,source=source2)

# Graph 5
source3 = ColumnDataSource(data=dict(
        l=rangee,# x-axis
        i=NR_profit,# y-axis
        name4=nr_name,# name of movies
        profit4=nr_dollar,# profit of movies to currency ($)
        system_rating4=nr_sratings,# system rating of movies
        percent_profit4=percentage_profit4,# profit percentage based on cost
        cost5=cost5))#cost of movies
#tooltips information; this is all the info shown when hovered
TOOLTIPS=[
    ("Name","@name4"),# the name
    ("Cost","@cost5"),# the cost
    ("Profit","@profit4"),# the profit in dollars
    ("(System-Rating)","@system_rating4"),# the system rating
    ("(Profit-Percentage)","@percent_profit4")]# the profit percentage
p7 = figure(title='Profit.Drama.System Rating NR',tools=TOOLS,
            plot_height=300,plot_width=300,tooltips=TOOLTIPS)
#takes away the scientiifc notation off the y-axis
p7.left[0].formatter.use_scientific=False
#makes the digits more visible by turning it into millions  on the y-axis
p7.yaxis[0].formatter=NumeralTickFormatter(format="$0.0a")
# the style and color of the graph
p7.circle(x='l',y='i',color='#4AA90D',fill_color=None,width=2,source=source3)
p7.line(x='l',y='i',color='#4AA90D',width=2,source=source3)

output_file("toolbar.thml")
show(row(p3,p4,p5,p6,p7))# this puts the graphs side by side

# Blueprint: Gross Profit Margin Percentage

This is the blueprint for creating the second visualiztion Gross Profit Margin Percentage, altair will be used to create this graph.

__Blueprint__:
 - 1. Understanding the dataframe format used to create this data visualiztion helps make the process easier, these are the key componets that make up the dataframe used for this graph.
   
    - The data frame that altair used to create this graph consist of four colunms;
     
       - Yield: This colunm is the only colunm that shows any type of informations that is in numbers 
       - Variety: This colunm is the only column that contains category or groupings among the other pionts in the dataframe
       - Year: This colunm is based on datasets that contains timeframes
       - Site: This is a colunm that pinpionts differiantion among the rest of the data pionts
       
 
 - 2. Create five dataframes for five different graphs based on the documented format that is supplied by Altair. 
   
    - The dataframes will consist of these six columns;
      
       - Name: This colunm shows the names of each movie
       - Type: The concept of this graph portrays the profit made compared to the Revenue, the two main elements that reflects that is the Revenue and the Profit ergo the 'Type' column are made up of those two elements.
       - Yield: This colunm shows how much the 'Type' column is in int, this is used to plot the pionts in the graph.
       - Type Yield: This colunm shows the 'Yield' colunm in currency which is a string, this is mostly used for the tooltip to make it easier to understand how much the elements in the 'Type' column is in dollars.
       - System Rating: This shows the System Rating of each movie.
       - Gross Profit Margin: This colunm shows the gross profit margin in percentage.
       
 
 - 3. The style of this graph is a Becker's Barkey Trellis Plot which is found in Altair's Gallery. There are two pionts shaped as a ring in each panel, the first ring projects the Renvue and the other ring projects the Profit, this set up allows the perseption of how much of a fraction do each movie actually walk away with when compared to the Revenue allowing the Profit to be seen from a differnt angle. This could make the movie look more profitable or seem over-rated. Each ring when hovered shows the Name of the movie, the Type choosing beteween Profit or Revenue, the Type Yield which is the amount of the Type in dollars, the Gross Profit Margin Percentage and the System Rating. The closer the Profit is to the Revenue the more buoyant it is!

In [101]:
# understanding how the data frame is formatted
# this was the eact dataframe used in Altairs example
from vega_datasets import data
source = data.barley()
source

        yield           variety  year             site
0    27.00000         Manchuria  1931  University Farm
1    48.86667         Manchuria  1931           Waseca
2    27.43334         Manchuria  1931           Morris
3    39.93333         Manchuria  1931        Crookston
4    32.96667         Manchuria  1931     Grand Rapids
..        ...               ...   ...              ...
115  58.16667  Wisconsin No. 38  1932           Waseca
116  47.16667  Wisconsin No. 38  1932           Morris
117  35.90000  Wisconsin No. 38  1932        Crookston
118  20.66667  Wisconsin No. 38  1932     Grand Rapids
119  29.33333  Wisconsin No. 38  1932           Duluth

[120 rows x 4 columns]

These are the variables needed to create the columns for the first dataframe; new_name,new_systems, new_total_gross, new_worldwide_gross, new_profit, new_currency_profit, gross_profit_margin_percentage.

This is all the names of the movie for the rated-R movies.

In [102]:
new_name=[]
name = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x=='R':
            name.append(all_Comedy_info1.Name[i])
for i,x in enumerate(name):
    new_name.append( x)
len(new_name)

42

This is all the domestic revenue of each movie in the rated-R catagory of movies.

In [103]:
new_total_gross = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='R':
            new_total_gross.append(all_Comedy_info1.Total_gross[i])
len(new_total_gross)

42

This is all the world wide revenue of each movie in the rated-R catagory of movies.

In [104]:
new_worldwide_gross = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='R':
            new_worldwide_gross.append(all_Comedy_info1.Worlwide_gross[i])
len(new_worldwide_gross)

42

This is all the profit in dollars of each movie in the rated-R catagory, this is particularly used for tooltip.

In [105]:
new_currency_profit = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='R':
            new_currency_profit.append(all_Comedy_info1['Profit$'][i])
len(new_currency_profit)

42

This is all the profit in int of each mvoie in the rated-R catagory, this is particularly used for the Y and X axis.

In [106]:
new_profit = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='R':
            new_profit.append(all_Comedy_info1.Profit[i])
len(new_profit)

42

In [107]:
# a list of rated-'r'
new_systems = list('R'*42)
len(new_systems)

42

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [108]:
# Creating the gross profit margin percentage column
p_rev = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'R':
        p_rev.append((all_Comedy_info1.Profit[i] / all_Comedy_info1.Total_gross[i])*100)
len(p_rev)

42

In [109]:
# turning float of percentage of profit into int
pp_rev= []
for i in p_rev:
    i = int(i)
    pp_rev.append(round(i,0))
len(pp_rev)

42

In [110]:
# converting integer to percentage
gross_profit_margin_percentage= []
for i in pp_rev:
    gross_profit_margin_percentage.append("{:}%".format(i))
len(gross_profit_margin_percentage)

42

These are the variables needed to create the columns for the second dataframe; new_name1, new_systems1, new_total_gross1, new_worldwide_gross1, new_profit1, new_currency_profit1, gross_profit_margin_percentage1

This is all the names of the movie for the rated-PG movies.

In [111]:
new_name1=[]
name1 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG':
            name1.append(all_Comedy_info1.Name[i])
for i,x in enumerate(name1):
    new_name1.append( x)
new_name1.pop(27)
len(new_name1)

41

This is all the domestic revenue of each movie in the rated-PG catagory of movies.

In [112]:
new_total_gross1 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG':
            new_total_gross1.append(all_Comedy_info1.Total_gross[i])
new_total_gross1.pop(27)
len(new_total_gross1)

41

This is all the world wide revenue of each movie in the rated-PG catagory of movies.

In [113]:
new_worldwide_gross1= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG':
            new_worldwide_gross1.append(all_Comedy_info1.Worlwide_gross[i])
new_worldwide_gross1.pop(27)
len(new_worldwide_gross1)

41

This is all the profit in dollars of each movie in the rated-PG catagory, this is particularly used for tooltip.

In [114]:
new_currency_profit1 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG':
            new_currency_profit1.append(all_Comedy_info1['Profit$'][i])
new_currency_profit1.pop(27)
len(new_currency_profit1)

41

This is all the profit in int of each mvoie in the rated-PG catagory, this is particularly used for the Y and X axis.

In [115]:
new_profit1 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG':
            new_profit1.append(all_Comedy_info1.Profit[i])
new_profit1.pop(27)
len(new_profit1)

41

In [116]:
# list of rated-'PG'
new_systems1 = []
for i in list(range(0,41)):
    new_systems1.append('PG')
len(new_systems1 )

41

The code below devides the profit of each movie from the total revenue of each movie and multiplies it by 100 to get the Gross Profit Margin Percentage.

In [117]:
# Creating the profit rev percentage column
p1_rev = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG':
        p1_rev.append((all_Comedy_info1.Profit[i] / all_Comedy_info1.Total_gross[i])*100)
p1_rev.pop(27)#getting rid of the inf integer
len(p1_rev)

<ipython-input-117-3a596fb9e46c>:5: RuntimeWarning: divide by zero encountered in longlong_scalars
  p1_rev.append((all_actionadventure_info1.Profit[i] / all_actionadventure_info1.Total_gross[i])*100)

41

In [118]:
# turning float of percentage of profit into int
pp1_rev= []
for i in p1_rev:
    i = int(i)
    pp1_rev.append(round(i,0))
len(pp1_rev)

41

In [119]:
# converting integer to percentage
gross_profit_margin_percent1= []
for i in pp1_rev:
    gross_profit_margin_percent1.append("{:}%".format(i))
gross_profit_margin_percent1
len(gross_profit_margin_percent1)

41

These are the variables needed to create the columns for the third dataframe; new_name2, new_systems2, new_total_gross2, new_worldwide_gross2, new_profit2, new_currency_profit2, gross_profit_margin_percentage2

In [120]:
new_name2=[]
name2 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='G':
            name2.append(all_Comedy_info1.Name[i])
for i,x in enumerate(name2):
    new_name2.append(x)
len(new_name2)

42

In [121]:
new_systems2= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='G':
            new_systems2.append(all_Comedy_info1.Total_gross[i])
len(new_systems2)

42

In [122]:
new_worldwide_gross2= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='G':
            new_worldwide_gross2.append(all_Comedy_info1.Worlwide_gross[i])
len(new_worldwide_gross2)

42

In [123]:
new_currency_profit2 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='G':
            new_currency_profit2.append(all_Comedy_info1['Profit$'][i])
len(new_currency_profit2)

42

In [124]:
new_profit2 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='G':
            new_profit2.append(all_Comedy_info1.Profit[i])
len(new_profit2)

42

In [125]:
new_systems2 = list('G'*42)
len(new_systems2)

42

In [126]:
# Creating the profit rev percentage column
p2_rev = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'G':
        p2_rev.append((all_Comedy_info1.Profit[i] / all_Comedy_info1.Total_gross[i])*100)
len(p2_rev)

42

In [127]:
# turning float of percentage of profit into int
pp2_rev= []
for i in p2_rev:
    i = int(i)
    pp2_rev.append(round(i,0))
len(pp2_rev)

42

In [128]:
# converting integer to percentage
gross_profit_margin_percentage2= []
for i in pp2_rev:
    gross_profit_margin_percentage2.append("{:}%".format(i))
len(gross_profit_margin_percentage2)

42

These are the variables needed to create the columns for the fourth dataframe; new_name3, new_systems3, new_total_gross3, new_worldwide_gross3, new_profit3, new_currency_profit3, gross_profit_margin_percentage3

In [129]:
new_name3=[]
name3 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            name3.append(all_Comedy_info1.Name[i])
for i,x in enumerate(name3):
    new_name3.append( x)
len(new_name3)

42

In [130]:
new_total_gross3 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            new_total_gross3.append(all_Comedy_info1.Total_gross[i])
len(new_total_gross3)

42

In [131]:
new_worldwide_gross3= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            new_worldwide_gross3.append(all_Comedy_info1.Worlwide_gross[i])
len(new_worldwide_gross3)

42

In [132]:
new_currency_profit3 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            new_currency_profit3.append(all_Comedy_info1['Profit$'][i])
len(new_currency_profit3)

42

In [133]:
new_profit3 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            new_profit3.append(all_Comedy_info1.Profit[i])
len(new_profit3)

42

In [134]:
new_systems3 = []
for i in list(range(0,42)):
    new_systems3.append('PG-13')

In [135]:
p3_rev = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='PG-13':
            p3_rev.append(all_Comedy_info1.Profit[i]/all_Comedy_info1.Total_gross[i]*100)

len(p3_rev)

42

In [136]:
# turning float of percentage of profit into int
pp3_rev= []
for i in p3_rev:
    i = int(i)
    pp3_rev.append(round(i,0))
len(pp3_rev)

42

In [137]:
# converting integer to percentage
gross_profit_margin_percentage3= []
for i in pp3_rev:
    gross_profit_margin_percentage3.append("{:}%".format(i))
len(gross_profit_margin_percentage3)

42

These are the variables needed to create the columns for the fivth dataframe; new_name4, new_systems4, new_total_gross4, new_worldwide_gross4, new_profit4, new_currency_profit4, gross_profit_margin_percentage4

In [138]:
new_name4=[]
name4= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            name4.append(all_Comedy_info1.Name[i])
for i,x in enumerate(name4):
    new_name4.append(x)
new_name4
len(new_name4)

42

In [139]:
new_total_gross4 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            new_total_gross4.append(all_Comedy_info1.Total_gross[i])
len(new_total_gross4)

42

In [140]:
new_worldwide_gross4= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            new_worldwide_gross4.append(all_Comedy_info1.Worlwide_gross[i])
len(new_worldwide_gross4)

42

In [141]:
new_currency_profit4 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            new_currency_profit4.append(all_Comedy_info1['Profit$'][i])
len(new_currency_profit4)

42

In [142]:
new_profit4= []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            new_profit4.append(all_Comedy_info1.Profit[i])
len(new_profit4)

42

In [143]:
new_systems4 = []
for i in list(range(0,42)):
    new_systems4.append('NR')

In [144]:
p4_rev = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
        if x =='NR':
            p4_rev.append(round(all_Comedy_info1.Profit[i]/all_Comedy_info1.Total_gross[i]*100,
                                0))
len(p4_rev)

42

In [145]:
# turning float of percentage of profit into int
pp4_rev= []
for i in p4_rev:
    i = int(i)
    pp4_rev.append(round(i,2))
len(pp4_rev)

42

In [146]:
# converting integer to percentage
gross_profit_margin_percent4= []
for i in pp4_rev:
    gross_profit_margin_percent4.append("{:}%".format(i))
len(gross_profit_margin_percent4)

42

In [147]:
# list for type colunm
l = []
for i in list(range(0,42)):
    l.append('Revenue')
for i in list(range(0,42)):
    l.append('Profit')
len(l)

84

In [148]:
# list for type column for dataframe2 due to -inf
l2 = []
for i in list(range(0,41)):
    l2.append('Revenue')
for i in list(range(0,41)):
    l2.append('Profit')
len(l2)

82

In [149]:
df5 = pd.DataFrame({'Name':new_name4*2,'Yield':new_total_gross4+new_profit4,'Type Yield':new_worldwide_gross4+new_currency_profit4,
                    'System Ratings':new_systems4*2,'Gross Profit Margin %':gross_profit_margin_percent4*2,'Type':l})

df4 = pd.DataFrame({'Name':new_name3*2,'Yield':new_total_gross3+new_profit3,'Type Yield':new_worldwide_gross3+new_currency_profit3,
                  'System Ratings':new_systems3*2,'Gross Profit Margin %':gross_profit_margin_percentage3*2,'Type':l})

df3 = pd.DataFrame({'Name':new_name2*2,'Yield':new_total_gross4+new_profit2,'Type Yield':new_worldwide_gross2+new_currency_profit2,
                    'System Ratings':new_systems2*2,'Gross Profit Margin %':gross_profit_margin_percentage2*2,'Type':l})

df2 = pd.DataFrame({'Name':new_name1*2,'Yield':new_total_gross1+new_profit1,'Type Yield':new_worldwide_gross1+new_currency_profit1,
                  'System Ratings':new_systems1*2,'Gross Profit Margin %':gross_profit_margin_percent1*2,'Type':l2})

df1 = pd.DataFrame({'Name':new_name*2,'Yield':new_total_gross+new_profit,'Type Yield':new_worldwide_gross+new_currency_profit,
                    'System Ratings':new_systems*2,'Gross Profit Margin %':gross_profit_margin_percentage*2,'Type':l})

In [150]:
df1

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Tangled,586477240,"$586,477,240",R,55%,Revenue
1,Transformers: The Last Knight,602893340,"$602,893,340",R,64%,Revenue
2,Incredibles 2,1242520711,"$1,242,520,711",R,83%,Revenue
3,Rogue One: A Star Wars Story,1049102856,"$1,049,102,856",R,80%,Revenue
4,Spider-Man 2,795110670,"$795,110,670",R,74%,Revenue
...,...,...,...,...,...,...
79,Ben-Hur,-3330352,"$-3,330,352",R,-3%,Profit
80,Cutthroat Island,-73482678,"$-73,482,678",R,-396%,Profit
81,The Haunted Mansion,65750628,"$65,750,628",R,42%,Profit
82,Happy Feet,300000317,"$300,000,317",R,77%,Profit
83,Sherlock Gnomes,28527651,"$28,527,651",R,32%,Profit

In [151]:
df2

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Jurassic World,1648854864,"$1,648,854,864",PG,86%,Revenue
1,The Golden Compass,367262558,"$367,262,558",PG,44%,Revenue
2,Cars 2,560155383,"$560,155,383",PG,64%,Revenue
3,The Great Gatsby,351040419,"$351,040,419",PG,45%,Revenue
4,Edge of Tomorrow,370541256,"$370,541,256",PG,51%,Revenue
...,...,...,...,...,...,...
77,Goosebumps,100905324,"$100,905,324",PG,63%,Profit
78,The Internship,35672764,"$35,672,764",PG,38%,Profit
79,The Pursuit of Happyness,252311093,"$252,311,093",PG,82%,Profit
80,The Equalizer,137903624,"$137,903,624",PG,71%,Profit
81,Chain Reaction,5209334,"$5,209,334",PG,8%,Profit

In [152]:
df3

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Where the Wild Things Are,313477717,"$99,123,656",G,0%,Revenue
1,A Good Day to Die Hard,322459006,"$304,249,198",G,69%,Revenue
2,The Peacemaker,747862775,"$62,967,368",G,20%,Revenue
3,Pinocchio,1123790543,"$31,681,811",G,-42%,Revenue
4,Chicken Run,335802233,"$224,834,564",G,79%,Revenue
...,...,...,...,...,...,...
79,102 Dalmatians,150550424,"$150,550,424",G,53%,Profit
80,Hannah Montana: The Movie,110545279,"$110,545,279",G,71%,Profit
81,The Land Before Time,160775761,"$160,775,761",G,85%,Profit
82,My Fair Lady (1964),457992835,"$457,992,835",G,76%,Profit
83,Funny Girl,378315879,"$378,315,879",G,85%,Profit

In [153]:
df4

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Avengers: Infinity War,2048134200,"$2,048,134,200",PG-13,85%,Revenue
1,John Carter,282778100,"$282,778,100",PG-13,2%,Revenue
2,Alice in Wonderland,1025491110,"$1,025,491,110",PG-13,80%,Revenue
3,Blade Runner 2049,259357408,"$259,357,408",PG-13,28%,Revenue
4,Guardians of the Galaxy,770867516,"$770,867,516",PG-13,77%,Revenue
...,...,...,...,...,...,...
79,2 Guns,71493015,"$71,493,015",PG-13,53%,Profit
80,London Has Fallen,135194085,"$135,194,085",PG-13,69%,Profit
81,Jack Reacher: Never Go Back,99946489,"$99,946,489",PG-13,62%,Profit
82,The Jackal,99356941,"$99,356,941",PG-13,62%,Profit
83,The Legend of Bagger Vance,-20764514,"$-20,764,514",PG-13,-52%,Profit

In [154]:
df5

,Name,Yield,Type Yield,System Ratings,Gross Profit Margin %,Type
0,Battleship,313477717,"$313,477,717",NR,30%,Revenue
1,Robin Hood,322459006,"$322,459,006",NR,35%,Revenue
2,X-Men: Days of Future Past,747862775,"$747,862,775",NR,73%,Revenue
3,Transformers: Dark of the Moon,1123790543,"$1,123,790,543",NR,83%,Revenue
4,Star Trek Beyond,335802233,"$335,802,233",NR,45%,Revenue
...,...,...,...,...,...,...
79,Out of Time,5489826,"$5,489,826",NR,10%,Profit
80,The Adventures of Ford Fairlane,-28576611,"$-28,576,611",NR,-140%,Profit
81,America's Sweethearts,114648493,"$114,648,493",NR,71%,Profit
82,The River Wild,49215000,"$49,215,000",NR,52%,Profit
83,Last Holiday,-1656753,"$-1,656,753",NR,-4%,Profit

In [155]:
# this is the first graph: this is the System R rating category
a=alt.Chart(df1).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis = alt.Axis(grid=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem PG rating category
b=alt.Chart(df2).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
        axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the second graph: this is the Sytem G rating category
c=alt.Chart(df3).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       scale=alt.Scale(zero=False),
       axis=None# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the third graph: this is the Sytem PG-13 rating category
d=alt.Chart(df4).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,#take away the grid
       scale=alt.Scale(zero=False)
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

# this is the fourth graph: this is the Sytem NR rating category
e=alt.Chart(df5).mark_point(size=80).encode(
    # x-axis section 
    alt.X(
      'Yield:Q',# this shows the amount of the type of data yield in integer 
       title='Revenue/Profit',# the title of the x-axis
       axis=None,
       scale=alt.Scale(zero=False),# takes away the grid
   ),
    #y-axis section  
    alt.Y(
       'Name', # shows the name of the movie
       title='R System Ratings', # the title of the y-axis
       axis=alt.Axis(grid=True)), # only shows the y-axis grid
    color=alt.Color('Type:N'),# puts the color based on two catrory, profit and revenue
    # tooltip allows grag to be intercative it shows the name, profit, revenue, gross profit nargin % and system rating
    tooltip = ['Type','Name','Type Yield','Gross Profit Margin %','System Ratings'],
).properties(
     width=500, # the size of the graph
     height=500)

f= alt.vconcat(b,c,d,e).configure_view(strokeOpacity=0).configure_axisLeft(labelColor='#2ECC71')
f&a # combines the graphs together

alt.VConcatChart(...)

# Blueprint: Budget and Revenue of Movies

This js the blueprint for creating the third visualization Budget and Revenue of Movies, altair will be used to create this graph. 

__Blueprint:__
   - The format of the dataframe needed for this graph is straight forward, based on the ideology of the persception of the chart, these are the colunms needed for thr dataframe;
        - Name,
        - System Ratings,
        - Budget,
        - Revenue,
        - Budget of Movie,
        - Renenue of Movies
   
  
  - The style of this chart is a Selection Histogram which is found in the Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis is the Revenue and the y-axis is the Budget, this set up projects wether a linear regression, meaning if the hypothesis which is, the higher the budget the higher the revenue is proven right projecting a linear regression.
  
  - The graph has an attachted histogram showing the amount of items in each category within the selection. In order to make a selection create a box by dragging the mouse. When the mouse hovers the pionts it projects the name, system rating, budget of the movies and the reevenue of the movies.

In [156]:
# variable for the range colunm neede for the dataframe below
listt = range(0,210)

In [157]:
# data frame created for the next three graphs
dataframe2 = pd.DataFrame({"Name":all_Comedy_info1.Name,"System Rating":all_Comedy_info1.System_ratings,"Budget":all_Comedy_info1.Buget,'Range':listt,
                           "Revenue":all_Comedy_info1.Total_gross,'Budget of Movie':all_Comedy_info1.Product_budget,'Revenue of Movie':all_Comedy_info1.Worlwide_gross})

In [158]:
#scatter graph
brush = alt.selection(type='interval')# to reate the selction box
points=alt.Chart(dataframe2).mark_circle(size=60).encode(
    x="Revenue:Q",# x-axis
    y='Budget',# y-axis
    color='System Rating', # color based on system rating put into category
    # interactive when the pionts are hovered the name, budget, revenue and system rating shows up
    tooltip=['Name','System Rating','Budget of Movie','Revenue of Movie']
).properties(height=400,width=500).add_selection(brush)# the size of graph

# histogram chart
bars=alt.Chart(dataframe2).mark_bar().encode(
        y='System Rating:N',# y-axis
        color='System Rating:N',# color put into groups based on system ratings
        x='count(Revenue):Q').transform_filter(brush)# x-axis
points&bars# graphs combined together

alt.VConcatChart(...)

# Blueprint: Revenue of Movies

This is the blueprint for creating the fourth visualization Revenue of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The x-axis shows the revenue of each movie and the y-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the revenue of the movie.

In [159]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
points1=base.mark_point(size=60).encode(
       y=alt.Y('Range',title='',axis=None),# y-axis
       x = alt.X('Revenue:Q',title='Revenue'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
x_ticks=base.mark_tick().encode(
    alt.X('Revenue',axis=tick_axis),# x-axis
    alt.Y('System Rating',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
points1&x_ticks# the two graphs combined

alt.VConcatChart(...)

# Blueprint: Budget of Movies

This is the blueprint for creating the fivth visualization Budget of Movies, Altair will be used to create this graph.

__Blueprint:__
   - The format of the dataframe needed for this graph is the same as the previous datarame that was created.
   
   - The style of this graph is the Dot Dash Plot which is found in Altairs Gallery. It is a scatter plot with a x-axis and a y-axis. The y-axis shows the Budget of each movie and the x-axis is not visible. The Dot Dash plots are scatter plot with trick marks protraying the minute seperation of the amount of items in each category within the selection. To create a selection create a box by dragging the mouse. When the mouse hovers over the pionts it projects the name, system rating and the budget of the movie.

In [160]:
brush= alt.selection(type='interval')# creates selective box
base = alt.Chart(dataframe2).add_selection(brush)

# scatter plot
pionts1=base.mark_point(size=60).encode(
       x=alt.X('Range',title='',axis=None),# y-axis
       y = alt.Y('Budget:Q',title='Budget'),# x-axis
       # interactive shows name,system rating and revenue of movies selected
       tooltip=['Name','System Rating','Revenue of Movie'],
       # color of selective box
       color=alt.condition(brush,'System Rating',alt.value('grey'))).properties(height=400,width=500)

tick_axis=alt.Axis(labels=False,domain=False,ticks=False)# cretes dot dash plot

# dot dash plot
y_ticks=base.mark_tick().encode(
    alt.X('System Rating',axis=tick_axis),# x-axis
    alt.Y('Budget',axis=tick_axis,title=''),# y-axis
    # interactive shows name, system rating and revenue of movies selected
    tooltip = ['Name','System Rating','Revenue of Movie'],
    # color of selective box
    color=alt.condition(brush,'System Rating',alt.value('lightgrey')))
y_ticks|pionts1# the two graphs combined

alt.HConcatChart(...)

# Blueprint: Movies that made Profit

This is the blueprint for creating the seventh visualization, Movies that made Profit. Highcharts will be used to create this graph. 

__Blueprint:__
- The graph used for this visualzation is Highcharts Lollipop series which is found in the Highcharts Demos. Lollipop charts are variants of column charts, with a circle marker for the data value and a line extending to the axis.The first approach to this chart is by understanding the format of the script. This graph has two types of code HTML and Javascript. JupyterLab has magic commands that supports HTML and Javascript, it uses the '%' syntax element for magics.

   Before the HTML and Javascript are scripted a dataframe needs to be made to extract all the movies that made profit in the Comedy genre. The two variable needed from the parent dataframe '_all_Comedy_info1_' is the name and profit made in integer. 
   
   - __HTML Section:__
      
      To start off the magic command '%%HTML' should be scripted first in the cell. The main scripted         lines that will be used to create highchart graph through out this project are;
          <script src="https://code.highcharts.com/highcharts.js"></script>
          <script src="https://code.highcharts.com/highcharts-more.js"></script>
          <script src="https://code.highcharts.com/modules/exporting.js"></script>
          <script src="https://code.highcharts.com/modules/accessibility.js"></script>
     For this particular graph this script will be used to get lollipop affect;
          <script src="https://code.highcharts.com/modules/dumbbell.js"></script>
          <script src="https://code.highcharts.com/modules/lollipop.js"></script>
     To close off the HTML script, this script is used and to indetify and differenate this claa from        other, the div id has to be named, and if thei graph is being used more than once the div id needs      to have a different name at all times or it will not work;
                       <figure class="highcharts-figure">
                       <div id="r1"></div> 
                       <p class= "highcharts-description">
                       </p>
                       </figure>
                       
   - __Javascript Section:__
   
      To start off, the magic command '%%JS' is used to script javascript in the jupyterlab cell. The         javascript section will have comments and explaination, but for futher information go to               Highcharts Demos.The normal layout is horizontal but for this graph its going to be vertical. The       main javascript used to create this lollipop graph is;
                         name: ' The Sound of Music ' 
                         low: 2303109231
      The name variable is where the name of the movies is put and the low variable is the amount of         profit made in integer is put.

In [161]:
dataframe = pd.DataFrame({"Name":all_Comedy_info1.Name,"Profit":all_Comedy_info1.Profit})

In [162]:
# get the largest movies in profit to the smallest for lollipop graph
new1 = []
for i,x in enumerate(dataframe.Profit):
    new1.append((i,x))
new1.sort(reverse=True,key=lambda x:x[1])
new1

[(0, 1748134200),
 (5, 1433854864),
 (8, 1042520711),
 (15, 928790543),
 (140, 874496193),
 (9, 849102856),
 (137, 842429370),
 (96, 840699645),
 (11, 825491110),
 (194, 825300000),
 (202, 817460782),
 (141, 769701857),
 (65, 737628605),
 (22, 622402853),
 (25, 609456552),
 (29, 600867516),
 (10, 595110670),
 (34, 591244673),
 (38, 588576929),
 (148, 576899282),
 (12, 547862775),
 (100, 497790539),
 (50, 493144660),
 (208, 457992835),
 (66, 444757719),
 (21, 437234314),
 (61, 429588516),
 (45, 414600000),
 (4, 385893340),
 (209, 378315879),
 (97, 377986200),
 (138, 377986200),
 (18, 376072059),
 (121, 373483213),
 (56, 368214888),
 (13, 360155383),
 (191, 356864079),
 (23, 352508025),
 (78, 349948323),
 (68, 346258539),
 (42, 340875846),
 (189, 334428135),
 (2, 326477240),
 (179, 318300000),
 (43, 303191819),
 (108, 300000317),
 (110, 293505812),
 (144, 293505812),
 (55, 281875536),
 (122, 281500000),
 (143, 278064265),
 (69, 272288147),
 (118, 267769200),
 (186, 267695435),
 (31, 263058296),
 (51, 255997896),
 (132, 252311093),
 (40, 252231063),
 (73, 243629585),
 (77, 236529144),
 (47, 235740705),
 (33, 232976036),
 (30, 231021746),
 (127, 230701374),
 (46, 230569776),
 (109, 230268353),
 (54, 228648063),
 (82, 225500000),
 (39, 224825760),
 (150, 222656605),
 (60, 222141403),
 (187, 221457746),
 (70, 220780051),
 (41, 220098020),
 (98, 212249198),
 (178, 212000000),
 (83, 211979256),
 (79, 210650574),
 (184, 198495971),
 (26, 192541256),
 (52, 191887208),
 (196, 184943740),
 (172, 179834564),
 (136, 178731369),
 (149, 174856037),
 (188, 169907151),
 (36, 169631958),
 (62, 167916633),
 (74, 165997378),
 (14, 165491792),
 (175, 162600000),
 (7, 162262558),
 (200, 162150197),
 (44, 161900902),
 (16, 161040419),
 (207, 160775761),
 (181, 157184237),
 (180, 155486600),
 (103, 154041804),
 (89, 151091610),
 (19, 150802233),
 (205, 150550424),
 (197, 141929190),
 (64, 141751370),
 (133, 137903624),
 (80, 136827677),
 (37, 135930148),
 (156, 135194085),
 (32, 130150546),
 (75, 129343008),
 (91, 128050874),
 (198, 126965572),
 (17, 125709697),
 (53, 121499665),
 (165, 121269535),
 (162, 119463257),
 (169, 114648493),
 (81, 112956024),
 (6, 112459006),
 (85, 112026975),
 (206, 110545279),
 (49, 110328374),
 (135, 109782709),
 (87, 109461378),
 (101, 101145256),
 (130, 100905324),
 (145, 100708462),
 (157, 99946489),
 (158, 99356941),
 (153, 98527824),
 (3, 93477717),
 (27, 89246220),
 (57, 86856088),
 (123, 86856088),
 (115, 77888063),
 (24, 76585882),
 (102, 75900000),
 (20, 74357408),
 (142, 72753837),
 (155, 71493015),
 (107, 71487563),
 (93, 70720921),
 (173, 69296573),
 (116, 67080413),
 (104, 65750628),
 (128, 64715863),
 (90, 64691085),
 (124, 63468793),
 (48, 59646680),
 (114, 52298489),
 (67, 50149302),
 (170, 49215000),
 (166, 46469187),
 (182, 43327234),
 (129, 41134059),
 (131, 35672764),
 (151, 33735965),
 (76, 30401882),
 (160, 28527651),
 (146, 26515310),
 (204, 19871429),
 (177, 19333034),
 (183, 18100248),
 (203, 17083611),
 (190, 14536290),
 (120, 14009602),
 (35, 13038324),
 (111, 12967368),
 (174, 12293743),
 (176, 10662822),
 (92, 9907746),
 (201, 9684950),
 (125, 9575290),
 (152, 9224232),
 (1, 7778100),
 (117, 6787530),
 (167, 5489826),
 (134, 5209334),
 (192, 4474661),
 (185, 2908803),
 (161, 1431365),
 (84, -876344),
 (171, -1656753),
 (105, -2579224),
 (95, -3330352),
 (86, -3778029),
 (112, -13318189),
 (193, -17324090),
 (113, -18058441),
 (199, -19790069),
 (159, -20764514),
 (28, -23283185),
 (154, -25982016),
 (63, -26605538),
 (164, -26768556),
 (168, -28576611),
 (94, -29300000),
 (71, -33517539),
 (72, -37995841),
 (126, -38329080),
 (195, -38600000),
 (88, -40081578),
 (163, -45478542),
 (147, -50274337),
 (59, -63301101),
 (58, -63357202),
 (139, -68088638),
 (106, -69533984),
 (99, -73482678),
 (119, -75000000)]

In [163]:
# getting the name of movies for the lollipop graph
new2 = []
for i in new1:
    new2.append(dataframe.Name[i[0]])
for i,x in enumerate(new2):
    print(i,x)

0 Avengers: Infinity War
1 Jurassic World
2 Incredibles 2
3 Transformers: Dark of the Moon
4 Jumanji: Welcome to the Jungle
5 Rogue One: A Star Wars Story
6 Finding Nemo
7 The Lord of the Rings: The Two Towers
8 Alice in Wonderland
9 101 Dalmatians
10 Mary Poppins
11 Ice Age: Dawn of the Dinosaurs
12 Venom
13 Fantastic Beasts and Where to Find Them
14 Mission: ImpossibleâFallout
15 Guardians of the Galaxy
16 Spider-Man 2
17 Shrek Forever After
18 The Matrix Reloaded
19 Ice Age: The Meltdown
20 X-Men: Days of Future Past
21 Men in Black
22 Ant-Man and the Wasp
23 My Fair Lady (1964)
24 Monsters, Inc.
25 Aladdin
26 Mission: Impossible 2
27 Armageddon
28 Transformers: The Last Knight
29 Funny Girl
30 Rise of the Planet of the Apes
31 Rise of the Planet of the Apes
32 Kong: Skull Island
33 Alvin and the Chipmunks: The Squeakquel
34 Clash of the Titans
35 Cars 2
36 Babe
37 WALL-E
38 Django Unchained
39 San Andreas
40 Angels & Demons
41 The Love Bug
42 Tangled
43 A Bug's Life
44 Tarzan
45 Happy Feet
46 Hotel Transylvania
47 Hotel Transylvania
48 X-Men 2
49 Who Framed Roger Rabbit?
50 Fast & Furious
51 Live Free or Die Hard
52 Now You See Me
53 Alvin and the Chipmunks: Chipwrecked
54 Terminator 3: Rise of the Machines
55 Home
56 The Pursuit of Happyness
57 Night at the Museum: Battle of the Smithsonian
58 I, Robot
59 Batman Forever
60 G.I. Joe: Retaliation
61 Alita: Battle Angel
62 Snow White and the Huntsman
63 The Green Mile
64 Captain America: The First Avenger
65 Air Force One
66 Dinosaur
67 The Hunchback of Notre Dame
68 X-Men Origins: Wolverine
69 Doctor Dolittle
70 How the Grinch Stole Christmas
71 Herbie Rides Again
72 300: Rise of an Empire
73 Mad Max: Fury Road
74 A Good Day to Die Hard
75 Horton Hears a Who!
76 The Expendables 2
77 Little Fockers
78 The Absent-Minded Professor
79 Edge of Tomorrow
80 Megamind
81 Freaky Friday
82 Chicken Run
83 The Tourist
84 Unbreakable
85 Son of Flubber
86 The Curious Case of Benjamin Button
87 Oblivion
88 The Princess and the Frog
89 Terminator Salvation
90 Wallace & Gromit: The Curse of the Were-Rabbit
91 The Golden Compass
92 The Sword in the Stone
93 Rise of the Guardians
94 The Great Gatsby
95 The Land Before Time
96 The Muppets
97 The Apple Dumpling Gang
98 Pixels
99 The Peanuts Movie
100 Star Trek Beyond
101 102 Dalmatians
102 The Return of the Pink Panthe
103 Knight and Day
104 The Equalizer
105 Cloudy with a Chance of Meatballs
106 Pacific Rim: Uprising
107 London Has Fallen
108 Van Helsing
109 Gone in 60 Seconds
110 Percy Jackson & the Olympians: The Lightning Thief
111 Yogi Bear
112 Disneyâs A Christmas Carol
113 After Earth
114 Mr. Deeds
115 George Of The Jungle
116 America's Sweethearts
117 Lemony Snicket's A Series of Unfortunate Events
118 Robin Hood
119 End of Days
120 Hannah Montana: The Movie
121 Teenage Mutant Ninja Turtles: Out of the Shadows
122 Public Enemies
123 The Expendables 3
124 Tropic Thunder
125 Goosebumps
126 I Now Pronounce You Chuck and Larry
127 Jack Reacher: Never Go Back
128 The Jackal
129 Unbroken
130 Battleship
131 Waterworld
132 Total Recall
133 Total Recall
134 Hellboy II: The Golden Army
135 Rush Hour 3
136 Contact
137 Blade Runner 2049
138 The Interpreter
139 2 Guns
140 The Predator
141 Unstoppable
142 The Emperor's New Groove
143 Swordfish
144 The Haunted Mansion
145 The Family Man
146 Black Hawk Down
147 Step Brothers
148 The BFG
149 Last Action Hero
150 The Huntsman: Winterâs War
151 The River Wild
152 Christmas with the Kranks
153 The Odd Couple
154 Joy
155 The Internship
156 Escape Plan
157 A Wrinkle in Time
158 Sherlock Gnomes
159 Spirit: Stallion of the Cimarron
160 Winnie the Pooh
161 Meet the Robinsons
162 A Shaun the Sheep Movie: Farmageddon
163 Pinocchio
164 A Night at the Opera
165 The Kingdom
166 Cowboys and Aliens
167 The Peacemaker
168 Ramona and Beezus
169 Africa Screams
170 The Campaign
171 Willy Wonka & the Chocolate Factory
172 I, Frankenstein
173 Money Train
174 John Carter
175 Oceans
176 Out of Time
177 Chain Reaction
178 Mr. Magorium's Wonder Emporium
179 Bringing Up Baby
180 The Flintstones in Viva Rock Vegas
181 Where the Wild Things Are
182 Last Holiday
183 Bicentennial Man
184 Ben-Hur
185 The Stepford Wives
186 Pinocchio
187 The Court Jester
188 102 Dalmatians
189 The Swan Princess
190 The Legend of Bagger Vance
191 47 Ronin
192 Primary Colors
193 Speed Racer
194 Thunderbirds
195 The Adventures of Ford Fairlane
196 The Road to El Dorado
197 Home on the Range
198 Around the World in 80 Days
199 Oliver Twist
200 Garfield: The Movie
201 Son of the Mask
202 All the King's Men
203 Battlefield Earth: A Saga of the Year 3000
204 The 13th Warrior
205 Monster Trucks
206 The Alamo
207 The Nutcracker in 3D
208 Cutthroat Island
209 355

Using a for loop to put the name and profit in html code which will be copied and pasted in the cell below.

In [164]:
for x in range(len(new2)):
    print('        }, { \n           name:',"'",new2[x],"'",','+'\n           low:',new1[x][1])

        }, {
           name: ' Avengers: Infinity War ' ,
           low: 1748134200
        }, {
           name: ' Jurassic World ' ,
           low: 1433854864
        }, {
           name: ' Incredibles 2 ' ,
           low: 1042520711
        }, {
           name: ' Transformers: Dark of the Moon ' ,
           low: 928790543
        }, {
           name: ' Jumanji: Welcome to the Jungle ' ,
           low: 874496193
        }, {
           name: ' Rogue One: A Star Wars Story ' ,
           low: 849102856
        }, {
           name: ' Finding Nemo ' ,
           low: 842429370
        }, {
           name: ' The Lord of the Rings: The Two Towers ' ,
           low: 840699645
        }, {
           name: ' Alice in Wonderland ' ,
           low: 825491110
        }, {
           name: ' 101 Dalmatians ' ,
           low: 825300000
        }, {
           name: ' Mary Poppins ' ,
           low: 817460782
        }, {
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, {
           name: ' Venom ' ,
           low: 737628605
        }, {
           name: ' Fantastic Beasts and Where to Find Them ' ,
           low: 622402853
        }, {
           name: ' Mission: ImpossibleâFallout ' ,
           low: 609456552
        }, {
           name: ' Guardians of the Galaxy ' ,
           low: 600867516
        }, {
           name: ' Spider-Man 2 ' ,
           low: 595110670
        }, {
           name: ' Shrek Forever After ' ,
           low: 591244673
        }, {
           name: ' The Matrix Reloaded ' ,
           low: 588576929
        }, {
           name: ' Ice Age: The Meltdown ' ,
           low: 576899282
        }, {
           name: ' X-Men: Days of Future Past ' ,
           low: 547862775
        }, {
           name: ' Men in Black ' ,
           low: 497790539
        }, {
           name: ' Ant-Man and the Wasp ' ,
           low: 493144660
        }, {
           name: ' My Fair Lady (1964) ' ,
           low: 457992835
        }, {
           name: ' Monsters, Inc. ' ,
           low: 444757719
        }, {
           name: ' Aladdin ' ,
           low: 437234314
        }, {
           name: ' Mission: Impossible 2 ' ,
           low: 429588516
        }, {
           name: ' Armageddon ' ,
           low: 414600000
        }, {
           name: ' Transformers: The Last Knight ' ,
           low: 385893340
        }, {
           name: ' Funny Girl ' ,
           low: 378315879
        }, {
           name: ' Rise of the Planet of the Apes ' ,
           low: 377986200
        }, {
           name: ' Rise of the Planet of the Apes ' ,
           low: 377986200
        }, {
           name: ' Kong: Skull Island ' ,
           low: 376072059
        }, {
           name: ' Alvin and the Chipmunks: The Squeakquel ' ,
           low: 373483213
        }, {
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, {
           name: ' Cars 2 ' ,
           low: 360155383
        }, {
           name: ' Babe ' ,
           low: 356864079
        }, {
           name: ' WALL-E ' ,
           low: 352508025
        }, {
           name: ' Django Unchained ' ,
           low: 349948323
        }, {
           name: ' San Andreas ' ,
           low: 346258539
        }, {
           name: ' Angels & Demons ' ,
           low: 340875846
        }, {
           name: ' The Love Bug ' ,
           low: 334428135
        }, {
           name: ' Tangled ' ,
           low: 326477240
        }, {
           name: ' A Bug's Life ' ,
           low: 318300000
        }, {
           name: ' Tarzan ' ,
           low: 303191819
        }, {
           name: ' Happy Feet ' ,
           low: 300000317
        }, {
           name: ' Hotel Transylvania ' ,
           low: 293505812
        }, {
           name: ' Hotel Transylvania ' ,
           low: 293505812
        }, {
           name: ' X-Men 2 ' ,
           low: 281875536
        }, {
           name: ' Who Framed Roger Rabbit? ' ,
           low: 281500000
        }, {
           name: ' Fast & Furious ' ,
           low: 278064265
        }, {
           name: ' Live Free or Die Hard ' ,
           low: 272288147
        }, {
           name: ' Now You See Me ' ,
           low: 267769200
        }, {
           name: ' Alvin and the Chipmunks: Chipwrecked ' ,
           low: 267695435
        }, {
           name: ' Terminator 3: Rise of the Machines ' ,
           low: 263058296
        }, {
           name: ' Home ' ,
           low: 255997896
        }, {
           name: ' The Pursuit of Happyness ' ,
           low: 252311093
        }, {
           name: ' Night at the Museum: Battle of the Smithsonian ' ,
           low: 252231063
        }, {
           name: ' I, Robot ' ,
           low: 243629585
        }, {
           name: ' Batman Forever ' ,
           low: 236529144
        }, {
           name: ' G.I. Joe: Retaliation ' ,
           low: 235740705
        }, {
           name: ' Alita: Battle Angel ' ,
           low: 232976036
        }, {
           name: ' Snow White and the Huntsman ' ,
           low: 231021746
        }, {
           name: ' The Green Mile ' ,
           low: 230701374
        }, {
           name: ' Captain America: The First Avenger ' ,
           low: 230569776
        }, {
           name: ' Air Force One ' ,
           low: 230268353
        }, {
           name: ' Dinosaur ' ,
           low: 228648063
        }, {
           name: ' The Hunchback of Notre Dame ' ,
           low: 225500000
        }, {
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, {
           name: ' Doctor Dolittle ' ,
           low: 222656605
        }, {
           name: ' How the Grinch Stole Christmas ' ,
           low: 222141403
        }, {
           name: ' Herbie Rides Again ' ,
           low: 221457746
        }, {
           name: ' 300: Rise of an Empire ' ,
           low: 220780051
        }, {
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, {
           name: ' A Good Day to Die Hard ' ,
           low: 212249198
        }, {
           name: ' Horton Hears a Who! ' ,
           low: 212000000
        }, {
           name: ' The Expendables 2 ' ,
           low: 211979256
        }, {
           name: ' Little Fockers ' ,
           low: 210650574
        }, {
           name: ' The Absent-Minded Professor ' ,
           low: 198495971
        }, {
           name: ' Edge of Tomorrow ' ,
           low: 192541256
        }, {
           name: ' Megamind ' ,
           low: 191887208
        }, {
           name: ' Freaky Friday ' ,
           low: 184943740
        }, {
           name: ' Chicken Run ' ,
           low: 179834564
        }, {
           name: ' The Tourist ' ,
           low: 178731369
        }, {
           name: ' Unbreakable ' ,
           low: 174856037
        }, {
           name: ' Son of Flubber ' ,
           low: 169907151
        }, {
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, {
           name: ' Oblivion ' ,
           low: 167916633
        }, {
           name: ' The Princess and the Frog ' ,
           low: 165997378
        }, {
           name: ' Terminator Salvation ' ,
           low: 165491792
        }, {
           name: ' Wallace & Gromit: The Curse of the Were-Rabbit ' ,
           low: 162600000
        }, {
           name: ' The Golden Compass ' ,
           low: 162262558
        }, {
           name: ' The Sword in the Stone ' ,
           low: 162150197
        }, {
           name: ' Rise of the Guardians ' ,
           low: 161900902
        }, {
           name: ' The Great Gatsby ' ,
           low: 161040419
        }, {
           name: ' The Land Before Time ' ,
           low: 160775761
        }, {
           name: ' The Muppets ' ,
           low: 157184237
        }, {
           name: ' The Apple Dumpling Gang ' ,
           low: 155486600
        }, {
           name: ' Pixels ' ,
           low: 154041804
        }, {
           name: ' The Peanuts Movie ' ,
           low: 151091610
        }, {
           name: ' Star Trek Beyond ' ,
           low: 150802233
        }, {
           name: ' 102 Dalmatians ' ,
           low: 150550424
        }, {
           name: ' The Return of the Pink Panthe ' ,
           low: 141929190
        }, {
           name: ' Knight and Day ' ,
           low: 141751370
        }, {
           name: ' The Equalizer ' ,
           low: 137903624
        }, {
           name: ' Cloudy with a Chance of Meatballs ' ,
           low: 136827677
        }, {
           name: ' Pacific Rim: Uprising ' ,
           low: 135930148
        }, {
           name: ' London Has Fallen ' ,
           low: 135194085
        }, {
           name: ' Van Helsing ' ,
           low: 130150546
        }, {
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, {
           name: ' Percy Jackson & the Olympians: The Lightning Thief ' ,
           low: 128050874
        }, {
           name: ' Yogi Bear ' ,
           low: 126965572
        }, {
           name: ' Disneyâs A Christmas Carol ' ,
           low: 125709697
        }, {
           name: ' After Earth ' ,
           low: 121499665
        }, {
           name: ' Mr. Deeds ' ,
           low: 121269535
        }, {
           name: ' George Of The Jungle ' ,
           low: 119463257
        }, {
           name: ' America's Sweethearts ' ,
           low: 114648493
        }, {
           name: ' Lemony Snicket's A Series of Unfortunate Events ' ,
           low: 112956024
        }, {
           name: ' Robin Hood ' ,
           low: 112459006
        }, {
           name: ' End of Days ' ,
           low: 112026975
        }, {
           name: ' Hannah Montana: The Movie ' ,
           low: 110545279
        }, {
           name: ' Teenage Mutant Ninja Turtles: Out of the Shadows ' ,
           low: 110328374
        }, {
           name: ' Public Enemies ' ,
           low: 109782709
        }, {
           name: ' The Expendables 3 ' ,
           low: 109461378
        }, {
           name: ' Tropic Thunder ' ,
           low: 101145256
        }, {
           name: ' Goosebumps ' ,
           low: 100905324
        }, {
           name: ' I Now Pronounce You Chuck and Larry ' ,
           low: 100708462
        }, {
           name: ' Jack Reacher: Never Go Back ' ,
           low: 99946489
        }, {
           name: ' The Jackal ' ,
           low: 99356941
        }, {
           name: ' Unbroken ' ,
           low: 98527824
        }, {
           name: ' Battleship ' ,
           low: 93477717
        }, {
           name: ' Waterworld ' ,
           low: 89246220
        }, {
           name: ' Total Recall ' ,
           low: 86856088
        }, {
           name: ' Total Recall ' ,
           low: 86856088
        }, {
           name: ' Hellboy II: The Golden Army ' ,
           low: 77888063
        }, {
           name: ' Rush Hour 3 ' ,
           low: 76585882
        }, {
           name: ' Contact ' ,
           low: 75900000
        }, {
           name: ' Blade Runner 2049 ' ,
           low: 74357408
        }, {
           name: ' The Interpreter ' ,
           low: 72753837
        }, {
           name: ' 2 Guns ' ,
           low: 71493015
        }, {
           name: ' The Predator ' ,
           low: 71487563
        }, {
           name: ' Unstoppable ' ,
           low: 70720921
        }, {
           name: ' The Emperor's New Groove ' ,
           low: 69296573
        }, {
           name: ' Swordfish ' ,
           low: 67080413
        }, {
           name: ' The Haunted Mansion ' ,
           low: 65750628
        }, {
           name: ' The Family Man ' ,
           low: 64715863
        }, {
           name: ' Black Hawk Down ' ,
           low: 64691085
        }, {
           name: ' Step Brothers ' ,
           low: 63468793
        }, {
           name: ' The BFG ' ,
           low: 59646680
        }, {
           name: ' Last Action Hero ' ,
           low: 52298489
        }, {
           name: ' The Huntsman: Winterâs War ' ,
           low: 50149302
        }, {
           name: ' The River Wild ' ,
           low: 49215000
        }, {
           name: ' Christmas with the Kranks ' ,
           low: 46469187
        }, {
           name: ' The Odd Couple ' ,
           low: 43327234
        }, {
           name: ' Joy ' ,
           low: 41134059
        }, {
           name: ' The Internship ' ,
           low: 35672764
        }, {
           name: ' Escape Plan ' ,
           low: 33735965
        }, {
           name: ' A Wrinkle in Time ' ,
           low: 30401882
        }, {
           name: ' Sherlock Gnomes ' ,
           low: 28527651
        }, {
           name: ' Spirit: Stallion of the Cimarron ' ,
           low: 26515310
        }, {
           name: ' Winnie the Pooh ' ,
           low: 19871429
        }, {
           name: ' Meet the Robinsons ' ,
           low: 19333034
        }, {
           name: ' A Shaun the Sheep Movie: Farmageddon ' ,
           low: 18100248
        }, {
           name: ' Pinocchio ' ,
           low: 17083611
        }, {
           name: ' A Night at the Opera ' ,
           low: 14536290
        }, {
           name: ' The Kingdom ' ,
           low: 14009602
        }, {
           name: ' Cowboys and Aliens ' ,
           low: 13038324
        }, {
           name: ' The Peacemaker ' ,
           low: 12967368
        }, {
           name: ' Ramona and Beezus ' ,
           low: 12293743
        }, {
           name: ' Africa Screams ' ,
           low: 10662822
        }, {
           name: ' The Campaign ' ,
           low: 9907746
        }, {
           name: ' Willy Wonka & the Chocolate Factory ' ,
           low: 9684950
        }, {
           name: ' I, Frankenstein ' ,
           low: 9575290
        }, {
           name: ' Money Train ' ,
           low: 9224232
        }, {
           name: ' John Carter ' ,
           low: 7778100
        }, {
           name: ' Oceans ' ,
           low: 6787530
        }, {
           name: ' Out of Time ' ,
           low: 5489826
        }, {
           name: ' Chain Reaction ' ,
           low: 5209334
        }, {
           name: ' Mr. Magorium's Wonder Emporium ' ,
           low: 4474661
        }, {
           name: ' Bringing Up Baby ' ,
           low: 2908803
        }, {
           name: ' The Flintstones in Viva Rock Vegas ' ,
           low: 1431365
        }, {
           name: ' Where the Wild Things Are ' ,
           low: -876344
        }, {
           name: ' Last Holiday ' ,
           low: -1656753
        }, {
           name: ' Bicentennial Man ' ,
           low: -2579224
        }, {
           name: ' Ben-Hur ' ,
           low: -3330352
        }, {
           name: ' The Stepford Wives ' ,
           low: -3778029
        }, {
           name: ' Pinocchio ' ,
           low: -13318189
        }, {
           name: ' The Court Jester ' ,
           low: -17324090
        }, {
           name: ' 102 Dalmatians ' ,
           low: -18058441
        }, {
           name: ' The Swan Princess ' ,
           low: -19790069
        }, {
           name: ' The Legend of Bagger Vance ' ,
           low: -20764514
        }, {
           name: ' 47 Ronin ' ,
           low: -23283185
        }, {
           name: ' Primary Colors ' ,
           low: -25982016
        }, {
           name: ' Speed Racer ' ,
           low: -26605538
        }, {
           name: ' Thunderbirds ' ,
           low: -26768556
        }, {
           name: ' The Adventures of Ford Fairlane ' ,
           low: -28576611
        }, {
           name: ' The Road to El Dorado ' ,
           low: -29300000
        }, {
           name: ' Home on the Range ' ,
           low: -33517539
        }, {
           name: ' Around the World in 80 Days ' ,
           low: -37995841
        }, {
           name: ' Oliver Twist ' ,
           low: -38329080
        }, {
           name: ' Garfield: The Movie ' ,
           low: -38600000
        }, {
           name: ' Son of the Mask ' ,
           low: -40081578
        }, {
           name: ' All the King's Men ' ,
           low: -45478542
        }, {
           name: ' Battlefield Earth: A Saga of the Year 3000 ' ,
           low: -50274337
        }, {
           name: ' The 13th Warrior ' ,
           low: -63301101
        }, {
           name: ' Monster Trucks ' ,
           low: -63357202
        }, {
           name: ' The Alamo ' ,
           low: -68088638
        }, {
           name: ' The Nutcracker in 3D ' ,
           low: -69533984
        }, {
           name: ' Cutthroat Island ' ,
           low: -73482678
        }, {
           name: ' 355 ' ,
           low: -75000000

In [127]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/dumbbell.js"></script>
<script src="https://code.highcharts.com/modules/lollipop.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="r3"></div> 
    <p class= "highcharts-description">
    </p>
</figure>

In [128]:
%%js
Highcharts.chart('r3', { //name of grapg is r3

    chart: {
        type: 'lollipop', //type of graph is the lollipop graph
        inverted:true, //this makes the graph horizontal
        height:2000  //this allows the size of the graph to be ajusted
    },

    accessibility: {
        point: {
            valueDescriptionFormat: '{index}. {xDescription}, {point.y}.'
        }
    },

    legend: {
        enabled: true,
        layout:'vertical',
        reversed:true
    },

    subtitle: {
        text: '209 Movies'
    },

    title: {
        text: 'Comedy Genre'
    },

    tooltip: {
        shared: true //allows the tooltip to be enabled
    },

    xAxis: {
        type:'category',
        title:{
            text:'Movies' //name of x-axis
        }
    },
    yAxis:{
        title:{
            text:'Profit' //name of y-axis
        }
    },
    series: [{
        name: 'Profit',
        color:'#2EF429', //allows color to be adjusted
        dataSorting:{
            enabled: false
        },
        data: [{ 
           name: ' Avengers: Infinity War ' ,
           low: 1748134200
        }, { 
           name: ' Jurassic World ' ,
           low: 1433854864
        }, { 
           name: ' Incredibles 2 ' ,
           low: 1042520711
        }, { 
           name: ' Transformers: Dark of the Moon ' ,
           low: 928790543
        }, { 
           name: ' Jumanji: Welcome to the Jungle ' ,
           low: 874496193
        }, { 
           name: ' Rogue One: A Star Wars Story ' ,
           low: 849102856
        }, { 
           name: ' Finding Nemo ' ,
           low: 842429370
        }, { 
           name: ' The Lord of the Rings: The Two Towers ' ,
           low: 840699645
        }, { 
           name: ' Alice in Wonderland ' ,
           low: 825491110
        }, { 
           name: ' 101 Dalmatians ' ,
           low: 825300000
        }, { 
           name: ' Mary Poppins ' ,
           low: 817460782
        }, { 
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           low: 769701857
        }, { 
           name: ' Venom ' ,
           low: 737628605
        }, { 
           name: ' Fantastic Beasts and Where to Find Them ' ,
           low: 622402853
        }, { 
           name: ' Mission: Impossibleâ Fallout ' ,
           low: 609456552
        }, { 
           name: ' Guardians of the Galaxy ' ,
           low: 600867516
        }, { 
           name: ' Spider-Man 2 ' ,
           low: 595110670
        }, { 
           name: ' Shrek Forever After ' ,
           low: 591244673
        }, { 
           name: ' The Matrix Reloaded ' ,
           low: 588576929
        }, { 
           name: ' Ice Age: The Meltdown ' ,
           low: 576899282
        }, { 
           name: ' X-Men: Days of Future Past ' ,
           low: 547862775
        }, { 
           name: ' Men in Black ' ,
           low: 497790539
        }, { 
           name: ' Ant-Man and the Wasp ' ,
           low: 493144660
        }, { 
           name: ' My Fair Lady (1964) ' ,
           low: 457992835
        }, { 
           name: ' Monsters, Inc. ' ,
           low: 444757719
        }, { 
           name: ' Aladdin ' ,
           low: 437234314
        }, { 
           name: ' Mission: Impossible 2 ' ,
           low: 429588516
        }, { 
           name: ' Armageddon ' ,
           low: 414600000
        }, { 
           name: ' Transformers: The Last Knight ' ,
           low: 385893340
        }, { 
           name: ' Funny Girl ' ,
           low: 378315879
        }, { 
           name: ' Rise of the Planet of the Apes ' ,
           low: 377986200
        }, { 
           name: ' Rise of the Planet of the Apes ' ,
           low: 377986200
        }, { 
           name: ' Kong: Skull Island ' ,
           low: 376072059
        }, { 
           name: ' Alvin and the Chipmunks: The Squeakquel ' ,
           low: 373483213
        }, { 
           name: ' Clash of the Titans ' ,
           low: 368214888
        }, { 
           name: ' Cars 2 ' ,
           low: 360155383
        }, { 
           name: ' Babe ' ,
           low: 356864079
        }, { 
           name: ' WALL-E ' ,
           low: 352508025
        }, { 
           name: ' Django Unchained ' ,
           low: 349948323
        }, { 
           name: ' San Andreas ' ,
           low: 346258539
        }, { 
           name: ' Angels & Demons ' ,
           low: 340875846
        }, { 
           name: ' The Love Bug ' ,
           low: 334428135
        }, { 
           name: ' Tangled ' ,
           low: 326477240
        }, { 
           name: ' A Bug\'s Life ' ,
           low: 318300000
        }, { 
           name: ' Tarzan ' ,
           low: 303191819
        }, { 
           name: ' Happy Feet ' ,
           low: 300000317
        }, { 
           name: ' Hotel Transylvania ' ,
           low: 293505812
        }, { 
           name: ' Hotel Transylvania ' ,
           low: 293505812
        }, { 
           name: ' X-Men 2 ' ,
           low: 281875536
        }, { 
           name: ' Who Framed Roger Rabbit? ' ,
           low: 281500000
        }, { 
           name: ' Fast & Furious ' ,
           low: 278064265
        }, { 
           name: ' Live Free or Die Hard ' ,
           low: 272288147
        }, { 
           name: ' Now You See Me ' ,
           low: 267769200
        }, { 
           name: ' Alvin and the Chipmunks: Chipwrecked ' ,
           low: 267695435
        }, { 
           name: ' Terminator 3: Rise of the Machines ' ,
           low: 263058296
        }, { 
           name: ' Home ' ,
           low: 255997896
        }, { 
           name: ' The Pursuit of Happyness ' ,
           low: 252311093
        }, { 
           name: ' Night at the Museum: Battle of the Smithsonian ' ,
           low: 252231063
        }, { 
           name: ' I, Robot ' ,
           low: 243629585
        }, { 
           name: ' Batman Forever ' ,
           low: 236529144
        }, { 
           name: ' G.I. Joe: Retaliation ' ,
           low: 235740705
        }, { 
           name: ' Alita: Battle Angel ' ,
           low: 232976036
        }, { 
           name: ' Snow White and the Huntsman ' ,
           low: 231021746
        }, { 
           name: ' The Green Mile ' ,
           low: 230701374
        }, { 
           name: ' Captain America: The First Avenger ' ,
           low: 230569776
        }, { 
           name: ' Air Force One ' ,
           low: 230268353
        }, { 
           name: ' Dinosaur ' ,
           low: 228648063
        }, { 
           name: ' The Hunchback of Notre Dame ' ,
           low: 225500000
        }, { 
           name: ' X-Men Origins: Wolverine ' ,
           low: 224825760
        }, { 
           name: ' Doctor Dolittle ' ,
           low: 222656605
        }, { 
           name: ' How the Grinch Stole Christmas ' ,
           low: 222141403
        }, { 
           name: ' Herbie Rides Again ' ,
           low: 221457746
        }, { 
           name: ' 300: Rise of an Empire ' ,
           low: 220780051
        }, { 
           name: ' Mad Max: Fury Road ' ,
           low: 220098020
        }, { 
           name: ' A Good Day to Die Hard ' ,
           low: 212249198
        }, { 
           name: ' Horton Hears a Who! ' ,
           low: 212000000
        }, { 
           name: ' The Expendables 2 ' ,
           low: 211979256
        }, { 
           name: ' Little Fockers ' ,
           low: 210650574
        }, { 
           name: ' The Absent-Minded Professor ' ,
           low: 198495971
        }, { 
           name: ' Edge of Tomorrow ' ,
           low: 192541256
        }, { 
           name: ' Megamind ' ,
           low: 191887208
        }, { 
           name: ' Freaky Friday ' ,
           low: 184943740
        }, { 
           name: ' Chicken Run ' ,
           low: 179834564
        }, { 
           name: ' The Tourist ' ,
           low: 178731369
        }, { 
           name: ' Unbreakable ' ,
           low: 174856037
        }, { 
           name: ' Son of Flubber ' ,
           low: 169907151
        }, { 
           name: ' The Curious Case of Benjamin Button ' ,
           low: 169631958
        }, { 
           name: ' Oblivion ' ,
           low: 167916633
        }, { 
           name: ' The Princess and the Frog ' ,
           low: 165997378
        }, { 
           name: ' Terminator Salvation ' ,
           low: 165491792
        }, { 
           name: ' Wallace & Gromit: The Curse of the Were-Rabbit ' ,
           low: 162600000
        }, { 
           name: ' The Golden Compass ' ,
           low: 162262558
        }, { 
           name: ' The Sword in the Stone ' ,
           low: 162150197
        }, { 
           name: ' Rise of the Guardians ' ,
           low: 161900902
        }, { 
           name: ' The Great Gatsby ' ,
           low: 161040419
        }, { 
           name: ' The Land Before Time ' ,
           low: 160775761
        }, { 
           name: ' The Muppets ' ,
           low: 157184237
        }, { 
           name: ' The Apple Dumpling Gang ' ,
           low: 155486600
        }, { 
           name: ' Pixels ' ,
           low: 154041804
        }, { 
           name: ' The Peanuts Movie ' ,
           low: 151091610
        }, { 
           name: ' Star Trek Beyond ' ,
           low: 150802233
        }, { 
           name: ' 102 Dalmatians ' ,
           low: 150550424
        }, { 
           name: ' The Return of the Pink Panthe ' ,
           low: 141929190
        }, { 
           name: ' Knight and Day ' ,
           low: 141751370
        }, { 
           name: ' The Equalizer ' ,
           low: 137903624
        }, { 
           name: ' Cloudy with a Chance of Meatballs ' ,
           low: 136827677
        }, { 
           name: ' Pacific Rim: Uprising ' ,
           low: 135930148
        }, { 
           name: ' London Has Fallen ' ,
           low: 135194085
        }, { 
           name: ' Van Helsing ' ,
           low: 130150546
        }, { 
           name: ' Gone in 60 Seconds ' ,
           low: 129343008
        }, { 
           name: ' Percy Jackson & the Olympians: The Lightning Thief ' ,
           low: 128050874
        }, { 
           name: ' Yogi Bear ' ,
           low: 126965572
        }, { 
           name: ' Disneyâs A Christmas Carol ' ,
           low: 125709697
        }, { 
           name: ' After Earth ' ,
           low: 121499665
        }, { 
           name: ' Mr. Deeds ' ,
           low: 121269535
        }, { 
           name: ' George Of The Jungle ' ,
           low: 119463257
        }, { 
           name: ' America\'s Sweethearts ' ,
           low: 114648493
        }, { 
           name: ' Lemony Snicket\'s A Series of Unfortunate Events ' ,
           low: 112956024
        }, { 
           name: ' Robin Hood ' ,
           low: 112459006
        }, { 
           name: ' End of Days ' ,
           low: 112026975
        }, { 
           name: ' Hannah Montana: The Movie ' ,
           low: 110545279
        }, { 
           name: ' Teenage Mutant Ninja Turtles: Out of the Shadows ' ,
           low: 110328374
        }, { 
           name: ' Public Enemies ' ,
           low: 109782709
        }, { 
           name: ' The Expendables 3 ' ,
           low: 109461378
        }, { 
           name: ' Tropic Thunder ' ,
           low: 101145256
        }, { 
           name: ' Goosebumps ' ,
           low: 100905324
        }, { 
           name: ' I Now Pronounce You Chuck and Larry ' ,
           low: 100708462
        }, { 
           name: ' Jack Reacher: Never Go Back ' ,
           low: 99946489
        }, { 
           name: ' The Jackal ' ,
           low: 99356941
        }, { 
           name: ' Unbroken ' ,
           low: 98527824
        }, { 
           name: ' Battleship ' ,
           low: 93477717
        }, { 
           name: ' Waterworld ' ,
           low: 89246220
        }, { 
           name: ' Total Recall ' ,
           low: 86856088
        }, { 
           name: ' Total Recall ' ,
           low: 86856088
        }, { 
           name: ' Hellboy II: The Golden Army ' ,
           low: 77888063
        }, { 
           name: ' Rush Hour 3 ' ,
           low: 76585882
        }, { 
           name: ' Contact ' ,
           low: 75900000
        }, { 
           name: ' Blade Runner 2049 ' ,
           low: 74357408
        }, { 
           name: ' The Interpreter ' ,
           low: 72753837
        }, { 
           name: ' 2 Guns ' ,
           low: 71493015
        }, { 
           name: ' The Predator ' ,
           low: 71487563
        }, { 
           name: ' Unstoppable ' ,
           low: 70720921
        }, { 
           name: ' The Emperor\'s New Groove ' ,
           low: 69296573
        }, { 
           name: ' Swordfish ' ,
           low: 67080413
        }, { 
           name: ' The Haunted Mansion ' ,
           low: 65750628
        }, { 
           name: ' The Family Man ' ,
           low: 64715863
        }, { 
           name: ' Black Hawk Down ' ,
           low: 64691085
        }, { 
           name: ' Step Brothers ' ,
           low: 63468793
        }, { 
           name: ' The BFG ' ,
           low: 59646680
        }, { 
           name: ' Last Action Hero ' ,
           low: 52298489
        }, { 
           name: ' The Huntsman: Winterâs War ' ,
           low: 50149302
        }, { 
           name: ' The River Wild ' ,
           low: 49215000
        }, { 
           name: ' Christmas with the Kranks ' ,
           low: 46469187
        }, { 
           name: ' The Odd Couple ' ,
           low: 43327234
        }, { 
           name: ' Joy ' ,
           low: 41134059
        }, { 
           name: ' The Internship ' ,
           low: 35672764
        }, { 
           name: ' Escape Plan ' ,
           low: 33735965
        }, { 
           name: ' A Wrinkle in Time ' ,
           low: 30401882
        }, { 
           name: ' Sherlock Gnomes ' ,
           low: 28527651
        }, { 
           name: ' Spirit: Stallion of the Cimarron ' ,
           low: 26515310
        }, { 
           name: ' Winnie the Pooh ' ,
           low: 19871429
        }, { 
           name: ' Meet the Robinsons ' ,
           low: 19333034
        }, { 
           name: ' A Shaun the Sheep Movie: Farmageddon ' ,
           low: 18100248
        }, { 
           name: ' Pinocchio ' ,
           low: 17083611
        }, { 
           name: ' A Night at the Opera ' ,
           low: 14536290
        }, { 
           name: ' The Kingdom ' ,
           low: 14009602
        }, { 
           name: ' Cowboys and Aliens ' ,
           low: 13038324
        }, { 
           name: ' The Peacemaker ' ,
           low: 12967368
        }, { 
           name: ' Ramona and Beezus ' ,
           low: 12293743
        }, { 
           name: ' Africa Screams ' ,
           low: 10662822
        }, { 
           name: ' The Campaign ' ,
           low: 9907746
        }, { 
           name: ' Willy Wonka & the Chocolate Factory ' ,
           low: 9684950
        }, { 
           name: ' I, Frankenstein ' ,
           low: 9575290
        }, { 
           name: ' Money Train ' ,
           low: 9224232
        }, { 
           name: ' John Carter ' ,
           low: 7778100
        }, { 
           name: ' Oceans ' ,
           low: 6787530
        }, { 
           name: ' Out of Time ' ,
           low: 5489826
        }, { 
           name: ' Chain Reaction ' ,
           low: 5209334
        }, { 
           name: ' Mr. Magorium\'s Wonder Emporium ' ,
           low: 4474661
        }, { 
           name: ' Bringing Up Baby ' ,
           low: 2908803
        }, { 
           name: ' The Flintstones in Viva Rock Vegas ' ,
           low: 1431365
        }]
    }]
});

# Blueprint: Movies that did not make any Profit.

This is the blueprint for creating the eight visualization, movies that did not make any profit. Highcharts will be used to create this graph. 

__Blueprint:__
     
   - The graph used for this visualazation is Highcharts Column chart with negative values series which is found in the Highcharts Demos. Column charts are mostly used to compare categories with different values including negative value, they are very popular and transparant types of charts.
    
 The first approach to this chart is by understanding the format of the code script. Like the previous data visualization this graph is constructed by two different types of code HTML and Javascript. The HTML script is very similar to the previous graph, they allow the column graph to produce negative column and comparison between any particular value of the movie. Closing of the script is similar to the previous script but with a unique name to it self;
                              <figure class="highcharts-figure">
                              <div id="w1"></div> 
                              <p class="highcharts-description">
                              </p>
                              </figure>
The second approach is scripting the javascript section. The javascript section is entirely different to the previous graph, before diving into the javascript code there needs to be data extracted. The names of all the movies that didn't make any profit which will be extracted from the parent dataframe, also the cost, the loss and the revenue of all the movies that did not make any profit.

- There are five major sections in the javascript section that are very critical.
     - 1. The list that is called categories is where all the names of all the movies that were not profitable are scripted. 
                             categories:['Random Hearts','Gods of Egypt','Peter Pan','Children of Men','I Spy','Fantastica: A Boonie Bears','Thirteen Days','Downsizing','Mortal Engines','The Oegieloves','Spanglish','Mighty Joe Young', 'Land of the Lost','Windtalkers',"A Boy's Life",'R.I.P.D.','Soldier','Stealth','The Alamo', 'Renegades']
     
     - 2. The y-axis min, max and steps are very important values that are put in a specific way to allow most of the negative values to be visible, based on how large the other values were;
                              yAxis:{
                              min:-500000,
                              max:180000000,
                              step:50000,
                              },
     
     - 3. The series section has three sub-section;
         - The Cost category is a list consisting of all the amount of money spent to create the movies that were not profitable.
                name:'Cost',
                data:[64000000,140000000,100000000,76000000,70000000,90000000,80000000,
                     68000000,100000000,20000000,75000000,80000000,100000000,115000000,
                     90000000,130000000,75000000,138000000,92000000,77500000]
         - The Revenue category is a list consisting of all the money thta were made but not minus the cost of all the movies not profitable.
                name:'Revenue',
                data:[63200000,138836756,95255485,69845011,60279822,77151096,66554547,54462971,
                      85287417,1065907,54344321,50632037,69548641,77628265,42460000,
                      79076678,14623082,76416746,23911362,1521672]
         - The Loss category is a list showing all the amount of money that fell short, meaning the cost was higher than the revenue giving the loss negitative values. Each movie spent more tahn they anticipated to make. 
                name:'Loss',
                data:[-800000,-1163244,-4744515,-6154989,-9720178,-12848904,-13445453,
                  -13537029,-14712583,-18934093,-20655679,-29367963,-30451359,
                  -37371735,-47540000,-50923322,-60376918,-61583254,-68088638,
                  -75978328]

In [174]:
# getting the Cost of the movies that had losses
new3 = []
for i in new1[-29:]:
    new3.append(all_Comedy_info1.Buget[i[0]])
new3

[100000000,
 45000000,
 90000000,
 95000000,
 100000000,
 45000000,
 38497977,
 85000000,
 37012716,
 60000000,
 175000000,
 65000000,
 120000000,
 55000000,
 49000000,
 95000000,
 110000000,
 110000000,
 65000000,
 50000000,
 100000000,
 55000000,
 80000000,
 125000000,
 125000000,
 92000000,
 90000000,
 92000000,
 75000000]

In [173]:
# getting the Revenue of the movies with losses
new4 = []
for i in new1[-29:]:
    new4.append(all_Comedy_info1.Total_gross[i[0]])
new4

[99123656,
 43343247,
 87420776,
 91669648,
 96221971,
 31681811,
 21173887,
 66941559,
 17222647,
 39235486,
 151716815,
 39017984,
 93394462,
 28231444,
 20423389,
 65700000,
 76482461,
 72004159,
 26670920,
 11400000,
 59918422,
 9521458,
 29725663,
 61698899,
 61642798,
 23911362,
 20466016,
 18517322,
 0]

In [172]:
# the the amount of money for thr movies with losses
for i in new1[-29:]:
    print(i[1])

-876344
-1656753
-2579224
-3330352
-3778029
-13318189
-17324090
-18058441
-19790069
-20764514
-23283185
-25982016
-26605538
-26768556
-28576611
-29300000
-33517539
-37995841
-38329080
-38600000
-40081578
-45478542
-50274337
-63301101
-63357202
-68088638
-69533984
-73482678
-75000000

In [175]:
# the names of the movies with losses
new2[-29:]

['Where the Wild Things Are',
 'Last Holiday',
 'Bicentennial Man',
 'Ben-Hur',
 'The Stepford Wives',
 'Pinocchio',
 'The Court Jester',
 '102 Dalmatians',
 'The Swan Princess',
 'The Legend of Bagger Vance',
 '47 Ronin',
 'Primary Colors',
 'Speed Racer',
 'Thunderbirds',
 'The Adventures of Ford Fairlane',
 'The Road to El Dorado',
 'Home on the Range',
 'Around the World in 80 Days',
 'Oliver Twist',
 'Garfield: The Movie',
 'Son of the Mask',
 "All the King's Men",
 'Battlefield Earth: A Saga of the Year 3000',
 'The 13th Warrior',
 'Monster Trucks',
 'The Alamo',
 'The Nutcracker in 3D',
 'Cutthroat Island',
 '355']

In [1]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibilty.js"></script>

<figure class="highcharts-figure">
    <div id="w3"></div> 
    <div id="w33"></div> 
    <p class="highcharts-description">
    </p>
</figure>

In [2]:
%%js
Highcharts.chart('w3',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:'Movies That Did Not Make Any Profit'
    },
    xAxis:{
        //name of all the movies 
        categories:['Where the Wild Things Are','Last Holiday','Bicentennial Man','Ben-Hur','The Stepford Wives',
                   'Pinocchio','The Court Jester','102 Dalmatians','The Swan Princess','The Legend of Bagger Vance',
                   '47 Ronin','Primary Colors','Speed Racer','Thunderbirds'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#05B41F','#145A32','#8FF60A'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[100000000,45000000,90000000,95000000,100000000,45000000,38497977,
              85000000,37012716,60000000,175000000,65000000,120000000,55000000,]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[-876344,-1656753,-2579224,-3330352,-3778029,-13318189,-17324090,
             -18058441,-19790069,-20764514,-23283185,-25982016,-26605538,-26768556]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[99123656,43343247,87420776,91669648,96221971,31681811,21173887,
             66941559,17222647,39235486,151716815,39017984,93394462,28231444]
    }]
});

In [3]:
%%js
Highcharts.chart('w33',{  
    //name of graph
    
    chart:{
        type:'column'
    },
    title:{
        text:''
    },
    xAxis:{
        //name of all the movies 
        categories:['The Adventures of Ford Fairlane','The Road to El Dorado','Home on the Range','Around the World in 80 Days',
                   'Oliver Twist','Garfield: The Movie','Son of the Mask',"All the King's Men",'Battlefield Earth: A Saga of the Year 3000',
                  'The 13th Warrior','Monster Trucks','The Alamo','The Nutcracker in 3D','Cutthroat Island',
                  '355'],
        labels:{
           enabled:false 
        }
    },
    credits:{
        enabled:false
    },
    //colors of the columns for cost, loss and revenue 
    colors:['#05B41F','#145A32','#8FF60A'],
    yAxis:{
        //the y-axis is going from -500,000 to 1.8 million
        min:-500000,
        max:180000000,
        step:50000,
    },
    series:[{
        //shows the cost of all movies
        name:'Cost',
        data:[49000000,95000000,110000000,10000000,65000000,50000000,100000000,55000000,
              80000000,125000000,125000000,92000000,90000000,92000000,75000000]
    },{
        //shows the loss of all movies ranging from 500,000 50 1.8 million
        name:'Loss',
        data:[-28576611,-29300000,-33517539,-37995841,-38329080,-38600000,-40081578,
             -45478542,-50274337,-63301101,-63357202,-68088638,-69533984,-73482678,
             -75000000]
    },{
        //the revenue of all movies
        name:'Revenue',
        data:[20423389,65700000,76482461,72004159,26670920,11400000,59918422,
              9521458,29725663,61698899,61642798,23911362,20466016,18517322,
              0]
    }]
});

# Blueprint: Top 20 Highest Profitable Movies and Top 20 Lowest Profitable Movies

This is the blueprint for creating the ninth and tenth visualization, Top 20 Highest Profitable Movies and the Top 20 Lowest Profitable Movies. Highcharts will be used to create these garphs.

__Blueprint:__
  - The graph used for these visualization is Highcharts 3D Cylinder Chart for the Top 20 Highest Profitable Movies and Highcharts Chart Rotation Chart Series for thr Top 20 lowest Profitable Movies, which is all found in the highcharts demos. The chart rotation chart series have an Alpha, Beta and Depth angle which can be adjusted to rotate the graph around.
  
    The first approach to this chart is by understanding the format of the code script. Like the previous graph this chart is constructed by two different types of code HTML and Javascript. The HTML section is very similar to the previous graph but the only difference is this HTML code;
         <script src="https://code.highcharts.com/highcharts-3d.js"></script>
         <script src="https://code.highcharts.com/modules/cylinder.js"></script>
    This allows the graphs to be 3D and it also allows it to be cylinder. To close of two script is also similar to the previous script but with a unique name to it self. 
       
       This is for the cylinder graph;
                      <figure class="highcharts-figure">
                      <div id="b1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
                
       This if for the 3D column graph;
                      <figure class="highcharts-figure">
                      <div id="c1"></div>
                      <p class="highcharts-description">
                      </p>
                      </figure>
   The second approach is scripting the javascript section. The javascript section is very simple, brfore that there needs to be some data extracted from the parent dataframe. These are the elements needed to be extracted for this visualazation. For the Top 20 Highest Profitable Movies the name and amount of profit made is needed, for the Top 20 Lowest Profitable Movies the name and amount of profit made in integer of all the movies is needed in that category.
   
 There is just one sub-section in each graph that are particular, the data sub-section in the series section. It is a body of sequenences of list that consist of the name and amount of profit made in integer.
   
   This is from the first graph;
            ['Avatar|1st Highest',2351345279],
            ['The Sound of Music|2nd Highest', 2303109231],
            ['Black Panther|3rd Highest',1148258224]
       
   This is from the second graph;
            [' Miami Vice|170th Highest', 28818556 ],
            [' Space Chimps|171th Highest', 28097693 ],
            [' The Tale of Despereaux|172th Highest', 26957280 ],

Using a for loop to put the top 20 highest profitable movie name and profit in html code which will be pasted in the cell below.

In [178]:
for i,x in enumerate(range(len(new2[:20]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Avengers: Infinity War | 0 th Highest', 1748134200 ],
[' Jurassic World | 1 th Highest', 1433854864 ],
[' Incredibles 2 | 2 th Highest', 1042520711 ],
[' Transformers: Dark of the Moon | 3 th Highest', 928790543 ],
[' Jumanji: Welcome to the Jungle | 4 th Highest', 874496193 ],
[' Rogue One: A Star Wars Story | 5 th Highest', 849102856 ],
[' Finding Nemo | 6 th Highest', 842429370 ],
[' The Lord of the Rings: The Two Towers | 7 th Highest', 840699645 ],
[' Alice in Wonderland | 8 th Highest', 825491110 ],
[' 101 Dalmatians | 9 th Highest', 825300000 ],
[' Mary Poppins | 10 th Highest', 817460782 ],
[' Ice Age: Dawn of the Dinosaurs | 11 th Highest', 769701857 ],
[' Venom | 12 th Highest', 737628605 ],
[' Fantastic Beasts and Where to Find Them | 13 th Highest', 622402853 ],
[' Mission: ImpossibleâFallout | 14 th Highest', 609456552 ],
[' Guardians of the Galaxy | 15 th Highest', 600867516 ],
[' Spider-Man 2 | 16 th Highest', 595110670 ],
[' Shrek Forever After | 17 th Highest', 591244673 ],
[' The Matrix Reloaded | 18 th Highest', 588576929 ],
[' Ice Age: The Meltdown | 19 th Highest', 576899282 ],

In [132]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/cylinder.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="httos://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="b3"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [133]:
%%js
new Highcharts.chart('b3',{ //name of graph
    chart:{
        type:'cylinder', // makes graph cylinder
        // adjust the position of graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:16,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Highest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // mkaes the graph one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Highest Profit',
        color:'#02FA11',// color of cylinders in graph
           data:[
     // names and amount of profit made in integer of the ten most highest profitable movies
            [' Avengers: Infinity War | 1st Highest', 1748134200 ],
[' Jurassic World | 2nd Highest', 1433854864 ],
[' Incredibles 2 | 3rd Highest', 1042520711 ],
[' Transformers: Dark of the Moon | 4th Highest', 928790543 ],
[' Jumanji: Welcome to the Jungle | 5th Highest', 874496193 ],
[' Rogue One: A Star Wars Story | 6th Highest', 849102856 ],
[' Finding Nemo | 7th Highest', 842429370 ],
[' The Lord of the Rings: The Two Towers | 8th Highest', 840699645 ],
[' Alice in Wonderland | 9th Highest', 825491110 ],
[' 101 Dalmatians | 10th Highest', 825300000 ],
[' Mary Poppins | 11th Highest', 817460782 ],
[' Ice Age: Dawn of the Dinosaurs | 12th Highest', 769701857 ],
[' Venom | 13th Highest', 737628605 ],
[' Fantastic Beasts and Where to Find Them | 14th Highest', 622402853 ],
[' Mission: Impossibleâ Fallout | 15th Highest', 609456552 ],
[' Guardians of the Galaxy | 16th Highest', 600867516 ],
[' Spider-Man 2 | 17th Highest', 595110670 ],
[' Shrek Forever After | 18th Highest', 591244673 ],
[' The Matrix Reloaded | 19th Highest', 588576929 ],
[' Ice Age: The Meltdown | 20th Highest', 576899282 ]
         ]
    }]
        
});

Using a for loop to put the top 20 lowest profitable movie name and profit in html code which will be pasted in the cell below

In [186]:
for i,x in enumerate(range(len(new2[:182]))):
    print('['+"'",new2[x],'|',i,'th','Highest'+"'"+',',new1[x][1],'],')

[' Avengers: Infinity War | 0 th Highest', 1748134200 ],
[' Jurassic World | 1 th Highest', 1433854864 ],
[' Incredibles 2 | 2 th Highest', 1042520711 ],
[' Transformers: Dark of the Moon | 3 th Highest', 928790543 ],
[' Jumanji: Welcome to the Jungle | 4 th Highest', 874496193 ],
[' Rogue One: A Star Wars Story | 5 th Highest', 849102856 ],
[' Finding Nemo | 6 th Highest', 842429370 ],
[' The Lord of the Rings: The Two Towers | 7 th Highest', 840699645 ],
[' Alice in Wonderland | 8 th Highest', 825491110 ],
[' 101 Dalmatians | 9 th Highest', 825300000 ],
[' Mary Poppins | 10 th Highest', 817460782 ],
[' Ice Age: Dawn of the Dinosaurs | 11 th Highest', 769701857 ],
[' Venom | 12 th Highest', 737628605 ],
[' Fantastic Beasts and Where to Find Them | 13 th Highest', 622402853 ],
[' Mission: ImpossibleâFallout | 14 th Highest', 609456552 ],
[' Guardians of the Galaxy | 15 th Highest', 600867516 ],
[' Spider-Man 2 | 16 th Highest', 595110670 ],
[' Shrek Forever After | 17 th Highest', 591244673 ],
[' The Matrix Reloaded | 18 th Highest', 588576929 ],
[' Ice Age: The Meltdown | 19 th Highest', 576899282 ],
[' X-Men: Days of Future Past | 20 th Highest', 547862775 ],
[' Men in Black | 21 th Highest', 497790539 ],
[' Ant-Man and the Wasp | 22 th Highest', 493144660 ],
[' My Fair Lady (1964) | 23 th Highest', 457992835 ],
[' Monsters, Inc. | 24 th Highest', 444757719 ],
[' Aladdin | 25 th Highest', 437234314 ],
[' Mission: Impossible 2 | 26 th Highest', 429588516 ],
[' Armageddon | 27 th Highest', 414600000 ],
[' Transformers: The Last Knight | 28 th Highest', 385893340 ],
[' Funny Girl | 29 th Highest', 378315879 ],
[' Rise of the Planet of the Apes | 30 th Highest', 377986200 ],
[' Rise of the Planet of the Apes | 31 th Highest', 377986200 ],
[' Kong: Skull Island | 32 th Highest', 376072059 ],
[' Alvin and the Chipmunks: The Squeakquel | 33 th Highest', 373483213 ],
[' Clash of the Titans | 34 th Highest', 368214888 ],
[' Cars 2 | 35 th Highest', 360155383 ],
[' Babe | 36 th Highest', 356864079 ],
[' WALL-E | 37 th Highest', 352508025 ],
[' Django Unchained | 38 th Highest', 349948323 ],
[' San Andreas | 39 th Highest', 346258539 ],
[' Angels & Demons | 40 th Highest', 340875846 ],
[' The Love Bug | 41 th Highest', 334428135 ],
[' Tangled | 42 th Highest', 326477240 ],
[' A Bug's Life | 43 th Highest', 318300000 ],
[' Tarzan | 44 th Highest', 303191819 ],
[' Happy Feet | 45 th Highest', 300000317 ],
[' Hotel Transylvania | 46 th Highest', 293505812 ],
[' Hotel Transylvania | 47 th Highest', 293505812 ],
[' X-Men 2 | 48 th Highest', 281875536 ],
[' Who Framed Roger Rabbit? | 49 th Highest', 281500000 ],
[' Fast & Furious | 50 th Highest', 278064265 ],
[' Live Free or Die Hard | 51 th Highest', 272288147 ],
[' Now You See Me | 52 th Highest', 267769200 ],
[' Alvin and the Chipmunks: Chipwrecked | 53 th Highest', 267695435 ],
[' Terminator 3: Rise of the Machines | 54 th Highest', 263058296 ],
[' Home | 55 th Highest', 255997896 ],
[' The Pursuit of Happyness | 56 th Highest', 252311093 ],
[' Night at the Museum: Battle of the Smithsonian | 57 th Highest', 252231063 ],
[' I, Robot | 58 th Highest', 243629585 ],
[' Batman Forever | 59 th Highest', 236529144 ],
[' G.I. Joe: Retaliation | 60 th Highest', 235740705 ],
[' Alita: Battle Angel | 61 th Highest', 232976036 ],
[' Snow White and the Huntsman | 62 th Highest', 231021746 ],
[' The Green Mile | 63 th Highest', 230701374 ],
[' Captain America: The First Avenger | 64 th Highest', 230569776 ],
[' Air Force One | 65 th Highest', 230268353 ],
[' Dinosaur | 66 th Highest', 228648063 ],
[' The Hunchback of Notre Dame | 67 th Highest', 225500000 ],
[' X-Men Origins: Wolverine | 68 th Highest', 224825760 ],
[' Doctor Dolittle | 69 th Highest', 222656605 ],
[' How the Grinch Stole Christmas | 70 th Highest', 222141403 ],
[' Herbie Rides Again | 71 th Highest', 221457746 ],
[' 300: Rise of an Empire | 72 th Highest', 220780051 ],
[' Mad Max: Fury Road | 73 th Highest', 220098020 ],
[' A Good Day to Die Hard | 74 th Highest', 212249198 ],
[' Horton Hears a Who! | 75 th Highest', 212000000 ],
[' The Expendables 2 | 76 th Highest', 211979256 ],
[' Little Fockers | 77 th Highest', 210650574 ],
[' The Absent-Minded Professor | 78 th Highest', 198495971 ],
[' Edge of Tomorrow | 79 th Highest', 192541256 ],
[' Megamind | 80 th Highest', 191887208 ],
[' Freaky Friday | 81 th Highest', 184943740 ],
[' Chicken Run | 82 th Highest', 179834564 ],
[' The Tourist | 83 th Highest', 178731369 ],
[' Unbreakable | 84 th Highest', 174856037 ],
[' Son of Flubber | 85 th Highest', 169907151 ],
[' The Curious Case of Benjamin Button | 86 th Highest', 169631958 ],
[' Oblivion | 87 th Highest', 167916633 ],
[' The Princess and the Frog | 88 th Highest', 165997378 ],
[' Terminator Salvation | 89 th Highest', 165491792 ],
[' Wallace & Gromit: The Curse of the Were-Rabbit | 90 th Highest', 162600000 ],
[' The Golden Compass | 91 th Highest', 162262558 ],
[' The Sword in the Stone | 92 th Highest', 162150197 ],
[' Rise of the Guardians | 93 th Highest', 161900902 ],
[' The Great Gatsby | 94 th Highest', 161040419 ],
[' The Land Before Time | 95 th Highest', 160775761 ],
[' The Muppets | 96 th Highest', 157184237 ],
[' The Apple Dumpling Gang | 97 th Highest', 155486600 ],
[' Pixels | 98 th Highest', 154041804 ],
[' The Peanuts Movie | 99 th Highest', 151091610 ],
[' Star Trek Beyond | 100 th Highest', 150802233 ],
[' 102 Dalmatians | 101 th Highest', 150550424 ],
[' The Return of the Pink Panthe | 102 th Highest', 141929190 ],
[' Knight and Day | 103 th Highest', 141751370 ],
[' The Equalizer | 104 th Highest', 137903624 ],
[' Cloudy with a Chance of Meatballs | 105 th Highest', 136827677 ],
[' Pacific Rim: Uprising | 106 th Highest', 135930148 ],
[' London Has Fallen | 107 th Highest', 135194085 ],
[' Van Helsing | 108 th Highest', 130150546 ],
[' Gone in 60 Seconds | 109 th Highest', 129343008 ],
[' Percy Jackson & the Olympians: The Lightning Thief | 110 th Highest', 128050874 ],
[' Yogi Bear | 111 th Highest', 126965572 ],
[' Disneyâs A Christmas Carol | 112 th Highest', 125709697 ],
[' After Earth | 113 th Highest', 121499665 ],
[' Mr. Deeds | 114 th Highest', 121269535 ],
[' George Of The Jungle | 115 th Highest', 119463257 ],
[' America's Sweethearts | 116 th Highest', 114648493 ],
[' Lemony Snicket's A Series of Unfortunate Events | 117 th Highest', 112956024 ],
[' Robin Hood | 118 th Highest', 112459006 ],
[' End of Days | 119 th Highest', 112026975 ],
[' Hannah Montana: The Movie | 120 th Highest', 110545279 ],
[' Teenage Mutant Ninja Turtles: Out of the Shadows | 121 th Highest', 110328374 ],
[' Public Enemies | 122 th Highest', 109782709 ],
[' The Expendables 3 | 123 th Highest', 109461378 ],
[' Tropic Thunder | 124 th Highest', 101145256 ],
[' Goosebumps | 125 th Highest', 100905324 ],
[' I Now Pronounce You Chuck and Larry | 126 th Highest', 100708462 ],
[' Jack Reacher: Never Go Back | 127 th Highest', 99946489 ],
[' The Jackal | 128 th Highest', 99356941 ],
[' Unbroken | 129 th Highest', 98527824 ],
[' Battleship | 130 th Highest', 93477717 ],
[' Waterworld | 131 th Highest', 89246220 ],
[' Total Recall | 132 th Highest', 86856088 ],
[' Total Recall | 133 th Highest', 86856088 ],
[' Hellboy II: The Golden Army | 134 th Highest', 77888063 ],
[' Rush Hour 3 | 135 th Highest', 76585882 ],
[' Contact | 136 th Highest', 75900000 ],
[' Blade Runner 2049 | 137 th Highest', 74357408 ],
[' The Interpreter | 138 th Highest', 72753837 ],
[' 2 Guns | 139 th Highest', 71493015 ],
[' The Predator | 140 th Highest', 71487563 ],
[' Unstoppable | 141 th Highest', 70720921 ],
[' The Emperor's New Groove | 142 th Highest', 69296573 ],
[' Swordfish | 143 th Highest', 67080413 ],
[' The Haunted Mansion | 144 th Highest', 65750628 ],
[' The Family Man | 145 th Highest', 64715863 ],
[' Black Hawk Down | 146 th Highest', 64691085 ],
[' Step Brothers | 147 th Highest', 63468793 ],
[' The BFG | 148 th Highest', 59646680 ],
[' Last Action Hero | 149 th Highest', 52298489 ],
[' The Huntsman: Winterâs War | 150 th Highest', 50149302 ],
[' The River Wild | 151 th Highest', 49215000 ],
[' Christmas with the Kranks | 152 th Highest', 46469187 ],
[' The Odd Couple | 153 th Highest', 43327234 ],
[' Joy | 154 th Highest', 41134059 ],
[' The Internship | 155 th Highest', 35672764 ],
[' Escape Plan | 156 th Highest', 33735965 ],
[' A Wrinkle in Time | 157 th Highest', 30401882 ],
[' Sherlock Gnomes | 158 th Highest', 28527651 ],
[' Spirit: Stallion of the Cimarron | 159 th Highest', 26515310 ],
[' Winnie the Pooh | 160 th Highest', 19871429 ],
[' Meet the Robinsons | 161 th Highest', 19333034 ],
[' A Shaun the Sheep Movie: Farmageddon | 162 th Highest', 18100248 ],
[' Pinocchio | 163 th Highest', 17083611 ],
[' A Night at the Opera | 164 th Highest', 14536290 ],
[' The Kingdom | 165 th Highest', 14009602 ],
[' Cowboys and Aliens | 166 th Highest', 13038324 ],
[' The Peacemaker | 167 th Highest', 12967368 ],
[' Ramona and Beezus | 168 th Highest', 12293743 ],
[' Africa Screams | 169 th Highest', 10662822 ],
[' The Campaign | 170 th Highest', 9907746 ],
[' Willy Wonka & the Chocolate Factory | 171 th Highest', 9684950 ],
[' I, Frankenstein | 172 th Highest', 9575290 ],
[' Money Train | 173 th Highest', 9224232 ],
[' John Carter | 174 th Highest', 7778100 ],
[' Oceans | 175 th Highest', 6787530 ],
[' Out of Time | 176 th Highest', 5489826 ],
[' Chain Reaction | 177 th Highest', 5209334 ],
[' Mr. Magorium's Wonder Emporium | 178 th Highest', 4474661 ],
[' Bringing Up Baby | 179 th Highest', 2908803 ],
[' The Flintstones in Viva Rock Vegas | 180 th Highest', 1431365 ],
[' Where the Wild Things Are | 181 th Highest', -876344 ],

In [134]:
%%HTML
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/highcharts-3d.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
<script src="https://code.highcharts.com/modules/coloraxis.js"></script>

<figure class="highcharts-figure">
    <div id="c3"></div>
    <p class="highcharts-description">
    </p>
</figure>

In [135]:
%%js
Highcharts.chart('c3',{ // name of graph
    chart:{
        type:'column', // makes the graph column
       // adjusting the graph allowing it to be 3D
        options3d:{
            enabled:true,
            alpha:15,
            beta:25,
            depth:100,
            viewDistance:25
        }
    },
    title:{
        text:'Top 20 Lowest Profit '
    },
    plotOptions:{
        series:{
            depth:25,
            colorByPoint:false // allows the graph to be one single color
        }
    },
    series:[{
        showInLegend:true,
        name: 'Top Lowest Profits',
        color :'#01802A', // the color of the graph
           data:[
// the name and amount of profit made in integer of the least most profitable movies
            [' Meet the Robinsons | 161th Highest', 19333034 ],
[' A Shaun the Sheep Movie: Farmageddon | 162th Highest', 18100248 ],
[' Pinocchio | 163th Highest', 17083611 ],
[' A Night at the Opera | 164th Highest', 14536290 ],
[' The Kingdom | 165th Highest', 14009602 ],
[' Cowboys and Aliens | 166th Highest', 13038324 ],
[' The Peacemaker | 167th Highest', 12967368 ],
[' Ramona and Beezus | 168th Highest', 12293743 ],
[' Africa Screams | 169th Highest', 10662822 ],
[' The Campaign | 170th Highest', 9907746 ],
[' Willy Wonka & the Chocolate Factory | 171th Highest', 9684950 ],
[' I, Frankenstein | 172th Highest', 9575290 ],
[' Money Train | 173th Highest', 9224232 ],
[' John Carter | 174th Highest', 7778100 ],
[' Oceans | 175th Highest', 6787530 ],
[' Out of Time | 176th Highest', 5489826 ],
[' Chain Reaction | 177th Highest', 5209334 ],
[' Mr. Magorium\'s Wonder Emporium | 178th Highest', 4474661 ],
[' Bringing Up Baby | 179th Highest', 2908803 ],
[' The Flintstones in Viva Rock Vegas | 180th Highest', 1431365 ]
         ]
    }]
        
});

# Blueprint: What Movie is the most Successful.

Just because a movie has made the most profit dosen't mean it is more profitable than a movie that made less profit and or revenue. These were the five main factors that were used to better understand what movie was the most successful. The cost, the revenue, the profit, the gross profit margin percentage which is how much of the revenue is each movie walking away in percentageand the profit percenatge by cost which is comparing the profit with the cost in percentage. 
 
This is the blueprint for creating the elevnth, twelith, thirthith and fourthith visualization. Highcharts will be used to create these graphs.  

__Blueprint:__
   - The factors are split into half when it comes to what type of graph that will be used to analyze the data. The profit, revenue and cost varaiables will be analyzed using highcharts Combination Chart. This chart allows different combinations of senories to be combined in a single chart. This chart is a set of column series overlaid by a line and a pie chart. The line in Highchart was designed to illustrate the column averages while the pie is illustrating the column totals. However in this project the pie sereis will not be used and there will be two column series overlaid by a line series. The two columns will be revenue and profit, the line series will be the cost of all the movies in the blueprint. Like every other graph that used Highchart visualization, they all have two different types of code, HTML and javascript. The HTML section is very similar to all the previous graphs expect two main factors, the HTML code that allows the combination graph to be displayed is;
          <script src="https://code.highcharts.com/modules/series-label.js"></script>
          <script type="text/javascript" src="js/script.js"></script>
The other factors are the two different divs id for the combination chart;
          <div id="x1" display; inline-block></div>
          <div id="no1" display; inline-block></div>
 These are the names of the two combination chart that analyze ten movies each of the Top 20 Most     Profitable Movies.The javascript section for these graphs consist of four main subsection. The categories, the two types in the series section that are columns and the type in the series section that is spline. The categories subsection is a list of all the names of the movies that will be analyzed. The two types in the in the series subsection that are columns are the profit and revenue of all the movies and the third type in the spline series subsection is the cost of all the movies. 
     
     
                series:[{
                   type:'column',
                   color:"#111E6C",
                   name:'Profit',
                   data:                                  
                   [2351345279,2303109231,1148258224, 1135772799,1015392272,984846267,912044677,894039076,
          890069413,878000000]
      },{
          type:'column'
          color:Highcharts.getOptions().colors[1],
          name:'Revenue',
          data:[2776345279,2366000000,1348258224,
          1305772799,1215392272,1234846267,1027044677,1104039076,1140069413,1078000000]
     },{
          type:'spline',
          color:'gold',
          name:'Cost',
          data:[425000000,62890769,200000000,170000000,200000000,250000000,115000000,210000000,
                    250000000,200000000],


   The other factors are the two different divs id for the column chart;
            
            <div id="n1" display; inline-block></div>
            <div id="xo1" display; inline-block></div>

   The Gross Profit Margin Percentage and the Profit Percentage by Cost will all be analyzed using        highcharts combination chart but with only column. The two column will be The Percentage of Gross      Profit Margin and Profit by Cost of each movie.
   
   The javascript section for the columns chart consist of the category subsection which is the names      of all the movies. 
      
      categories:['Zootopia| 11th Highest',
      'Finding Nemo| 12th Highest',
      'The Jungle Book| 13th Highest',
      'The Lord of the Rings: The Fellowship of the Ring| 14th Highest',
      'Ice Age: Dawn of the Dinosaurs| 15th Highest',
      'Star Wars Ep. III: Revenge of the Sith| 16th Highest',
      'The Hobbit: The Battle of the Five Armies| 17th Highest',
      'The Twilight Saga: Breaking Dawn, Part 2| 18th Highest',
      'Inside Out| 19th Highest',
      'Deadpool 2| 20th Highest']

   It also consist of the series subsection that has two factors, the type column which is where the      gross profit margin percentage and profit by cost is scripted.
      
      series:[{
           type:'column',
           color:'#3FE0D0',
           name:'Gross Profit Margin Percentage',
           data:[85.0, 97.0, 85.0, 87.0, 84.0, 80.0, 89.0, 81.0, 78.0, 81.0]
       },{
           type:'column',
           color:'#008081',
           name:'Profit Percentage by Cost',
           data:[553.0, 3662.0, 574.0, 668.0, 508.0, 394.0, 793.0, 426.0, 356.0, 439.0]
       }]

In [188]:
#getting the profit of the movie
for i in new1[:21]:
    print(all_Comedy_info1.Profit[i[0]])

1748134200
1433854864
1042520711
928790543
874496193
849102856
842429370
840699645
825491110
825300000
817460782
769701857
737628605
622402853
609456552
600867516
595110670
591244673
588576929
576899282
547862775

In [189]:
#getting the revenue of the movie
for i in new1[:21]:
    print(all_Comedy_info1.Total_gross[i[0]])

2048134200
1648854864
1242520711
1123790543
964496193
1049102856
936429370
934699645
1025491110
900300000
850726024
859701857
853628605
802402853
787456552
770867516
795110670
756244673
738576929
651899282
747862775

In [190]:
#getting the cost of the movie
for i in new1[:21]:
    print(all_Comedy_info1.Buget[i[0]])

300000000
215000000
200000000
195000000
90000000
200000000
94000000
94000000
200000000
75000000
33265242
90000000
116000000
180000000
178000000
170000000
200000000
165000000
150000000
75000000
200000000

In [208]:
#getting profit percent by cost of the top 20 highest most profitable movie
new5 = []
for i in new1:
    new5.append(round(all_Comedy_info1.Profit[i[0]]/all_Comedy_info1.Buget[i[0]]
         *100,0))
new5[:11]

[583.0, 667.0, 521.0, 476.0, 972.0, 425.0, 896.0, 894.0, 413.0, 1100.0, 2457.0]

In [207]:
#getting gross profit margin percent of the top 20 highest most profitable movie
new6 = []
for i in new1:
    new6.append(round(all_Comedy_info1.Profit[i[0]]/all_Comedy_info1.Total_gross[i[0]]
         *100,0))
new6[:11]

<ipython-input-207-4ec4ba68fc6b>:4: RuntimeWarning: divide by zero encountered in longlong_scalars
  new6.append(round(all_actionadventure_info1.Profit[i[0]]/all_actionadventure_info1.Total_gross[i[0]]

[85.0, 87.0, 84.0, 83.0, 91.0, 81.0, 90.0, 90.0, 80.0, 92.0, 96.0]

Using a for loop to get the names of the highest most profitable and putting it into html code

In [203]:
for i,x in enumerate(new2[:21]):
    print("'"+new2[i]+'|',i,'th','Highest'+"',")

'Avengers: Infinity War| 0 th Highest',
'Jurassic World| 1 th Highest',
'Incredibles 2| 2 th Highest',
'Transformers: Dark of the Moon| 3 th Highest',
'Jumanji: Welcome to the Jungle| 4 th Highest',
'Rogue One: A Star Wars Story| 5 th Highest',
'Finding Nemo| 6 th Highest',
'The Lord of the Rings: The Two Towers| 7 th Highest',
'Alice in Wonderland| 8 th Highest',
'101 Dalmatians| 9 th Highest',
'Mary Poppins| 10 th Highest',
'Ice Age: Dawn of the Dinosaurs| 11 th Highest',
'Venom| 12 th Highest',
'Fantastic Beasts and Where to Find Them| 13 th Highest',
'Mission: ImpossibleâFallout| 14 th Highest',
'Guardians of the Galaxy| 15 th Highest',
'Spider-Man 2| 16 th Highest',
'Shrek Forever After| 17 th Highest',
'The Matrix Reloaded| 18 th Highest',
'Ice Age: The Meltdown| 19 th Highest',
'X-Men: Days of Future Past| 20 th Highest',

In [136]:
%%HTML
<script type="text/javascript" src="js/script.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/series-label.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="x3" display; inline-block></div>
    <div id="n3" display; inline-block></div>
    <div id="no3" display; inline-block></div>
    <div id="xo3" display; inline-block></div>
    <p class="highcharts-description">
    </p>
</figure>

In [137]:
%%js
Highcharts.chart('x3',{ // name of graph
    title:{
        text:"What Movie Is The Most Successful?"
    },
    xAxis:{
        // name of movies
        categories:['Avengers: Infinity War| 1st Highest',
                   'Jurassic World| 2nd Highest',
                   'Incredibles 2| 3rd Highest',
                   'Transformers: Dark of the Moon| 4th Highest',
                   'Jumanji: Welcome to the Jungle| 5th Highest',
                   'Rogue One: A Star Wars Story| 6th Highest',
                   'Finding Nemo| 7th Highest',
                   'The Lord of the Rings: The Two Towers| 8th Highest',
                   'Alice in Wonderland| 9th Highest',
                   '101 Dalmatians| 10th Highest'],
        crosshair:{
            // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column', // makes graph to be colunm 
        color:"#145A32",// color of colunm
        name:'Profit', // name of colunm
        // profit of each movie in integer 
        data:[1748134200,1433854864,1042520711,928790543,874496193,
              849102856,842429370,840699645,825491110,825300000]
    },{
        type:'column',// makes graph to be colunm
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[2048134200,1648854864,1242520711,1123790543,964496193,
             1049102856,936429370,934699645,1025491110,900300000]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost', // name of spline
        // cost of each movie in integer
        data:[300000000,215000000,200000000,195000000,90000000,
            200000000,94000000,94000000,200000000,75000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [138]:
%%js
Highcharts.chart('n3',{ //name of graph
        title:{
            text:""
        },
        xAxis:{
        // name of movies 
           categories:['Avengers: Infinity War| 1st Highest',
                   'Jurassic World| 2nd Highest',
                   'Incredibles 2| 3rd Highest',
                   'Transformers: Dark of the Moon| 4th Highest',
                   'Jumanji: Welcome to the Jungle| 5th Highest',
                   'Rogue One: A Star Wars Story| 6th Highest',
                   'Finding Nemo| 7th Highest',
                   'The Lord of the Rings: The Two Towers| 8th Highest',
                   'Alice in Wonderland| 9th Highest',
                   '101 Dalmatians| 10th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
           // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#87D582',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
           // Gross Profit Margin Percentage of each movie in integer
           data:[85.0, 87.0, 84.0, 83.0, 91.0, 81.0, 90.0, 90.0, 80.0, 92.0]
       },{
           type:'column',// makes graph to be colunm
           color:'#519A4C',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[583.0, 667.0, 521.0, 476.0, 972.0, 425.0, 896.0, 894.0, 413.0, 1100.0]
       }]  
    
   });

In [139]:
%%js
Highcharts.chart('no3',{ //name of graph
    title:{
        text:""
    },
    xAxis:{
        // name of movies 
        categories:['Mary Poppins| 11th Highest',
                   'Ice Age: Dawn of the Dinosaurs| 12th Highest',
                   'Venom| 13th Highest',
                   'Fantastic Beasts and Where to Find Them| 14th Highest',
                   'Mission: ImpossibleâFallout| 15th Highest',
                   'Guardians of the Galaxy| 16th Highest',
                   'Spider-Man 2| 17th Highest',
                   'Shrek Forever After| 18th Highest',
                   'The Matrix Reloaded| 19th Highest',
                   'Ice Age: The Meltdown| 20th Highest'],
        crosshair:{
             // allows two columns to be analyzed at the same time 
            enabled:true
        },
        labels:{
            enabled:false
        }
    },
    plotOptions:{
       series:{
           marker:{
               states:{
                   hover:{
                       radiusPlus:10,
                       lineWidthPlus:2
                   }
               }
           }
       } 
    },
    tooltip:{
        shared:false
    },
    states:{
        hover:{
            lineWidthPlus:10
        }
    },
    series:[{
        type:'column',// makes graph  colunm 
        color:'#145A32',// color of colunm
        name:'Profit',// name of column
        // profit of each movie in integer 
        data:[817460782,769701857,737628605,622402853,609456552,
              600867516,595110670,591244673,588576929,576899282,
              547862775]
    },{
        type:'column',// makes graph  colunm 
        color:Highcharts.getOptions().colors[1],// color of colunm
        name:'Revenue',// name of column
        // revenue of each movie in integer
        data:[850726024,859701857,853628605,802402853,787456552,
             770867516,795110670,756244673,738576929,651899282,
             747862775]
    },{
        type:'spline',// makes graph spline
        color:'gold',// color of spline
        name:'Cost',// name of spline
        // cost of each movie in integer
        data:[33265242,90000000,116000000,180000000,178000000,
             170000000,200000000,165000000,150000000,75000000,
             200000000],
        marker:{
            lineWidth: 2,
            lineColor: 'gold',
            fillColor: 'white',
            raduis:2
        }
   }]
});

In [140]:
%%js
Highcharts.chart('xo3',{//name of graph
        title:{
            text:""
        },
        xAxis:{
           // name of movies 
           categories:['Mary Poppins| 11th Highest',
                     'Ice Age: Dawn of the Dinosaurs| 12th Highest',
                     'Venom| 13th Highest',
                     'Fantastic Beasts and Where to Find Them| 14th Highest',
                     'Mission: ImpossibleâFallout| 15th Highest',
                     'Guardians of the Galaxy| 16th Highest',
                     'Spider-Man 2| 17th Highest',
                     'Shrek Forever After| 18th Highest',
                     'The Matrix Reloaded| 19th Highest',
                     'Ice Age: The Meltdown| 20th Highest'],
           crosshair:{
               // allows two columns to be analyzed at the same time 
               enabled:true
           },
           labels:{
               enabled:true
           } 
        },
       tooltip:{
            // turns digits to percentage
           valueSuffix:'%',
           shared:true
       },
       series:[{
           type:'column',// makes graph to be colunm 
           color:'#87D582',// color of colunm
           name:'Gross Profit Margin Percentage',// name of column
          // Gross Profit Margin Percentage of each movie in integer
           data:[90.0, 86.0, 78.0, 77.0, 78.0, 75.0, 78.0, 80.0, 88.0, 73.0]
       },{
           type:'column',// makes graph to be colunm 
           color:'#518A4C',// color of colunm
           name:'Profit Percentage by Cost',// name of column
           // Profit Percentage by Cost of each movie in integer
           data:[855.0, 636.0, 346.0, 342.0, 353.0, 298.0, 358.0, 392.0, 769.0, 274.0]
       }]  
    
   });

# Blueprint: Number of Tickets Sold.

This analysis objective is to axknowledge what system rating that best suit this genre, this allows the ideology of what kind of audience is drawn to this genre, to specify the audience and make them the target focus. This is the blueprint for creating the last visualization of this project, Highcharts will be used to create this graph.

__Blueprint:__
   - The graph used for this visualization is a Highchart Donut chart, it is basically a hallow pie chart which is commonly referred to as a donut charts. This pie charts also ahs an inner chart resulting in a hierachical type of visualization.
   - The first approach th this chart is the HTML section whcih is very simple, it has the div id which is where the graph is named and the style and height should be chosen.
               <div id='hraph2' style="height:700px"></div>
   - The second approach is the javascript code, it is divided into two sections the inner pie and the outer pie. The inner pie shows how much each sytem ratings occupies the most total tickets sold in percentage comparied to the total tickest sold in the whole entire parent dataframe '_all_Comedy_info1_'. The outer pie shows the individule movies in the category the amount of tickets they sold.
        - <u>__Javascript Section__</u>:
         
             -<u>_First Section_</u>: The first section is a list called data it has consist of the name of the system ratings and the percenatge of tickets sold compared to the total of tickets sold. The color and the sliced adjustments and it also has the adjustments of the size of the ring pie.
                      data:[{
                  name:'System Rating: R',
                  y:28.0,
                  sliced:true,
                  color: '#4682B4',}
            
            -<u>_Second Section_</u>: The second section is a list also called data it requires the name of all the movies, the amount of tickest they sold , the option to slice that section and the color of the slice .       
                     data:[{ 
               name: ' Avatar ' ,
               y: 213565021 ,
               sliced:true,
               selected: true,
               color:"#4682B4",}

In [215]:
# getting the number of tickets sold in the r-rated category
var = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'R':
        var.append(no_tickets[i])
len(var)

42

In [216]:
# getting the name of the r-rated movies 
var1 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'R':
        var1.append(all_Comedy_info1['Name'][i])
len(var1)

42

In [217]:
# getting the profit of thr r-rated movies
var2 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'R':
        var2.append(all_Comedy_info1['Profit'][i])
len(var2)

42

Using a for loop to put the name and the number of tickets sold in the R-rated genre in html code which will be pasted in the cell below.

In [242]:
for i,x in enumerate(range(len(var))):
    print('         },{ \n           name:',"'",var1[i],"'",','+'\n           y:',var[i],','+'\n           sliced:true,'+'\n           color:"#28B463",')

         },{
           name: ' Tangled ' ,
           y: 45113634 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Transformers: The Last Knight ' ,
           y: 46376411 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Incredibles 2 ' ,
           y: 95578516 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Rogue One: A Star Wars Story ' ,
           y: 80700220 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Spider-Man 2 ' ,
           y: 61162359 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Terminator Salvation ' ,
           y: 28114753 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Disneyâs A Christmas Carol ' ,
           y: 24285361 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Kong: Skull Island ' ,
           y: 43159389 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' WALL-E ' ,
           y: 40962156 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Rush Hour 3 ' ,
           y: 19737376 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Mission: ImpossibleâFallout ' ,
           y: 60573581 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Snow White and the Huntsman ' ,
           y: 30847827 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Terminator 3: Rise of the Machines ' ,
           y: 33312177 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Cowboys and Aliens ' ,
           y: 13541410 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Night at the Museum: Battle of the Smithsonian ' ,
           y: 30940851 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Tarzan ' ,
           y: 34476294 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Rise of the Guardians ' ,
           y: 23607762 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Armageddon ' ,
           y: 42661538 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Captain America: The First Avenger ' ,
           y: 28505367 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' G.I. Joe: Retaliation ' ,
           y: 28903131 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Megamind ' ,
           y: 24760554 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Monster Trucks ' ,
           y: 4741754 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Mission: Impossible 2 ' ,
           y: 42276040 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Venom ' ,
           y: 65663739 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Home on the Range ' ,
           y: 5883266 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Around the World in 80 Days ' ,
           y: 5538781 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' The Princess and the Frog ' ,
           y: 20845952 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' A Wrinkle in Time ' ,
           y: 10261683 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Django Unchained ' ,
           y: 34611409 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Little Fockers ' ,
           y: 23896198 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' The Expendables 2 ' ,
           y: 23998404 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' End of Days ' ,
           y: 16309767 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Son of the Mask ' ,
           y: 4609109 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' The Peanuts Movie ' ,
           y: 19237816 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Black Hawk Down ' ,
           y: 12283930 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Percy Jackson & the Olympians: The Lightning Thief ' ,
           y: 17157760 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Unstoppable ' ,
           y: 12747763 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Ben-Hur ' ,
           y: 7051511 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Cutthroat Island ' ,
           y: 1424409 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' The Haunted Mansion ' ,
           y: 11980818 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Happy Feet ' ,
           y: 29615409 ,
           sliced:true,
           color:"#28B463",
         },{
           name: ' Sherlock Gnomes ' ,
           y: 6732896 ,
           sliced:true,
           color:"#28B463",

In [219]:
# getting the number of tickets sold in the NR-rated category
var3 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'NR':
        var3.append(no_tickets[i])
len(var3)

42

In [220]:
# getting the name of the NR-rated movies 
var4 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'NR':
        var4.append(all_Comedy_info1['Name'][i])
len(var4)

42

In [221]:
# getting the profit of thr NR-rated movies
var5 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'NR':
        var5.append(all_Comedy_info1['Profit'][i])
len(var5)

42

Using a for loop to put the name and the number of tickets sold in the NR-rated genre in html code which will be pasted in the cell below.

In [245]:
for i,x in enumerate(range(len(var4))):
    print('         },{ \n           name:',"'",var4[i],"'",','+'\n           y:',var3[i],',','\n           sliced:true,'+'\n           color:"#B9F306",')

         },{
           name: ' Battleship ' ,
           y: 24113671 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Robin Hood ' ,
           y: 24804539 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' X-Men: Days of Future Past ' ,
           y: 57527906 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Transformers: Dark of the Moon ' ,
           y: 86445426 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Star Trek Beyond ' ,
           y: 25830941 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Aladdin ' ,
           y: 47633409 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Fantastic Beasts and Where to Find Them ' ,
           y: 61723296 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' 47 Ronin ' ,
           y: 11670524 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Shrek Forever After ' ,
           y: 58172667 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Pacific Rim: Uprising ' ,
           y: 22379242 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' X-Men Origins: Wolverine ' ,
           y: 28832751 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Mad Max: Fury Road ' ,
           y: 28469078 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Angels & Demons ' ,
           y: 37759680 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The BFG ' ,
           y: 15357437 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Dinosaur ' ,
           y: 27396005 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' X-Men 2 ' ,
           y: 31298118 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' How the Grinch Stole Christmas ' ,
           y: 26549339 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Monsters, Inc. ' ,
           y: 43058286 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Live Free or Die Hard ' ,
           y: 29406781 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' 300: Rise of an Empire ' ,
           y: 25444619 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Batman Forever ' ,
           y: 25886857 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Cloudy with a Chance of Meatballs ' ,
           y: 18217514 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Stepford Wives ' ,
           y: 7401690 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Expendables 3 ' ,
           y: 16112414 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Road to El Dorado ' ,
           y: 5053846 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Men in Black ' ,
           y: 45214657 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Tropic Thunder ' ,
           y: 14703481 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Contact ' ,
           y: 12761538 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Nutcracker in 3D ' ,
           y: 1574309 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Predator ' ,
           y: 12268274 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Air Force One ' ,
           y: 24251412 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Flintstones in Viva Rock Vegas ' ,
           y: 4571643 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' George Of The Jungle ' ,
           y: 13420251 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' All the King's Men ' ,
           y: 732420 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Thunderbirds ' ,
           y: 2171650 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Mr. Deeds ' ,
           y: 13174580 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Christmas with the Kranks ' ,
           y: 7420707 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Out of Time ' ,
           y: 4268448 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The Adventures of Ford Fairlane ' ,
           y: 1571030 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' America's Sweethearts ' ,
           y: 12357576 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' The River Wild ' ,
           y: 7247308 ,
           sliced:true,
           color:"#B9F306",
         },{
           name: ' Last Holiday ' ,
           y: 3334096 ,
           sliced:true,
           color:"#B9F306",

In [223]:
# getting the number of tickets sold in the pg-rated category
var6 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG':
        var6.append(no_tickets[i])
len(var6)

42

In [224]:
# getting the name of the pg-rated movies 
var7 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG':
        var7.append(all_Comedy_info1['Name'][i])
len(var7)

42

In [225]:
# getting the profit of thr pg-rated movies
var8 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG':
        var8.append(all_Comedy_info1['Profit'][i])
len(var8)

42

Using a for loop to put the name and the number of tickets sold in the PG-rated genre in html code which will be pasted in the cell below.

In [244]:
for i,x in enumerate(range(len(var7))):
    print('         },{ \n           name:',"'",var7[i],"'",','+'\n           y:',var6[i],',','\n           sliced:true,'+'\n           color:"#17A589",')

         },{
           name: ' Jurassic World ' ,
           y: 126834990 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Golden Compass ' ,
           y: 28250966 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Cars 2 ' ,
           y: 43088876 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Great Gatsby ' ,
           y: 27003109 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Edge of Tomorrow ' ,
           y: 28503174 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Waterworld ' ,
           y: 20326632 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Van Helsing ' ,
           y: 23088504 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Curious Case of Benjamin Button ' ,
           y: 25356304 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Home ' ,
           y: 29692146 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Clash of the Titans ' ,
           y: 37939607 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Oblivion ' ,
           y: 22147433 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Speed Racer ' ,
           y: 7184189 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Knight and Day ' ,
           y: 19903952 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Huntsman: Winterâs War ' ,
           y: 12703792 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' I, Robot ' ,
           y: 26817660 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Gone in 60 Seconds ' ,
           y: 17895616 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Lemony Snicket's A Series of Unfortunate Events ' ,
           y: 16381233 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Hunchback of Notre Dame ' ,
           y: 25038462 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Lord of the Rings: The Two Towers ' ,
           y: 71899973 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Pixels ' ,
           y: 18772446 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Bicentennial Man ' ,
           y: 6724675 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' 102 Dalmatians ' ,
           y: 5149351 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Last Action Hero ' ,
           y: 10561422 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Hellboy II: The Golden Army ' ,
           y: 12337543 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Swordfish ' ,
           y: 11313878 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Oceans ' ,
           y: 6675964 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Now You See Me ' ,
           y: 26366862 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' 355 ' ,
           y: 0 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Kingdom ' ,
           y: 6654585 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Alvin and the Chipmunks: The Squeakquel ' ,
           y: 34114093 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Who Framed Roger Rabbit? ' ,
           y: 27038462 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Step Brothers ' ,
           y: 9882215 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' I, Frankenstein ' ,
           y: 5736561 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Oliver Twist ' ,
           y: 2051609 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Green Mile ' ,
           y: 22361644 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Family Man ' ,
           y: 9593528 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Joy ' ,
           y: 7779543 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Goosebumps ' ,
           y: 12223486 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Internship ' ,
           y: 7205597 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Pursuit of Happyness ' ,
           y: 23639315 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' The Equalizer ' ,
           y: 14838740 ,
           sliced:true,
           color:"#17A589",
         },{
           name: ' Chain Reaction ' ,
           y: 4631487 ,
           sliced:true,
           color:"#17A589",

In [227]:
# getting the number of tickets sold in the g-rated category
var9 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'G':
        var9.append(no_tickets[i])
len(var9)

42

In [228]:
# getting the name of the g-rated movies
var10 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'G':
        var10.append(all_Comedy_info1['Name'][i])
len(var10)

42

In [229]:
# getting the profit of thr g-rated movies
var11 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'G':
        var11.append(all_Comedy_info1['Profit'][i])
len(var11)

42

Using a for loop to put the name and the number of tickets sold in the G-rated genre in html code which will be pasted in the cell below.

In [246]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var10[i],"'",','+'\n           y:',var9[i],',','\n           sliced:true,'+'\n           color:"#2C8605",')

         },{
           name: ' Where the Wild Things Are ' ,
           y: 7624897 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' A Good Day to Die Hard ' ,
           y: 23403784 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Peacemaker ' ,
           y: 4843644 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Pinocchio ' ,
           y: 2437062 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Chicken Run ' ,
           y: 17294966 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Emperor's New Groove ' ,
           y: 13022813 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Ramona and Beezus ' ,
           y: 2099519 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Wallace & Gromit: The Curse of the Were-Rabbit ' ,
           y: 14815385 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Africa Screams ' ,
           y: 1230326 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Meet the Robinsons ' ,
           y: 13025618 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Horton Hears a Who! ' ,
           y: 22846154 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' A Bug's Life ' ,
           y: 27946154 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Apple Dumpling Gang ' ,
           y: 14036257 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Muppets ' ,
           y: 12706480 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Odd Couple ' ,
           y: 3425172 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' A Shaun the Sheep Movie: Farmageddon ' ,
           y: 3315404 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Absent-Minded Professor ' ,
           y: 16848579 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Bringing Up Baby ' ,
           y: 1733751 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Alvin and the Chipmunks: Chipwrecked ' ,
           y: 26361187 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Herbie Rides Again ' ,
           y: 20881365 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Son of Flubber ' ,
           y: 14370257 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Love Bug ' ,
           y: 28509358 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' A Night at the Opera ' ,
           y: 2677427 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Babe ' ,
           y: 31127567 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Mr. Magorium's Wonder Emporium ' ,
           y: 5344205 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Court Jester ' ,
           y: 1628761 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' 101 Dalmatians ' ,
           y: 69253846 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Garfield: The Movie ' ,
           y: 876923 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Freaky Friday ' ,
           y: 16007273 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Return of the Pink Panthe ' ,
           y: 12821987 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Yogi Bear ' ,
           y: 15920429 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Swan Princess ' ,
           y: 1324819 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Sword in the Stone ' ,
           y: 14423806 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Willy Wonka & the Chocolate Factory ' ,
           y: 2234988 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Mary Poppins ' ,
           y: 65440463 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Pinocchio ' ,
           y: 4621816 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Winnie the Pooh ' ,
           y: 3836264 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' 102 Dalmatians ' ,
           y: 21564252 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Hannah Montana: The Movie ' ,
           y: 11965021 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' The Land Before Time ' ,
           y: 14474272 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' My Fair Lady (1964) ' ,
           y: 46105394 ,
           sliced:true,
           color:"#2C8605",
         },{
           name: ' Funny Girl ' ,
           y: 34232538 ,
           sliced:true,
           color:"#2C8605",

In [231]:
# getting the number of tickets sold in the pg13-rated category
var12 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG-13':
        var12.append(no_tickets[i])
len(var12)

42

In [232]:
# getting the name of the pg13-rated movies
var13 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG-13':
        var13.append(all_Comedy_info1['Name'][i])
len(var13)

42

In [233]:
# getting the profit of thr pg13-rated movies
var14 = []
for i,x in enumerate(all_Comedy_info1.System_ratings):
    if x == 'PG-13':
        var14.append(all_Comedy_info1['Profit'][i])
len(var14)

42

Using a for loop to put the name and the number of tickets sold in the PG-13-rated genre in html code which will be pasted in the cell below.

In [243]:
for i,x in enumerate(range(len(var10))):
    print('         },{ \n           name:',"'",var13[i],"'",','+'\n           y:',var12[i],',','\n           sliced:true,'+'\n           color:"#0B5345",')

         },{
           name: ' Avengers: Infinity War ' ,
           y: 157548785 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' John Carter ' ,
           y: 21752162 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Alice in Wonderland ' ,
           y: 78883932 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Blade Runner 2049 ' ,
           y: 19950570 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Guardians of the Galaxy ' ,
           y: 59297501 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Alita: Battle Angel ' ,
           y: 30998157 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Matrix Reloaded ' ,
           y: 56813610 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Teenage Mutant Ninja Turtles: Out of the Shadows ' ,
           y: 18871413 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Ant-Man and the Wasp ' ,
           y: 47934205 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' After Earth ' ,
           y: 19346128 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Total Recall ' ,
           y: 16296622 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The 13th Warrior ' ,
           y: 4746069 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' San Andreas ' ,
           y: 35096811 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Campaign ' ,
           y: 8069827 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Rise of the Planet of the Apes ' ,
           y: 36229708 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Hotel Transylvania ' ,
           y: 29115832 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Total Recall ' ,
           y: 16296622 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Public Enemies ' ,
           y: 16329439 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Tourist ' ,
           y: 21440875 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Finding Nemo ' ,
           y: 72033028 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Rise of the Planet of the Apes ' ,
           y: 36229708 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Alamo ' ,
           y: 1839336 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Jumanji: Welcome to the Jungle ' ,
           y: 74192015 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           y: 66130912 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Interpreter ' ,
           y: 12519526 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Fast & Furious ' ,
           y: 27928020 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Hotel Transylvania ' ,
           y: 29115832 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' I Now Pronounce You Chuck and Larry ' ,
           y: 14285266 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Spirit: Stallion of the Cimarron ' ,
           y: 8193485 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Battlefield Earth: A Saga of the Year 3000 ' ,
           y: 2286589 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Ice Age: The Meltdown ' ,
           y: 50146099 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Unbreakable ' ,
           y: 19084549 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Doctor Dolittle ' ,
           y: 22627431 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Escape Plan ' ,
           y: 7979690 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Money Train ' ,
           y: 5940326 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Unbroken ' ,
           y: 12579063 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Primary Colors ' ,
           y: 3001383 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' 2 Guns ' ,
           y: 10191770 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' London Has Fallen ' ,
           y: 15014930 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' Jack Reacher: Never Go Back ' ,
           y: 12303576 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Jackal ' ,
           y: 12258226 ,
           sliced:true,
           color:"#0B5345",
         },{
           name: ' The Legend of Bagger Vance ' ,
           y: 3018114 ,
           sliced:true,
           color:"#0B5345",

In [235]:
# putting all the number of tickest that each movie made in a list
ttl = var3+var6+var9+var12+var
ttl

[24113671,
 24804539,
 57527906,
 86445426,
 25830941,
 47633409,
 61723296,
 11670524,
 58172667,
 22379242,
 28832751,
 28469078,
 37759680,
 15357437,
 27396005,
 31298118,
 26549339,
 43058286,
 29406781,
 25444619,
 25886857,
 18217514,
 7401690,
 16112414,
 5053846,
 45214657,
 14703481,
 12761538,
 1574309,
 12268274,
 24251412,
 4571643,
 13420251,
 732420,
 2171650,
 13174580,
 7420707,
 4268448,
 1571030,
 12357576,
 7247308,
 3334096,
 126834990,
 28250966,
 43088876,
 27003109,
 28503174,
 20326632,
 23088504,
 25356304,
 29692146,
 37939607,
 22147433,
 7184189,
 19903952,
 12703792,
 26817660,
 17895616,
 16381233,
 25038462,
 71899973,
 18772446,
 6724675,
 5149351,
 10561422,
 12337543,
 11313878,
 6675964,
 26366862,
 0,
 6654585,
 34114093,
 27038462,
 9882215,
 5736561,
 2051609,
 22361644,
 9593528,
 7779543,
 12223486,
 7205597,
 23639315,
 14838740,
 4631487,
 7624897,
 23403784,
 4843644,
 2437062,
 17294966,
 13022813,
 2099519,
 14815385,
 1230326,
 13025618,
 22846154,
 27946154,
 14036257,
 12706480,
 3425172,
 3315404,
 16848579,
 1733751,
 26361187,
 20881365,
 14370257,
 28509358,
 2677427,
 31127567,
 5344205,
 1628761,
 69253846,
 876923,
 16007273,
 12821987,
 15920429,
 1324819,
 14423806,
 2234988,
 65440463,
 4621816,
 3836264,
 21564252,
 11965021,
 14474272,
 46105394,
 34232538,
 157548785,
 21752162,
 78883932,
 19950570,
 59297501,
 30998157,
 56813610,
 18871413,
 47934205,
 19346128,
 16296622,
 4746069,
 35096811,
 8069827,
 36229708,
 29115832,
 16296622,
 16329439,
 21440875,
 72033028,
 36229708,
 1839336,
 74192015,
 66130912,
 12519526,
 27928020,
 29115832,
 14285266,
 8193485,
 2286589,
 50146099,
 19084549,
 22627431,
 7979690,
 5940326,
 12579063,
 3001383,
 10191770,
 15014930,
 12303576,
 12258226,
 3018114,
 45113634,
 46376411,
 95578516,
 80700220,
 61162359,
 28114753,
 24285361,
 43159389,
 40962156,
 19737376,
 60573581,
 30847827,
 33312177,
 13541410,
 30940851,
 34476294,
 23607762,
 42661538,
 28505367,
 28903131,
 24760554,
 4741754,
 42276040,
 65663739,
 5883266,
 5538781,
 20845952,
 10261683,
 34611409,
 23896198,
 23998404,
 16309767,
 4609109,
 19237816,
 12283930,
 17157760,
 12747763,
 7051511,
 1424409,
 11980818,
 29615409,
 6732896]

In [236]:
# adding all the number of tickects ech movie made
tt2 = 0
for i in ttl:
    tt2+=i

In [237]:
# average of no tickets of R system rating
v = 0
for i in var:
    v+=i
round(v/tt2*100,0)

24.0

In [238]:
# average of no tickets of NR system rating
v1 = 0
for i in var3:
    v1+=i
round(v1/tt2*100,0)

20.0

In [239]:
# average of no tickets of PG system rating
v2 = 0
for i in var6:
    v2+=i
round(v2/tt2*100,0)

18.0

In [240]:
# average of no tickets of G system rating
v3 = 0
for i in var9:
    v3+=i
round(v3/tt2*100,0)

13.0

In [241]:
# average of no tickets of PG13 system rating
v4= 0
for i in var12:
    v4+=i
round(v4/tt2*100,0)

24.0

In [1]:
%%html
<script src="http://code.highcharts.com/highchart.js"></script>
<div id='hraph3' style="height:700px"></div>

In [2]:
%%js
var chart = new Highcharts.Chart({
    chart:{
        renderTo:'hraph3'//name of graph 
    },
    title:{
        text:'Number of Tickets Sold'
    },
    subtitle:{
        text:'Comedy Genre'
    },
    series:[{
        type:'pie',// makes the graph pie 
        name: 'Percentage of Tickets Sold',
        tooltip:{
            // turns digits to percentage
            valueSuffix:'%'
        },
        shadow: true,
        data:[{
            name:'System Rating: R',// name of category
            y:24.0,// amount of tickets sold in percentage
            sliced:true,
            color: '#28B463',// color of section
        },{
            name:'System Rating: PG-13',// name of category
            y:24.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#0B5345',// color of section
        },{
            name:'System Rating: PG',// name of category
            y:18.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#17A589',// color of section
        },{
            name:'System Rating: NR',// name of category
            y:20.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#B9F306',// color of section
        },{
            name:'System Rating: G',// name of category
            y:13.0,// amount of tickets sold in percentage
            sliced:true,
            color:'#2C8605',// color of section
        }],
        innerSize:'80%',// size of inner pie
        size:'83%'// size of outer pie
       },{
        type:'pie',
        shadow: true,
        dataLabels: false,
        name: 'No. of Tickets Sold',
        data:[{ 
           name: ' Tangled ' ,
           y: 45113634 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Transformers: The Last Knight ' ,
           y: 46376411 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Incredibles 2 ' ,
           y: 95578516 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Rogue One: A Star Wars Story ' ,
           y: 80700220 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Spider-Man 2 ' ,
           y: 61162359 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Terminator Salvation ' ,
           y: 28114753 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Disneyâs A Christmas Carol ' ,
           y: 24285361 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Kong: Skull Island ' ,
           y: 43159389 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' WALL-E ' ,
           y: 40962156 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Rush Hour 3 ' ,
           y: 19737376 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Mission: ImpossibleâFallout ' ,
           y: 60573581 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Snow White and the Huntsman ' ,
           y: 30847827 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Terminator 3: Rise of the Machines ' ,
           y: 33312177 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Cowboys and Aliens ' ,
           y: 13541410 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Night at the Museum: Battle of the Smithsonian ' ,
           y: 30940851 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Tarzan ' ,
           y: 34476294 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Rise of the Guardians ' ,
           y: 23607762 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Armageddon ' ,
           y: 42661538 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Captain America: The First Avenger ' ,
           y: 28505367 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' G.I. Joe: Retaliation ' ,
           y: 28903131 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Megamind ' ,
           y: 24760554 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Monster Trucks ' ,
           y: 4741754 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Mission: Impossible 2 ' ,
           y: 42276040 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Venom ' ,
           y: 65663739 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Home on the Range ' ,
           y: 5883266 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Around the World in 80 Days ' ,
           y: 5538781 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' The Princess and the Frog ' ,
           y: 20845952 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' A Wrinkle in Time ' ,
           y: 10261683 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Django Unchained ' ,
           y: 34611409 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Little Fockers ' ,
           y: 23896198 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' The Expendables 2 ' ,
           y: 23998404 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' End of Days ' ,
           y: 16309767 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Son of the Mask ' ,
           y: 4609109 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' The Peanuts Movie ' ,
           y: 19237816 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Black Hawk Down ' ,
           y: 12283930 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Percy Jackson & the Olympians: The Lightning Thief ' ,
           y: 17157760 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Unstoppable ' ,
           y: 12747763 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Ben-Hur ' ,
           y: 7051511 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Cutthroat Island ' ,
           y: 1424409 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' The Haunted Mansion ' ,
           y: 11980818 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Happy Feet ' ,
           y: 29615409 ,
           sliced:true,
           color:"#28B463",
         },{ 
           name: ' Sherlock Gnomes ' ,
           y: 6732896 ,
           sliced:false,
           color:"#28B463",
         },{ 
           name: ' Avengers: Infinity War ' ,
           y: 157548785 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' John Carter ' ,
           y: 21752162 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Alice in Wonderland ' ,
           y: 78883932 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Blade Runner 2049 ' ,
           y: 19950570 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Guardians of the Galaxy ' ,
           y: 59297501 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Alita: Battle Angel ' ,
           y: 30998157 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' The Matrix Reloaded ' ,
           y: 56813610 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Teenage Mutant Ninja Turtles: Out of the Shadows ' ,
           y: 18871413 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Ant-Man and the Wasp ' ,
           y: 47934205 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' After Earth ' ,
           y: 19346128 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Total Recall ' ,
           y: 16296622 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' The 13th Warrior ' ,
           y: 4746069 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' San Andreas ' ,
           y: 35096811 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' The Campaign ' ,
           y: 8069827 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Rise of the Planet of the Apes ' ,
           y: 36229708 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Hotel Transylvania ' ,
           y: 29115832 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Total Recall ' ,
           y: 16296622 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Public Enemies ' ,
           y: 16329439 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' The Tourist ' ,
           y: 21440875 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Finding Nemo ' ,
           y: 72033028 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Rise of the Planet of the Apes ' ,
           y: 36229708 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' The Alamo ' ,
           y: 1839336 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Jumanji: Welcome to the Jungle ' ,
           y: 74192015 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Ice Age: Dawn of the Dinosaurs ' ,
           y: 66130912 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' The Interpreter ' ,
           y: 12519526 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Fast & Furious ' ,
           y: 27928020 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Hotel Transylvania ' ,
           y: 29115832 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' I Now Pronounce You Chuck and Larry ' ,
           y: 14285266 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Spirit: Stallion of the Cimarron ' ,
           y: 8193485 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Battlefield Earth: A Saga of the Year 3000 ' ,
           y: 2286589 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Ice Age: The Meltdown ' ,
           y: 50146099 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Unbreakable ' ,
           y: 19084549 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Doctor Dolittle ' ,
           y: 22627431 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Escape Plan ' ,
           y: 7979690 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Money Train ' ,
           y: 5940326 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Unbroken ' ,
           y: 12579063 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Primary Colors ' ,
           y: 3001383 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' 2 Guns ' ,
           y: 10191770 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' London Has Fallen ' ,
           y: 15014930 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' Jack Reacher: Never Go Back ' ,
           y: 12303576 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' The Jackal ' ,
           y: 12258226 , 
           sliced:true,
           color:"#0B5345",
         },{ 
           name: ' The Legend of Bagger Vance ' ,
           y: 3018114 , 
           sliced:false,
           color:"#0B5345",
         },{ 
           name: ' Jurassic World ' ,
           y: 126834990 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Golden Compass ' ,
           y: 28250966 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Cars 2 ' ,
           y: 43088876 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Great Gatsby ' ,
           y: 27003109 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Edge of Tomorrow ' ,
           y: 28503174 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Waterworld ' ,
           y: 20326632 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Van Helsing ' ,
           y: 23088504 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Curious Case of Benjamin Button ' ,
           y: 25356304 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Home ' ,
           y: 29692146 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Clash of the Titans ' ,
           y: 37939607 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Oblivion ' ,
           y: 22147433 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Speed Racer ' ,
           y: 7184189 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Knight and Day ' ,
           y: 19903952 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Huntsman: Winterâs War ' ,
           y: 12703792 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' I, Robot ' ,
           y: 26817660 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Gone in 60 Seconds ' ,
           y: 17895616 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Lemony Snicket\'s A Series of Unfortunate Events ' ,
           y: 16381233 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Hunchback of Notre Dame ' ,
           y: 25038462 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' The Lord of the Rings: The Two Towers ' ,
           y: 71899973 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Pixels ' ,
           y: 18772446 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Bicentennial Man ' ,
           y: 6724675 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' 102 Dalmatians ' ,
           y: 5149351 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Last Action Hero ' ,
           y: 10561422 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Hellboy II: The Golden Army ' ,
           y: 12337543 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Swordfish ' ,
           y: 11313878 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Oceans ' ,
           y: 6675964 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Now You See Me ' ,
           y: 26366862 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' 355 ' ,
           y: 0 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' The Kingdom ' ,
           y: 6654585 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Alvin and the Chipmunks: The Squeakquel ' ,
           y: 34114093 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Who Framed Roger Rabbit? ' ,
           y: 27038462 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Step Brothers ' ,
           y: 9882215 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' I, Frankenstein ' ,
           y: 5736561 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Oliver Twist ' ,
           y: 2051609 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' The Green Mile ' ,
           y: 22361644 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Family Man ' ,
           y: 9593528 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' Joy ' ,
           y: 7779543 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Goosebumps ' ,
           y: 12223486 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' The Internship ' ,
           y: 7205597 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' The Pursuit of Happyness ' ,
           y: 23639315 , 
           sliced:false,
           color:"#17A589",
         },{ 
           name: ' The Equalizer ' ,
           y: 14838740 , 
           sliced:true,
           color:"#17A589",
         },{ 
           name: ' Chain Reaction ' ,
           y: 4631487 , 
           sliced:false,
           color:"#17A589",
          },{ 
           name: ' Battleship ' ,
           y: 24113671 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Robin Hood ' ,
           y: 24804539 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' X-Men: Days of Future Past ' ,
           y: 57527906 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Transformers: Dark of the Moon ' ,
           y: 86445426 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Star Trek Beyond ' ,
           y: 25830941 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Aladdin ' ,
           y: 47633409 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Fantastic Beasts and Where to Find Them ' ,
           y: 61723296 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' 47 Ronin ' ,
           y: 11670524 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Shrek Forever After ' ,
           y: 58172667 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Pacific Rim: Uprising ' ,
           y: 22379242 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' X-Men Origins: Wolverine ' ,
           y: 28832751 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Mad Max: Fury Road ' ,
           y: 28469078 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Angels & Demons ' ,
           y: 37759680 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' The BFG ' ,
           y: 15357437 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Dinosaur ' ,
           y: 27396005 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' X-Men 2 ' ,
           y: 31298118 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' How the Grinch Stole Christmas ' ,
           y: 26549339 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Monsters, Inc. ' ,
           y: 43058286 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Live Free or Die Hard ' ,
           y: 29406781 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' 300: Rise of an Empire ' ,
           y: 25444619 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Batman Forever ' ,
           y: 25886857 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Cloudy with a Chance of Meatballs ' ,
           y: 18217514 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' The Stepford Wives ' ,
           y: 7401690 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' The Expendables 3 ' ,
           y: 16112414 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' The Road to El Dorado ' ,
           y: 5053846 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Men in Black ' ,
           y: 45214657 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Tropic Thunder ' ,
           y: 14703481 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Contact ' ,
           y: 12761538 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' The Nutcracker in 3D ' ,
           y: 1574309 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' The Predator ' ,
           y: 12268274 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Air Force One ' ,
           y: 24251412 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' The Flintstones in Viva Rock Vegas ' ,
           y: 4571643 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' George Of The Jungle ' ,
           y: 13420251 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' All the King\'s Men ' ,
           y: 732420 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Thunderbirds ' ,
           y: 2171650 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Mr. Deeds ' ,
           y: 13174580 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' Christmas with the Kranks ' ,
           y: 7420707 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Out of Time ' ,
           y: 4268448 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' The Adventures of Ford Fairlane ' ,
           y: 1571030 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' America\'s Sweethearts ' ,
           y: 12357576 , 
           sliced:false,
           color:"#B9F306",
         },{ 
           name: ' The River Wild ' ,
           y: 7247308 , 
           sliced:true,
           color:"#B9F306",
         },{ 
           name: ' Last Holiday ' ,
           y: 3334096 , 
           sliced:false,
           color:"#B9F306",
        },{ 
           name: ' Where the Wild Things Are ' ,
           y: 7624897 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' A Good Day to Die Hard ' ,
           y: 23403784 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' The Peacemaker ' ,
           y: 4843644 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Pinocchio ' ,
           y: 2437062 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Chicken Run ' ,
           y: 17294966 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Emperor\'s New Groove ' ,
           y: 13022813 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Ramona and Beezus ' ,
           y: 2099519 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Wallace & Gromit: The Curse of the Were-Rabbit ' ,
           y: 14815385 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Africa Screams ' ,
           y: 1230326 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Meet the Robinsons ' ,
           y: 13025618 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Horton Hears a Who! ' ,
           y: 22846154 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' A Bug\'s Life ' ,
           y: 27946154 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' The Apple Dumpling Gang ' ,
           y: 14036257 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Muppets ' ,
           y: 12706480 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' The Odd Couple ' ,
           y: 3425172 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' A Shaun the Sheep Movie: Farmageddon ' ,
           y: 3315404 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' The Absent-Minded Professor ' ,
           y: 16848579 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Bringing Up Baby ' ,
           y: 1733751 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Alvin and the Chipmunks: Chipwrecked ' ,
           y: 26361187 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Herbie Rides Again ' ,
           y: 20881365 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Son of Flubber ' ,
           y: 14370257 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Love Bug ' ,
           y: 28509358 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' A Night at the Opera ' ,
           y: 2677427 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Babe ' ,
           y: 31127567 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Mr. Magorium\'s Wonder Emporium ' ,
           y: 5344205 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Court Jester ' ,
           y: 1628761 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' 101 Dalmatians ' ,
           y: 69253846 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Garfield: The Movie ' ,
           y: 876923 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Freaky Friday ' ,
           y: 16007273 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Return of the Pink Panthe ' ,
           y: 12821987 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Yogi Bear ' ,
           y: 15920429 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Swan Princess ' ,
           y: 1324819 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' The Sword in the Stone ' ,
           y: 14423806 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Willy Wonka & the Chocolate Factory ' ,
           y: 2234988 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Mary Poppins ' ,
           y: 65440463 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Pinocchio ' ,
           y: 4621816 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Winnie the Pooh ' ,
           y: 3836264 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' 102 Dalmatians ' ,
           y: 21564252 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' Hannah Montana: The Movie ' ,
           y: 11965021 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' The Land Before Time ' ,
           y: 14474272 , 
           sliced:false,
           color:"#2C8605",
         },{ 
           name: ' My Fair Lady (1964) ' ,
           y: 46105394 , 
           sliced:true,
           color:"#2C8605",
         },{ 
           name: ' Funny Girl ' ,
           y: 34232538 , 
           sliced:false,
           color:"#2C8605"
        }],
    innerSize:'93%',// size of inner pie
    size:'100%'// size of outer pie
    }]
});