In [1]:
import pandas as pd

In [2]:
%store -r raw_info

In [3]:
raw_info

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,10/13/2014,221900.0,3,1.00,1180,5650,1.0,NaN,0.0,...,7,1180,0.0,1955,0.0,98178,47.5112,-122.257,1340,5650
1,6414100192,12/9/2014,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,7,2170,400.0,1951,1991.0,98125,47.7210,-122.319,1690,7639
2,5631500400,2/25/2015,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,6,770,0.0,1933,NaN,98028,47.7379,-122.233,2720,8062
3,2487200875,12/9/2014,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,7,1050,910.0,1965,0.0,98136,47.5208,-122.393,1360,5000
4,1954400510,2/18/2015,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,8,1680,0.0,1987,0.0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,263000018,5/21/2014,360000.0,3,2.50,1530,1131,3.0,0.0,0.0,...,8,1530,0.0,2009,0.0,98103,47.6993,-122.346,1530,1509
21593,6600060120,2/23/2015,400000.0,4,2.50,2310,5813,2.0,0.0,0.0,...,8,2310,0.0,2014,0.0,98146,47.5107,-122.362,1830,7200
21594,1523300141,6/23/2014,402101.0,2,0.75,1020,1350,2.0,0.0,0.0,...,7,1020,0.0,2009,0.0,98144,47.5944,-122.299,1020,2007
21595,291310100,1/16/2015,400000.0,3,2.50,1600,2388,2.0,NaN,0.0,...,8,1600,0.0,2004,0.0,98027,47.5345,-122.069,1410,1287
21596,1523300157,10/15/2014,325000.0,2,0.75,1020,1076,2.0,0.0,0.0,...,7,1020,0.0,2008,0.0,98144,47.5941,-122.299,1020,1357

In [4]:
raw_info['yr_renovated'] = raw_info['yr_renovated'].fillna(0)

In [5]:
locationzip =raw_info.zipcode
locationzip

0        98178
1        98125
2        98028
3        98136
4        98074
         ...
21592    98103
21593    98146
21594    98144
21595    98027
21596    98144
Name: zipcode, Length: 21597, dtype: int64

In [6]:
select= [98178,98199,98106,98072,98075,98019,98116,98106,98178,98108,98199,98056,98136,98065,98040,98029,
98006,98024,98106,98059,98034,98118,98056,98029,98119,98199,98199,98040,98034,98006,98006,98146,
98106,98072,98052,98126,98108,98199,98059,98118,98118,98122,98027,98027,98004,98199]

In [7]:
index2 = []
for x,i in enumerate(raw_info.zipcode):
        if i == select[0] : index2.append(x)
        elif i == select[1] : index2.append(x)
        elif i == select[2] : index2.append(x)
        elif i == select[3] : index2.append(x)
        elif i == select[4] : index2.append(x)
        elif i == select[5] : index2.append(x)
        elif i == select[6] : index2.append(x)
        elif i == select[7] : index2.append(x)
        elif i == select[8] : index2.append(x)
        elif i == select[9] : index2.append(x)
        elif i == select[10] : index2.append(x)
        elif i == select[11] : index2.append(x)
        elif i == select[12] : index2.append(x)
        elif i == select[13] : index2.append(x)
        elif i == select[14] : index2.append(x)
        elif i == select[15] : index2.append(x)
        elif i == select[16] : index2.append(x)
        elif i == select[17] : index2.append(x)
        elif i == select[18] : index2.append(x)
        elif i == select[19] : index2.append(x)
        elif i == select[20] : index2.append(x)
        elif i == select[21]: index2.append(x)
        elif i == select[22] : index2.append(x)
        elif i == select[23] : index2.append(x)
        elif i == select[24] : index2.append(x)
        elif i == select[25] : index2.append(x)
        elif i == select[26] : index2.append(x)
        elif i == select[27] : index2.append(x)
        elif i == select[28] : index2.append(x)
        elif i == select[29] : index2.append(x)
        elif i == select[30] : index2.append(x)
        elif i == select[31] : index2.append(x)
        elif i == select[32] : index2.append(x)
        elif i == select[33] : index2.append(x)
        elif i == select[34] : index2.append(x)
        elif i == select[35] : index2.append(x)
        elif i == select[36] : index2.append(x)
        elif i == select[37] : index2.append(x)
        elif i == select[38] : index2.append(x)
        elif i == select[39] : index2.append(x)
        elif i == select[40] : index2.append(x)
        elif i == select[41] : index2.append(x)
        elif i == select[42] : index2.append(x)
        elif i == select[43] : index2.append(x)
        elif i == select[44] : index2.append(x)
        elif i == select[45] : index2.append(x)
len(index2)
%store index2

Stored 'index2' (list)

In [8]:
id = []
for i in index2:
    id.append(raw_info.id[i])
len(id)

8349

In [9]:
date = []
for i in index2:
    date.append(raw_info.date[i])
len(date)

8349

In [10]:
bedrooms = []
for i in index2:
    bedrooms.append(raw_info.bedrooms[i])
len(bedrooms)

8349

In [11]:
bathrooms = []
for i in index2:
    bathrooms.append(raw_info.bathrooms[i])
len(bathrooms)

8349

In [12]:
sqft_living = []
for i in index2:
    sqft_living.append(raw_info.sqft_living[i])
len(sqft_living)

8349

In [13]:
sqft_lot = []
for i in index2:
    sqft_lot.append(raw_info.sqft_lot[i])
len(sqft_lot)

8349

In [14]:
floors = []
for i in index2:
    floors.append(raw_info.floors[i])
len(floors)

8349

In [15]:
yr_built = []
for i in index2:
    yr_built.append(raw_info.yr_built[i])
len(yr_built)

8349

In [16]:
yr_renovated = []
for i in index2:
    yr_renovated.append(raw_info.yr_renovated[i])
len(yr_renovated)

8349

In [17]:
condition = []
for i in index2:
    condition.append(raw_info.condition[i])
len(condition)

8349

In [18]:
g = []
for i in range(8349):
    g.append('Quantile')

In [19]:
x = []
for i in range(8349):
    x.append('Regression')

In [20]:
w = []
for i in range(8349):
    w.append('Weighted')

In [21]:
a = []
for i in range(8349):
    a.append('Average')

In [22]:
f = []
for i in range(8349):
    f.append('Predictions')

In [23]:
house_info = pd.DataFrame({'Id':id,'Date':date,'Bedrooms':bedrooms, 'Bathrooms':bathrooms, 
                           'Floors':floors, 'Year Built':yr_built, 'Year Renoveted':yr_renovated,
            'Condition':condition, 'Sqft_living':sqft_living,'Sqft_lot':sqft_lot,
                          })
house_info

,Id,Date,Bedrooms,Bathrooms,Floors,Year Built,Year Renoveted,Condition,Sqft_living,Sqft_lot
0,7129300520,10/13/2014,3,1.0,1.0,1955,0.0,3,1180,5650
1,2487200875,12/9/2014,4,3.0,1.0,1965,0.0,5,1960,5000
2,2414600126,4/15/2015,3,1.0,1.0,1960,0.0,3,1780,7470
3,9297300055,1/24/2015,4,3.0,2.0,1979,0.0,3,2950,5000
4,1875500060,7/31/2014,3,2.0,2.0,1994,0.0,3,1890,14040
...,...,...,...,...,...,...,...,...,...,...
8344,3448900210,10/14/2014,4,2.5,2.0,2014,0.0,3,2520,6023
8345,7936000429,3/26/2015,4,3.5,2.0,2009,0.0,3,3510,7200
8346,2997800021,2/19/2015,3,2.5,2.0,2008,0.0,3,1310,1294
8347,6600060120,2/23/2015,4,2.5,2.0,2014,0.0,3,2310,5813
8348,291310100,1/16/2015,3,2.5,2.0,2004,0.0,3,1600,2388

In [24]:
%store -r Quantile_Regression_Prediction8 
%store -r Quantile_Regression_Prediction7 
%store -r Quantile_Regression_Prediction5 
%store -r Quantile_Regression_Prediction4
%store -r Quantile_Regression_Prediction3
%store -r Quantile_Regression_Prediction2
%store -r Quantile_Regression_Prediction1
%store -r Quantile_Regression_Prediction
%store -r Weighted_Average_Prediction8 
%store -r Weighted_Average_Prediction7 
%store -r Weighted_Average_Prediction5 
%store -r Weighted_Average_Prediction4
%store -r Weighted_Average_Prediction3
%store -r Weighted_Average_Prediction2
%store -r Weighted_Average_Prediction1
%store -r Weighted_Average_Prediction
%store -r price
%store -r house_info

In [25]:
East_prediction_sqft_lot= Quantile_Regression_Prediction8
East_prediction_sqft_lot

      Amount_of_sqft_lot Quantile_Regression_Prediction Actual Price
0                   5650            $201,558 - $939,876     $221,900
1                   5000            $201,558 - $939,876     $604,000
2                   7470            $201,558 - $939,876     $229,500
3                   5000            $201,558 - $939,876     $650,000
4                  14040            $201,558 - $939,876     $395,000
...                  ...                            ...          ...
8344                6023            $201,558 - $939,876     $610,685
8345                7200            $201,558 - $939,876   $1,010,000
8346                1294            $201,558 - $939,876     $475,000
8347                5813            $201,558 - $939,876     $400,000
8348                2388            $201,558 - $939,876     $400,000

[8349 rows x 3 columns]

In [26]:
East_Weighted_Average_sqft_lot= Weighted_Average_Prediction8 
East_Weighted_Average_sqft_lot

      Amount_of_sqft_lot Weighted_Average_Prediction Actual Price
0                   5650                    $528,685     $221,900
1                   5000                    $528,685     $604,000
2                   7470                    $528,685     $229,500
3                   5000                    $528,685     $650,000
4                  14040                    $528,685     $395,000
...                  ...                         ...          ...
8344                6023                    $610,000     $610,685
8345                7200                    $318,500   $1,010,000
8346                1294                    $595,000     $475,000
8347                5813                    $912,000     $400,000
8348                2388                    $580,000     $400,000

[8349 rows x 3 columns]

In [27]:
East_prediction_sqft_living= Quantile_Regression_Prediction7
East_prediction_sqft_living

      Amount_of_sqft_Living Quantile_Regression_Prediction Actual Price
0                      1180             $336,638- $724,824     $221,900
1                      1960             $336,638- $724,824     $604,000
2                      1780             $336,638- $724,824     $229,500
3                      2950             $336,638- $724,824     $650,000
4                      1890             $336,638- $724,824     $395,000
...                     ...                            ...          ...
8344                   2520             $336,638- $724,824     $610,685
8345                   3510           $710,003- $1,514,226   $1,010,000
8346                   1310             $336,638- $724,824     $475,000
8347                   2310             $336,638- $724,824     $400,000
8348                   1600             $336,638- $724,824     $400,000

[8349 rows x 3 columns]

In [28]:
East_Weighted_Average_Amount_of_sqft_Living = Weighted_Average_Prediction7 
East_Weighted_Average_Amount_of_sqft_Living

      Amount_of_sqft_Living Weighted_Average_Prediction Actual Price
0                      1180                    $387,403     $221,900
1                      1960                    $470,676     $604,000
2                      1780                    $488,822     $229,500
3                      2950                    $765,034     $650,000
4                      1890                    $532,858     $395,000
...                     ...                         ...          ...
8344                   2520                    $656,487     $610,685
8345                   3510                    $872,158   $1,010,000
8346                   1310                    $363,025     $475,000
8347                   2310                    $678,408     $400,000
8348                   1600                    $451,349     $400,000

[8349 rows x 3 columns]

In [29]:
East_prediction_Condition_Level= Quantile_Regression_Prediction5
East_prediction_Condition_Level

      Condition Level Quantile_Regression_Prediction Actual Price
0                   3            $299,999 - $990,999     $221,900
1                   5            $299,999 - $990,999     $604,000
2                   3            $299,999 - $990,999     $229,500
3                   3            $299,999 - $990,999     $650,000
4                   3            $299,999 - $990,999     $395,000
...               ...                            ...          ...
8344                3            $299,999 - $990,999     $610,685
8345                3            $299,999 - $990,999   $1,010,000
8346                3            $299,999 - $990,999     $475,000
8347                3            $299,999 - $990,999     $400,000
8348                3            $299,999 - $990,999     $400,000

[8349 rows x 3 columns]

In [30]:
East_Weighted_Average_Condition_Level = Weighted_Average_Prediction5
East_Weighted_Average_Condition_Level

      Condition Level Weighted_Average_Prediction Actual Price
0                   3                    $606,899     $221,900
1                   5                    $647,621     $604,000
2                   3                    $606,899     $229,500
3                   3                    $606,899     $650,000
4                   3                    $606,899     $395,000
...               ...                         ...          ...
8344                3                    $606,899     $610,685
8345                3                    $606,899   $1,010,000
8346                3                    $606,899     $475,000
8347                3                    $606,899     $400,000
8348                3                    $606,899     $400,000

[8349 rows x 3 columns]

In [31]:
East_prediction_Year_Renoveted=Quantile_Regression_Prediction4
East_prediction_Year_Renoveted

      Year Renoveted Quantile_Regression_Prediction Actual Price
0                0.0          $263,411 - $1,322,038     $221,900
1                0.0          $263,411 - $1,322,038     $604,000
2                0.0          $263,411 - $1,322,038     $229,500
3                0.0          $263,411 - $1,322,038     $650,000
4                0.0          $263,411 - $1,322,038     $395,000
...              ...                            ...          ...
8344             0.0          $263,411 - $1,322,038     $610,685
8345             0.0          $263,411 - $1,322,038   $1,010,000
8346             0.0          $263,411 - $1,322,038     $475,000
8347             0.0          $263,411 - $1,322,038     $400,000
8348             0.0          $263,411 - $1,322,038     $400,000

[8349 rows x 3 columns]

In [32]:
East_Weighted_Average_Year_Renoveted = Weighted_Average_Prediction4
East_Weighted_Average_Year_Renoveted

      Year Renoveted Weighted_Average_Prediction Actual Price
0                0.0                    $600,432     $221,900
1                0.0                    $600,432     $604,000
2                0.0                    $600,432     $229,500
3                0.0                    $600,432     $650,000
4                0.0                    $600,432     $395,000
...              ...                         ...          ...
8344             0.0                    $600,432     $610,685
8345             0.0                    $600,432   $1,010,000
8346             0.0                    $600,432     $475,000
8347             0.0                    $600,432     $400,000
8348             0.0                    $600,432     $400,000

[8349 rows x 3 columns]

In [33]:
East_prediction_Year_Built=Quantile_Regression_Prediction3
East_prediction_Year_Built

      Year Built Quantile_Regression_Prediction Actual Price
0           1955          $361,699 - $1,003,203     $221,900
1           1965          $361,699 - $1,003,203     $604,000
2           1960          $361,699 - $1,003,203     $229,500
3           1979          $361,699 - $1,003,203     $650,000
4           1994          $361,699 - $1,003,203     $395,000
...          ...                            ...          ...
8344        2014           $359,232- $1,216,998     $610,685
8345        2009           $359,232- $1,216,998   $1,010,000
8346        2008           $359,232- $1,216,998     $475,000
8347        2014           $359,232- $1,216,998     $400,000
8348        2004          $361,699 - $1,003,203     $400,000

[8349 rows x 3 columns]

In [34]:
East_Weighted_Average_Year_Built = Weighted_Average_Prediction3
East_Weighted_Average_Year_Built

      Year Built Weighted_Average_Prediction Actual Price
0           1955                    $484,755     $221,900
1           1965                    $553,073     $604,000
2           1960                    $550,011     $229,500
3           1979                    $600,587     $650,000
4           1994                    $632,657     $395,000
...          ...                         ...          ...
8344        2014                    $736,528     $610,685
8345        2009                    $583,143   $1,010,000
8346        2008                    $692,798     $475,000
8347        2014                    $736,528     $400,000
8348        2004                    $661,901     $400,000

[8349 rows x 3 columns]

In [35]:
East_prediction_Amount_of_Floors= Quantile_Regression_Prediction2
East_prediction_Amount_of_Floors

      Amount of Floors Quantile_Regression_Prediction Actual Price
0                  1.0          $340,198 - $1,316,791     $221,900
1                  1.0          $340,198 - $1,316,791     $604,000
2                  1.0          $340,198 - $1,316,791     $229,500
3                  2.0          $340,198 - $1,316,791     $650,000
4                  2.0          $340,198 - $1,316,791     $395,000
...                ...                            ...          ...
8344               2.0          $340,198 - $1,316,791     $610,685
8345               2.0          $340,198 - $1,316,791   $1,010,000
8346               2.0          $340,198 - $1,316,791     $475,000
8347               2.0          $340,198 - $1,316,791     $400,000
8348               2.0          $340,198 - $1,316,791     $400,000

[8349 rows x 3 columns]

In [36]:
East_Weighted_Average_Amount_of_Floors = Weighted_Average_Prediction2
East_Weighted_Average_Amount_of_Floors

      Amount of Floors Weighted_Average_Prediction Actual Price
0                  1.0                    $503,324     $221,900
1                  1.0                    $503,324     $604,000
2                  1.0                    $503,324     $229,500
3                  2.0                    $720,587     $650,000
4                  2.0                    $720,587     $395,000
...                ...                         ...          ...
8344               2.0                    $720,587     $610,685
8345               2.0                    $720,587   $1,010,000
8346               2.0                    $720,587     $475,000
8347               2.0                    $720,587     $400,000
8348               2.0                    $720,587     $400,000

[8349 rows x 3 columns]

In [37]:
East_prediction_Amount_of_Bathrooms= Quantile_Regression_Prediction1
East_prediction_Amount_of_Bathrooms

      Amount of Bathrooms Quantile_Regression_Prediction Actual Price
0                     1.0            $200,002 - $550,008     $221,900
1                     3.0          $536,188 - $1,612,980     $604,000
2                     1.0            $200,002 - $550,008     $229,500
3                     3.0          $536,188 - $1,612,980     $650,000
4                     2.0            $200,002 - $550,008     $395,000
...                   ...                            ...          ...
8344                  2.5            $200,002 - $550,008     $610,685
8345                  3.5          $536,188 - $1,612,980   $1,010,000
8346                  2.5            $200,002 - $550,008     $475,000
8347                  2.5            $200,002 - $550,008     $400,000
8348                  2.5            $200,002 - $550,008     $400,000

[8349 rows x 3 columns]

In [38]:
East_Weighted_Average_Amount_of_Bathrooms= Weighted_Average_Prediction1
East_Weighted_Average_Amount_of_Bathrooms

      Amount of Bathrooms Weighted_Average_Prediction Actual Price
0                     1.0                    $351,193     $221,900
1                     3.0                    $769,417     $604,000
2                     1.0                    $351,193     $229,500
3                     3.0                    $769,417     $650,000
4                     2.0                    $496,507     $395,000
...                   ...                         ...          ...
8344                  2.5                    $625,123     $610,685
8345                  3.5                    $951,673   $1,010,000
8346                  2.5                    $625,123     $475,000
8347                  2.5                    $625,123     $400,000
8348                  2.5                    $625,123     $400,000

[8349 rows x 3 columns]

In [39]:
East_prediction_Amount_of_Bedrooms= Quantile_Regression_Prediction
East_prediction_Amount_of_Bedrooms

      Amount of Bedrooms Quantile_Regression_Prediction Actual Price
0                      3           $210,001  - $633,508     $221,900
1                      4          $351,398 - $1,607,982     $604,000
2                      3           $210,001  - $633,508     $229,500
3                      4          $351,398 - $1,607,982     $650,000
4                      3           $210,001  - $633,508     $395,000
...                  ...                            ...          ...
8344                   4          $351,398 - $1,607,982     $610,685
8345                   4          $351,398 - $1,607,982   $1,010,000
8346                   3           $210,001  - $633,508     $475,000
8347                   4          $351,398 - $1,607,982     $400,000
8348                   3           $210,001  - $633,508     $400,000

[8349 rows x 3 columns]

In [40]:
East_Weighted_Average_Amount_of_Bedrooms= Weighted_Average_Prediction
East_Weighted_Average_Amount_of_Bedrooms

      Amount of Bedrooms Weighted_Average_Prediction Actual Price
0                      3                    $522,941     $221,900
1                      4                    $724,117     $604,000
2                      3                    $522,941     $229,500
3                      4                    $724,117     $650,000
4                      3                    $522,941     $395,000
...                  ...                         ...          ...
8344                   4                    $724,117     $610,685
8345                   4                    $724,117   $1,010,000
8346                   3                    $522,941     $475,000
8347                   4                    $724,117     $400,000
8348                   3                    $522,941     $400,000

[8349 rows x 3 columns]

In [41]:
East_predictions = pd.DataFrame({'Id':x,
'Date':f,'Bedrooms':East_prediction_Amount_of_Bedrooms.Quantile_Regression_Prediction,
'Bathrooms':East_prediction_Amount_of_Bathrooms.Quantile_Regression_Prediction, 
'Floors':East_prediction_Amount_of_Floors.Quantile_Regression_Prediction,
'Year Built':East_prediction_Year_Built.Quantile_Regression_Prediction,
'Years Renoveted':East_prediction_Year_Renoveted.Quantile_Regression_Prediction,
'Condition':East_prediction_Condition_Level.Quantile_Regression_Prediction, 
'Sqft_living':East_prediction_sqft_living.Quantile_Regression_Prediction,
'Sqft_lot':East_prediction_sqft_lot.Quantile_Regression_Prediction})
East_predictions

,Id,Date,Bedrooms,Bathrooms,Floors,Year Built,Years Renoveted,Condition,Sqft_living,Sqft_lot
0,Regression,Predictions,"$210,001 - $633,508","$200,002 - $550,008","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
1,Regression,Predictions,"$351,398 - $1,607,982","$536,188 - $1,612,980","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
2,Regression,Predictions,"$210,001 - $633,508","$200,002 - $550,008","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
3,Regression,Predictions,"$351,398 - $1,607,982","$536,188 - $1,612,980","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
4,Regression,Predictions,"$210,001 - $633,508","$200,002 - $550,008","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
...,...,...,...,...,...,...,...,...,...,...
8344,Regression,Predictions,"$351,398 - $1,607,982","$200,002 - $550,008","$340,198 - $1,316,791","$359,232- $1,216,998","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
8345,Regression,Predictions,"$351,398 - $1,607,982","$536,188 - $1,612,980","$340,198 - $1,316,791","$359,232- $1,216,998","$263,411 - $1,322,038","$299,999 - $990,999","$710,003- $1,514,226","$201,558 - $939,876"
8346,Regression,Predictions,"$210,001 - $633,508","$200,002 - $550,008","$340,198 - $1,316,791","$359,232- $1,216,998","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
8347,Regression,Predictions,"$351,398 - $1,607,982","$200,002 - $550,008","$340,198 - $1,316,791","$359,232- $1,216,998","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"
8348,Regression,Predictions,"$210,001 - $633,508","$200,002 - $550,008","$340,198 - $1,316,791","$361,699 - $1,003,203","$263,411 - $1,322,038","$299,999 - $990,999","$336,638- $724,824","$201,558 - $939,876"

In [42]:
id1 = []
for i in range(8349):
    id1.append(id[i])
    id1.append(x[i])
    id1.append(w[i])
len(id1)

25047

In [43]:
date1 = []
for i in range(8349):
    date1.append(date[i])
    date1.append(f[i])
    date1.append(a[i])
len(date1)

25047

In [44]:
bedrooms1 = []
for i in range(8349):
    bedrooms1.append(bedrooms[i])
    bedrooms1.append(East_prediction_Amount_of_Bedrooms.Quantile_Regression_Prediction[i])
    bedrooms1.append(East_Weighted_Average_Amount_of_Bedrooms.Weighted_Average_Prediction[i])
len(bedrooms1)

25047

In [45]:
bathrooms1 = []
for i in range(8349):
    bathrooms1.append(bathrooms[i])
    bathrooms1.append(East_prediction_Amount_of_Bathrooms.Quantile_Regression_Prediction[i])
    bathrooms1.append(East_Weighted_Average_Amount_of_Bathrooms.Weighted_Average_Prediction[i])
len(bathrooms1)

25047

In [46]:
floors1 = []
for i in range(8349):
    floors1.append(floors[i])
    floors1.append(East_prediction_Amount_of_Floors.Quantile_Regression_Prediction[i])
    floors1.append(East_Weighted_Average_Amount_of_Floors.Weighted_Average_Prediction[i])
len(floors1)

25047

In [47]:
yr_built1 = []
for i in range(8349):
    yr_built1.append(yr_built[i])
    yr_built1.append(East_prediction_Year_Built.Quantile_Regression_Prediction[i])
    yr_built1.append(East_Weighted_Average_Year_Built.Weighted_Average_Prediction[i])
len(yr_built1)

25047

In [48]:
yr_renovated1 = []
for i in range(8349):
    yr_renovated1.append(yr_renovated[i])
    yr_renovated1.append(East_prediction_Year_Renoveted.Quantile_Regression_Prediction[i])
    yr_renovated1.append(East_Weighted_Average_Year_Renoveted.Weighted_Average_Prediction[i])
len(yr_renovated1)

25047

In [49]:
condition1 = []
for i in range(8349):
    condition1.append(condition[i])
    condition1.append(East_prediction_Condition_Level.Quantile_Regression_Prediction[i])
    condition1.append(East_Weighted_Average_Condition_Level.Weighted_Average_Prediction[i])
len(condition1)

25047

In [50]:
sqft_living1 = []
for i in range(8349):
    sqft_living1.append(sqft_living[i])
    sqft_living1.append(East_prediction_sqft_living.Quantile_Regression_Prediction[i])
    sqft_living1.append(East_Weighted_Average_Amount_of_sqft_Living.Weighted_Average_Prediction[i])
len(sqft_living1)

25047

In [51]:
sqft_lot1 = []
for i in range(8349):
    sqft_lot1.append(sqft_lot[i])
    sqft_lot1.append(East_prediction_sqft_lot.Quantile_Regression_Prediction[i])
    sqft_lot1.append(East_Weighted_Average_sqft_lot.Weighted_Average_Prediction[i])
len(sqft_lot1)

25047

In [52]:
no = []
for i in range(1,8350):
    no.append(i)

In [53]:
house_info1 = pd.DataFrame({'Id':id1,'Date':date1,'Bedrooms':bedrooms1, 'Bathrooms':bathrooms1, 
                           'Floors':floors1, 'Year Built':yr_built1, 'Year Renoveted':yr_renovated1,
            'Condition':condition1, 'Sqft_living':sqft_living1,'Sqft_lot':sqft_lot1,
                          },
    pd.MultiIndex.from_product([no, ['A', 'B','C']]),
                          )
%store house_info1
house_info1['Year Renoveted'] = house_info1['Year Renoveted'].fillna(0)
house_info1[:65]

Stored 'house_info1' (DataFrame)

              Id         Date               Bedrooms              Bathrooms  \
1  A  7129300520   10/13/2014                      3                      1
   B  Regression  Predictions   $210,001  - $633,508    $200,002 - $550,008
   C    Weighted      Average               $522,941               $351,193
2  A  2487200875    12/9/2014                      4                      3
   B  Regression  Predictions  $351,398 - $1,607,982  $536,188 - $1,612,980
...          ...          ...                    ...                    ...
21 A  2391600320    4/20/2015                      3                      1
   B  Regression  Predictions   $210,001  - $633,508    $200,002 - $550,008
   C    Weighted      Average               $522,941               $351,193
22 A  9418400240   10/28/2014                      2                      1
   B  Regression  Predictions   $210,001  - $633,508    $200,002 - $550,008

                     Floors             Year Built         Year Renoveted  \
1  A                      1                   1955                      0
   B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
   C               $503,324               $484,755               $600,432
2  A                      1                   1965                      0
   B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
...                     ...                    ...                    ...
21 A                      1                   1941                      0
   B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
   C               $503,324               $468,363               $600,432
22 A                      1                   1948                      0
   B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038

                Condition         Sqft_living             Sqft_lot
1  A                    3                1180                 5650
   B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
   C             $606,899            $387,403             $528,685
2  A                    5                1960                 5000
   B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
...                   ...                 ...                  ...
21 A                    3                1040                 5060
   B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
   C             $606,899            $336,903             $528,685
22 A                    3                2020                 6720
   B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876

[65 rows x 10 columns]

In [54]:
import statistics

x = []
for i in range(8349):
    bed_pred = int(float(East_Weighted_Average_Amount_of_Bedrooms.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    bath_pred = int(float(East_Weighted_Average_Amount_of_Bathrooms.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    fl_pred = int(float(East_Weighted_Average_Amount_of_Floors.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    yb_pred = int(float(East_Weighted_Average_Year_Built.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    yr_pred = int(float(East_Weighted_Average_Year_Renoveted.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    Con_pred = int(float(East_Weighted_Average_Condition_Level.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    sliv_pred = int(float(East_Weighted_Average_Amount_of_sqft_Living.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    slot_pred = int(float(East_Weighted_Average_sqft_lot.Weighted_Average_Prediction[i].replace(',','').replace('$','')))
    final = [bed_pred,bath_pred,fl_pred,yb_pred,Con_pred,sliv_pred,slot_pred,yr_pred]
    x.append(final)
x

[[522941, 351193, 503324, 484755, 606899, 387403, 528685, 600432],
 [724117, 769417, 503324, 553073, 647621, 470676, 528685, 600432],
 [522941, 351193, 503324, 550011, 606899, 488822, 528685, 600432],
 [724117, 769417, 720587, 600587, 606899, 765034, 528685, 600432],
 [522941, 496507, 720587, 632657, 606899, 532858, 528685, 600432],
 [522941, 731200, 503324, 582677, 606899, 831567, 528685, 600432],
 [522941, 496520, 720587, 548417, 606899, 729748, 528685, 600432],
 [724117, 625123, 720587, 654231, 606899, 659616, 528685, 600432],
 [522941, 625123, 720587, 680247, 606899, 551305, 528685, 600432],
 [724117, 351193, 503324, 1097467, 414406, 448700, 528685, 600432],
 [724117, 625123, 720587, 808699, 606899, 664758, 528685, 600432],
 [522941, 351193, 720587, 450303, 606899, 488746, 528685, 600432],
 [522941, 625123, 720587, 680247, 606899, 841891, 528685, 600432],
 [883041, 625123, 503324, 567241, 617713, 696607, 528685, 600432],
 [724117, 769417, 720587, 872264, 606899, 502925, 528685, 600432],
 [522941, 611194, 503324, 600587, 606899, 448700, 528685, 600432],
 [724117, 625123, 720587, 741852, 606899, 746829, 528685, 600432],
 [883041, 611194, 503324, 553073, 606899, 849199, 528685, 600432],
 [522941, 496507, 503324, 617467, 617713, 383212, 528685, 600432],
 [724117, 1269576, 720587, 635797, 617713, 998056, 528685, 600432],
 [522941, 351193, 503324, 468363, 606899, 336903, 528685, 600432],
 [398709, 351193, 503324, 458605, 606899, 535690, 528685, 600432],
 [522941, 460762, 503324, 635061, 606899, 499580, 528685, 600432],
 [522941, 460762, 720587, 562445, 606899, 526051, 528685, 600432],
 [522941, 978283, 720587, 694045, 606899, 787170, 528685, 600432],
 [398709, 611194, 720587, 600587, 617713, 440567, 528685, 600432],
 [398709, 496520, 720587, 694045, 606899, 336602, 528685, 600432],
 [883041, 731200, 720587, 758947, 617713, 1058458, 528685, 600432],
 [724117, 625123, 503324, 605827, 606899, 874393, 528685, 1141050],
 [522941, 625123, 720587, 516239, 606899, 817768, 528685, 986850],
 [883041, 496520, 720587, 314792, 617713, 512684, 528685, 600432],
 [724117, 625123, 720587, 666642, 606899, 678408, 528685, 600432],
 [522941, 496520, 503324, 485241, 606899, 479996, 528685, 600432],
 [398709, 351193, 503324, 389206, 617713, 301333, 528685, 600432],
 [522941, 496507, 503324, 638947, 606899, 382707, 528685, 600432],
 [724117, 496520, 570777, 484567, 647621, 551043, 528685, 600432],
 [522941, 611194, 720587, 776035, 606899, 802568, 528685, 600432],
 [724117, 731200, 570777, 654700, 606899, 782175, 528685, 748571],
 [522941, 611194, 503324, 562982, 606899, 551043, 528685, 600432],
 [724117, 625123, 720587, 661901, 606899, 548362, 528685, 600432],
 [724117, 611194, 503324, 635797, 606899, 543828, 528685, 600432],
 [522941, 951673, 570777, 741852, 606899, 1185517, 528685, 600432],
 [522941, 625123, 720587, 736528, 606899, 543828, 528685, 600432],
 [398709, 351193, 503324, 562445, 606899, 442903, 528685, 600432],
 [883041, 625123, 503324, 582677, 617713, 720074, 528685, 600432],
 [724117, 611194, 503324, 563560, 617713, 512684, 528685, 600432],
 [398709, 625123, 720587, 674145, 606899, 628565, 528685, 600432],
 [724117, 978283, 720587, 694045, 606899, 1505000, 528685, 600432],
 [883041, 951673, 720587, 808699, 606899, 1006665, 528685, 600432],
 [724117, 496520, 503324, 582677, 617713, 475515, 528685, 600432],
 [883041, 611194, 503324, 527307, 606899, 566420, 528685, 600432],
 [522941, 496520, 503324, 527307, 606899, 488822, 528685, 600432],
 [522941, 625123, 720587, 702078, 606899, 828443, 528685, 600432],
 [522941, 731200, 503324, 600587, 606899, 536561, 528685, 600432],
 [522941, 496507, 503324, 577663, 617713, 535690, 528685, 600432],
 [522941, 496520, 503324, 619575, 606899, 421805, 528685, 600432],
 [724117, 625123, 720587, 716481, 606899, 655835, 528685, 600432],
 [522941, 625123, 503324, 600587, 617713, 655835, 528685, 600432],
 [724117, 611194, 720587, 642416, 617713, 732124, 528685, 600432],
 [522941, 625123, 720587, 692798, 606899, 347703, 528685, 600432],
 [522941, 351193, 503324, 629298, 606899, 371812, 528685, 600432],
 [724117, 769417, 570777, 562445, 617713, 587994, 528685, 600432],
 [724117, 769417, 720587, 563560, 647621, 628877, 528685, 600432],
 [724117, 731200, 720587, 738933, 606899, 742076, 528685, 600432],
 [522941, 611194, 503324, 577663, 606899, 585181, 528685, 600432],
 [522941, 496520, 503324, 618693, 606899, 438822, 528685, 600432],
 [522941, 625123, 503324, 536113, 617713, 526051, 528685, 600432],
 [724117, 496507, 570777, 436181, 647621, 476911, 528685, 600432],
 [522941, 625123, 720587, 674145, 606899, 538278, 528685, 600432],
 [522941, 625123, 720587, 699408, 606899, 536561, 528685, 600432],
 [522941, 351193, 503324, 325179, 617713, 272719, 528685, 600432],
 [522941, 351193, 503324, 527307, 617713, 316371, 528685, 600432],
 [724117, 496520, 503324, 567241, 617713, 681248, 528685, 600432],
 [522941, 625123, 720587, 653951, 606899, 628877, 528685, 600432],
 [522941, 351193, 503324, 548417, 606899, 325607, 528685, 600432],
 [724117, 731200, 720587, 604737, 606899, 485377, 528685, 600432],
 [883041, 769417, 503324, 489798, 606899, 874393, 528685, 1141050],
 [522941, 625123, 720587, 702078, 606899, 576114, 528685, 600432],
 [724117, 625123, 720587, 716481, 606899, 594020, 528685, 600432],
 [522941, 611194, 503324, 314792, 647621, 340109, 528685, 600432],
 [724117, 731200, 503324, 550011, 647621, 539634, 528685, 600432],
 [398709, 351193, 503324, 563560, 606899, 329504, 528685, 600432],
 [522941, 460762, 570777, 479821, 647621, 681248, 528685, 600432],
 [724117, 351193, 570777, 525278, 606899, 476911, 528685, 833545],
 [398709, 351193, 503324, 596068, 606899, 256278, 528685, 600432],
 [398709, 460762, 503324, 504555, 606899, 265028, 528685, 600432],
 [522941, 351193, 503324, 602723, 606899, 389840, 528685, 600432],
 [724117, 496520, 503324, 484755, 617713, 622400, 528685, 600432],
 [522941, 496520, 503324, 583484, 617713, 421805, 528685, 600432],
 [724117, 625123, 720587, 694045, 606899, 600032, 528685, 600432],
 [522941, 351193, 503324, 504555, 606899, 347703, 528685, 600432],
 [724117, 978283, 570777, 664777, 606899, 1897500, 528685, 600432],
 [522941, 351193, 503324, 563560, 606899, 409425, 528685, 600432],
 [522941, 496520, 503324, 504555, 606899, 301553, 528685, 1129562],
 [522941, 496520, 503324, 536697, 606899, 605780, 528685, 600432],
 [398709, 351193, 503324, 602084, 606899, 272719, 528685, 600432],
 [883041, 769417, 720587, 586606, 647621, 1086042, 528685, 1110001],
 [883041, 611194, 503324, 600587, 606899, 595041, 528685, 600432],
 [522941, 496520, 503324, 642416, 606899, 543599, 528685, 600432],
 [883041, 611194, 503324, 631276, 606899, 778545, 528685, 600432],
 [398709, 351193, 503324, 504555, 617713, 466680, 528685, 600432],
 [724117, 496520, 503324, 577663, 617713, 765034, 528685, 600432],
 [724117, 769417, 720587, 635797, 606899, 1081195, 528685, 600432],
 [522941, 496507, 720587, 531205, 647621, 476911, 528685, 600432],
 [724117, 625123, 720587, 632657, 606899, 804960, 528685, 600432],
 [522941, 625123, 720587, 776035, 606899, 660892, 528685, 600432],
 [522941, 460762, 503324, 653544, 606899, 512684, 528685, 600432],
 [724117, 731200, 720587, 550011, 647621, 869322, 528685, 600432],
 [883041, 496520, 570777, 548417, 606899, 448700, 528685, 600432],
 [883041, 625123, 720587, 621686, 647621, 1339362, 528685, 600432],
 [724117, 978283, 503324, 699408, 606899, 1332500, 528685, 600432],
 [724117, 978283, 503324, 699408, 606899, 1332500, 528685, 600432],
 [883041, 731200, 720587, 757191, 606899, 696607, 528685, 600432],
 [522941, 611194, 720587, 666642, 606899, 512684, 528685, 600432],
 [398709, 351193, 503324, 450303, 606899, 400291, 528685, 495444],
 [398709, 351193, 503324, 450303, 606899, 400291, 528685, 495444],
 [724117, 496507, 720587, 582677, 647621, 708274, 528685, 600432],
 [522941, 731200, 503324, 661901, 606899, 745446, 528685, 600432],
 [522941, 496520, 503324, 504555, 606899, 487814, 528685, 600432],
 [724117, 496520, 720587, 527307, 617713, 612879, 528685, 600432],
 [724117, 951673, 720587, 653951, 606899, 758436, 528685, 600432],
 [724117, 625123, 720587, 637701, 606899, 688961, 528685, 600432],
 [724117, 351193, 503324, 325179, 606899, 329504, 528685, 600432],
 [724117, 351193, 503324, 325179, 606899, 329504, 528685, 600432],
 [398709, 351193, 503324, 574352, 617713, 344180, 528685, 600432],
 [724117, 731200, 720587, 553073, 606899, 575233, 528685, 600432],
 [724117, 496520, 503324, 484755, 647621, 599972, 528685, 600432],
 [724117, 351193, 570777, 504555, 617713, 463187, 528685, 600432],
 [522941, 625123, 720587, 702078, 606899, 628877, 528685, 600432],
 [883041, 625123, 720587, 604737, 617713, 594020, 528685, 600432],
 [883041, 625123, 503324, 567241, 617713, 758436, 519811, 600432],
 [724117, 731200, 503324, 741852, 617713, 628877, 519811, 600432],
 [724117, 769417, 503324, 635797, 606899, 507031, 519811, 600432],
 [522941, 611194, 720587, 738933, 606899, 385925, 519811, 600432],
 [522941, 611194, 720587, 632657, 606899, 382707, 519811, 600432],
 [724117, 625123, 720587, 661901, 606899, 903860, 519811, 600432],
 [724117, 611194, 720587, 758947, 606899, 596190, 519811, 600432],
 [724117, 611194, 503324, 582677, 606899, 583206, 519811, 600432],
 [883041, 951673, 720587, 706856, 606899, 1215000, 519811, 600432],
 [724117, 611194, 720587, 552074, 617713, 665923, 519811, 600432],
 [522941, 496507, 503324, 639104, 617713, 398723, 519811, 600432],
 [724117, 625123, 720587, 738933, 606899, 579297, 519811, 600432],
 [724117, 351193, 570777, 489798, 606899, 423416, 519811, 600432],
 [522941, 625123, 720587, 654231, 606899, 451349, 519811, 600432],
 [724117, 731200, 720587, 602723, 606899, 874393, 519811, 600432],
 [724117, 625123, 720587, 639104, 617713, 1080208, 519811, 600432],
 [724117, 496507, 503324, 527307, 414406, 546985, 519811, 600432],
 [522941, 625123, 570777, 690498, 606899, 631063, 519811, 404688],
 [522941, 951673, 720587, 692798, 606899, 507687, 519811, 600432],
 [522941, 978283, 720587, 758947, 606899, 437684, 519811, 600432],
 [522941, 625123, 720587, 793829, 606899, 519852, 519811, 600432],
 [724117, 460762, 570777, 436181, 606899, 605780, 519811, 600432],
 [522941, 496520, 503324, 562982, 617713, 802568, 519811, 600432],
 [724117, 496520, 503324, 635061, 606899, 563500, 519811, 600432],
 [522941, 611194, 720587, 612027, 606899, 482242, 519811, 600432],
 [883041, 1604965, 720587, 716481, 606899, 1560000, 519811, 600432],
 [522941, 496520, 503324, 484755, 647621, 451349, 519811, 600432],
 [522941, 625123, 720587, 716212, 606899, 576114, 519811, 600432],
 [398709, 351193, 503324, 690498, 606899, 329996, 519811, 600432],
 [522941, 496507, 503324, 619575, 617713, 598640, 519811, 600432],
 [724117, 496507, 503324, 485241, 606899, 404280, 519811, 600432],
 [724117, 769417, 720587, 638947, 606899, 1152875, 519811, 600432],
 [724117, 625123, 503324, 619575, 606899, 507687, 519811, 648834],
 [522941, 625123, 720587, 872264, 606899, 742076, 519811, 600432],
 [522941, 496520, 503324, 618693, 606899, 579297, 519811, 600432],
 [522941, 496520, 503324, 582677, 606899, 515046, 519811, 600432],
 [522941, 625123, 503324, 654231, 606899, 1030000, 519811, 600432],
 [522941, 496507, 503324, 617467, 606899, 383212, 519811, 600432],
 [883041, 625123, 503324, 577663, 606899, 568658, 519811, 600432],
 [522941, 1373232, 720587, 618693, 606899, 1407875, 519811, 600432],
 [522941, 731200, 503324, 639104, 617713, 622400, 519811, 600432],
 [522941, 496520, 503324, 550011, 617713, 447043, 519811, 600432],
 [522941, 625123, 720587, 632657, 606899, 590052, 519811, 600432],
 [724117, 951673, 720587, 674145, 606899, 1024792, 519811, 600432],
 [398709, 496507, 720587, 574352, 606899, 440567, 519811, 493480],
 [724117, 611194, 720587, 680247, 606899, 532858, 519811, 600432],
 [522941, 625123, 720587, 654231, 606899, 440567, 519811, 600432],
 [398709, 351193, 503324, 488748, 606899, 217667, 519811, 600432],
 [724117, 496520, 503324, 484755, 606899, 503678, 519811, 600432],
 [522941, 460762, 503324, 516239, 606899, 411975, 519811, 600432],
 [847272, 951673, 720587, 706856, 606899, 1375000, 519811, 600432],
 [398709, 496507, 503324, 455285, 606899, 271031, 519811, 600432],
 [724117, 731200, 720587, 637701, 606899, 780495, 519811, 600432],
 [883041, 625123, 720587, 618693, 617713, 828443, 519811, 600432],
 [724117, 460762, 503324, 653544, 617713, 421805, 519811, 600432],
 [883041, 625123, 720587, 550011, 617713, 720074, 519811, 600432],
 [522941, 496507, 503324, 617467, 606899, 437684, 519811, 600432],
 [724117, 496507, 720587, 562445, 606899, 565876, 519811, 1129562],
 [398709, 460762, 570777, 532435, 617713, 452115, 519811, 600432],
 [522941, 625123, 720587, 702078, 606899, 579297, 519811, 600432],
 [724117, 625123, 720587, 680247, 606899, 868743, 519811, 600432],
 [522941, 351193, 503324, 468363, 617713, 332382, 519811, 600432],
 [398709, 351193, 503324, 605827, 617713, 456842, 519811, 600432],
 [724117, 496520, 503324, 541244, 617713, 586011, 519811, 600432],
 [724117, 625123, 720587, 654231, 606899, 675636, 519811, 600432],
 [522941, 496520, 503324, 575095, 647621, 510274, 519811, 600432],
 [724117, 978283, 720587, 654231, 606899, 868743, 519811, 600432],
 [398709, 351193, 503324, 325179, 606899, 217667, 519811, 833545],
 [398709, 351193, 503324, 575095, 606899, 329996, 519811, 600432],
 [398709, 496507, 503324, 618354, 617713, 400291, 519811, 600432],
 [847272, 2106000, 720587, 758947, 606899, 1600000, 519811, 600432],
 [522941, 496520, 503324, 666642, 606899, 595041, 519811, 600432],
 [724117, 978283, 720587, 638947, 606899, 1123333, 519811, 600432],
 [724117, 625123, 720587, 680247, 606899, 493137, 519811, 600432],
 [522941, 611194, 503324, 562982, 606899, 579297, 519811, 600432],
 [724117, 625123, 720587, 716212, 606899, 901000, 519811, 600432],
 [724117, 625123, 720587, 872264, 617713, 587994, 519811, 600432],
 [398709, 496507, 720587, 692798, 606899, 344180, 519811, 600432],
 [522941, 496520, 503324, 605827, 617713, 586653, 519811, 600432],
 [522941, 769417, 720587, 618354, 647621, 1148333, 519811, 600432],
 [724117, 625123, 720587, 716481, 606899, 689022, 519811, 600432],
 [856707, 951673, 720587, 553073, 606899, 1692500, 519811, 1129562],
 [847272, 496520, 720587, 648370, 617713, 782175, 519811, 600432],
 [724117, 769417, 503324, 604737, 606899, 585181, 519811, 600432],
 [522941, 351193, 570777, 536113, 617713, 387403, 519811, 600432],
 [724117, 1269576, 720587, 661901, 606899, 849199, 519811, 600432],
 [883041, 769417, 570777, 615319, 617713, 612879, 519811, 600432],
 [883041, 731200, 570777, 629329, 647621, 583206, 519811, 600432],
 [522941, 625123, 720587, 654231, 606899, 746829, 519811, 600432],
 [398709, 611194, 570777, 468363, 617713, 596190, 519811, 600432],
 [724117, 611194, 720587, 577663, 606899, 566420, 519811, 600432],
 [522941, 625123, 570777, 467248, 606899, 631063, 519811, 819727],
 [724117, 625123, 720587, 808699, 606899, 492223, 519811, 600432],
 [398709, 625123, 720587, 674145, 606899, 389840, 519811, 600432],
 [724117, 611194, 720587, 527307, 617713, 849199, 519811, 600432],
 [522941, 496520, 503324, 642416, 606899, 404280, 519811, 600432],
 [522941, 611194, 720587, 631276, 606899, 382707, 519811, 600432],
 [522941, 496507, 503324, 562445, 617713, 447043, 519811, 600432],
 [522941, 625123, 720587, 776035, 617713, 486048, 519811, 600432],
 [522941, 611194, 720587, 541244, 606899, 452115, 519811, 600432],
 [522941, 625123, 720587, 716212, 606899, 470406, 519811, 600432],
 [522941, 625123, 503324, 619575, 606899, 566420, 519811, 600432],
 [522941, 351193, 503324, 350938, 617713, 316839, 519811, 600432],
 [522941, 611194, 503324, 537035, 606899, 377186, 519811, 600432],
 [398709, 496520, 503324, 654700, 617713, 429387, 519811, 410500],
 [522941, 496520, 503324, 582677, 647621, 479996, 519811, 600432],
 [522941, 496520, 503324, 618693, 606899, 344180, 519811, 600432],
 [522941, 460762, 720587, 484567, 647621, 754939, 519811, 600432],
 [398709, 496507, 503324, 653544, 606899, 409425, 519811, 600432],
 [522941, 625123, 746923, 738367, 606899, 448700, 519811, 600432],
 [522941, 625123, 720587, 680247, 606899, 622400, 519811, 600432],
 [522941, 496520, 570777, 624290, 606899, 499580, 519811, 600432],
 [724117, 351193, 570777, 562445, 606899, 383212, 519811, 600432],
 [522941, 351193, 503324, 618354, 606899, 515046, 519811, 600432],
 [522941, 496507, 570777, 654143, 617713, 538278, 519811, 600432],
 [522941, 625123, 720587, 716481, 606899, 436512, 519811, 600432],
 [522941, 625123, 720587, 872264, 606899, 868743, 519811, 600432],
 [522941, 625123, 503324, 489798, 617713, 1413421, 519811, 600432],
 [724117, 951673, 720587, 758947, 606899, 787170, 519811, 600432],
 [522941, 460762, 503324, 602723, 617713, 340109, 519811, 600432],
 [724117, 625123, 503324, 562982, 606899, 576114, 519811, 600432],
 [522941, 351193, 503324, 619575, 606899, 373421, 519811, 600432],
 [522941, 496520, 503324, 635797, 606899, 409425, 519811, 600432],
 [724117, 731200, 503324, 604737, 647621, 665923, 519811, 600432],
 [522941, 611194, 503324, 577663, 606899, 447043, 519811, 600432],
 [398709, 460762, 503324, 484567, 606899, 347703, 519811, 600432],
 [522941, 351193, 503324, 552074, 606899, 507031, 519811, 600432],
 [724117, 951673, 720587, 758947, 606899, 1412500, 519811, 600432],
 [724117, 951673, 720587, 793829, 617713, 587994, 519811, 600432],
 [883041, 731200, 720587, 736528, 606899, 689022, 519811, 600432],
 [724117, 625123, 720587, 694045, 606899, 683377, 519811, 600432],
 [522941, 351193, 503324, 562982, 606899, 405628, 519811, 600432],
 [883041, 625123, 720587, 553073, 647621, 1165000, 519811, 600432],
 [883041, 625123, 503324, 600587, 647621, 697001, 519811, 600432],
 [724117, 611194, 720587, 619575, 606899, 571079, 519811, 600432],
 [398709, 351193, 570777, 586606, 606899, 437867, 519811, 600432],
 [398709, 351193, 503324, 602723, 606899, 321139, 519811, 600432],
 [724117, 496507, 503324, 532435, 606899, 389840, 519811, 600432],
 [522941, 496520, 503324, 666642, 617713, 445588, 519811, 600432],
 [522941, 496520, 503324, 562982, 647621, 452115, 519811, 600432],
 [522941, 625123, 720587, 674145, 606899, 526051, 519811, 600432],
 [883041, 769417, 503324, 661901, 606899, 656487, 519811, 600432],
 [398709, 351193, 503324, 516239, 606899, 367423, 519811, 600432],
 [522941, 496520, 503324, 639104, 606899, 436512, 519811, 600432],
 [522941, 731200, 720587, 612027, 606899, 507031, 519811, 600432],
 [522941, 496520, 503324, 618693, 617713, 515046, 519811, 600432],
 [724117, 496520, 503324, 653544, 617713, 543828, 519811, 600432],
 [724117, 460762, 503324, 537035, 606899, 437684, 519811, 600432],
 [522941, 496520, 503324, 550011, 647621, 538278, 519811, 600432],
 [522941, 351193, 503324, 350938, 647621, 438166, 514554, 600432],
 [883041, 951673, 503324, 541244, 617713, 1921250, 514554, 600432],
 [398709, 611194, 720587, 872264, 606899, 1185517, 514554, 600432],
 [883041, 460762, 837321, 488748, 617713, 697001, 514554, 600432],
 [522941, 611194, 720587, 692798, 606899, 332382, 514554, 600432],
 [522941, 496507, 503324, 699408, 606899, 389840, 514554, 600432],
 [522941, 731200, 503324, 639104, 647621, 605780, 514554, 600432],
 [724117, 611194, 503324, 563560, 617713, 708274, 514554, 600432],
 [522941, 460762, 503324, 563560, 617713, 348945, 514554, 600432],
 [522941, 351193, 503324, 484755, 617713, 317397, 514554, 600432],
 [724117, 496507, 503324, 560650, 606899, 536561, 514554, 600432],
 [522941, 351193, 503324, 562982, 647621, 340109, 514554, 600432],
 [522941, 496520, 570777, 589794, 647621, 457232, 514554, 600432],
 [724117, 496507, 503324, 666642, 617713, 507031, 514554, 600432],
 [522941, 625123, 720587, 776035, 617713, 452660, 514554, 600432],
 [522941, 496520, 503324, 642416, 617713, 414454, 514554, 600432],
 [724117, 951673, 503324, 716481, 606899, 844258, 514554, 600432],
 [522941, 625123, 720587, 716481, 606899, 551043, 514554, 600432],

In [55]:
takeClosest = lambda num,collection:min(collection,key=lambda x:abs(x-num))
closest = []
for i in range(8349):
    closest.append(takeClosest(price[i],x[i]))

In [56]:
closest

[351193,
 600432,
 351193,
 606899,
 496507,
 831567,
 729748,
 720587,
 600432,
 528685,
 606899,
 720587,
 522941,
 503324,
 502925,
 448700,
 746829,
 883041,
 383212,
 724117,
 468363,
 351193,
 460762,
 720587,
 522941,
 398709,
 336602,
 1058458,
 874393,
 986850,
 496520,
 600432,
 479996,
 301333,
 382707,
 484567,
 776035,
 782175,
 503324,
 528685,
 635797,
 741852,
 522941,
 606899,
 528685,
 503324,
 398709,
 1505000,
 606899,
 475515,
 503324,
 488822,
 828443,
 503324,
 496507,
 421805,
 724117,
 655835,
 642416,
 347703,
 371812,
 528685,
 600432,
 742076,
 585181,
 438822,
 625123,
 436181,
 522941,
 522941,
 272719,
 316371,
 724117,
 653951,
 351193,
 485377,
 1141050,
 522941,
 716481,
 340109,
 503324,
 329504,
 479821,
 351193,
 256278,
 265028,
 351193,
 484755,
 421805,
 694045,
 347703,
 1897500,
 351193,
 301553,
 496520,
 272719,
 1110001,
 503324,
 496520,
 631276,
 503324,
 617713,
 600432,
 531205,
 804960,
 522941,
 460762,
 647621,
 448700,
 1339362,
 1332500,
 1332500,
 757191,
 522941,
 351193,
 351193,
 724117,
 528685,
 487814,
 496520,
 653951,
 528685,
 325179,
 325179,
 344180,
 731200,
 484755,
 463187,
 702078,
 528685,
 758436,
 741852,
 503324,
 385925,
 382707,
 724117,
 519811,
 582677,
 1215000,
 724117,
 398723,
 519811,
 351193,
 451349,
 874393,
 1080208,
 414406,
 404688,
 522941,
 606899,
 600432,
 436181,
 562982,
 563500,
 482242,
 1560000,
 647621,
 522941,
 398709,
 619575,
 404280,
 1152875,
 724117,
 872264,
 579297,
 496520,
 1030000,
 503324,
 503324,
 1407875,
 731200,
 617713,
 519811,
 1024792,
 398709,
 519811,
 440567,
 351193,
 484755,
 522941,
 951673,
 271031,
 720587,
 883041,
 460762,
 625123,
 437684,
 724117,
 617713,
 519811,
 625123,
 468363,
 617713,
 586011,
 519811,
 600432,
 868743,
 217667,
 329996,
 618354,
 1600000,
 666642,
 978283,
 493137,
 522941,
 901000,
 724117,
 344180,
 617713,
 1148333,
 724117,
 1692500,
 720587,
 503324,
 351193,
 720587,
 519811,
 647621,
 625123,
 617713,
 519811,
 631063,
 492223,
 389840,
 849199,
 496520,
 382707,
 617713,
 522941,
 522941,
 470406,
 566420,
 316839,
 537035,
 519811,
 479996,
 344180,
 754939,
 398709,
 738367,
 519811,
 522941,
 383212,
 351193,
 600432,
 436512,
 872264,
 1413421,
 758947,
 617713,
 503324,
 351193,
 409425,
 665923,
 503324,
 347703,
 503324,
 951673,
 519811,
 736528,
 519811,
 405628,
 1165000,
 697001,
 724117,
 606899,
 321139,
 496507,
 445588,
 452115,
 625123,
 503324,
 351193,
 436512,
 507031,
 600432,
 653544,
 437684,
 647621,
 438166,
 951673,
 1185517,
 460762,
 332382,
 389840,
 503324,
 724117,
 348945,
 351193,
 496507,
 340109,
 457232,
 496507,
 452660,
 522941,
 951673,
 514554,
 902431,
 445575,
 351193,
 514554,
 600432,
 398709,
 499580,
 611194,
 2090000,
 356385,
 654231,
 759067,
 292314,
 639104,
 432674,
 466680,
 514554,
 514554,
 444212,
 453877,
 503324,
 444212,
 514554,
 405628,
 367417,
 720587,
 323264,
 724117,
 883041,
 720587,
 514554,
 335692,
 426794,
 883041,
 951673,
 757191,
 318391,
 455285,
 611194,
 484755,
 325179,
 617713,
 493137,
 436181,
 367417,
 541244,
 421805,
 292314,
 570777,
 776035,
 1002750,
 398723,
 808699,
 514554,
 460762,
 650000,
 488746,
 493137,
 522941,
 522941,
 794700,
 351193,
 769417,
 398709,
 405628,
 514554,
 246294,
 514554,
 522941,
 496520,
 450303,
 340109,
 509887,
 316839,
 383212,
 438530,
 509887,
 796668,
 1002750,
 503324,
 600432,
 546985,
 496520,
 515046,
 350938,
 724117,
 625123,
 354460,
 618354,
 493137,
 731200,
 351193,
 332382,
 503324,
 503324,
 731200,
 635061,
 503324,
 351193,
 724117,
 617713,
 476911,
 496507,
 883041,
 766050,
 600432,
 481275,
 265028,
 1560000,
 606899,
 398709,
 802568,
 606899,
 351193,
 647621,
 606899,
 509887,
 329996,
 905700,
 951600,
 496520,
 350938,
 332382,
 460762,
 460762,
 351193,
 1269576,
 720587,
 356385,
 509887,
 486048,
 1131009,
 720587,
 724117,
 488746,
 509887,
 509887,
 444212,
 606899,
 382707,
 606899,
 595041,
 600432,
 724117,
 522941,
 874393,
 951673,
 724117,
 351193,
 475515,
 606899,
 456842,
 617713,
 492223,
 452115,
 509528,
 509528,
 647621,
 503324,
 509528,
 1297500,
 724117,
 720587,
 466680,
 503324,
 606899,
 617713,
 503324,
 398709,
 808699,
 351193,
 503324,
 591377,
 606899,
 522941,
 606837,
 503324,
 509528,
 1584375,
 503678,
 509528,
 340109,
 951673,
 351193,
 356385,
 837321,
 398709,
 351193,
 325607,
 509528,
 5300000,
 463187,
 460762,
 617713,
 724117,
 606899,
 496520,
 842593,
 409425,
 883041,
 724117,
 508195,
 837321,
 351193,
 625123,
 720587,
 1692500,
 720587,
 721739,
 628877,
 356385,
 347703,
 617713,
 389206,
 508195,
 460762,
 720587,
 348945,
 1060000,
 510274,
 314792,
 635797,
 383212,
 720587,
 385977,
 496507,
 522941,
 1215958,
 385977,
 1152875,
 508195,
 868743,
 286499,
 432674,
 503324,
 600432,
 5350000,
 314792,
 452660,
 752604,
 720587,
 720587,
 503324,
 953000,
 508195,
 405628,
 720587,
 640000,
 336602,
 508195,
 536561,
 508195,
 398709,
 1151531,
 724117,
 606899,
 606899,
 508195,
 245790,
 611194,
 503324,
 503324,
 724117,
 488746,
 724117,
 720587,
 457682,
 720587,
 847272,
 452115,
 540742,
 449430,
 503324,
 503324,
 724117,
 347703,
 883041,
 618354,
 438822,
 606899,
 724117,
 759067,
 720587,
 540742,
 540742,
 600432,
 384073,
 351193,
 503324,
 732124,
 617713,
 460762,
 661901,
 847272,
 344180,
 453877,
 398235,
 724117,
 720587,
 883041,
 484755,
 617713,
 540742,
 423416,
 377186,
 340109,
 284409,
 522941,
 496520,
 503324,
 429387,
 844258,
 488822,
 600432,
 475515,
 452660,
 322053,
 496520,
 516730,
 496520,
 842593,
 647621,
 470406,
 468363,
 426794,
 503324,
 758947,
 951673,
 351193,
 745446,
 351193,
 522941,
 505960,
 516730,
 617713,
 387403,
 883041,
 351193,
 449430,
 351193,
 1680000,
 389840,
 1456812,
 516730,
 318391,
 516730,
 516730,
 458605,
 745446,
 516730,
 516730,
 516730,
 724117,
 451555,
 453877,
 553603,
 366017,
 1165000,
 553603,
 883041,
 600432,
 553603,
 553603,
 600432,
 479461,
 553603,
 503324,
 351193,
 898395,
 978283,
 553603,
 272719,
 720587,
 769417,
 720756,
 470406,
 606899,
 553603,
 978283,
 460762,
 566420,
 452115,
 600432,
 522941,
 869500,
 553603,
 606899,
 496507,
 503324,
 485377,
 398709,
 553603,
 1230818,
 1086042,
 706064,
 793829,
 731200,
 600432,
 1570000,
 444212,
 351193,
 617713,
 398709,
 724117,
 606899,
 637701,
 625123,
 479996,
 817768,
 902431,
 445575,
 539634,
 457232,
 724117,
 570777,
 1236225,
 606899,
 503324,
 819727,
 301553,
 600432,
 587994,
 606899,
 503324,
 228225,
 445588,
 395770,
 496520,
 503324,
 706064,
 448700,
 831567,
 522941,
 842593,
 496520,
 600432,
 600432,
 351193,
 503324,
 535690,
 280196,
 724117,
 398709,
 600432,
 351193,
 600432,
 587027,
 869322,
 414454,
 325179,
 550574,
 484567,
 647621,
 625123,
 460762,
 883041,
 503324,
 293471,
 550574,
 332382,
 351193,
 522941,
 503324,
 656487,
 445588,
 445588,
 769417,
 389206,
 550574,
 546985,
 485377,
 314792,
 398723,
 503324,
 724117,
 316782,
 720587,
 654983,
 871962,
 724117,
 2765000,
 978283,
 731200,
 721263,
 617713,
 491000,
 366907,
 503324,
 1216600,
 950333,
 503324,
 380926,
 582677,
 724117,
 600432,
 351193,
 618354,
 538119,
 259969,
 617713,
 380926,
 724117,
 759067,
 724117,
 600432,
 503324,
 410000,
 600432,
 400104,
 617713,
 496520,
 787170,
 990390,
 336903,
 766050,
 883041,
 351193,
 400104,
 606899,
 731200,
 485377,
 600432,
 606899,
 606899,
 731200,
 898395,
 351193,
 891600,
 600432,
 400104,
 662062,
 618693,
 452115,
 600432,
 606899,
 1760000,
 325460,
 883041,
 348945,
 336602,
 438530,
 1584375,
 522941,
 579960,
 2750000,
 398709,
 637701,
 438822,
 522941,
 488822,
 302247,
 978283,
 496507,
 744372,
 447043,
 332382,
 325179,
 787170,
 522941,
 457327,
 496520,
 449430,
 445000,
 246294,
 314792,
 570777,
 978283,
 522941,
 708274,
 620665,
 323264,
 570777,
 758947,
 503324,
 629329,
 720587,
 720587,
 647621,
 496507,
 496507,
 650000,
 724117,
 496520,
 503324,
 1540000,
 325179,
 484755,
 659616,
 808699,
 625123,
 351193,
 351193,
 600432,
 525000,
 778545,
 765034,
 883041,
 503324,
 951673,
 398709,
 600432,
 951673,
 457327,
 942877,
 841891,
 351193,
 436512,
 1097467,
 750661,
 695123,
 2106000,
 614874,
 546985,
 841891,
 765034,
 837321,
 351193,
 351193,
 750661,
 398709,
 543599,
 332382,
 573818,
 421805,
 557622,
 522941,
 492223,
 775398,
 625123,
 522941,
 245790,
 371812,
 696607,
 460762,
 557622,
 467248,
 611194,
 878000,
 600432,
 661000,
 503324,
 557622,
 720587,
 336602,
 731200,
 731200,
 606899,
 490300,
 1197500,
 1197500,
 490300,
 600432,
 503324,
 883041,
 462507,
 462507,
 661901,
 741852,
 617713,
 398235,
 301553,
 404280,
 720587,
 462507,
 317539,
 741852,
 351193,
 522941,
 325179,
 600432,
 502925,
 317397,
 861675,
 1600000,
 606899,
 522941,
 600432,
 411633,
 617713,
 891250,
 638947,
 953604,
 503324,
 600432,
 522941,
 1380000,
 351193,
 496520,
 570777,
 720587,
 398723,
 724117,
 351193,
 409425,
 503324,
 470676,
 505960,
 720587,
 265028,
 398709,
 628877,
 356385,
 600432,
 ...]

In [57]:
final_prediction = []
for i in closest:
    final_prediction.append( "${:,.0f}". format(i))

In [58]:
for i in range(8349):
    print(i,closest[i],East_Weighted_Average_Amount_of_Bedrooms['Actual Price'][i])

0 351193 $221,900
1 600432 $604,000
2 351193 $229,500
3 606899 $650,000
4 496507 $395,000
5 831567 $2,000,000
6 729748 $937,000
7 720587 $719,000
8 600432 $580,500
9 528685 $550,000
10 606899 $605,000
11 720587 $685,000
12 522941 $488,000
13 503324 $345,000
14 502925 $430,000
15 448700 $425,000
16 746829 $975,000
17 883041 $1,330,000
18 383212 $325,000
19 724117 $832,500
20 468363 $480,000
21 351193 $355,000
22 460762 $356,000
23 720587 $940,000
24 522941 $461,000
25 398709 $215,000
26 336602 $335,000
27 1058458 $1,100,000
28 874393 $905,000
29 986850 $1,090,000
30 496520 $470,000
31 600432 $597,750
32 479996 $329,950
33 301333 $205,425
34 382707 $391,500
35 484567 $445,000
36 776035 $770,000
37 782175 $1,450,000
38 503324 $445,000
39 528685 $430,000
40 635797 $660,500
41 741852 $784,000
42 522941 $453,246
43 606899 $665,000
44 528685 $527,700
45 503324 $500,000
46 398709 $430,000
47 1505000 $2,250,000
48 606899 $650,000
49 475515 $320,000
50 503324 $255,000
51 488822 $438,000
52 828443 $900,000
53 503324 $441,000
54 496507 $420,000
55 421805 $370,000
56 724117 $807,100
57 655835 $653,000
58 642416 $673,000
59 347703 $425,000
60 371812 $385,000
61 528685 $470,000
62 600432 $589,000
63 742076 $835,000
64 585181 $585,188
65 438822 $305,000
66 625123 $799,000
67 436181 $423,000
68 522941 $465,000
69 522941 $440,000
70 272719 $210,000
71 316371 $274,250
72 724117 $840,000
73 653951 $677,900
74 351193 $425,000
75 485377 $477,000
76 1141050 $1,510,000
77 522941 $445,838
78 716481 $686,000
79 340109 $390,000
80 503324 $500,000
81 329504 $213,000
82 479821 $475,000
83 351193 $410,000
84 256278 $210,000
85 265028 $181,000
86 351193 $349,500
87 484755 $385,000
88 421805 $315,000
89 694045 $693,000
90 347703 $285,000
91 1897500 $2,900,000
92 351193 $236,000
93 301553 $331,000
94 496520 $405,000
95 272719 $170,000
96 1110001 $2,050,000
97 503324 $467,000
98 496520 $405,000
99 631276 $675,000
100 503324 $500,000
101 617713 $630,000
102 600432 $580,000
103 531205 $550,000
104 804960 $879,000
105 522941 $446,500
106 460762 $404,000
107 647621 $665,000
108 448700 $201,000
109 1339362 $2,380,000
110 1332500 $1,380,000
111 1332500 $1,400,000
112 757191 $819,900
113 522941 $520,000
114 351193 $232,000
115 351193 $240,500
116 724117 $940,000
117 528685 $559,900
118 487814 $245,000
119 496520 $485,000
120 653951 $684,000
121 528685 $552,250
122 325179 $165,000
123 325179 $239,900
124 344180 $320,000
125 731200 $855,000
126 484755 $375,000
127 463187 $420,000
128 702078 $679,900
129 528685 $380,000
130 758436 $795,000
131 741852 $785,000
132 503324 $338,000
133 385925 $280,000
134 382707 $297,000
135 724117 $730,000
136 519811 $389,000
137 582677 $560,000
138 1215000 $1,350,000
139 724117 $799,000
140 398723 $365,500
141 519811 $403,950
142 351193 $345,000
143 451349 $330,000
144 874393 $927,000
145 1080208 $1,120,000
146 414406 $365,000
147 404688 $378,750
148 522941 $557,000
149 606899 $650,000
150 600432 $577,500
151 436181 $339,000
152 562982 $570,000
153 563500 $563,500
154 482242 $355,000
155 1560000 $1,550,000
156 647621 $625,000
157 522941 $538,000
158 398709 $375,000
159 619575 $1,300,000
160 404280 $397,000
161 1152875 $988,000
162 724117 $749,000
163 872264 $843,000
164 579297 $578,000
165 496520 $400,000
166 1030000 $1,030,000
167 503324 $505,000
168 503324 $475,000
169 1407875 $1,450,000
170 731200 $691,100
171 617713 $811,000
172 519811 $496,500
173 1024792 $1,050,000
174 398709 $290,900
175 519811 $520,000
176 440567 $460,000
177 351193 $315,000
178 484755 $378,500
179 522941 $525,000
180 951673 $1,070,000
181 271031 $207,950
182 720587 $699,900
183 883041 $1,280,000
184 460762 $452,000
185 625123 $669,950
186 437684 $397,500
187 724117 $725,000
188 617713 $625,000
189 519811 $437,500
190 625123 $650,000
191 468363 $442,000
192 617713 $615,000
193 586011 $585,000
194 519811 $480,000
195 600432 $615,000
196 868743 $890,000
197 217667 $190,000
198 329996 $275,000
199 618354 $727,500
200 1600000 $1,600,000
201 666642 $662,000
202 978283 $970,000
203 493137 $280,000
204 522941 $530,000
205 901000 $910,000
206 724117 $782,000
207 344180 $259,950
208 617713 $705,000
209 1148333 $1,450,000
210 724117 $725,000
211 1692500 $1,950,000
212 720587 $750,000
213 503324 $460,000
214 351193 $260,000
215 720587 $720,000
216 519811 $442,000
217 647621 $650,000
218 625123 $619,000
219 617713 $730,000
220 519811 $439,000
221 631063 $640,000
222 492223 $360,000
223 389840 $372,500
224 849199 $1,220,000
225 496520 $460,000
226 382707 $435,500
227 617713 $650,000
228 522941 $533,600
229 522941 $525,000
230 470406 $485,000
231 566420 $577,000
232 316839 $289,500
233 537035 $543,500
234 519811 $565,000
235 479996 $426,700
236 344180 $415,000
237 754939 $1,120,000
238 398709 $378,000
239 738367 $729,500
240 519811 $430,000
241 522941 $545,000
242 383212 $425,000
243 351193 $325,000
244 600432 $597,500
245 436512 $337,000
246 872264 $1,000,000
247 1413421 $3,070,000
248 758947 $748,000
249 617713 $888,000
250 503324 $496,500
251 351193 $323,000
252 409425 $331,000
253 665923 $664,000
254 503324 $497,000
255 347703 $188,000
256 503324 $478,500
257 951673 $1,150,000
258 519811 $413,000
259 736528 $802,541
260 519811 $507,000
261 405628 $396,000
262 1165000 $1,480,000
263 697001 $700,000
264 724117 $980,000
265 606899 $795,000
266 321139 $195,000
267 496507 $485,000
268 445588 $440,000
269 452115 $310,000
270 625123 $636,000
271 503324 $350,000
272 351193 $245,000
273 436512 $328,000
274 507031 $403,000
275 600432 $605,000
276 653544 $650,000
277 437684 $435,000
278 647621 $950,000
279 438166 $447,000
280 951673 $942,500
281 1185517 $1,310,000
282 460762 $405,600
283 332382 $400,000
284 389840 $330,000
285 503324 $405,300
286 724117 $824,000
287 348945 $341,500
288 351193 $390,000
289 496507 $493,000
290 340109 $305,000
291 457232 $400,000
292 496507 $460,000
293 452660 $408,200
294 522941 $522,000
295 951673 $1,360,000
296 514554 $470,000
297 902431 $1,220,000
298 445575 $422,120
299 351193 $385,200
300 514554 $500,000
301 600432 $565,000
302 398709 $419,000
303 499580 $347,000
304 611194 $625,000
305 2090000 $2,400,000
306 356385 $310,000
307 654231 $682,000
308 759067 $1,100,000
309 292314 $226,000
310 639104 $659,000
311 432674 $428,750
312 466680 $352,000
313 514554 $512,000
314 514554 $535,800
315 444212 $438,000
316 453877 $370,500
317 503324 $450,000
318 444212 $425,000
319 514554 $467,000
320 405628 $457,500
321 367417 $381,156
322 720587 $860,000
323 323264 $200,000
324 724117 $930,000
325 883041 $1,270,000
326 720587 $700,000
327 514554 $480,000
328 335692 $340,000
329 426794 $209,000
330 883041 $980,000
331 951673 $905,000
332 757191 $839,900
333 318391 $200,000
334 455285 $435,000
335 611194 $615,000
336 484755 $384,000
337 325179 $270,000
338 617713 $800,000
339 493137 $451,000
340 436181 $420,000
341 367417 $300,000
342 541244 $545,000
343 421805 $350,000
344 292314 $315,000
345 570777 $570,000
346 776035 $1,320,000
347 1002750 $1,030,000
348 398723 $435,000
349 808699 $851,000
350 514554 $550,000
351 460762 $378,000
352 650000 $650,000
353 488746 $335,000
354 493137 $440,000
355 522941 $532,500
356 522941 $524,250
357 794700 $765,000
358 351193 $427,200
359 769417 $718,000
360 398709 $420,000
361 405628 $399,000
362 514554 $484,950
363 246294 $178,500
364 514554 $515,000
365 522941 $540,000
366 496520 $475,000
367 450303 $429,000
368 340109 $164,808
369 509887 $520,000
370 316839 $375,000
371 383212 $349,500
372 438530 $446,450
373 509887 $543,115
374 796668 $768,000
375 1002750 $980,000
376 503324 $395,000
377 600432 $566,000
378 546985 $550,000
379 496520 $499,000
380 515046 $515,000
381 350938 $410,000
382 724117 $850,000
383 625123 $648,000
384 354460 $379,000
385 618354 $699,000
386 493137 $425,000
387 731200 $790,000
388 351193 $399,950
389 332382 $250,000
390 503324 $505,000
391 503324 $470,500
392 731200 $1,240,000
393 635061 $986,000
394 503324 $310,000
395 351193 $356,700
396 724117 $775,000
397 617713 $825,000
398 476911 $490,000
399 496507 $385,000
400 883041 $837,700
401 766050 $730,000
402 600432 $575,000
403 481275 $430,000
404 265028 $151,000
405 1560000 $1,570,000
406 606899 $631,000
407 398709 $285,000
408 802568 $817,500
409 606899 $609,850
410 351193 $200,000
411 647621 $660,000
412 606899 $624,000
413 509887 $552,500
414 329996 $239,000
415 905700 $975,000
416 951600 $1,200,000
417 496520 $302,000
418 350938 $170,000
419 332382 $195,000
420 460762 $272,000
421 460762 $369,000
422 351193 $269,000
423 1269576 $1,280,000
424 720587 $687,500
425 356385 $252,500
426 509887 $510,000
427 486048 $425,000
428 1131009 $1,960,000
429 720587 $699,000
430 724117 $790,000
431 488746 $315,000
432 509887 $435,000
433 509887 $482,500
434 444212 $460,000
435 606899 $605,000
436 382707 $359,000
437 606899 $850,000
438 595041 $565,000
439 600432 $585,000
440 724117 $826,000
441 522941 $535,000
442 874393 $925,000
443 951673 $875,000
444 724117 $902,000
445 351193 $235,000
446 475515 $405,000
447 606899 $655,000
448 456842 $357,000
449 617713 $630,000
450 492223 $472,800
451 452115 $263,000
452 509528 $510,000
453 509528 $525,000
454 647621 $651,000
455 503324 $470,000
456 509528 $485,500
457 1297500 $1,880,000
458 724117 $735,000
459 720587 $680,000
460 466680 $349,000
461 503324 $360,000
462 606899 $659,000
463 617713 $645,000
464 503324 $350,000
465 398709 $375,000
466 808699 $780,000
467 351193 $276,900
468 503324 $495,000
469 591377 $600,000
470 606899 $609,000
471 522941 $530,000
472 606837 $614,000
473 503324 $484,000
474 509528 $441,500
475 1584375 $2,300,000
476 503678 $403,000
477 509528 $445,000
478 340109 $345,000
479 951673 $2,260,000
480 351193 $355,000
481 356385 $420,000
482 837321 $925,000
483 398709 $389,250
484 351193 $275,000
485 325607 $316,000
486 509528 $530,000
487 5300000 $5,300,000
488 463187 $432,000
489 460762 $455,000
490 617713 $625,000
491 724117 $788,500
492 606899 $805,000
493 496520 $495,000
494 842593 $825,000
495 409425 $445,950
496 883041 $960,000
497 724117 $735,000
498 508195 $450,000
499 837321 $842,500
500 351193 $345,000
501 625123 $643,000
502 720587 $815,000
503 1692500 $2,200,000
504 720587 $700,000
505 721739 $933,399
506 628877 $672,000
507 356385 $334,000
508 347703 $260,000
509 617713 $749,950
510 389206 $225,000
511 508195 $505,000
512 460762 $250,000
513 720587 $719,000
514 348945 $325,000
515 1060000 $1,060,000
516 510274 $542,000
517 314792 $280,000
518 635797 $658,588
519 383212 $300,000

520 720587 $750,000
521 385977 $245,000
522 496507 $445,000
523 522941 $530,000
524 1215958 $1,700,000
525 385977 $389,000
526 1152875 $1,400,000
527 508195 $470,000
528 868743 $914,600
529 286499 $265,000
530 432674 $459,000
531 503324 $491,500
532 600432 $566,000
533 5350000 $5,350,000
534 314792 $235,867
535 452660 $382,000
536 752604 $755,000
537 720587 $757,000
538 720587 $765,000
539 503324 $440,000
540 953000 $1,330,000
541 508195 $519,500
542 405628 $400,000
543 720587 $701,000
544 640000 $640,000
545 336602 $250,000
546 508195 $514,000
547 536561 $532,000
548 508195 $423,000
549 398709 $420,000
550 1151531 $1,220,000
551 724117 $720,000
552 606899 $612,000
553 606899 $850,000
554 508195 $442,000
555 245790 $190,000
556 611194 $610,000
557 503324 $500,000
558 503324 $405,000
559 724117 $775,000
560 488746 $425,000
561 724117 $810,000
562 720587 $819,000
563 457682 $409,900
564 720587 $935,000
565 847272 $900,000
566 452115 $391,000
567 540742 $420,000
568 449430 $350,000
569 503324 $495,000
570 503324 $503,000
571 724117 $957,500
572 347703 $343,000
573 883041 $937,500
574 618354 $720,000
575 438822 $434,500
576 606899 $607,010
577 724117 $828,500
578 759067 $789,500
579 720587 $797,000
580 540742 $539,950
581 540742 $525,000
582 600432 $605,000
583 384073 $380,000
584 351193 $352,000
585 503324 $420,000
586 732124 $1,180,000
587 617713 $1,380,000
588 460762 $453,500
589 661901 $655,000
590 847272 $900,000
591 344180 $327,500
592 453877 $390,000
593 398235 $455,000
594 724117 $800,000
595 720587 $703,770
596 883041 $780,000
597 484755 $285,000
598 617713 $667,500
599 540742 $537,500
600 423416 $425,000
601 377186 $349,500
602 340109 $370,000
603 284409 $245,000
604 522941 $520,000
605 496520 $415,000
606 503324 $495,000
607 429387 $440,000
608 844258 $810,000
609 488822 $450,000
610 600432 $570,000
611 475515 $450,000
612 452660 $272,750
613 322053 $284,950
614 496520 $400,000
615 516730 $490,000
616 496520 $331,500
617 842593 $830,000
618 647621 $662,990
619 470406 $349,950
620 468363 $396,000
621 426794 $275,000
622 503324 $445,000
623 758947 $1,230,000
624 951673 $874,150
625 351193 $281,000
626 745446 $749,000
627 351193 $340,000
628 522941 $561,000
629 505960 $469,000
630 516730 $550,000
631 617713 $800,000
632 387403 $360,000
633 883041 $830,000
634 351193 $345,000
635 449430 $300,000
636 351193 $350,000
637 1680000 $1,680,000
638 389840 $337,000
639 1456812 $1,930,000
640 516730 $544,500
641 318391 $252,000
642 516730 $445,000
643 516730 $379,500
644 458605 $469,000
645 745446 $785,000
646 516730 $445,000
647 516730 $508,000
648 516730 $541,100
649 724117 $729,000
650 451555 $451,555
651 453877 $416,000
652 553603 $480,000
653 366017 $368,000
654 1165000 $1,040,000
655 553603 $545,000
656 883041 $850,000
657 600432 $599,950
658 553603 $531,000
659 553603 $530,000
660 600432 $597,326
661 479461 $299,000
662 553603 $400,000
663 503324 $467,500
664 351193 $210,000
665 898395 $883,000
666 978283 $901,000
667 553603 $552,500
668 272719 $256,000
669 720587 $686,000
670 769417 $950,000
671 720756 $780,000
672 470406 $212,000
673 606899 $615,000
674 553603 $519,000
675 978283 $1,140,000
676 460762 $240,000
677 566420 $574,000
678 452115 $415,000
679 600432 $589,000
680 522941 $477,000
681 869500 $1,430,000
682 553603 $453,250
683 606899 $607,000
684 496507 $255,000
685 503324 $450,000
686 485377 $460,000
687 398709 $389,950
688 553603 $550,000
689 1230818 $1,530,000
690 1086042 $1,100,000
691 706064 $720,000
692 793829 $905,000
693 731200 $762,500
694 600432 $580,000
695 1570000 $1,570,000
696 444212 $386,500
697 351193 $210,000
698 617713 $655,000
699 398709 $405,000
700 724117 $765,000
701 606899 $625,000
702 637701 $668,000
703 625123 $618,000
704 479996 $345,000
705 817768 $850,000
706 902431 $832,000
707 445575 $350,000
708 539634 $349,000
709 457232 $320,000
710 724117 $785,500
711 570777 $550,000
712 1236225 $1,580,000
713 606899 $599,000
714 503324 $485,000
715 819727 $1,050,000
716 301553 $315,000
717 600432 $590,000
718 587994 $439,950
719 606899 $577,000
720 503324 $500,000
721 228225 $265,000
722 445588 $467,000
723 395770 $316,500
724 496520 $378,000
725 503324 $333,800
726 706064 $690,000
727 448700 $320,000
728 831567 $840,000
729 522941 $550,000
730 842593 $998,000
731 496520 $483,945
732 600432 $590,000
733 600432 $605,000
734 351193 $375,000
735 503324 $471,750
736 535690 $490,000
737 280196 $250,000
738 724117 $780,000
739 398709 $409,000
740 600432 $562,500
741 351193 $310,000
742 600432 $500,000
743 587027 $335,000
744 869322 $962,000
745 414454 $299,000
746 325179 $194,000
747 550574 $560,000
748 484567 $463,500
749 647621 $760,000
750 625123 $630,000
751 460762 $275,000
752 883041 $835,000
753 503324 $475,000
754 293471 $235,000
755 550574 $475,000
756 332382 $210,000
757 351193 $350,000
758 522941 $505,000
759 503324 $464,900
760 656487 $650,000
761 445588 $250,000
762 445588 $320,000
763 769417 $940,000
764 389206 $399,950
765 550574 $528,000
766 546985 $545,000
767 485377 $380,000
768 314792 $320,000
769 398723 $439,900
770 503324 $460,000
771 724117 $884,250
772 316782 $235,000
773 720587 $767,500
774 654983 $1,200,000
775 871962 $822,500
776 724117 $800,000
777 2765000 $3,850,000
778 978283 $1,200,000
779 731200 $750,000
780 721263 $1,030,000
781 617713 $700,000
782 491000 $491,000
783 366907 $310,000
784 503324 $490,000
785 1216600 $1,640,000
786 950333 $989,000
787 503324 $491,500
788 380926 $345,000
789 582677 $585,000
790 724117 $723,000
791 600432 $594,000
792 351193 $330,000
793 618354 $678,500
794 538119 $463,000
795 259969 $250,000
796 617713 $655,000
797 380926 $251,700
798 724117 $735,000
799 759067 $765,000
800 724117 $950,000
801 600432 $585,000
802 503324 $525,000
803 410000 $410,000
804 600432 $570,000
805 400104 $345,000
806 617713 $638,000
807 496520 $460,000
808 787170 $760,000
809 990390 $1,090,000
810 336903 $234,000
811 766050 $1,650,000
812 883041 $1,550,000
813 351193 $150,000
814 400104 $330,000
815 606899 $605,000
816 731200 $750,000
817 485377 $490,000
818 600432 $585,000
819 606899 $612,000
820 606899 $604,000
821 731200 $783,000
822 898395 $1,050,000
823 351193 $276,000
824 891600 $1,030,000
825 600432 $564,500
826 400104 $257,000
827 662062 $665,000
828 618693 $670,000
829 452115 $465,000
830 600432 $600,000
831 606899 $608,000
832 1760000 $1,760,000
833 325460 $315,000
834 883041 $1,000,000
835 348945 $280,005
836 336602 $330,000
837 438530 $468,000
838 1584375 $1,340,000
839 522941 $515,000
840 579960 $455,000
841 2750000 $2,750,000
842 398709 $418,000
843 637701 $660,000
844 438822 $429,500
845 522941 $517,100
846 488822 $354,950
847 302247 $322,500
848 978283 $860,000
849 496507 $302,000
850 744372 $993,000
851 447043 $380,000
852 332382 $260,000
853 325179 $243,000
854 787170 $1,400,000
855 522941 $471,000
856 457327 $450,000
857 496520 $437,000
858 449430 $270,000
859 445000 $445,000
860 246294 $250,000
861 314792 $307,000
862 570777 $555,000
863 978283 $1,370,000
864 522941 $545,000
865 708274 $705,380
866 620665 $625,000
867 323264 $172,500
868 570777 $554,000
869 758947 $775,000
870 503324 $500,000
871 629329 $665,000
872 720587 $1,100,000
873 720587 $674,750
874 647621 $719,000
875 496507 $437,000
876 496507 $400,000
877 650000 $650,000
878 724117 $995,000
879 496520 $335,000
880 503324 $446,000
881 1540000 $1,540,000
882 325179 $325,000
883 484755 $453,000
884 659616 $655,000
885 808699 $810,000
886 625123 $625,000
887 351193 $335,000
888 351193 $286,700
889 600432 $580,000
890 525000 $525,000
891 778545 $808,900
892 765034 $992,000
893 883041 $1,600,000
894 503324 $355,000
895 951673 $985,000
896 398709 $349,950
897 600432 $520,000
898 951673 $1,130,000
899 457327 $200,000
900 942877 $913,000
901 841891 $1,600,000
902 351193 $265,000
903 436512 $381,000
904 1097467 $1,220,000
905 750661 $739,900
906 695123 $674,250
907 2106000 $1,700,000
908 614874 $703,000
909 546985 $500,000
910 841891 $1,280,000
911 765034 $1,870,000
912 837321 $1,220,000
913 351193 $236,500
914 351193 $294,000
915 750661 $1,010,000
916 398709 $335,000
917 543599 $540,000
918 332382 $195,000
919 573818 $560,000
920 421805 $260,000
921 557622 $575,000
922 522941 $475,000
923 492223 $285,000
924 775398 $753,888
925 625123 $650,000
926 522941 $526,000
927 245790 $155,000
928 371812 $390,000
929 696607 $685,000
930 460762 $462,000
931 557622 $545,000
932 467248 $415,000
933 611194 $627,000
934 878000 $865,000
935 600432 $595,000
936 661000 $661,000
937 503324 $419,950
938 557622 $552,500
939 720587 $715,000
940 336602 $175,000
941 731200 $785,000
942 731200 $890,000
943 606899 $612,000
944 490300 $493,000
945 1197500 $1,620,000
946 1197500 $1,650,000
947 490300 $499,000
948 600432 $603,500
949 503324 $530,000
950 883041 $895,000
951 462507 $439,950
952 462507 $455,000
953 661901 $690,000
954 741852 $965,000
955 617713 $675,000
956 398235 $387,000
957 301553 $265,000
958 404280 $375,000
959 720587 $1,070,000
960 462507 $352,500
961 317539 $320,000
962 741852 $733,000
963 351193 $343,000
964 522941 $525,000
965 325179 $300,000
966 600432 $561,000
967 502925 $540,000
968 317397 $210,000
969 861675 $1,170,000
970 1600000 $1,600,000
971 606899 $606,000
972 522941 $530,000
973 600432 $590,000
974 411633 $395,000
975 617713 $739,000
976 891250 $895,000
977 638947 $645,000
978 953604 $1,000,000
979 503324 $500,000
980 600432 $523,000
981 522941 $558,000
982 1380000 $1,380,000
983 351193 $311,000
984 496520 $470,000
985 570777 $569,000
986 720587 $689,000
987 398723 $399,500
988 724117 $725,786
989 351193 $315,500
990 409425 $312,000
991 503324 $415,000
992 470676 $369,990
993 505960 $349,950
994 720587 $705,000
995 265028 $184,500
996 398709 $412,000
997 628877 $662,700
998 356385 $383,000
999 600432 $610,000
1000 520400 $545,000
1001 1110000 $1,110,000
1002 351193 $326,500
1003 437867 $365,000
1004 787133 $1,000,000
1005 452115 $390,000
1006 741852 $749,999
1007 600432 $570,000
1008 724117 $700,000
1009 744372 $1,150,000
1010 720587 $726,000
1011 736528 $856,000
1012 883041 $866,059
1013 522941 $410,000
1014 951673 $860,000
1015 548793 $555,000
1016 409425 $385,000
1017 496507 $199,000
1018 600432 $604,000
1019 414454 $268,000

1020 503324 $509,250
1021 452660 $416,000
1022 575233 $560,000
1023 681248 $665,000
1024 485377 $375,000
1025 488746 $359,950
1026 625123 $638,500
1027 523044 $524,000
1028 1215958 $1,610,000
1029 351193 $280,000
1030 724117 $828,000
1031 617253 $750,000
1032 724117 $711,000
1033 489798 $415,000
1034 523044 $525,000
1035 444212 $330,000
1036 883041 $845,000
1037 259969 $157,500
1038 1215958 $1,390,000
1039 329504 $332,000
1040 522941 $459,950
1041 387403 $425,000
1042 731200 $864,000
1043 854654 $900,000
1044 325179 $162,000
1045 496520 $450,000
1046 496520 $490,000
1047 523044 $515,000
1048 503324 $478,000
1049 1373232 $1,400,000
1050 600432 $593,500
1051 493137 $306,000
1052 389840 $399,950
1053 539634 $534,000
1054 600432 $582,000
1055 828443 $799,000
1056 522941 $423,700
1057 1840000 $1,840,000
1058 437684 $441,500
1059 803996 $875,000
1060 445575 $425,000
1061 576114 $499,000
1062 445588 $335,000
1063 492223 $334,000
1064 503324 $525,000
1065 1123333 $1,050,000
1066 470676 $402,000
1067 522941 $520,000
1068 398709 $406,650
1069 323264 $180,000
1070 978283 $1,250,000
1071 400291 $355,000
1072 1818300 $3,000,000
1073 351193 $311,000
1074 731200 $769,000
1075 457682 $430,000
1076 503324 $510,000
1077 265028 $205,000
1078 496520 $455,000
1079 460762 $372,000
1080 317397 $160,000
1081 590788 $570,000
1082 285000 $295,000
1083 551043 $380,000
1084 460762 $315,000
1085 314792 $230,000
1086 568202 $550,000
1087 590788 $580,000
1088 476911 $438,000
1089 583206 $590,000
1090 787133 $1,200,000
1091 398709 $415,000
1092 724117 $900,000
1093 367423 $378,000
1094 522941 $464,000
1095 503324 $510,000
1096 720587 $855,000
1097 318391 $219,500
1098 503324 $495,000
1099 496520 $390,000
1100 754939 $740,000
1101 769417 $991,700
1102 731200 $765,000
1103 724117 $802,000
1104 731200 $950,000
1105 515046 $425,000
1106 883041 $765,000
1107 404280 $313,500
1108 606899 $604,000
1109 625123 $639,000
1110 496507 $335,000
1111 460762 $441,000
1112 436512 $228,800
1113 535690 $430,000
1114 502925 $449,000
1115 720587 $945,000
1116 664758 $659,500
1117 522941 $540,000
1118 259969 $202,000
1119 2530000 $2,530,000
1120 448700 $453,000
1121 351193 $367,000
1122 565600 $550,000
1123 322053 $310,000
1124 479996 $285,000
1125 1604965 $2,300,000
1126 782175 $763,776
1127 351193 $362,000
1128 351193 $386,900
1129 484755 $479,000
1130 522941 $525,000
1131 716212 $716,000
1132 301553 $308,000
1133 720587 $800,000
1134 724117 $770,000
1135 446326 $424,950
1136 446326 $387,000
1137 171667 $156,000
1138 600432 $580,000
1139 398723 $400,000
1140 272719 $311,000
1141 446326 $200,000
1142 606899 $708,000
1143 606899 $691,000
1144 1382250 $2,290,000
1145 301553 $210,000
1146 351193 $285,000
1147 314792 $190,000
1148 436512 $400,000
1149 199975 $89,950
1150 316839 $158,800
1151 807228 $870,000
1152 729748 $850,000
1153 792390 $775,000
1154 446326 $483,500
1155 432674 $387,000
1156 400291 $336,000
1157 398709 $415,000
1158 1320000 $1,320,000
1159 628877 $765,000
1160 600432 $527,000
1161 536697 $524,000
1162 724117 $775,000
1163 724117 $750,000
1164 351193 $250,000
1165 731200 $759,000
1166 617713 $640,000
1167 522941 $390,000
1168 600432 $589,000
1169 600432 $580,000
1170 385925 $345,000
1171 377186 $402,500
1172 437867 $426,000
1173 485377 $389,000
1174 720587 $670,000
1175 447043 $288,400
1176 868500 $830,000
1177 606899 $720,000
1178 414429 $415,000
1179 606899 $700,000
1180 475515 $285,000
1181 452660 $410,000
1182 522941 $520,000
1183 476489 $450,000
1184 793829 $850,000
1185 389840 $249,000
1186 842593 $1,140,000
1187 476489 $445,000
1188 516239 $537,000
1189 869322 $805,000
1190 460762 $178,000
1191 293471 $255,000
1192 460762 $442,000
1193 625123 $637,250
1194 400291 $427,500
1195 690498 $680,000
1196 521446 $525,000
1197 654231 $632,500
1198 503324 $405,000
1199 522941 $551,000
1200 775398 $1,900,000
1201 978283 $965,000
1202 720587 $739,000
1203 493137 $491,500
1204 496507 $464,000
1205 883041 $1,000,000
1206 488748 $439,000
1207 1215958 $1,210,000
1208 1215958 $1,100,000
1209 586653 $580,000
1210 398709 $380,000
1211 381910 $425,000
1212 724117 $732,000
1213 714193 $805,500
1214 503324 $507,250
1215 503324 $456,500
1216 883041 $1,310,000
1217 933394 $843,500
1218 1245566 $1,970,000
1219 724117 $725,000
1220 318391 $315,000
1221 714193 $700,000
1222 351193 $363,000
1223 724117 $820,000
1224 335692 $289,000
1225 318391 $334,000
1226 512684 $430,000
1227 522941 $400,000
1228 503324 $325,000
1229 470406 $410,000
1230 502925 $445,000
1231 724117 $921,000
1232 389206 $359,000
1233 570777 $555,000
1234 398709 $400,000
1235 600432 $437,500
1236 819727 $865,000
1237 606899 $626,000
1238 1358617 $2,080,000
1239 453877 $425,000
1240 666642 $675,000
1241 440567 $395,000
1242 883041 $1,100,000
1243 429387 $374,500
1244 503324 $490,000
1245 323264 $160,000
1246 522941 $542,000
1247 702078 $700,000
1248 369409 $356,000
1249 617713 $625,000
1250 983750 $970,000
1251 492818 $415,000
1252 492818 $485,000
1253 778545 $799,950
1254 606899 $950,000
1255 872264 $895,000
1256 591727 $579,000
1257 398709 $369,900
1258 351193 $160,000
1259 617713 $650,000
1260 519668 $515,000
1261 724117 $756,000
1262 314792 $368,000
1263 456842 $445,000
1264 348945 $250,000
1265 724117 $732,350
1266 579297 $414,000
1267 522941 $550,000
1268 625123 $1,100,000
1269 933394 $1,280,000
1270 354460 $355,000
1271 276000 $276,000
1272 278410 $100,000
1273 724117 $955,500
1274 752590 $762,000
1275 444212 $425,000
1276 546000 $546,000
1277 724117 $735,000
1278 1087500 $1,290,000
1279 754939 $1,080,000
1280 1129562 $1,230,000
1281 805000 $805,000
1282 618693 $749,700
1283 377160 $330,000
1284 469792 $479,200
1285 460762 $355,000
1286 444212 $380,000
1287 1215958 $1,170,000
1288 647621 $629,000
1289 469792 $415,000
1290 600432 $595,000
1291 245790 $119,900
1292 351193 $325,088
1293 769417 $790,000
1294 351193 $255,000
1295 724117 $980,000
1296 617713 $619,420
1297 503324 $500,000
1298 600432 $569,000
1299 503324 $425,000
1300 617713 $635,000
1301 346357 $454,200
1302 731200 $749,950
1303 1250000 $1,250,000
1304 600432 $570,000
1305 769417 $700,000
1306 1339362 $1,580,000
1307 883041 $865,000
1308 570777 $548,500
1309 346357 $175,000
1310 460762 $326,000
1311 724117 $690,000
1312 841891 $805,000
1313 583969 $557,500
1314 351193 $385,000
1315 522941 $539,950
1316 522941 $529,000
1317 409425 $417,000
1318 429387 $405,000
1319 373421 $372,220
1320 741852 $760,000
1321 351193 $360,000
1322 560650 $521,000
1323 503324 $330,000
1324 1373232 $1,600,000
1325 724117 $862,000
1326 404280 $432,250
1327 503324 $495,000
1328 951673 $889,000
1329 618693 $625,000
1330 325179 $328,000
1331 429156 $502,500
1332 479461 $484,000
1333 606899 $610,000
1334 874393 $850,000
1335 404280 $410,000
1336 503324 $510,000
1337 436181 $435,000
1338 567241 $550,000
1339 617713 $830,000
1340 794700 $803,000
1341 344180 $200,000
1342 317539 $219,000
1343 724117 $777,000
1344 600432 $593,700
1345 617713 $712,500
1346 600432 $600,000
1347 429156 $335,000
1348 724117 $938,000
1349 625123 $634,000
1350 496507 $337,500
1351 398709 $400,000
1352 1037500 $1,290,000
1353 503324 $435,000
1354 661901 $681,000
1355 731200 $772,500
1356 611194 $620,000
1357 503324 $475,000
1358 511298 $527,500
1359 496507 $430,000
1360 618354 $641,000
1361 496507 $436,300
1362 731200 $830,000
1363 353700 $380,000
1364 280196 $132,500
1365 617713 $659,000
1366 496507 $317,000
1367 611194 $625,000
1368 617713 $610,000
1369 389840 $367,500
1370 265028 $230,000
1371 352636 $286,000
1372 510136 $525,000
1373 363025 $421,000
1374 731200 $735,000
1375 856707 $884,900
1376 766050 $775,000
1377 936275 $866,500
1378 766350 $800,000
1379 336602 $277,284
1380 503324 $460,000
1381 351193 $211,000
1382 496507 $320,000
1383 457327 $455,000
1384 1605000 $2,450,000
1385 453877 $325,000
1386 548362 $495,000
1387 403944 $345,100
1388 316839 $200,000
1389 600432 $598,600
1390 403944 $367,777
1391 731200 $750,000
1392 582677 $575,000
1393 246294 $255,000
1394 403944 $415,000
1395 891600 $899,000
1396 625123 $680,000
1397 600432 $605,000
1398 731200 $759,000
1399 366860 $411,000
1400 351193 $149,000
1401 351193 $284,700
1402 618354 $816,000
1403 550011 $533,250
1404 596190 $586,000
1405 724117 $680,000
1406 582500 $582,500
1407 606899 $637,000
1408 329504 $225,000
1409 720587 $795,000
1410 314792 $240,000
1411 724117 $772,000
1412 393303 $430,000
1413 724117 $750,000
1414 522941 $532,000
1415 460762 $460,000
1416 414429 $445,000
1417 1216600 $1,580,000
1418 883041 $856,000
1419 393303 $414,250
1420 393303 $399,950
1421 522941 $524,000
1422 351193 $349,950
1423 351193 $300,000
1424 600432 $585,000
1425 567241 $576,750
1426 503324 $495,000
1427 724117 $675,000
1428 515092 $510,000
1429 351193 $210,000
1430 724117 $1,080,000
1431 625123 $756,000
1432 445575 $203,000
1433 522941 $525,000
1434 432674 $347,500
1435 606899 $620,000
1436 625123 $645,000
1437 720587 $790,000
1438 460762 $442,000
1439 536714 $490,000
1440 837321 $1,330,000
1441 2950000 $2,950,000
1442 481275 $387,000
1443 325607 $216,000
1444 371148 $390,000
1445 371148 $357,000
1446 265000 $265,000
1447 600432 $589,950
1448 274939 $248,000
1449 720587 $730,000
1450 664758 $680,000
1451 665923 $695,500
1452 398709 $418,000
1453 978283 $876,650
1454 351193 $330,000
1455 546985 $550,000
1456 720587 $978,500
1457 746829 $975,000
1458 503324 $455,000
1459 978283 $1,420,000
1460 562548 $420,000
1461 400291 $357,823
1462 7060000 $7,060,000
1463 724117 $711,777
1464 724117 $825,000
1465 351193 $210,000
1466 1584375 $1,210,000
1467 1215958 $1,500,000
1468 1334992 $1,300,000
1469 522941 $515,000
1470 325179 $315,000
1471 638947 $675,000
1472 460762 $400,000
1473 395770 $355,000
1474 389840 $210,000
1475 329504 $265,000
1476 696607 $700,000
1477 951673 $1,020,000
1478 724117 $1,150,000
1479 503324 $460,000
1480 647621 $665,000
1481 600432 $600,000
1482 399482 $364,950
1483 600432 $576,000
1484 399482 $405,000
1485 479996 $450,000
1486 322053 $210,000
1487 351193 $355,000
1488 731200 $735,000
1489 265028 $155,000
1490 351193 $354,000
1491 186667 $202,000
1492 978283 $1,500,000
1493 522941 $499,900
1494 780495 $810,000
1495 351193 $291,000
1496 606899 $645,000
1497 247500 $247,500
1498 395770 $395,000
1499 321139 $235,000
1500 617713 $639,000
1501 522941 $525,000
1502 758947 $2,400,000
1503 769417 $1,390,000
1504 522941 $521,450
1505 419179 $346,150
1506 419179 $430,000
1507 951673 $960,000
1508 724117 $1,350,000
1509 720587 $777,000
1510 522941 $550,000
1511 419179 $325,000
1512 419179 $365,000
1513 3140000 $2,150,000
1514 419179 $390,000
1515 625123 $619,000
1516 419179 $412,450
1517 419179 $227,064
1518 336903 $339,888
1519 419179 $439,000
1520 606899 $703,011
1521 351193 $363,000
1522 606899 $650,000
1523 336602 $299,950
1524 720587 $725,000
1525 363025 $300,000
1526 617713 $979,000
1527 438822 $435,000
1528 522941 $555,750
1529 358545 $262,500
1530 522941 $499,500
1531 458605 $462,500
1532 841891 $845,000
1533 660000 $660,000
1534 978283 $1,060,000
1535 418889 $359,950
1536 457232 $417,000
1537 942062 $1,040,000
1538 496520 $462,600
1539 456842 $340,000
1540 617713 $661,000
1541 625123 $635,000
1542 503324 $480,000
1543 486048 $360,000
1544 522941 $525,000
1545 335692 $292,000
1546 720587 $700,000
1547 600432 $545,000
1548 912273 $1,210,000
1549 522941 $545,000
1550 720587 $701,000
1551 432433 $430,000
1552 293471 $260,600
1553 432433 $435,000
1554 496520 $522,500
1555 351193 $240,000
1556 562982 $523,000
1557 883041 $1,190,000
1558 432433 $438,000
1559 340109 $340,000
1560 502925 $489,200
1561 426794 $393,500
1562 470676 $360,000
1563 351193 $400,800
1564 600432 $585,000
1565 617713 $665,900
1566 558467 $470,000
1567 600432 $581,000
1568 351193 $410,000
1569 606899 $606,000
1570 503324 $373,000
1571 522941 $480,680
1572 452660 $305,000
1573 1081195 $1,880,000
1574 763333 $1,570,000
1575 339750 $356,000
1576 409425 $390,000
1577 457232 $509,500
1578 543828 $475,000
1579 339750 $268,000
1580 600432 $562,000
1581 724117 $780,000
1582 793514 $815,000
1583 776035 $865,000
1584 606899 $615,000
1585 828443 $865,000
1586 724117 $755,000
1587 367750 $375,000
1588 724117 $750,000
1589 720587 $722,000
1590 739100 $1,010,000
1591 720756 $725,000
1592 1300000 $1,300,000
1593 625123 $619,500
1594 476911 $435,000
1595 1235000 $2,400,000
1596 385925 $394,900
1597 883041 $858,000
1598 746829 $1,280,000
1599 724117 $730,000
1600 600432 $585,000
1601 351193 $326,500
1602 708274 $1,160,000
1603 720587 $1,190,000
1604 883041 $899,100
1605 351193 $330,000
1606 625123 $649,950
1607 398709 $386,000
1608 487814 $430,000
1609 674145 $688,000
1610 695123 $834,500
1611 373421 $402,500
1612 502440 $432,500
1613 447043 $455,000
1614 378556 $371,000
1615 382707 $395,000
1616 378556 $330,000
1617 347703 $290,000
1618 724117 $705,000
1619 902431 $2,130,000
1620 378556 $348,500
1621 378556 $370,000
1622 746923 $715,000
1623 354094 $360,000
1624 625123 $659,950
1625 496507 $458,500
1626 344180 $259,950
1627 763333 $978,000
1628 720587 $926,300
1629 600432 $600,000
1630 978283 $1,140,000
1631 463187 $453,000
1632 724117 $800,000
1633 477318 $490,000
1634 503324 $499,950
1635 477318 $352,800
1636 466680 $350,000
1637 769417 $1,050,000
1638 383212 $353,000
1639 694045 $717,550
1640 470676 $450,000
1641 286499 $167,500
1642 724117 $939,000
1643 606899 $700,000
1644 600432 $580,000
1645 503324 $527,550
1646 483378 $240,000
1647 438530 $335,000
1648 522941 $475,000
1649 978283 $1,150,000
1650 600432 $575,000
1651 935662 $1,090,000
1652 600432 $515,000
1653 1456812 $2,050,000
1654 769417 $1,710,000
1655 570777 $565,000
1656 911000 $911,000
1657 398709 $425,000
1658 398709 $425,000
1659 460762 $374,950
1660 451349 $475,000
1661 731200 $1,340,000
1662 351193 $325,000
1663 1337875 $1,670,000
1664 451836 $448,000
1665 720587 $819,000
1666 720587 $685,000
1667 398709 $379,500
1668 606899 $620,000
1669 522941 $477,590
1670 456842 $263,500
1671 367417 $369,000
1672 351193 $197,500
1673 488746 $468,000
1674 617713 $639,000
1675 1148333 $1,050,000
1676 654231 $670,000
1677 340109 $294,000
1678 445575 $360,000
1679 522941 $520,000
1680 2000000 $2,000,000
1681 363025 $306,500
1682 617713 $716,000
1683 769417 $950,000
1684 453877 $393,000
1685 522941 $525,000

1686 503324 $518,000
1687 522941 $535,000
1688 647621 $785,200
1689 452115 $285,000
1690 548105 $425,000
1691 317397 $260,000
1692 423416 $369,000
1693 720587 $1,240,000
1694 746829 $875,000
1695 460762 $320,000
1696 681195 $810,000
1697 351193 $265,000
1698 503324 $418,000
1699 482242 $430,000
1700 837321 $1,440,000
1701 265028 $195,000
1702 351193 $300,000
1703 503324 $530,000
1704 409425 $397,500
1705 479731 $466,000
1706 381910 $280,000
1707 400291 $412,000
1708 479731 $454,000
1709 503324 $540,000
1710 1335569 $1,260,000
1711 479731 $500,000
1712 503324 $549,900
1713 724117 $760,000
1714 316839 $319,000
1715 647621 $640,000
1716 938333 $1,050,000
1717 460762 $456,000
1718 414429 $369,950
1719 347703 $345,000
1720 883041 $851,000
1721 720587 $900,000
1722 522941 $534,500
1723 606899 $643,500
1724 496520 $495,000
1725 471557 $435,000
1726 688961 $700,000
1727 724117 $760,000
1728 336602 $240,000
1729 470676 $325,000
1730 476911 $291,700
1731 951673 $1,130,000
1732 1275000 $1,160,000
1733 1181667 $1,410,000
1734 583375 $369,900
1735 978283 $1,020,000
1736 853838 $865,000
1737 1172150 $2,490,000
1738 853838 $810,000
1739 611194 $652,500
1740 503324 $360,000
1741 245790 $208,000
1742 568202 $560,000
1743 302247 $280,000
1744 125000 $125,000
1745 438822 $390,000
1746 387403 $425,000
1747 600432 $605,000
1748 323264 $302,000
1749 720587 $886,000
1750 498275 $435,000
1751 498275 $409,000
1752 351193 $405,000
1753 575217 $560,200
1754 522941 $441,500
1755 457327 $375,000
1756 1172150 $1,350,000
1757 724117 $949,880
1758 570777 $570,000
1759 724117 $736,000
1760 617713 $670,000
1761 654700 $650,000
1762 720587 $765,000
1763 828443 $828,200
1764 488822 $540,000
1765 551305 $423,000
1766 599900 $599,900
1767 883041 $1,080,000
1768 532435 $558,000
1769 351193 $354,000
1770 1191667 $1,200,000
1771 690498 $670,000
1772 350938 $333,000
1773 301333 $323,000
1774 583206 $575,000
1775 398709 $328,000
1776 385977 $415,000
1777 731200 $800,000
1778 369409 $420,000
1779 347703 $266,000
1780 600432 $499,000
1781 457327 $440,000
1782 385925 $424,000
1783 724117 $760,000
1784 377186 $379,600
1785 551613 $530,000
1786 883300 $925,000
1787 570777 $565,000
1788 398709 $405,100
1789 383212 $425,000
1790 308900 $330,000
1791 1230818 $1,490,000
1792 503324 $353,000
1793 305572 $260,000
1794 653544 $921,000
1795 314792 $220,000
1796 457682 $372,977
1797 724117 $975,000
1798 2027857 $1,850,000
1799 600432 $600,000
1800 384073 $357,186
1801 720587 $717,000
1802 475353 $470,000
1803 475353 $497,000
1804 351193 $371,000
1805 475353 $379,000
1806 600432 $616,000
1807 600432 $605,000
1808 351193 $369,950
1809 398723 $410,000
1810 611194 $650,000
1811 453877 $437,500
1812 555183 $567,000
1813 329996 $255,000
1814 351193 $285,000
1815 503324 $475,000
1816 606899 $650,500
1817 617713 $760,000
1818 503324 $480,000
1819 720587 $689,000
1820 377386 $415,000
1821 351193 $339,950
1822 336903 $210,000
1823 522941 $440,000
1824 438166 $375,000
1825 428000 $428,000
1826 336903 $382,500
1827 600432 $596,000
1828 720587 $679,950
1829 600432 $600,000
1830 883041 $950,000
1831 653544 $700,000
1832 409425 $275,000
1833 409425 $369,500
1834 883041 $825,000
1835 1048644 $930,000
1836 468100 $325,000
1837 293471 $255,000
1838 906455 $952,000
1839 720587 $721,000
1840 468100 $487,275
1841 322053 $245,000
1842 522941 $550,000
1843 351193 $350,000
1844 808699 $815,000
1845 575095 $572,000
1846 414429 $419,500
1847 496507 $455,000
1848 606899 $620,000
1849 606899 $620,000
1850 691227 $690,000
1851 1131009 $1,900,000
1852 1131009 $1,940,000
1853 739100 $832,500
1854 673200 $653,000
1855 951673 $970,000
1856 414454 $268,000
1857 457682 $440,000
1858 625123 $635,000
1859 606899 $625,000
1860 429800 $425,000
1861 568658 $572,000
1862 325179 $278,000
1863 452660 $474,900
1864 429800 $450,000
1865 600432 $525,000
1866 448667 $436,000
1867 1580000 $1,580,000
1868 600432 $568,000
1869 448667 $385,000
1870 883041 $815,000
1871 625000 $625,000
1872 606899 $690,000
1873 351193 $210,000
1874 606899 $860,000
1875 522941 $476,900
1876 503324 $450,000
1877 600432 $570,000
1878 618354 $875,000
1879 496507 $490,000
1880 379805 $335,000
1881 543599 $550,000
1882 647621 $650,000
1883 371065 $322,400
1884 951673 $1,030,000
1885 371065 $365,000
1886 720587 $699,000
1887 522941 $525,000
1888 351193 $325,000
1889 259969 $279,000
1890 496507 $455,000
1891 322053 $226,550
1892 308900 $320,000
1893 468400 $425,000
1894 600432 $540,000
1895 1235000 $1,060,000
1896 522941 $525,000
1897 600432 $600,000
1898 444238 $464,000
1899 444238 $415,000
1900 444238 $459,000
1901 724117 $711,800
1902 553073 $560,000
1903 457232 $337,000
1904 1390000 $1,390,000
1905 317397 $249,000
1906 606899 $735,000
1907 513017 $475,000
1908 488748 $397,500
1909 475515 $460,000
1910 351193 $250,000
1911 398709 $430,000
1912 460762 $461,550
1913 522941 $479,990
1914 643000 $643,000
1915 606899 $607,000
1916 771983 $731,100
1917 617713 $740,000
1918 625123 $656,000
1919 346650 $360,000
1920 654983 $803,000
1921 720587 $823,000
1922 398709 $420,000
1923 522941 $479,000
1924 570777 $555,000
1925 522941 $490,000
1926 493137 $422,500
1927 716481 $692,500
1928 496520 $499,900
1929 470406 $460,000
1930 720587 $800,000
1931 1373232 $1,310,000
1932 351193 $310,000
1933 351193 $235,000
1934 758947 $770,000
1935 720587 $690,700
1936 847272 $755,000
1937 724117 $700,000
1938 571079 $565,000
1939 486875 $529,888
1940 759067 $800,000
1941 438166 $370,000
1942 479996 $436,000
1943 486875 $395,000
1944 486875 $370,000
1945 522941 $515,000
1946 720587 $822,000
1947 745446 $1,500,000
1948 600432 $590,000
1949 271031 $169,000
1950 466680 $478,000
1951 720587 $835,000
1952 654231 $639,000
1953 496520 $220,000
1954 522941 $526,000
1955 317539 $243,500
1956 750661 $750,000
1957 496507 $329,000
1958 259969 $190,000
1959 642416 $650,000
1960 615444 $710,000
1961 720587 $792,500
1962 720587 $675,000
1963 398709 $352,000
1964 978283 $1,050,000
1965 625123 $685,000
1966 998056 $997,000
1967 503324 $335,000
1968 286499 $162,500
1969 600432 $600,000
1970 883041 $852,500
1971 262483 $227,450
1972 351193 $383,000
1973 861600 $835,000
1974 522941 $545,500
1975 370300 $375,000
1976 600432 $600,000
1977 370300 $292,600
1978 883041 $1,040,000
1979 479996 $424,240
1980 600432 $589,950
1981 342250 $294,000
1982 479996 $440,000
1983 456842 $439,990
1984 872889 $815,000
1985 482242 $535,000
1986 606899 $605,000
1987 515100 $515,100
1988 327533 $307,000
1989 720587 $865,000
1990 404280 $410,000
1991 444212 $460,000
1992 325179 $279,000
1993 460762 $420,000
1994 750661 $1,160,000
1995 1215958 $1,070,000
1996 452115 $412,500
1997 978283 $1,120,000
1998 828443 $915,000
1999 522941 $535,000
2000 635061 $635,000
2001 720074 $682,000
2002 466680 $410,000
2003 310225 $194,990
2004 731200 $774,000
2005 432674 $385,000
2006 724117 $723,000
2007 631063 $625,000
2008 470676 $474,000
2009 600432 $589,000
2010 457682 $386,591
2011 351193 $279,000
2012 720587 $710,000
2013 332382 $320,000
2014 452660 $300,000
2015 414454 $445,000
2016 724117 $775,000
2017 576114 $572,650
2018 351193 $350,000
2019 291729 $285,000
2020 617713 $779,000
2021 661901 $695,000
2022 625123 $638,000
2023 291729 $214,000
2024 817768 $823,000
2025 729748 $760,000
2026 362333 $359,950
2027 362333 $375,000
2028 362333 $295,000
2029 503324 $459,900
2030 335692 $158,000
2031 600432 $439,950
2032 522941 $535,000
2033 796668 $798,000
2034 738933 $785,000
2035 450303 $425,000
2036 617713 $665,000
2037 720587 $680,000
2038 363025 $290,000
2039 606899 $605,500
2040 724117 $762,500
2041 647621 $665,000
2042 570777 $540,000
2043 351193 $340,000
2044 1413421 $1,250,000
2045 716481 $693,000
2046 769417 $805,000
2047 493137 $270,000
2048 847272 $880,000
2049 2065000 $2,850,000
2050 314792 $259,950
2051 2090000 $1,780,000
2052 351193 $299,950
2053 690583 $719,000
2054 690583 $660,000
2055 582677 $575,000
2056 1215958 $1,220,000
2057 600432 $560,000
2058 455285 $450,000
2059 386000 $410,000
2060 386000 $372,500
2061 386000 $439,500
2062 617713 $985,000
2063 775398 $751,305
2064 351193 $280,000
2065 720587 $736,000
2066 468363 $230,000
2067 351193 $366,350
2068 571079 $482,000
2069 702988 $682,000
2070 448700 $425,000
2071 600432 $578,000
2072 769417 $1,090,000
2073 402667 $355,000
2074 351193 $309,000
2075 383212 $354,000
2076 323264 $119,500
2077 769417 $805,000
2078 600432 $602,000
2079 522941 $530,000
2080 606899 $681,000
2081 479996 $448,500
2082 336602 $260,000
2083 600432 $587,000
2084 600432 $355,000
2085 600432 $340,000
2086 552074 $565,000
2087 600432 $600,000
2088 720587 $735,000
2089 463187 $434,000
2090 503324 $465,425
2091 543599 $539,950
2092 437867 $406,430
2093 302282 $302,282
2094 351193 $370,000
2095 437357 $362,000
2096 448700 $450,000
2097 479461 $485,000
2098 437357 $357,500
2099 398709 $365,000
2100 606899 $725,000
2101 437357 $463,000
2102 526286 $536,000
2103 625123 $630,000
2104 1345429 $1,690,000
2105 348945 $270,000
2106 724117 $850,000
2107 351193 $335,000
2108 503324 $510,000
2109 653544 $750,000
2110 445500 $439,900
2111 654700 $710,000
2112 1181667 $2,400,000
2113 496507 $500,000
2114 805000 $885,000
2115 301333 $235,000
2116 381910 $406,000
2117 720587 $720,000
2118 351193 $343,000
2119 351193 $364,000
2120 398709 $392,000
2121 935662 $980,000
2122 351193 $352,500
2123 883041 $895,000
2124 620665 $668,500
2125 522941 $538,000
2126 883041 $898,000
2127 720587 $800,000
2128 1456812 $1,200,000
2129 720587 $689,000
2130 1345429 $1,420,000
2131 802568 $998,000
2132 317539 $329,000
2133 724117 $1,470,000
2134 384073 $335,000
2135 600432 $510,000
2136 389206 $294,010
2137 665923 $660,000
2138 457232 $395,000
2139 522941 $530,000
2140 398709 $380,000
2141 486983 $472,000
2142 565876 $565,000
2143 742623 $765,000
2144 720756 $1,520,000
2145 448700 $405,000
2146 1165000 $1,100,000
2147 556000 $487,500
2148 339000 $339,000
2149 550000 $550,000
2150 834030 $990,400
2151 600432 $600,000
2152 834030 $1,090,000
2153 766050 $800,000
2154 951673 $1,150,000
2155 570777 $565,000
2156 1560556 $1,500,000
2157 1141050 $1,100,000
2158 640233 $648,000
2159 696607 $705,000
2160 617713 $640,000
2161 1320000 $1,460,000
2162 432674 $375,000
2163 724117 $842,000
2164 371567 $310,000
2165 647621 $625,700
2166 371567 $270,000
2167 384073 $357,562
2168 1056845 $1,010,000
2169 522941 $415,000
2170 682475 $810,000
2171 716212 $699,950
2172 445588 $450,000
2173 351193 $350,000
2174 479996 $460,000
2175 367417 $420,200
2176 336903 $258,000
2177 720587 $775,000
2178 577663 $570,000
2179 406654 $435,000
2180 367423 $250,000
2181 720587 $1,700,000
2182 1385000 $1,800,000
2183 617713 $690,000
2184 900290 $789,900
2185 444167 $440,000
2186 444167 $435,000
2187 600432 $585,000
2188 606899 $616,000
2189 600432 $565,000
2190 600432 $572,500
2191 294105 $254,000
2192 522941 $560,000
2193 245790 $200,000
2194 292314 $172,000
2195 316371 $219,900
2196 618354 $641,200
2197 522847 $473,000
2198 305572 $295,000
2199 1151531 $1,730,000
2200 381910 $275,000
2201 367423 $175,000
2202 550011 $550,000
2203 647621 $652,450
2204 606899 $605,000
2205 503324 $395,000
2206 470406 $449,950
2207 301333 $241,000
2208 457682 $400,375
2209 906227 $1,200,000
2210 536697 $535,000
2211 600432 $420,000
2212 496507 $483,500
2213 522941 $513,000
2214 340109 $234,900
2215 951673 $963,000
2216 600432 $595,000
2217 978283 $942,500
2218 1048644 $1,030,000
2219 503324 $497,000
2220 769417 $925,000
2221 492223 $390,000
2222 848214 $785,000
2223 272719 $170,000
2224 724117 $750,000
2225 351193 $335,000
2226 900290 $1,200,000
2227 562445 $575,000
2228 484567 $450,000
2229 503324 $440,000
2230 398709 $377,500
2231 724117 $749,400
2232 1584300 $1,480,000
2233 351193 $261,000
2234 871962 $908,950
2235 582677 $554,000
2236 382600 $387,000
2237 456842 $376,000
2238 720587 $705,000
2239 724117 $725,995
2240 724117 $731,000
2241 1277500 $1,560,000
2242 503324 $510,000
2243 720587 $807,000
2244 635797 $637,000
2245 413312 $425,000
2246 653544 $685,000
2247 503324 $465,000
2248 323264 $194,000
2249 888625 $1,050,000
2250 343000 $286,000
2251 351193 $255,000
2252 344180 $152,000
2253 617467 $599,000
2254 425357 $330,000
2255 625123 $620,000
2256 440567 $435,000
2257 720587 $725,000
2258 447043 $455,000
2259 600432 $587,000
2260 522941 $524,000
2261 351193 $249,900
2262 522941 $499,500
2263 606899 $635,000
2264 305572 $263,500
2265 724117 $975,000
2266 556375 $575,000
2267 822000 $822,000
2268 556375 $487,600
2269 503324 $500,000
2270 444212 $450,000
2271 606899 $650,000
2272 522941 $550,000
2273 314792 $330,000
2274 724117 $750,000
2275 1584375 $2,200,000
2276 449430 $245,000
2277 724117 $751,000
2278 638947 $675,000
2279 790658 $762,500
2280 321139 $150,000
2281 637701 $650,000
2282 521714 $530,000
2283 308900 $248,000
2284 414429 $415,000
2285 329504 $228,000
2286 732124 $781,000
2287 570777 $525,000
2288 259969 $175,000
2289 883041 $1,100,000
2290 754939 $800,000
2291 470676 $445,000
2292 1001260 $1,110,000
2293 600432 $600,000
2294 690500 $670,000
2295 318391 $330,000
2296 522941 $540,000
2297 1086042 $1,150,000
2298 480000 $440,000
2299 600432 $590,300
2300 550011 $541,125
2301 335692 $310,000
2302 724117 $704,111
2303 475515 $289,200
2304 265028 $185,000
2305 1151531 $1,450,000
2306 351193 $345,000
2307 395770 $309,950
2308 706856 $775,000
2309 854654 $863,500
2310 522941 $517,500
2311 522941 $350,000
2312 488746 $325,000
2313 351193 $337,500
2314 409425 $425,000
2315 635797 $780,000
2316 351193 $259,000
2317 519271 $524,400
2318 350938 $226,000
2319 503324 $390,000
2320 503324 $375,000
2321 724117 $742,500
2322 496520 $450,000
2323 600432 $390,000
2324 351193 $382,000
2325 452115 $287,000
2326 470676 $460,000
2327 437867 $435,000
2328 570777 $575,000
2329 404280 $352,000
2330 617713 $650,000
2331 398235 $354,000
2332 759067 $769,000
2333 606899 $650,000
2334 475515 $471,000
2335 625123 $639,000
2336 351193 $287,000
2337 724117 $740,000
2338 635797 $675,000
2339 496520 $445,000
2340 496507 $450,000
2341 600432 $594,950
2342 388500 $450,000
2343 453877 $402,000
2344 314792 $275,000
2345 458605 $421,500
2346 432674 $314,000
2347 314792 $287,000
2348 351193 $337,500
2349 766350 $792,000
2350 522941 $435,000
2351 271031 $299,950
2352 986850 $1,030,000

2353 522941 $535,000
2354 488822 $292,000
2355 2200000 $2,200,000
2356 724117 $810,000
2357 301333 $280,000
2358 587994 $574,000
2359 724117 $1,050,000
2360 371812 $271,950
2361 830075 $846,450
2362 298580 $335,950
2363 503324 $480,000
2364 625123 $668,000
2365 745446 $750,000
2366 600432 $560,000
2367 448700 $300,000
2368 522941 $533,000
2369 503324 $549,950
2370 351193 $241,000
2371 336903 $270,000
2372 628877 $675,000
2373 503324 $499,000
2374 568658 $550,000
2375 290250 $390,000
2376 522941 $535,000
2377 1245566 $1,450,000
2378 587027 $490,000
2379 290250 $319,950
2380 467600 $430,000
2381 351193 $313,000
2382 978283 $950,000
2383 724117 $760,000
2384 437684 $310,650
2385 586606 $580,000
2386 423940 $295,000
2387 329996 $212,700
2388 423940 $415,000
2389 515046 $372,000
2390 470406 $334,950
2391 460762 $400,000
2392 503324 $455,850
2393 1412500 $1,970,000
2394 351193 $397,500
2395 451349 $260,000
2396 245790 $260,000
2397 450303 $430,000
2398 1058458 $905,000
2399 438822 $440,000
2400 347700 $270,000
2401 347700 $380,000
2402 951673 $1,450,000
2403 414454 $317,500
2404 661901 $650,000
2405 724117 $852,000
2406 250000 $250,000
2407 678408 $817,000
2408 414454 $320,000
2409 317539 $263,300
2410 463187 $435,000
2411 890114 $870,000
2412 847272 $800,000
2413 582677 $555,000
2414 351193 $280,000
2415 661901 $675,000
2416 883041 $850,000
2417 452115 $480,000
2418 449430 $379,500
2419 1440000 $1,440,000
2420 800000 $800,000
2421 1131009 $1,580,000
2422 305572 $258,000
2423 284409 $345,000
2424 1921250 $2,900,000
2425 360107 $350,000
2426 503324 $473,000
2427 618354 $695,000
2428 522941 $529,000
2429 492223 $481,500
2430 453877 $455,000
2431 724117 $795,000
2432 774367 $775,000
2433 625123 $645,000
2434 496520 $375,000
2435 325179 $330,000
2436 606899 $940,000
2437 316839 $322,000
2438 522941 $517,500
2439 351193 $343,566
2440 550011 $550,000
2441 978283 $900,000
2442 440567 $449,950
2443 724117 $810,000
2444 759067 $998,160
2445 496520 $377,000
2446 313300 $313,300
2447 326600 $360,000
2448 438530 $455,000
2449 883041 $817,500
2450 1048644 $1,150,000
2451 522941 $503,500
2452 625123 $653,000
2453 1215958 $1,340,000
2454 522941 $525,000
2455 507687 $525,000
2456 444212 $425,500
2457 720587 $710,000
2458 325179 $360,000
2459 398709 $405,000
2460 933394 $865,000
2461 484755 $483,300
2462 1373232 $1,930,000
2463 325179 $250,800
2464 724117 $815,000
2465 817768 $1,020,000
2466 522941 $535,000
2467 775000 $775,000
2468 503317 $439,000
2469 461793 $450,000
2470 545000 $565,000
2471 744372 $775,000
2472 600432 $598,200
2473 522941 $544,900
2474 600432 $557,500
2475 978283 $1,350,000
2476 522941 $530,000
2477 389840 $346,100
2478 398723 $365,000
2479 617713 $615,000
2480 456842 $450,000
2481 329996 $121,800
2482 731200 $805,000
2483 498137 $475,000
2484 778545 $1,340,000
2485 302247 $269,000
2486 600432 $573,000
2487 448700 $330,000
2488 503324 $535,000
2489 600432 $538,900
2490 436512 $432,000
2491 389206 $300,000
2492 1123333 $1,350,000
2493 538119 $550,000
2494 436181 $425,000
2495 347703 $230,000
2496 720587 $675,000
2497 724117 $814,000
2498 385977 $290,000
2499 600432 $600,000
2500 369409 $354,000
2501 978283 $995,000
2502 438822 $472,500
2503 316839 $225,000
2504 503324 $515,000
2505 600432 $601,000
2506 522941 $470,000
2507 351193 $371,500
2508 522941 $550,000
2509 758947 $782,000
2510 612284 $612,000
2511 523214 $530,000
2512 635797 $639,500
2513 571079 $580,379
2514 398709 $378,000
2515 496507 $358,000
2516 451349 $442,500
2517 665923 $659,000
2518 488000 $414,999
2519 488000 $424,000
2520 488000 $463,000
2521 1548333 $1,520,000
2522 340109 $230,000
2523 519271 $359,000
2524 522941 $505,000
2525 329996 $253,905
2526 1197500 $2,000,000
2527 522941 $509,990
2528 369409 $303,500
2529 531000 $520,000
2530 317397 $275,000
2531 600432 $540,000
2532 381460 $455,000
2533 600432 $602,000
2534 720587 $712,000
2535 316371 $244,500
2536 316371 $301,000
2537 731200 $739,999
2538 625123 $617,950
2539 453877 $385,000
2540 466680 $319,000
2541 351193 $345,000
2542 720587 $725,000
2543 351193 $299,950
2544 1413421 $1,880,000
2545 469500 $495,000
2546 351193 $333,000
2547 448700 $385,000
2548 496507 $415,000
2549 729748 $969,000
2550 404280 $339,888
2551 767238 $1,190,000
2552 767238 $780,000
2553 351193 $350,000
2554 351193 $350,000
2555 2700000 $2,700,000
2556 496507 $480,000
2557 479821 $425,000
2558 872158 $1,260,000
2559 495000 $398,500
2560 587027 $585,000
2561 336903 $212,000
2562 423416 $390,000
2563 572900 $560,000
2564 869322 $800,000
2565 724117 $830,000
2566 522941 $485,000
2567 617713 $800,000
2568 562445 $580,000
2569 381910 $270,000
2570 606899 $1,430,000
2571 492223 $457,500
2572 503324 $350,000
2573 479461 $428,000
2574 871962 $1,000,000
2575 606899 $641,000
2576 625123 $675,000
2577 600432 $607,500
2578 617713 $775,000
2579 1560556 $1,440,000
2580 537035 $525,000
2581 617713 $615,000
2582 503324 $507,500
2583 449430 $439,000
2584 606899 $620,000
2585 265028 $276,000
2586 720086 $715,000
2587 522941 $543,000
2588 522941 $495,000
2589 594020 $424,950
2590 329996 $230,000
2591 342500 $350,000
2592 720587 $900,000
2593 342500 $250,000
2594 302247 $225,000
2595 435000 $336,000
2596 503324 $505,000
2597 351193 $250,000
2598 570777 $570,000
2599 618354 $655,000
2600 724117 $710,000
2601 883041 $1,370,000
2602 272719 $284,000
2603 314792 $208,000
2604 491843 $475,000
2605 883041 $985,000
2606 265028 $280,000
2607 398709 $390,000
2608 606899 $612,000
2609 600432 $591,000
2610 600432 $565,000
2611 606899 $650,000
2612 496520 $482,000
2613 1505000 $1,490,000
2614 625123 $635,000
2615 488822 $475,000
2616 625123 $640,000
2617 325179 $299,000
2618 398709 $447,500
2619 724117 $736,500
2620 629250 $665,000
2621 625123 $707,000
2622 639104 $648,000
2623 359000 $415,000
2624 716481 $690,000
2625 617713 $750,000
2626 617713 $1,160,000
2627 720587 $744,000
2628 600432 $583,000
2629 460762 $303,100
2630 485377 $430,000
2631 720086 $708,000
2632 503324 $525,000
2633 457682 $356,200
2634 600432 $595,000
2635 1536667 $2,180,000
2636 419667 $368,000
2637 1373232 $1,390,000
2638 731200 $750,000
2639 606899 $605,000
2640 457327 $413,900
2641 724117 $802,500
2642 807228 $795,000
2643 548362 $567,000
2644 617713 $631,000
2645 3800000 $3,800,000
2646 720587 $717,000
2647 351193 $190,000
2648 414454 $430,000
2649 503324 $475,000
2650 720587 $715,000
2651 901000 $845,000
2652 503324 $390,000
2653 946250 $920,000
2654 912273 $940,000
2655 483125 $465,000
2656 731200 $780,000
2657 522941 $517,500
2658 724117 $1,040,000
2659 724117 $750,000
2660 351193 $360,000
2661 351193 $354,900
2662 438530 $350,000
2663 1129562 $990,000
2664 1136850 $1,650,000
2665 481000 $481,000
2666 503324 $485,000
2667 487814 $477,000
2668 556374 $560,000
2669 617713 $622,500
2670 351193 $240,000
2671 351193 $281,500
2672 496520 $485,000
2673 461050 $411,500
2674 724117 $765,000
2675 522941 $528,000
2676 715000 $715,000
2677 325179 $300,000
2678 377186 $346,000
2679 503324 $500,000
2680 606899 $750,000
2681 505960 $519,900
2682 503324 $499,950
2683 460762 $460,000
2684 621667 $713,400
2685 600432 $510,000
2686 600432 $605,000
2687 724117 $725,000
2688 571079 $410,000
2689 655835 $721,000
2690 600432 $605,000
2691 647621 $738,000
2692 508000 $530,000
2693 264368 $180,000
2694 488746 $430,000
2695 325000 $460,000
2696 640233 $660,000
2697 522941 $515,000
2698 354460 $305,000
2699 724117 $710,000
2700 272719 $205,000
2701 720587 $700,000
2702 551613 $568,000
2703 351193 $275,500
2704 482242 $495,000
2705 522941 $457,500
2706 316782 $235,000
2707 1269576 $1,300,000
2708 625123 $655,000
2709 460762 $369,000
2710 736528 $779,950
2711 479461 $449,999
2712 364500 $425,000
2713 472000 $438,000
2714 724117 $1,490,000
2715 400291 $375,000
2716 606899 $627,000
2717 716212 $674,725
2718 496520 $485,000
2719 327750 $325,000
2720 442903 $416,000
2721 793829 $878,000
2722 351193 $350,000
2723 445575 $395,000
2724 606899 $606,400
2725 541244 $540,000
2726 486048 $469,500
2727 1584375 $1,620,000
2728 900290 $1,200,000
2729 503324 $440,000
2730 720587 $693,000
2731 647621 $700,000
2732 482242 $440,000
2733 659616 $654,000
2734 617713 $710,000
2735 617713 $620,000
2736 437684 $390,000
2737 562982 $550,000
2738 496520 $353,000
2739 503324 $465,000
2740 351193 $395,000
2741 600432 $570,000
2742 351193 $389,000
2743 442375 $445,000
2744 600432 $585,000
2745 1269576 $2,500,000
2746 566399 $555,000
2747 1136850 $3,100,000
2748 405628 $295,000
2749 387403 $330,000
2750 451349 $286,000
2751 503324 $469,950
2752 382707 $435,000
2753 314792 $295,000
2754 883041 $1,250,000
2755 496520 $483,000
2756 600432 $379,900
2757 600432 $599,950
2758 1354000 $1,540,000
2759 1615000 $1,530,000
2760 503324 $500,000
2761 776035 $775,000
2762 452660 $340,000
2763 351193 $279,900
2764 724117 $849,000
2765 724117 $786,000
2766 421805 $325,000
2767 606899 $1,150,000
2768 438166 $406,000
2769 503324 $510,000
2770 264368 $250,000
2771 265028 $295,000
2772 330000 $323,000
2773 720587 $713,000
2774 720587 $1,070,000
2775 595041 $585,000
2776 477250 $450,000
2777 731200 $879,000
2778 600432 $584,999
2779 912273 $987,500
2780 351193 $300,000
2781 463187 $360,000
2782 467248 $311,000
2783 1456812 $1,600,000
2784 584667 $564,000
2785 522941 $425,000
2786 481275 $360,000
2787 600432 $552,000
2788 440567 $393,000
2789 484755 $485,000
2790 340109 $250,000
2791 625123 $670,000
2792 1275000 $1,390,000
2793 496520 $440,000
2794 720587 $1,250,000
2795 600432 $583,000
2796 1191667 $1,600,000
2797 1339362 $1,310,000
2798 606899 $630,000
2799 1081195 $928,950
2800 357167 $277,000
2801 606899 $615,000
2802 469967 $343,000
2803 600432 $600,000
2804 438822 $292,000
2805 503324 $486,000
2806 883041 $1,170,000
2807 347703 $245,000
2808 655835 $830,200
2809 625123 $650,000
2810 315000 $305,000
2811 724117 $725,000
2812 442500 $460,000
2813 410000 $396,480
2814 351193 $320,000
2815 721850 $679,000
2816 460762 $242,000
2817 776035 $765,000
2818 398709 $375,000
2819 600432 $580,000
2820 1136850 $1,610,000
2821 503324 $515,000
2822 404000 $295,000
2823 398709 $406,500
2824 322053 $250,000
2825 453877 $397,000
2826 496507 $450,000
2827 358545 $229,950
2828 522941 $470,000
2829 600432 $579,000
2830 606899 $614,285
2831 398235 $376,000
2832 503324 $487,000
2833 724117 $935,000
2834 625123 $622,000
2835 880833 $1,320,000
2836 325607 $160,000
2837 367500 $183,750
2838 915000 $915,000
2839 381910 $317,000
2840 264368 $165,000
2841 335692 $300,000
2842 332382 $322,500
2843 381910 $440,000
2844 522941 $535,000
2845 562000 $562,000
2846 522941 $527,900
2847 488822 $395,000
2848 438530 $320,000
2849 503324 $505,000
2850 2435000 $1,700,000
2851 724117 $680,000
2852 367417 $387,500

2853 351193 $256,000
2854 600432 $548,000
2855 336602 $367,500
2856 346667 $390,000
2857 617713 $825,000
2858 346667 $245,000
2859 503324 $482,000
2860 496520 $475,000
2861 503324 $518,000
2862 437000 $430,000
2863 802568 $805,000
2864 274939 $275,000
2865 352636 $285,000
2866 763333 $775,000
2867 249000 $288,250
2868 351193 $339,000
2869 606899 $865,000
2870 769417 $730,000
2871 522941 $507,200
2872 351193 $339,900
2873 352636 $416,500
2874 600432 $575,000
2875 426794 $385,000
2876 336602 $253,000
2877 849199 $1,450,000
2878 526773 $542,500
2879 351193 $345,000
2880 600432 $575,000
2881 600432 $510,000
2882 625123 $640,000
2883 503324 $500,000
2884 522941 $529,000
2885 456667 $435,000
2886 631063 $670,000
2887 470676 $365,000
2888 1185517 $1,270,000
2889 450500 $465,000
2890 302247 $219,950
2891 1373232 $1,470,000
2892 625123 $620,000
2893 562982 $545,000
2894 617713 $639,500
2895 1040000 $1,130,000
2896 496520 $355,000
2897 721263 $698,000
2898 445588 $449,950
2899 351193 $404,600
2900 298580 $189,900
2901 1151531 $2,150,000
2902 336602 $345,000
2903 600432 $569,000
2904 600432 $592,500
2905 625123 $620,000
2906 883041 $1,000,000
2907 600432 $515,000
2908 351193 $216,000
2909 351193 $249,900
2910 448700 $410,000
2911 503324 $458,000
2912 340109 $340,000
2913 1152875 $1,250,000
2914 350938 $299,800
2915 492667 $340,000
2916 522941 $535,500
2917 305572 $258,000
2918 275000 $275,000
2919 617713 $713,250
2920 496520 $472,000
2921 351193 $250,000
2922 398709 $375,000
2923 293471 $170,000
2924 617713 $860,000
2925 793829 $920,000
2926 309988 $269,950
2927 309988 $276,000
2928 351193 $329,000
2929 625123 $639,000
2930 600432 $585,000
2931 872264 $1,150,000
2932 325179 $338,000
2933 503324 $325,000
2934 426794 $440,000
2935 724117 $700,000
2936 503324 $488,000
2937 617713 $615,000
2938 314792 $299,500
2939 460762 $459,000
2940 414454 $435,000
2941 720587 $745,000
2942 281645 $250,000
2943 600432 $599,000
2944 350938 $199,950
2945 724117 $712,500
2946 351193 $299,000
2947 496507 $469,000
2948 872264 $1,070,000
2949 724117 $725,000
2950 324500 $299,950
2951 479461 $315,000
2952 326000 $328,000
2953 327000 $320,000
2954 1285700 $1,650,000
2955 959500 $1,210,000
2956 951673 $1,200,000
2957 503324 $508,000
2958 351193 $342,000
2959 869500 $850,000
2960 577663 $570,000
2961 398709 $387,000
2962 642416 $653,450
2963 351193 $285,000
2964 351193 $217,000
2965 593750 $580,135
2966 1150000 $1,150,000
2967 381910 $267,500
2968 351193 $315,000
2969 351193 $360,000
2970 625000 $625,000
2971 951673 $950,000
2972 752604 $1,900,000
2973 405628 $425,000
2974 503324 $500,000
2975 503324 $475,000
2976 625123 $625,000
2977 3200000 $3,200,000
2978 1226500 $1,820,000
2979 401667 $435,000
2980 401667 $310,000
2981 401667 $443,750
2982 724117 $795,000
2983 325607 $315,000
2984 625123 $635,000
2985 522941 $525,000
2986 308750 $279,000
2987 625123 $664,000
2988 308750 $378,500
2989 503324 $520,000
2990 325179 $369,950
2991 541244 $545,000
2992 862500 $760,000
2993 335692 $280,000
2994 738933 $750,000
2995 351193 $237,000
2996 350938 $153,000
2997 310000 $203,000
2998 625123 $620,000
2999 496520 $466,000
3000 351193 $355,500
3001 453877 $432,100
3002 522941 $500,000
3003 716212 $690,000
3004 351193 $350,000
3005 325179 $268,000
3006 460762 $365,000
3007 625123 $630,000
3008 610000 $895,000
3009 314792 $141,800
3010 274939 $230,000
3011 2695000 $3,400,000
3012 617713 $622,000
3013 264368 $90,000
3014 496507 $420,000
3015 351193 $355,200
3016 351193 $379,500
3017 522941 $495,500
3018 496520 $476,500
3019 351193 $261,000
3020 484755 $375,000
3021 548362 $550,000
3022 351193 $230,000
3023 456842 $450,000
3024 350938 $325,000
3025 496520 $210,000
3026 883041 $920,000
3027 305572 $258,305
3028 720587 $850,000
3029 348667 $408,000
3030 1334992 $1,850,000
3031 600432 $499,000
3032 600432 $590,000
3033 312490 $385,000
3034 978283 $1,250,000
3035 503324 $361,000
3036 732124 $760,000
3037 496520 $505,000
3038 616200 $825,000
3039 351193 $319,950
3040 720587 $682,000
3041 546000 $560,000
3042 496507 $450,000
3043 724117 $710,000
3044 606899 $787,000
3045 519271 $537,000
3046 292600 $154,200
3047 460762 $485,500
3048 4670000 $4,670,000
3049 522941 $525,000
3050 292314 $303,000
3051 488748 $315,000
3052 274939 $163,250
3053 404280 $330,000
3054 398709 $395,000
3055 503324 $440,000
3056 612027 $625,000
3057 488746 $299,950
3058 600432 $560,000
3059 423416 $386,000
3060 600432 $450,000
3061 352636 $374,000
3062 496520 $447,000
3063 274939 $212,000
3064 398235 $425,000
3065 157500 $170,000
3066 316782 $234,000
3067 1285700 $1,510,000
3068 457327 $415,000
3069 398709 $360,000
3070 398709 $394,000
3071 488748 $477,500
3072 1334992 $1,250,000
3073 560500 $567,000
3074 625123 $635,000
3075 804960 $945,800
3076 617713 $650,000
3077 978283 $1,450,000
3078 438530 $370,000
3079 606899 $630,000
3080 617713 $698,000
3081 1560556 $1,630,000
3082 272333 $299,000
3083 488748 $475,000
3084 481275 $495,000
3085 600432 $600,000
3086 617713 $665,000
3087 302247 $165,000
3088 351193 $350,000
3089 2450000 $2,450,000
3090 351193 $365,000
3091 955000 $955,000
3092 503324 $500,000
3093 259969 $107,000
3094 606899 $621,500
3095 272719 $222,900
3096 280196 $190,000
3097 606899 $733,500
3098 600432 $555,000
3099 205000 $165,000
3100 600432 $506,000
3101 883041 $949,950
3102 515046 $380,600
3103 351193 $342,888
3104 606899 $613,000
3105 503324 $437,000
3106 617713 $621,000
3107 351193 $250,000
3108 585181 $585,000
3109 647621 $675,000
3110 720587 $695,000
3111 916750 $915,000
3112 522941 $500,000
3113 503324 $508,000
3114 492223 $433,000
3115 316839 $267,500
3116 763333 $910,000
3117 373421 $370,000
3118 338000 $320,000
3119 724117 $787,888
3120 404280 $224,000
3121 358545 $315,500
3122 437684 $374,000
3123 301333 $292,000
3124 272719 $82,000
3125 272719 $219,900
3126 440000 $440,000
3127 484755 $453,000
3128 347000 $330,000
3129 308900 $193,000
3130 606899 $650,000
3131 595000 $597,500
3132 605000 $605,000
3133 600432 $602,000
3134 575095 $575,000
3135 352636 $306,500
3136 380000 $325,000
3137 606899 $623,000
3138 522941 $549,000
3139 321139 $207,000
3140 475000 $474,900
3141 398723 $375,000
3142 647621 $689,000
3143 369409 $360,000
3144 400291 $425,000
3145 201050 $239,950
3146 617713 $615,000
3147 946250 $1,220,000
3148 1403501 $1,660,000
3149 314792 $250,000
3150 883041 $1,300,000
3151 716212 $675,000
3152 316839 $235,000
3153 522941 $545,000
3154 398709 $320,000
3155 724117 $756,000
3156 330000 $330,000
3157 503324 $510,000
3158 522941 $532,000
3159 398709 $205,000
3160 496507 $459,000
3161 351193 $354,000
3162 522941 $536,000
3163 483500 $425,000
3164 398709 $400,000
3165 438166 $446,000
3166 724117 $910,000
3167 663500 $771,000
3168 366907 $408,000
3169 647621 $1,010,000
3170 340109 $330,000
3171 625123 $652,500
3172 522941 $582,000
3173 720587 $700,000
3174 311650 $235,000
3175 474333 $460,000
3176 474333 $475,000
3177 336903 $210,000
3178 344180 $239,300
3179 504555 $510,000
3180 724117 $871,000
3181 871962 $1,110,000
3182 720587 $710,000
3183 1215958 $1,300,000
3184 479996 $248,000
3185 496520 $319,950
3186 466680 $320,000
3187 720587 $700,000
3188 606899 $640,000
3189 426725 $420,000
3190 731200 $749,950
3191 223250 $225,000
3192 295700 $302,100
3193 606899 $607,000
3194 971667 $1,250,000
3195 503324 $250,000
3196 522941 $525,000
3197 720587 $739,900
3198 409425 $315,000
3199 351193 $340,000
3200 332382 $299,000
3201 325607 $340,000
3202 317539 $140,000
3203 522941 $330,000
3204 323225 $306,000
3205 323225 $238,000
3206 625123 $649,950
3207 438000 $236,000
3208 1382250 $1,290,000
3209 568658 $563,000
3210 375000 $410,988
3211 868743 $1,200,000
3212 351193 $343,000
3213 445588 $332,000
3214 951673 $945,000
3215 351193 $200,000
3216 329504 $264,950
3217 724117 $880,000
3218 292314 $209,500
3219 503324 $380,000
3220 325250 $249,900
3221 522941 $549,950
3222 389206 $225,000
3223 389206 $270,000
3224 278410 $299,800
3225 548300 $555,000
3226 398709 $415,000
3227 236850 $353,000
3228 351193 $312,000
3229 496507 $453,000
3230 316839 $320,000
3231 653544 $898,000
3232 775398 $1,240,000
3233 720587 $1,210,000
3234 864303 $1,590,000
3235 741852 $880,000
3236 439750 $420,000
3237 496520 $350,000
3238 586011 $570,000
3239 869322 $1,110,000
3240 625123 $616,500
3241 503324 $506,400
3242 423416 $324,000
3243 496520 $448,000
3244 503324 $437,850
3245 522941 $520,000
3246 586606 $575,000
3247 503324 $365,000
3248 647621 $795,000
3249 481275 $400,000
3250 314792 $245,000
3251 274939 $205,000
3252 315750 $310,000
3253 496507 $470,000
3254 522941 $538,500
3255 351193 $340,000
3256 600432 $565,000
3257 318391 $355,000
3258 246294 $114,975
3259 325000 $325,000
3260 731200 $751,000
3261 389840 $425,000
3262 808699 $833,450
3263 444212 $190,000
3264 444212 $314,950
3265 351193 $315,000
3266 568658 $545,000
3267 565876 $565,000
3268 4490000 $4,490,000
3269 951673 $1,440,000
3270 951673 $929,950
3271 350938 $289,900
3272 590000 $552,500
3273 317397 $260,000
3274 481275 $485,000
3275 456842 $402,000
3276 444212 $450,000
3277 398709 $396,675
3278 436512 $399,950
3279 677767 $690,000
3280 483125 $349,900
3281 436512 $454,280
3282 647621 $700,000
3283 1605000 $1,490,000
3284 600432 $557,800
3285 400291 $225,000
3286 720587 $700,000
3287 724117 $780,000
3288 481000 $434,500
3289 481000 $445,000
3290 400078 $373,000
3291 647621 $625,000
3292 503324 $429,300
3293 323264 $155,000
3294 625123 $650,000
3295 617713 $625,000
3296 503324 $479,500
3297 596068 $540,000
3298 694045 $685,000
3299 738933 $810,000
3300 496520 $490,000
3301 496520 $490,000
3302 440567 $426,250
3303 402983 $358,000
3304 316839 $305,000
3305 488748 $520,000
3306 724117 $733,000
3307 539634 $540,000
3308 990000 $1,200,000
3309 426794 $460,000
3310 350938 $159,075
3311 293058 $235,000
3312 449430 $433,000
3313 915500 $895,000
3314 915500 $835,000
3315 606899 $640,000
3316 503324 $438,000
3317 600432 $540,000
3318 471667 $325,000
3319 471667 $380,000
3320 780495 $825,000
3321 1097467 $1,800,000
3322 265028 $287,000
3323 502345 $509,000
3324 316839 $210,000
3325 817768 $1,250,000
3326 503324 $499,950
3327 632125 $659,000
3328 351750 $265,000
3329 724117 $715,000
3330 624290 $630,000
3331 377186 $367,500
3332 618693 $699,950
3333 888625 $1,000,000
3334 347703 $215,000
3335 758947 $1,050,000
3336 1044458 $1,370,000
3337 606899 $750,000
3338 351193 $350,000
3339 883041 $1,100,000
3340 570777 $568,000
3341 351193 $357,000
3342 435000 $425,000
3343 600432 $588,000
3344 503324 $500,000
3345 351193 $370,000
3346 503324 $360,000
3347 883300 $1,410,000
3348 503324 $485,000
3349 429387 $400,000
3350 600432 $580,000
3351 325179 $261,490
3352 351193 $347,000

3353 600432 $601,000
3354 539634 $560,000
3355 503324 $453,500
3356 780000 $811,000
3357 1584375 $1,530,000
3358 600432 $562,000
3359 316782 $310,000
3360 383212 $350,000
3361 959000 $843,500
3362 460000 $370,000
3363 426794 $392,000
3364 325179 $323,500
3365 351193 $364,500
3366 259969 $183,000
3367 435000 $405,000
3368 256278 $150,000
3369 447000 $440,000
3370 899000 $875,000
3371 647621 $650,000
3372 617713 $653,000
3373 464125 $350,000
3374 951673 $998,000
3375 464125 $465,000
3376 367417 $366,000
3377 522941 $348,000
3378 429387 $386,000
3379 438822 $410,000
3380 780495 $855,000
3381 869322 $852,600
3382 265028 $235,000
3383 457682 $404,763
3384 625123 $626,100
3385 716212 $684,000
3386 765034 $1,070,000
3387 606899 $611,206
3388 351193 $350,000
3389 606899 $675,000
3390 351193 $342,000
3391 522941 $482,500
3392 782175 $812,500
3393 978283 $1,080,000
3394 461793 $275,000
3395 371812 $225,000
3396 724117 $1,100,000
3397 457232 $454,000
3398 552074 $555,000
3399 600432 $590,000
3400 496520 $459,900
3401 731200 $970,500
3402 522941 $552,500
3403 522941 $463,000
3404 367417 $350,000
3405 661500 $685,000
3406 583484 $580,000
3407 409950 $440,000
3408 600432 $565,000
3409 440567 $415,000
3410 404280 $435,000
3411 423416 $225,000
3412 648834 $770,000
3413 883041 $965,000
3414 356385 $265,950
3415 459167 $455,000
3416 951673 $952,000
3417 1233250 $1,210,000
3418 411000 $285,000
3419 398709 $348,140
3420 600432 $499,000
3421 536113 $565,000
3422 720587 $765,000
3423 1330000 $1,330,000
3424 457682 $413,565
3425 724117 $679,000
3426 600432 $585,888
3427 556816 $405,000
3428 600432 $610,000
3429 440567 $320,000
3430 302000 $384,000
3431 436512 $426,000
3432 647621 $675,000
3433 625123 $685,000
3434 387250 $318,500
3435 978283 $925,000
3436 460762 $420,000
3437 1185517 $1,050,000
3438 340109 $333,000
3439 450000 $399,990
3440 445000 $445,000
3441 358545 $190,000
3442 460762 $310,000
3443 1403501 $1,400,000
3444 485377 $304,000
3445 600432 $560,000
3446 570777 $557,510
3447 351193 $320,000
3448 387403 $383,001
3449 522941 $545,000
3450 503324 $487,500
3451 583484 $583,000
3452 522941 $534,950
3453 369409 $403,504
3454 550011 $525,000
3455 410000 $450,000
3456 660892 $665,000
3457 724117 $748,000
3458 562982 $580,000
3459 246294 $235,750
3460 1226500 $1,960,000
3461 978283 $1,270,000
3462 689022 $698,000
3463 398709 $400,000
3464 724117 $760,000
3465 597333 $570,000
3466 269250 $139,000
3467 340109 $267,100
3468 837321 $975,000
3469 383212 $405,000
3470 316839 $225,000
3471 606899 $625,000
3472 522941 $525,000
3473 496520 $465,500
3474 522941 $443,500
3475 446000 $470,000
3476 792390 $1,100,000
3477 438530 $307,150
3478 600432 $585,000
3479 711375 $704,000
3480 577112 $580,000
3481 883041 $875,000
3482 617713 $610,000
3483 724117 $733,000
3484 600432 $500,000
3485 606899 $700,000
3486 503324 $480,000
3487 606899 $650,000
3488 479996 $368,000
3489 883041 $811,500
3490 398235 $425,000
3491 640233 $657,000
3492 421805 $315,000
3493 522941 $550,000
3494 306750 $347,000
3495 503324 $525,000
3496 585000 $585,000
3497 778545 $926,500
3498 1912172 $1,680,000
3499 600032 $600,000
3500 503324 $510,000
3501 398709 $370,000
3502 579297 $560,000
3503 438530 $439,000
3504 737299 $779,000
3505 991700 $903,000
3506 449430 $323,000
3507 2605000 $2,580,000
3508 678408 $1,360,000
3509 720587 $720,000
3510 849199 $825,000
3511 1269576 $1,340,000
3512 586653 $571,500
3513 292314 $217,000
3514 354094 $335,000
3515 503324 $339,950
3516 600432 $598,000
3517 583206 $465,000
3518 1155364 $1,100,000
3519 351193 $300,000
3520 457232 $325,000
3521 351193 $370,000
3522 724117 $715,000
3523 600432 $615,000
3524 800000 $950,000
3525 377186 $259,000
3526 366907 $349,950
3527 1525000 $1,570,000
3528 432674 $430,000
3529 366907 $230,000
3530 567241 $550,388
3531 351193 $334,998
3532 314792 $197,200
3533 493137 $353,900
3534 318391 $380,000
3535 431633 $440,000
3536 431633 $447,450
3537 411975 $275,000
3538 883041 $869,000
3539 314792 $272,000
3540 522941 $550,000
3541 351193 $248,000
3542 522941 $546,940
3543 696607 $680,000
3544 600432 $593,000
3545 953604 $1,700,000
3546 496507 $500,000
3547 696607 $695,000
3548 409500 $425,000
3549 409500 $411,000
3550 488822 $499,000
3551 340109 $310,000
3552 600432 $600,000
3553 316371 $155,000
3554 792390 $780,000
3555 647621 $707,000
3556 484755 $349,170
3557 409425 $287,000
3558 887500 $2,380,000
3559 398709 $365,000
3560 351193 $308,000
3561 470676 $405,000
3562 606899 $604,000
3563 541244 $525,000
3564 398709 $280,000
3565 503324 $490,000
3566 314792 $265,000
3567 617713 $645,000
3568 780495 $812,500
3569 302247 $265,000
3570 503324 $480,000
3571 1350000 $1,350,000
3572 538278 $550,000
3573 606899 $615,000
3574 445575 $464,000
3575 568500 $575,550
3576 600432 $487,500
3577 1155000 $1,160,000
3578 787170 $825,000
3579 265028 $190,000
3580 398709 $417,000
3581 640000 $661,000
3582 2200000 $1,800,000
3583 446950 $408,000
3584 398709 $400,000
3585 351193 $235,000
3586 647621 $675,000
3587 522941 $516,200
3588 1185517 $1,780,000
3589 351193 $277,000
3590 503324 $449,500
3591 546985 $545,000
3592 600432 $563,250
3593 720074 $675,000
3594 373421 $275,000
3595 502925 $476,100
3596 617713 $700,000
3597 351193 $350,000
3598 264368 $130,000
3599 351193 $273,000
3600 600032 $599,000
3601 1455000 $1,160,000
3602 300000 $385,000
3603 350938 $264,250
3604 606899 $608,000
3605 350938 $339,950
3606 323264 $215,000
3607 466680 $420,000
3608 639104 $655,000
3609 724117 $730,000
3610 503324 $473,000
3611 720587 $698,000
3612 398709 $358,000
3613 888625 $920,000
3614 383212 $230,000
3615 316839 $290,000
3616 522941 $505,000
3617 409425 $425,000
3618 606899 $608,095
3619 526051 $550,000
3620 316782 $280,000
3621 600432 $575,000
3622 724117 $760,500
3623 522941 $435,000
3624 780495 $1,570,000
3625 522941 $514,000
3626 1413421 $1,090,000
3627 606899 $865,000
3628 499500 $535,000
3629 538000 $460,500
3630 496520 $315,000
3631 1325993 $1,700,000
3632 695123 $1,140,000
3633 600432 $430,000
3634 625123 $641,000
3635 600432 $601,000
3636 535690 $555,000
3637 1024792 $1,390,000
3638 398709 $390,000
3639 389500 $260,000
3640 724117 $751,000
3641 400000 $400,000
3642 625123 $638,000
3643 496520 $440,000
3644 654231 $680,000
3645 625123 $629,000
3646 522941 $555,000
3647 440000 $270,000
3648 617713 $690,000
3649 335000 $256,000
3650 351193 $410,000
3651 398709 $410,000
3652 531205 $518,000
3653 475515 $485,000
3654 1014084 $999,950
3655 496520 $464,500
3656 986850 $1,080,000
3657 351193 $315,000
3658 724117 $780,000
3659 978283 $885,000
3660 496520 $349,000
3661 358545 $306,000
3662 522941 $560,000
3663 341167 $365,000
3664 341167 $366,000
3665 861675 $875,000
3666 680247 $689,900
3667 496507 $289,275
3668 503324 $505,000
3669 507455 $450,000
3670 548750 $567,500
3671 456842 $375,000
3672 724117 $850,000
3673 872264 $900,000
3674 661901 $675,000
3675 398709 $435,000
3676 793829 $875,000
3677 503324 $510,000
3678 316371 $305,000
3679 476911 $350,000
3680 456842 $284,200
3681 731200 $854,000
3682 1326667 $1,180,000
3683 620000 $650,000
3684 872264 $845,000
3685 503324 $490,000
3686 724117 $753,000
3687 496520 $475,000
3688 350938 $230,000
3689 404280 $440,000
3690 486048 $425,000
3691 1257250 $1,730,000
3692 496507 $491,000
3693 752604 $750,000
3694 724117 $830,000
3695 1140000 $1,140,000
3696 336267 $225,000
3697 724117 $818,000
3698 440567 $450,000
3699 351193 $269,000
3700 606899 $875,000
3701 756167 $890,000
3702 539634 $565,000
3703 438166 $448,175
3704 702078 $680,000
3705 488746 $494,000
3706 503324 $450,000
3707 496520 $330,000
3708 803996 $960,000
3709 503324 $499,950
3710 519271 $450,000
3711 516239 $523,500
3712 451349 $332,500
3713 503324 $505,000
3714 522941 $530,000
3715 617713 $713,000
3716 481275 $420,000
3717 746923 $784,950
3718 377186 $386,000
3719 383212 $335,000
3720 463187 $472,500
3721 272719 $250,000
3722 533550 $518,000
3723 329504 $317,500
3724 606899 $605,000
3725 522941 $535,000
3726 351193 $325,000
3727 487814 $429,950
3728 850000 $1,200,000
3729 600432 $575,000
3730 503324 $352,000
3731 847272 $893,880
3732 457327 $420,000
3733 617713 $689,000
3734 597000 $563,500
3735 503324 $445,000
3736 1530000 $1,250,000
3737 344180 $210,000
3738 510274 $539,000
3739 560000 $440,000
3740 503324 $370,000
3741 738933 $755,000
3742 503324 $497,000
3743 720086 $835,000
3744 731200 $730,000
3745 720587 $716,500
3746 295000 $388,500
3747 407500 $419,000
3748 407500 $385,000
3749 600432 $620,000
3750 688408 $690,000
3751 503324 $530,000
3752 503324 $292,050
3753 470406 $326,000
3754 305572 $300,000
3755 460762 $435,000
3756 354975 $238,000
3757 522941 $517,500
3758 606899 $649,950
3759 496520 $228,000
3760 679000 $689,000
3761 600432 $560,000
3762 522941 $529,000
3763 503324 $375,000
3764 483125 $325,000
3765 600432 $555,000
3766 575095 $585,000
3767 522941 $425,590
3768 265028 $235,000
3769 351193 $362,362
3770 675636 $665,000
3771 358545 $370,000
3772 351193 $315,500
3773 617713 $620,000
3774 503324 $510,000
3775 373421 $315,000
3776 600432 $579,000
3777 496520 $499,000
3778 351193 $333,760
3779 724117 $745,000
3780 463187 $380,000
3781 1136850 $965,000
3782 600432 $577,500
3783 868743 $1,230,000
3784 1900000 $1,900,000
3785 840000 $840,000
3786 366907 $362,000
3787 489810 $350,000
3788 542967 $555,000
3789 883041 $896,000
3790 542967 $550,000
3791 586653 $464,000
3792 661901 $679,975
3793 617713 $624,800
3794 503324 $510,000
3795 600432 $585,000
3796 731200 $940,000
3797 451349 $460,000
3798 485377 $280,000
3799 351193 $250,000
3800 473475 $465,000
3801 473475 $456,000
3802 475000 $475,000
3803 351193 $338,000
3804 617713 $800,000
3805 606899 $610,000
3806 600432 $596,500
3807 332382 $245,000
3808 373421 $373,000
3809 754939 $759,900
3810 369409 $310,000
3811 752604 $750,000
3812 377500 $408,000
3813 370000 $339,000
3814 351193 $235,000
3815 519271 $445,000
3816 503324 $462,000
3817 724117 $790,000
3818 398723 $442,000
3819 787170 $890,000
3820 737299 $1,400,000
3821 511100 $471,000
3822 787170 $804,000
3823 457682 $419,990
3824 724117 $725,000
3825 522941 $510,000
3826 314792 $270,000
3827 496507 $495,000
3828 720587 $690,000
3829 351193 $325,000
3830 720587 $682,000
3831 606899 $605,000
3832 496507 $466,000
3833 632657 $649,000
3834 522941 $515,000
3835 564450 $550,000
3836 230000 $335,000
3837 354460 $310,000
3838 731200 $730,000
3839 452660 $257,000
3840 457232 $355,000
3841 322500 $382,500
3842 510000 $510,000
3843 606899 $625,000
3844 638947 $635,000
3845 370000 $480,000
3846 563667 $575,000
3847 563667 $426,950
3848 724117 $728,725
3849 606899 $708,000
3850 1334992 $1,300,000
3851 551305 $451,000
3852 951673 $1,030,000
3853 577663 $583,000
3854 503324 $465,000
3855 600432 $595,000
3856 316782 $166,000
3857 503324 $529,500
3858 503324 $464,000
3859 351193 $354,000
3860 600432 $601,000
3861 383000 $370,000
3862 383212 $399,900
3863 438530 $398,000
3864 503324 $550,500
3865 695123 $709,000
3866 503324 $402,000
3867 496507 $495,000
3868 854654 $880,000
3869 421805 $247,800
3870 625123 $661,500
3871 377186 $370,000
3872 778545 $785,000
3873 351193 $355,000
3874 808699 $830,000
3875 541244 $500,000
3876 617713 $745,000
3877 398709 $385,000
3878 503324 $500,000
3879 439975 $340,500
3880 439975 $375,000
3881 519852 $536,500
3882 600432 $599,900
3883 647621 $750,000
3884 617713 $680,000
3885 482242 $429,000
3886 2980000 $2,980,000
3887 724117 $979,700
3888 351193 $350,000
3889 625123 $645,500
3890 615319 $750,000
3891 600432 $575,000
3892 462450 $518,000
3893 488822 $399,000
3894 567241 $565,000
3895 484755 $420,000
3896 883041 $847,700
3897 314792 $185,000
3898 324054 $269,000
3899 496520 $422,800
3900 398709 $379,950
3901 522941 $525,000
3902 724117 $810,000
3903 202450 $359,000
3904 720587 $740,000
3905 629298 $630,000
3906 182000 $109,000
3907 845000 $1,200,000
3908 628565 $640,000
3909 503324 $449,500
3910 332382 $312,000
3911 720587 $690,000
3912 617713 $646,000
3913 395000 $400,000
3914 496520 $455,000
3915 314792 $304,950
3916 522941 $482,000
3917 724117 $855,000
3918 398709 $330,000
3919 481275 $450,000
3920 1431500 $3,120,000
3921 1215958 $2,000,000
3922 891600 $820,000
3923 276250 $292,000
3924 399900 $400,000
3925 186667 $202,000
3926 436500 $405,000
3927 482242 $301,350
3928 423416 $425,000
3929 482242 $460,000
3930 871962 $938,000
3931 453877 $410,000
3932 387403 $390,000
3933 978283 $1,500,000
3934 351193 $385,000
3935 522941 $535,950
3936 906455 $1,230,000
3937 476911 $400,000
3938 398235 $420,000
3939 351193 $313,000
3940 398709 $389,100
3941 384073 $351,358
3942 1236225 $1,700,000
3943 1818300 $1,570,000
3944 422500 $470,000
3945 422500 $366,000
3946 566420 $545,000
3947 940000 $901,000
3948 1369500 $1,700,000
3949 936275 $1,170,000
3950 724117 $850,000
3951 313983 $327,000
3952 475515 $440,000
3953 790658 $947,500
3954 507455 $510,000
3955 496520 $440,000
3956 486000 $465,000
3957 310650 $360,000
3958 499580 $290,500
3959 539634 $433,000
3960 398723 $440,000
3961 400291 $333,000
3962 766350 $759,950
3963 800000 $730,000
3964 385925 $266,200
3965 800000 $1,060,000
3966 650000 $650,000
3967 455285 $392,000
3968 363025 $373,000
3969 883041 $951,250
3970 503324 $502,000
3971 565876 $580,000
3972 398709 $422,500
3973 724117 $783,200
3974 720587 $715,000
3975 522941 $472,217
3976 844258 $959,900
3977 600432 $510,000
3978 356385 $340,000
3979 522941 $489,950
3980 617713 $652,000
3981 338000 $333,000
3982 883041 $860,000
3983 720074 $692,500
3984 724117 $925,000
3985 485000 $396,800
3986 496507 $455,500
3987 617713 $743,000
3988 522941 $435,000
3989 535690 $520,000
3990 496520 $440,000
3991 452660 $425,000
3992 766350 $950,000
3993 484755 $435,000
3994 460762 $415,000
3995 411975 $439,000
3996 720587 $730,000
3997 484755 $415,000
3998 998056 $1,010,000
3999 631063 $653,000
4000 724117 $715,000
4001 325607 $306,888
4002 600432 $525,000
4003 1151531 $1,050,000
4004 503324 $452,000
4005 423416 $350,000
4006 548362 $410,000
4007 586606 $595,000
4008 526051 $545,000
4009 460762 $335,000
4010 600432 $499,950
4011 456700 $456,700
4012 731200 $925,500
4013 503324 $375,000
4014 600432 $575,000
4015 409425 $428,000
4016 720587 $738,000
4017 389206 $392,000
4018 381910 $392,500

4019 912000 $912,000
4020 256278 $135,000
4021 503324 $500,000
4022 438822 $251,000
4023 398709 $406,500
4024 397530 $425,000
4025 398709 $450,000
4026 397530 $345,000
4027 576114 $497,000
4028 280196 $205,000
4029 741852 $745,000
4030 600432 $545,000
4031 308900 $287,000
4032 351193 $265,000
4033 1080208 $1,140,000
4034 398235 $289,571
4035 600432 $589,000
4036 522941 $520,000
4037 490950 $470,000
4038 883041 $1,310,000
4039 358545 $210,000
4040 724117 $725,000
4041 724117 $998,000
4042 600587 $602,000
4043 731200 $750,000
4044 1269576 $1,050,000
4045 720587 $700,500
4046 720587 $710,000
4047 391133 $350,000
4048 256278 $200,000
4049 503324 $450,000
4050 318391 $310,000
4051 295586 $281,000
4052 1131009 $976,000
4053 720587 $729,000
4054 625123 $625,000
4055 436512 $432,500
4056 596068 $605,000
4057 1530000 $1,690,000
4058 457682 $318,000
4059 720587 $795,000
4060 566420 $558,000
4061 522941 $515,700
4062 680247 $653,750
4063 503324 $532,000
4064 724117 $945,000
4065 724117 $812,000
4066 606899 $995,000
4067 398709 $360,000
4068 505960 $548,500
4069 503324 $500,000
4070 503324 $500,000
4071 551250 $550,000
4072 1056845 $1,250,000
4073 398709 $405,000
4074 522941 $540,000
4075 497475 $392,500
4076 720587 $735,000
4077 262483 $175,000
4078 764855 $791,500
4079 332382 $238,950
4080 600432 $600,000
4081 460762 $210,750
4082 503324 $405,000
4083 456842 $462,500
4084 503324 $435,000
4085 460762 $440,000
4086 562982 $538,000
4087 720587 $729,000
4088 484755 $331,500
4089 508803 $535,000
4090 325179 $199,500
4091 325179 $247,000
4092 454100 $442,500
4093 367423 $300,000
4094 503324 $525,888
4095 724117 $711,000
4096 522941 $550,000
4097 476051 $450,000
4098 883041 $825,000
4099 476051 $472,500
4100 724117 $1,010,000
4101 1386667 $1,580,000
4102 285000 $279,900
4103 600432 $571,000
4104 1152875 $1,650,000
4105 314792 $137,900
4106 351193 $360,000
4107 442903 $411,500
4108 531500 $535,000
4109 535690 $554,729
4110 724117 $868,000
4111 724117 $770,000
4112 731200 $742,500
4113 796668 $1,250,000
4114 772750 $1,560,000
4115 978283 $1,050,000
4116 600432 $425,000
4117 600432 $554,950
4118 440212 $326,000
4119 577663 $580,000
4120 720587 $699,000
4121 389840 $335,000
4122 659616 $660,000
4123 600432 $540,000
4124 351193 $300,000
4125 295700 $360,000
4126 724117 $950,000
4127 332382 $190,000
4128 418000 $350,000
4129 522941 $522,000
4130 807228 $850,000
4131 325607 $308,000
4132 1024792 $1,380,000
4133 503324 $375,000
4134 351193 $315,000
4135 488748 $467,500
4136 351193 $330,000
4137 496520 $469,000
4138 405628 $408,000
4139 272719 $235,000
4140 731200 $903,000
4141 496520 $494,950
4142 865000 $1,130,000
4143 451250 $449,000
4144 724117 $751,000
4145 724117 $1,120,000
4146 395000 $450,000
4147 468363 $354,000
4148 292314 $325,000
4149 724117 $1,000,000
4150 617713 $650,000
4151 503324 $500,000
4152 789346 $870,000
4153 284409 $299,000
4154 1058458 $1,660,000
4155 499950 $499,990
4156 325179 $315,000
4157 373421 $365,000
4158 731200 $774,000
4159 775000 $814,950
4160 600432 $540,000
4161 496520 $450,000
4162 536113 $545,000
4163 398709 $388,000
4164 922000 $1,180,000
4165 625123 $629,950
4166 552074 $545,000
4167 625123 $625,000
4168 496520 $324,950
4169 470676 $330,000
4170 720587 $685,000
4171 606899 $660,000
4172 631276 $650,000
4173 522941 $535,000
4174 724117 $770,000
4175 393817 $375,000
4176 720587 $850,000
4177 503324 $463,000
4178 721263 $750,000
4179 539634 $525,000
4180 371812 $319,000
4181 496520 $454,900
4182 302247 $285,000
4183 720587 $750,000
4184 390500 $442,250
4185 390500 $394,000
4186 443500 $355,000
4187 429387 $344,950
4188 496507 $230,000
4189 600432 $600,000
4190 1215958 $1,380,000
4191 398235 $427,800
4192 484755 $435,000
4193 843500 $1,450,000
4194 398709 $393,000
4195 398709 $425,000
4196 720587 $753,000
4197 323264 $310,000
4198 398709 $395,000
4199 664758 $725,000
4200 1256000 $1,700,000
4201 449430 $431,000
4202 600432 $595,000
4203 530000 $468,000
4204 606899 $640,000
4205 600432 $575,000
4206 3000000 $3,000,000
4207 1037500 $950,000
4208 647621 $785,000
4209 828443 $951,000
4210 503324 $499,950
4211 532435 $549,000
4212 758436 $1,600,000
4213 503324 $311,000
4214 951673 $1,080,000
4215 442000 $436,000
4216 522941 $514,000
4217 503324 $500,000
4218 1373232 $1,800,000
4219 366907 $278,000
4220 617713 $780,000
4221 617713 $650,000
4222 600432 $559,500
4223 322053 $219,950
4224 720587 $671,500
4225 203700 $203,700
4226 724117 $740,000
4227 654231 $663,000
4228 503324 $448,000
4229 336602 $335,000
4230 522941 $524,950
4231 729748 $729,000
4232 606899 $687,500
4233 883041 $1,170,000
4234 724117 $825,000
4235 503324 $500,000
4236 617713 $619,500
4237 384073 $305,000
4238 746923 $874,000
4239 482242 $477,500
4240 1014084 $1,080,000
4241 460000 $343,500
4242 425000 $334,900
4243 552074 $544,300
4244 570777 $535,000
4245 1230818 $1,160,000
4246 325607 $289,000
4247 700000 $790,000
4248 475515 $350,000
4249 453877 $246,950
4250 367423 $400,000
4251 724117 $875,000
4252 600432 $600,000
4253 305572 $292,500
4254 522941 $525,000
4255 724117 $1,170,000
4256 342495 $275,000
4257 503324 $317,500
4258 470406 $320,000
4259 661901 $650,000
4260 325607 $325,000
4261 347703 $165,000
4262 460762 $443,000
4263 395770 $299,880
4264 1332500 $1,710,000
4265 550011 $550,000
4266 681248 $920,000
4267 600432 $568,000
4268 548362 $560,000
4269 383212 $315,000
4270 148633 $106,000
4271 720587 $751,000
4272 340109 $235,000
4273 724117 $745,000
4274 522941 $470,000
4275 503324 $440,000
4276 600432 $590,000
4277 883041 $827,500
4278 611194 $630,000
4279 347703 $340,000
4280 582677 $570,000
4281 1489500 $2,750,000
4282 351193 $360,000
4283 625123 $647,000
4284 261375 $354,000
4285 922000 $850,000
4286 487814 $496,700
4287 496520 $475,000
4288 354094 $275,000
4289 912273 $1,180,000
4290 316782 $245,000
4291 314792 $265,000
4292 522941 $497,000
4293 538119 $545,800
4294 724117 $1,130,000
4295 731200 $855,000
4296 460762 $429,900
4297 503324 $457,500
4298 254525 $229,050
4299 667320 $815,000
4300 186667 $156,000
4301 617713 $676,000
4302 397500 $475,000
4303 460762 $420,000
4304 600432 $607,000
4305 398709 $395,000
4306 617713 $650,000
4307 617713 $625,000
4308 898395 $849,000
4309 720587 $825,000
4310 271031 $283,000
4311 617713 $610,000
4312 1585714 $3,200,000
4313 351193 $339,000
4314 950333 $950,000
4315 606899 $677,500
4316 883041 $840,000
4317 456842 $491,234
4318 503324 $490,000
4319 341832 $400,000
4320 562445 $530,000
4321 724117 $804,000
4322 833545 $808,250
4323 465000 $350,000
4324 475515 $400,000
4325 1530000 $1,450,000
4326 617713 $680,000
4327 503324 $440,000
4328 218667 $188,000
4329 1129562 $1,190,000
4330 570777 $575,000
4331 1132660 $1,200,000
4332 302247 $238,000
4333 793829 $820,000
4334 470406 $355,000
4335 1132660 $1,300,000
4336 724117 $835,000
4337 617713 $625,000
4338 522941 $540,000
4339 457327 $450,000
4340 1975000 $2,800,000
4341 615319 $613,000
4342 611194 $614,000
4343 600432 $595,000
4344 439317 $472,000
4345 389206 $412,000
4346 647621 $800,000
4347 890114 $968,000
4348 872158 $948,000
4349 606899 $615,000
4350 522941 $550,000
4351 611194 $629,000
4352 363025 $415,885
4353 280196 $272,000
4354 625123 $665,000
4355 503324 $510,000
4356 351193 $355,000
4357 776035 $790,000
4358 720587 $695,000
4359 453877 $410,000
4360 367423 $332,888
4361 343000 $320,000
4362 503324 $342,500
4363 724117 $752,875
4364 1530000 $1,730,000
4365 301333 $255,000
4366 884468 $840,000
4367 460762 $500,000
4368 435000 $510,000
4369 600432 $597,500
4370 323264 $315,000
4371 415250 $455,000
4372 522941 $523,000
4373 336602 $310,000
4374 466680 $402,000
4375 470676 $478,000
4376 325460 $208,417
4377 647621 $648,000
4378 442500 $465,000
4379 600432 $622,000
4380 617713 $617,000
4381 265028 $295,000
4382 367417 $330,000
4383 404280 $405,000
4384 496520 $485,000
4385 398709 $400,000
4386 599972 $585,000
4387 2200000 $2,200,000
4388 503324 $500,000
4389 1230000 $1,250,000
4390 600432 $435,000
4391 596068 $590,000
4392 951673 $1,240,000
4393 503324 $395,000
4394 480000 $419,000
4395 883041 $855,000
4396 536561 $545,000
4397 615319 $615,000
4398 496520 $460,000
4399 495000 $465,000
4400 367417 $370,000
4401 398709 $240,000
4402 325179 $232,000
4403 351193 $237,502
4404 1096625 $1,280,000
4405 395770 $350,000
4406 688961 $688,888
4407 978283 $905,000
4408 310000 $365,000
4409 398709 $400,000
4410 503324 $510,000
4411 560000 $512,000
4412 522941 $491,500
4413 384500 $375,000
4414 301333 $199,400
4415 384073 $324,950
4416 351193 $315,000
4417 351193 $370,000
4418 453877 $330,000
4419 1790000 $1,790,000
4420 1337875 $1,600,000
4421 496520 $305,495
4422 1050313 $1,620,000
4423 600432 $494,500
4424 648370 $746,000
4425 280000 $385,000
4426 720587 $688,100
4427 503324 $425,000
4428 716212 $700,000
4429 447043 $432,000
4430 493137 $465,000
4431 522941 $498,688
4432 348945 $220,000
4433 321139 $260,000
4434 316839 $290,000
4435 724117 $730,000
4436 719000 $690,000
4437 316371 $254,000
4438 476911 $432,000
4439 647621 $672,500
4440 351193 $336,000
4441 503324 $505,000
4442 647621 $636,000
4443 1269576 $1,290,000
4444 629329 $900,000
4445 350000 $419,500
4446 647621 $685,000
4447 335000 $429,950
4448 466680 $464,950
4449 451000 $406,250
4450 538278 $559,500
4451 522941 $522,500
4452 600432 $498,500
4453 570777 $543,000
4454 323264 $104,950
4455 499900 $485,500
4456 890114 $875,909
4457 309000 $309,000
4458 600432 $600,000
4459 902431 $1,030,000
4460 502925 $469,500
4461 1256000 $1,150,000
4462 872264 $872,750
4463 380625 $350,000
4464 380625 $315,000
4465 522941 $509,950
4466 503324 $286,300
4467 600432 $590,000
4468 313500 $325,000
4469 325607 $325,000
4470 496520 $484,000
4471 744372 $760,000
4472 724117 $750,000
4473 522941 $440,000
4474 503324 $501,000
4475 752590 $739,000
4476 336602 $275,000
4477 425000 $330,000
4478 600432 $566,000
4479 720587 $738,000
4480 398709 $445,000
4481 323264 $175,000
4482 317539 $315,000
4483 1187500 $1,400,000
4484 724117 $832,500
4485 758947 $771,150
4486 503678 $389,950
4487 522941 $435,000
4488 724117 $750,000
4489 503324 $500,000
4490 999500 $920,000
4491 936000 $936,000
4492 618354 $1,500,000
4493 522941 $432,500
4494 600432 $589,000
4495 724117 $756,450
4496 522941 $536,650
4497 522941 $540,000
4498 371812 $240,000
4499 371812 $415,500
4500 423416 $415,000
4501 522941 $420,000
4502 898395 $857,500
4503 935000 $1,060,000
4504 600432 $585,000
4505 496507 $440,000
4506 429387 $385,000
4507 647621 $700,000
4508 600432 $585,000
4509 398709 $401,000
4510 628565 $655,000
4511 537035 $500,000
4512 720587 $715,000
4513 648370 $661,000
4514 724117 $697,000
4515 1339362 $1,200,000
4516 398709 $404,500
4517 351193 $396,500
4518 487814 $450,000
4519 606899 $605,000
4520 716481 $699,000
4521 600432 $595,000
4522 369900 $285,000
4523 724117 $725,000
4524 503324 $410,000
4525 600432 $597,000
4526 412989 $338,000
4527 496520 $423,000
4528 358545 $299,000
4529 302247 $218,000
4530 600432 $590,000
4531 398709 $348,500
4532 1604965 $1,430,000
4533 503324 $502,000
4534 451349 $405,000
4535 323500 $222,000
4536 319333 $250,000
4537 600432 $599,000
4538 600432 $585,000
4539 329504 $350,000
4540 325460 $151,100
4541 325460 $251,000
4542 598640 $555,000
4543 171667 $229,000
4544 570777 $575,000
4545 760111 $815,000
4546 512684 $471,000
4547 617713 $590,000
4548 738000 $744,000
4549 738000 $1,110,000
4550 351193 $339,000
4551 351193 $375,000
4552 724117 $700,000
4553 351193 $200,000
4554 428950 $452,000
4555 396000 $418,000
4556 617713 $600,000
4557 398709 $290,000
4558 457232 $300,000
4559 358000 $350,000
4560 617713 $626,000
4561 600432 $595,000
4562 522941 $429,000
4563 1113875 $2,140,000
4564 503324 $480,000
4565 1215958 $1,670,000
4566 590052 $486,000
4567 890114 $1,020,000
4568 600432 $565,000
4569 1300000 $1,300,000
4570 864303 $870,000
4571 864303 $902,000
4572 398709 $269,500
4573 1044458 $1,450,000
4574 606899 $615,000
4575 600432 $530,000
4576 496507 $474,950
4577 301333 $210,000
4578 457232 $324,500
4579 522941 $525,000
4580 452804 $385,000
4581 1172150 $1,310,000
4582 272167 $180,000
4583 600432 $589,000
4584 351193 $350,000
4585 460762 $480,000
4586 411975 $325,000
4587 600432 $595,000
4588 600432 $605,000
4589 1151531 $994,000
4590 505960 $489,950
4591 600032 $495,000
4592 398235 $330,000
4593 438530 $450,000
4594 654231 $655,000
4595 496520 $375,000
4596 539634 $570,000
4597 575095 $550,000
4598 503324 $513,000
4599 503324 $450,000
4600 479461 $480,000
4601 453877 $402,200
4602 617713 $650,000
4603 864303 $1,200,000
4604 617713 $610,000
4605 1960000 $1,960,000
4606 606899 $624,000
4607 680000 $815,000
4608 2380000 $1,650,000
4609 329504 $180,000
4610 398709 $368,000
4611 335692 $345,000
4612 782175 $950,000
4613 1071667 $995,000
4614 731200 $741,000
4615 583484 $575,000
4616 503324 $385,000
4617 769417 $870,000
4618 600432 $440,000
4619 460762 $518,000
4620 316839 $290,000
4621 363025 $330,000
4622 351193 $280,000
4623 600432 $595,000
4624 883041 $895,000
4625 763333 $1,070,000
4626 252000 $260,000
4627 481275 $295,000
4628 721050 $1,190,000
4629 724117 $749,950
4630 351193 $175,000
4631 438166 $415,000
4632 522941 $400,000
4633 724117 $1,650,000
4634 369409 $275,000
4635 522941 $450,000
4636 496520 $468,000
4637 278410 $285,000
4638 1550000 $1,550,000
4639 4210000 $4,210,000
4640 606899 $670,000
4641 316371 $107,000
4642 316371 $232,900
4643 625123 $670,000
4644 600432 $570,500
4645 600432 $599,990
4646 496520 $395,000
4647 979500 $979,500
4648 649048 $650,100
4649 479461 $385,000
4650 398709 $335,000
4651 611194 $615,000
4652 720587 $943,500
4653 522941 $560,000
4654 518000 $547,500
4655 496520 $359,500
4656 638947 $660,000
4657 293471 $253,500
4658 377186 $422,500
4659 367417 $352,000
4660 883041 $870,000
4661 647621 $661,254
4662 642416 $680,000
4663 228225 $148,000
4664 228225 $244,900
4665 600432 $580,000
4666 503324 $317,000
4667 503324 $302,000
4668 720587 $899,000
4669 625123 $1,290,000
4670 351193 $230,000
4671 468363 $430,000
4672 990000 $1,170,000
4673 496520 $485,000
4674 587000 $550,000
4675 625123 $630,000
4676 568658 $560,000
4677 438530 $385,000
4678 606899 $610,000
4679 731200 $750,000
4680 512684 $544,000
4681 496520 $420,000
4682 951673 $1,070,000
4683 496507 $287,500
4684 503324 $502,775
4685 350938 $222,900

4686 724117 $728,000
4687 577842 $525,000
4688 425000 $433,500
4689 503324 $500,000
4690 409425 $275,000
4691 485377 $498,000
4692 607000 $625,000
4693 724117 $770,000
4694 500000 $475,000
4695 647621 $660,000
4696 724117 $705,000
4697 389840 $311,000
4698 522941 $485,000
4699 452660 $485,000
4700 720587 $725,000
4701 1770000 $1,890,000
4702 353700 $356,000
4703 731200 $760,250
4704 543500 $535,500
4705 617713 $745,000
4706 548793 $355,000
4707 656487 $840,500
4708 617713 $625,000
4709 724117 $740,000
4710 600432 $575,000
4711 724117 $1,030,000
4712 496520 $440,000
4713 600432 $567,500
4714 752604 $735,000
4715 298000 $114,000
4716 600432 $608,000
4717 496507 $330,000
4718 278410 $90,000
4719 292500 $312,000
4720 625123 $618,080
4721 351193 $242,000
4722 562445 $545,000
4723 759067 $1,090,000
4724 888625 $845,000
4725 246294 $213,800
4726 398709 $400,000
4727 724117 $990,000
4728 318391 $315,000
4729 503324 $515,000
4730 647621 $638,000
4731 340109 $309,500
4732 318391 $299,000
4733 284409 $215,000
4734 503324 $478,000
4735 398709 $431,000
4736 648370 $648,000
4737 625123 $640,000
4738 883041 $932,808
4739 445588 $469,775
4740 647621 $677,915
4741 687015 $695,000
4742 493137 $360,000
4743 731200 $735,000
4744 600432 $589,500
4745 351193 $291,000
4746 1300000 $1,300,000
4747 724117 $740,000
4748 458605 $467,000
4749 631276 $670,000
4750 503324 $500,000
4751 720587 $669,888
4752 351193 $280,000
4753 451349 $435,000
4754 625123 $630,000
4755 460762 $442,000
4756 872158 $900,000
4757 496520 $489,500
4758 724117 $800,000
4759 452660 $515,000
4760 340000 $329,000
4761 460762 $458,500
4762 724117 $890,000
4763 1277500 $2,540,000
4764 317539 $325,000
4765 724117 $945,000
4766 778545 $800,000
4767 316782 $150,000
4768 568202 $555,000
4769 391500 $227,000
4770 445588 $410,000
4771 600432 $345,000
4772 625123 $627,500
4773 351193 $355,000
4774 488822 $350,000
4775 1269576 $1,300,000
4776 720587 $705,000
4777 496507 $498,000
4778 617713 $610,000
4779 724117 $689,000
4780 637701 $640,000
4781 388250 $290,000
4782 1001260 $1,100,000
4783 600432 $575,000
4784 455000 $475,200
4785 398709 $218,000
4786 600432 $600,000
4787 1365000 $2,410,000
4788 460000 $460,000
4789 398709 $425,000
4790 484755 $455,000
4791 724117 $780,000
4792 668000 $670,000
4793 367417 $325,000
4794 345000 $281,000
4795 351193 $130,000
4796 572500 $485,000
4797 656487 $642,860
4798 565000 $577,288
4799 351193 $287,000
4800 323264 $375,000
4801 522941 $530,000
4802 575233 $425,000
4803 910000 $975,000
4804 724117 $750,000
4805 522941 $515,000
4806 475515 $470,000
4807 425000 $429,000
4808 600432 $505,000
4809 414429 $382,000
4810 438166 $355,000
4811 503324 $410,000
4812 600032 $452,500
4813 278000 $363,500
4814 503324 $510,000
4815 278410 $170,000
4816 503324 $510,000
4817 674000 $690,000
4818 245790 $199,950
4819 272719 $207,000
4820 358545 $361,550
4821 837321 $838,400
4822 265028 $225,000
4823 437867 $329,900
4824 314792 $282,500
4825 724117 $899,000
4826 336500 $317,000
4827 407000 $395,000
4828 600432 $570,000
4829 317539 $191,000
4830 398709 $400,000
4831 606899 $610,000
4832 476911 $432,000
4833 522941 $535,000
4834 488822 $310,000
4835 847272 $1,310,000
4836 351193 $343,000
4837 600432 $599,950
4838 1325993 $1,750,000
4839 963000 $870,000
4840 724117 $727,000
4841 503324 $400,000
4842 600432 $599,000
4843 978283 $930,000
4844 522941 $498,000
4845 720587 $737,000
4846 758947 $860,000
4847 351193 $370,000
4848 635061 $725,000
4849 503324 $529,000
4850 1151531 $1,300,000
4851 496507 $435,000
4852 476911 $350,000
4853 366907 $410,000
4854 600432 $430,000
4855 445588 $446,000
4856 600432 $595,000
4857 344180 $319,950
4858 437684 $399,950
4859 398709 $399,950
4860 883041 $860,000
4861 3100000 $3,100,000
4862 351193 $245,000
4863 367417 $255,000
4864 600432 $575,000
4865 488822 $442,573
4866 496507 $485,000
4867 1199658 $1,610,000
4868 522941 $340,000
4869 398709 $380,000
4870 429387 $400,000
4871 582677 $582,000
4872 284409 $285,950
4873 617713 $645,000
4874 686766 $663,000
4875 496520 $443,950
4876 369409 $315,000
4877 314792 $230,000
4878 542500 $315,000
4879 438822 $334,009
4880 724117 $818,000
4881 352500 $310,000
4882 579297 $575,000
4883 570777 $555,000
4884 617713 $850,000
4885 497000 $372,000
4886 522941 $453,000
4887 414429 $345,000
4888 745446 $890,000
4889 479461 $440,000
4890 341500 $395,000
4891 321139 $305,000
4892 496520 $383,000
4893 617713 $672,000
4894 497500 $291,375
4895 497500 $519,950
4896 600432 $614,950
4897 600432 $599,500
4898 720587 $787,500
4899 305572 $310,000
4900 496507 $280,000
4901 302247 $200,000
4902 325179 $231,500
4903 496520 $467,100
4904 539634 $565,000
4905 351193 $295,000
4906 411975 $270,000
4907 380000 $340,000
4908 720587 $726,888
4909 265028 $285,000
4910 432674 $460,000
4911 600432 $585,000
4912 654700 $998,500
4913 340109 $320,000
4914 503324 $500,000
4915 496520 $402,000
4916 600432 $570,000
4917 724117 $870,000
4918 535690 $532,000
4919 307500 $201,000
4920 496507 $475,000
4921 577112 $565,000
4922 205000 $110,000
4923 450000 $375,000
4924 503324 $496,600
4925 351193 $380,000
4926 503324 $542,500
4927 1373232 $1,700,000
4928 503324 $469,000
4929 553073 $305,000
4930 828443 $815,000
4931 536561 $531,000
4932 720587 $677,500
4933 817768 $868,500
4934 437867 $350,000
4935 448700 $452,000
4936 731200 $915,000
4937 647621 $666,570
4938 322053 $250,000
4939 308900 $290,000
4940 951673 $1,260,000
4941 438000 $381,000
4942 484755 $300,000
4943 387000 $360,000
4944 529000 $419,000
4945 407500 $465,000
4946 522941 $545,000
4947 582677 $550,000
4948 759067 $980,000
4949 600432 $555,000
4950 527307 $430,000
4951 724117 $730,100
4952 512500 $525,000
4953 724117 $788,000
4954 351193 $320,000
4955 382707 $394,000
4956 600432 $575,000
4957 351193 $240,000
4958 898395 $1,250,000
4959 398709 $425,000
4960 565876 $548,000
4961 438822 $379,880
4962 675636 $695,000
4963 377186 $435,000
4964 453877 $425,000
4965 317397 $220,000
4966 551613 $540,000
4967 606899 $667,500
4968 600432 $585,000
4969 397475 $375,000
4970 397475 $420,000
4971 690498 $710,000
4972 258000 $279,500
4973 1336000 $1,610,000
4974 301553 $325,000
4975 1615000 $1,700,000
4976 653544 $658,500
4977 617713 $680,000
4978 695123 $675,000
4979 758436 $825,000
4980 437684 $455,000
4981 731200 $713,500
4982 351193 $240,000
4983 351193 $243,800
4984 624975 $625,000
4985 395770 $150,000
4986 606899 $683,500
4987 522941 $499,950
4988 351193 $255,000
4989 298000 $316,000
4990 398709 $410,000
4991 589794 $559,000
4992 600432 $575,000
4993 600432 $602,000
4994 503324 $481,000
4995 503324 $500,000
4996 522941 $553,000
4997 600432 $589,500
4998 278410 $280,000
4999 440567 $450,000
5000 340109 $290,000
5001 1500000 $2,000,000
5002 522941 $545,000
5003 563560 $550,000
5004 731200 $905,000
5005 354094 $370,000
5006 664694 $717,500
5007 1325993 $2,000,000
5008 259969 $272,000
5009 724117 $744,000
5010 769417 $830,000
5011 452115 $271,000
5012 395770 $340,000
5013 458605 $340,000
5014 366907 $335,000
5015 1529188 $1,150,000
5016 496520 $451,000
5017 600432 $580,000
5018 720587 $685,000
5019 350938 $275,000
5020 741852 $739,888
5021 287500 $350,000
5022 522941 $452,500
5023 278410 $248,000
5024 377186 $435,010
5025 647621 $678,100
5026 522941 $529,950
5027 570777 $585,000
5028 453750 $462,608
5029 522941 $510,000
5030 402200 $280,000
5031 802568 $1,100,000
5032 429387 $375,000
5033 837321 $732,000
5034 694045 $681,716
5035 552074 $530,000
5036 933394 $860,000
5037 720587 $690,000
5038 522941 $530,000
5039 351193 $190,000
5040 398709 $375,000
5041 765034 $759,000
5042 749950 $810,000
5043 247500 $331,292
5044 436181 $435,000
5045 322053 $246,000
5046 594950 $594,950
5047 485377 $313,100
5048 503324 $455,000
5049 724117 $770,000
5050 778545 $1,580,000
5051 1820000 $1,820,000
5052 775398 $765,000
5053 1050000 $1,050,000
5054 760111 $829,000
5055 246294 $122,000
5056 632657 $629,500
5057 1140000 $1,140,000
5058 367417 $275,000
5059 731200 $720,000
5060 694045 $675,000
5061 519668 $520,000
5062 951673 $1,040,000
5063 582677 $575,000
5064 470676 $480,000
5065 720587 $720,000
5066 274939 $265,000
5067 978283 $1,050,000
5068 787133 $804,100
5069 448700 $432,000
5070 951673 $935,000
5071 522941 $520,000
5072 606899 $652,000
5073 724117 $745,000
5074 329504 $257,000
5075 496520 $485,000
5076 325179 $330,000
5077 906455 $975,000
5078 367423 $375,000
5079 398709 $400,000
5080 661901 $665,000
5081 611194 $620,000
5082 724117 $852,500
5083 758436 $790,000
5084 447043 $289,950
5085 721263 $850,000
5086 503324 $505,000
5087 499000 $372,000
5088 617713 $780,000
5089 417358 $400,000
5090 600432 $585,000
5091 780000 $850,000
5092 857500 $869,000
5093 724117 $728,935
5094 496520 $515,000
5095 807228 $845,000
5096 351193 $135,000
5097 600432 $585,000
5098 617713 $620,000
5099 398709 $399,500
5100 2435000 $3,170,000
5101 600432 $600,000
5102 488748 $310,000
5103 340109 $200,000
5104 438530 $310,000
5105 351193 $230,000
5106 546985 $420,000
5107 724117 $785,000
5108 1337875 $1,780,000
5109 317397 $250,000
5110 898000 $905,000
5111 522941 $530,000
5112 354460 $310,000
5113 351193 $252,000
5114 332382 $311,000
5115 414454 $260,000
5116 457327 $423,500
5117 350000 $299,000
5118 625123 $635,000
5119 842593 $806,000
5120 470676 $289,950
5121 351193 $436,000
5122 404280 $390,000
5123 522941 $502,000
5124 452475 $260,000
5125 399000 $399,000
5126 301333 $312,500
5127 1050313 $1,240,000
5128 1044458 $1,280,000
5129 351193 $294,350
5130 316839 $208,950
5131 900290 $965,000
5132 940000 $925,000
5133 479996 $364,000
5134 606899 $610,000
5135 351193 $348,580
5136 496520 $459,000
5137 323264 $375,000
5138 401000 $384,205
5139 769417 $780,000
5140 888625 $820,000
5141 496520 $492,000
5142 720587 $675,750
5143 617713 $765,000
5144 577112 $563,500
5145 452660 $439,000
5146 883041 $975,000
5147 522941 $469,900
5148 626847 $898,000
5149 487000 $450,000
5150 317475 $350,000
5151 522941 $479,500
5152 837321 $831,500
5153 625123 $655,000
5154 452660 $449,950
5155 606899 $612,000
5156 600432 $575,000
5157 397000 $375,000
5158 503324 $330,000
5159 1343750 $1,900,000
5160 260000 $235,000
5161 448700 $431,000
5162 538278 $550,000
5163 506902 $515,000
5164 398723 $265,000
5165 617713 $661,000
5166 818500 $818,500
5167 600432 $580,000
5168 1548333 $2,340,000
5169 351193 $360,500
5170 503324 $490,000
5171 351193 $307,500
5172 2200000 $2,600,000
5173 708274 $700,000
5174 724117 $756,100
5175 600432 $555,000
5176 790658 $775,000
5177 363790 $275,000
5178 720587 $766,000
5179 1285700 $1,330,000
5180 476911 $265,000
5181 351193 $325,000
5182 387403 $338,900
5183 583143 $584,950
5184 724117 $750,000
5185 617713 $775,000
5186 457327 $464,000
5187 868743 $850,000
5188 321139 $102,500
5189 284409 $216,000
5190 522941 $505,000
5191 325607 $289,000
5192 398709 $375,000
5193 503324 $537,500
5194 351193 $185,000
5195 382707 $402,000
5196 802568 $1,810,000
5197 437867 $345,000
5198 496520 $480,000
5199 599950 $535,000
5200 724117 $775,000
5201 225000 $320,000
5202 351193 $253,200
5203 600432 $530,000
5204 484755 $415,000
5205 350000 $384,000
5206 351193 $405,000
5207 596068 $550,000
5208 503324 $540,000
5209 600432 $257,000
5210 503324 $400,000
5211 351193 $356,000
5212 522941 $515,000
5213 300000 $245,000
5214 503324 $465,000
5215 562445 $550,000
5216 493137 $430,000
5217 936275 $950,000
5218 503324 $525,000
5219 888625 $1,800,000
5220 1530000 $1,150,000
5221 165000 $329,900
5222 724117 $875,000
5223 787170 $910,000
5224 1215800 $1,890,000
5225 617713 $624,500
5226 625123 $640,000
5227 496507 $500,000
5228 496520 $390,000
5229 617713 $620,000
5230 522941 $499,950
5231 344180 $330,000
5232 735000 $850,000
5233 600432 $599,950
5234 720587 $699,000
5235 351193 $374,000
5236 519271 $467,000
5237 600432 $593,000
5238 329996 $223,000
5239 600432 $593,777
5240 500000 $539,500
5241 536000 $550,000
5242 325000 $265,000
5243 453000 $428,000
5244 883041 $925,000
5245 720587 $695,000
5246 720587 $700,000
5247 466500 $470,000
5248 765034 $810,000
5249 600432 $589,000
5250 587027 $572,500
5251 447000 $302,000
5252 503324 $485,000
5253 398723 $383,000
5254 761000 $750,000
5255 372000 $372,000
5256 470676 $425,000
5257 752604 $754,000
5258 872264 $891,500
5259 285000 $349,950
5260 739100 $975,000
5261 406000 $350,000
5262 639104 $990,000
5263 551305 $518,000
5264 695000 $695,000
5265 606899 $720,000
5266 606899 $625,000
5267 432000 $420,000
5268 724117 $800,000
5269 952990 $915,000
5270 408000 $400,000
5271 625123 $750,000
5272 1129562 $1,820,000
5273 871962 $940,000
5274 351193 $326,250
5275 278410 $200,000
5276 606899 $625,000
5277 171667 $130,000
5278 300000 $229,000
5279 567241 $539,950
5280 503324 $450,000
5281 510274 $515,000
5282 666642 $681,000
5283 351193 $255,000
5284 351193 $286,000
5285 448700 $380,000
5286 600432 $449,950
5287 351193 $255,000
5288 389840 $389,000
5289 351193 $210,000
5290 1680000 $1,680,000
5291 484000 $360,000
5292 310000 $257,500
5293 453877 $455,000
5294 625123 $639,900
5295 575000 $563,500
5296 503324 $510,000
5297 264368 $289,000
5298 380000 $365,000
5299 460762 $410,000
5300 327750 $284,000
5301 577663 $550,120
5302 600432 $602,500
5303 456842 $235,000
5304 360107 $375,000
5305 600432 $599,000
5306 600432 $562,100
5307 720587 $714,000
5308 351193 $368,000
5309 724117 $830,000
5310 398709 $282,500
5311 421805 $335,000
5312 560650 $558,000
5313 414454 $270,000
5314 496520 $493,000
5315 724117 $740,000
5316 654700 $715,000
5317 600432 $600,000
5318 617713 $802,000
5319 522941 $521,900
5320 329504 $275,000
5321 350938 $229,950
5322 503324 $468,000
5323 281645 $229,950
5324 620665 $670,000
5325 654231 $680,000
5326 351193 $325,000
5327 625123 $875,000
5328 522941 $426,000
5329 883041 $868,500
5330 351193 $366,000
5331 398000 $385,000
5332 488822 $459,000
5333 1650000 $2,110,000
5334 724117 $825,000
5335 600432 $590,000
5336 503324 $452,100
5337 890114 $950,000
5338 502925 $475,000
5339 363025 $307,000
5340 447043 $433,000
5341 522941 $476,000
5342 308900 $230,000
5343 438530 $427,500
5344 402000 $400,000
5345 351193 $350,000
5346 503324 $525,000
5347 292314 $315,000
5348 817768 $820,000
5349 600432 $599,000
5350 647621 $639,950
5351 702078 $824,000

5352 787170 $950,000
5353 720587 $822,000
5354 460762 $473,600
5355 496507 $490,000
5356 953000 $1,340,000
5357 600432 $549,000
5358 883041 $913,888
5359 724117 $689,888
5360 600432 $602,500
5361 398709 $355,000
5362 720587 $756,000
5363 864303 $800,000
5364 450000 $517,500
5365 325607 $310,000
5366 724117 $749,500
5367 724117 $815,000
5368 2200000 $2,200,000
5369 449430 $429,950
5370 600432 $580,000
5371 796668 $862,500
5372 600432 $589,000
5373 329504 $230,000
5374 642416 $655,000
5375 600432 $572,000
5376 606899 $615,000
5377 444212 $375,000
5378 774367 $925,000
5379 389000 $429,000
5380 389000 $400,000
5381 617713 $625,000
5382 456500 $349,000
5383 481275 $487,500
5384 522941 $475,000
5385 606899 $685,000
5386 366907 $385,000
5387 347500 $352,000
5388 620665 $622,500
5389 400000 $420,000
5390 503324 $499,950
5391 900290 $975,000
5392 503324 $540,000
5393 503324 $469,950
5394 380000 $346,500
5395 680247 $685,000
5396 744372 $783,500
5397 1575000 $1,500,000
5398 248500 $355,000
5399 363025 $223,000
5400 600432 $577,000
5401 617713 $645,000
5402 351193 $280,000
5403 411975 $405,500
5404 522475 $495,000
5405 750661 $750,000
5406 404600 $412,500
5407 725000 $920,000
5408 522941 $537,100
5409 280500 $329,950
5410 522941 $490,000
5411 600432 $579,000
5412 600432 $600,000
5413 496520 $445,000
5414 382707 $362,500
5415 503324 $525,000
5416 332382 $319,500
5417 625000 $850,000
5418 724117 $775,000
5419 731200 $800,000
5420 479996 $436,800
5421 281645 $165,000
5422 503324 $490,000
5423 496520 $480,000
5424 542519 $570,000
5425 336602 $326,000
5426 503324 $450,000
5427 600432 $546,000
5428 720587 $765,000
5429 264368 $285,000
5430 479461 $335,000
5431 423416 $430,000
5432 426794 $425,000
5433 924250 $998,000
5434 400500 $396,000
5435 625123 $633,000
5436 395770 $265,800
5437 568202 $489,000
5438 519349 $513,000
5439 750661 $765,000
5440 871962 $974,350
5441 650000 $653,675
5442 440567 $390,000
5443 606899 $606,500
5444 503324 $500,000
5445 543828 $550,000
5446 978283 $980,000
5447 484755 $361,000
5448 774367 $760,000
5449 522941 $495,000
5450 396800 $260,000
5451 720587 $697,000
5452 316839 $212,625
5453 600432 $593,000
5454 437684 $400,000
5455 522941 $532,000
5456 460762 $287,000
5457 878000 $1,120,000
5458 720587 $765,000
5459 460762 $417,000
5460 575095 $573,300
5461 484755 $260,000
5462 280196 $280,000
5463 833545 $825,000
5464 542000 $528,000
5465 617713 $782,000
5466 351193 $320,000
5467 271031 $153,500
5468 411975 $414,500
5469 265028 $248,500
5470 488746 $500,000
5471 436181 $250,000
5472 455285 $440,000
5473 434000 $402,000
5474 626847 $635,000
5475 507687 $479,000
5476 482242 $462,370
5477 617713 $675,000
5478 404975 $499,950
5479 246294 $295,000
5480 389206 $435,000
5481 503324 $508,000
5482 2400000 $2,400,000
5483 496520 $430,000
5484 456842 $345,000
5485 398709 $410,000
5486 496520 $485,000
5487 778545 $770,000
5488 351193 $325,000
5489 724117 $760,000
5490 398723 $415,000
5491 978283 $996,000
5492 720587 $717,000
5493 900290 $1,230,000
5494 1277500 $1,260,000
5495 453877 $249,950
5496 888625 $1,990,000
5497 488822 $442,900
5498 456842 $395,000
5499 358545 $390,000
5500 522941 $505,000
5501 390000 $335,750
5502 647621 $719,000
5503 398235 $417,000
5504 398723 $410,000
5505 724117 $984,000
5506 336903 $314,950
5507 625123 $657,000
5508 720587 $706,000
5509 792390 $770,000
5510 451000 $449,000
5511 724117 $1,000,000
5512 421805 $406,000
5513 720587 $770,000
5514 405000 $419,000
5515 503324 $479,000
5516 272719 $310,000
5517 674145 $666,000
5518 1230818 $2,230,000
5519 617713 $610,000
5520 600432 $564,800
5521 750000 $855,000
5522 332382 $229,000
5523 354094 $260,000
5524 351193 $277,000
5525 424950 $283,000
5526 507687 $415,000
5527 746829 $1,440,000
5528 325607 $180,000
5529 600432 $592,500
5530 351193 $340,000
5531 535000 $545,000
5532 619575 $625,000
5533 537500 $560,000
5534 496520 $320,000
5535 869322 $802,500
5536 978283 $935,000
5537 617713 $860,000
5538 389840 $274,000
5539 522941 $499,000
5540 316839 $265,000
5541 449430 $295,000
5542 1480000 $1,480,000
5543 308900 $285,000
5544 1269576 $1,470,000
5545 600432 $565,500
5546 600432 $565,000
5547 496520 $438,000
5548 355295 $405,000
5549 661901 $690,000
5550 522941 $526,500
5551 951673 $1,040,000
5552 351193 $335,000
5553 592500 $570,000
5554 1014084 $1,080,000
5555 522941 $475,000
5556 384073 $315,000
5557 600432 $562,000
5558 436512 $352,500
5559 351193 $239,950
5560 522941 $515,000
5561 600432 $590,000
5562 1215958 $1,160,000
5563 325179 $199,000
5564 724117 $730,000
5565 259969 $240,000
5566 466680 $415,000
5567 398709 $378,510
5568 1006665 $1,200,000
5569 398709 $379,900
5570 314792 $308,500
5571 883041 $989,900
5572 398709 $295,000
5573 409425 $270,000
5574 600432 $410,000
5575 600432 $588,000
5576 522941 $420,000
5577 724117 $765,000
5578 764855 $967,500
5579 724117 $716,000
5580 606899 $605,000
5581 340109 $255,000
5582 807228 $780,000
5583 445838 $450,000
5584 398709 $420,000
5585 1610000 $1,610,000
5586 724117 $740,000
5587 675636 $860,000
5588 600432 $620,000
5589 448700 $410,000
5590 617713 $825,000
5591 697001 $713,414
5592 301333 $190,000
5593 570777 $560,000
5594 830075 $998,000
5595 618354 $725,000
5596 292314 $210,000
5597 936275 $1,050,000
5598 942877 $925,000
5599 529999 $545,000
5600 272719 $219,900
5601 398709 $380,000
5602 1181667 $2,600,000
5603 475515 $450,000
5604 746923 $834,800
5605 375667 $365,000
5606 861600 $840,000
5607 496507 $465,000
5608 351193 $240,000
5609 522941 $300,523
5610 551305 $552,500
5611 912273 $1,070,000
5612 883041 $825,000
5613 405000 $420,000
5614 398709 $389,000
5615 522941 $550,000
5616 351193 $201,500
5617 522941 $459,000
5618 521000 $521,000
5619 392000 $375,000
5620 1044458 $1,520,000
5621 385000 $383,000
5622 385000 $249,950
5623 457682 $431,000
5624 496520 $459,900
5625 503324 $475,000
5626 978283 $910,000
5627 774367 $915,000
5628 441250 $416,100
5629 720587 $750,000
5630 496507 $310,000
5631 724117 $725,000
5632 883041 $1,030,000
5633 611194 $610,000
5634 449430 $430,000
5635 600432 $600,000
5636 661901 $638,000
5637 522941 $561,000
5638 625123 $625,000
5639 405628 $329,500
5640 503324 $464,950
5641 600432 $599,000
5642 496507 $462,600
5643 648370 $875,000
5644 382707 $393,000
5645 720587 $671,000
5646 289000 $245,000
5647 325607 $337,000
5648 844258 $920,000
5649 322053 $335,000
5650 1269576 $1,380,000
5651 276750 $265,000
5652 665000 $795,000
5653 724117 $699,900
5654 281645 $295,000
5655 492223 $275,000
5656 1412500 $1,500,000
5657 720587 $795,000
5658 639104 $650,000
5659 398709 $382,000
5660 732124 $790,100
5661 724117 $799,000
5662 720587 $898,000
5663 737299 $972,000
5664 351193 $361,280
5665 371812 $385,000
5666 522941 $475,000
5667 883041 $935,000
5668 600432 $585,000
5669 600432 $585,000
5670 414406 $432,500
5671 600432 $589,000
5672 841891 $840,000
5673 600432 $536,000
5674 540000 $563,750
5675 724117 $731,688
5676 284409 $289,000
5677 351193 $233,000
5678 617713 $625,000
5679 409425 $360,000
5680 815800 $970,000
5681 503324 $426,000
5682 496507 $325,000
5683 496520 $340,000
5684 454000 $447,000
5685 507687 $470,000
5686 731200 $735,000
5687 333000 $200,000
5688 1024792 $1,300,000
5689 383212 $352,000
5690 724117 $905,000
5691 606899 $628,000
5692 640233 $675,000
5693 947500 $1,080,000
5694 883041 $1,050,000
5695 746829 $840,000
5696 445575 $285,000
5697 724117 $723,000
5698 600432 $430,000
5699 606899 $645,000
5700 1000227 $1,580,000
5701 951673 $939,000
5702 351193 $320,000
5703 358545 $365,000
5704 488746 $502,000
5705 410750 $423,000
5706 585181 $500,000
5707 440000 $442,000
5708 350938 $194,000
5709 724117 $1,030,000
5710 593000 $490,000
5711 447043 $348,500
5712 606899 $660,000
5713 1215958 $1,210,000
5714 522941 $525,000
5715 460762 $430,000
5716 522941 $534,640
5717 793514 $1,230,000
5718 347703 $320,000
5719 705904 $690,000
5720 724117 $725,126
5721 325179 $135,000
5722 688961 $1,770,000
5723 492223 $390,000
5724 301553 $147,400
5725 503324 $245,000
5726 522941 $520,000
5727 398723 $352,500
5728 1080208 $2,150,000
5729 724117 $735,000
5730 363025 $375,000
5731 1345429 $1,950,000
5732 470676 $310,000
5733 619400 $650,000
5734 460762 $412,000
5735 340109 $225,000
5736 606899 $616,200
5737 606899 $612,125
5738 978283 $972,800
5739 516239 $399,000
5740 395000 $376,000
5741 447043 $340,000
5742 452500 $490,000
5743 500000 $374,000
5744 522941 $540,000
5745 378745 $450,000
5746 351193 $157,500
5747 556816 $542,000
5748 1456812 $1,900,000
5749 301553 $350,000
5750 799500 $1,300,000
5751 542519 $475,000
5752 398709 $390,000
5753 625123 $645,000
5754 1150000 $1,150,000
5755 724117 $752,000
5756 583000 $585,000
5757 1058458 $1,400,000
5758 720587 $1,090,000
5759 452115 $467,500
5760 724117 $745,000
5761 606899 $615,000
5762 1155000 $1,150,000
5763 536697 $480,000
5764 802568 $1,400,000
5765 1943333 $2,300,000
5766 351193 $345,000
5767 720587 $684,680
5768 951673 $910,000
5769 1559745 $3,070,000
5770 492223 $442,500
5771 351193 $229,000
5772 470000 $518,000
5773 493137 $399,950
5774 503324 $513,000
5775 317397 $329,000
5776 606899 $607,500
5777 1269576 $1,120,000
5778 314792 $340,000
5779 647621 $635,250
5780 351193 $324,800
5781 617713 $640,500
5782 606899 $1,330,000
5783 522941 $535,000
5784 496520 $492,000
5785 625123 $622,500
5786 680247 $678,000
5787 485377 $493,000
5788 344180 $147,000
5789 351193 $345,000
5790 606899 $599,000
5791 344180 $225,000
5792 731200 $734,500
5793 317539 $235,000
5794 438530 $450,000
5795 1595000 $1,470,000
5796 847272 $900,000
5797 752604 $780,000
5798 600432 $572,500
5799 617713 $720,000
5800 681248 $650,000
5801 451349 $436,000
5802 600432 $658,000
5803 860000 $880,000
5804 385925 $375,000
5805 435000 $500,000
5806 460762 $450,000
5807 724117 $840,500
5808 677723 $679,000
5809 460762 $270,000
5810 720587 $757,500
5811 600432 $524,950
5812 522941 $551,100
5813 366907 $421,000
5814 300000 $255,000
5815 606899 $655,275
5816 897500 $813,000
5817 774367 $990,000
5818 459000 $398,000
5819 953000 $839,000
5820 600432 $574,950
5821 351193 $387,000
5822 335000 $336,750
5823 661901 $645,000
5824 479000 $479,000
5825 485377 $404,000
5826 452115 $320,000
5827 982500 $1,000,000
5828 653000 $660,000
5829 570777 $546,000
5830 427800 $300,000
5831 503324 $500,000
5832 720587 $990,000
5833 724117 $760,000
5834 539634 $539,500
5835 387450 $299,980
5836 219000 $254,500
5837 369000 $409,950
5838 479461 $497,950
5839 351193 $334,000
5840 496520 $453,500
5841 731200 $915,000
5842 617467 $619,850
5843 515000 $525,000
5844 720587 $802,000
5845 3200000 $3,200,000
5846 471000 $480,000
5847 720587 $751,000
5848 352636 $423,000
5849 600432 $601,002
5850 1220000 $1,080,000
5851 724117 $700,000
5852 503324 $537,000
5853 400291 $405,000
5854 1058458 $1,110,000
5855 841891 $1,190,000
5856 606899 $615,000
5857 1181667 $1,100,000
5858 600432 $575,000
5859 522941 $527,500
5860 351193 $325,000
5861 346100 $295,000
5862 487814 $470,000
5863 570777 $565,000
5864 503324 $547,000
5865 293471 $125,000
5866 1912172 $2,300,000
5867 457327 $439,950
5868 327000 $207,000
5869 1090000 $1,090,000
5870 724117 $730,000
5871 731200 $745,000
5872 1830000 $1,830,000
5873 724117 $715,000
5874 617713 $611,000
5875 496520 $463,000
5876 551613 $369,950
5877 600432 $589,500
5878 503324 $458,000
5879 436000 $436,000
5880 335000 $310,000
5881 978283 $1,010,000
5882 398709 $435,000
5883 746829 $790,000
5884 1680000 $1,680,000
5885 503324 $250,000
5886 994000 $1,120,000
5887 625123 $624,000
5888 496507 $383,000
5889 600432 $558,000
5890 437867 $275,000
5891 720587 $700,000
5892 384073 $342,500
5893 411975 $190,000
5894 411975 $300,000
5895 503324 $370,000
5896 351193 $260,000
5897 606899 $640,000
5898 724117 $723,000
5899 475515 $388,000
5900 350938 $249,950
5901 724117 $705,000
5902 330000 $319,500
5903 240000 $265,000
5904 724117 $740,000
5905 522941 $561,000
5906 351193 $342,500
5907 951673 $910,000
5908 447043 $419,950
5909 746923 $799,950
5910 522941 $400,000
5911 510000 $518,000
5912 444212 $402,000
5913 409425 $448,500
5914 840000 $779,000
5915 978283 $1,850,000
5916 370000 $343,000
5917 325607 $265,000
5918 951673 $889,000
5919 398709 $407,000
5920 1160000 $1,160,000
5921 265028 $300,000
5922 600587 $500,000
5923 800000 $925,000
5924 600432 $593,567
5925 522941 $440,000
5926 745000 $751,000
5927 900290 $890,900
5928 664758 $672,500
5929 1585714 $1,680,000
5930 724117 $725,000
5931 600432 $595,000
5932 868743 $850,000
5933 453877 $366,000
5934 715000 $715,000
5935 550011 $538,000
5936 351193 $280,500
5937 404280 $295,000
5938 522941 $560,000
5939 950333 $912,000
5940 490000 $437,000
5941 452660 $447,000
5942 502345 $500,000
5943 398709 $325,000
5944 724117 $965,800
5945 570777 $550,000
5946 315000 $315,000
5947 600432 $480,000
5948 749950 $1,260,000
5949 522941 $520,000
5950 617713 $750,000
5951 351193 $275,000
5952 503324 $546,000
5953 377186 $435,000
5954 600432 $579,000
5955 496507 $525,000
5956 496520 $455,000
5957 617713 $650,000
5958 398709 $400,000
5959 1086042 $989,000
5960 503324 $485,000
5961 452660 $385,000
5962 360107 $375,000
5963 436512 $468,000
5964 445575 $412,500
5965 545000 $545,000
5966 295000 $133,000
5967 479821 $440,000

5968 389840 $322,000
5969 496507 $380,000
5970 731200 $784,000
5971 600432 $600,000
5972 375000 $359,900
5973 724117 $700,000
5974 302247 $280,000
5975 625123 $655,000
5976 2140000 $2,480,000
5977 522941 $540,000
5978 496520 $474,000
5979 1113875 $1,160,000
5980 720587 $696,000
5981 503324 $518,000
5982 1520000 $1,520,000
5983 479461 $322,000
5984 351193 $229,000
5985 600432 $583,500
5986 522941 $539,000
5987 503324 $535,000
5988 308900 $286,000
5989 731200 $710,000
5990 445575 $464,000
5991 284409 $257,500
5992 724117 $840,000
5993 351193 $282,500
5994 606899 $827,235
5995 351193 $249,950
5996 479461 $400,000
5997 648834 $865,000
5998 870000 $899,950
5999 355000 $370,000
6000 325607 $310,000
6001 760111 $1,570,000
6002 600432 $510,000
6003 225000 $299,950
6004 257000 $300,000
6005 665923 $994,000
6006 503324 $480,500
6007 351193 $373,000
6008 724117 $728,000
6009 330000 $415,000
6010 510274 $431,500
6011 496520 $490,000
6012 1119500 $1,430,000
6013 314792 $325,000
6014 724117 $960,000
6015 323264 $235,000
6016 548750 $431,000
6017 774900 $778,000
6018 617713 $910,000
6019 872264 $860,000
6020 724117 $782,000
6021 522941 $525,000
6022 330000 $345,000
6023 351193 $237,000
6024 385925 $305,000
6025 833545 $981,000
6026 720587 $680,000
6027 616636 $850,000
6028 720587 $693,000
6029 600432 $478,000
6030 625123 $635,000
6031 210000 $180,000
6032 503324 $490,000
6033 606899 $615,000
6034 611194 $618,000
6035 1226500 $1,190,000
6036 301333 $230,000
6037 436181 $447,000
6038 439000 $436,000
6039 720587 $765,000
6040 560650 $564,000
6041 398709 $384,500
6042 568658 $465,950
6043 503324 $450,000
6044 503324 $475,000
6045 883041 $1,350,000
6046 600432 $540,000
6047 631063 $987,000
6048 1400000 $1,190,000
6049 503324 $497,300
6050 496520 $377,000
6051 386180 $396,500
6052 258305 $300,000
6053 1058458 $1,400,000
6054 293000 $301,950
6055 1064375 $1,370,000
6056 351193 $226,000
6057 724117 $840,000
6058 432674 $399,000
6059 348945 $315,450
6060 351193 $330,000
6061 689945 $655,000
6062 475515 $437,500
6063 600432 $568,500
6064 280196 $247,500
6065 883041 $1,250,000
6066 736528 $814,842
6067 351193 $230,000
6068 449430 $210,000
6069 366907 $293,000
6070 398709 $325,000
6071 577663 $588,000
6072 351193 $200,000
6073 503324 $495,000
6074 639104 $637,000
6075 600432 $589,000
6076 389840 $305,000
6077 583206 $587,000
6078 731200 $833,000
6079 802500 $860,000
6080 271031 $180,000
6081 503324 $507,000
6082 485377 $427,000
6083 496520 $372,000
6084 978283 $1,550,000
6085 470676 $434,400
6086 642416 $1,320,000
6087 600432 $560,000
6088 482242 $445,000
6089 522941 $535,000
6090 606899 $570,000
6091 562100 $555,000
6092 351193 $350,000
6093 317397 $245,000
6094 503324 $465,000
6095 503324 $517,850
6096 522941 $512,500
6097 618354 $915,000
6098 351193 $329,950
6099 522941 $532,500
6100 706856 $683,000
6101 301333 $218,000
6102 496507 $460,000
6103 566231 $480,000
6104 883041 $1,300,000
6105 503324 $475,000
6106 316371 $290,000
6107 382707 $360,000
6108 600000 $585,083
6109 731200 $840,000
6110 357186 $326,000
6111 398709 $447,000
6112 456842 $439,950
6113 724117 $750,000
6114 802583 $865,000
6115 448700 $375,000
6116 325179 $190,000
6117 439500 $399,950
6118 522941 $528,000
6119 1585714 $1,490,000
6120 600432 $590,000
6121 522941 $439,000
6122 503324 $277,554
6123 720587 $1,200,000
6124 720587 $710,000
6125 577500 $535,000
6126 600432 $600,000
6127 452660 $285,000
6128 724117 $800,000
6129 260000 $216,500
6130 532435 $550,000
6131 387403 $400,000
6132 665923 $1,950,000
6133 1604965 $1,400,000
6134 370000 $400,000
6135 1233250 $2,330,000
6136 298580 $225,000
6137 1037500 $1,250,000
6138 389840 $380,000
6139 600432 $600,000
6140 479461 $315,000
6141 837321 $847,000
6142 724117 $730,000
6143 724117 $1,060,000
6144 606899 $664,000
6145 600432 $565,000
6146 600432 $585,000
6147 787170 $750,000
6148 617713 $672,500
6149 606899 $620,000
6150 617713 $615,000
6151 731200 $870,000
6152 746829 $740,000
6153 366907 $336,500
6154 436512 $420,000
6155 951673 $1,030,000
6156 625123 $625,000
6157 369000 $255,000
6158 606899 $869,000
6159 742076 $745,000
6160 951673 $1,350,000
6161 522941 $540,000
6162 883041 $890,000
6163 1336000 $1,050,000
6164 647621 $670,000
6165 488000 $480,000
6166 405628 $440,000
6167 1006665 $1,190,000
6168 847272 $875,000
6169 1285700 $1,390,000
6170 600432 $600,000
6171 620000 $650,000
6172 256278 $275,000
6173 340109 $318,000
6174 724117 $817,000
6175 522941 $525,000
6176 625123 $629,950
6177 606899 $641,500
6178 503324 $490,000
6179 415000 $415,000
6180 618354 $781,000
6181 351193 $355,000
6182 724117 $926,250
6183 344180 $361,500
6184 617713 $616,000
6185 398709 $395,000
6186 570777 $578,000
6187 600432 $575,000
6188 351193 $330,000
6189 400000 $445,000
6190 351193 $333,000
6191 600432 $598,500
6192 720587 $779,000
6193 724117 $760,000
6194 600432 $595,000
6195 351193 $321,000
6196 631276 $653,000
6197 724117 $750,000
6198 600432 $558,000
6199 351193 $340,000
6200 600432 $548,000
6201 492223 $411,715
6202 1604965 $1,750,000
6203 628565 $755,000
6204 625123 $667,400
6205 810000 $1,220,000
6206 317397 $227,000
6207 606899 $625,000
6208 759067 $822,600
6209 292000 $377,000
6210 600432 $600,000
6211 769417 $760,000
6212 774367 $810,000
6213 274939 $197,000
6214 325179 $254,000
6215 398709 $416,000
6216 746923 $779,950
6217 645000 $658,100
6218 398709 $397,000
6219 427000 $330,000
6220 351193 $349,950
6221 625123 $619,500
6222 398723 $380,500
6223 250000 $253,000
6224 619575 $627,000
6225 503324 $469,500
6226 342500 $319,950
6227 522941 $485,000
6228 720587 $699,850
6229 485377 $450,000
6230 284409 $271,000
6231 394000 $305,000
6232 351193 $255,000
6233 731200 $821,000
6234 951673 $885,000
6235 317539 $304,000
6236 398709 $376,000
6237 1326667 $1,400,000
6238 1548333 $1,980,000
6239 731200 $950,000
6240 721739 $725,000
6241 503324 $505,000
6242 148633 $90,000
6243 496507 $400,000
6244 367417 $369,000
6245 293471 $155,000
6246 496520 $379,000
6247 600432 $592,100
6248 351193 $227,000
6249 272719 $199,988
6250 385925 $279,000
6251 460762 $333,500
6252 400291 $345,000
6253 903860 $1,260,000
6254 503324 $440,000
6255 522941 $444,500
6256 724117 $968,000
6257 470676 $355,000
6258 1584375 $1,810,000
6259 617713 $885,000
6260 466680 $455,000
6261 724117 $980,000
6262 445588 $412,500
6263 724117 $740,000
6264 1097467 $1,300,000
6265 625123 $620,000
6266 449430 $283,000
6267 503324 $376,000
6268 720587 $710,000
6269 503324 $439,000
6270 460762 $455,000
6271 600432 $585,000
6272 400291 $400,000
6273 2200000 $2,200,000
6274 265000 $256,000
6275 606899 $615,000
6276 1100000 $1,200,000
6277 503678 $347,950
6278 351193 $205,000
6279 724117 $705,000
6280 600432 $535,000
6281 377186 $313,500
6282 720587 $712,000
6283 487814 $470,000
6284 351193 $367,000
6285 522941 $440,500
6286 611194 $1,020,000
6287 647621 $660,000
6288 522941 $552,321
6289 617713 $1,100,000
6290 398709 $402,000
6291 449430 $470,000
6292 808699 $808,000
6293 759067 $775,000
6294 496520 $464,600
6295 600432 $590,000
6296 452660 $399,000
6297 336602 $305,000
6298 496520 $478,000
6299 423416 $433,000
6300 347703 $305,000
6301 878000 $900,000
6302 543599 $540,000
6303 398235 $324,950
6304 625123 $1,150,000
6305 606899 $637,000
6306 708274 $704,000
6307 522941 $550,000
6308 731200 $795,000
6309 529888 $495,000
6310 351193 $387,000
6311 398709 $422,000
6312 451349 $365,000
6313 484000 $424,000
6314 1692500 $1,350,000
6315 405628 $418,000
6316 764855 $800,000
6317 496520 $476,000
6318 496520 $478,000
6319 746923 $890,000
6320 453877 $450,000
6321 575000 $449,400
6322 496520 $450,000
6323 452115 $310,000
6324 617713 $615,000
6325 476911 $437,500
6326 631276 $770,000
6327 600432 $600,000
6328 522941 $560,000
6329 351193 $345,000
6330 600432 $550,000
6331 367417 $327,000
6332 351193 $350,000
6333 724117 $750,000
6334 587994 $582,000
6335 503324 $465,000
6336 522941 $540,000
6337 496520 $529,000
6338 1770000 $1,650,000
6339 398709 $400,950
6340 377186 $379,950
6341 606899 $605,000
6342 318391 $194,000
6343 951673 $1,400,000
6344 482242 $315,000
6345 468363 $465,000
6346 766350 $795,000
6347 314792 $126,500
6348 724117 $760,000
6349 280196 $170,000
6350 395000 $379,000
6351 731200 $800,000
6352 841891 $820,000
6353 453877 $392,000
6354 438822 $465,000
6355 475000 $449,950
6356 731200 $825,000
6357 398709 $380,000
6358 576114 $585,000
6359 496507 $435,000
6360 522941 $515,000
6361 587994 $590,000
6362 385977 $425,000
6363 339000 $407,500
6364 522941 $524,000
6365 522941 $560,000
6366 995000 $995,000
6367 837321 $835,000
6368 460762 $440,000
6369 1120000 $1,020,000
6370 351193 $300,000
6371 951673 $986,000
6372 479996 $315,000
6373 978283 $972,000
6374 753000 $760,000
6375 351193 $355,000
6376 351193 $300,000
6377 479996 $474,950
6378 457682 $457,000
6379 642416 $635,000
6380 724117 $735,000
6381 721739 $910,000
6382 488746 $346,500
6383 440567 $425,000
6384 363025 $420,000
6385 570777 $560,000
6386 310000 $226,000
6387 351193 $358,000
6388 503324 $501,000
6389 447043 $350,500
6390 807228 $1,390,000
6391 369409 $335,000
6392 352636 $397,000
6393 1081195 $2,300,000
6394 617713 $615,000
6395 617713 $736,500
6396 522941 $542,500
6397 245790 $191,000
6398 1172150 $1,230,000
6399 716481 $675,000
6400 496520 $485,000
6401 720587 $720,000
6402 3050000 $3,100,000
6403 496520 $499,000
6404 631276 $632,000
6405 600432 $580,000
6406 724117 $730,000
6407 352636 $421,000
6408 452115 $316,000
6409 354094 $335,000
6410 325000 $339,000
6411 617713 $650,000
6412 724117 $975,000
6413 460762 $420,000
6414 503324 $430,000
6415 398723 $413,000
6416 488822 $495,000
6417 861600 $965,000
6418 606899 $636,100
6419 720587 $720,000
6420 891250 $917,000
6421 978283 $957,000
6422 756167 $760,369
6423 625123 $625,000
6424 457232 $357,000
6425 367423 $400,000
6426 461550 $465,000
6427 487814 $425,000
6428 496507 $445,000
6429 330000 $385,000
6430 351193 $303,000
6431 720587 $710,000
6432 792390 $838,000
6433 551305 $562,500
6434 382600 $389,999
6435 492000 $450,000
6436 351193 $208,000
6437 522941 $455,000
6438 286499 $190,000
6439 358545 $168,000
6440 606899 $630,000
6441 381910 $400,000
6442 600432 $600,000
6443 487500 $450,600
6444 522941 $550,000
6445 507031 $415,000
6446 400000 $390,000
6447 758947 $750,000
6448 724117 $845,000
6449 445000 $350,000
6450 606899 $675,000
6451 503324 $503,000
6452 618693 $780,000
6453 731200 $733,000
6454 617713 $640,000
6455 724117 $840,000
6456 617713 $625,000
6457 437867 $350,000
6458 398709 $435,000
6459 606899 $660,000
6460 503324 $435,000
6461 460762 $500,000
6462 712000 $712,000
6463 600432 $425,000
6464 496520 $415,000
6465 437684 $360,000
6466 883041 $960,000
6467 522941 $500,000
6468 978283 $1,780,000
6469 351193 $367,500
6470 600432 $535,000
6471 618354 $655,000
6472 951673 $1,300,000
6473 468363 $465,000
6474 600432 $590,000
6475 507687 $500,000
6476 1215958 $2,500,000
6477 245790 $209,995
6478 697001 $680,000
6479 503324 $505,000
6480 539634 $560,000
6481 305572 $135,000
6482 480000 $420,000
6483 351193 $360,000
6484 625123 $642,000
6485 455000 $379,950
6486 322053 $275,000
6487 489798 $435,000
6488 245790 $175,000
6489 447043 $325,000
6490 724117 $752,000
6491 1413421 $1,200,000
6492 275000 $240,000
6493 625123 $640,000
6494 600432 $564,450
6495 445575 $300,000
6496 503324 $502,000
6497 724117 $993,500
6498 411975 $450,000
6499 951673 $997,950
6500 522941 $526,000
6501 308500 $305,000
6502 1191667 $1,380,000
6503 720587 $707,000
6504 720587 $695,000
6505 738933 $796,500
6506 503324 $420,000
6507 325179 $275,000
6508 724117 $760,000
6509 522941 $499,000
6510 625123 $620,000
6511 522941 $525,000
6512 356385 $300,000
6513 323264 $280,000
6514 570777 $569,950
6515 316371 $300,000
6516 625123 $629,950
6517 695123 $690,000
6518 864303 $1,290,000
6519 680247 $685,000
6520 351193 $387,500
6521 398709 $401,750
6522 500000 $500,000
6523 790658 $856,500
6524 503324 $506,500
6525 522941 $500,000
6526 613000 $613,500
6527 625123 $620,000
6528 483125 $450,000
6529 625123 $625,000
6530 496520 $423,000
6531 433190 $250,000
6532 350000 $350,000
6533 350000 $399,000
6534 516239 $529,000
6535 625123 $640,000
6536 503324 $380,000
6537 625123 $624,900
6538 436512 $379,770
6539 565000 $515,500
6540 381910 $400,000
6541 576114 $440,000
6542 323264 $317,000
6543 503324 $518,000
6544 556816 $555,000
6545 325179 $244,000
6546 579297 $578,550
6547 543599 $451,000
6548 503324 $475,000
6549 522941 $530,000
6550 883041 $1,630,000
6551 606899 $637,500
6552 583206 $543,500
6553 436512 $430,000
6554 600432 $600,000
6555 496520 $476,800
6556 522941 $455,600
6557 325607 $270,000
6558 1269576 $1,200,000
6559 570777 $525,000
6560 724117 $715,000
6561 522941 $475,000
6562 577112 $520,000
6563 720587 $725,000
6564 351193 $335,000
6565 738933 $919,000
6566 842593 $905,000
6567 398709 $435,000
6568 724117 $725,000
6569 476911 $425,500
6570 720074 $853,505
6571 522941 $418,500
6572 724117 $742,000
6573 724117 $739,000
6574 582677 $499,900
6575 808699 $836,500
6576 317539 $334,000
6577 445000 $500,000
6578 157500 $145,000
6579 570777 $550,000
6580 351193 $347,000
6581 451349 $390,000
6582 983750 $1,800,000
6583 452660 $425,000
6584 647621 $648,752
6585 1152875 $1,390,000
6586 314792 $250,000
6587 506950 $475,000
6588 724117 $775,000
6589 503324 $410,000
6590 445575 $445,000
6591 530000 $530,000
6592 617713 $650,000
6593 325460 $325,000
6594 522941 $541,000
6595 586011 $560,000
6596 503324 $490,000
6597 600432 $565,000
6598 355000 $330,000
6599 503324 $463,000
6600 1870000 $1,870,000
6601 664758 $650,000
6602 1325993 $1,560,000
6603 649500 $650,500
6604 868743 $960,000
6605 720587 $710,000
6606 522941 $540,000
6607 458605 $340,000
6608 458605 $363,000
6609 190000 $210,000
6610 460762 $468,000
6611 351193 $268,000
6612 278410 $115,000
6613 522941 $500,000
6614 794700 $982,000
6615 665923 $665,000
6616 1585714 $1,220,000
6617 398709 $380,000
6618 398723 $220,000
6619 617713 $631,500
6620 377186 $386,100
6621 868743 $1,050,000
6622 724117 $870,000
6623 901000 $1,200,000
6624 485377 $465,000
6625 871962 $870,000
6626 235000 $249,000
6627 414454 $425,000
6628 457327 $447,500
6629 492500 $285,000
6630 488822 $336,900
6631 456842 $415,000
6632 522941 $500,000
6633 556816 $419,950
6634 345000 $349,950
6635 968000 $965,000
6636 522941 $515,000
6637 675636 $665,000
6638 905000 $879,000
6639 885000 $833,000
6640 286499 $261,590
6641 512500 $512,500
6642 600432 $600,000
6643 1000227 $970,000
6644 625123 $1,350,000
6645 724117 $840,000
6646 618354 $680,000
6647 796668 $763,000
6648 452660 $475,000
6649 219000 $219,000
6650 183500 $90,000
6651 183500 $220,000
6652 606899 $616,000
6653 769417 $770,000
6654 795000 $840,000
6655 398709 $428,950
6656 842593 $800,000
6657 759067 $754,999
6658 488822 $406,500
6659 1320000 $1,650,000
6660 256278 $160,000
6661 335692 $220,000
6662 1604965 $1,280,000
6663 891250 $970,000
6664 600432 $527,000
6665 953604 $970,000
6666 568658 $535,000
6667 363025 $337,000
6668 301553 $228,500

6669 457327 $436,000
6670 522941 $451,000
6671 825000 $725,000
6672 606899 $605,004
6673 269250 $260,000
6674 351193 $230,000
6675 570777 $540,000
6676 1550000 $1,550,000
6677 522941 $496,600
6678 503324 $350,000
6679 721739 $746,000
6680 600432 $598,555
6681 492223 $465,000
6682 720587 $710,000
6683 679000 $690,000
6684 720587 $721,500
6685 895000 $924,000
6686 855000 $825,000
6687 522941 $560,000
6688 600432 $599,000
6689 400291 $425,000
6690 606899 $612,500
6691 600432 $605,000
6692 720086 $710,000
6693 414429 $399,500
6694 522941 $500,000
6695 606899 $616,750
6696 896000 $1,080,000
6697 731200 $990,000
6698 600432 $590,000
6699 647621 $775,000
6700 647621 $680,000
6701 408200 $395,000
6702 600432 $572,500
6703 720587 $1,330,000
6704 600432 $600,000
6705 503324 $515,000
6706 368000 $425,000
6707 570777 $565,000
6708 398709 $355,000
6709 415000 $322,000
6710 274939 $290,000
6711 978283 $969,500
6712 351193 $261,500
6713 503324 $488,800
6714 351193 $340,000
6715 724117 $799,000
6716 448000 $447,000
6717 606899 $765,000
6718 1560556 $1,320,000
6719 351193 $310,000
6720 398709 $380,000
6721 351193 $325,000
6722 308900 $300,000
6723 600432 $590,000
6724 313500 $270,000
6725 522941 $520,000
6726 398709 $382,000
6727 617713 $1,210,000
6728 951673 $900,000
6729 731200 $675,000
6730 398235 $399,000
6731 720587 $740,000
6732 793514 $799,000
6733 325179 $275,000
6734 503324 $508,450
6735 570777 $550,000
6736 385925 $380,000
6737 522941 $539,900
6738 325179 $330,000
6739 371812 $315,000
6740 600432 $592,500
6741 600432 $600,000
6742 522941 $550,000
6743 869322 $950,000
6744 625123 $623,000
6745 600432 $600,000
6746 600432 $515,000
6747 625123 $638,150
6748 1575000 $1,650,000
6749 278410 $159,100
6750 336903 $299,000
6751 627000 $620,047
6752 503324 $480,000
6753 522941 $515,000
6754 617713 $610,000
6755 503324 $430,000
6756 503324 $480,000
6757 316839 $255,000
6758 318391 $283,700
6759 648370 $731,000
6760 398723 $334,200
6761 596068 $560,000
6762 351193 $306,000
6763 423416 $440,000
6764 366017 $360,000
6765 265028 $217,000
6766 228225 $255,000
6767 625123 $625,000
6768 617713 $680,000
6769 314792 $239,000
6770 847272 $975,000
6771 325179 $330,000
6772 750661 $1,600,000
6773 724117 $715,000
6774 794700 $950,000
6775 951673 $1,190,000
6776 568000 $427,500
6777 300000 $115,000
6778 583206 $550,000
6779 351193 $260,000
6780 522941 $428,000
6781 586653 $590,000
6782 429387 $424,000
6783 606899 $610,000
6784 1151531 $1,320,000
6785 405628 $330,000
6786 351193 $275,000
6787 420000 $411,000
6788 325179 $400,000
6789 295000 $342,000
6790 484755 $475,000
6791 850000 $850,000
6792 720587 $765,000
6793 435000 $437,000
6794 503324 $310,000
6795 317397 $200,000
6796 390000 $430,000
6797 351193 $360,000
6798 575233 $575,000
6799 1261250 $2,030,000
6800 455285 $430,000
6801 485377 $340,000
6802 542519 $440,000
6803 457232 $310,000
6804 377186 $343,000
6805 398709 $415,000
6806 482242 $410,000
6807 522941 $540,000
6808 606899 $715,000
6809 1250000 $1,320,000
6810 1001260 $1,440,000
6811 314792 $275,000
6812 746923 $742,000
6813 647621 $640,000
6814 310000 $301,500
6815 457682 $285,000
6816 503324 $498,000
6817 600432 $607,000
6818 503324 $492,500
6819 600432 $585,000
6820 606899 $625,000
6821 496520 $345,000
6822 351193 $314,000
6823 443950 $400,000
6824 724117 $820,000
6825 1097467 $1,250,000
6826 285000 $275,000
6827 600432 $577,000
6828 503324 $446,950
6829 522941 $457,000
6830 600432 $589,000
6831 1600000 $1,740,000
6832 647621 $705,000
6833 921000 $915,557
6834 496520 $427,000
6835 488822 $455,000
6836 360000 $397,000
6837 271031 $150,000
6838 1375000 $1,680,000
6839 336903 $217,450
6840 661901 $677,000
6841 367417 $361,000
6842 316839 $330,000
6843 716212 $711,000
6844 978283 $1,100,000
6845 329900 $240,000
6846 333000 $321,000
6847 812944 $865,000
6848 600432 $515,500
6849 600432 $576,925
6850 451349 $292,000
6851 432674 $382,880
6852 900000 $852,500
6853 606899 $762,400
6854 522941 $550,000
6855 488822 $449,500
6856 731200 $744,000
6857 708274 $700,000
6858 493137 $511,100
6859 1373232 $1,700,000
6860 487814 $399,000
6861 538278 $346,500
6862 535690 $552,500
6863 456842 $262,500
6864 666642 $660,000
6865 298580 $267,000
6866 351193 $230,000
6867 522941 $535,000
6868 600432 $590,000
6869 438530 $369,300
6870 503324 $510,000
6871 548793 $542,500
6872 292314 $262,500
6873 951673 $1,100,000
6874 448700 $343,500
6875 354094 $400,000
6876 351193 $334,850
6877 606899 $605,000
6878 720587 $760,000
6879 398709 $390,000
6880 522941 $488,000
6881 298580 $299,950
6882 1155364 $2,370,000
6883 442903 $452,000
6884 445575 $330,950
6885 600432 $535,000
6886 570777 $479,000
6887 522941 $529,999
6888 600432 $587,100
6889 496507 $475,000
6890 570777 $581,000
6891 398235 $383,000
6892 496520 $315,000
6893 600432 $591,000
6894 496520 $430,000
6895 724117 $712,000
6896 503324 $510,000
6897 503324 $464,000
6898 720587 $740,000
6899 340000 $339,900
6900 522941 $539,000
6901 833545 $1,390,000
6902 503324 $490,000
6903 724117 $740,000
6904 1360000 $1,360,000
6905 305572 $238,000
6906 724117 $921,000
6907 496520 $380,000
6908 538119 $449,000
6909 460762 $445,000
6910 618354 $750,000
6911 869322 $959,000
6912 398709 $425,000
6913 1860000 $1,860,000
6914 415000 $445,000
6915 543828 $559,000
6916 3300000 $3,300,000
6917 1269576 $1,230,000
6918 305572 $250,000
6919 625123 $625,000
6920 404688 $329,000
6921 692798 $658,000
6922 625123 $655,000
6923 190000 $215,000
6924 496520 $494,000
6925 535000 $560,000
6926 317397 $130,000
6927 351193 $208,000
6928 515000 $451,000
6929 432674 $442,200
6930 453877 $335,000
6931 617713 $625,000
6932 570777 $570,000
6933 720587 $685,000
6934 776035 $792,000
6935 344180 $212,000
6936 625123 $622,500
6937 522941 $525,000
6938 936275 $1,140,000
6939 659616 $655,000
6940 325607 $235,000
6941 227064 $323,000
6942 451349 $455,000
6943 775398 $1,230,000
6944 404280 $325,000
6945 292314 $315,000
6946 930000 $1,070,000
6947 819727 $825,000
6948 350938 $235,000
6949 645000 $650,000
6950 2605000 $2,630,000
6951 606899 $685,000
6952 1050313 $1,250,000
6953 721050 $850,000
6954 344180 $265,000
6955 493137 $465,000
6956 375000 $420,000
6957 1330000 $1,420,000
6958 1037500 $1,730,000
6959 694045 $690,000
6960 351193 $357,500
6961 389840 $358,500
6962 724117 $705,000
6963 351193 $384,950
6964 856707 $840,000
6965 891250 $905,000
6966 367417 $300,000
6967 720587 $695,000
6968 302247 $255,000
6969 562445 $552,700
6970 600432 $571,500
6971 522941 $520,000
6972 340109 $358,000
6973 3650000 $3,650,000
6974 566420 $543,000
6975 318391 $295,000
6976 560650 $544,000
6977 720587 $672,600
6978 606899 $689,800
6979 384073 $340,000
6980 550011 $550,000
6981 323264 $325,000
6982 445575 $475,000
6983 492223 $432,100
6984 359000 $359,000
6985 522941 $545,000
6986 218667 $115,000
6987 470676 $300,000
6988 902431 $1,650,000
6989 350938 $280,000
6990 656487 $849,000
6991 316839 $319,000
6992 1297500 $1,450,000
6993 720587 $695,000
6994 515000 $482,000
6995 351193 $220,000
6996 869322 $1,100,000
6997 426794 $410,000
6998 562445 $562,000
6999 790658 $930,000
7000 731200 $745,000
7001 720587 $720,000
7002 808699 $839,000
7003 568658 $568,000
7004 398709 $382,000
7005 583143 $574,000
7006 512000 $405,000
7007 600432 $572,000
7008 350938 $165,000
7009 350938 $260,000
7010 522941 $515,000
7011 637701 $651,000
7012 265028 $240,000
7013 775398 $768,000
7014 321000 $315,000
7015 398723 $240,000
7016 351193 $325,000
7017 385000 $435,000
7018 385925 $427,500
7019 503324 $450,000
7020 654983 $688,000
7021 351193 $285,000
7022 647621 $1,100,000
7023 720587 $732,500
7024 522941 $526,000
7025 625123 $645,500
7026 725000 $725,000
7027 724117 $815,000
7028 302247 $245,000
7029 812944 $1,320,000
7030 1199658 $1,160,000
7031 522941 $480,000
7032 317539 $329,950
7033 457682 $460,000
7034 600432 $515,000
7035 398709 $355,000
7036 505960 $515,000
7037 600432 $588,000
7038 1002750 $1,050,000
7039 720587 $710,000
7040 600432 $600,000
7041 664758 $683,000
7042 515046 $517,000
7043 724117 $797,500
7044 385977 $379,000
7045 570777 $575,000
7046 432674 $415,000
7047 647621 $693,000
7048 496520 $465,000
7049 302247 $280,000
7050 971667 $1,390,000
7051 503324 $440,000
7052 570777 $572,000
7053 476911 $454,000
7054 535000 $535,000
7055 339888 $320,000
7056 503324 $475,000
7057 385977 $390,000
7058 635061 $746,300
7059 522941 $525,000
7060 680247 $699,950
7061 503324 $464,050
7062 849000 $835,000
7063 484000 $350,000
7064 503324 $415,000
7065 724117 $788,000
7066 496520 $360,000
7067 606899 $692,500
7068 451349 $425,000
7069 606899 $645,000
7070 351193 $340,000
7071 774367 $946,000
7072 503324 $475,000
7073 720587 $750,000
7074 194990 $180,000
7075 280196 $230,000
7076 617713 $759,000
7077 1152875 $1,120,000
7078 325179 $325,000
7079 292314 $210,000
7080 656487 $685,000
7081 724117 $725,000
7082 692798 $695,000
7083 503324 $505,000
7084 731200 $999,000
7085 617713 $740,000
7086 351193 $310,000
7087 415000 $389,000
7088 720587 $731,781
7089 503324 $502,501
7090 577663 $585,000
7091 741852 $1,030,000
7092 351193 $180,000

7093 411975 $322,500
7094 586653 $568,500
7095 925000 $1,090,000
7096 259969 $235,000
7097 720587 $740,000
7098 351193 $415,000
7099 1560556 $1,270,000
7100 606899 $676,500
7101 398709 $419,000
7102 780495 $1,700,000
7103 758436 $1,000,000
7104 600432 $469,950
7105 387000 $361,000
7106 236500 $230,005
7107 460762 $280,000
7108 522941 $520,000
7109 460762 $335,000
7110 606899 $612,000
7111 503324 $520,000
7112 724117 $855,000
7113 577112 $567,500
7114 503324 $519,000
7115 502925 $474,950
7116 398709 $390,000
7117 351193 $355,000
7118 617713 $685,000
7119 325179 $202,500
7120 542519 $540,000
7121 522941 $518,000
7122 323264 $330,000
7123 695000 $898,000
7124 570777 $570,000
7125 500000 $475,000
7126 617713 $620,000
7127 351193 $296,500
7128 436000 $440,000
7129 325179 $269,500
7130 724117 $740,000
7131 496507 $510,000
7132 292314 $300,000
7133 883041 $1,300,000
7134 978283 $925,850
7135 351193 $255,500
7136 351193 $344,950
7137 429387 $381,000
7138 1300936 $1,950,000
7139 600432 $1,500,000
7140 475000 $220,000
7141 456842 $380,000
7142 503324 $511,200
7143 661901 $680,000
7144 950000 $1,050,000
7145 600432 $575,000
7146 351193 $165,000
7147 654143 $850,000
7148 302247 $210,000
7149 389840 $430,000
7150 496520 $385,000
7151 600432 $550,000
7152 503324 $503,000
7153 617713 $620,000
7154 456842 $396,450
7155 536561 $565,000
7156 354460 $374,000
7157 600432 $592,500
7158 452115 $507,000
7159 493137 $291,000
7160 398709 $350,000
7161 840500 $909,000
7162 272719 $187,000
7163 432674 $345,000
7164 571079 $497,000
7165 351193 $345,000
7166 576114 $559,000
7167 470676 $410,000
7168 351193 $259,000
7169 496507 $480,000
7170 470000 $450,000
7171 538278 $410,000
7172 600432 $577,000
7173 484567 $471,000
7174 586653 $560,000
7175 883041 $955,000
7176 1240000 $1,240,000
7177 522941 $485,000
7178 151000 $280,000
7179 503324 $550,000
7180 868743 $1,410,000
7181 868743 $1,510,000
7182 301333 $210,000
7183 308900 $137,000
7184 503324 $400,000
7185 496507 $365,000
7186 430000 $441,000
7187 720587 $717,500
7188 617713 $629,000
7189 438530 $425,000
7190 346500 $346,500
7191 553073 $550,000
7192 585083 $565,000
7193 398709 $400,000
7194 724117 $724,950
7195 600432 $623,000
7196 295000 $295,000
7197 793829 $770,000
7198 600432 $512,000
7199 617713 $680,000
7200 724117 $707,000
7201 617713 $690,000
7202 793514 $872,000
7203 1081195 $925,000
7204 353700 $365,000
7205 617713 $725,000
7206 336903 $299,000
7207 371812 $287,500
7208 891250 $879,950
7209 286499 $135,900
7210 787133 $1,230,000
7211 455285 $450,000
7212 720587 $718,500
7213 460762 $430,000
7214 522941 $402,500
7215 617713 $665,000
7216 385925 $350,000
7217 758947 $789,888
7218 600432 $550,000
7219 883041 $774,900
7220 325607 $250,000
7221 1048644 $962,800
7222 720587 $745,000
7223 320000 $279,475
7224 522941 $450,000
7225 617713 $665,000
7226 522941 $375,000
7227 217667 $148,000
7228 351193 $399,000
7229 600432 $600,000
7230 503324 $429,000
7231 764855 $980,000
7232 661901 $675,000
7233 165000 $235,000
7234 903860 $827,000
7235 738933 $747,500
7236 395770 $424,500
7237 360107 $430,000
7238 825000 $920,000
7239 978283 $1,030,000
7240 347703 $227,000
7241 888625 $885,000
7242 1129562 $1,050,000
7243 606899 $650,000
7244 325179 $190,000
7245 522941 $423,800
7246 460000 $460,000
7247 449430 $434,000
7248 351193 $244,000
7249 600432 $585,000
7250 496507 $393,000
7251 746829 $873,000
7252 476911 $475,000
7253 496520 $325,000
7254 522941 $500,000
7255 404280 $350,000
7256 351193 $187,300
7257 467248 $345,600
7258 496520 $374,000
7259 404280 $328,000
7260 409425 $257,500
7261 496507 $464,950
7262 908990 $925,000
7263 775398 $727,500
7264 600432 $585,000
7265 351193 $374,500
7266 635061 $661,000
7267 2000000 $2,000,000
7268 600432 $589,000
7269 265028 $199,900
7270 951673 $1,060,000
7271 316839 $200,000
7272 577663 $580,000
7273 496520 $435,000
7274 695123 $690,000
7275 492223 $403,000
7276 351193 $250,000
7277 536113 $550,000
7278 659616 $675,000
7279 978283 $981,000
7280 808699 $1,000,000
7281 978283 $959,000
7282 351193 $372,000
7283 398709 $390,000
7284 271031 $302,000
7285 522941 $550,000
7286 1604965 $1,520,000
7287 758947 $781,500
7288 337000 $300,000
7289 272719 $316,000
7290 404280 $447,000
7291 606899 $675,000
7292 351193 $190,000
7293 606899 $650,000
7294 323264 $174,900
7295 563560 $575,000
7296 351193 $270,000
7297 606899 $624,000
7298 350938 $221,347
7299 760000 $746,000
7300 1001260 $2,160,000
7301 769417 $820,000
7302 856707 $824,000
7303 625123 $625,000
7304 351193 $399,888
7305 731200 $770,126
7306 724117 $710,000
7307 437684 $465,000
7308 265028 $151,000
7309 760111 $820,000
7310 720587 $708,000
7311 519349 $390,000
7312 405628 $383,000
7313 600432 $454,000
7314 457682 $371,000
7315 774367 $780,000
7316 387403 $299,000
7317 647621 $680,000
7318 400000 $224,000
7319 496507 $509,000
7320 343500 $440,000
7321 367417 $399,700
7322 522941 $539,000
7323 898395 $936,000
7324 452660 $445,000
7325 746829 $846,000
7326 724117 $725,000
7327 600432 $589,900
7328 351193 $401,000
7329 404280 $260,000
7330 503324 $470,000
7331 617713 $620,000
7332 317397 $229,000
7333 302247 $152,275
7334 353700 $356,000
7335 457232 $349,000
7336 600432 $549,000
7337 522941 $523,000
7338 600432 $500,000
7339 720587 $710,000
7340 398709 $375,000
7341 496520 $324,950
7342 470676 $490,000
7343 647621 $630,000
7344 600432 $595,000
7345 868500 $872,500
7346 503324 $490,000
7347 1900000 $1,900,000
7348 302247 $310,000
7349 341000 $300,000
7350 522941 $545,000
7351 317397 $342,000
7352 496507 $439,000
7353 628565 $774,888
7354 1058458 $1,500,000
7355 724117 $1,230,000
7356 883041 $1,390,000
7357 344180 $370,000
7358 414429 $431,200
7359 351193 $351,000
7360 951673 $850,000
7361 885000 $885,000
7362 301553 $185,000
7363 411000 $440,000
7364 1675000 $2,400,000
7365 450000 $410,000
7366 351193 $350,000
7367 351193 $344,000
7368 398709 $229,500
7369 600432 $445,000
7370 600432 $518,000
7371 600432 $565,000
7372 594020 $445,000
7373 883041 $968,000
7374 496520 $487,585
7375 812944 $819,000
7376 314792 $267,000
7377 503324 $525,000
7378 600432 $578,000
7379 503324 $499,000
7380 807228 $1,010,000
7381 1050313 $991,500
7382 1510000 $1,980,000
7383 456842 $484,998
7384 1354750 $1,280,000
7385 724117 $875,000
7386 503324 $529,950
7387 436512 $415,000
7388 351193 $385,000
7389 274939 $252,500
7390 398709 $385,000
7391 503324 $419,000
7392 316839 $175,000
7393 433000 $419,950
7394 496520 $460,000
7395 496520 $481,000
7396 724117 $719,521
7397 450000 $334,000
7398 522941 $556,000
7399 724117 $900,000
7400 1199658 $1,360,000
7401 625123 $640,000
7402 617713 $619,790
7403 522941 $541,338
7404 724117 $794,154
7405 724117 $820,000
7406 731200 $739,000
7407 351193 $275,500
7408 522941 $515,000
7409 647621 $1,410,000
7410 340109 $282,000
7411 522941 $506,950
7412 720587 $812,000
7413 883041 $850,000
7414 398723 $377,500
7415 720587 $825,500
7416 883041 $880,000
7417 760111 $855,169
7418 404280 $380,000
7419 447043 $377,000
7420 913888 $921,800
7421 522941 $529,500
7422 432674 $425,000
7423 883041 $1,040,000
7424 389840 $299,000
7425 1215958 $1,260,000
7426 568658 $429,000
7427 375000 $267,800
7428 369900 $369,950
7429 765034 $839,704
7430 449430 $275,000
7431 548362 $425,000
7432 384073 $299,900
7433 720587 $720,000
7434 370000 $460,000
7435 451349 $375,000
7436 398709 $386,180
7437 720587 $785,000
7438 600432 $575,000
7439 1256000 $1,850,000
7440 503324 $390,000
7441 998056 $2,210,000
7442 951673 $1,050,000
7443 847272 $915,000
7444 377186 $290,750
7445 720587 $715,000
7446 522941 $532,000
7447 807228 $885,000
7448 1132660 $1,450,000
7449 625123 $645,000
7450 445000 $505,000
7451 503324 $495,000
7452 600432 $549,995
7453 660000 $690,000
7454 688961 $673,000
7455 731200 $780,000
7456 951673 $950,968
7457 398709 $334,950
7458 383212 $282,000
7459 450000 $450,000
7460 256278 $299,000
7461 600432 $585,000
7462 256278 $301,500
7463 724117 $949,950
7464 724117 $759,990
7465 625123 $629,800
7466 724117 $745,000
7467 335692 $335,000
7468 883041 $809,000
7469 600432 $569,950
7470 724117 $723,000
7471 600432 $569,900
7472 496507 $385,000
7473 432674 $420,000
7474 356000 $304,500
7475 566231 $489,500
7476 758436 $815,000
7477 720587 $719,000
7478 566231 $465,000
7479 522941 $540,000
7480 720587 $701,000
7481 1810000 $2,640,000
7482 654231 $672,500
7483 550000 $538,000
7484 452660 $362,500
7485 358545 $230,000
7486 545000 $550,000
7487 1044458 $1,050,000
7488 640000 $655,000
7489 438166 $385,000
7490 720587 $729,999
7491 360107 $369,000
7492 522941 $509,900
7493 600432 $385,000
7494 530000 $536,000
7495 398709 $395,000
7496 600432 $545,000
7497 720587 $715,000
7498 405628 $348,000
7499 496520 $455,000
7500 600432 $575,000
7501 452660 $364,000
7502 942877 $932,990
7503 720587 $710,000
7504 367417 $299,950
7505 789346 $962,000
7506 398709 $395,825
7507 774367 $920,000
7508 382600 $366,000
7509 583143 $480,000
7510 421000 $388,000
7511 1897500 $2,320,000
7512 720587 $730,000
7513 883041 $950,000
7514 507687 $358,990
7515 335000 $398,651
7516 600432 $530,000
7517 606899 $610,360

7518 724117 $760,000
7519 1269576 $1,260,000
7520 452660 $379,900
7521 600432 $472,000
7522 583206 $465,000
7523 606899 $659,950
7524 457232 $484,950
7525 350000 $359,000
7526 583143 $519,000
7527 600432 $535,000
7528 606899 $622,950
7529 522941 $515,000
7530 556816 $540,000
7531 978283 $1,080,000
7532 2700000 $2,700,000
7533 1100000 $1,100,000
7534 265000 $293,467
7535 522941 $550,000
7536 538278 $435,000
7537 625000 $625,000
7538 660892 $665,000
7539 600432 $589,500
7540 416000 $437,000
7541 351193 $320,000
7542 522941 $430,000
7543 883041 $995,500
7544 556816 $334,990
7545 765000 $909,500
7546 844258 $952,990
7547 694045 $700,000
7548 933394 $907,687
7549 522941 $395,000
7550 600432 $559,950
7551 1172150 $1,330,000
7552 720587 $695,000
7553 522941 $545,000
7554 571079 $389,950
7555 381910 $288,790
7556 606899 $615,000
7557 611194 $615,000
7558 503324 $500,000
7559 752590 $802,945
7560 479461 $430,000
7561 583143 $515,000
7562 769417 $1,260,000
7563 475000 $400,000
7564 363025 $390,000
7565 522941 $450,000
7566 758436 $825,000
7567 499000 $435,000
7568 485377 $398,000
7569 438530 $315,000
7570 496507 $455,000
7571 457682 $380,000
7572 377186 $340,000
7573 351193 $360,000
7574 746923 $820,000
7575 360000 $360,000
7576 522941 $515,000
7577 600432 $375,000
7578 398709 $325,000
7579 736528 $740,000
7580 507031 $455,000
7581 404280 $292,500
7582 625123 $650,000
7583 600432 $530,000
7584 445000 $395,000
7585 488822 $443,000
7586 566231 $570,000
7587 990390 $1,560,000
7588 746923 $840,000
7589 600432 $572,800
7590 1912172 $1,700,000
7591 472500 $445,000
7592 790658 $801,000
7593 720587 $711,000
7594 354460 $268,500
7595 503324 $500,000
7596 600432 $600,000
7597 1330000 $1,270,000
7598 720587 $689,500
7599 381910 $175,003
7600 429387 $479,000
7601 1165000 $1,040,000
7602 720587 $685,000
7603 460762 $439,108
7604 451300 $279,000
7605 398709 $377,000
7606 1326667 $1,400,000
7607 352500 $341,000
7608 358000 $358,000
7609 606899 $633,634
7610 883041 $887,250
7611 438530 $459,000
7612 951673 $918,000
7613 600432 $555,000
7614 481275 $450,000
7615 625123 $648,000
7616 600432 $580,000
7617 385925 $384,000
7618 460762 $455,000
7619 515000 $415,000
7620 736528 $799,950
7621 533000 $545,000
7622 522941 $498,000
7623 864303 $895,000
7624 400000 $417,000
7625 546985 $555,000
7626 546985 $555,000
7627 398709 $325,000
7628 720587 $700,000
7629 460762 $379,000
7630 600432 $571,000
7631 724117 $769,900
7632 606899 $633,000
7633 1330000 $1,240,000
7634 872889 $1,030,000
7635 757191 $754,842
7636 1330000 $1,040,000
7637 583143 $544,999
7638 551305 $449,950
7639 736528 $809,950
7640 951673 $1,060,000
7641 935662 $971,971
7642 370000 $389,000
7643 600432 $551,500
7644 1373232 $1,750,000
7645 356385 $335,000
7646 438166 $368,000
7647 844258 $859,000
7648 482242 $399,950
7649 522941 $547,500
7650 421805 $375,000
7651 398709 $407,000
7652 499580 $399,000
7653 442200 $439,990
7654 953604 $923,990
7655 625123 $639,888
7656 522941 $252,000
7657 902431 $925,000
7658 631063 $629,000
7659 452115 $309,000
7660 522941 $554,950
7661 600432 $550,000
7662 951673 $1,010,000
7663 1230818 $1,580,000
7664 380000 $328,423
7665 367417 $385,000
7666 398709 $459,000
7667 1525000 $1,480,000
7668 398709 $395,000
7669 539634 $535,000
7670 951673 $970,000
7671 256278 $205,000
7672 451349 $384,500
7673 1113875 $1,050,000
7674 1750000 $1,750,000
7675 600432 $569,995
7676 522941 $525,000
7677 583206 $516,000
7678 1261250 $1,350,000
7679 522500 $440,000
7680 612027 $610,000
7681 612027 $645,000
7682 522941 $536,751
7683 503324 $535,000
7684 332382 $300,500
7685 695000 $675,000
7686 445000 $415,000
7687 611194 $640,000
7688 600432 $592,000
7689 595041 $475,000
7690 382707 $380,000
7691 720587 $718,000
7692 600432 $515,805
7693 978283 $1,030,000
7694 452660 $437,718
7695 475000 $450,000
7696 522941 $515,000
7697 625123 $650,880
7698 942877 $895,900
7699 586011 $585,000
7700 444212 $380,000
7701 600432 $565,997
7702 522941 $459,000
7703 492000 $461,500
7704 2150000 $2,150,000
7705 724117 $790,000
7706 583143 $588,000
7707 720587 $724,500
7708 731200 $749,000
7709 720587 $720,000
7710 731200 $790,000
7711 625123 $649,000
7712 522941 $453,000
7713 414454 $329,780
7714 752590 $771,005
7715 267500 $278,000
7716 409425 $270,000
7717 736528 $778,983
7718 367417 $221,000
7719 452660 $338,800
7720 600432 $550,000
7721 575000 $575,000
7722 606899 $649,000
7723 600432 $545,000
7724 611194 $625,000
7725 611000 $611,000
7726 625123 $650,000
7727 883041 $1,210,000
7728 355000 $252,500
7729 340109 $308,000
7730 792390 $803,100
7731 535690 $415,000
7732 542519 $456,500
7733 883041 $919,990
7734 292314 $302,860
7735 3200000 $3,200,000
7736 444212 $333,000
7737 340109 $419,950
7738 760111 $775,950
7739 606899 $605,000
7740 496520 $520,000
7741 611194 $665,000
7742 951673 $870,515
7743 367417 $305,000
7744 720587 $716,500
7745 1269576 $1,240,000
7746 1560556 $3,000,000
7747 482242 $309,620
7748 479461 $425,000
7749 522941 $550,000
7750 1334992 $1,360,000
7751 828443 $830,000
7752 763333 $855,000
7753 1285700 $1,390,000
7754 335000 $235,000
7755 606899 $659,950
7756 759067 $785,000
7757 398709 $475,000
7758 606899 $657,044
7759 359950 $359,950
7760 600432 $420,000
7761 600432 $570,000
7762 385925 $439,000
7763 426794 $399,950
7764 837321 $805,000
7765 724117 $745,000
7766 522941 $494,815
7767 600432 $591,975
7768 600432 $600,000
7769 697001 $673,000
7770 507950 $500,000
7771 724117 $890,000
7772 382707 $419,700
7773 358545 $394,000
7774 352636 $343,000
7775 724117 $838,000
7776 398709 $395,000
7777 600432 $480,000
7778 550000 $539,000
7779 325460 $306,500
7780 452660 $408,474
7781 522941 $437,000
7782 377186 $160,797
7783 729000 $729,000
7784 499000 $499,000
7785 432674 $461,000
7786 256278 $271,115
7787 720587 $709,950
7788 600432 $599,000
7789 522941 $471,500
7790 1215958 $1,020,000
7791 951673 $998,000
7792 901000 $844,000
7793 757191 $745,641
7794 398709 $352,500
7795 951673 $1,140,000
7796 664758 $675,000
7797 513000 $530,000
7798 377186 $335,000
7799 3000000 $3,000,000
7800 421805 $379,000
7801 503324 $500,012
7802 405000 $405,000
7803 366907 $294,000
7804 810000 $798,800
7805 724117 $820,000
7806 785000 $950,000
7807 957500 $1,270,000
7808 3350000 $3,350,000
7809 522941 $489,950
7810 336602 $345,000
7811 625123 $650,000
7812 951673 $900,000
7813 398723 $391,000
7814 1800000 $1,800,000
7815 675636 $661,000
7816 432674 $415,000
7817 274939 $290,000
7818 421805 $349,900
7819 445588 $465,000
7820 946250 $950,000
7821 502925 $496,800
7822 978283 $920,000
7823 1269576 $1,290,000
7824 583143 $576,000
7825 398709 $399,000
7826 736528 $847,093
7827 1215958 $1,700,000
7828 978283 $1,030,000
7829 600432 $515,000
7830 396000 $355,000
7831 398709 $394,950
7832 387000 $382,000
7833 522941 $530,000
7834 720587 $719,950
7835 951673 $1,500,000
7836 736528 $799,950
7837 600432 $572,000
7838 438530 $459,000
7839 522941 $529,500
7840 1373232 $1,900,000
7841 789346 $799,000
7842 522941 $547,000
7843 1044458 $960,000
7844 1604965 $2,950,000
7845 438530 $312,500
7846 869322 $850,000
7847 399888 $455,000
7848 429900 $362,500
7849 600432 $540,000
7850 354460 $230,000
7851 373421 $258,800
7852 379900 $295,000
7853 736528 $908,990
7854 445575 $475,000
7855 1495000 $1,240,000
7856 606899 $635,000
7857 437867 $350,000
7858 1269576 $1,300,000
7859 583143 $579,000
7860 555000 $552,500
7861 568202 $467,000
7862 496507 $479,950
7863 1180000 $1,180,000
7864 358545 $289,000
7865 389840 $265,000
7866 742623 $749,000
7867 583206 $492,000
7868 600432 $552,500
7869 383212 $333,000
7870 435000 $415,000
7871 600432 $445,000
7872 736528 $969,990
7873 596190 $392,000
7874 763333 $795,000
7875 598640 $469,995
7876 600432 $555,000
7877 432674 $445,000
7878 344180 $256,950
7879 883041 $805,000
7880 803996 $799,990
7881 674950 $680,000
7882 355000 $395,000
7883 329504 $163,800
7884 305000 $220,000
7885 736528 $779,380
7886 1336000 $1,510,000
7887 620665 $635,000
7888 1215958 $1,060,000
7889 411975 $389,500
7890 568202 $359,800
7891 445588 $320,000
7892 596190 $380,000
7893 583143 $580,000
7894 503324 $545,000
7895 522941 $451,300
7896 579950 $560,000
7897 606899 $640,000
7898 543599 $539,950
7899 594020 $300,000
7900 404280 $405,000
7901 452660 $379,900
7902 625123 $625,000
7903 398723 $315,000
7904 942877 $939,000
7905 680247 $674,000
7906 2320000 $2,320,000
7907 951673 $914,154
7908 409425 $310,000
7909 1064375 $1,050,000
7910 654231 $680,000
7911 757191 $828,950
7912 398709 $293,000
7913 835000 $795,000
7914 625123 $630,000
7915 654231 $654,000
7916 600432 $575,000
7917 570000 $554,000
7918 462370 $360,000
7919 347703 $305,000
7920 600432 $380,000
7921 566231 $440,000
7922 522941 $530,000
7923 600432 $600,000
7924 522941 $445,000
7925 367417 $285,000
7926 600432 $440,000
7927 404280 $287,450
7928 600432 $507,950
7929 730000 $750,000
7930 429000 $420,000
7931 411975 $394,950
7932 612027 $635,000
7933 398709 $352,499
7934 486048 $330,675
7935 381910 $275,000
7936 522941 $497,000
7937 382600 $355,000
7938 398709 $345,000
7939 522941 $478,000
7940 399000 $395,000
7941 385977 $370,000
7942 724117 $775,000
7943 724117 $790,000
7944 335692 $249,000
7945 769417 $765,000
7946 720587 $739,000
7947 883041 $890,000
7948 610000 $641,000
7949 650000 $660,000
7950 745446 $800,000
7951 551043 $555,000
7952 766050 $760,000
7953 566231 $430,000
7954 600432 $399,963
7955 398709 $411,000
7956 496507 $469,950
7957 736528 $749,950
7958 460762 $450,000
7959 611194 $643,950
7960 520000 $536,000
7961 405628 $182,568
7962 757191 $799,900
7963 660892 $674,950
7964 883041 $1,110,000
7965 935662 $1,250,000
7966 381910 $208,800
7967 807228 $837,000
7968 757191 $780,000
7969 1215958 $1,600,000
7970 522941 $530,000
7971 1495000 $1,750,000
7972 457232 $489,950
7973 414454 $357,500
7974 453877 $414,000
7975 522941 $533,500
7976 724117 $725,000
7977 373421 $239,800
7978 606899 $616,950
7979 1510000 $1,260,000
7980 426794 $435,000
7981 600432 $475,000
7982 404280 $427,000
7983 525000 $499,000
7984 457682 $336,900
7985 951673 $999,950
7986 479000 $479,000
7987 769417 $798,500
7988 694045 $689,000
7989 606899 $639,983
7990 625123 $627,000
7991 452660 $352,800
7992 625123 $644,000
7993 611194 $640,000
7994 449950 $425,000
7995 600432 $562,500
7996 787133 $850,000
7997 1358617 $1,940,000
7998 452115 $312,000
7999 522941 $410,000
8000 720587 $725,000
8001 510274 $335,000
8002 515000 $519,990
8003 356385 $325,000
8004 526000 $526,000
8005 410000 $299,999
8006 495000 $525,000
8007 1604965 $1,830,000
8008 1048644 $1,180,000
8009 1150000 $1,150,000
8010 438822 $400,000
8011 600432 $561,000
8012 522941 $490,000
8013 409425 $330,000
8014 844258 $880,000
8015 460762 $465,000
8016 421805 $375,000
8017 475515 $294,500
8018 731200 $730,000
8019 606899 $605,000
8020 746923 $720,000
8021 535000 $549,900
8022 465000 $492,000
8023 398709 $419,190
8024 398723 $295,500
8025 724117 $860,000
8026 842593 $812,000
8027 448700 $324,500
8028 425000 $305,450
8029 398723 $399,900
8030 600432 $580,000
8031 746923 $910,000
8032 522941 $414,000
8033 522941 $525,000
8034 432674 $450,000
8035 1270000 $1,270,000
8036 522941 $485,000
8037 736528 $782,900
8038 452660 $409,316
8039 382600 $415,000
8040 522941 $521,500
8041 600432 $580,000
8042 933394 $882,566
8043 522941 $525,000
8044 600432 $589,410
8045 724117 $757,500
8046 356385 $338,500
8047 398723 $379,500
8048 445588 $450,000
8049 757191 $740,000
8050 746923 $727,000
8051 532858 $535,000
8052 367417 $255,000
8053 789346 $810,000
8054 479461 $500,000
8055 742623 $810,000
8056 606899 $605,000
8057 600432 $459,000
8058 351193 $375,000
8059 398709 $375,000
8060 372000 $346,000
8061 381910 $302,059
8062 595041 $575,000
8063 900000 $900,000
8064 436512 $397,500
8065 951673 $1,080,000
8066 742623 $775,900
8067 951673 $989,990
8068 436512 $300,000
8069 606899 $664,950
8070 720587 $699,188
8071 692798 $670,000
8072 508000 $487,000
8073 606899 $613,500
8074 383212 $255,000
8075 606899 $637,850
8076 625123 $636,230
8077 568658 $544,000
8078 331500 $425,000
8079 351193 $294,570
8080 437850 $300,000
8081 665923 $680,000
8082 438822 $424,950
8083 720587 $720,000
8084 600432 $530,000
8085 522941 $556,000
8086 720587 $712,198
8087 332382 $277,140
8088 600432 $585,000
8089 522941 $520,000
8090 398709 $315,000
8091 454000 $424,950
8092 522941 $542,300
8093 438530 $320,000
8094 1014084 $1,140,000
8095 479461 $425,000
8096 736528 $834,538
8097 883041 $820,875
8098 600432 $595,500
8099 697001 $695,000
8100 600432 $515,000
8101 275000 $279,800
8102 566231 $525,000
8103 606899 $613,000
8104 432000 $449,500
8105 519852 $515,000
8106 356385 $346,100
8107 674145 $695,000
8108 1181667 $1,090,000
8109 589000 $525,000
8110 2106000 $1,800,000
8111 298580 $265,050
8112 432674 $450,000
8113 999950 $915,000
8114 398709 $294,000
8115 1269576 $1,070,000
8116 522941 $494,900
8117 440567 $415,000
8118 933394 $882,990
8119 606899 $620,000
8120 625123 $654,000
8121 1235000 $1,840,000
8122 935662 $855,000
8123 724117 $775,000
8124 746923 $687,015
8125 694045 $663,000
8126 978283 $1,050,000
8127 438822 $433,190
8128 724117 $725,000
8129 398709 $272,167
8130 600432 $303,500
8131 355000 $308,000
8132 606899 $646,800
8133 527900 $530,200
8134 651000 $675,900
8135 600432 $570,000
8136 507687 $445,000
8137 522941 $477,000
8138 522941 $450,000
8139 1056845 $2,230,000
8140 583143 $450,800
8141 769417 $1,060,000
8142 600432 $590,000
8143 746923 $760,000
8144 951673 $1,030,000
8145 551613 $385,000
8146 600432 $500,000
8147 522941 $552,100
8148 769417 $785,000
8149 612027 $615,000
8150 449400 $391,000
8151 429387 $372,000
8152 544900 $561,000
8153 615000 $635,000
8154 318391 $235,000
8155 606899 $623,300

8156 496507 $412,500
8157 522941 $497,000
8158 736528 $775,000
8159 411975 $288,790
8160 720587 $800,000
8161 577112 $452,000
8162 606899 $630,000
8163 793829 $1,080,000
8164 522941 $429,900
8165 503324 $505,000
8166 724117 $729,950
8167 594020 $424,950
8168 1240000 $1,240,000
8169 600432 $495,000
8170 837321 $870,000
8171 539634 $567,500
8172 598640 $459,995
8173 332000 $365,000
8174 421805 $389,950
8175 315000 $320,000
8176 752604 $775,000
8177 720587 $950,000
8178 310000 $229,800
8179 625123 $645,000
8180 493137 $448,000
8181 746923 $988,990
8182 606899 $625,000
8183 731200 $773,000
8184 481000 $392,000
8185 600432 $549,995
8186 522941 $480,000
8187 385925 $355,000
8188 398709 $208,400
8189 522941 $445,000
8190 600432 $492,500
8191 583143 $435,000
8192 606899 $612,995
8193 545000 $540,000
8194 398709 $331,000
8195 625123 $669,000
8196 1604965 $2,350,000
8197 470000 $490,000
8198 606899 $627,000
8199 438822 $440,000
8200 770000 $935,000
8201 606899 $641,000
8202 522941 $452,000
8203 612027 $625,000
8204 883041 $834,950
8205 674145 $659,000
8206 351193 $353,000
8207 498000 $535,000
8208 2000000 $2,000,000
8209 383212 $329,950
8210 425000 $417,000
8211 600432 $563,950
8212 460762 $332,220
8213 675000 $680,000
8214 765034 $825,750
8215 457682 $338,000
8216 606899 $608,000
8217 665923 $667,000
8218 861600 $928,990
8219 600432 $519,995
8220 405628 $405,000
8221 600432 $410,000
8222 381910 $370,000
8223 522941 $553,000
8224 1356667 $2,070,000
8225 600432 $455,950
8226 600432 $490,000
8227 720587 $705,000
8228 1170000 $1,170,000
8229 479461 $409,000
8230 452660 $391,000
8231 600432 $542,525
8232 1386667 $1,770,000
8233 606899 $608,000
8234 464000 $392,000
8235 398723 $274,800
8236 429387 $325,000
8237 577112 $418,500
8238 414454 $350,000
8239 724117 $782,000
8240 746923 $779,000
8241 674145 $685,000
8242 448700 $350,000
8243 724117 $775,000
8244 398709 $438,000
8245 724117 $830,000
8246 510274 $353,000
8247 514000 $460,000
8248 600432 $569,888
8249 675000 $695,000
8250 236000 $288,790
8251 731200 $750,000
8252 736528 $729,999
8253 344180 $386,950
8254 549995 $535,000
8255 883041 $890,000
8256 951673 $1,110,000
8257 452660 $365,000
8258 951673 $899,000
8259 480000 $465,750
8260 600432 $494,995
8261 522941 $530,000
8262 496507 $435,000
8263 625123 $639,000
8264 757191 $914,500
8265 318391 $250,000
8266 389840 $358,000
8267 375000 $425,000
8268 486048 $326,000
8269 724117 $749,950
8270 438530 $315,000
8271 398709 $375,000
8272 606899 $669,950
8273 497000 $518,000
8274 2695000 $1,990,000
8275 606899 $649,500
8276 566000 $525,000
8277 400291 $402,000
8278 933394 $1,750,000
8279 568202 $359,800
8280 444212 $330,000
8281 978283 $1,010,000
8282 600432 $599,832
8283 522941 $495,000
8284 775000 $819,995
8285 724117 $850,000
8286 1460000 $1,460,000
8287 600432 $579,000
8288 883041 $890,776
8289 522941 $484,000
8290 500000 $534,950
8291 758436 $776,000
8292 883041 $850,000
8293 522941 $443,000
8294 1285700 $1,150,000
8295 455950 $453,000
8296 724117 $735,000
8297 2240000 $2,240,000
8298 411975 $377,500
8299 600432 $600,000
8300 436512 $420,000
8301 398709 $406,000
8302 583143 $505,000
8303 861600 $942,990
8304 438166 $390,000
8305 344180 $420,000
8306 388000 $462,500
8307 585000 $579,950
8308 600432 $585,000
8309 692798 $670,000
8310 3050000 $3,000,000
8311 369409 $346,000
8312 1269576 $1,330,000
8313 720587 $999,999
8314 354094 $336,750
8315 1560556 $1,880,000
8316 720587 $715,000
8317 600432 $589,999
8318 538119 $405,000
8319 522941 $509,900
8320 398709 $327,000
8321 383212 $249,000
8322 522941 $549,000
8323 522941 $530,000
8324 736528 $747,450
8325 300000 $305,000
8326 600432 $540,000
8327 720587 $750,000
8328 600432 $579,950
8329 1086042 $1,700,000
8330 382707 $330,000
8331 606899 $608,500
8332 354460 $230,000
8333 787133 $785,000
8334 606899 $645,000
8335 600432 $594,866
8336 606899 $625,000
8337 383212 $380,000
8338 600432 $572,000
8339 1132660 $1,090,000
8340 720587 $679,950
8341 1181667 $1,580,000
8342 1584300 $1,540,000
8343 522941 $507,250
8344 610000 $610,685
8345 951673 $1,010,000
8346 522941 $475,000
8347 600432 $400,000
8348 451349 $400,000

In [59]:
subtraction_accurracy = []
for i in range(8349):
    subtraction_accurracy.append(closest[i]-price[i])

In [60]:
division_accurracy = []
for i in range(8349):
    division_accurracy.append(subtraction_accurracy[i]/price[i])

In [61]:
percentage_accurracy = []
for i in range(8349):
    percentage_accurracy.append(division_accurracy[i]*100)

In [62]:
abs_value = [] 
for i in range(8349):
    abs_value.append(abs(percentage_accurracy[i]))
abs_value

[58.266336187471836,
 0.5907284768211921,
 53.02527233115468,
 6.630923076923077,
 25.697974683544306,
 58.42165,
 22.118676627534686,
 0.22072322670375522,
 3.43359173126615,
 3.875454545454545,
 0.31388429752066116,
 5.195182481751825,
 7.160040983606557,
 45.89101449275363,
 16.959302325581397,
 5.576470588235294,
 23.402153846153848,
 33.605939849624065,
 17.911384615384616,
 13.018978978978978,
 2.424375,
 1.072394366197183,
 29.427528089887637,
 23.341808510638298,
 13.436225596529283,
 85.4460465116279,
 0.47820895522388057,
 3.7765454545454546,
 3.381988950276243,
 9.463302752293579,
 5.642553191489362,
 0.44868255959849435,
 45.47537505682679,
 46.68759888036996,
 2.245977011494253,
 8.891460674157303,
 0.7837662337662338,
 46.05689655172414,
 13.106516853932584,
 22.95,
 3.7400454201362607,
 5.376020408163265,
 15.376859365554246,
 8.736992481203007,
 0.18665908660223612,
 0.6648000000000001,
 7.2769767441860465,
 33.111111111111114,
 6.630923076923077,
 48.5984375,
 97.38196078431372,
 11.603196347031963,
 7.950777777777778,
 14.132426303854876,
 18.21595238095238,
 14.001351351351351,
 10.281625573039276,
 0.43415007656967847,
 4.544427934621099,
 18.187529411764704,
 3.4254545454545453,
 12.486170212765957,
 1.940916808149406,
 11.128622754491017,
 0.0011961967777876512,
 43.87606557377049,
 21.76182728410513,
 3.1160756501182036,
 12.460430107526882,
 18.850227272727274,
 29.866190476190475,
 15.358614402917045,
 13.795595238095238,
 3.532821950140139,
 17.366352941176473,
 1.7561844863731655,
 24.433774834437084,
 17.293949820338327,
 4.4432944606413995,
 12.792564102564102,
 0.6648000000000001,
 54.69671361502348,
 1.0149473684210526,
 14.343170731707316,
 22.037142857142857,
 46.424309392265194,
 0.48440629470672386,
 25.91038961038961,
 33.906349206349205,
 0.1507936507936508,
 22.001052631578947,
 34.56896551724138,
 48.81059322033898,
 8.896374622356495,
 22.59753086419753,
 60.42294117647059,
 45.85360975609756,
 7.778158458244111,
 22.59753086419753,
 6.477629629629629,
 0.6648000000000001,
 1.9503174603174602,
 3.5227586206896553,
 3.417272727272727,
 8.42320819112628,
 17.12004479283315,
 14.05,
 2.6133834586466165,
 123.23383084577115,
 43.72428571428571,
 3.4420289855072466,
 4.821428571428572,
 7.648371752652762,
 0.5655769230769231,
 51.376293103448276,
 46.02619542619543,
 22.96627659574468,
 5.575102696910163,
 99.10775510204081,
 2.375257731958763,
 4.39312865497076,
 4.267089180624717,
 97.07818181818182,
 35.547728220091706,
 7.55625,
 14.47953216374269,
 29.268,
 10.282619047619047,
 3.2619502868068833,
 39.12763157894737,
 4.599245283018868,
 5.49656050955414,
 48.91242603550296,
 37.83035714285714,
 28.85757575757576,
 0.8058904109589041,
 33.62750642673522,
 4.0494642857142855,
 10.0,
 9.3720901126408,
 9.089740082079343,
 28.68201510087882,
 1.795072463768116,
 36.772424242424236,
 5.674973031283711,
 3.552857142857143,
 13.535890410958903,
 6.848316831683168,
 6.114721723518851,
 6.630923076923077,
 3.9709090909090907,
 28.666961651917404,
 1.2312280701754386,
 0.0,
 35.842816901408455,
 0.6451612903225806,
 3.61936,
 2.79907063197026,
 6.3224,
 52.340384615384615,
 1.8337531486146097,
 16.687753036437247,
 3.322162883845127,
 3.4714116251482796,
 0.22439446366782004,
 24.13,
 0.0,
 0.33188118811881184,
 5.9629473684210526,
 2.9051724137931036,
 5.802344089133266,
 23.83316892725031,
 4.695065458207452,
 2.4007619047619047,
 37.06050189068408,
 0.03634615384615385,
 4.224565217391304,
 11.48984126984127,
 28.072655217965654,
 0.3921904761904762,
 11.058598130841121,
 30.33469584034624,
 2.955707958279754,
 31.012421875,
 1.938495575221239,
 6.691096350473916,
 10.109182389937107,
 0.12179310344827586,
 1.16592,
 18.813942857142855,
 3.8272307692307694,
 5.96447963800905,
 0.44113821138211384,
 0.1728205128205128,
 8.293958333333332,
 2.368780487804878,
 2.388426966292135,
 14.56157894736842,
 19.998545454545454,
 15.002886597938145,
 0.0,
 0.7012084592145016,
 0.8539175257731959,
 76.12035714285715,
 1.3318867924528304,
 0.9890109890109889,
 7.401918158567774,
 32.4023850740527,
 12.38113475177305,
 20.804620689655174,
 0.12179310344827586,
 13.205128205128206,
 3.9217333333333335,
 9.418260869565218,
 35.074230769230766,
 0.08152777777777777,
 17.604298642533937,
 0.366,
 0.9891760904684975,
 15.38178082191781,
 18.407972665148066,
 1.39640625,
 36.72861111111111,
 4.6550335570469805,
 30.393524590163935,
 7.939130434782609,
 12.122388059701493,
 4.967230769230769,
 1.9975637181409294,
 0.3921904761904762,
 3.0090721649484538,
 1.833622183708839,
 9.443523316062176,
 1.1895124195032198,
 7.9980530973451325,
 12.490274197328334,
 17.065060240963856,
 32.59473214285714,
 5.478571428571429,
 1.2154900616860864,
 20.88627906976744,
 4.047522935779817,
 9.832470588235294,
 8.059384615384616,
 0.4907112970711297,
 29.52878338278932,
 12.773599999999998,
 53.96022801302932,
 1.4635026737967916,
 30.437725225225226,
 1.3744209466263848,
 8.728482972136224,
 23.69335347432024,
 0.2896084337349398,
 1.2724346076458752,
 84.94840425531916,
 5.1878787878787875,
 17.245826086956523,
 25.86222760290557,
 8.225498759564932,
 2.5268244575936882,
 2.4313131313131313,
 21.283783783783782,
 0.42842857142857144,
 26.11051020408163,
 23.660503144654086,
 64.68666666666667,
 2.372577319587629,
 1.27,
 45.843548387096774,
 1.7102201257861636,
 43.80685714285714,
 43.34408163265306,
 33.082926829268295,
 25.814143920595534,
 0.7550413223140496,
 0.5452307692307692,
 0.6170114942528736,
 31.829368421052635,
 1.9762863534675614,
 0.973262599469496,
 9.502519083969466,
 13.60009861932939,
 16.9045,
 18.133333333333333,
 24.18554157414261,
 12.121723300970874,
 2.1800878477306003,
 9.95051282051282,
 0.7113590263691684,
 11.511147540983606,
 14.308000000000002,
 7.936304347826087,
 10.89171974522293,
 0.18026819923371648,
 30.02404411764706,
 9.479574468085106,
 26.030245901639343,
 5.556476831232825,
 8.828400830737278,
 2.9108,
 6.271150442477875,
 4.84272076372315,
 43.971181556195965,
 2.2089600000000003,
 12.916666666666668,
 14.962903225806452,
 4.0717008797653955,
 30.99390909090909,
 29.342477876106194,
 3.0191198786039455,
 0.9152186588921283,
 32.57954545454545,
 0.49882812499999996,
 3.9652855543113104,
 1.4182648401826485,
 22.50391363022942,
 11.849777777777778,
 4.520470588235294,
 10.182869379014988,
 11.33814207650273,
 3.604560862219144,
 16.210813953488373,
 61.632,
 22.13795698924731,
 30.469212598425198,
 2.941,
 7.1987499999999995,
 1.2670588235294118,
 104.20765550239236,
 9.893775510204081,
 5.157237569060773,
 9.847481843076556,
 59.1955,
 4.663218390804598,
 0.6188617886178862,
 26.23828125,
 20.436666666666667,
 22.785875,
 9.343015521064302,
 3.8526190476190476,
 22.47233333333333,
 0.6891743119266055,
 20.515714285714285,
 7.201904761904762,
 0.13631578947368422,
 41.2094696969697,
 2.645631067961165,
 8.339540229885058,
 4.970740305522915,
 6.444727272727273,
 21.894708994708996,
 0.0,
 45.89432835820896,
 12.076590909090909,
 1.7951173708920187,
 0.2496900333810205,
 3.882352941176471,
 17.79190074906367,
 7.161142061281336,
 5.069285714285714,
 1.6611528822055137,
 6.104546860501083,
 37.97983193277311,
 0.08660194174757281,
 3.159074074074074,
 4.530526315789474,
 4.965734265734266,
 106.36680258239892,
 1.9448076923076922,
 15.5096,
 9.645779685264664,
 1.773994848247284,
 6.118041298804121,
 3.7328124999999996,
 2.3214285714285716,
 27.423797468354433,
 6.08339222614841,
 0.5481818181818181,
 0.4969939879759519,
 0.008932038834951457,
 14.405365853658536,
 14.809764705882353,
 3.530401234567901,
 6.474934036939314,
 11.537339055793991,
 16.032235294117648,
 7.443037974683545,
 12.190773846730842,
 32.952799999999996,
 0.33188118811881184,
 6.976408076514347,
 41.03225806451613,
 35.5921906693712,
 62.362580645161295,
 1.543874404261284,
 6.565548387096774,
 25.12569696969697,
 2.671224489795918,
 28.96285714285714,
 5.412558195057897,
 4.938356164383562,
 4.42295652173913,
 11.924418604651162,
 75.51523178807948,
 0.6369426751592357,
 3.819492868462757,
 39.897894736842105,
 1.8265443425076453,
 0.48388948101992296,
 75.5965,
 1.8756060606060605,
 2.7405448717948717,
 7.712760180995475,
 38.07364016736401,
 7.107692307692308,
 20.7,
 64.41059602649007,
 106.43411764705884,
 70.4523076923077,
 69.39779411764707,
 24.867750677506777,
 30.555018587360593,
 0.814375,
 4.812654545454546,
 41.14257425742574,
 0.022156862745098038,
 14.364235294117647,
 42.295459183673465,
 3.0882689556509297,
 8.339620253164556,
 55.15746031746032,
 17.215402298850574,
 5.676062176165804,
 3.4321739130434783,
 0.31388429752066116,
 6.603621169916435,
 28.600117647058827,
 5.316991150442478,
 2.637948717948718,
 12.33450363196126,
 2.254018691588785,
 5.471027027027027,
 8.762628571428571,
 19.720953436807097,
 49.443829787234044,
 17.41111111111111,
 7.343664122137404,
 27.96694677871148,
 1.9503174603174602,
 4.108079526226734,
 71.90684410646388,
 0.09254901960784313,
 2.947047619047619,
 0.5190476190476191,
 7.090212765957447,
 4.949124613800206,
 30.984042553191486,
 1.4806802721088435,
 5.968676470588235,
 33.719197707736384,
 39.81222222222222,
 7.906069802731411,
 4.230542635658915,
 43.80685714285714,
 6.3224,
 3.6793589743589745,
 26.830263633080538,
 1.6816161616161618,
 1.4371666666666667,
 0.344991789819376,
 1.3318867924528304,
 1.166612377850163,
 3.992561983471074,
 15.408380520951305,
 31.11413043478261,
 24.98213399503722,
 14.50067415730337,
 1.4176811594202898,
 57.89057522123894,
 1.072394366197183,
 15.146428571428572,
 9.47881081081081,
 2.430057803468208,
 27.706545454545456,
 3.0401898734177215,
 3.8626415094339626,
 0.0,
 7.219212962962963,
 1.2663736263736265,
 1.16592,
 8.165250475586557,
 24.608819875776398,
 0.30707070707070705,
 2.1324848484848484,
 8.19038008745375,
 8.016562500000001,
 1.4806802721088435,
 12.932222222222222,
 0.6147181008902077,
 1.795072463768116,
 2.780248833592535,
 11.58441717791411,
 23.068181818181817,
 2.941,
 22.676261705872836,
 6.417113095238096,
 6.702095808383233,
 33.731923076923074,
 17.63277551836789,
 72.98044444444444,
 0.6326732673267327,
 84.3048,
 0.22072322670375522,
 7.367692307692307,
 0.0,
 5.85350553505535,
 12.425714285714285,
 3.4605853735567607,
 27.737333333333336,
 3.9217333333333335,
 57.54163265306123,
 11.574606741573033,
 1.3318867924528304,
 28.473058823529414,
 0.777120822622108,
 17.651785714285715,
 8.12659574468085,
 5.013885851738465,
 8.112830188679245,
 5.735511982570806,
 2.405696846388606,
 6.08339222614841,
 0.0,
 33.46165423734562,
 18.49738219895288,
 0.31735099337748346,
 4.810171730515191,
 5.80562091503268,
 14.39181818181818,
 28.345864661654137,
 2.176130895091434,
 1.407,
 2.794151212553495,
 0.0,
 34.6408,
 1.1293774319066148,
 0.8573308270676692,
 20.14066193853428,
 5.069285714285714,
 5.612213114754098,
 0.5718055555555556,
 0.8334967320261437,
 28.600117647058827,
 14.976244343891404,
 29.36315789473684,
 0.1957377049180328,
 0.6648000000000001,
 24.27753086419753,
 6.565548387096774,
 14.999058823529413,
 10.60283950617284,
 12.016239316239316,
 11.656989509636496,
 22.93187165775401,
 5.858666666666667,
 15.630434782608695,
 28.74809523809524,
 28.408571428571427,
 1.6816161616161618,
 0.06441351888667991,
 24.37420365535248,
 1.371137026239067,
 5.80896,
 14.1175,
 0.9947065592635214,
 0.018286354425791997,
 12.599034399517201,
 3.854718176060798,
 9.58757841907152,
 0.14668024817112696,
 2.9984761904761905,
 0.7550413223140496,
 1.071842105263158,
 0.22926136363636365,
 19.83904761904762,
 37.95559322033898,
 55.2381884057971,
 1.6013230429988974,
 1.053587786259542,
 5.858666666666667,
 5.093129770992366,
 16.37871794871795,
 12.475824175824176,
 9.485375,
 2.3895590889068874,
 13.210384615384616,
 70.08947368421052,
 7.458726591760299,
 0.6031627906976744,
 0.37270588235294116,
 7.921602288984262,
 8.078648648648649,
 16.08530612244898,
 0.5655769230769231,
 19.643373493975904,
 1.6816161616161618,
 2.4120454545454546,
 4.229382716049383,
 8.627111111111113,
 5.338947368421053,
 5.67,
 65.96150320806599,
 13.020880856290578,
 24.13,
 5.455102040816326,
 49.77978883861237,
 1.5172289156626506,
 2.3181345118327576,
 34.42091727389627,
 18.27348484848485,
 55.19781818181818,
 13.106516853932584,
 38.2969918699187,
 8.868386432534463,
 24.979715302491105,
 0.47449933244325765,
 3.2920588235294117,
 6.784135472370767,
 7.880597014925374,
 6.049090909090909,
 22.785875,
 7.611944444444445,
 6.390481927710844,
 1.795072463768116,
 49.81,
 0.34085714285714286,
 0.0,
 15.679525222551929,
 24.517512953367877,
 5.100091827364555,
 26.345634920634918,
 16.119101123595506,
 36.16073781291173,
 2.2164179104477615,
 5.038726114649681,
 16.119101123595506,
 1.718503937007874,
 4.50378857882092,
 0.6698216735253772,
 0.0,
 9.105048076923076,
 15.333958333333333,
 0.5388586956521739,
 12.01923076923077,
 1.5785321100917433,
 3.8871764705882357,
 0.08034002833569465,
 4.2566854990583805,
 4.453396226415094,
 0.5199840623043364,
 60.35484949832776,
 38.40075,
 7.6628877005347595,
 67.23476190476191,
 1.7434881087202716,
 8.57746947835738,
 0.19963800904977377,
 6.530859375,
 5.041836734693877,
 19.008736842105264,
 7.595384615384615,
 121.88962264150945,
 1.3172357723577235,
 6.667244701348747,
 14.185701754385965,
 91.98416666666667,
 1.3205574912891986,
 8.943373493975903,
 1.940916808149406,
 9.631236897274635,
 39.19580419580419,
 22.1407611693326,
 0.016639209225700165,
 94.70862745098039,
 11.849777777777778,
 5.516739130434782,
 2.2461854083856903,
 0.6550909090909091,
 19.554379084967323,
 1.2689090909090908,
 1.9355555555555557,
 12.284088397790056,
 4.104918032786886,
 3.5227586206896553,
 0.0,
 14.93195342820181,
 67.23476190476191,
 5.692671755725191,
 1.5533333333333332,
 5.344183006535948,
 2.89616,
 4.535778443113773,
 1.1525889967637541,
 39.129275362318836,
 3.7920000000000003,
 8.465264423076924,
 27.307142857142857,
 54.622922636103155,
 42.885,
 7.814513049013367,
 3.7776363636363635,
 21.757911392405063,
 1.3186978297161935,
 3.778144329896907,
 21.930761904761905,
 4.268888888888888,
 1.768135593220339,
 33.650187521309235,
 5.181802426343155,
 0.6648000000000001,
 13.877358490566039,
 4.585010706638116,
 25.04581358609795,
 31.354497354497358,
 50.78609946075494,
 2.3281159420289854,
 40.21875,
 1.0039285714285715,
 4.919818181818182,
 15.57184368737475,
 2.5984357726601166,
 1.768135593220339,
 0.7550413223140496,
 6.348533333333334,
 6.692951775304716,
 9.324489795918367,
 12.0784,
 7.164487179487179,
 2.5161369193154033,
 6.743466666666667,
 13.288064516129033,
 20.086399999999998,
 75.23194029850745,
 9.633887733887732,
 38.61337792642141,
 67.6180412371134,
 1.6832142857142858,
 4.545199568500539,
 14.786710526315789,
 0.7741269841269841,
 67.54981818181818,
 5.753413173652695,
 5.9629473684210526,
 24.88127659574468,
 15.910315789473684,
 58.27714285714286,
 0.34085714285714286,
 3.5526732673267327,
 8.265003226500323,
 0.9979999999999999,
 78.2352,
 39.246249999999996,
 18.14712765957447,
 2.6863357919739967,
 4.275378787878788,
 0.3642201834862385,
 27.730789473684208,
 1.6275000000000002,
 9.3605364855649,
 9.418260869565218,
 18.109471303364433,
 34.80085106382978,
 6.112442996742671,
 45.41808333333333,
 6.0136170212765965,
 9.485375,
 28.18181818181818,
 18.47641666666667,
 2.506666666666667,
 29.974466019417477,
 11.755285714285714,
 0.0,
 18.35709677419355,
 2.719183673469388,
 25.817073170731707,
 3.9097067745197167,
 2.405696846388606,
 10.413333333333332,
 0.3970940170940171,
 0.1544951590594744,
 1.0828282828282827,
 6.422121212121212,
 8.864554163596168,
 16.224406047516197,
 3.9876,
 5.692671755725191,
 51.34127930075487,
 1.4806802721088435,
 0.7755555555555556,
 23.777157894736842,
 2.637948717948718,
 4.128761904761904,
 0.0,
 5.338947368421053,
 15.972173913043477,
 3.179780564263323,
 7.939130434782609,
 3.5749999999999997,
 9.138532110091743,
 43.975641025641025,
 53.57272727272727,
 43.029612903225804,
 134.12866666666667,
 21.243636363636366,
 0.31388429752066116,
 2.506666666666667,
 0.943469387755102,
 2.637948717948718,
 0.8334967320261437,
 0.4799668874172185,
 6.615581098339719,
 14.438571428571429,
 27.243840579710145,
 13.436893203883496,
 6.365279007971656,
 55.68249027237354,
 0.4418045112781955,
 7.657761194029851,
 2.770967741935484,
 0.07200000000000001,
 0.18108552631578947,
 0.0,
 3.3206349206349204,
 11.6959,
 24.620988910912306,
 2.0006060606060605,
 6.297008547008547,
 18.236940298507463,
 1.5419417475728157,
 27.463736263736266,
 0.0,
 4.615071770334929,
 3.3786363636363634,
 2.170430733410943,
 1.1295687487913364,
 37.71573461050852,
 6.279999999999999,
 13.753837209302326,
 64.40629139072847,
 25.038066465256797,
 17.642894736842106,
 27.83923076923077,
 33.81851851851852,
 43.77357142857143,
 11.027813163481953,
 1.6282222222222222,
 13.620137299771168,
 66.45555555555556,
 0.0,
 1.4824,
 2.538110749185668,
 2.8427027027027028,
 28.592481751824817,
 4.047522935779817,
 0.41027531259746525,
 0.6936,
 87.39942028985507,
 3.0283393501805054,
 2.071354838709677,
 0.6648000000000001,
 5.3640601503759395,
 34.49209090909091,
 6.793182660244534,
 9.927538247566064,
 13.61716247139588,
 24.12675,
 0.0,
 27.224422110552766,
 48.21492537313433,
 12.852914798206278,
 0.0,
 0.05507692307692308,
 7.009933774834437,
 0.7047328244274809,
 0.16061728395061728,
 0.019680000000000003,
 4.833731343283582,
 22.494942448552493,
 3.5227586206896553,
 0.0,
 3.7526270243540614,
 22.879637096774193,
 44.809937500000004,
 41.78140845070423,
 3.3834517766497463,
 13.933133304757822,
 15.467692307692307,
 15.781150442477877,
 128.6635,
 3.272398685651698,
 47.381812499999995,
 32.52566037735849,
 14.57007874015748,
 10.043688524590163,
 1.4543857278010541,
 3.095736002966259,
 23.88235294117647,
 12.53570412517781,
 9.397,
 34.227265624999994,
 59.08909090909091,
 31.367131147540984,
 48.49598308668076,
 19.453401360544216,
 25.677128712871287,
 19.017611940298508,
 0.6664814814814815,
 70.4523076923077,
 2.4675,
 62.232692307692304,
 3.0222608695652173,
 10.09284210526316,
 72.70982456140351,
 2.8532089647268557,
 3.8272307692307694,
 0.5815589353612167,
 58.5741935483871,
 4.6635897435897435,
 1.6944525547445255,
 0.26796536796536796,
 2.3159633027522935,
 12.589879518072289,
 2.5208931419457734,
 1.5028901734104045,
 0.9129411764705883,
 0.0,
 19.853315870937017,
 0.9270588235294117,
 0.7813986013986014,
 92.34400000000001,
 6.853503184713376,
 17.842696629213485,
 0.8334967320261437,
 0.5476673427991886,
 26.080246913580247,
 27.424242424242422,
 1.743486973947896,
 0.508367854183927,
 5.033207547169812,
 1.3362011173184358,
 5.127173542448006,
 1.64989010989011,
 4.072318840579711,
 23.124145077720208,
 8.486962962962963,
 2.9031007751937987,
 13.793584905660378,
 7.808,
 32.65542056074766,
 31.20765957446808,
 0.7690625000000001,
 1.2076398362892224,
 2.3886297376093295,
 0.3921904761904762,
 8.393,
 7.028877005347593,
 6.8657407407407405,
 51.14142857142857,
 26.352564102564102,
 0.0,
 0.14834983498349835,
 1.3318867924528304,
 1.768135593220339,
 4.210886075949367,
 16.412313937753723,
 0.41899441340782123,
 0.9384496124031009,
 4.6396,
 0.6648000000000001,
 14.805353728489484,
 6.282974910394265,
 0.0,
 12.92379421221865,
 5.642553191489362,
 0.3123022847100176,
 4.584470246734398,
 0.19449311639549435,
 0.22995759080500314,
 11.313153724247227,
 31.22596153846154,
 21.28289156626506,
 27.213167923457394,
 44.58065437919703,
 2.210921985815603,
 43.646612466124665,
 3.225970873786408,
 5.103817715406669,
 6.949086161879896,
 1.5685245901639344,
 ...]

In [69]:
percentage2_accurracy = []
for i in abs_value:
    if i > 100: percentage2_accurracy.append(int(i-200))
    else:percentage2_accurracy.append(int(100-i))

count = 0
for i in percentage2_accurracy:
    if  i == 60 or i > 60:
        count+=1
        
display(count/8349*100)  
display(percentage2_accurracy)

90.65756378009343

[41,
 99,
 46,
 93,
 74,
 41,
 77,
 99,
 96,
 96,
 99,
 94,
 92,
 54,
 83,
 94,
 76,
 66,
 82,
 86,
 97,
 98,
 70,
 76,
 86,
 14,
 99,
 96,
 96,
 90,
 94,
 99,
 54,
 53,
 97,
 91,
 99,
 53,
 86,
 77,
 96,
 94,
 84,
 91,
 99,
 99,
 92,
 66,
 93,
 51,
 2,
 88,
 92,
 85,
 81,
 85,
 89,
 99,
 95,
 81,
 96,
 87,
 98,
 88,
 99,
 56,
 78,
 96,
 87,
 81,
 70,
 84,
 86,
 96,
 82,
 98,
 75,
 82,
 95,
 87,
 99,
 45,
 98,
 85,
 77,
 53,
 99,
 74,
 66,
 99,
 77,
 65,
 51,
 91,
 77,
 39,
 54,
 92,
 77,
 93,
 99,
 98,
 96,
 96,
 91,
 82,
 85,
 97,
 -76,
 56,
 96,
 95,
 92,
 99,
 48,
 53,
 77,
 94,
 0,
 97,
 95,
 95,
 2,
 64,
 92,
 85,
 70,
 89,
 96,
 60,
 95,
 94,
 51,
 62,
 71,
 99,
 66,
 95,
 90,
 90,
 90,
 71,
 98,
 63,
 94,
 96,
 86,
 93,
 93,
 93,
 96,
 71,
 98,
 100,
 64,
 99,
 96,
 97,
 93,
 47,
 98,
 83,
 96,
 96,
 99,
 75,
 100,
 99,
 94,
 97,
 94,
 76,
 95,
 97,
 62,
 99,
 95,
 88,
 71,
 99,
 88,
 69,
 97,
 68,
 98,
 93,
 89,
 99,
 98,
 81,
 96,
 94,
 99,
 99,
 91,
 97,
 97,
 85,
 80,
 84,
 100,
 99,
 99,
 23,
 98,
 99,
 92,
 67,
 87,
 79,
 99,
 86,
 96,
 90,
 64,
 99,
 82,
 99,
 99,
 84,
 81,
 98,
 63,
 95,
 69,
 92,
 87,
 95,
 98,
 99,
 96,
 98,
 90,
 98,
 92,
 87,
 82,
 67,
 94,
 98,
 79,
 95,
 90,
 91,
 99,
 70,
 87,
 46,
 98,
 69,
 98,
 91,
 76,
 99,
 98,
 15,
 94,
 82,
 74,
 91,
 97,
 97,
 78,
 99,
 73,
 76,
 35,
 97,
 98,
 54,
 98,
 56,
 56,
 66,
 74,
 99,
 99,
 99,
 68,
 98,
 99,
 90,
 86,
 83,
 81,
 75,
 87,
 97,
 90,
 99,
 88,
 85,
 92,
 89,
 99,
 69,
 90,
 73,
 94,
 91,
 97,
 93,
 95,
 56,
 97,
 87,
 85,
 95,
 69,
 70,
 96,
 99,
 67,
 99,
 96,
 98,
 77,
 88,
 95,
 89,
 88,
 96,
 83,
 38,
 77,
 69,
 97,
 92,
 98,
 -95,
 90,
 94,
 90,
 40,
 95,
 99,
 73,
 79,
 77,
 90,
 96,
 77,
 99,
 79,
 92,
 99,
 58,
 97,
 91,
 95,
 93,
 78,
 100,
 54,
 87,
 98,
 99,
 96,
 82,
 92,
 94,
 98,
 93,
 62,
 99,
 96,
 95,
 95,
 -93,
 98,
 84,
 90,
 98,
 93,
 96,
 97,
 72,
 93,
 99,
 99,
 99,
 85,
 85,
 96,
 93,
 88,
 83,
 92,
 87,
 67,
 99,
 93,
 58,
 64,
 37,
 98,
 93,
 74,
 97,
 71,
 94,
 95,
 95,
 88,
 24,
 99,
 96,
 60,
 98,
 99,
 24,
 98,
 97,
 92,
 61,
 92,
 79,
 35,
 -93,
 29,
 30,
 75,
 69,
 99,
 95,
 58,
 99,
 85,
 57,
 96,
 91,
 44,
 82,
 94,
 96,
 99,
 93,
 71,
 94,
 97,
 87,
 97,
 94,
 91,
 80,
 50,
 82,
 92,
 72,
 98,
 95,
 28,
 99,
 97,
 99,
 92,
 95,
 69,
 98,
 94,
 66,
 60,
 92,
 95,
 56,
 93,
 96,
 73,
 98,
 98,
 99,
 98,
 98,
 96,
 84,
 68,
 75,
 85,
 98,
 42,
 98,
 84,
 90,
 97,
 72,
 96,
 96,
 100,
 92,
 98,
 98,
 91,
 75,
 99,
 97,
 91,
 91,
 98,
 87,
 99,
 98,
 97,
 88,
 76,
 97,
 77,
 93,
 93,
 66,
 82,
 27,
 99,
 15,
 99,
 92,
 100,
 94,
 87,
 96,
 72,
 96,
 42,
 88,
 98,
 71,
 99,
 82,
 91,
 94,
 91,
 94,
 97,
 93,
 100,
 66,
 81,
 99,
 95,
 94,
 85,
 71,
 97,
 98,
 97,
 100,
 65,
 98,
 99,
 79,
 94,
 94,
 99,
 99,
 71,
 85,
 70,
 99,
 99,
 75,
 93,
 85,
 89,
 87,
 88,
 77,
 94,
 84,
 71,
 71,
 98,
 99,
 75,
 98,
 94,
 85,
 99,
 99,
 87,
 96,
 90,
 99,
 97,
 99,
 98,
 99,
 80,
 62,
 44,
 98,
 98,
 94,
 94,
 83,
 87,
 90,
 97,
 86,
 29,
 92,
 99,
 99,
 92,
 91,
 83,
 99,
 80,
 98,
 97,
 95,
 91,
 94,
 94,
 34,
 86,
 75,
 94,
 50,
 98,
 97,
 65,
 81,
 44,
 86,
 61,
 91,
 75,
 99,
 96,
 93,
 92,
 93,
 77,
 92,
 93,
 98,
 50,
 99,
 100,
 84,
 75,
 94,
 73,
 83,
 63,
 97,
 94,
 83,
 98,
 95,
 99,
 100,
 90,
 84,
 99,
 87,
 98,
 96,
 99,
 95,
 95,
 99,
 39,
 61,
 92,
 32,
 98,
 91,
 99,
 93,
 94,
 80,
 92,
 -78,
 98,
 93,
 85,
 8,
 98,
 91,
 98,
 90,
 60,
 77,
 99,
 5,
 88,
 94,
 97,
 99,
 80,
 98,
 98,
 87,
 95,
 96,
 100,
 85,
 32,
 94,
 98,
 94,
 97,
 95,
 98,
 60,
 96,
 91,
 72,
 45,
 57,
 92,
 96,
 78,
 98,
 96,
 78,
 95,
 98,
 66,
 94,
 99,
 86,
 95,
 74,
 68,
 49,
 97,
 59,
 98,
 95,
 84,
 97,
 98,
 99,
 93,
 93,
 90,
 87,
 92,
 97,
 93,
 86,
 79,
 24,
 90,
 61,
 32,
 98,
 95,
 85,
 99,
 32,
 94,
 94,
 75,
 84,
 41,
 99,
 96,
 91,
 99,
 21,
 60,
 81,
 97,
 95,
 99,
 72,
 98,
 90,
 90,
 81,
 65,
 93,
 54,
 93,
 90,
 71,
 81,
 97,
 70,
 88,
 100,
 81,
 97,
 74,
 96,
 97,
 89,
 99,
 99,
 98,
 93,
 91,
 83,
 96,
 94,
 48,
 98,
 99,
 76,
 97,
 95,
 100,
 94,
 84,
 96,
 92,
 96,
 90,
 56,
 46,
 56,
 -65,
 78,
 99,
 97,
 99,
 97,
 99,
 99,
 93,
 85,
 72,
 86,
 93,
 44,
 99,
 92,
 97,
 99,
 99,
 100,
 96,
 88,
 75,
 97,
 93,
 81,
 98,
 72,
 100,
 95,
 96,
 97,
 98,
 62,
 93,
 86,
 35,
 74,
 82,
 72,
 66,
 56,
 88,
 98,
 86,
 33,
 100,
 98,
 97,
 97,
 71,
 95,
 99,
 99,
 12,
 96,
 97,
 99,
 94,
 65,
 93,
 90,
 86,
 75,
 100,
 72,
 51,
 87,
 100,
 99,
 92,
 99,
 99,
 99,
 95,
 77,
 96,
 100,
 96,
 77,
 55,
 58,
 96,
 86,
 84,
 84,
 -71,
 96,
 52,
 67,
 85,
 89,
 98,
 96,
 76,
 87,
 90,
 65,
 40,
 68,
 51,
 80,
 74,
 80,
 99,
 29,
 97,
 37,
 96,
 89,
 27,
 97,
 96,
 99,
 41,
 95,
 98,
 99,
 97,
 87,
 97,
 98,
 99,
 100,
 80,
 99,
 99,
 7,
 93,
 82,
 99,
 99,
 73,
 72,
 98,
 99,
 94,
 98,
 94,
 98,
 95,
 76,
 91,
 97,
 86,
 92,
 67,
 68,
 99,
 98,
 97,
 99,
 91,
 92,
 93,
 48,
 73,
 100,
 99,
 98,
 98,
 95,
 83,
 99,
 99,
 95,
 99,
 85,
 93,
 100,
 87,
 94,
 99,
 95,
 99,
 99,
 88,
 68,
 78,
 72,
 55,
 97,
 56,
 96,
 94,
 93,
 98,
 ...]

In [71]:
negative = []
positive = []
for x,i in enumerate(percentage2_accurracy):
    if i >= 70:positive.append(x)
    else:negative.append(x)
%store negative
%store positive

Stored 'negative' (list)
Stored 'positive' (list)

In [64]:
final_percentage_accurracy = []
for i in percentage2_accurracy:
    final_percentage_accurracy.append( '{:d}%'. format(i))
final_percentage_accurracy

['41%',
 '99%',
 '46%',
 '93%',
 '74%',
 '41%',
 '77%',
 '99%',
 '96%',
 '96%',
 '99%',
 '94%',
 '92%',
 '54%',
 '83%',
 '94%',
 '76%',
 '66%',
 '82%',
 '86%',
 '97%',
 '98%',
 '70%',
 '76%',
 '86%',
 '14%',
 '99%',
 '96%',
 '96%',
 '90%',
 '94%',
 '99%',
 '54%',
 '53%',
 '97%',
 '91%',
 '99%',
 '53%',
 '86%',
 '77%',
 '96%',
 '94%',
 '84%',
 '91%',
 '99%',
 '99%',
 '92%',
 '66%',
 '93%',
 '51%',
 '2%',
 '88%',
 '92%',
 '85%',
 '81%',
 '85%',
 '89%',
 '99%',
 '95%',
 '81%',
 '96%',
 '87%',
 '98%',
 '88%',
 '99%',
 '56%',
 '78%',
 '96%',
 '87%',
 '81%',
 '70%',
 '84%',
 '86%',
 '96%',
 '82%',
 '98%',
 '75%',
 '82%',
 '95%',
 '87%',
 '99%',
 '45%',
 '98%',
 '85%',
 '77%',
 '53%',
 '99%',
 '74%',
 '66%',
 '99%',
 '77%',
 '65%',
 '51%',
 '91%',
 '77%',
 '39%',
 '54%',
 '92%',
 '77%',
 '93%',
 '99%',
 '98%',
 '96%',
 '96%',
 '91%',
 '82%',
 '85%',
 '97%',
 '-76%',
 '56%',
 '96%',
 '95%',
 '92%',
 '99%',
 '48%',
 '53%',
 '77%',
 '94%',
 '0%',
 '97%',
 '95%',
 '95%',
 '2%',
 '64%',
 '92%',
 '85%',
 '70%',
 '89%',
 '96%',
 '60%',
 '95%',
 '94%',
 '51%',
 '62%',
 '71%',
 '99%',
 '66%',
 '95%',
 '90%',
 '90%',
 '90%',
 '71%',
 '98%',
 '63%',
 '94%',
 '96%',
 '86%',
 '93%',
 '93%',
 '93%',
 '96%',
 '71%',
 '98%',
 '100%',
 '64%',
 '99%',
 '96%',
 '97%',
 '93%',
 '47%',
 '98%',
 '83%',
 '96%',
 '96%',
 '99%',
 '75%',
 '100%',
 '99%',
 '94%',
 '97%',
 '94%',
 '76%',
 '95%',
 '97%',
 '62%',
 '99%',
 '95%',
 '88%',
 '71%',
 '99%',
 '88%',
 '69%',
 '97%',
 '68%',
 '98%',
 '93%',
 '89%',
 '99%',
 '98%',
 '81%',
 '96%',
 '94%',
 '99%',
 '99%',
 '91%',
 '97%',
 '97%',
 '85%',
 '80%',
 '84%',
 '100%',
 '99%',
 '99%',
 '23%',
 '98%',
 '99%',
 '92%',
 '67%',
 '87%',
 '79%',
 '99%',
 '86%',
 '96%',
 '90%',
 '64%',
 '99%',
 '82%',
 '99%',
 '99%',
 '84%',
 '81%',
 '98%',
 '63%',
 '95%',
 '69%',
 '92%',
 '87%',
 '95%',
 '98%',
 '99%',
 '96%',
 '98%',
 '90%',
 '98%',
 '92%',
 '87%',
 '82%',
 '67%',
 '94%',
 '98%',
 '79%',
 '95%',
 '90%',
 '91%',
 '99%',
 '70%',
 '87%',
 '46%',
 '98%',
 '69%',
 '98%',
 '91%',
 '76%',
 '99%',
 '98%',
 '15%',
 '94%',
 '82%',
 '74%',
 '91%',
 '97%',
 '97%',
 '78%',
 '99%',
 '73%',
 '76%',
 '35%',
 '97%',
 '98%',
 '54%',
 '98%',
 '56%',
 '56%',
 '66%',
 '74%',
 '99%',
 '99%',
 '99%',
 '68%',
 '98%',
 '99%',
 '90%',
 '86%',
 '83%',
 '81%',
 '75%',
 '87%',
 '97%',
 '90%',
 '99%',
 '88%',
 '85%',
 '92%',
 '89%',
 '99%',
 '69%',
 '90%',
 '73%',
 '94%',
 '91%',
 '97%',
 '93%',
 '95%',
 '56%',
 '97%',
 '87%',
 '85%',
 '95%',
 '69%',
 '70%',
 '96%',
 '99%',
 '67%',
 '99%',
 '96%',
 '98%',
 '77%',
 '88%',
 '95%',
 '89%',
 '88%',
 '96%',
 '83%',
 '38%',
 '77%',
 '69%',
 '97%',
 '92%',
 '98%',
 '-95%',
 '90%',
 '94%',
 '90%',
 '40%',
 '95%',
 '99%',
 '73%',
 '79%',
 '77%',
 '90%',
 '96%',
 '77%',
 '99%',
 '79%',
 '92%',
 '99%',
 '58%',
 '97%',
 '91%',
 '95%',
 '93%',
 '78%',
 '100%',
 '54%',
 '87%',
 '98%',
 '99%',
 '96%',
 '82%',
 '92%',
 '94%',
 '98%',
 '93%',
 '62%',
 '99%',
 '96%',
 '95%',
 '95%',
 '-93%',
 '98%',
 '84%',
 '90%',
 '98%',
 '93%',
 '96%',
 '97%',
 '72%',
 '93%',
 '99%',
 '99%',
 '99%',
 '85%',
 '85%',
 '96%',
 '93%',
 '88%',
 '83%',
 '92%',
 '87%',
 '67%',
 '99%',
 '93%',
 '58%',
 '64%',
 '37%',
 '98%',
 '93%',
 '74%',
 '97%',
 '71%',
 '94%',
 '95%',
 '95%',
 '88%',
 '24%',
 '99%',
 '96%',
 '60%',
 '98%',
 '99%',
 '24%',
 '98%',
 '97%',
 '92%',
 '61%',
 '92%',
 '79%',
 '35%',
 '-93%',
 '29%',
 '30%',
 '75%',
 '69%',
 '99%',
 '95%',
 '58%',
 '99%',
 '85%',
 '57%',
 '96%',
 '91%',
 '44%',
 '82%',
 '94%',
 '96%',
 '99%',
 '93%',
 '71%',
 '94%',
 '97%',
 '87%',
 '97%',
 '94%',
 '91%',
 '80%',
 '50%',
 '82%',
 '92%',
 '72%',
 '98%',
 '95%',
 '28%',
 '99%',
 '97%',
 '99%',
 '92%',
 '95%',
 '69%',
 '98%',
 '94%',
 '66%',
 '60%',
 '92%',
 '95%',
 '56%',
 '93%',
 '96%',
 '73%',
 '98%',
 '98%',
 '99%',
 '98%',
 '98%',
 '96%',
 '84%',
 '68%',
 '75%',
 '85%',
 '98%',
 '42%',
 '98%',
 '84%',
 '90%',
 '97%',
 '72%',
 '96%',
 '96%',
 '100%',
 '92%',
 '98%',
 '98%',
 '91%',
 '75%',
 '99%',
 '97%',
 '91%',
 '91%',
 '98%',
 '87%',
 '99%',
 '98%',
 '97%',
 '88%',
 '76%',
 '97%',
 '77%',
 '93%',
 '93%',
 '66%',
 '82%',
 '27%',
 '99%',
 '15%',
 '99%',
 '92%',
 '100%',
 '94%',
 '87%',
 '96%',
 '72%',
 '96%',
 '42%',
 '88%',
 '98%',
 '71%',
 '99%',
 '82%',
 '91%',
 '94%',
 '91%',
 '94%',
 '97%',
 '93%',
 '100%',
 '66%',
 '81%',
 '99%',
 '95%',
 '94%',
 '85%',
 '71%',
 '97%',
 '98%',
 '97%',
 '100%',
 '65%',
 '98%',
 '99%',
 '79%',
 '94%',
 '94%',
 '99%',
 '99%',
 '71%',
 '85%',
 '70%',
 '99%',
 '99%',
 '75%',
 '93%',
 '85%',
 '89%',
 '87%',
 '88%',
 '77%',
 '94%',
 '84%',
 '71%',
 '71%',
 '98%',
 '99%',
 '75%',
 '98%',
 '94%',
 '85%',
 '99%',
 '99%',
 '87%',
 '96%',
 '90%',
 '99%',
 '97%',
 '99%',
 '98%',
 '99%',
 '80%',
 '62%',
 '44%',
 '98%',
 '98%',
 '94%',
 '94%',
 '83%',
 '87%',
 '90%',
 '97%',
 '86%',
 '29%',
 '92%',
 '99%',
 '99%',
 '92%',
 '91%',
 '83%',
 '99%',
 '80%',
 '98%',
 '97%',
 '95%',
 '91%',
 '94%',
 '94%',
 '34%',
 '86%',
 '75%',
 '94%',
 '50%',
 '98%',
 '97%',
 '65%',
 '81%',
 '44%',
 '86%',
 '61%',
 '91%',
 '75%',
 '99%',
 '96%',
 '93%',
 '92%',
 '93%',
 '77%',
 '92%',
 '93%',
 '98%',
 '50%',
 '99%',
 '100%',
 '84%',
 '75%',
 '94%',
 '73%',
 '83%',
 '63%',
 '97%',
 '94%',
 '83%',
 '98%',
 '95%',
 '99%',
 '100%',
 '90%',
 '84%',
 '99%',
 '87%',
 '98%',
 '96%',
 '99%',
 '95%',
 '95%',
 '99%',
 '39%',
 '61%',
 '92%',
 '32%',
 '98%',
 '91%',
 '99%',
 '93%',
 '94%',
 '80%',
 '92%',
 '-78%',
 '98%',
 '93%',
 '85%',
 '8%',
 '98%',
 '91%',
 '98%',
 '90%',
 '60%',
 '77%',
 '99%',
 '5%',
 '88%',
 '94%',
 '97%',
 '99%',
 '80%',
 '98%',
 '98%',
 '87%',
 '95%',
 '96%',
 '100%',
 '85%',
 '32%',
 '94%',
 '98%',
 '94%',
 '97%',
 '95%',
 '98%',
 '60%',
 '96%',
 '91%',
 '72%',
 '45%',
 '57%',
 '92%',
 '96%',
 '78%',
 '98%',
 '96%',
 '78%',
 '95%',
 '98%',
 '66%',
 '94%',
 '99%',
 '86%',
 '95%',
 '74%',
 '68%',
 '49%',
 '97%',
 '59%',
 '98%',
 '95%',
 '84%',
 '97%',
 '98%',
 '99%',
 '93%',
 '93%',
 '90%',
 '87%',
 '92%',
 '97%',
 '93%',
 '86%',
 '79%',
 '24%',
 '90%',
 '61%',
 '32%',
 '98%',
 '95%',
 '85%',
 '99%',
 '32%',
 '94%',
 '94%',
 '75%',
 '84%',
 '41%',
 '99%',
 '96%',
 '91%',
 '99%',
 '21%',
 '60%',
 '81%',
 '97%',
 '95%',
 '99%',
 '72%',
 '98%',
 '90%',
 '90%',
 '81%',
 '65%',
 '93%',
 '54%',
 '93%',
 '90%',
 '71%',
 '81%',
 '97%',
 '70%',
 '88%',
 '100%',
 '81%',
 '97%',
 '74%',
 '96%',
 '97%',
 '89%',
 '99%',
 '99%',
 '98%',
 '93%',
 '91%',
 '83%',
 '96%',
 '94%',
 '48%',
 '98%',
 '99%',
 '76%',
 '97%',
 '95%',
 '100%',
 '94%',
 '84%',
 '96%',
 '92%',
 '96%',
 '90%',
 '56%',
 '46%',
 '56%',
 '-65%',
 '78%',
 '99%',
 '97%',
 '99%',
 '97%',
 '99%',
 '99%',
 '93%',
 '85%',
 '72%',
 '86%',
 '93%',
 '44%',
 '99%',
 '92%',
 '97%',
 '99%',
 '99%',
 '100%',
 '96%',
 '88%',
 '75%',
 '97%',
 '93%',
 '81%',
 '98%',
 '72%',
 '100%',
 '95%',
 '96%',
 '97%',
 '98%',
 '62%',
 '93%',
 '86%',
 '35%',
 '74%',
 '82%',
 '72%',
 '66%',
 '56%',
 '88%',
 '98%',
 '86%',
 '33%',
 '100%',
 '98%',
 '97%',
 '97%',
 '71%',
 '95%',
 '99%',
 '99%',
 '12%',
 '96%',
 '97%',
 '99%',
 '94%',
 '65%',
 '93%',
 '90%',
 '86%',
 '75%',
 '100%',
 '72%',
 '51%',
 '87%',
 '100%',
 '99%',
 '92%',
 '99%',
 '99%',
 '99%',
 '95%',
 '77%',
 '96%',
 '100%',
 '96%',
 '77%',
 '55%',
 '58%',
 '96%',
 '86%',
 '84%',
 '84%',
 '-71%',
 '96%',
 '52%',
 '67%',
 '85%',
 '89%',
 '98%',
 '96%',
 '76%',
 '87%',
 '90%',
 '65%',
 '40%',
 '68%',
 '51%',
 '80%',
 '74%',
 '80%',
 '99%',
 '29%',
 '97%',
 '37%',
 '96%',
 '89%',
 '27%',
 '97%',
 '96%',
 '99%',
 '41%',
 '95%',
 '98%',
 '99%',
 '97%',
 '87%',
 '97%',
 '98%',
 '99%',
 '100%',
 '80%',
 '99%',
 '99%',
 '7%',
 '93%',
 '82%',
 '99%',
 '99%',
 '73%',
 '72%',
 '98%',
 '99%',
 '94%',
 '98%',
 '94%',
 '98%',
 '95%',
 '76%',
 '91%',
 '97%',
 '86%',
 '92%',
 '67%',
 '68%',
 '99%',
 '98%',
 '97%',
 '99%',
 '91%',
 '92%',
 '93%',
 '48%',
 '73%',
 '100%',
 '99%',
 '98%',
 '98%',
 '95%',
 '83%',
 '99%',
 '99%',
 '95%',
 '99%',
 '85%',
 '93%',
 '100%',
 '87%',
 '94%',
 '99%',
 '95%',
 '99%',
 '99%',
 '88%',
 '68%',
 '78%',
 '72%',
 '55%',
 '97%',
 '56%',
 '96%',
 '94%',
 '93%',
 '98%',
 ...]

In [65]:
house_info

,Bedrooms,Bathrooms,Floors,Year Built,Year Renoveted,Size of Basement,Condition,Size of Above,Location,Price,Sqft_living,Sqft_lot,Sqft_basement
0,3,1.00,1.0,1955,0.0,0.0,3,1180,98178,221900.0,1180,5650,0.0
1,3,2.25,2.0,1951,1991.0,400.0,3,2170,98125,538000.0,2570,7242,400.0
2,2,1.00,1.0,1933,NaN,0.0,3,770,98028,180000.0,770,10000,0.0
3,4,3.00,1.0,1965,0.0,910.0,5,1050,98136,604000.0,1960,5000,910.0
4,3,2.00,1.0,1987,0.0,0.0,3,1680,98074,510000.0,1680,8080,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,3,2.50,3.0,2009,0.0,0.0,3,1530,98103,360000.0,1530,1131,0.0
21593,4,2.50,2.0,2014,0.0,0.0,3,2310,98146,400000.0,2310,5813,0.0
21594,2,0.75,2.0,2009,0.0,0.0,3,1020,98144,402101.0,1020,1350,0.0
21595,3,2.50,2.0,2004,0.0,0.0,3,1600,98027,400000.0,1600,2388,0.0
21596,2,0.75,2.0,2008,0.0,0.0,3,1020,98144,325000.0,1020,1076,0.0

In [66]:
house_info1

                Id         Date               Bedrooms              Bathrooms  \
1    A  7129300520   10/13/2014                      3                      1
     B  Regression  Predictions   $210,001  - $633,508    $200,002 - $550,008
     C    Weighted      Average               $522,941               $351,193
2    A  2487200875    12/9/2014                      4                      3
     B  Regression  Predictions  $351,398 - $1,607,982  $536,188 - $1,612,980
...            ...          ...                    ...                    ...
8348 B  Regression  Predictions  $351,398 - $1,607,982    $200,002 - $550,008
     C    Weighted      Average               $724,117               $625,123
8349 A   291310100    1/16/2015                      3                    2.5
     B  Regression  Predictions   $210,001  - $633,508    $200,002 - $550,008
     C    Weighted      Average               $522,941               $625,123

                       Floors             Year Built         Year Renoveted  \
1    A                      1                   1955                      0
     B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
     C               $503,324               $484,755               $600,432
2    A                      1                   1965                      0
     B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
...                       ...                    ...                    ...
8348 B  $340,198 - $1,316,791   $359,232- $1,216,998  $263,411 - $1,322,038
     C               $720,587               $736,528               $600,432
8349 A                      2                   2004                      0
     B  $340,198 - $1,316,791  $361,699 - $1,003,203  $263,411 - $1,322,038
     C               $720,587               $661,901               $600,432

                  Condition         Sqft_living             Sqft_lot
1    A                    3                1180                 5650
     B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
     C             $606,899            $387,403             $528,685
2    A                    5                1960                 5000
     B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
...                     ...                 ...                  ...
8348 B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
     C             $606,899            $678,408             $912,000
8349 A                    3                1600                 2388
     B  $299,999 - $990,999  $336,638- $724,824  $201,558 - $939,876
     C             $606,899            $451,349             $580,000

[25047 rows x 10 columns]

In [67]:
house_predictions = pd.DataFrame({'Id':id,'Date':date,'Bedrooms':bedrooms, 'Bathrooms':bathrooms, 
                           'Floors':floors, 'Year Built':yr_built, 'Year Renoveted':yr_renovated,
            'Condition':condition, 'Sqft_living':sqft_living,'Sqft_lot':sqft_lot,
            'Actual Price':East_Weighted_Average_Amount_of_Bedrooms['Actual Price'],
            'Predicted Price':final_prediction, 
             'Percentage Accuracy':final_percentage_accurracy
                          })
house_predictions

,Id,Date,Bedrooms,Bathrooms,Floors,Year Built,Year Renoveted,Condition,Sqft_living,Sqft_lot,Actual Price,Predicted Price,Percentage Accuracy
0,7129300520,10/13/2014,3,1.0,1.0,1955,0.0,3,1180,5650,"$221,900","$351,193",41%
1,2487200875,12/9/2014,4,3.0,1.0,1965,0.0,5,1960,5000,"$604,000","$600,432",99%
2,2414600126,4/15/2015,3,1.0,1.0,1960,0.0,3,1780,7470,"$229,500","$351,193",46%
3,9297300055,1/24/2015,4,3.0,2.0,1979,0.0,3,2950,5000,"$650,000","$606,899",93%
4,1875500060,7/31/2014,3,2.0,2.0,1994,0.0,3,1890,14040,"$395,000","$496,507",74%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8344,3448900210,10/14/2014,4,2.5,2.0,2014,0.0,3,2520,6023,"$610,685","$610,000",99%
8345,7936000429,3/26/2015,4,3.5,2.0,2009,0.0,3,3510,7200,"$1,010,000","$951,673",94%
8346,2997800021,2/19/2015,3,2.5,2.0,2008,0.0,3,1310,1294,"$475,000","$522,941",89%
8347,6600060120,2/23/2015,4,2.5,2.0,2014,0.0,3,2310,5813,"$400,000","$600,432",49%
8348,291310100,1/16/2015,3,2.5,2.0,2004,0.0,3,1600,2388,"$400,000","$451,349",87%

In [68]:
%store house_predictions

Stored 'house_predictions' (DataFrame)